### DISCUSSION TITLE
Test Data

### DISCUSSION THREAD

**Discussion by cuchakma** [Codeception/Codeception#6131] [General]
while doing automated acceptance testing, suppose if a form data is filled and submitted. now the new test data that are created in the system, get deleted after a few seconds. Can I get a suggestion, on how to store the test data permanantly?

**Comment by c33s** [comment]
would be good to have some details to your config and setup.

but if i assume you use symfony and doctrine and doing a functional test:

`functional.suite.yml`:
```yaml
actor: FunctionalTester
modules:
    enabled:
        - Symfony:
            url: 'http://localhost/'
            app_path: 'src'
            var_path: 'var'
            environment: 'test'
        - Doctrine2:
            depends: Symfony
            cleanup: true # All doctrine queries will be wrapped in a transaction, which will be rolled back at the end of each test
```
there you have the `cleanup` setting. if this is set to true your test database gets cleared for every test. set this to false and the data preserves through the tests.

that said i would like to warn you to do so. having fixtures of tests preserved through multiple tests can have sideeffects. so if a test looks in the database and count the "items" which should be a specific number and another test creates one extra item the test will fail or succseeed if the tests are in the "right" order (first checking for the count, then running the test which creates a new item). your tests should not rely on a specific execution order.

there is even a setting in `codeception.yml` to execute the tests in a different order each time to ensure that the tests do not depend on each other.
```yaml
settings:
    ...
    shuffle: true
    ...
```
if you have fixtures which are the same all the time like the data to fill all "cities" for a dropbox this data can be quite static. you can load it with events https://codeception.com/docs/08-Customization (scroll down to events or use a bundle for it 
https://github.com/liip/LiipTestFixturesBundle/blob/1e0f995a6ad0b87acf77d4950c6196d7809c2f71/doc/database.md#sqlite see "2."
