### DISCUSSION TITLE
Proof of concept multiple test paths

### DISCUSSION THREAD

**Discussion by SamMousa** [Codeception/Codeception#6206] [Ideas]
#### What are you trying to achieve?
I'm trying to run test from an application module (I'm using Yii, but that's not relevant here) from the main application.

Note that this issue is about the specific case where I can and want to reuse the configuration. If you just want to run another `codeception.yml` file the include key works fine.

#### What do you get instead?
If I use the `include` key I have to repeat all the configuration and get stuck with multiple output paths and so on.

### Related issues:
- #319 
- #4827 
- #4122
### Proof of concept
I've created a proof of concept that works, but to implement it properly changes to codeception are needed.
```php
use Codeception\Extension;
use Codeception\SuiteManager;
use Codeception\Test\Cest;
use Codeception\Test\Loader;

class TestExtension extends Extension
{
    public static $events = [
        'suite.before' => 'beforeSuite'
    ];

    public function beforeSuite(\Codeception\Event\SuiteEvent $e)
    {
        /** @var SuiteManager $suiteManager */
        $suiteManager = debug_backtrace(DEBUG_BACKTRACE_PROVIDE_OBJECT + DEBUG_BACKTRACE_IGNORE_ARGS, 4)[3]['object'];
        $method = (new \ReflectionClass($suiteManager))->getMethod('addToSuite');
        $method->setAccessible(true);

        $settings = $e->getSettings();
        foreach($this->config['includePaths'] as $relativePath) {
            $absolutePath = $this->getRootDir() . $relativePath;
            $settings['path'] = $absolutePath;
            $loader = new Loader($settings);
            $loader->loadTests();
            /** @var Cest $test */
            foreach($loader->getTests() as $test) {
                $method->invoke($suiteManager, $test);
            }
        }
    }
}
```

The idea is simple, inside your test suite config you add the include paths for that specific suite, in my case it is the functional test suite.

Before the suite starts the event is triggered and the extension scans the configured paths for additional tests.
The next step is to add the tests to the test suite. The problem here is that the `SuiteManager` does some additional configuration (like configuring the actor class for the test) before adding it to the suite. This means I cannot simply use the `Suite` object given in the event, but really need the manager.

Hack 1: Obtain the suite manager.
By using the `debug_backtrace` function I'm able to obtain a reference to the `SuiteManager` object.

Hack 2: Call protected method.
The `addToSuite` method that I'd like to use is protected and therefore reflection is used to allow me to call it.

### Possible solutions
If we decide we want to allow a plugin to add tests to the suite, several solutions exist.
The simplest is to pass the manager to the event and make the `addToSuite` function public, however this might have cons that I am unaware of.
If, instead of exposing the whole `SuiteManager` object we just want to allow extensions to add tests to a suite, a solution would be to extend the `SuiteEvent` object which can then expose only that functionality. The advantage of this approach is that it is a smaller change to the public API (allowing you to more easily make changes later).

This solution could look like this:
```php
class BeforeSuiteEvent extends SuiteEvent {
    public function __construct(
$suite,
$result = null,
$settings = [],
\Closure $addTest
}

   public function addTestToSuite(Test $test) {
    return call_user_func($this->addTest, $test);
}
````

This allows us to selectively expose functionality via the event without actually passing a reference to the suite manager or requiring changes to function visibility.

**Comment by JackRobbers** [comment]
This would be very useful addition to codeception. The final implementation should also support loading configuration, actor classes, and extensions from the included paths. Tests from included paths should be visible to 'codeception run suitename testname'.

**Comment by DavertMik** [comment]
Good idea but I'm also not so sure how to make this without over complicating things.

I think SuiteManager, as it works now, should not be a part of a public API. So probably we need to expose something more user-friendly. However, I don't know for now how to make it work for all cases you provided. 😶

**Comment by SamMousa** [comment]
@DavertMik Why not add a function to the `SuiteEvent` class? That class is part of the public API, its implementation can be as simple / complicated as you want. The closure example is simple and doesn't require changing the `SuiteManager` public interface.

@JackRobbers why would we need to load configuration / actor classes / extensions from included paths? Isn't that functionality already covered by the current `include:` key for `codeception.yml`?

**Comment by SilverFire** [comment]
Experiencing nearly the same problem. @SamMousa glad to meet you here :)

___

I have a bit different configuration, but the idea and problem are pretty close. I have the following project structure:

```
+
+-+--> Root web-site repository (private) with config and credentials
| |
| |requires modules
| |
| +----> Panel commons (https://github.com/hiqdev/hipanel-core)
| |
| +----> Tickets module (https://github.com/hiqdev/hipanel-module-tickets)
| |
| +----> Domain module (https://github.com/hiqdev/hipanel-module-domain)
| |
| +----> Other modules (https://github.com/hiqdev/hipanel-module-dashboard)
|
+
```

The modules can be optionally installed, but the root repo should be able to run complete tests, w/ tests in modules.

Including tests with `include` option in global configuration is OK to describe where are located the tests I would like to run, but I have problems with sharing testers and suite configuration.

In order to generate WebDriver-related tester actions (such as `saveSessionSnapshot`) I must add WebDriver config (including url and browser) into each suite, making it impossible to change the URL from the root config (am I wrong?). If I don't include the WebDriver module, [ModuleContainer::moduleForAction()](https://github.com/Codeception/Codeception/blob/604e62c191f51363c69246b8082767ca60364ac5/src/Codeception/Lib/ModuleContainer.php#L258) will NOT provide me a `WebDriver` module when tester will ask to `saveSessionSnapshot`.

**Comment by johannesschobel** [comment]
As I see more and more issues with this "tests are scattered all around my project" topic, i strongly believe that this would be a valuable contribution. Maybe this can be fleshed out to a full PR?! 👍

**Comment by SilverFire** [comment]
I have succeeded with it. Will do a pull request and a cookbook article

**Comment by johannesschobel** [comment]
@SilverFire oh man.. that would be so awesome..
Just to be sure.. Am i right, that your PR would allow for the following thing:

1) If you `include` other `codeception.yml` files in your `root codeception.yml` file (as described [in this doc article](https://codeception.com/docs/08-Customization#One-Runner-for-Multiple-Applications) ), all pre-defined values from the `root codeception.yml` file are available in the `module codeception.yml` files. This would allow for "extending" configuration files

2) Same applies to the `xxx.suite.yml` files in the `tests/` folder

If this would work, this would be soooooooooo damn awesome.. because it would help to reduce the amount of configuration you need to do, if all your modules should behave the same way (e.g., you want to have the `parts : orm` and `laravel module` set up the same way.. 

Cheers!

**Comment by SilverFire** [comment]
The answer is "Yes". For making it work in Yii, I have created PR #4961 to respect absolute paths, but for Laravel it may already work. Here is a sort of manual:

1. In the root project (root of modules composition) create `src/config/acceptance.php` with the following settings:

```php
return [
    'PARAMS_LOCATION' => __FILE__,

    // Everything bellow is an example and is not mandatory
    'YII2_CONFIG_LOCATION' => dirname(dirname(__DIR__)) . '/tests/acceptance/config/suite.php',

    'URL' => 'http://local.test.example.com',
    'BROWSER' => 'chrome',

    'client' => [
        'login' => 'test_user@example.com',
        'password' => 'securepass',
    ],
]
```

2. Create `codeception.yml` in your application root:

```yml
namespace: root
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
params:
    - src/config/acceptance.php
include:
    - vendor/acme/mySubmodule
    - vendor/acme/otherCoolSumodule
```

3. Here comes the main trick. In your submodule `mySubmodule` create the following `codeception.yml`:

```php
actor: AcceptanceTester
namespace: acme\mySubmodule\tests
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
params:
    - '%PARAMS_LOCATION%'
    - src/config/submodule-testing-params.php
```

When this submodule is being loaded, the `%PARAMS_LOCATION%` will be substituted with path defined in the root configuration file (see first line in step 1), so properties will be loaded from there. Also you can add additional configs and depending on their order in list they will either override that setting or provide defaults.

Then you can use all the setting in suites wherever they are located:

```yml
actor: AcceptanceTester
namespace: acme\mySubmodules\tests\_support
modules:
    enabled:
        - WebDriver:
            url: '%URL%'
            browser: '%BROWSER%'
        - Yii2:
            part: init
            cleanup: false
            configFile: '%YII2_CONFIG_LOCATION%'
        - \acme\tests\_support\Helper\CredentialsProvider:
            client.login: '%client.login%'
            client.password: '%client.password%'
```

**Comment by johannesschobel** [comment]
Hey @SilverFire ,

thank you for your time to explain respective feature. As far as i understood, this may already work "out of the box" for Laravel, right? Becaues the `params` option is already available..

You may answer another question?
If i correctly understand, you are only "outsourcing" the configuration values (e.g., the URL of the website).. But i want to completely "outsource" the entire configuration file (e.g,. everything that is within the `modules.enabled` config property).

For example, my `functional.suite.yml` in my `User` module looks like this:
```yml
actor: FunctionalTester
modules:
    enabled:
      - Asserts
      - \App\Modules\User\Tests\Helper\Functional
      - Laravel5:
            root: ../../../../
            part: ORM
            environment_file: .env.testing
            run_database_migrations: true
            database_seeder_class: DatabaseSeeder
      - REST:
            depends: Laravel5
```

The `functional.suite.yml` file for my `Authentication` module looks liket his:
```yml
actor: FunctionalTester
modules:
    enabled:
      - Asserts
      - \App\Modules\Authentication\Tests\Helper\Functional
      - Laravel5:
            root: ../../../../
            part: ORM
            environment_file: .env.testing
            run_database_migrations: true
            database_seeder_class: DatabaseSeeder
      - REST:
            depends: Laravel5
```

So my goal is to only have the respective content in the `functional.suite.yml` file of the `User` module:
```yml
modules:
    enabled:
      - \App\Modules\User\Tests\Helper\Functional
```

and move the rest to a `shared configuration` that may be used by all modules:
```yml
actor: FunctionalTester
modules:
    enabled:
      - Asserts
      - Laravel5:
            root: ../../../../
            part: ORM
            environment_file: .env.testing
            run_database_migrations: true
            database_seeder_class: DatabaseSeeder
      - REST:
            depends: Laravel5
```

Is this possible with your approach?!
Cheers and best,
Johannes

**Comment by SilverFire** [comment]
Ehh, no, this is not possible because for isolation purposes each include section is being processed completely separately, so you need to define codeception modules in each extension. With the hack I've posted you can at least have settings (and credentials) stored in a single file outside of the extension.

I have another idea of ugly hack, but I've never tested it. Could you?

1. Added the following props to your config:

```php
return [
    'GLOBAL_MODULES' => '
    enabled:
        - Asserts
        - Laravel5:
            root: ../../../../
            part: ORM
            environment_file: .env.testing
            run_database_migrations: true
            database_seeder_class: DatabaseSeeder
        - REST:
            depends: Laravel5
'
];
```

2. Update your suite config in extension like so:

```yaml
actor: FunctionalTester
modules:
%GLOBAL_MODULES%
```

I guess it should work :)
