### DISCUSSION TITLE
How to run tests in subfolders?

### DISCUSSION THREAD

**Discussion by badmansan** [Codeception/Codeception#6214] [Q&A] [answered]
Hi, I have next structure of tests:
```
tests/acceptance/codeception.yml
tests/acceptance/Test1.php
tests/acceptance/folder1/SomeTest1.php
tests/acceptance/folder1/SomeTest2.php
tests/acceptance/folder2/AnotherSomeTest1.php
tests/acceptance/folder2/AnotherSomeTest2.php
```
tests/acceptance/codeception.yml:
```
paths:
    tests: tests/acceptance
    output: tests/acceptance/_output
    data: tests/acceptance/_data
    support: tests/acceptance/_support
    envs: tests/acceptance/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
bootstrap: bootstrap.php
```
In this case only Test1.php is runing. How can I run all tests, including tests in subfolders?
