### DISCUSSION TITLE
Is it just me or is the Codeception 5 documentation severely lacking and inconsistent?

### DISCUSSION THREAD

**Discussion by Swennet** [Codeception/Codeception#6577] [General]
I've tried installing Codeception 5 into my project and just can't seem to get it to work. Following the installation steps is very confusing, and does not seem to be up to date.

For example, on the [Quickstart](https://codeception.com/quickstart) page, it shows the following config for Acceptance tests:

```
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: {YOUR APP'S URL}
        - Tests\Support\Helper\Acceptance
```

However, then trying to run the tests results in the following error message:

>   Module Tests\Support\Helper\Acceptance could not be found and loaded

Then browsing to the [Getting Started](https://codeception.com/docs/GettingStarted) page in the Docs, it shows more inconsistencies. For example, there the code snippet for configuring Acceptance tests is:

```
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: 'http://myappurl.local'
        - \Helper\Acceptance
```

Note the change in the Acceptance module path. Surprisingly, this config also does not work, and returns the same error.

> Module \Helper\Acceptance could not be found and loaded

I would like to get Codeception 5 working in my project, but so far, I haven't even been able to get the most basic examples working.
