### DISCUSSION TITLE
Codeception $I->see() action doesn't work with WebDriver

### DISCUSSION THREAD

**Discussion by AdamOB1290** [Codeception/Codeception#6585] [Q&A]
The same action works with PhpBrowser but as soon as I set WebDriver in acceptance.suite.yml it throws the following error :

`[PHPUnit\Framework\Exception] Invalid argument supplied for foreach() at vendor/php-webdriver/webdriver/lib/Remote/RemoteWebDriver.php:240`

I followed the documentation for setting up WebDriver with Selenium. Here is what my acceptance.suite.yml looks like:

```
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: '{website url here}'
            browser: chrome
        - \Helper\Acceptance
step_decorators: ~   
```

Here is my acceptance test file:

```
<?php

class FirstAcceptanceCest
{
    public function _before(AcceptanceTester $I)
    {
    }

    public function seeLoginInFrontPage(AcceptanceTester $I)
    {
        $I->amOnPage('/');
        $I->see('Login');
    }
}
```

Any help would be greatly appreciated.
