### DISCUSSION TITLE
Functional test passes locally, fails on CI

### DISCUSSION THREAD

**Discussion by maxxer** [Codeception/Codeception#6619] [Q&A]
I’ve set up testing for an Yii2 app. The test suite (unit and functional) runs fine locally, while it fails when executed via Gitlab CI. It's a single test failing, all the others passes. Additionally, if I run that single test only, it passes on CI!

Codeception is configured to reset DB at each test, so it shouldn't be a problem of bad data. 

```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
bootstrap: _bootstrap.php
settings:
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'config/test.php'
            cleanup: false
            transaction: false
        Db:
            dsn: 'mysql:host=app_db;dbname=app_test'
            user: 'root'
            password: 'password'
            populate: true
            cleanup: true
            dump: tests/_data/app_test.sql
```
The test checks if a list (GridView) contains certain rows, loaded from fixtures. When the test fails on the CI, I see there are two rows in the list of the generated HTML, but they contain no data, as if they're empty db rows.

I ran out of options and I don't know how to further debug this. 

Any hint on what else I can check would be welcome.
thanks

This is the test code:
```php
class EndingEndUserPresenceInStructureCest
{
    public function _before(FunctionalTester $I)
    {
    }

    public function endingEndUserPresenceInStructure(FunctionalTester $I)
    {
        $I->haveFixtures(['user' => UtenteFixture::className()]);
        $I->haveFixtures(['anagrafica' => AnagraficaFixture::className()]);
        $user = $I->grabFixture('user', 'user');
        $I->amLoggedInAs($user->id);
        $I->amOnRoute('anagrafica', ['tipologia' => '9']);
        $I->see('test_struttura', 'td');
        $I->see('Nuova Anagrafica', 'a');
        $enduser1 = $I->grabFixture('anagrafica', 'enduser1');
        $enduser2 = $I->grabFixture('anagrafica', 'enduser2');
        $I->see($enduser1->cognome, 'a');
        $I->see($enduser2->cognome, 'a');
    }
}
```

Running on Codeception v4.2.2, PHPUnit 8.5.31.
