### DISCUSSION TITLE
Sloving: cURL error 7: Failed to connect to HOST port 443

### DISCUSSION THREAD

**Discussion by DavertMik** [Codeception/Codeception#6669] [Cookbook]
Sometimes you may see this error using PhpBrowser module. Please note the 443 port which is mentioned there. It means that request goes by HTTPS protocol. HTTPS is a secure protocol and by default curl tries to verify the host, but it can be problematic for testing. There are [2 curl options](https://web.archive.org/web/20180322224647/http://stackoverflow.com/questions/15135834/php-curl-curlopt-ssl-verifypeer-ignored) which should disabled in order to make such requests pass.

This is how you can do that in PhpBrowser config:

```
        PhpBrowser:
            url: 'https://github.com'
            curl:
              CURLOPT_SSL_VERIFYHOST: false
              CURLOPT_SSL_VERIFYPEER: false
```
