### DISCUSSION TITLE
Make Symfony based client request as before suite in Helper class

### DISCUSSION THREAD

**Discussion by ACooperrr** [Codeception/Codeception#6670] [Cookbook]
Had a problem with making request  in Helper class using REST and Symfony modules in a way to get an open api spec before suite

Codeception 5.0
PHP 8.0

codeception.yaml
```
namespace: App\Tests
bootstrap: bootstrap.php
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
params:
    - .env
    - .env.test
```

Rest.suite.yml
```
actor: RestTester
modules:
    enabled:
        - Symfony:
              app_path: '%APP_PATH%'
              kernel_class: '%KERNEL_CLASS%'
              environment: '%APP_ENV%'
              cache_router: false
              rebootable_client: true
              guard: true
        - REST:
              url: /
              depends: Symfony
        - App\Tests\Helper\Rest
        - Asserts
```

google said Helper class should be something like this
```
class Rest extends Module
{
    use RestAssertsTrait;

    private ValidatorInterface $openApiValidator;

    public function _beforeSuite(array $settings = [])
    {
        /** @var RestTester $I */
        $I = $this->getModule('REST');
        $I->sendGet('/path');

        $this->openApiValidator = ValidatorBuilder::fromJson($I->grabResponse())->getValidator();
    }
}
```
But `$I->sendGet('/path');` -> method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
In InnerBrowser.php line 227

Both modules has no clients at that moment. Clients inits only on _before test steps

Workaround is to setup the client manually
```
/** @var Module\Symfony $symfony */
$symfony = $this->getModule('Symfony');
$client = new Symfony($symfony->kernel, [], $symfony->config['rebootable_client']);
$client->jsonRequest('GET', '/path');
```
