### DISCUSSION TITLE
Incomplete coverage of Acceptance tests but not always.

### DISCUSSION THREAD

**Discussion by Uccio** [Codeception/Codeception#6825] [Q&A]
I am successfully using codeception with code coverage with both xdebug and pcov on a Drupal 10.x project.

However, I have the following problem: If I run my tests on the single test file like:

php vendor/bin/codecept run Acceptance myTestNumberTwoCest.php --coverage --coverage-html
 
**my coverage is complete and is exactly as I expect**.

If on the contrary I launch all tests together in all drupal modules files in paths similar to this are "discarded":

./web/moudules/custom/mymodule/src/Breadcrum/myModuleBreadcrumbBuilder.php

my codeception.yml configuration file is:
```
namespace: Tests
support_namespace: Support
paths:
    tests: tests
    output: tests/_output
    data: tests/Support/Data
    support: tests/Support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
  enabled: true
  show_uncovered: true
  c3_url: 'http://127.0.0.1/drupal10/web'
  include:
    - web/modules/custom/*
  exclude:
    - "web/modules/custom/**/tests/"
```
 and my Aceptance Test conf is:

```
# Codeception Acceptance Test Suite Configuration
#
# Perform tests in a browser by either emulating one using PhpBrowser, or in a real browser using WebDriver.
# If you need both WebDriver and PhpBrowser tests, create a separate suite for each.

actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://127.0.0.1/drupal10/web
        - DrupalBootstrap:
            server:
              SERVER_PORT: null
              REQUEST_URI: '/drupal10/web'
              REMOTE_ADDR: '127.0.0.1'
              HTTP_HOST: 'site.multi'
        - DrupalUser:
              default_role: 'authenticated'
              driver: 'PhpBrowser'
              drush: 'drush'
              cleanup_test: true
              cleanup_failed: false
              cleanup_suite: true

# Add Codeception\Step\Retry trait to AcceptanceTester to enable retries
step_decorators:
    - Codeception\Step\ConditionalAssertion
    - Codeception\Step\TryTo
    - Codeception\Step\Retry
```

I hypothesize that by launching a single test for some reason the configuration is different than for the single test but I don't know some fix the global project coverage that is incomplete.
