### ISSUE TITLE
RC2 : Failed asserting that 'N/A' matches expected 200

### ISSUE THREAD

**Issue by pmcjury** [Codeception/Codeception#1030]
The assertion failed but the output of the status says 200 . This works in 1.8.5

Set up:

```
class_name: ApiGuy
modules:
    enabled: [ApiHelper, PhpBrowser, REST, Symfony2, Db]
    config:
        PhpBrowser:
            url: 'http://localhost/1'
        REST:
            url: 'http://localhost/1'
        Symfony2:
            environment: dev
        Db:
            dsn: 'mysql:host=localhost;dbname=test'
            user: 'test_user'
            password: 'testpass'
            dump: tests/_data/dump.sql
            cleanup: false
            populate: true

```

Output:

```
2) Failed to get api ApiUserCest::getUserTest (/vagrant/tests/api/ApiUserCest.php)
Sorry, I couldn't see response code is 200:
Failed asserting that 'N/A' matches expected 200.

Scenario Steps:
15. I see response code is 200
14. I send get "/user/1

[Request] GET http://172.20.0.15/app_test.php/1/users/1
  [Response] {"errors":[],"data":[{"created_at":"2014-05-22T11:26:32-0400","id":1,"name":"john"}]}
  [Headers] {"server":["nginx\/1.4.1 (Ubuntu)"],"transfer-encoding":["chunked"],"connection":["keep-alive"],"x-powered-by":["PHP\/5.5.3-1ubuntu2.3"],"cache-control":["no-cache"],"date":["Thu, 22 May 2014 15:26:36 GMT"],"content-type":["application\/json"]}
  [Status] 200"

```
