### ISSUE TITLE
[Laravel4] issue with amOnPage and translations

### ISSUE THREAD

**Issue by ludo237** [Codeception/Codeception#1087]
Hello everyone.
I'm using codeception 2.0.0 on Laravel 4.2 project.
I've a bunch of acceptance tests and I can run them without any problem when the `acceptance.suite.yml` is like below

```
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        #- WebDriver
        - AcceptanceHelper
        #- Laravel4
    config:
        PhpBrowser:
            url: 'http://localhost/l4dev/public'
        WebDriver:
            url: 'http://localhost/l4dev/public'
            browser: firefox
        Laravel4:
            cleanup: true
            bootstrap: '../../bootstrap/start.php'
```

For the record I'm using the `Lang::get('')` method from Laravel 4 in order to have a multilingual site and I never had a problem with this, even with the configuration above.
The problem comes when I enable the Laravel4 module and it "collide" with the translator system, in some way that I've to figured it out. In particular this is the exception shown when I run `codecept run` with the Laravel4 module enable

```
[ErrorException] Array to string conversion (View: /Users/Ludo237/Sites/l4dev/app/views/anyview.blade.php)
```

`anyview.blade.php` is just a placeholder because this Exception occurs with whatever view has got even a single `Lang::get()` or `trans()` method.

The strange part is that the `amOnPage` works like a charm when Laravel4 module is disable. I think this is an issue related to Laravel4 module in some way. I will dig into it as soon as possible but maybe someone else has got a fix for this :smile:
