### ISSUE TITLE
Problem w/ API and Codeception 2.x

### ISSUE THREAD

**Issue by mikeerickson** [Codeception/Codeception#1088]
Receiving the following error

```
[Codeception\Exception\ModuleConfig]                                              
  PhpBrowser module is not configured!                                              
  Options: url are required                                                         
                  Please, update the configuration and set all the required fields
```

Here is the api.yml file

```

class_name: ApiTester
modules:
    enabled: [PHPBrowser,REST,ApiHelper,Laravel4]
    config:
        PhpBrowser:
          url: http://rangladex.app:8000/
        REST:
          url: http://rangladex.app:8000/api/v1/

```
