### ISSUE TITLE
PhpBrowser url not being used 

### ISSUE THREAD

**Issue by ghost** [Codeception/Codeception#1118]
I'm using 
Codeception version 1.8.6 and I have the phpbrowser url defined in acceptance.suite.yml and in codeception.yml
my  acceptance.suite.yml is 

```
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
        - Db
        - Symfony2
        - TestHelper
    config:
        PhpBrowser:
            url: 'http://local.domain.de/app_test.php'
        Symfony2:
            app_path: 'app'
            environment: 'test'
```

When I try `$I->amOnPage('/login');`  I get 

```
Acceptance Tests (1) -----------------------------------------
Modules: PhpBrowser, WebHelper, Db, Symfony2, TestHelper
--------------------------------------------------------------
Trying to test the friends (FriendCest.friendTest)
Scenario:
* I expect to login
* I am on page "login"
  [Page] http://localhost/login
...
```

This only started to happen after I enabled Symfony2 module, I looked the configuration but there is no url parameter in Symfony2. 
Is there something I can do to fix this?
