### ISSUE TITLE
Set WebDriver capability "firefox_profile"

### ISSUE THREAD

**Issue by pablopaul** [Codeception/Codeception#1188]
Hei,

I want to use the WebDriver module with a given firefox browser profile to "disable" the file download dialog and save downloads to a specified location, but I do not know how to include the base64 encoded firefox profile in the suite configuration file, basically the structure should look like

``` yml
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
    config:
        WebDriver:
            url: 'http://'
            browser: firefox
            capabilities:
                firefox_profile: base64 encoded firefox profile here
```

If I just paste the bas64 string in the configuration file the following error get thrown

``` php
 [Symfony\Component\Yaml\Exception\ParseException]
 Unable to parse in "\tests\acceptance.suite.yml" at line 24 (near "AwQUAAAACACjVdhEmhfBLlgzAAAMygEAIwAAAGIwbnh3d3l6LmNvZGVjZXB0aW9uMi9ibG9j").
```

I "patched" the file Module/WebDriver.php and added the following line in the "_initialize function"

``` php
$this->capabilities['firefox_profile'] = file_get_contents("profile.zip.b64");
```

which basically works but is not the prefered way…

Can you please give me a concrete example how to load the nested WebDriver configuration from AccceptanceHelper class, thanks a lot!

---

Commands on Mac to build base64 encoded firefox profile

``` terminal
cd ~/Library/Application Support/Firefox/Profiles/PROFILE-NAME
zip -r profile *
openssl base64 -in profile.zip -out profile.zip.b64
```

---

References:
http://codeception.com/docs/modules/WebDriver
https://code.google.com/p/selenium/wiki/DesiredCapabilities
http://stackoverflow.com/a/7549723

**Comment by burzum** [comment]
When I try to do what is suggested above I'm ending up with

> 1) CompanyRegistrationCept: Login from the landing page /en
 Test  codeception\acceptance\Users\CompanyRegistrationCept.php

>  [RuntimeException] Call to undefined method AcceptanceTester::amOnPage

This is my confic
```
class_name: AcceptanceTester
modules:
    enabled:
        - Helper\Acceptance
    config:
        AcceptanceHelper:
            browser: firefox
            window_size: 1280x900
            url: 'http://localhost:3000'
```

Codeception PHP Testing Framework v2.2.6
Powered by PHPUnit 5.6.2 by Sebastian Bergmann and contributors.

**Comment by Naktibalda** [comment]
@burzum your naming is inconsistent - `Helper\Acceptance` and `AcceptanceHelper`, please use the same name in both places.

**Comment by burzum** [comment]
@Naktibalda OK, but I'm still getting the same error message.

**Comment by Naktibalda** [comment]
Does your helper extend WebDriver as suggested by https://github.com/Codeception/Codeception/issues/1188#issuecomment-48525310 ?

**Comment by burzum** [comment]
I'm getting all kinds of errors not matter what I try to do. Getting this FF crap to work is a pain... :( 

```
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://localhost:3000
            browser: firefox
        #    # You can use $I->resizeWindow(1024, 768); to change it at runtime
        #    window_size: 1280x900
        #    clear_cookies: true
        #- PhpBrowser:
        #    url: http://localhost:3000
        - Helper\Acceptance
        - Helper\Select2
    config:
        Helper\Acceptance:
            browser: firefox
            window_size: 1280x900
            url: 'http://localhost:3000'
```

```php
<?php
namespace Helper;

// here you can define custom actions
// all public methods declared in helper class will be available in $I

class Acceptance extends \Codeception\Module {

	public function _initialize() {
		$ds = DIRECTORY_SEPARATOR;
		$profilePath = __DIR__ . $ds . '..' . $ds . '..' . $ds . '_data' . $ds . 'profile.zip.b64';

		$this->wd_host = sprintf('http://%s:%s/wd/hub', $this->config['host'], $this->config['port']);
		$this->capabilities = $this->config['capabilities'];
		$this->capabilities[\WebDriverCapabilityType::BROWSER_NAME] = $this->config['browser'];
		$this->capabilities['firefox_profile'] = file_get_contents($profilePath);
		$this->webDriver = \RemoteWebDriver::create($this->wd_host, $this->capabilities);
		$this->webDriver->manage()->timeouts()->implicitlyWait($this->config['wait']);
		$this->initialWindowSize();
	}
}
```

```sh
Codeception PHP Testing Framework v2.2.6
Powered by PHPUnit 5.6.2 by Sebastian Bergmann and contributors.

Notice: Undefined index: host in C:\xampp\htdocs\wa3\codeception\_support\Helper\Acceptance.php on line 13

Call Stack:
    0.0002     140152   1. {main}() C:\xampp\htdocs\wa3\vendor\codeception\codeception\codecept:0
    0.0850    6221304   2. Codeception\Application->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\codecept:33
    0.0850    6221440   3. Symfony\Component\Console\Application->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Application.php:103
    0.0889    6408400   4. Symfony\Component\Console\Application->doRun() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:118
    0.0892    6408888   5. Symfony\Component\Console\Application->doRunCommand() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:187
    0.0892    6409168   6. Symfony\Component\Console\Command\Command->run() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:820
    0.0900    6412288   7. Codeception\Command\Run->execute() C:\xampp\htdocs\wa3\vendor\symfony\console\Command\Command.php:256
    0.1455    7459200   8. Codeception\Codecept->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Command\Run.php:281
    0.1534    7463464   9. Codeception\Codecept->runSuite() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Codecept.php:178
    0.1679    8342336  10. Codeception\SuiteManager->initialize() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Codecept.php:207
    0.1697    8352464  11. Helper\Acceptance->_initialize() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\SuiteManager.php:81


Notice: Undefined index: port in C:\xampp\htdocs\wa3\codeception\_support\Helper\Acceptance.php on line 13

Call Stack:
    0.0002     140152   1. {main}() C:\xampp\htdocs\wa3\vendor\codeception\codeception\codecept:0
    0.0850    6221304   2. Codeception\Application->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\codecept:33
    0.0850    6221440   3. Symfony\Component\Console\Application->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Application.php:103
    0.0889    6408400   4. Symfony\Component\Console\Application->doRun() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:118
    0.0892    6408888   5. Symfony\Component\Console\Application->doRunCommand() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:187
    0.0892    6409168   6. Symfony\Component\Console\Command\Command->run() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:820
    0.0900    6412288   7. Codeception\Command\Run->execute() C:\xampp\htdocs\wa3\vendor\symfony\console\Command\Command.php:256
    0.1455    7459200   8. Codeception\Codecept->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Command\Run.php:281
    0.1534    7463464   9. Codeception\Codecept->runSuite() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Codecept.php:178
    0.1679    8342336  10. Codeception\SuiteManager->initialize() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Codecept.php:207
    0.1697    8352464  11. Helper\Acceptance->_initialize() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\SuiteManager.php:81


Notice: Undefined index: capabilities in C:\xampp\htdocs\wa3\codeception\_support\Helper\Acceptance.php on line 14

Call Stack:
    0.0002     140152   1. {main}() C:\xampp\htdocs\wa3\vendor\codeception\codeception\codecept:0
    0.0850    6221304   2. Codeception\Application->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\codecept:33
    0.0850    6221440   3. Symfony\Component\Console\Application->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Application.php:103
    0.0889    6408400   4. Symfony\Component\Console\Application->doRun() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:118
    0.0892    6408888   5. Symfony\Component\Console\Application->doRunCommand() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:187
    0.0892    6409168   6. Symfony\Component\Console\Command\Command->run() C:\xampp\htdocs\wa3\vendor\symfony\console\Application.php:820
    0.0900    6412288   7. Codeception\Command\Run->execute() C:\xampp\htdocs\wa3\vendor\symfony\console\Command\Command.php:256
    0.1455    7459200   8. Codeception\Codecept->run() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Command\Run.php:281
    0.1534    7463464   9. Codeception\Codecept->runSuite() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Codecept.php:178
    0.1679    8342336  10. Codeception\SuiteManager->initialize() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\Codecept.php:207
    0.1697    8352464  11. Helper\Acceptance->_initialize() C:\xampp\htdocs\wa3\vendor\codeception\codeception\src\Codeception\SuiteManager.php:81


  [Facebook\WebDriver\Exception\WebDriverException]
  JSON decoding of remote response failed.
  Error code: 4
  The response: '<html>
  <head><title>400 Bad Request</title></head>
  <body bgcolor="white">
  <center><h1>400 Bad Request</h1></center>
  <hr><center>nginx/1.9.2</center>
  </body>
  </html>'
```
