### ISSUE TITLE
WebDriver + PhantomJS - Coverage

### ISSUE THREAD

**Issue by aewing** [Codeception/Codeception#1195]
I'm running some acceptance tests via WebDriver + PhantomJS and I would like to get some sort of coverage reports for my tests. Reading through the docs I am given the impression that this should work, but I can't seem to get the coverage reports to see any of my code.

I have tried whitelisting and configuring the coverage in both codeception.yml and acceptance.suite.yml like so:

``` yml
coverage:
    enabled: true
    remote: true
    whitelist:
        include:
          - app/models/*
          - app/views/*
          - app/controllers/*
```

But to no avail. The end result is always the same; Several tests run successfully, but cover no code:

```
Code Coverage Report:  
  2014-07-10 18:11:10  

 Summary:              
  Classes:        (0/0)
  Methods:        (0/0)
  Lines:          (0/0)
```

Might I be doing something wrong, or is coverage with acceptance tests not possible?
