### ISSUE TITLE
Running acceptance tests of HTTP auth protected site

### ISSUE THREAD

**Issue by vojtech-dobes** [Codeception/Codeception#1202]
I have found out that one can specify username and password for `PhpBrowser`, but is it possible something similar with `WebDriver`, ideally `phantomjs`? Thanks for any suggestions in advance!

**Comment by vml-rmott** [comment]
Embedding the username and password in the url almost worked for me, but as soon as the script clicked on another link the run died with error `[WebDriverCurlException] Curl error thrown for http POST to /session/.../click with params...` and `Operation timed out after 300001 milliseconds with 0 bytes received`.

Adding the `phantomjs.page.customHeaders.Authorization` config as shown by @splinter89 seems to be the only way to fix my issue short of dropping basic auth on the site under test.  Would be great if the error message could be improved or this documented better, but that might be a Facebook problem?

**Comment by paulsheldrake** [comment]
I'm using codeception 2.1.2 and phantomjs 1.9.8.   This works for me

        WebDriver:
            url: 'http://user:pass@example.com/'
            browser: phantomjs
            window_size: 1024x768
            restart: true

**Comment by slowkow** [comment]
Putting the user and pass into the URL does not work for me. The browser just sits there at the password prompt.

I'm using codeception 2.2.5 and Chrome.

Here's my `tests/acceptance.suite.yml`:

```yaml
class_name: AcceptanceTester
  modules:
      enabled:
          - \Helper\Acceptance
          - WebDriver:
              url: 'https://user:pass@example.net'
              host: 'slowkow:pass@testrunner.com'
              port: 80
              browser: chrome
              capabilities:
                  platform: 'Windows 10'
              connection_timeout: 60
              request_timeout: 60
```
