### ISSUE TITLE
ERROR No code coverage driver available

### ISSUE THREAD

**Issue by marcioAlmada** [Codeception/Codeception#1207]
When I try to run tests with coverage enabled `codecept run unit --coverage --coverage-html` I get the following error output:

```
[PHP_CodeCoverage_Exception]
No code coverage driver available 
```

Configuration:

``` yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Db: ...
coverage:
    enabled: true
    include:
        - app/*
    exclude:
        - app/storage/*
```

Am I doing something wrong?
