### ISSUE TITLE
SSL issue with PhantomJS and Selenium

### ISSUE THREAD

**Issue by alairock** [Codeception/Codeception#1220]
Phantom/Selenium stalls when I go to an uncertified SSL site. Here is my test.
```
$I->wantTo('Test SSL page open');
$I->amOnPage('/');
```
Here is my configuration

```
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
    config:
        WebDriver:
            url: 'https://dryearth.com/'
            browser: phantomjs
            window_size: 1024x768
            capabilities:
                unexpectedAlertBehaviour: 'accept'
```

Using
- Selenium server 2.30.0 
- PhantomJS 1.9.0
- Codecept 2.0.2
