### ISSUE TITLE
Can't run full suite with coverage without c3.php even if acceptance coverage disabled

### ISSUE THREAD

**Issue by precariouspanther** [Codeception/Codeception#1249]
For our purposes we want to run all three suites of tests (unit, functional, acceptance) and at the same time generate coverage reports for the unit and functional tests.

However, even if we explicitly disable coverage in the acceptance suite:

```
class_name: AcceptanceTester
modules:
  enabled:
    - WebDriver
  config:
    WebDriver:
      url: 'http://app.dev'
      host: 'localhost'
      port: '9988'
      browser: 'phantomjs'
coverage:
    enabled: false
    remote: false
```

Codeception ignores this and tries to run the coverage for the acceptance tests anyway, causing a 404 exception to be thrown when Codeception cant connect to c3.php (we do not wish to include this in the application). We are running the suites with:

```
vendor/bin/codecept run --coverage-html -xml -d
```

However, if we leave off the --coverage-html flag coverage isn't generated for the Unit/Functional suites even if they explicitly enable them in their individual suite configs.

We have tried various combinations of configuration options (specifying remote:false in the global codeception.yml, etc) but can't get this to work without modifying codeception to completely remove the LocalServer coverage functionality.

Is there some configuration we're missing or using incorrectly, or can you add the ability to specifically disable coverage for acceptance test whilst still preserving the feature for Unit and Functional tests? Older versions of Codeception allowed us to do this before the new C3 feature was added.

Thanks.
