### ISSUE TITLE
Zombiejs not working I think

### ISSUE THREAD

**Issue by sabmark** [Codeception/Codeception#127]
I can't get Zombiejs to work. When I fill some fields and click some link, it can't see element on the resulting page, its like its stuck on the initial page ($I->amOnPage('/');)

acceptance.suite.yml

```
class_name: WebGuy
modules:
    enabled: [WebHelper, Zombiejs]
    config:
        Zombiejs:
            url: 'http://www.somedomain.com/'
```

does anyone have sample test that works?
