### ISSUE TITLE
Acceptance test: InvalidArgumentException: The current node list is empty.

### ISSUE THREAD

**Issue by hgraca** [Codeception/Codeception#1282]
Hi,

I am starting to create acceptance tests for a project running on PHP 5.3 and using Codeception v1.8.7.
my first test is very simple, and using phpBrowser, but it fails:

``` php
<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('go to the admin area');
$I->amOnPage('/admin');
$I->see('Broadcaster List');
```

This is what happens when I run it:

``` bash
php bin/codecept run acceptance
Codeception PHP Testing Framework v1.8.7
Powered by PHPUnit 3.7.37 by Sebastian Bergmann.

Acceptance Tests (1) ----------------------------------------
Trying to login to the admin area (loginCept.php)       Error
-------------------------------------------------------------


Time: 1.97 seconds, Memory: 21.00Mb

There was 1 error:

---------
1) Failed to login to the admin area in loginCept.php
Sorry, I couldn't see "Broadcaster List":
InvalidArgumentException: The current node list is empty.

Scenario Steps:
2. I see "Broadcaster List"
1. I am on page "/admin"

#1  /var/www/evp/vendor/behat/mink-browserkit-driver/src/Behat/Mink/Driver/BrowserKitDriver.php:348
#2  /var/www/evp/vendor/behat/mink/src/Behat/Mink/Element/Element.php:101
#3  /var/www/evp/tests/acceptance/AcceptanceTester.php:838
#4  /var/www/evp/tests/acceptance/loginCept.php:8

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```

however, when I go check the log to see what phpBrowser received, it has the correct page with the required text in it.

Also, if I change the test so that it tests if www.google.com has the word 'Google' in it, it works fine.

This is the config file for the suite:

``` yaml
class_name: AcceptanceTester
modules:
    enabled: [Db, PhpBrowser, AcceptanceHelper]
    config:
        PhpBrowser:
            url: http://evp/app_test.php
            curl:
                CURLOPT_RETURNTRANSFER: true
                CURLOPT_FOLLOWLOCATION: true
                CURLOPT_COOKIEFILE: './cookies.txt'
                CURLOPT_COOKIEJAR: './cookies.txt'
        Db:
            dsn: 'mysql:host=dbhost;dbname=evp_tst'
            user: 'someuser'
            password: '....--....'
            dump: 'tests/_data/dump.sql'
            populate: true # should the dump be loaded before test suite is started.
            cleanup: false # should the dump be reloaded after each test
```

Any ideas on what can be going wrong?

Tkx
