### ISSUE TITLE
 Phalcon1 module is not configured!         

### ISSUE THREAD

**Issue by duythien** [Codeception/Codeception#1315]
Hi all

I have a problem, in functional.suite.yml file i define 

```
class_name: FunctionalTester
modules:
    enabled: [Filesystem, FunctionalHelper, Phalcon1]
    Phalcon1:
        bootstrap: common/config/services.php
        cleanup: true
        savepoints: true
```

Then running command line 

```
$ ./vendor/bin/codecept  run functional --steps --debug
```

It is display error

```
[Codeception\Exception\ModuleConfig]                             
  Phalcon1 module is not configured!                               
  Bootstrap file does not exists in app/config/bootstrap.php       
  Please create the bootstrap file that return Application object  
  And specify path to it with 'bootstrap' config                   
  Sample bootstrap:                                                
  <?php                                                            
  $config = include __DIR__ . "/config.php";                       
  include __DIR__ . "/loader.php";                                 
  $di = new \Phalcon\DI\FactoryDefault();                          
  include __DIR__ . "/services.php";                               
  return new \Phalcon\Mvc\Application($di);                        

```

I see file config boot phalcon [here](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/Phalcon1.php#L60), I don't want edit source , so want overwrite it, can you help me
