### ISSUE TITLE
Select multiple checkboxes with Laravel4 Module via pseudo selectors

### ISSUE THREAD

**Issue by austenc** [Codeception/Codeception#1334]
When trying to check several options in a functional test using the Laravel4 module I am unable to find the form fields using `:nth-of-type(0)` syntax. Keeps saying form field couldn't be found. Here's the applicable portion of my test:

``` php
        for($i = 0; $i < 3; $i++)
        {
            $input = 'input[type=checkbox]:nth-of-type('.$i.')';
            $I->checkOption($input);
            $students[] = $I->grabValueFrom($input);
        }
```

Here is a snippet from the failed test HTML:

``` HTML
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Schedule</th>
                    <th>Name</th>
                    <th>Location</th>
                    <th>Attempt #</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><input name="student_id[]" type="checkbox" value="93"></td>
                    <td>Caden Nienow</td>
                    <td>New Kiarraburgh, NY
                    <td>0</td>
                </tr>
                <tr>
                    <td><input name="student_id[]" type="checkbox" value="120"></td>
                    <td>Morgan Murray</td>
                    <td>Florencioville, VA
                    <td>0</td>
                </tr>
                <tr>
                    <td><input name="student_id[]" type="checkbox" value="135"></td>
                    <td>Deborah Lowe</td>
                    <td>Eladioberg, FL
                    <td>0</td>
                </tr>
            </tbody>
        </table>
```

Finally, my functional testing config:

```
# Codeception Test Suite Configuration

# suite for functional (integration) tests.
# emulate web requests and make application process them.
# Include one of framework modules (Symfony2, Yii2, Laravel4) to use it.

class_name: FunctionalTester
modules:
    enabled: [Db, Filesystem, FunctionalHelper, Laravel4]
    config:
        Laravel4:
            cleanup: false
```

Any idea what might be happening? Seems like that selector should work fine! I've also tried a selector like `//form/*[@type=checkbox][0]` as well. All I'd like to do is select several checkboxes on this page and grab the selected values.

Also, here's the error from the console:
`Form field by Label or CSS 'input[type=checkbox]:nth-of-type(0)' was not found on page.`

Thanks! Codeception rocks!
