### ISSUE TITLE
PhantomJS and HTTP Auth

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#1355]
I am trying to run acceptance tests using PhantomJS in which the URL is password protected (HTTP Basic Auth)

I have the following in my `acceptance.suite.yml`

```
config:
    WebDriver:
        url: 'https://my.url.com'
        browser: 'phantomjs'
        port: 4445
        wait: 0
        capabilities:
          phantomjs.page.settings.userAgent: "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36"
          pantomjs.page.settings.userName: "myUser"
          pantomjs.page.settings.password: "myPassword"
          unexpectedAlertBehaviour: 'accept'
```

This never seems to be able to passthrough, as when using `$I->makeScreenshot();` always results in a blank image.

Is this the correct way of going about this?

I'm using `PhantomJS 1.9.7' and using the following to run PhantomJS

`phantomjs --webdriver=4445 --ignore-ssl-errors=true`

Thanks
