### ISSUE TITLE
Laravel4: amOnPage / amOnRoute making two requests for each call

### ISSUE THREAD

**Issue by austenc** [Codeception/Codeception#1389]
When functional testing _in a workbench package_ with the Laravel4 module, `amOnPage` and `amOnRoute` seem to be requesting the given path/route twice for each single call of the function. _Is this intended behavior?_

**functional.suite.yml**

``` yaml
class_name: FunctionalTester
modules:
    enabled: [Db, Filesystem, FunctionalHelper, Laravel4]
    config:
        Laravel4:
            cleanup: false
```

**My test, ExampleCept.php**

``` php
<?php 
$I = new FunctionalTester($scenario);
$I->amOnPage('/example');
```

**Package route**

``` php
Route::get('example', function(){
    Log::error('example route called');
});
```

`codecept run functional ExampleCept.php` **from workbench dir gives:**

``` yaml
[2014-09-08 08:08:16] testing.ERROR: example route called [] []
[2014-09-08 08:08:16] testing.ERROR: example route called [] []
```

I don't understand enough about codeception and its dependencies to have figured out where / why this is happening in the codecept source.. Any guidance to where I might look appreciated. I'm on the latest version of codecept `*` from composer.
