### ISSUE TITLE
ZF2 module wont work as expeted with redirects

### ISSUE THREAD

**Issue by olekhy** [Codeception/Codeception#1405]
THREe troubles:

I've installed CC and enabled ZF2 module firstly, my application on first request do a redirect (from / to /de-DE fe). 

- Trouble ONE is that the host isnt defined error see below, 

- and SECOND trouble when I've hardcoded $_SERVER['HOST_NAME'] then application redirected infinitely to /de-DE

- THIRD trouble no response content was in Zend Response too so when redirect for locale was temporarily switched off where is the response content I don't know maybe listener SendResponseListener is detached in ZF2 Module. Is so ok?
hm :(
****

**acceptance.suite.yaml**

```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
        - ZF2
    config:
        PhpBrowser:
            url: 'http://www.myapp.com'
```

**WelcomeCept.php**
```php
$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');
$I->amOnPage('/');
$I->seeInCurrentUrl('de-DE');
```

** undefined host error**
```shell

1) Failed to perform actions and see result in WelcomeCept (/home/.../tests/acceptance/WelcomeCept.php)
Can't be on page "/":
ErrorException: Undefined index: host

Scenario Steps:
1. I am on page "/"

#1  /home/.../vendor/symfony/browser-kit/Symfony/Component/BrowserKit/CookieJar.php:215
#2  /home/.../vendor/symfony/browser-kit/Symfony/Component/BrowserKit/Client.php:316
#3  /home/.../vendor/symfony/browser-kit/Symfony/Component/BrowserKit/Client.php:520
#4  /home/.../vendor/symfony/browser-kit/Symfony/Component/BrowserKit/Client.php:343
#5  /home/.../tests/acceptance/AcceptanceTester.php:129
#6  /home/.../tests/acceptance/WelcomeCept.php:4

FAILURES!
Tests: 1, Assertions: 0, Errors: 1.


```
