### ISSUE TITLE
Include multiples urls in testing

### ISSUE THREAD

**Issue by ChiChi88** [Codeception/Codeception#1429]
Hello,

Am a fresher to this fields. I have problem that i want to use multiple urls for my testing by using codeception 
I try for research and i can see i can include it on diff envs but it doesn't works
http://codeception.com/docs/12-ParallelExecution

it keeps using my default URL (url1) but not url1 and url2 when am calling
php codecept.phar run --env frontend

```
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
    config:
     WebDriver:
            url: 'url1'
            browser: firefox
            wait: 10
            clear_cookies: false
            restart: true
            cleanSession: true
env:
    backend:
        modules:
            config:
                Db:
                    dsn: 
                WebDriver:
                    url: 'url2'
    frontend:
        modules:
            config:
                Db:
                    dsn:
                WeDriver:
                    url: 'url3'	
```
