### ISSUE TITLE
How i can get Module from Cest?

### ISSUE THREAD

**Issue by maxgu** [Codeception/Codeception#1430]
I have modules:

``` yml
class_name: FunctionalTester
modules:
    enabled: [ZF2, Filesystem, FunctionalHelper]
```

How i can get public property of module ZF2?

``` php
public function _before(FunctionalTester $I)
{
    $application = $I->getModule('ZF2')->application;
    ...
}
```
