### ISSUE TITLE
Extension not loading

### ISSUE THREAD

**Issue by bkuhl** [Codeception/Codeception#1442]
Using the following configuration my extension is not loading which I do not understand.  It shows no errors, I can build/run my tests fine.  MyExtension.php has an `exit()` in the constructor so I would expect this to fail.  

``` yml
class_name: WebGuy
extensions:
    enabled: [MyExtension]
modules:
    enabled: [WebDriver, WebHelper, Asserts, Db]
```

I've tried building and then running with --debug and cannot get things to fail, but it does not load the module:

```
Acceptance Tests (1) --------------------------------------------------------------------------------------------------------
Modules: WebDriver, WebHelper, Asserts, Db
-----------------------------------------------------------------------------------------------------------------------------
Trying to ....
```
