### ISSUE TITLE
acceptPopup doesn't work when using CodeCoverage

### ISSUE THREAD

**Issue by rafaelbdb** [Codeception/Codeception#1485]
My acceptance tests works perfectly when I don't use --coverage (or --coverage-html), but when I do the following error appears (and I have a "$I->acceptPopup();" in this point of the code).

Command:

> php codecept.phar run acceptance myTestCept.php --coverage-html -d

```
[UnexpectedAlertOpenException]
  unexpected alert open
    (Session info: chrome=38.0.2125.104)
    (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 SP1 x86_64
  ) (WARNING: The server did not provide any stacktrace information)
  Command duration or timeout: 1 milliseconds: null
  Build info: version: '2.43.0', revision: '597b76b', time: '2014-09-09 20:52
  :14'
  System info: host: 'Rafael-PC', ip: '10.1.1.14', os.name: 'Windows 7', os.a
  rch: 'x86', os.version: '6.1', java.version: '1.7.0_71'
  Session ID: c609d18ac1e286650052fa88369ed083
  Driver info: org.openqa.selenium.chrome.ChromeDriver
  Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, br
  owserName=chrome, chrome={userDataDir=C:\Users\Cliente\AppData\Local\Temp\s
  coped_dir6936_23574}, rotatable=false, locationContextEnabled=true, version
  =38.0.2125.104, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseE
  nabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEve
  nts=true, webStorageEnabled=true, applicationCacheEnabled=false, takesScree
  nshot=true}]
Exception trace:
 () at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/facebook/webdriver/lib/WebDriverExceptions.php:94
 WebDriverException::throwException() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:253
 HttpCommandExecutor::curl() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:153
 HttpCommandExecutor::remoteExecute() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/facebook/webdriver/lib/remote/HttpCommandExecutor.php:117
 HttpCommandExecutor->execute() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/facebook/webdriver/lib/remote/RemoteWebDriver.php:261
 RemoteWebDriver->takeScreenshot() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/Module/WebDriver.php:197
 Codeception\Module\WebDriver->_saveScreenshot() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/Module/WebDriver.php:137
 Codeception\Module\WebDriver->_failed() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/Subscriber/Module.php:72
 Codeception\Subscriber\Module->failed() at n/a:n/a
 call_user_func() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:164
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php:53
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/PHPUnit/Listener.php:101
 Codeception\PHPUnit\Listener->fire() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/PHPUnit/Listener.php:51
 Codeception\PHPUnit\Listener->addError() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestResult.php:269
 PHPUnit_Framework_TestResult->addError() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestResult.php:735
 PHPUnit_Framework_TestResult->run() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php:771
 PHPUnit_Framework_TestCase->run() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestSuite.php:703
 PHPUnit_Framework_TestSuite->run() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/PHPUnit/Runner.php:100
 Codeception\PHPUnit\Runner->doEnhancedRun() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/SuiteManager.php:153
 Codeception\SuiteManager->run() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/Codecept.php:162
 Codeception\Codecept->runSuite() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/Codecept.php:145
 Codeception\Codecept->run() at phar://E:/Auto_testing/Codecept/codecept.phar/src/Codeception/Command/Run.php:177
 Codeception\Command\Run->execute() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:889
 Symfony\Component\Console\Application->doRunCommand() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar://E:/Auto_testing/Codecept/codecept.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at phar://E:/Auto_testing/Codecept/codecept.phar/codecept:34
 require_once() at E:\Auto_testing\Codecept\codecept.phar:7
run [-c|--config="..."] [--report] [--html[="..."]] [--xml[="..."]] [--tap[="..."]] [--json[="..."]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug]
[--coverage[="..."]] [--coverage-html[="..."]] [--coverage-xml[="..."]] [--coverage-text[="..."]] [--no-exit] [-g|--group="..."] [-s|--skip="..."] [-sg|--skip-group="..."] [--env="..."] [-f|--fail-fast] [suite] [test]
```

My codeception.yml:

``` yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    memory_limit: 1024M
    colors: true
    steps: true
    coverage:
        enabled: true
        remote: true
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```

And my acceptance.suite.yml:

``` yaml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
    config:
        WebDriver:
            url: 'http://myurl.com/'
            browser: 'chrome'
            restart: false
            window_size: 1024x768
```

I'm using:
Windows 7 Home Premium x64 bits
Codeception 2.0.5
php 5.5.12
XDebug 2.2.5

I tried to use

``` yaml
capabilities:
        unexpectedAlertBehaviour: 'accept'
```

in acceptance.suite.yml, but nothing changes...

Am I doing anything wrong?
