### ISSUE TITLE
Problem sending file data with REST

### ISSUE THREAD

**Issue by cent4auka** [Codeception/Codeception#1490]
I have a problem sending file data with REST
    if $files = [];
    test pass OK

```
if $file = [ __DIR__ . '/images/1.jpg',];
then error curl timeout
```
#### Test

```
public function testAdd()
{
    $files = [
        __DIR__ . '/images/1.jpg',
    ];
    $data = [
        'name' => '111',
    ];

    $this->tester->sendPOST('/admin/popup/save/', $data, $files);

    $this->tester->seeResponseCodeIs(200);
}
```
#### suite

```
class_name: ApiTester
modules:
    enabled: [PhpBrowser, REST, ApiHelper]
    config:
        PhpBrowser:
            url: http://localhost
        REST:
          url: http://localhost/clientapi/v1
```
#### Test execution

```
$ php-vendor/bin/codecept run api
Codeception PHP Testing Framework v2.0.7
Powered by PHPUnit 4.3.4 by Sebastian Bergmann.

Api Tests (1) -----------------------------------------------------------
Trying to test add (PopupTest::testAdd)                             Error
-------------------------------------------------------------------------


Time: 30.1 seconds, Memory: 9.00Mb

There was 1 error:

---------
1) PopupTest::testAdd
GuzzleHttp\Exception\RequestException: [curl] (#28) See http://curl.haxx.se/libcurl/c/libcurl-errors.html for an explanation of cURL errors [url] http://localhost/clientapi/v1/admin/popup/save/


FAILURES!                          
Tests: 1, Assertions: 0, Errors: 1.
```
