### ISSUE TITLE
Empty coverage with Acceptance tests

### ISSUE THREAD

**Issue by FnTm** [Codeception/Codeception#1491]
I am using a following configuration to run my tests:
```
actor: Tester
coverage:
    enabled: true
    remote: false
    whitelist:
          include:
              - module/Application/*
              - module/Application/*.php
              - module/Application/src/Application/Model/*
          exclude:
              - module/Application/view/*
              - module/Application/config/*
              - module/Application/language/*
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
```
I have a couple of unit tests and 2 acceptance tests. If I run only the unit tests with code coverage (with `--coverage-html`) it generates html of only the classes that were involved with the particular unit tests, and includes the info about the tests and which methods are covered by which test. I guess this is ok.

But when I run the acceptance tests, the html for ALL of the whitelisted classes is generated, but there is no information about any tests that were run. Meaning, it says, that no lines in the code have been tested. The tests run without any errors.
