### ISSUE TITLE
Functional Testing with Selenium

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#1492]
Hi

I've been using phantomjs for pretty much all of my tests, but i need to introduce Selenium as well (so people in the company can see on screen what it is running!)

I have looked through the docs and I've seen the `env` configuration, so I thought I'd update my current `functional.suite.yml`

```
class_name: FunctionalTester
modules:
    enabled:
        - WebDriver
        - WebHelper
    config:
        WebDriver:
            url: 'https://my.url.local'
            browser: 'phantomjs'
            port: 4445
            wait: 0
            restart: true
            clear_cookies: true
            capabilities:
              phantomjs.page.settings.userAgent: "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36"
              unexpectedAlertBehaviour: 'accept'
        Db:
            dsn: 'mysql:host=localhost;dbname=test'
            user: 'root'
            password: 's3cr3t'

env:
    firefox:
         modules:
            config:
                WebDriver:
                    url: 'https://my.url.local'
                    browser: 'firefox'
                    port: 4444`
```

When I run the following, Firefox opens, but the URL doesn't seem to get sent to WebDriver as Firefox just opens a blank page, not filling out the URL in the address bar.

Does this configuration look correct?

I have the following in my cept:

```
$I = new FunctionalTester($scenario);
$I->wantTo("test");
$I->amOnPage('/');
```

I'd expect Firefox to open the URL: `https://my.url.local/` but nothing is typed

I'm also using `1.8.7` (for various PHP version-related issues)

Thanks
