### ISSUE TITLE
Running desired_capabilities['prerun'] 

### ISSUE THREAD

**Issue by joshhornby** [Codeception/Codeception#1497]
Is it possible to use this prerun command in codeception?

https://support.saucelabs.com/entries/49849880-How-can-I-use-HTTP-basic-auth-in-Safari-

I am currently doing something like this with env

```
  ios8:
     modules:
        config:
            WebDriver:
                browser: 'iphone'
                capabilities:
                  unexpectedAlertBehaviour: 'accept'
                  platform: 'OS X 10.9'
                  version: '8'
                  device-orientation: 'portrait'
```

Would be nice if I could pass prerun in there?
