### ISSUE TITLE
Multiple Selenium2 Sessions for Acceptance tests

### ISSUE THREAD

**Issue by precariouspanther** [Codeception/Codeception#154]
Would be fantastic to be able to run through all of the acceptance tests in multiple, separate browser configs as an option built in to Codeception.

Currently in order to do this I have a script to export the acceptance.suite.yml:

``` yml
class_name: WebGuy
modules:
    enabled:
        - WebHelper
        - WebDebug
        - Selenium2
    config:
        Selenium2:
            url: 'http://localhost/'
            browser: 'firefox'
            delay: 200
```

And then execute and parse the test results, and _then_ reexport acceptance.suite.yml with

``` yml
class_name: WebGuy
modules:
    enabled:
        - WebHelper
        - WebDebug
        - Selenium2
    config:
        Selenium2:
            url: 'http://localhost/'
            browser: 'chrome'
            delay: 20
```

And then run codecept again. This is clumsy and makes it difficult to get the results together in one report - it would be fantastic if I could do something like this instead:

``` yml
class_name: WebGuy
modules:
    enabled:
        - WebHelper
        - WebDebug
        - Selenium2
    config:
        Selenium2:
            session1:
                url: 'http://localhost/'
                browser: 'firefox'
                delay: 200
            session2:
                url: 'http://localhost/'
                browser: 'chrome'
                delay: 20
```

I run the acceptance tests through both to catch any odd behavior in one browser or the other.
