### ISSUE TITLE
Reloading DB dump after all tests

### ISSUE THREAD

**Issue by dvapelnik** [Codeception/Codeception#1546]
Can I explain Codeception what I want it to be restored to the original state of the database after the test data to the state that existed before the test?

``` yml
modules:
   enabled: [Db]
   config:
      Db:
         dsn: 'mysql:host=localhost;dbname=testdb'
         user: 'root'
         password: ''
         dump: 'tests/_data/dump.sql'
         populate: true
         cleanup: true
```
