### ISSUE TITLE
Can't find class in Phalcon1 Module

### ISSUE THREAD

**Issue by phoenixgao** [Codeception/Codeception#1552]
Hi I was trying to write some unit tests with phalcon1 module for my phalcon project,
but when I exec

```
php codecept.phar run
```

I got this:

`Fatal error: Class 'Phalcon\Session\Adapter' not found in phar:///path/to/project/codecept.phar/src/Codeception/Lib/Connector/Phalcon1.php on line 124`

Here is my unit.suite.yml

```
# Codeception Test Suite Configuration

# suite for unit (internal) tests.
class_name: UnitTester
modules:
    enabled: [Asserts, UnitHelper, Phalcon1, FileSystem]
    config:
        Phalcon1:
            bootstrap: 'tests/bootstrap.php'
            cleanup: true
            savepoints: true
```

Did I do anything wrong ?
