### ISSUE TITLE
Acceptance Laravel4 amOnPage "Can't be on page" 404 testing

### ISSUE THREAD

**Issue by svpernova09** [Codeception/Codeception#1559]
I'm trying to check to make sure my 404 handling works. I'm trying to use `$I->seePageNotFound();` but `$I->amOnPage('/some/bad/url/that/will/never/exist');` throws `Symfony\Component\HttpKernel\Exception\NotFoundHttpException:` and the test fails.

What is the proper way to test for this? Is there something wrong with my config that's causing this?

codeception.yml

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=homestead'
            user: 'homestead'
            password: 'secret'
            dump: tests/_data/dump.sql
            cleanup: true
```

acceptance.suite.yml:

```
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
        - Db
        - Laravel4
    config:
        WebDriver:
            url: 'http://localhost/'
            browser: phantomjs
            window_size: 1024x750
            capabilities:
              webStorageEnabled: true
        Db:
            cleanup: true
```

404WorksCept.php

```
<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('ensure that the 404 page works');
$I->haveEnabledFilters();
$I->amOnPage('/some/bad/url/that/will/never/exist');
$I->seePageNotFound();
$I->dontSee('whoops');
```

app/filters.php

```
...
App::missing(function($exception)
{
    return Response::view('errors.404', array(), 404);
});
```

app/views/errors/404.blade.php

```
404 - Invalid URl
```

Test Output:

```
codecept run acceptance 404WorksCept.php --debug
Codeception PHP Testing Framework v2.0.8
Powered by PHPUnit 4.3.5 by Sebastian Bergmann.

Acceptance Tests (1) ----------------------------------------------------------------------------------------------
Modules: WebDriver, AcceptanceHelper, Db, Laravel4
-------------------------------------------------------------------------------------------------------------------
Trying to ensure that frontpage works (404WorksCept)
Scenario:
* I have enabled filters
* I am on page "/some/bad/url/that/will/never/exist"
  Screenshot and HTML snapshot were saved into '_output' dir
 ERROR

-------------------------------------------------------------------------------------------------------------------


Time: 1.9 seconds, Memory: 17.75Mb

There was 1 error:

---------
1) Failed to ensure that frontpage works in 404WorksCept (/home/vagrant/hackmemphis.dev/tests/acceptance/404WorksCept.php)
Can't be on page "/some/bad/url/that/will/never/exist":
Symfony\Component\HttpKernel\Exception\NotFoundHttpException:

Scenario Steps:
2. I am on page "/some/bad/url/that/will/never/exist"
1. I have enabled filters


  [PHPUnit_Framework_ExceptionWrapper]


FAILURES!
Tests: 1, Assertions: 0, Errors: 1.
```
