### ISSUE TITLE
Selenium 2 do NOT takes screenshot on failure

### ISSUE THREAD

**Issue by xt99** [Codeception/Codeception#156]
With all the same configuration and test steps _Selenium_ takes screenshot on failure (as expected) but _Selenium 2_ **doesn't**. 

Codeception version 1.5.3

_acceptance.suite.yml_ for _Selenium_ :

```
class_name: WebGuy
modules:
  enabled:
    - Selenium
    - WebHelper
  config:
    Selenium:
      url: 'http://test.loc/'
      browser: firefox
```

_acceptance.suite.yml_ for _Selenium 2_ :

```
class_name: WebGuy
modules:
  enabled:
    - Selenium2
    - WebHelper
  config:
    Selenium2:
      url: 'http://test.loc/'
      browser: firefox
```
