### ISSUE TITLE
Empty coverage with Unit tests

### ISSUE THREAD

**Issue by hgraca** [Codeception/Codeception#1560]
Hi,

First let me thank you again for this project you started. 
I love it.

That being said, I'm having some problems...
I've used Codeception before and generated coverage reports for API tests in a Symfony project.
Now I'm setting up codeception in a project with a custom framework.
I installed it with composer by adding this (there's also some extra stuff):

``` json
  "require-dev": {
    "fabpot/php-cs-fixer": "dev-master",
    "phpunit/phpunit": "~4.0",
    "phpunit/php-code-coverage": "~2.0",
    "Mockery/Mockery": "~0.9",
    "codeception/codeception": "2.*",
    "codeception/c3": "2.*",
    "codeception/specify": "*",
    "codeception/verify": "*",
    "codeception/aspect-mock": "*"
  },
  "scripts": {
      "post-install-cmd": [
          "Codeception\\c3\\Installer::copyC3ToRoot"
      ],
      "post-update-cmd": [
          "Codeception\\c3\\Installer::copyC3ToRoot"
      ]
  },
```

my configurations are all the default ones:

``` yml
# ./codeception.yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```

``` yml
# ./tests/unit.suite.yml
class_name: UnitTester
modules:
    enabled: [Asserts, UnitHelper]
```

I also added the c3.php file through composer and I've put it in the bootstrap to be loaded in development and testing, but as I'm only using unit tests so far, and I run them locally, I don't think it's needed.

I made some tests and got it running but can't get any code coverage.

I'm using vagrant, so I login to the VM, cd into the project root and run:

``` bash
./vendor/bin/codecept run unit --coverage --coverage-xml --coverage-html
```

After running it this is the result in the command line:

``` bash
...

Time: 7.83 seconds, Memory: 39.75Mb

OK (140 tests, 200 assertions)


Code Coverage Report:  
  2014-11-25 18:17:56  

 Summary:              
  Classes:        (0/0)
  Methods:        (0/0)
  Lines:          (0/0)

Remote CodeCoverage reports are not printed to console

HTML report generated in coverage
XML report generated in coverage.xml
```

the coverage.xml file has this:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1416935876">
  <project timestamp="1416935876">
    <metrics files="0" loc="0" ncloc="0" classes="0" methods="0" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="0" coveredstatements="0" elements="0" coveredelements="0"/>
  </project>
</coverage>
```

Edit: This is my xdebug config:

``` ini
;# /etc/php5/cli/conf.d/20-xdebug.ini 

zend_extension=xdebug.so

xdebug.var_display_max_depth=5
xdebug.var_display_max_data=5
xdebug.var_display_max_children=5
xdebug.max_nesting_level=250
xdebug.cli_color=1

xdebug.remote_enable=1              ;# trigger: cookie:XDEBUG_SESSION=PHPSTORM
xdebug.remote_host=10.13.37.1
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_mode=req

xdebug.profiler_enable=0
xdebug.profiler_enable_trigger=1    ;# trigger: cookie:XDEBUG_PROFILE=1
xdebug.profiler_output_dir="/www/backend/no-vcs/xdebug"
xdebug.profiler_output_name="%H.profiler"

xdebug.auto_trace=0
xdebug.trace_enable_trigger=1       ;# trigger: cookie:XDEBUG_TRACE=1
xdebug.trace_options=0
xdebug.collect_params=4
xdebug.collect_return=0             ;# if set to 1 it breaks
xdebug.trace_format=2
xdebug.trace_output_dir="/www/backend/no-vcs/xdebug"
xdebug.trace_output_name="%H.trace"

xdebug.idekey="PHPSTORM"
```

Can someone help me figure out what is wrong?

Thank you.
