### ISSUE TITLE
Cannot create helper that uses Symfony's Filesystem module

### ISSUE THREAD

**Issue by etki** [Codeception/Codeception#1597]
Hi again.

Strangely, but `2.1.x-dev` version skips tester build if one of the helpers contains `use Symfony\Component\Filesystem\Filesystem;` statement. here is the most basic example possible:

```php
namespace Codeception\Module;

use Symfony\Component\Filesystem\Filesystem;

class ImageHelper extends \Codeception\Module
{
}
```

unit.suite.yml:
```yml
class_name: UnitTester
modules:
    enabled: [Asserts, UnitHelper, ImageHelper]
```

As soon as i remove Filesystem statement, everything gets back to normal.
