### ISSUE TITLE
Yii module doesn't pass to url

### ISSUE THREAD

**Issue by vollossy** [Codeception/Codeception#160]
to @Ragazzo
I'm trying to use Yii module insid my TestHelper class:

``` php
<?php
namespace Codeception\Module;

// here you can define custom functions for TestGuy 

class TestHelper extends \Codeception\Module
{
    private $_username;
    private $_password;

    /**
     * Авторизует пользователя в системе по указанным учетным данным
     * @param string $userName Имя пользователя
     * @param string $userPassword Пароль пользователя
     */
    public function loggedWithCredentials($userName, $userPassword)
    {
        $this->_username = $userName;
        $this->_password = $userPassword;
        /**
         * @var PhpBrowser $yii
         */
        $yii = $this->getModule('Yii1');
        $yii->amOnPage('/site/logout);
        $yii->amOnPage('/site/login');
        $yii->fillField('#UserLoginForm_username', $userName);
        $yii->fillField('#UserLoginForm_password', $userPassword);
        $yii->click('Войти');
    }

    /**
     * Задает определенное значение для денег, которые есть у пользователя.
     * @param $amount количество денег пользователя.
     */
    public function haveMoney($amount)
    {
        $user = \User::model()->findByAttributes(array('login' => $this->_username));
        $user->money = $amount;
        $user->save();
    }
}
```

but tests falls with error "Guy couldn't logged with credentials "arkhimed","Evrika!": Link or button for 'Войти' was not found". As i found, this error appears becaus of yii shows only my front page.
Further research tells me that $_SERVER['REQUEST_URI'] allways set to url, which defined in configuration file('http://vollossy/index-test.php' or my case).
here's example of my config file

``` yaml
# Codeception Test Suite Configuration

# suite for functional (integration) tests.
# emulate web requests and make application process them.
# (tip: better to use with frameworks).

# RUN `build` COMMAND AFTER ADDING/REMOVING MODULES.

class_name: TestGuy
modules:
  enabled: [Filesystem, TestHelper, Yii1]
  config:
    Yii1:
      appPath: '/home/roman/projects/vollossy/index-test.php'
      url: 'http://vollossy/index-test.php/'

```
