### ISSUE TITLE
Unable to generate code coverage for acceptance tests

### ISSUE THREAD

**Issue by ThePeach** [Codeception/Codeception#1611]
The specific error being:

```
 Use of undefined constant C3_CODECOVERAGE_MEDIATE_STORAGE ...
```

and many others:
as you can see [from the snapshot taken](http://i.imgur.com/g4bKppH.png)
I've seen several issues about the same error but none of them was this specific.

I'm using Yii 2 and I've got no problems running all kind of tests.
I'm starting looking into generating code coverage reports, and no problem whatsoever with unit tests.

As [per instructions](https://github.com/Codeception/c3) found here: https://github.com/Codeception/c3.
I've installed https://github.com/Codeception/c3 adding the following in `composer.json`:

``` json
    "require-dev": {

        "codeception/codeception": " 2.0.*",
        "codeception/c3": "2.*",

    },
    "scripts": {
        "post-install-cmd": [
            "Codeception\\c3\\Installer::copyC3ToRoot"
        ],
        "post-update-cmd": [
            "Codeception\\c3\\Installer::copyC3ToRoot"
        ],

    },
```

I've configured CodeCeption as the following:

``` yaml
actor: Tester
paths:
    tests: codeception
    log: codeception/_output
    data: codeception/_data
    helpers: codeception/_support
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    memory_limit: 1024M
    log: true
    colors: true
config:
    test_entry_url: /index-test.php
coverage:
    enabled: true
    remote: true
    include:
        - ../models/*
        - ../modules/*
        - ../controllers/*
    c3_url: 'https://basic-dev.yii2.sandbox/index-test.php/'
```

and added at the beginning of `web/index-test.php` the following:

```
include '../vendor/codeception/c3/c3.php';
```

I've previously tried including the file that was copied in the root of the project (still don't get the purpose of that):

```
include '../c3.php';
```

but it didn't make any difference.
The coverage is reporting 0% of code covered regardless.

How is taking care of doing the autoload of c3 related things?
Is there anything that I've stupidly missed?
