### ISSUE TITLE
functional or acceptance tests report 0% coverage

### ISSUE THREAD

**Issue by ThePeach** [Codeception/Codeception#1622]
If I run

    $ ../vendor/bin/codecept run acceptance --coverage --coverage-html 

I get a report generated:

```
Remote CodeCoverage reports are not printed to console

HTML report generated in coverage
```

but the reports are actually stating a 0% coverage

This is done using Yii2 basic app and the following codeception configuration:

```yaml
# /tests/codeception.yml
actor: Tester
paths:
    tests: codeception
    log: codeception/_output
    data: codeception/_data
    helpers: codeception/_support
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    memory_limit: 1024M
    log: true
    colors: true
config:
    test_entry_url: /index-test.php
coverage:
    enabled: true
    remote: true
    remote_config: ../tests/codeception.yml
    include:
        - ../models/*
        - ../modules/*
        - ../controllers/*
    c3_url: 'https://basic-dev.yii2.sandbox/index-test.php/'
```

the tests alone are working without issues and reporting a *passed* state.

**Comment by Ragazzo** [comment]
Hi @ThePeach , did you include `c3.php` file in your `index-test.php` file as was said in docs? Also note that things that are printed in console for remote code coverage are useless, they does not reflect actual situation, you should check `_output` directory first.

Also i've done a [repo](https://github.com/Ragazzo/testing_check_repo) with correctly setup testing env for you, you can clone it and see that everything works, there are also code coverage results in `_ouput` (i did not deleted them so you can see them also).

You only need to:
- go to `basic/web` and start php builtin server `127.0.0.1:8000`, all configs already changed to use this port (8000).

I've tested it with `PhpBrowser` and `WebDriver`, everything works correctly

**Comment by ThePeach** [comment]
> did you include c3.php file in your index-test.php file as was said in docs?

yup, here's the content of `index-test.php`
```php
<?php

// NOTE: Make sure this file is not accessible when deployed to production
if (!in_array(@$_SERVER['REMOTE_ADDR'], ['127.0.0.1', '::1', '192.168.56.1', '192.168.56.2', '192.168.56.101', '192.168.56.102'])) {
    die('You are not allowed to access this file.');
}

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/../tests/codeception/config/acceptance.php');

include 'c3.php';
(new yii\web\Application($config))->run();
```

the coverage results contained in the `_output` directory report 0% coverage.
This happens for both of the following commands:

    $ ../vendor/bin/codecept run functional --coverage-html

and

    $ ../vendor/bin/codecept run acceptance --coverage-html

The tests are all passing and the configuration is the one I've pasted in the initial comment.

**Comment by ThePeach** [comment]
Furthermore, I've had a look at the configuration of codeception in the repo you've shared, and I've noticed that you've used the full url in the config for `test_entry_url` so I modified it with the following:

```yaml
config:
    test_entry_url: http://basic-dev.yii2.sandbox/index-test.php
```

with this I'm getting the following error when running the acceptance tests:

```
Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Unable to determine the path info of the current request.' 

in /mnt/workspace/test/yii2composer/basic-dev/vendor/yiisoft/yii2/web/Request.php:716

Stack trace:
#0 /mnt/workspace/test/yii2composer/basic-dev/vendor/yiisoft/yii2/web/Request.php(657): yii\web\Request->resolvePathInfo()
#1 /mnt/workspace/test/yii2composer/basic-dev/vendor/yiisoft/yii2/web/UrlManager.php(230): yii\web\Request->getPathInfo()
#2 /mnt/workspace/test/yii2composer/basic-dev/vendor/yiisoft/yii2/web/Request.php(180): yii\web\UrlManager->parseRequest(Object(yii\web\Request))
#3 /mnt/workspace/test/yii2composer/basic-dev/vendor/yiisoft/yii2/web/Application.php(75): yii\web\Request->resolve()
#4 /mnt/workspace/test/yii2composer/basic-dev/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#5 /mnt/workspace/test/yii2composer/basic-dev/web/index-test.php(17): yii\base\Application->run()
#6 {main}
```

which doesn't really make much sense to me... odd.

**Comment by Ragazzo** [comment]
can you update your application to latest `yii2-basic` , this should solve all ther problems . Also did you check that app that i shared , does it works for you ?

**Comment by ThePeach** [comment]
OK, I've updated the basic app and the previous error is now gone. I now have `test_entry_url: http://basic-dev.yii2.sandbox/index-test.php` and it does not throw any more errors, although it still reports 0% coverage.

I've cloned your repo, updated the db configuration and tried to run the migration but run into some errors:

```
$ ./yii migrate
PHP Warning:  require(/home/peach/public_html/testing_check_repo/vendor/codeception/verify/src/Codeception/function.php): failed to open stream: No such file or directory in /home/peach/public_html/testing_
check_repo/vendor/composer/autoload_real.php on line 58
PHP Stack trace:
PHP   1. {main}() /home/peach/public_html/testing_check_repo/yii:0
PHP   2. require() /home/peach/public_html/testing_check_repo/yii:17
PHP   3. ComposerAutoloaderInit437edbf9368aa0e42af6c317fc4b87f5::getLoader() /home/peach/public_html/testing_check_repo/vendor/autoload.php:7
PHP   4. composerRequire437edbf9368aa0e42af6c317fc4b87f5() /home/peach/public_html/testing_check_repo/vendor/composer/autoload_real.php:49

Warning: require(/home/peach/public_html/testing_check_repo/vendor/codeception/verify/src/Codeception/function.php): failed to open stream: No such file or directory in /home/peach/public_html/testing_check
_repo/vendor/composer/autoload_real.php on line 58

[snip]
```

**Comment by Ragazzo** [comment]
>/home/peach/public_html/testing_check_repo/vendor/codeception/verify/src/Codeception/function.php

check that this file is included , it is a `verify` `Codeception` package , check that it is installed (it should be) or if not you can install it `require codeception/verify:*`

**Comment by ThePeach** [comment]
yeah, most of the dirs in `vendor` were empty, most likely because they were git repos on their own so automatically excluded. wiped it out and run `composer install` and now it works.

Run the tests as `functional --acceptance-html` and the coverage report was correct.
More over I could also run all the testing suites coverage and it won't generate any error as per my other ticket #1621 

might it be because I've got installed all composer packages with `minimum-stability: dev`?

**Comment by ThePeach** [comment]
I've tried replacing the `include`configuration with the one you have:

```yaml
    white_list:
        include:
            - ../models/*
            - ../modules/*
            - ../controllers/*
            - ../commands/*
            - ../mail/*
    blacklist:
        include:
            - ../assets/*
            - ../build/*
            - ../config/*
            - ../runtime/*
            - ../vendor/*
            - ../views/*
            - ../web/*
            - ../tests/*
```

and I'm now getting the following summary output at the end of the functional tests:

```
OK (6 tests, 49 assertions)


Code Coverage Report:  
  2015-01-17 16:43:05  
                       
 Summary:              
  Classes:        (0/0)
  Methods:        (0/0)
  Lines:          (0/0)
```

the reports dashboard.html and index.html do not contain anything either.
Haven't tried moving to `stable` yet and I'd like to keep it as last resource.
