### ISSUE TITLE
Cert error on CircleCI, with SauceConnect

### ISSUE THREAD

**Issue by aequasi** [Codeception/Codeception#1649]
Having an issue.... Am i missing something?

I'm not connecting to an HTTPS url... Works fine locally on a vagrant VM, but when I'm running on a CircleCI box, im getting:

***Error***
```
[Exception]                                                                                                                            
          Got an error while making a request: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none  
                                                                                                                                                 
        
        
        Exception trace:
         () at /home/ubuntu/app.lfgame.rs/vendor/sauce/sausage/src/Sauce/Sausage/SauceAPI.php:67
         Sauce\Sausage\SauceAPI->makeRequest() at n/a:n/a
         call_user_func_array() at /home/ubuntu/app.lfgame.rs/vendor/sauce/sausage/src/Sauce/Sausage/SauceAPI.php:87
         Sauce\Sausage\SauceAPI->__call() at /home/ubuntu/app.lfgame.rs/vendor/psychomieze/sauceextension/extensions/sauce/SauceExtension.php:54
         Sauce\Sausage\SauceAPI->getJobs() at /home/ubuntu/app.lfgame.rs/vendor/psychomieze/sauceextension/extensions/sauce/SauceExtension.php:54
         Codeception\Extension\SauceExtension->getFirstJob() at /home/ubuntu/app.lfgame.rs/vendor/psychomieze/sauceextension/extensions/sauce/SauceExtension.php:36
         Codeception\Extension\SauceExtension->testFailed() at n/a:n/a
         call_user_func() at /home/ubuntu/app.lfgame.rs/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164
         Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /home/ubuntu/app.lfgame.rs/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:53
         Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:101
         Codeception\PHPUnit\Listener->fire() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:51
         Codeception\PHPUnit\Listener->addError() at /home/ubuntu/app.lfgame.rs/vendor/phpunit/phpunit/src/Framework/TestResult.php:269
         PHPUnit_Framework_TestResult->addError() at /home/ubuntu/app.lfgame.rs/vendor/phpunit/phpunit/src/Framework/TestResult.php:724
         PHPUnit_Framework_TestResult->run() at /home/ubuntu/app.lfgame.rs/vendor/phpunit/phpunit/src/Framework/TestCase.php:722
         PHPUnit_Framework_TestCase->run() at /home/ubuntu/app.lfgame.rs/vendor/phpunit/phpunit/src/Framework/TestSuite.php:751
         PHPUnit_Framework_TestSuite->run() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:100
         Codeception\PHPUnit\Runner->doEnhancedRun() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/src/Codeception/SuiteManager.php:153
         Codeception\SuiteManager->run() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/src/Codeception/Codecept.php:151
         Codeception\Codecept->runSuite() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/src/Codeception/Codecept.php:134
         Codeception\Codecept->run() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/src/Codeception/Command/Run.php:261
         Codeception\Command\Run->runSuites() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/src/Codeception/Command/Run.php:190
         Codeception\Command\Run->execute() at /home/ubuntu/app.lfgame.rs/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:253
         Symfony\Component\Console\Command\Command->run() at /home/ubuntu/app.lfgame.rs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:874
         Symfony\Component\Console\Application->doRunCommand() at /home/ubuntu/app.lfgame.rs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
         Symfony\Component\Console\Application->doRun() at /home/ubuntu/app.lfgame.rs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
         Symfony\Component\Console\Application->run() at /home/ubuntu/app.lfgame.rs/vendor/codeception/codeception/codecept:27
```

Heres my config:

***codeception.yml***
```yml 
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 2048M
coverage:
    enabled: false
extensions:
    enabled:
        - Codeception\Extension\SauceExtension
    config:
        Codeception\Extension\SauceExtension:
            username: '***'
            accesskey: '***'
```

***acceptance.suite.yml***
```yml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - AcceptanceHelper
        - WebDriver
    config:
        WebDriver:
            url: 'http://localhost:8080/'
            host: '***:***@ondemand.saucelabs.com'
            port: 80
            wait: 5
            browser: chrome
            restart: true
            capabilities:
                unexpectedAlertBehaviour: 'accept'
                platform: 'Windows 8.1'
                version: '36'
env:
    chrome:
    firefox:
         modules:
            config:
                WebDriver:
                    browser: 'firefox'
                    capabilities:
                        version: 31
```
