### ISSUE TITLE
GuzzleHttp\Exception\ConnectException when running acceptance tests with coverage

### ISSUE THREAD

**Issue by parhamdoustdar** [Codeception/Codeception#1654]
Hello,

I only have one acceptance test, and that is using `PHPBrowser`. The test is simply to open `/`. Here is what I type to run my test:

`vendor/bin/codecept run acceptance --coverage --coverage-xml`

And here is the error:

`GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after
30029 milliseconds with 0 out of -1 bytes received`

Is it normal for my page to respond so late? If so, how can I increase the guzzle `timeout`?

**Comment by Ragazzo** [comment]
what is your `codeception.yaml` configuration ? did you installed `c3` correctly and included it in your entry point ?

**Comment by parhamdoustdar** [comment]
Here is my configuration:

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
coverage:
    enabled: true
    include:
        - application/*
    exclude:
        - vendor/*
        - application/Cache/*
        - application/Config/*
```

I've also successfully included `c3`.

When I run acceptance tests without `--coverage --coverage-xml`, all works fine. It is only with this option set that it starts taking a very long time.

**Comment by Ragazzo** [comment]
if you are using `PhpBrowser` then you have to enable `remote` code coverage and set correctly `c3_url`

**Comment by parhamdoustdar** [comment]
>if you are using  PhpBrowser  then you have to enable  remote  code coverage

I'm collecting code coverage reports locally (I.E. the requests are being sent to my own local apache server).

> and set correctly  c3_url

I thought this is for times when the `c3_url` differs from the base URL? In my case these are equal.

Anyway, per your suggestion, I changed my config to this:

```yaml
coverage:
    enabled: true
    remote: true
    c3_url: http://eticket.dev/index.php
    include:
        - application/*
    exclude:
        - vendor/*
        - application/Cache/*
        - application/Config/*
```

However, I still get:

```
1) Failed to view the homepage in homepageCept (/vagrant/code/tests/acceptance/homepageCept.php)
Can't be on page "/":
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 30026 milliseconds with 0 out of -1 bytes received
```
