### ISSUE TITLE
PhantomJS and Sessions

### ISSUE THREAD

**Issue by craigwillis85** [Codeception/Codeception#1662]
I'm using PhantomJS to test a form I have.

The form uses sessions to manage the stages.

If I run the test the forst time, the form is filled out fine. When each section is filled out, it is then made read-only.

The next time I run the test, the session seems to be kept and therefore the tests, which looks for fields to fill, fails.

I have the following in my `functional.suite.yml`:

```
config:
    WebDriver:
        url: 'http://my.url.tld
        browser: 'phantomjs'
        port: 4445
        wait: 0
        restart: true
        clear_cookies: true
        capabilities:
          phantomjs.page.settings.userAgent: "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36"
          unexpectedAlertBehaviour: 'accept'
```

I have the `clear_cookies` set, but I'm unsure if there are any other configurations i need to have

**Comment by juan88** [comment]
I am experiencing something similar here. 

I have a test that logs into a webpage filling a form. The thing worked fine the first time but on successive runs (while phantomjs process still runing) tests fails because the log in form no longer appears due to the fact that the user is already logged in.

```
WebDriver:
            url: http://my.url
            browser: phantomjs
            restart: true
            clear_cookies: true
```

I'm using phantomjs 1.9.8 and 2.0.11
