### ISSUE TITLE
SOAP with acceptance test

### ISSUE THREAD

**Issue by Kofriv** [Codeception/Codeception#1706]
Hello,
Is there any way to send SOAP while executing acceptance test?
I tried to config SOAP module for acceptance but seemed it works only with API test and phpBrowser.
I'm trying to do some acceptance test scenarios, there is a step that user should simulate a SOAP request from a 3rd party to our system and then check the system calculates some element from the response and then display result properly on the UI.
Any help could be truly appreciated.
Thanks,
Khoa Nguyen

**Comment by DavertMik** [comment]
Actually you can have SOAP + PhpBrowser + WebDriver mixed together.
Not a good idea but you can. PhpBrowser is used for SOAP to simulate POST requests. If it will be passed before WebDriver it won't be used in `$I->` actions

**Comment by Kofriv** [comment]
Thanks, I've tried to mix WebDriver, SOAP, PhpBrowser in acceptance test and it works.

**Comment by frantzen** [comment]
Hi,

we also need SOAP + Webdriver in our tests. We solved this in a similar way by using a dummy PhpBrowser class for the SOAP module, which just says:

    // disable all inherited actions
    public static $includeInheritedActions = false;

By so doing you can use this PhpBrowser together with the WebDriver, and always the methods from the WebDriver will be used.

Cheers,
Lars

**Comment by yadwinds** [comment]
@frantzen  I am stuck with the same problem for SOAP and Angular js module. Did you mean that you created a PhpBrowser.php file and added public static $includeInheritedActions = false; this in it. Then added it like the following
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        -  DbHelper
        -  Asserts
        - PhpBrowser: 
            url: "http://test"                                   
        -  SOAP:
            depends: PhpBrowser
            endpoint: "http://testapi"   
        - AngularJS:
            url: "http://test"
            browser: 'chrome'

**Comment by yadwinds** [comment]
@DavertMik I am trying your solution for AngularJS and SOAP . But it doesn't work. Can you please confirm if the following should work for AngularJS as well
"Actually you can have SOAP + PhpBrowser + WebDriver mixed together.
Not a good idea but you can. PhpBrowser is used for SOAP to simulate POST requests. If it will be passed before WebDriver it won't be used in $I-> actions"

**Comment by DavertMik** [comment]
@yadwinds  Please try this config. You should remove PhpBrowser from the list of enabled modules to not avoid conflict

```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        -  DbHelper
        -  Asserts                             
        -  SOAP:
            depends: PhpBrowser
            endpoint: "http://testapi"   
        - AngularJS:
            url: "http://test"
            browser: 'chrome'
    config:
        PhpBrowser:
            url: "http://test"     
```
