### ISSUE TITLE
Firefox profile: works for individual test, fails when running suite

### ISSUE THREAD

**Issue by MikeHopley** [Codeception/Codeception#1710]
I have a Firefox profile that I want to be activated whenever Codeception runs acceptance tests:

``` YAML
# app/tests/acceptance.suite.yml

class_name: WebGuy
modules:
  enabled: [WebDriver, Db]
  config:
    WebDriver:
      url: 'http://localhost'
      browser: firefox
      window_size: 1200x950
      capabilities:
        firefox_profile: 'app/tests/_data/browsers/firefox/profile.zip.b64'
      curl:
        CURLOPT_RETURNTRANSFER: true
```

This works fine when I run a single test, like `codecept run acceptance someCept`. But if I run the whole suite with `codecept run acceptance`, then the browser is loaded using my default Firefox profile instead.

I am using this custom profile to trigger an "acceptance" environment in Laravel, by checking for a cookie. So when I say, "the profile is not loaded", I don't technically know this. What I do know is that the correct environment is not triggered.
