### ISSUE TITLE
Laravel 5 Module not rolling back DB

### ISSUE THREAD

**Issue by foxted** [Codeception/Codeception#1739]
I am having an issue with the new version of the Laravel 5 module.

I was waiting for this new module to get the domain-prefixed routes support, but now all db queries are not rolled back after tests, even when setting the cleanup config explicitly.

I am using this version in my composer.json: 

```
"codeception/codeception": "~2.0@dev"
```

**Comment by DavertMik** [comment]
@janhenkgerritsen any ideas?

**Comment by janhenkgerritsen** [comment]
There have been no code changes related to DB cleanup for a while in the Laravel 5 module. It also works as it should for the sample app you can find at https://github.com/janhenkgerritsen/codeception-laravel5-sample.

What are the differences between the sample app and your own app?

**Comment by foxted** [comment]
I am using Jeffrey Way's TestDummy package, it thought it could be the issue but even when trying the `haveRecord` method the database is not cleared between tests. I'll try to investigate more tomorrow ;)

**Comment by olimorris** [comment]
+1

The transactions do not appear to be working at all for me. I modified the Laravel5.php module to use the Laravel DB facade and use the DB::beginTransaction() and DB::rollback() accessors but to no avail.

I have tried this using MySQL and SQLite

**Comment by constb** [comment]
okay, let's guess.

a) do you use a transactions-aware DB engine? because neither SQLITE nor MyISAM support transactions and ignore transaction-related statements.
b) do you use database-related methods of codeception's ``Db`` module? because it uses separate DB connection and runs queries outside L5 module transaction. Use ``*Record`` methods instead.

**Comment by janhenkgerritsen** [comment]
@foxted @olimorris Is this still an issue?

**Comment by foxted** [comment]
@janhenkgerritsen Sorry I thought I answered! Everything ok on my side :)

**Comment by janhenkgerritsen** [comment]
Ok great.

**Comment by olimorris** [comment]
Now fine on my side too. I found an interesting error with Laravel itself which screws CodeCeption and its own password reset trait

**Comment by chungth** [comment]
I also faced this problem in current project. How did you fix it ? 

My settings: 
```
# tests/unit.suite.yml
class_name: UnitTester
modules:
    enabled:
        - \Helper\Unit
        - Laravel5:
            environment_file: .env.testing
```
and 

```
# codeception.yml

actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support

settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    strict_xml: true

coverage:
    enabled: true
    include:
        - app/Http/*
        - app/Models/*
    exclude:
        - app/Http/routes.php
        - app/Http/Kernel.php
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```
