### ISSUE TITLE
waitForText is marked as internal 

### ISSUE THREAD

**Issue by javigomez** [Codeception/Codeception#1741]
Not sure, but I think this docblock here is not needed:

![screen shot 2015-02-24 at 14 31 02](https://cloud.githubusercontent.com/assets/1375475/6350122/5516553e-bc31-11e4-83c6-0e2cb251ce0b.png)

Is causing this:

![screen shot 2015-02-24 at 14 31 24](https://cloud.githubusercontent.com/assets/1375475/6350129/60adb8c4-bc31-11e4-9395-80a8ed51fe68.png)

Witch I think is not the purpose, isn't it?

**Comment by DavertMik** [comment]
Yeah, really strange why so. Could you send a PR to fix it?
24 лют. 2015 15:28, користувач "javier gomez" <notifications@github.com>
написав:

**Comment by javigomez** [comment]
Oops just got the update of that issue. Sorry. Do you still need the PR or is already fixed?

**Comment by javigomez** [comment]
I found my issue, my configuration needs to be like this:

```
config:
        Codeception\Extension\Recorder:
            delete_successful: false
            module: JoomlaBrowser
```

Because I'm using the JoomlaBrowser Extension http://codeception.com/addons#Extensions

Thanks
