### ISSUE TITLE
Environments merging and configuration files

### ISSUE THREAD

**Issue by sjableka** [Codeception/Codeception#1746]
For more complex projects with multiple environments and running contexts (like many WebDriver browsers), environment configuration is quite cumbersome as it requires creating separate environment for each settings combination.

Possibility to merge multiple environments into one configuration would be great:

```bash
$ php codecept.phar run acceptance --env dev,phantom --env dev,chrome --env dev,firefox
```

In addition, to avoid main configuration file to grow too much and to make the structure a bit cleaner, we could provide option to put environment-specific settings into its own file.

**Comment by Patabugen** [comment]
Agreed, I'd like to have inheritance in the configuration files, to avoid repeating multiple settings.

More importantly, I'd like to be able to specify more than one browser in the config and have it run on each of them.

```
class_name: MyTester
modules:
    enabled:
        - WebDriver
        - PortalHelper
    config:
        baseUrl: 'http://example.com'
        WebDriver:
            url: 'http://example.com'
            browser: chrome
            clear_cookies: true
            window_size: maximize
env:
    dev_firefox:
        extends: default
        modules:
            config:
                WebDriver:
                    browser: firefox
    dev_chrome:
        extends: dev
        modules:
            config:
                WebDriver:
                    browser: chrome
```
