### ISSUE TITLE
Laravel5 Request::route undefined

### ISSUE THREAD

**Issue by simnom** [Codeception/Codeception#1748]
Hey,

Getting the following error when running a functional test for Laravel 5:

```
PHP Fatal error:  Call to undefined method Symfony\Component\HttpFoundation\Request::route() in /var/www/vhosts/buildingcentre.knauf.co.uk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php on line 146
```

Associated yaml config is:

```
class_name: ApiTester
modules:
    enabled:
        - REST
        - Laravel5
        - ApiHelper
        - Asserts
    config:
        Laravel5:
            environment_file: .env.testing
```
