### ISSUE TITLE
HTTP header merge/delete

### ISSUE THREAD

**Issue by coviex** [Codeception/Codeception#1791]
Hi,
Inside cept I use phpbrowser module to see() if I'm not logged in, then rest module to login with xhr (I set xhr header explicitly), then again phpbrowser module to see() if I'm logged in.
Problem is in Codeception\Lib\Connector\Guzzle::doRequest() which merges my first xhr header into all subsequent requests, creating header duplicates and resulting in that last check failure. It was OK several months ago, I guess it wasn't merging back then.

It would be great if whether the connector could stop merging recursively or method to delete a header by name was added.

Thanks

```yaml
class_name: AcceptanceHeadlessTester
modules:
    enabled:
        - PhpBrowser
        - REST
        - MyHelper
        - AcceptanceHeadlessHelper
    config:
        PhpBrowser:
            url: "http://my.dev/"
        REST:
            url: "http://my.dev/"
```

```php
namespace Codeception\Module;
class AcceptanceHeadlessHelper extends \Codeception\Module
{
    public function login($username, $password)
    {
        $browser = $this->getModule('REST');
        $browser->haveHttpHeader('X-Requested-With', 'XMLHttpRequest');
        $browser->sendPOST(
            'forum/login/',
            [
                'login[login]'    => $username,
                'login[password]' => $password
            ]
        );
        $browser->seeResponseCodeIs(200);
        $browser->seeResponseIsJson();
        $browser->seeResponseContainsJson(['status' => true]);
        $browser->seeResponseContains('Welcome');

        $browser = $this->getModule('PhpBrowser');
        // this one does not override previously set
        $browser->setHeader('X-Requested-With', '');
    }
}
```
