### ISSUE TITLE
Symfony2: Cannot access protected property FooCest::$env

### ISSUE THREAD

**Issue by JonnyD** [Codeception/Codeception#1870]
Does anyone know what I am missing?

Console:
```
C:\xampp\htdocs\EFL>php vendor/codeception/codeception/codecept run
Codeception PHP Testing Framework v2.0.12
Powered by PHPUnit 4.5.1 by Sebastian Bergmann and contributors.

Acceptance Tests (0) ------------------------
---------------------------------------------

Fatal error: Cannot access protected property FooCest::$env in C:\xampp\htdocs\EFL\vendor\codeception\codeception\src\Codeception\TestCase\Cest.php on line 177

Call Stack:
    0.0007     129600   1. {main}() C:\xampp\htdocs\EFL\vendor\codeception\codeception\codecept:0
    0.1033    1887776   2. Symfony\Component\Console\Application->run() C:\xampp\htdocs\EFL\vendor\codeception\codeception\codecept:27
    0.1187    2152120   3. Symfony\Component\Console\Application->doRun() C:\xampp\htdocs\EFL\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:126
    0.1194    2152560   4. Symfony\Component\Console\Application->doRunCommand() C:\xampp\htdocs\EFL\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:195
    0.1195    2152768   5. Symfony\Component\Console\Command\Command->run() C:\xampp\htdocs\EFL\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:874
    0.1253    2155152   6. Codeception\Command\Run->execute() C:\xampp\htdocs\EFL\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:257
    0.2582    3872536   7. Codeception\Command\Run->runSuites() C:\xampp\htdocs\EFL\vendor\codeception\codeception\src\Codeception\Command\Run.php:191
    0.4520    5634448   8. Codeception\Codecept->run() C:\xampp\htdocs\EFL\vendor\codeception\codeception\src\Codeception\Command\Run.php:262
    0.4776    5636960   9. Codeception\Codecept->runSuite() C:\xampp\htdocs\EFL\vendor\codeception\codeception\src\Codeception\Codecept.php:149
    0.5488    6940288  10. Codeception\SuiteManager->loadTests() C:\xampp\htdocs\EFL\vendor\codeception\codeception\src\Codeception\Codecept.php:165
    0.8143    8978968  11. Codeception\SuiteManager->addToSuite() C:\xampp\htdocs\EFL\vendor\codeception\codeception\src\Codeception\SuiteManager.php:98
    0.8154    8979112  12. Codeception\TestCase\Cest->configEnv() C:\xampp\htdocs\EFL\vendor\codeception\codeception\src\Codeception\SuiteManager.php:107

FATAL ERROR. TESTS NOT FINISHED.
Cannot access protected property FooCest::$env
in C:\xampp\htdocs\EFL\vendor\codeception\codeception\src\Codeception\TestCase\Cest.php:177
```

functional.suite.yml
```
# Codeception Test Suite Configuration

# suite for functional (integration) tests.
# emulate web requests and make application process them.
# Include one of framework modules (Symfony2, Yii2, Laravel4) to use it.

class_name: FunctionalTester
modules:
    enabled: [Filesystem, FunctionalHelper, Symfony2]
    config:
      Symfony2:
        app_path: 'app'
        environment: 'dev'
```

unit.suite.yml
```
# Codeception Test Suite Configuration

# suite for unit (internal) tests.
class_name: UnitTester
modules:
    enabled: [Asserts, UnitHelper, Symfony2]
    config:
      Symfony2:
        app_path: 'app'
        environment: 'dev'
```

FooCest
```
class FooCest extends \Codeception\TestCase\Test
{
    public function _before(\FunctionalTester $I)
    {

    }

    public function _after(\FunctionalTester $I)
    {

    }

    public function testFooBar(\FunctionalTester $I)
    {
        $foo = true;
        $this->assertTrue($foo);
    }
}
```

Thanks
