### ISSUE TITLE
Operation timed out after 30003 milliseconds

### ISSUE THREAD

**Issue by henriqueoliveira** [Codeception/Codeception#1918]
Hello everybody, this is a wonderful project, thanks for everyone envolved, i cant find a solution for a timeout problem, i think its a bug, I m using ` 2.1.*@dev ` version and tried all solution i could find on internet.
I get this error:

```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 30003 milliseconds with 0 bytes received
```

I m trying to change the timeout value for $I->sendGET method, but I changed it on the file "acceptance.suite.yml" and its not working, here is how my acceptance.suite.yml looks like:

```yaml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
        - REST
    config:
        REST:
            timeout: 90 # or 90000 the same result
        PhpBrowser:
            url: 'http://localhost/myapp/'
```
