### ISSUE TITLE
2.1-beta - SOAP ModuleRequireException: Connection client is not available

### ISSUE THREAD

**Issue by metheoryt** [Codeception/Codeception#1930]
I try to execute an API suite test using SOAP module. 
My `api.suite.yml`:
```yml
class_name: ApiTester
modules:
    enabled: [PhpBrowser, SOAP, \Helper\Api]
    config:
      SOAP:
        endpoint: https://www.example.com/api/wsdl
      PhpBrowser:
        url: https://www.example.com
``` 
I have ran `build` after configuring suite. Then i tried to run simple cept:
```php
<?php
use Codeception\Util\Soap;

$I = new ApiTester($scenario);
$I->wantTo('Try this cool stuff');
$I->sendSoapRequest('coreLoginRequest',Soap::request()->username
                                                          ->val('metheoryt')
                                                              ->parent()
                                                          ->password
                                                              ->val('123456')
                                                              ->parent()
                                                          ->captcha
                                                              ->val(''));
```
Codeception answers on this:
>[ModuleRequireException] SOAP module requirements are not met!
Connection client is not available.

**Comment by DavertMik** [comment]
You should set dependencies:

```
      SOAP:
        endpoint: https://www.example.com/api/wsdl
        depends: PhpBrowser
```

probably an error message should be more descriptive in this case

**Comment by metheoryt** [comment]
I tried to run cept with this config - it fails with the same exception
Then I saw dependency message inside `Codeception\Util\SOAP` with example config piece
```yml
modules:
    enabled: [PhpBrowser, SOAP, \Helper\Api]
    depends:
      SOAP: PhpBrowser
``` 
and try to run cept after configuring ApiTester like this and `build`. But I got the same exception again.
I tried to debug cept, and it seems to `_inject` function didn't inject anything in `SOAP::innerModule`.

**Comment by DavertMik** [comment]
Oh, looks like you passed 2 spaces in `  SOAP: PhpBrowser` instead of 4. Looks like an indentation issue

**Comment by metheoryt** [comment]
I'm afraid that problem isn't in indentation. I fixed the config and tried to run cept again, but caught the same error again. Fresh listing of config below:
```yml
class_name: ApiTester
modules:
    enabled: [PhpBrowser, SOAP, \Helper\Api]
    config:
        PhpBrowser:
            url: https://www.example.com
        SOAP:
            endpoint: https://www.example.com/api/wsdl
            depends: PhpBrowser
```

**Comment by mhightower** [comment]
I'm having the same problem:
<pre>
class_name: ApiTester
modules:
    enabled:
        - PhpBrowser:
             url: http://example.com/ExampleDev/WebServices/
        - SOAP:
             depends: PhpBrowser
             endpoint: http://example.com/ExampleDev/WebServices/WorkflowEngineSOA.asmx?WSDL
</pre>
config builds just fine but I get 

    [ModuleRequireException] SOAP module requirements are not met!
    Connection client is not available. 

in version 2.1.1

**Comment by Noles** [comment]
@DavertMik I can confirm this in current 2.1 release too. I think the cause of the problem is that the SOAP module does not implement the "DependsOnModule" Interface. So the framework or phpbrowser will never be injected.

**Comment by alexg-dev** [comment]
@DavertMik The same error here:

```yaml
class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - PhpBrowser
        - SOAP:
            depends: PhpBrowser
            endpoint: http://endpoint.com
    config:
        PhpBrowser:
            url: http://localhost
```
