### ISSUE TITLE
Codeception error: Class db does not exist

### ISSUE THREAD

**Issue by JePaFe** [Codeception/Codeception#1959]
I try to run codeception tests on MAMP. This is my config:

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=testing'
            user: 'homestead'
            password: 'secret'
            dump: tests/_data/dump.sql
            populate: true
            cleanup: false
        WebDriver:
            url: 'http://testing.app/'
            browser: firefox
            window_size: 1024x768
            wait: 100
            capabilities:
                unexpectedAlertBehaviour: 'accept'
```

When run:

```
./vendor/bin/codecept run functional
```

I get Class db does not exist error

My version of codeception is 2.1.x@dev and Laravel 5
Thanks in advance for help.
