### ISSUE TITLE
Laravel5 module - cleanup is not working

### ISSUE THREAD

**Issue by daniel-rosiak** [Codeception/Codeception#1972]
Issue: Laravel5 module is not cleaning data after tests
Branch: master
Latest commit: 86b9ddfdd8

Sadly it works perfecly on https://github.com/janhenkgerritsen/codeception-laravel5 so i had to do rollback to it

@janhenkgerritsen can You please look into it?

my api.suite.yml:
```
class_name: ApiTester
modules:
    enabled: [Laravel5, REST, ApiHelper, Asserts]
    config:
        REST:
            depends: PhpBrowser
            url: 'http://local.url/api/'
        Laravel5:
            environment_file: .env.testing
            cleanup: true
```
