### ISSUE TITLE
Problem with laravel5 seeAuthentication after update

### ISSUE THREAD

**Issue by dominiquedutra** [Codeception/Codeception#1975]
On codecept console functional

```
$I = new \FunctionalTester($scenario);
$I->amOnPage('auth/login');
$I->fillField(['id' => 'email'], 'admin@admin.com');
$I->fillField(['id' => 'password'], 'admin123');
$I->click(['id' => 'btn_login']);
```

  [Uri] http://domain.com/auth/login
  [Method] POST
  [Parameters] {"_token":"fvYpLxzhECj4tpF5EztiIgcQD3mhaF1uwlfaIOXd","email":"admin@admin.com","password":"admin123","":null}
  [Response] 200
  [Page] http://domain.com/home
  [Cookies] {"laravel_session":"eyJpdiI6InNjYTdKZ0hhY2tqbEtoYjJCRkYyMmc9PSIsInZhbHVlIjoiUXp4cGJPYndcLzZaRE53Sml5S2NpYVUxVlZHRlBkcDdGZ251bk1hMm5hMFhUWGNVclp2bXhNVEFnMlJkbXF5SEJVczhnSk1vYlwvVVIrNW55TFwvVytCQmc9PSIsIm1hYyI6ImU5ODFiMzE3OTMyZWNlNmRkODFiODYxOThlMjY2YWEyMGYyNTY4ZWQ0MGVmOTY0NTI2NDM5NmUyNDY2NWM1NWYifQ=="}

The redirect /home shows that the user was logged in.
Then:

```
$I->seeAuthentication();
```

fail User is not logged in
Failed asserting that false is true.

Function is returning false.

This is my functional.yml

```
class_name: FunctionalTester
modules:
    enabled: [Filesystem, FunctionalHelper, Laravel5, Db, REST, Asserts, PhpBrowser]
    config:
        Laravel5:
            cleanup: false
            environment_file: .env.testing
        REST:
            depends: PhpBrowser
            url: 'http://domain.com'
```

Thanks.
