### ISSUE TITLE
mongodb driver does not allow whitespace in the filename of its dumps

### ISSUE THREAD

**Issue by christoph-hautzinger** [Codeception/Codeception#1997]
I had the problem within jenkins where we have paths like this:

`jenkins@build01:~/workspace/00 - conspecton - Build - Build/products`

setting config

```
MongoDb:
  dsn: 'localhost:27017/conspecton_test'
  user: ''
  password: ''
  dump: 'tests/_data/product_platform.js'
  populate: true
  cleanup: false
```

only cleared the whole database without loading the fixtures
