### ISSUE TITLE
Laravel 5 routes don't resolve correctly

### ISSUE THREAD

**Issue by JonoB** [Codeception/Codeception#2000]
I've set up the Laravel 5 module, along with a few others. For some reason, the base url is not being constructed properly inside of the tests when using the `route()` function.

```yml
// api.suite.yml
class_name: ApiTester
modules:
    enabled: [Laravel5, REST, ApiHelper, Asserts]
    config:
        Laravel5:
            environment_file: .env.testing
```

```php
// .env.testing
APP_ENV=testing
APP_DEBUG=true
APP_KEY=whatever
APP_URL=http://fsadmin.dev

DB_DEFAULT=testing
```

```php
class AuthCest
{
    public function test_logout(ApiTester $i)
    {
        $i->assertEquals('testing', \App::environment()); // passes  
        $i->assertEquals('http://fsadmin.dev', \Config::get('app.url')); // passes

        $i->assertEquals('http://fsadmin.dev/api/auth/logout', route('api.auth.logout')); 

        // Failed asserting that two strings are equal.
        --- Expected
       +++ Actual
       -'http://fsadmin.dev/api/auth/logout'
       +'http://:/api/auth/logout#'
    }
}
```

Basically, all urls constructed from route are missing the base URL (fsadmin.dev), and I have no idea why.

Any help much appreciated.
