### ISSUE TITLE
Is it possible to enable extensions per environment?

### ISSUE THREAD

**Issue by igorsantos07** [Codeception/Codeception#2031]
Phantoman is a cool extension that turns on and off PhantomJS when tests begin and finish running.

Would be cool, tho, to enable it only on a given environment, so if we have different envs for different browsers, PhantomJS would only run on its own environment.

**Comment by DavertMik** [comment]
I thought you can enable it per environment...
You can list it in environment config. Or not?

**Comment by igorsantos07** [comment]
It seems it ignores `extensions` entry on suite settings; it only works if you add the entry to the main settings file. This makes no difference:

```yaml
class_name: AcceptanceTester
modules:
  enabled:
    - WebDriver
    - AcceptanceHelper
  config:
    WebDriver:
      url: http://localhost
      browser: 'phantomjs'
extensions:
  enabled:
    - Codeception\Extension\Phantoman
```

**Comment by grantlucas** [comment]
Based on issue #1370, I'll be adding support shortly to Phantoman so that it only starts for configured suites. This will be dependant on Codeception 2.1+ however. I just haven't had the chance to get to coding it up yet :smile: 

I believe once I add support for the [new `MODULE_INIT` event](https://github.com/Codeception/Codeception/commit/1cbddbb0058d9f1350b08e30fac29912f7d807b1) I should be able to determine if Phantoman is enabled for the current suite and act accordingly.

I believe for environment support, though I haven't tried it yet, you would just need to enable Phantoman for a specific environment instead of the whole suite.

```yaml
class_name: AcceptanceTester
modules:
  enabled:
    - WebDriver
    - AcceptanceHelper
  config:
    WebDriver:
      url: http://localhost
      browser: 'firefox'
env:
    phantom:
        modules:
            config:
                WebDriver:
                    browser: 'phantomjs'
        extensions:
            enabled:
                - Codeception\Extension\Phantoman
```

@DavertMik Does ^that make sense?
