### ISSUE TITLE
Coverage throw directory not found Exception on windows 7

### ISSUE THREAD

**Issue by herb123456** [Codeception/Codeception#2061]
My config:

```
coverage:
    enabled: true
    whitelist:
        include:
            - xxx\ooo\yyy
```

and the Exception message is

```
[InvalidArgumentException]
The "D:\Projects\xxx/ooo/yyy" directory does not exist.
```

look at the slash in the error message

its different with my config

and there have two different slash in the final path 

so it could throw exception

how can I fix it?
