### ISSUE TITLE
v2.0.9 selectOption() throws InvalidArgumentException: Unreachable field ""

### ISSUE THREAD

**Issue by daison12006013** [Codeception/Codeception#2062]
So I am using a chrome extension to get the exact xpath, I was able to use ``grabTextFrom()`` function to show the lists of options in the select tag. When trying to use ``grabValueFrom()`` it returns a ``NULL``.

Here's my codeception code
```
$el = "//div[@class='formBlock']/div[@class='row form-group'][2]/div[@class='col-sm-4'][1]/div[@class='form-group']/select[@class='citySelection form-control input-sm']";
//dd($this->I->grabTextFrom($el));
$city_name = $this->cities[array_rand($this->cities)];
$city = City::where('name', '=', $city_name)->first();
$this->I->selectOption($el, $city->id);
````

Here's the output fail file.
``http://pastebin.com/raw.php?i=VNc7Z6Y8``

When using the ``grabTextForm($el)``:
``http://pastebin.com/raw.php?i=M8Xnd1q9``

Thrown InvalidArgumentException from CLI:
``http://pastebin.com/raw.php?i=FT8FeRDq``

This is an acceptance test, this is the config in acceptance.suit.yml:
````
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
        - Laravel4
        - Db
    config:
        PhpBrowser:
            url: '<I didn't include here, for security purposes>'
        Laravel4:
            cleanup: false
````

Using the input tag works well, while this select tag, really not working, I also tried creating a simple html just to test, but still 2.0.9 was failing to select a value.

Fyi,
I'm using codeception 2.0.9 for my old Laravel4 Framework Project.
