### ISSUE TITLE
Group definitions for acceptance Cest files not working

### ISSUE THREAD

**Issue by dlfxhappy** [Codeception/Codeception#2088]
I'm currently using 2.0.15 and I can't get Codeception to execute acceptance tests which are defined in  acceptance.suite.yml. The config is pretty much the same as recommended in http://codeception.com/docs/07-AdvancedUsage

groups:
  quick: [acceptance/stories/UserResetPasswordCest.php:someTestFuntion]

The only way I can get groups to work is by using the @group annotation within the Cest, which has a few drawbacks compared to the other method.
Any ideas?

**Comment by dlfxhappy** [comment]
Quick Update: It was a configuration issue with the directory structure. If you keep the codeception.yml in the same directory as the suite ymls you have to really pay attention to the paths. After some trial and error this config seems to work (on Windows):

codeception.yml (in testproject root)
```yml
actor: Tester
paths:
    tests: .
    log: _output
    data: _data
...
```

acceptance.suite.yml (also testproject root)
```yml
groups:
    quick: [./acceptance/stories/someStoryCest.php:tryToTestMe]
    critical: ./acceptance/slow
...
```
