### ISSUE TITLE
REST module brakes if client is declared after it in version 2.0.15

### ISSUE THREAD

**Issue by pedrochaves** [Codeception/Codeception#2100]
I have some API tests using the `Silex` and `REST` modules. When using the version `2.0.14` everything was working fine, but right after updating to version `2.0.15` I got the fatal error `Call to a member function request() on null` on [the line 391 of the REST module] (https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/REST.php#L391).

After some debugging I found out that just changing the order of the declaration of the modules in the suite config solved the problem, so what used to be 
```yaml
modules:
    enabled:
        - ApiHelper
        - REST
        - Db
        - Silex
# Modules config
```

Became this
```yaml
modules:
    enabled:
        - ApiHelper
        - Silex
        - REST
        - Db
# Modules config
```

I also tested changing the `Silex` module to `PhpBrowser` and the same error occurred, so I assume it is the order of declaration. Haven't got time to look at what introduced the issue, but maybe I can look later.
