### ISSUE TITLE
Error on test_entry_url for Yii2 module

### ISSUE THREAD

**Issue by switchy** [Codeception/Codeception#2110]
I have a problem with Yii2-module.

codeception.yml:
```yaml
...
    config:
        # the entry script URL (without host info) for functional and acceptance tests
        # PLEASE ADJUST IT TO THE ACTUAL ENTRY SCRIPT URL
        test_entry_url: /index-test.php
...
```

When i start functional test, got the error:
```shell
Can't be on page "/index-test.php/about/":
yii\base\ErrorException: array_replace(): Argument #2 is not an array

Scenario Steps:
1. I am on page "/index-test.php/about/"
                                                                        
  [yii\base\ErrorException] array_replace(): Argument #2 is not an array  
                                                                          
#1  yii\base\ErrorHandler->handleError
#2  /root/.composer/vendor/symfony/browser-kit/CookieJar.php:210
#3  /root/.composer/vendor/symfony/browser-kit/Client.php:316
#4  Codeception\Module\Yii2->amOnPage
#5  /usr/local/www/website/www/tests/front/codeception/functional/FunctionalTester.php:484
#6  /usr/local/www/website/www/vendor/yiisoft/yii2-codeception/BasePage.php:77
#7  /usr/local/www/website/www/tests/front/codeception/functional/AboutCept.php:7
#8  Codeception\TestCase\Cept->testCodecept
```

Error raise when HTTP_HOST is empty on /root/.composer/vendor/symfony/browser-kit/Client.php

/vendor/codeception/codeception/src/Codeception/Module/Yii2.php:22 force set empty HTTP_HOST when parse from test_entry_url. Next vendor/symfony/browser-kit/Client.php:113 merge empty HTTP_HOST with their server - vars. And finaly got error when parse_url return not array on vendor/symfony/browser-kit/CookieJar.php:210

My solve, set HTTP_HOST to 'localhost', when it empty on vendor/codeception/codeception/src/Codeception/Module/Yii2.php:
```php
    public function _before(\Codeception\TestCase $test)
    {
        $this->client = new \Codeception\Lib\Connector\Yii2();
        $this->client->configFile = \Codeception\Configuration::projectDir().$this->config['configFile'];
        $mainConfig = \Codeception\Configuration::config();

        if (isset($mainConfig['config']) && isset($mainConfig['config']['test_entry_url'])){
            $this->client->setServerParameter('HTTP_HOST', (string) parse_url($mainConfig['config']['test_entry_url'], PHP_URL_HOST));
            $this->client->setServerParameter('HTTPS', ((string) parse_url($mainConfig['config']['test_entry_url'], PHP_URL_SCHEME)) === 'https');
        }
        $this->app = $this->client->startApp();

        if ($this->config['cleanup'] and isset($this->app->db)) {
            $this->transaction = $this->app->db->beginTransaction();
        }
    }
```

to 

```php
    public function _before(\Codeception\TestCase $test)
    {
        $this->client = new \Codeception\Lib\Connector\Yii2();
        $this->client->configFile = \Codeception\Configuration::projectDir().$this->config['configFile'];
        $mainConfig = \Codeception\Configuration::config();

        if (isset($mainConfig['config']) && isset($mainConfig['config']['test_entry_url'])){
            $host = (string) parse_url($mainConfig['config']['test_entry_url'], PHP_URL_HOST);
            $this->client->setServerParameter('HTTP_HOST', strlen($host) ? $host : 'localhost');
            $this->client->setServerParameter('HTTPS', ((string) parse_url($mainConfig['config']['test_entry_url'], PHP_URL_SCHEME)) === 'https');
        }
        $this->app = $this->client->startApp();

        if ($this->config['cleanup'] and isset($this->app->db)) {
            $this->transaction = $this->app->db->beginTransaction();
        }
    }
```

**Comment by switchy** [comment]
Excuse me, the problem was found in 2.0 branch.

In branch 2.1 the problem is then the same symptom.

**Comment by Ragazzo** [comment]
@DavertMik @samdark why this fix in `_before` with host variables was made? Is not enough that we already set values in [`_bootstrap.php`](https://github.com/yiisoft/yii2-app-basic/blob/master/tests/codeception/_bootstrap.php)?

**Comment by SergioMadness** [comment]
Hello.
Have the same error in functional test.

Trace:
```php
←[35;1mEnsure login page works←[39;22m (RegistrationCept)
Scenario:
* I am on page "site/login"
array_replace(): Argument #2 is not an array
#0 C:\Users\user\AppData\Roaming\Composer\vendor\symfony\browser-
kit\Client.php(318): Symfony\Component\BrowserKit\CookieJar->allValues()
#1 C:\Users\user\AppData\Roaming\Composer\vendor\codeception\code
ception\src\Codeception\Lib\InnerBrowser.php(75): Symfony\Component\BrowserKit\C
lient->request()
etc...
```

Exception throws in CookieJar.php at line:
```php
$parts = array_replace(array('path' => '/'), parse_url($uri));
```
because of
```php
$uri='http:///site/login';
parse_url($uri) ===false;
```

Codeception yml:
```yml
namespace: tests\codeception\backend
actor: Tester
paths:
    tests: .
    log: _output
    data: _data
    helpers: _support
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
config:
    # the entry script URL (without host info) for functional and acceptance tests
    # PLEASE ADJUST IT TO THE ACTUAL ENTRY SCRIPT URL
    test_entry_url: /backend/web/index-test.php
```

functional.suite.yml
```yml
class_name: FunctionalTester
modules:
    enabled:
      - Filesystem
      - Yii2
    config:
        Yii2:
            configFile: '../config/backend/functional.php'
```

_bootstrap.php
```php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');

defined('YII_APP_BASE_PATH') or define('YII_APP_BASE_PATH',
        dirname(dirname(dirname(__DIR__))));

defined('YII_BACKEND_TEST_ENTRY_URL') or define('YII_BACKEND_TEST_ENTRY_URL',
        \Codeception\Configuration::config()['config']['test_entry_url']);
defined('YII_TEST_BACKEND_ENTRY_FILE') or define('YII_TEST_BACKEND_ENTRY_FILE',
        YII_APP_BASE_PATH.'/backend/web/index-test.php');

require_once(YII_APP_BASE_PATH.'/vendor/autoload.php');
require_once(YII_APP_BASE_PATH.'/vendor/yiisoft/yii2/Yii.php');
require_once(YII_APP_BASE_PATH.'/common/config/bootstrap.php');
require_once(YII_APP_BASE_PATH.'/backend/config/bootstrap.php');

// set correct script paths
// the entry script file path for functional and acceptance tests
$_SERVER['SCRIPT_FILENAME'] = YII_TEST_BACKEND_ENTRY_FILE;
$_SERVER['SCRIPT_NAME']     = YII_BACKEND_TEST_ENTRY_URL;
$_SERVER['SERVER_NAME']     = 'localhost';

Yii::setAlias('@tests', dirname(dirname(__DIR__)));
```

Test:
```php
use tests\codeception\backend\FunctionalTester;

/* @var $scenario Codeception\Scenario */
$I = new FunctionalTester($scenario);
$I->wantTo('ensure login page works');
$I->amOnPage(['site/login']);
```
