### ISSUE TITLE
Class `Codeception\Extension\RunFailed` is not defined.

### ISSUE THREAD

**Issue by bendauphinee** [Codeception/Codeception#2111]
When attempting to run the latest stable version:

```
Codeception PHP Testing Framework v2.1.0
Powered by PHPUnit 4.7.5 by Sebastian Bergmann and contributors.

  [Codeception\Exception\ConfigurationException]
  Class `Codeception\Extension\RunFailed` is not defined. Autoload it or include into '_bootstrap.php' file of 'tests' directory
```

Steps to reproduce:
1 - Download phar: wget http://codeception.com/codecept.phar
2 - Bootstrap: php codecept.phar bootstrap
3 - Generate test: php codecept.phar generate:cept acceptance Welcome
4 - Run: php codecept.phar run

```
[root@localhost ~]# php -i
phpinfo()
PHP Version => 5.5.25

System => Linux localhost.localdomain 3.10.0-229.4.2.el7.x86_64 #1 SMP Wed May 13 10:06:09 UTC 2015 x86_64
Build Date => May 15 2015 05:29:08

[root@localhost ~]# cat codeception.yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed  # I attempted this with 
                                           # enabled: [Codeception\Extension\RunFailed]
                                           # but that also failed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```
