### ISSUE TITLE
PHP Fatal error:  Access to undeclared static property: Codeception\Module\Doctrine2::$em 

### ISSUE THREAD

**Issue by kimpellikaan** [Codeception/Codeception#2116]
After updating to codeception 2.1 I get an error passing the Entity Manager to the Doctrine 2 module. 

`PHP Fatal error:  Access to undeclared static property: Codeception\Module\Doctrine2::$em `

I have modified my unit.suite.yml to load the EM through a callback class as following:

```
class_name: UnitTester
modules:
    enabled: [ZF1, Doctrine2, Asserts, UnitHelper]
    config:
        Doctrine2:
            cleanup: true
            connection_callback: [UnitTester, getEntityManager]
```

The problem is that the ZF1 app also needs the same instance of the Entity Manger, else the tests will not work properly. In the bootstrap we used to get the $em like `\Codeception\Module\Doctrine2::$em;` but this no longer works.

Is this a bug, or am I doing this wrong?
