### ISSUE TITLE
Support NTLM option for Guzzle Client

### ISSUE THREAD

**Issue by jfgrissom** [Codeception/Codeception#2130]
Guzzle uses curl so this NTLM authentication example works great:
curl --ntlm --user username:userpassword http://some.domain.tld/

Is there an option somewhere to set PhpBrowser to use NTLM for authentication?

I've tried many things (cross referencing the Guzzle docs and looking at the options available in the PHPBrowser Module)

```
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
    config:
        PhpBrowser:
            url: 'http://host.domaint.tld/'
            curl: 
                CURLOPT_HTTPAUTH: CURLAUTH_NTLM
                CURLOPT_USERPWD: 'validUser:usersPasssword'
```

**Comment by DavertMik** [comment]
Looks like you are trying to pass value of a constant `CURLAUTH_NTLM`, however you are passing the string "CURLAUTH_NTLM" itself. You can use the real value of a constant, which is `8` or send a Pull Request to PhpBrowser module which will improve using of AUTH strategies with Guzzle

**Comment by jfgrissom** [comment]
Hi DavertMik,

I see.  I'll take a look at the module to see what I can do to make these options available.

Thanks very much for this. This works as expected.

```
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
    config:
        PhpBrowser:
            url: 'http://host.domaint.tld/'
            curl: 
                CURLOPT_HTTPAUTH: 8
                CURLOPT_USERPWD: 'validUser:usersPasssword'
```
