### ISSUE TITLE
delete_successful not working

### ISSUE THREAD

**Issue by dynasource** [Codeception/Codeception#2160]
the record extension looks very promising, but it only creates screenshots with errors though, despite setting delete_successful to false or true.

``` yml
extensions:
    enabled: 
        Codeception\Extension\Recorder:
            delete_successful: false
```

Codeception PHP Testing Framework v2.1.0
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

**Comment by DavertMik** [comment]
Ok, could you take a look into code? It is very first version of that extension so sush stupid errors are possible

**Comment by dynasource** [comment]
I will

**Comment by reinholdfuereder** [comment]
I just tested this (with Codeception v2.5.4) and I claim it works as expected; which comes to no surprise as this issue is quite old.

@DavertMik Do you mind closing this issue with "Fixed" (or so)?

**Comment by Naktibalda** [comment]
It looks like it was fixed in 2.1.2
https://github.com/Codeception/Codeception/commit/441086c911f48198eddfbb343836d9d259940a9e#diff-343943e77ba6082470e54544f75a02a5

**Comment by reinholdfuereder** [comment]
@Naktibalda Thanks for the confirmation => Do you mind closing this issue with "Fixed" (or so) instead of @DavertMik?

**Comment by Nebulosar** [comment]
I'm using the newest codeception version, a.k.a. `"codeception/codeception": "*"`, and I also am having trouble with this parameter.

I looked into the Recorder code but could not find a simple  explanation.  
I added the recorder in my `codeception.yml` file AND in my `acceptance.suite.yml` file, but neither of them works:
```yaml
extensions:
  enabled:
    - Codeception\Extension\Recorder:
        -  delete_orphaned: true
```
It keeps adding records. 😞  

My full codeception file:
```yaml
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
extensions:
  enabled:
    - Codeception\Extension\RunFailed
    - Codeception\Extension\Recorder:
        - delete_orphaned: true
settings:
  bootstrap: _bootstrap.php
  memory_limit: 1024M
  colors: true
  suite_class: \PHPUnit_Framework_TestSuite
modules:
  config:
    Yii2:
      configFile: 'config/web.development.php'
coverage:
  enabled: true
  low_limit: 65
  high_limit: 80
  whitelist:
    include:
      - models/*
      - controllers/*
      - commands/*
      - mail/*
```
As one can see, i am using Yii2.  
If I can/need to provide more info, I'm happy to.
