### ISSUE TITLE
Bootstrap with custom directory does not create /codeception.yml

### ISSUE THREAD

**Issue by roland-jungwirth** [Codeception/Codeception#2167]
When initialising Codeception 2.1.1, using the command
```
php codecept.phar bootstrap src/bundle/ --namespace frontend
```
everything is generated, except for the codeception.yml file in the root directory. When creating the file with
```
include:
  - src/bundle
paths:
  log: log
```
everything works as expected.

**Comment by tomtomsen** [comment]
codeception.yml should be in src/bundle/

```
Usage:
  bootstrap [options] [--] [<path>]

Arguments:
  path                          custom installation path [default: "."]
```

**Comment by roland-jungwirth** [comment]
If you are (as in my case) running Codeception in a Symfony project (where tests - in my opinion - should be in the bundle), the include path would be something like
```
src/ACME/MyBundle/
```
It is generated this way. However, you cannot run the anything from the root directory without adding a codeception.yml to that directory, including the above path.

**Comment by tomtomsen** [comment]
so your folder structure is something like this:
```
|- codeception.yml
|- src/
|-- bundle/
|--- tests/
```

it should work, if you modifiy the paths settings like so:
```
namespace: frontend\
actor: Tester
paths:
    tests: src/bundle/tests
    log: src/bundle/tests/_output
    data: src/bundle/tests/_data
    support: src/bundle/tests/_support
    envs: src/bundle/tests/_envs
```

now you can run codeception from your root directory
