### ISSUE TITLE
Cannot overwrite webdriver with multiple environments.

### ISSUE THREAD

**Issue by sharpner** [Codeception/Codeception#2178]
Hi guys! Great project :-)

I have a small problem and I believe it to be a bug.

Using an acceptance suite, I configured multiple environments.
```
modules:
    config:
      WebDriver:
        browser: 'chrome'
        url: http://localhost
        host: selenium.test
    enabled:
        - WebDriver
```
And now custom environments like in your documentation:
```
env:
  chrome:
    #default
  firefox:
    modules:
      config:
        WebDriver:
          browser: 'firefox'
          port: 4445
  staging:
    modules:
      config:
        WebDriver:
          url: 'http://staging.localhost'
  development:
    modules:
      config:
        WebDriver:
          url: 'http://development.localhost'
```

Running --env chrome,staging and --env chrome,development work as expected.

But running --env firefox,staging and --env firefox,development causes the following error:

```
 [UnknownServerException]
  The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/inde
  x.html
```

I suspect it does not overwrite, or preloads the driver for chrome. 

Can you guys help me out?
