### ISSUE TITLE
Can't codecept build with Laravel 5.1 / Codecept 2.1

### ISSUE THREAD

**Issue by dominiquedutra** [Codeception/Codeception#2198]
Hey guys,

I migrated my project to Laravel 5.1 (v5.1.8) and Codeception to 2.1 (2.1.1).

Was able to get my Acceptance tests working easily. The new Support Class injection is great!

Hit a problem with my Functional tests though. I can't build when I enable the Laravel5 module, so my first question is: Is the Laravel 5 Module compatible with Laravel 5.1 LTS?

(I think the anwser is yes because I had Codeception 2.0 working with Laravel 5.1 RC before I did the full upgrade).

Anyways, here is my codecept functional yml file:

```
class_name: FunctionalTester
modules:
    enabled:
        - Laravel5:
            cleanup: false
            environment_file: .env.testing
        - Filesystem
        - Db
        - Asserts
        - \Helper\Functional
```

Codecept build gives me this:

```
PHP Catchable fatal error:  Argument 1 passed to Codeception\Module::__construct() must be an instance of Codeception\Lib\ModuleContainer, none given, called in /var/www/App/laravel/vendor/janhenkgerritsen/codeception-laravel5/src/Codeception/Module/Laravel5.php on line 70 and defined in /var/www/App/laravel/vendor/codeception/codeception/src/Codeception/Module.php on line 52
```

If I remove the Laravel5 entry it builds perfectly.

Thanks!
