### ISSUE TITLE
upgrading v2.1.0-beta to v2.1.0/v2.1.1 takes much more ram/time

### ISSUE THREAD

**Issue by christoph-hautzinger** [Codeception/Codeception#2203]
first of all I have a small functional test suite written in v2.1.0-beta, everything looks like this:

```
notroot@conspectondev:/var/www/conspecton/products$ bin/codecept run functional
Codeception PHP Testing Framework v2.1.0-beta
Powered by PHPUnit 4.6.10 by Sebastian Bergmann and contributors.

Products.functional Tests (36) ------------------------------------------------------------------------------------------------------------------------------------------------------------
... all the tests go here
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 27.31 seconds, Memory: 444.50Mb

OK (36 tests, 100 assertions)
```

after upgrading to v2.1.0, the same test suite runs like this:

```
notroot@conspectondev:/var/www/conspecton/products$ bin/codecept run functional
Codeception PHP Testing Framework v2.1.0
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

Products.functional Tests (36) ------------------------------------------------------------------------------------------------------------------------------------------------------------
... all the tests go here again
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 1.2 minutes, Memory: 1219.50Mb

OK (36 tests, 100 assertions)
```

So time and memory increased by factor 3 - same result for v2.1.1

On our build server, I receive a message of "too many connections" when executing tests in v2.1.0/v2.1.1, It seems like a database connection is created for every functional test (checked this with `mytop` - connections increase and increase... none were closed). solved this with:

```php
<?php

namespace Conspecton\Component\Doctrine\Driver;

use Doctrine\DBAL\Driver\PDOMySql\Driver;

class MySqlTestDriver extends Driver
{
    public function connect(array $params, $username = null, $password = null, array $driverOptions = array())
    {
        static $conn = null;
        if (null === $conn) {
            $conn = parent::connect($params, $username, $password, $driverOptions);
        }
        return $conn;
    }
}
```
and configuring this driver class in `config_test.yml` but it seems very hackish to me :D. Had this same problem on my development machine, but I can't reproduce it anymore. 

The functional tests configuration looks like this:

```
# Codeception Test Suite Configuration

# suite for functional (integration) tests.
# emulate web requests and make application process them.
# Include one of framework modules (Symfony2, Yii2, Laravel4) to use it.

class_name: FunctionalTester
modules:
    enabled:
        - Db
        - MongoDb
        - Symfony2
        - MailCatcher
        - \Products\Helper\Functional

    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=conspecton_test'
            user: 'root'
            password: ''
            dump: 'tests/_data/users.sql'
            populate: true
            cleanup: false

        MongoDb:
            dsn: 'localhost:27017/conspecton_test'
            user: ''
            password: ''
            dump: 'tests/_data/product_platform.js'
            populate: true
            cleanup: false

        MailCatcher:
            url: 'http://127.0.0.1'
            port: '1080'

        Symfony2: {}

        \Products\Helper\Functional: {}

error_level: "E_RECOVERABLE_ERROR & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED"
```

ah - and the whole thing bases upon Symfony2

How can I help on this problem?
