### ISSUE TITLE
Codeception 2.1.1 environment configs issue

### ISSUE THREAD

**Issue by alex3190** [Codeception/Codeception#2229]
I am trying to run a test suite using configs from two environments (this is a feature implemented in 2.1 - http://codeception.com/docs/07-AdvancedUsage#Environments) and when I run bin/codecept suite --env env1,env2 it just runs full resolution on chrome, which is the default setting in codeception.yml. Here is the contents of env1 and env2:

env2:
```
modules:
    config:
        WebDriver:
            window_size: 320x450
            capabilities: []
```
env1:
```
modules:
    config:
        WebDriver:
            browser: 'firefox'
```
env1.yml and env2.yml are correctly placed in the _envs forlder, and the path to this folder is specified in codeception.yml.

The yml of the suite I am trying to run is:
```
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver
```
This is `codeception.yml`
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver
    config:
        WebDriver:
            url: 'http://myurl.com/'
            browser: 'chrome'
            host: 127.0.0.1
            port: 4444
            window_size: 1920x1080
```

**Comment by alex3190** [comment]
It worked without using the yml files in _envs, i just specified the envs i wanted to use in codeception.yml and both settings were accounted for.

Still couldn't manage to solve the initial problem , but maybe there's a setting that i'm missing or haven't filled out properly.

**Comment by DavertMik** [comment]
I didn't manage to reproduce it. My files:


`_envs/normal.yml`:
```
modules:
    config:
        WebDriver:
            browser: 'firefox'
```

`_envs/mobile.yml`

```
modules:
    config:
        WebDriver:
            window_size: 320x450
            capabilities: []
```

running `--env normal,mobile` executed firefox in 320x450 resolution. (there is no browser set in `acceptance.yml`)

**Comment by sjableka** [comment]
There was a bug with loading env configuration files (only .dist.yml files were loaded), but it has already been fixed https://github.com/Codeception/Codeception/commit/18c831303aaccadb7e234531dc91611e32f4ae73
@alex3190 Please update your Codeception if you still have this issue

**Comment by oparoz** [comment]
Confirmed as working in 2.1.2, using the new config syntax (docs should be updated),

`acceptance.suite.yml`
```
modules:
    enabled:
         - \Helper\Acceptance
         - WebDriver:
             url: http://localhost:8000
             browser: phantomjs
             window_size: 960x1080
             capabilities:
                 unexpectedAlertBehaviour: 'accept'
```
`_envs/firefox.yml`
```
modules:
    enabled:
         - WebDriver:
             browser: firefox
```

`php vendor/bin/codecept run --env firefox` get me a test with Firefox

**Comment by LoopKarma** [comment]
In addition to this issue I want to ask about possibility of storing config of some Codeception modules in separate file outside VSC. e.g: I have a project and everybody have different urls to project on their local machines and I think it would be nice to set `url` for `PhpBrowser` outside common config file.
###### common config in functional.suite.yml:
```yaml
class_name: FunctionalTester
modules:
    enabled:
        - PhpBrowser
        - Yii2
        - REST
        - ApiHelper
    config:
      Yii2:
        configFile: 'codeception/config/functional.php'
      REST:
        depends: PhpBrowser
```
###### personal config e.g project-name.yml:
```yaml
modules:
    enabled:
        - PhpBrowser
        - REST
    config:
      PhpBrowser:
        url: http://local.dev/v1/
      REST:
        url: http://local.dev/v1/
        depends: PhpBrowser
```
But it won't work because while `build` codeception looking for a PhpBrowser url config in functional.suite.yml
Any ideas?

**Comment by VoidWalker** [comment]
Still got this problem.
My **acceptance.suite.yml:**
```
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - \Helper\ISMWebDriver
    config:
        \Helper\ISMWebDriver:
            url: 'http://website.alpha.com/'
            browser: firefox
            window_size:1460x900
```
I have additional configuration **_envs\beta.yml**:
````
modules:
   config:
      \Helper\ISMWebDriver:
        url: 'https://website.beta.com/'
````
And configuration **_envs\mobile.yml**:
````
modules:
   config:
      \Helper\ISMWebDriver:
        window_size: 360x640
````

By running: **php codecept.phar run acceptance --env beta,mobile** I got my tests launched with mobile resolution but on http://website.alpha.com/.
with **php codecept.phar run acceptance --env mobile,beta** I got them on https://website.beta.com/ but with windows size from default config (1460x900)

What I see through debug, is that custom config files are merged with default config before merging together, that is why some configurations are overwritten
