### ISSUE TITLE
Functional tests don't run after adding Laravel5 module

### ISSUE THREAD

**Issue by andela-potemuyiwa** [Codeception/Codeception#2240]
@DavertMik @janhenkgerritsen 
```yml
 # Codeception Test Suite Configuration
#
# Suite for functional (integration) tests
# Emulate web requests and make application process them
# Include one of framework modules (Symfony2, Yii2, Laravel5) to use it

class_name: FunctionalTester
modules:
    enabled:
        - Laravel5
        - \Helper\Functional
```

If i remove Laravel5, functional tests run but i cant use any of the laravel methods, so it's still useless to me.
Once i add it back, the functional tests dont run again. Any reason why?..Been on this for days

**Comment by micaweb** [comment]
Don't ask me why, but If I do the following:

    - Laravel5:
        part: ORM

It enables me to use all Laravel and Eloquent methods.

**Comment by busayo** [comment]
@micaweb like this?

```php
# Codeception Test Suite Configuration
#
# Suite for functional (integration) tests
# Emulate web requests and make application process them
# Include one of framework modules (Symfony2, Yii2, Laravel5) to use it

class_name: FunctionalTester
modules:
    enabled:
        - \Helper\Functional
        - Laravel5:
          part: ORM
          environment_file: .env.testing
        - Asserts
```

..i just tried that now, still the functional tests don't run

**Comment by Naktibalda** [comment]
What do you mean by "don't run"?
Run them with -vvv flag and paste the output here.

Options have to be indented more:

```yaml
class_name: FunctionalTester
modules:
    enabled:
        - \Helper\Functional
        - Laravel5:
            part: ORM
            environment_file: .env.testing
        - Asserts
```
