### ISSUE TITLE
Access denied for user 'root'@'localhost' with Db module

### ISSUE THREAD

**Issue by rahul-cuelogic** [Codeception/Codeception#2246]
I am not able to use Db module in codeception, I am using 2.1.1 version and using mysql as database

I am getting following exception:

```                                                                                                                             
  [Codeception\Exception\ModuleException]                                                                                     
  Db: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: YES) while creating PDO connection
                                                                                                                              
```
```
Exception trace:
 () at APP_PATH/vendor/codeception/codeception/src/Codeception/Module/Db.php:165
 Codeception\Module\Db->connect() at APP_PATH/vendor/codeception/codeception/src/Codeception/Module/Db.php:142
 Codeception\Module\Db->_initialize() at APP_PATH/vendor/codeception/codeception/src/Codeception/SuiteManager.php:81
 Codeception\SuiteManager->initialize() at APP_PATH/vendor/codeception/codeception/src/Codeception/Codecept.php:198
 Codeception\Codecept->runSuite() at APP_PATH/vendor/codeception/codeception/src/Codeception/Codecept.php:172
 Codeception\Codecept->run() at APP_PATH/vendor/codeception/codeception/src/Codeception/Command/Run.php:184
 Codeception\Command\Run->execute() at APP_PATH/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at APP_PATH/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at APP_PATH/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at APP_PATH/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at APP_PATH/vendor/codeception/codeception/codecept:28
```
 I belive I have configured Db module correctly and credential are correct, since I am able to connect to Db with those credentials, I even tried the sample PDO connection script with which I was able to connect to database.

I have create new suite for it:
 Here is test.suite.yml content
```
class_name: FunctionalTester
modules:
    enabled:
        - \Helper\Functional
        - PhpBrowser
        - Db
        
    config:    
        PhpBrowser:
            url: 'http://dev.mysite.com'
        Db:
            dsn: 'mysql:host=localhost;dbname=mysite_test' 
            user: 'root'
            password: 'root'
            dump: 'tests/_data/mysite_test_dump.sql'
            populate: true
            cleanup: false
            reconnect: true

```
