### ISSUE TITLE
amOnPage using https

### ISSUE THREAD

**Issue by micaweb** [Codeception/Codeception#2259]
In my current Laravel app, some routes are accessible only through `https`.

This means when I use `$I->amOnPage` for these routes, the test will break.

Is there any kind of option to force `$I->amOnPage` to use `https`?

**Comment by janhenkgerritsen** [comment]
You can use absolute URLs in the `$I->amOnPage()` method, so something like this should work:
```
$I->amOnPage('https://localhost/my-secure-page');
```

**Comment by micaweb** [comment]
Ok!
What was bugging me is that if I use 'route()' combined with `amOnPage` or `amOnUrl` within `codeception` + `homestead`, then I receive `http://localhost` as the base url, instead of the url specified in `acceptance.suite.yml`.
That is completely annoying since rendered pages from broken tests won't have its layout properly displayed.
What i did in the end is a helper named `router()`, there I will use `route()` and `str_replace` `localhost` with the url specified in the `env` file.

**Comment by janhenkgerritsen** [comment]
You can try to set the Laravel `app.url` config variable for the `route()` calls, but then you still have the http/https problem.

**Comment by micaweb** [comment]
Do you know if I can grab `url` from the following with `codeception`?

```yml
env:
    local:
         modules:
            config:
                PhpBrowser:
                    url: 'http://my.app'
                    verify: false
                Laravel5:
                    environment_file: .env.testing-local
```
