### ISSUE TITLE
codecept class array is not defined trying to use Recorder

### ISSUE THREAD

**Issue by cloudEdwards** [Codeception/Codeception#2266]
I get an exception when trying to run tests with Recorder extension enabled.

I get the following 
```
Class "Array" is not defined. Autoload it or include into '_bootstrap.php' files of  'tests' directory
```

Not sure what to do here. Any ideas?

**Comment by cloudEdwards** [comment]
The problem was I had my extension path with the [] around it. So it thought that it was an Array class, rather than Logger or what ever. I changed it like this
```
extensions:
    enabled:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        - [Codeception\Extension\Logger]
        - [Codeception\Extension\Recorder]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        - Codeception\Extension\Logger
        - Codeception\Extension\Recorder
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
```

**Comment by cloudEdwards** [comment]
By the way, for any one having trouble getting this to work.

I first had to change the  ```api.suite.yml```  file, like this;
```
modules:
    config:
        enabled: [PhpBrowser, REST, ApiHelper]
        REST:
            url: http://tests.secure.retreat.guru/wp-json
            depends: PhpBrowser
```

Then I added the following to the ```codeception.yml``` file;
```
extensions:
    enabled:
        - Codeception\Extension\Logger
        - Codeception\Extension\Recorder
    config:
        Codeception\Extension\Recorder:
            delete_successful: false
```

Then I used ```codecept build```

And voila, it should work like a charm. Good luck
