### ISSUE TITLE
WebDriver not triggering JS events

### ISSUE THREAD

**Issue by montogeek** [Codeception/Codeception#2273]
Hi!
I am writing a Acceptance test using the WebDriver, in one step I am clicking the submit button, which should trigger the following JS event but it doesn't.

```javascript
(function() {
    var $horario = $('#horario');
    var $inputHorario = $('input[name="horario_json"]');
    var $registro = $('#registro');
    var selected = [];

    $horario.selectable({
        filter: '.selectable'
    });

    $registro.on('submit', function() {
        $('.ui-selected', $horario).each(function(index, elemento) {
            selected.push(elemento.dataset.dia + '|' + elemento.dataset.hora);
        });
        if(selected.length >= 1) {
           // Attach the JSON representation to the hidden input.
            $inputHorario.val(JSON.stringify(selected));
        }
    });
})();
```

Thanks!

**Comment by micaweb** [comment]
I have the same problem. I'm using Codeception 2.1.1 and PhantomJS.

**Comment by montogeek** [comment]
Hi @micaweb I solved it by setting correctly the acceptance tests:
```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - FunctionalHelper
        - Laravel4
        - Db
        - WebDriver
    config:
        WebDriver:
            url: 'http://monitores.dev/'
            browser: chrome
            capabilities:
                browserName: "chrome"
                javascriptEnabled: true,
                webStorageEnabled: true,
                nativeEvents: true
        Db:
            dsn: 'mysql:host=localhost;dbname=monitores_test'
            user: 'monitores'
            password: 'monitores'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
```
