### ISSUE TITLE
Laravel4 module not setting environment correctly

### ISSUE THREAD

**Issue by montogeek** [Codeception/Codeception#2276]
Hi!

I am trying to run some acceptance tests using the next configuration:
Codeception 2.0.13
App running inside a Vagrant machine

```yaml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - FunctionalHelper
        - Laravel4
        - Db
        - WebDriver
    config:
        WebDriver:
            url: 'http://monitores.dev/'
            browser: chrome
            capabilities:
                browserName: "chrome"
                javascriptEnabled: true,
                webStorageEnabled: true,
                nativeEvents: true
        Db:
            dsn: 'mysql:host=localhost;dbname=monitores_test'
            user: 'monitores'
            password: 'monitores'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
env:
    acceptance:
        modules:
            config:
                Laravel4:
                    environment: acceptance
                Db:
                    dsn: 'mysql:host=192.168.22.10;dbname=monitores_test'
                    user: 'monitores'
                    password: 'monitores'
                    dump: 'tests/_data/dump.sql'
                    populate: true
                    cleanup: true
```

I am executing `vendor/bin/codecept run acceptance --steps --env acceptance` form the host machine:

Doing a simple `dd(\App::environment())` returns `local`.

Shouldn't it return `acceptance`?

Thanks!
