### ISSUE TITLE
[PhpBrowser] Incorrect error message when proxy is down

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#2289]
I discovered this issue while testing #2149

I used configuration:
```yaml
class_name: ApiGuy
modules:
    enabled:
        - \Helper\Api
        - PhpBrowser:
            url: http://localhost:8010
            proxy: localhost:8081
        - REST:
            url: http://localhost:8010
            depends: PhpBrowser
```

Test code
```php
$I->sendGET('http://google.com');
```
I started http daemon with php -S 127.0.0.1:8010 -t tests/data/ but I didn't have proxy server running.

The error I got was "[ConnectionException] Couldn't connect to http://localhost:8010. Please check that web server is running"

Correct message would tell me that the proxy server at localhost:8081 is not running.
