### ISSUE TITLE
save my webpage as HTML

### ISSUE THREAD

**Issue by karunakarkarna** [Codeception/Codeception#2294]
I am trying to save my webpage as html, there is any alternative ways to save my page as html

I am trying to enter key using presskey but instead of enter key i want to use "Ctrl + S" to save page as html .

```
         $I->pressKey('Xpath',WebDriverKeys::ENTER);
         $I->pressKey('Xpath',WebDriverKeys::array(ctrl,s));
```

please tell me how to save my web page as html using codeception 
this is my acceptance.suite.yml file 

```
lass_name: AcceptanceTester
modules:
    enabled:
            - AcceptanceHelper
            - Sequence
            - Cli
            - Filesystem
            - Db
            - WebDriver
    config:
      WebDriver:
         url: 'https://www.google.co.in/' 
         browser: chrome
         restart: false
         wait: 2
         clear_cookies: false
         window_size: false
         capabilities:
             unexpectedAlertBehaviour: 'accept'
```
