### ISSUE TITLE
Coverage whitelist includes xml files, but blacklist doesn't exclude them

### ISSUE THREAD

**Issue by oparoz** [Codeception/Codeception#2295]
Example config
```
coverage:
    enabled: true
    include:
        - appinfo/*
        - controller/*
    exclude:
        - appinfo/info.xml
        - build/*
```

The HTML coverage report show `appinfo/info.xml` at 0% coverage

**Comment by oparoz** [comment]
For people experiencing the same problem, one solution is to add a PHP filter, but it won't work if you have different php extensions in the same folder.

```
coverage:
    enabled: true
    include:
        - appinfo/*.php
        - controller/*
    exclude:
        - build/*
```
