### ISSUE TITLE
Class 'Facebook\WebDriver\Remote\WebDriverCapabilityType' not found

### ISSUE THREAD

**Issue by matperez** [Codeception/Codeception#2300]
Hello!

I got the following error while trying to run my acceptance tests. All other tests suites are working fine.

```
/www/prj/vendor/bin/codecept run acceptance --no-colors -d
Codeception PHP Testing Framework v2.1.2
Powered by PHPUnit 4.8.5-1-ga7df5a5 by Sebastian Bergmann and contributors.
PHP Fatal error:  Class 'Facebook\WebDriver\Remote\WebDriverCapabilityType' not found in /www/prj/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php on line 171
PHP Stack trace:
PHP   1. {main}() /www/prj/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run($input = *uninitialized*, $output = *uninitialized*) /www/prj/vendor/codeception/codeception/codecept:28
PHP   3. Symfony\Component\Console\Application->doRun($input = *uninitialized*, $output = *uninitialized*) /www/prj/vendor/symfony/console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand($command = *uninitialized*, $input = *uninitialized*, $output = *uninitialized*) /www/prj/vendor/symfony/console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run($input = *uninitialized*, $output = *uninitialized*) /www/prj/vendor/symfony/console/Application.php:878
PHP   6. Codeception\Command\Run->execute($input = *uninitialized*, $output = *uninitialized*) /www/prj/vendor/symfony/console/Command/Command.php:259
PHP   7. Codeception\Command\Run->runSuites($suites = *uninitialized*, $skippedSuites = *uninitialized*) /www/prj/vendor/codeception/codeception/src/Codeception/Command/Run.php:189
PHP   8. Codeception\Codecept->run($suite = *uninitialized*, $test = *uninitialized*) /www/prj/vendor/codeception/codeception/src/Codeception/Command/Run.php:262
PHP   9. Codeception\Codecept->runSuite($settings = *uninitialized*, $suite = *uninitialized*, $test = *uninitialized*) /www/prj/vendor/codeception/codeception/src/Codeception/Codecept.php:172
PHP  10. Codeception\SuiteManager->initialize() /www/prj/vendor/codeception/codeception/src/Codeception/Codecept.php:198
PHP  11. Codeception\Module\WebDriver->_initialize() /www/prj/vendor/codeception/codeception/src/Codeception/SuiteManager.php:81

Process finished with exit code 255
```

acceptance.suite.yaml
```
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
    config:
        WebDriver:
            url: 'http://prj.test' # our url base
            browser: phantomjs
            restart: true
            capabilities:
                unexpectedAlertBehaviour: 'accept'
        Yii2:
            configFile: 'tests/config/acceptance.php'
```

Facebook/WebDriver version:
```
            "name": "facebook/webdriver",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/facebook/php-webdriver.git",
                "reference": "575600dfcfebad49fd0fc59d781b0696462a1f4e"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/facebook/php-webdriver/zipball/575600dfcfebad49fd0fc59d781b0696462a1f4e",
                "reference": "575600dfcfebad49fd0fc59d781b0696462a1f4e",
                "shasum": ""
            },
```
