### ISSUE TITLE
Make test suite path more configurable

### ISSUE THREAD

**Issue by didinahmadi** [Codeception/Codeception#2302]
Hi, 

Is codeception support to customize test suite path?

for example:

I have this configuration:

```
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - Yii1
        - \Helper\Functional
        - PhpBrowser
        - Db
    config:
        Yii1:
            appPath: '/Volumes/disk0s4/www/new-proj/trunk/test.php'
            url: 'https://my.proj.local/test.php'
        PhpBrowser:
            url: 'https://my.proj.local/'
        Db:
            dsn: 'mysql:host=127.0.0.1;dbname=test-proj-new'
            user: 'root'
            password: 'root'
            ...
```

at `config` > `Yii1` > `appPath` is fixed path which my own local configuration. unfortunately if someone in my team want to setup his own test, this configuration won't work, instead he need to setup new suite for it. as I know each suite will have its own test-file.

What I expect is everyone can have own-suite-configuration, but keep to run the same test-file.

So, do you have any idea to handle the kind of this situation? I really appreciate all of your input and thanks a lot for attention.

**Comment by didinnurdin** [comment]
Today, I discover `--env` options, that seems to be the way to handle my problem above. so I tried it and it works well.

This is my `functional.suite.yml` looks like:
```
class_name: FunctionalTester
env:
    didin:
        modules:
            enabled:
                - Yii1
                - \Helper\Functional
                - PhpBrowser
                - Db
            config:
                Yii1:
                    appPath: '/Volumes/disk0s4/www/didin.local/trunk/test.php'
                    url: 'https://didin.localtest.php'
                PhpBrowser:
                    url: 'https://didin.local/'
                Db:
                    dsn: 'mysql:host=127.0.0.1;dbname=test-local-new'
                    user: 'root'
                    password: 'root'
                    dump: "tests/_data"
    johndoe:
        modules:
            enabled:
                - Yii1
                - \Helper\Functional
                - PhpBrowser
                - Db
            config:
                Yii1:
                    appPath: '/Volumes/disk0s4/www/johndoe.local/trunk/test.php'
                    url: 'https://johndoe.localtest.php'
                PhpBrowser:
                    url: 'https://didin.local/'
                Db:
                    dsn: 'mysql:host=127.0.0.1;dbname=test-local-new'
                    user: 'root'
                    password: 'root'
                    dump: "tests/_data"
```

awesome! then I try to simplify the configuration above to be like this:
```
class_name: FunctionalTester
modules:
            enabled:
                - Yii1
                - \Helper\Functional
                - PhpBrowser
                - Db
            config:
                Db:
                    dsn: 'mysql:host=127.0.0.1;dbname=test-local-new'
                    user: 'root'
                    password: 'root'
                    dump: "tests/_data"

env:
    didin:
        modules:
            config:
                Yii1:
                    appPath: '/Volumes/disk0s4/www/didin.local/trunk/test.php'
                    url: 'https://didin.localtest.php'
                PhpBrowser:
                    url: 'https://didin.local/'
    johndoe:
        modules:
            config:
                Yii1:
                    appPath: '/Volumes/disk0s4/www/johndoe.local/trunk/test.php'
                    url: 'https://johndoe.localtest.php'
                PhpBrowser:
                    url: 'https://johndoe.local/'
```

in my case, the config above which should override the previous config doesn't work, then I try to create separate environment's file suite by running ie: `codecept g:env johndoe`, and put this config at new generated env's file.
```
        modules:
            config:
                Yii1:
                    appPath: '/Volumes/disk0s4/www/johndoe.local/trunk/test.php'
                    url: 'https://johndoe.localtest.php'
                PhpBrowser:
                    url: 'https://didin.local/'
```

but it doesn't work either.
