### ISSUE TITLE
Cept tests ignoring environment

### ISSUE THREAD

**Issue by farstrider** [Codeception/Codeception#2309]
I have two environments set up: one for PhpBrowser and one for WebDriver.  My acceptance.suite.yml file is as follows:

```
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
        - Db
    config:
        PhpBrowser:
            url: http://alpha.test.local/

env:
    phantom:
        modules:
            enabled:
                - WebDriver
                - WebHelper
                - Db
            config:
                WebDriver:
                    url: http://alpha.test.local/
                    browser: phantomjs
                    window_size: 1024x768
    browser:
```

However, even when including `$scenario->env('browser');` in the code for Cept tests, the tests still run when the "phantom" environment is specified.  For example:

```
php ./vendor/bin/codecept run acceptance UserController --env phantom
Codeception PHP Testing Framework v2.1.2
Powered by PHPUnit 4.8.6 by Sebastian Bergmann and contributors.

Acceptance-phantom Tests (2) -------------------------------------------------------------------------------------------------------------------
Reset database and edit password (PasswordCept)                                                                                           Ok
Reset database and edit username (UsernameEditCept)                                                                                       Ok
------------------------------------------------------------------------------------------------------------------------------------------------
DEPRECATION: reset database and edit password | $scenario->env() is deprecated in favor of annotation: // @env
DEPRECATION: reset database and edit username | $scenario->env() is deprecated in favor of annotation: // @env
```

Changing to `// @env browser` -- as suggested by the deprecation message -- also does not work, however.

So how can I ensure that Cept tests only run under the specified environment?
