### ISSUE TITLE
unit tests build command error

### ISSUE THREAD

**Issue by hesna** [Codeception/Codeception#2320]
I'm trying to enable only a specific part of a module in my unit tests, according to [this part](http://codeception.com/docs/05-UnitTests#Interacting-with-the-Framework) of documentations. my `unit.suite.yml` file looks like this:
```yml
class_name: UnitTester
modules:
    enabled:
      - Yii2:
        part: ORM
    config:
        Yii2:
            cleanup: true
            configFile: '../config/backend/unit.php'
```
the above code includes Yii2 module but using Laravel also leads to same results. after executing `codecept build` command, this is the output (error reporting is enabled):
```
Building Actor classes for suites: unit
Warning: Illegal offset type in isset or empty in /Applications/MAMP/htdocs/kalpok/vendor/codeception/codeception/src/Codeception/Configuration.php on line 286
Warning: mb_strpos() expects parameter 1 to be string, array given in /Applications/MAMP/htdocs/kalpok/vendor/codeception/codeception/src/Codeception/Configuration.php on line 310
Notice: Array to string conversion in /Applications/MAMP/htdocs/kalpok/vendor/codeception/codeception/src/Codeception/Configuration.php on line 317
Notice: Array to string conversion in /Applications/MAMP/htdocs/kalpok/vendor/codeception/codeception/src/Codeception/Configuration.php on line 321
Notice: Array to string conversion in /Applications/MAMP/htdocs/kalpok/vendor/codeception/codeception/src/Codeception/Configuration.php on line 323
                   
  [Codeception\Exception\Configuration]  
  Array could not be found and loaded    
                                         
build [-c|--config [CONFIG]]
```
I can't find the reason. and enabling a module without specifying a part works just fine.
I'm using codeception `version 2.0.16`.

**Comment by DavertMik** [comment]
Looks like you use double configuration. Also there is an issue with spaces in config. Please use 4 spaces always... Probably your config should look like this:

```yaml
class_name: UnitTester
modules:
    enabled:
        - Yii2:
            part: ORM
            cleanup: true
            configFile: '../config/backend/unit.php'
```
