### ISSUE TITLE
WebDriverKeys not working with PhantomJS

### ISSUE THREAD

**Issue by montogeek** [Codeception/Codeception#2337]
Hi!

I found out that using the `\WebDriverKeys` class to send keys does not work with PhantomJS. 

My app is using https://jqueryui.com/selectable/ to fill a schedule, you can select multiple cells by clicking in a cell while the META key is pressed.
I have a eventListener when the form is submitted to fill a hidden input with JavaScript, like this:

```javascript
(function() {
    var $horario = $('#horario'),
        $inputHorario = $('input[name="horario_json"]'),
        $registro = $('#registro'),
        selected = [];

    $horario.selectable({
        filter: '.selectable'
    });

    $registro.on('submit', function() {
        $('.ui-selected', $horario).each(function(index, elemento) {
            selected.push(elemento.dataset.dia + '|' + elemento.dataset.hora);
        });
        if(selected.length >= 1) {
            $inputHorario.val(JSON.stringify(selected));
        }
    });
})();
```

This is my test:
```php
public function puede_enviar_horario_disponibilidad(AcceptanceTester $I) {

        $I->am('Monitor');
        $I->wantTo('Puedo enviar mi horario de disponibilidad a traves de la pagina de registro');

        $I->click('Registro');

        $faker = Faker\Factory::create('es_ES');

        // Campos requeridos
        $usuario = array(
            'nombre' => $faker->firstName,
            'apellido' => $faker->lastName,
            'cedula' => $faker->numberBetween(30000000, 1119000000),
            'promedio' => $faker->randomFloat(1, 0, 5),
            'usuario' => $faker->userName,
            'direccion' => $faker->address,
            'telefono' => $faker->numerify('##########')
        );

        $horario_disponibilidad = array(
            array(1,8),
            array(1,9),
            array(1,10),
            array(2,10),
            array(4,18),
            array(3,12),
            array(5,20),
            array(0,15),
            array(6,21)
        );

        foreach ($usuario as $dato => $valor) {
            $I->fillField($dato, $valor);
        }

        $I->selectOption('programa_id', 1);

        foreach($horario_disponibilidad as $horario) {
            $I->executeInSelenium(function(\RemoteWebDriver $webdriver) use ($horario) {
                $celda = $webdriver->findElement(\WebDriverBy::cssSelector("[data-dia='$horario[0]'][data-hora='$horario[1]']"));

                $webdriver->getKeyboard()->pressKey(\WebDriverKeys::META);
                $celda->click();
                $webdriver->getKeyboard()->releaseKey(\WebDriverKeys::META);
            });
            $I->makeScreenshot("$horario[0]-$horario[1]");
        }
        $I->click('Registrarme');

        $I->seeRecord('usuarios', $usuario);
        $I->seeRecord('usuarios', array('email' => $I->formatEmail($usuario['usuario'])));
        $I->seeRecord('usuarios', array('programa_id' => 1));

        $I->seeRecord('disponibilidad', array(
            'hora_inicio' => 8,
            'hora_fin' => 11,
            'dia' => 1,
            'usuario_id' => 101
        ));

        foreach ($horario_disponibilidad[3] as $horario) {
            $I->seeRecord('disponibilidad', array(
                'hora_inicio' => $horario[1],
                'hora_fin' => $horario[1] + 1,
                'dia' => $horario[0],
                'usuario_id' => 101
            ));
        }
    }
```

This is my `acceptance.suite.yml` config file:
```yaml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - FunctionalHelper
        - AcceptanceHelper
        - Laravel4
        - Db
        - WebDriver
    config:
        WebDriver:
            url: 'http://monitores.dev/'
            browser: chrome
            capabilities:
                browserName: "chrome"
                javascriptEnabled: true,
                webStorageEnabled: true,
                nativeEvents: true
        Db:
            dsn: 'mysql:host=localhost;dbname=monitores_test'
            user: 'monitores'
            password: 'monitores'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: false
env:
    acceptance:
        modules:
            config:
                Laravel4:
                    environment: acceptance
                    filter: true
                Db:
                    dsn: 'mysql:host=192.168.22.10;dbname=monitores_test'
                    user: 'monitores'
                    password: 'monitores'
                    dump: 'tests/_data/dump.sql'
                    populate: true
                    cleanup: true
```

My app is running inside a Vagrant VM with CentOS, when running the test from the host machine `vendor/bin/codecept run acceptance --steps --env acceptance --debug` its executed like this https://cloudup.com/c39KSV09zc0, getting a successful result, the schedule is filled and the JavaScript code runs without problem.

But when running the test from inside the VM `vendor/bin/codecept run acceptance --stesps --debug` the META key is not being pressed, I know it because I make some screenshots from the same step:
PhantomJS: 
![1-10](https://cloud.githubusercontent.com/assets/1002461/9667269/7c07d58c-5240-11e5-93f6-ee1e6127f1c6.png)
(I don't know why it looks like that)

Chrome:
![1-10](https://cloud.githubusercontent.com/assets/1002461/9667281/86f6d358-5240-11e5-98ea-9f08d06a6ba4.png)

And I only get the data from the last element that was clicked. This is the log from PhantomJS https://gist.github.com/montogeek/d030eedae878532c1362

Is there another way to do it? I have already tried with
```php
$this->getModule('WebDriver')->webDriver->getKeyboard()->pressKey(\WebDriverKeys::META);
```
in the AcceptanceHelper as function.

Thanks!
