### ISSUE TITLE
WebDriver config timeout being ignored.

### ISSUE THREAD

**Issue by nickcolley** [Codeception/Codeception#2341]
I'm trying to use the iPhone saucelabs VMs and they seem to take a while to boot up.

I need to increase the first timeout as it times out with the default 30 seconds:

```
  [WebDriverCurlException]                                                                                                                                                          
  Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"iphone","platform":"OS X 10.10","version":"8.0","deviceOrientation":"portrait"}}  
  Operation timed out after 29599 milliseconds with 0 bytes received 
```

The following config is being used:
```
    ios8:
         modules:
            config:
                WebDriver:
                    connection_timeout: 120
                    request_timeout: 120
                    browser: 'iphone'
                    capabilities:
                        browserName: 'iphone'
                        platform: 'OS X 10.10'
                        version: '8.0'
                        deviceOrientation: 'portrait'
```
