### ISSUE TITLE
Event before run tests

### ISSUE THREAD

**Issue by nepster-web** [Codeception/Codeception#2368]
Hi. Sorry for my bad English. 

I need to test the Rest Api . My api is protected by the access_token.

Therefore, before run all tests, I want to get the access, and use method amBearerAuthenticated.

I don't want to receive a new access token in each test of the method _before. I want to get the access token once and work with it.

How can I do this?

**Comment by Darhazer** [comment]
Add a module and put  in `_beforeSuite()` 
```php
$this->getModule('REST')->amBearerAuthenticated()
```

**Comment by nepster-web** [comment]
I found only this:
https://jordaneldredge.com/blog/writing-a-custom-codeception-module/

Why add the module so hard?
And why codeception has no standard methods for this ?

**Comment by Naktibalda** [comment]
Custom modules are called Helpers: http://codeception.com/docs/06-ReusingTestCode#Modules-and-Helpers

**Comment by nepster-web** [comment]
I use yii2, codeception yii2 module.

I create a file tests/codeception/_support/Helper/Oauth2.php:
```
<?php

namespace Helper;

/**
 * Class Oauth2
 * @package Helper
 */
class Oauth2 extends \Codeception\Module
{
    public function _before()
    {
        $I = $this->getModule('REST');

        $I->sendPOST("http://site.com/oauth2/user", [
            'username' => 'admin',
            'password' => 'admin',
        ]);

        $I->seeResponseCodeIs(200);
        $I->seeResponseIsJson();

        $token = $I->grabDataFromResponseByJsonPath('$..access_token');
        $token = $token[0];

        $I->amBearerAuthenticated($token);
    }

}
```

Config:
```
class_name: ApiTester

modules:
    enabled:
        - REST
        - Helper\Oauth2
    config:
        REST:
          url: http://site.com/v1/
          depends: PhpBrowser
          part: Json
```




And it really works. Pay attention: works only method _before, method _beforeSuite() gives an error message.

Many thanks.
