### ISSUE TITLE
REST module, headers set on YML file not sent

### ISSUE THREAD

**Issue by centerax** [Codeception/Codeception#2401]
We have this configuration on an api suite (api.suite.yml)

```yaml
class_name: ApiTester

modules:
    enabled:
        - \Helper\Api
        - REST
        - Db
    config:
        REST:
          url: {{url}}
          depends: PhpBrowser
          headers:
            Header-One: {{value_1}}
            Header-Two: {{value_2}}
            Header-Three: {{value_3}}
            Content-Type: application/json
        Db:
          dsn: 'mysql:host=localhost; dbname={{dbname}}'
          user: '{{dbusername}}'
          password: '{{dbpass}}'
          populate: false
          cleanup: false
```

when we run the suite the headers are not sent

```shell
[Request headers] []
```

headers are loaded on the config property of REST class but never taken into account, they are not traversed and added to the $this->headers property.

**Comment by Naktibalda** [comment]
```
[Request headers] []
```
This could be a debugging issue - REST modules does nothing with headers parameter, PhpBrowser passes it straight to Guzzle, so REST module is not aware of these headers, but they could still be sent to the service.

Check what you get in your application.

https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/PhpBrowser.php#L243

**Comment by DavertMik** [comment]
Please try this config:

```yaml
    config:
        REST:
          url: {{url}}
          depends: PhpBrowser
        PhpBrowser:
          headers:
            Header-One: {{value_1}}
            Header-Two: {{value_2}}
            Header-Three: {{value_3}}
            Content-Type: application/json
        Db:
          dsn: 'mysql:host=localhost; dbname={{dbname}}'
          user: '{{dbusername}}'
          password: '{{dbpass}}'
          populate: false
          cleanup: false
```
