### ISSUE TITLE
PhpBrowser does not support redirects correctly with base url option not set to be index

### ISSUE THREAD

**Issue by JarJak** [Codeception/Codeception#2402]
my config (functional.suite.yml):
```yaml
modules:
    enabled:
        - Symfony2:
            environment: 'test'
        - Doctrine2:
            depends: Symfony2
        - PhpBrowser:
            url: http://test.local/app_test.php
            allow_redirects: true
        - \Helper\Functional
```

As you can see I have PhpBrowser configured with base path ```http://test.local/app_test.php```.

The test:
```php
$I = new FunctionalTester($scenario);
$I->wantTo('See if old login page redirects me to homepage');
$I->amOnPage('/login');
$I->canSeeResponseCodeIs(301); //does not work
```

And the tested action (part of Symfony2 Controller):
```php
    /**
     * @return RedirectResponse
     */
    public function loginAction()
    {
        return $this->redirect($this->generateUrl('homepage'), 301);
    }
```

This works fine in normal browser, but what happens during the test:
1. ``` $I->amOnPage('/login') ``` opens URL ``` http://test.local/app_test.php/login ```
2. The Redirect happens
3. (probably) PhpBrowser changes the new URL to match configured base path
4. It redirects me to ``` http://test.local/app_test.php/app_test.php/ ``` instead of expected ``` http://test.local/app_test.php/ ``` so Symfony produces 404 page.

Im not sure if this bug sits in Codeception tself, in PhpBrowser or in Guzzle, nor if it happens only iwth Symfony.
