### ISSUE TITLE
Custom commands registering

### ISSUE THREAD

**Issue by MelindaN** [Codeception/Codeception#2410]
I would find interesting and very useful if in Codeception existed a feature which gives us the possibility to run a program with custom parameters from command line. 

In my case, I need to verify lots of URLs and I need to compose them from 2 parts. For one part I already use environments and for the other one which is external I have no option for the moment. That's why, the possibility to run with custom parameters would be very useful, e.g. running the program like 
```php codecept.phar somecommands --myCustomVariable variable```

I saw that the same issue was raised by someone else in the past and deferred https://github.com/Codeception/Codeception/issues/314. I think this would be a very useful feature that's why I created a new issue, also hoping that meanwhile other people would find the same such as to raise its priority to implement.

**Comment by Naktibalda** [comment]
Implemented in Codeception 2.2: http://codeception.com/docs/08-Customization#Custom-Commands

**Comment by dianaolaru** [comment]
I saw the example but I still don't know how to use it... 
First I don't know where I should place MyCustomCommand class and then I don't know how it should work... I imagine something like this:
php codecept.phar run acceptance TestCest.php --myCommand variable
but I get this error: [Symfony\Component\Console\Exception\RuntimeException]  
  The "--myCommand" option does not exist.            
What am I doing wrong?

**Comment by Naktibalda** [comment]
Where to place:

Place it anywhere you like in your code base as long as it can be autoloaded.


How it should work:
`php codecept.phar myCommand`

**Comment by dianaolaru** [comment]
thank you.. but unfortunately it's not working...

my codeception.yml looks like this:
```
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
    commands: Project\Command\MyCustomCommand
params:
    - .env 
```

I placed the MyCustomCommand.php file under codeception/tests/Command Dir

If i run `php codecept.phar myCommand `
I get:
```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "myCommand" is not defined. 
```

Do I have to customize this? (How?)
```
    public static function getCommandName()
    {
        return "myProject:myCommand";
    }
```
