### ISSUE TITLE
Auth Filter is always on for Laravel4 module

### ISSUE THREAD

**Issue by drakakisgeo** [Codeception/Codeception#2428]
I am trying to get to a page that is for authenticated users. I am disabling filters and I login as a User but again it seems that I am always redirected back to /login form. The _output show the /login form.

This is the test

```
$I = new FunctionalTester($scenario);
$I->wantTo('check if insertion of new customer is ok');
$I->haveDisabledFilters();
$I->amLoggedAs(User::find(1));
$I->amOnPage('/customers/create');
$I->seeCurrentUrlEquals('/customers/create');
$I->see('test');
```
I get

```
 Step  I see current url equals "/customers/create"
 Fail  Failed asserting that two strings are equal.--- Expected
+++ Actual
@@ @@
-'/customers/create'
+'/login'

```
My functional.yml is this

```
class_name: FunctionalTester
modules:
    enabled:
        - \Helper\Functional
        - Db
        - Asserts
        - Laravel4
        - PhpBrowser:
            url: 'http://app.mytestingdomain.gr'
        - MailCatcher:
            url: 'http://localhost'
            port: 1080
        - REST:
            depends: PhpBrowser
            url: 'https://api.mytestingdomain.gr'
```
I have spend many hours with this issue, no clue what to look. I am using "2.1.x-dev"
