### ISSUE TITLE
firefox and chrome show blank white page in acceptance tests

### ISSUE THREAD

**Issue by hesna** [Codeception/Codeception#2439]
I'm using codeception with Yii2 and my configuration is as follows:
```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: 'http://ucms.ac.ir/admin/index-test.php/'
            browser: chrome
        - tests\codeception\common\_support\FixtureHelper
        - Yii2
    config:
        Yii2:
            configFile: '../config/backend/acceptance.php'
```
tests run, and they finish successfully, but nothing appears on the new browser tab opened by selenium. I've seen some tutorials and in those tutorials browser actually shows process of testing. also, when an error occurs and a screenshot is taken, it's only a white empty page too. 
I'm on ubuntu 14.10, selenium 2.47.1 and chrome 45. it all happens when I use firefox instead of chrome.
