### ISSUE TITLE
REST module function doesn't work?

### ISSUE THREAD

**Issue by d3sire** [Codeception/Codeception#2448]
I am trying to write tests using REST module but I they seem to just don't work.
My tests:
```php
    $I = new AcceptanceTester($scenario); 
    $I->wantTo('perform actions and see result');
    $I->amOnPage('/sample/path.json');
    $I->seeResponseCodeIs(200);
    $I->seeResponseEquals("");
```

My config:
```yaml
    class_name: AcceptanceTester
    modules:
        enabled:
            - REST:
                depends: PhpBrowser
            - PhpBrowser:
                url: http://myValidLocalUrl.dev
            - \Helper\Acceptance
```

This test doesn't fail but I have checked my url path a lot of times and it returns valid json. But this tests tell that it is empty. Also, whenever I try to check json response using `seeResponseContains` or `seeResponseJsonMatchesJsonPath` it fails either.
You can try to run this method on sample url from [swagger](https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore.json) it still tells that response is empty.
My codeception version is dev-master
