### ISSUE TITLE
Call to undefined method Exception::getStatusCode() 

### ISSUE THREAD

**Issue by sitehopper** [Codeception/Codeception#2466]
When I run functional tests in Codeception in Laravel, every now and then I get the error:

 [Symfony\Component\Debug\Exception\FatalErrorException]  
  Call to undefined method Exception::getStatusCode() 

Im running Codeception version 2.1.3 in Laravel 5.1

Why is this error thrown?

**Comment by Naktibalda** [comment]
Please provide the configuration file of suite.

Then run codeception with -vvv parameter and get the stacktrace.

**Comment by sitehopper** [comment]
codeception.yml
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'mysql:host=127.0.0.1;port=3306;dbname=la51'
            user: 'root'
            password: 'root'
            populate: false
            cleanup: false
            reconnect: true
```

functional.suite.yml
```
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - \Helper\Functional
        - Asserts
        - Db
        - Laravel5
    config:
        Laravel5:
            cleanup: false
```

```
Rubens-MacBook-Pro:la51 rubenbijker$ codecept run -vvv
Codeception PHP Testing Framework v2.1.3
Powered by PHPUnit 4.8.10 by Sebastian Bergmann and contributors.

Acceptance Tests (0) ------------------------
Modules: PhpBrowser, \Helper\Acceptance
---------------------------------------------
---------------------------------------------

Functional Tests (9) -------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Functional, Asserts, Db, Laravel5
----------------------------------------------------------------------------------------------------------------------------------------------------
Create a boat (AdminCreatesBoatCept)
Scenario:
* As an a guest
* I am on page ""


                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Call to undefined method Exception::getStatusCode()      
                                                           




                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Call to undefined method Exception::getStatusCode()      
                                                           





FATAL ERROR. TESTS NOT FINISHED.
Call to undefined method Exception::getStatusCode() 
in /Applications/MAMP/htdocs/la51/app/Exceptions/Handler.php:71
Rubens-MacBook-Pro:la51 rubenbijker$ 
```

Im not sure what you mean by stacktrace. Let me know if this information is enough. Thank you for your help!
