### ISSUE TITLE
A problem with merge multiple environments

### ISSUE THREAD

**Issue by klokovas** [Codeception/Codeception#2493]
_envs/test.yml

```
module
     webdriver:
          url: 'test.host.org'
```

_envs/env2.yml

```
modules:
    config:
      somemodule:
          somaparam: 'test'
```

acceptance.suite.yml

```
modules:
    config:
       webdriver:
             url: 'prod.host.org'
        somemodule:
          somaparam: 'default'
```

If I run with  `--env test` I get config with correct URL:

```
webdriver:
             url: 'test.host.org'
somemodule:
          somaparam: 'default'
```

If I run with  `--env env2` I get config with correct somemodule parameter:

```
webdriver:
             url: 'prod.host.org'
somemodule:
          somaparam: 'test'
```

_But_ If I run with  `--env test,env2` I get only env2 config.

**Comment by Toushin** [comment]
seconded, but maybe I am just misunderstanding how environment merging is supposed to work...
this is my acceptance.suite.yml

```
modules:
    enabled:
        - WebDriver
        - \Helper\Acceptance
    config:
        WebDriver:
            url: 'http://www.test.com'
            browser: 'firefox'

env:
    google:
        modules:
            config:
                WebDriver:
                    url: 'http://www.google.com'
    chrome:
        modules:
            config:
                WebDriver:
                    browser: 'chrome'
```

I expect a run with `--env chrome,google` to open the Google webpage in Chrome, but get a new Firefox instance instead.
