### ISSUE TITLE
Any chance to let ZF1 module make use of methods from REST module?

### ISSUE THREAD

**Issue by Lance0312** [Codeception/Codeception#2496]
I use ZF1 module to build functional test cases, and some response in JSON. I'd like to use `seeResponseIsJson()` from REST module. However, `seeResponseIsJson()` uses the property `$response`, which is only set with response value from framework modules when `execute()` is ran. Is there any chance that `$response` property in REST module can be fully synchronized with response set in framework modules.

https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/REST.php#L483

**Comment by Naktibalda** [comment]
Use REST methods instead of framework methods.

functional.suite.yml
```yaml
class_name: FunctionalTester
modules:
  enabled: 
    - FunctionalHelper
    - ZF1
    - REST:
        depends: ZF1
```

Test code:
```php
$I->sendGET('/resource');
$I->seeResponseIsJson();
$I->seeResponseContainsJson($expectedResponse);
```
