### ISSUE TITLE
Acceptance test: Select a field with brackets inbetween (f.e. test[5]test)

### ISSUE THREAD

**Issue by XzenTorXz** [Codeception/Codeception#2532]
Is it possible to fill a field with which has some text after the brackets ?
```html
<input type="text" name="test[5]" />
```

works fine but

```html
<input type="text" name="test[5]test" />
```

does not work. If I try to fill the field I get the error:

```
 [InvalidArgumentException] Malformed field path "test[id]test"
```

modules:
```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - AcceptanceHelper
```

test:
```php
$I = new User($scenario);
$I->logIn();
$I->wantTo('test');
$I->amOnPage('/test.php');
$I->fillField('test[id]test', "test");
