### ISSUE TITLE
Where to put SSL / Curl settings in new config ?

### ISSUE THREAD

**Issue by phpetra** [Codeception/Codeception#2533]
I have an API test suite which I recently updated to Codeception 2.1.3 and now my SSL settings for connecting to the https-site is not working anymore, because I need to put in the TLSv1 cipher And I can't for the life of me figure out where to put it.

I used to have  the following config:
``` modules:
            enabled: [PhpBrowser, REST, ApiHelper]
            config:
                PhpBrowser:
                    url: https://secure.website.com
                    curl:
                        CURLOPT_SSL_CIPHER_LIST: 'TLSv1'
```
Can someone maybe tell me where I need to put these settings (or how I need to call them?) in the new style config files? 
Cause none of the below options  work?
``` 
enabled:
                - PhpBrowser:
                    url: https://secure.website.com
                    verify_peer: false
                    ssl:
                        CURLOPT_SSL_CIPHER_LIST: 'TLSv1'
                    curl:
                        CURLOPT_SSL_CIPHER_LIST: 'TLSv1'
```
