### ISSUE TITLE
Yii2 as dependency of REST module

### ISSUE THREAD

**Issue by moicirk** [Codeception/Codeception#2562]
I use REST module to test my Yii2 application rest controllers so my functional tests config looks like this:
```
modules:
    enabled:
      - Yii2
      - REST

    config:
        Yii2:
            configFile: 'codeception/config/functional.php'
        REST:
            depends: Yii2
```

So REST module uses Yii2Connector as a client to send requests. Considering that REST module encodes parameters to JSON string Yii2 client gets only raw body message here:
```
$yiiRequest = $app->getRequest();
$yiiRequest->setRawBody($request->getContent());
$yiiRequest->setBodyParams($_POST); //$_POST here is an empty array
$yiiRequest->setQueryParams($_GET);
```

Now, if we look at the yii\web\Request body parameters parsing we see this:
```
public function getBodyParams()
{
    if ($this->_bodyParams === null) {
        ....
    }
    return $this->_bodyParams;
}
```
and _bodyParams  here is an empty array, so I cannot get my payload and parse it as a json. Am I doing everything right?

My test example:
```
$I->haveHttpHeader('Content-Type', 'application/json');
$I->wantTo('Update one record');
$I->sendPUT('/api/controller', $data);
$I->seeResponseCodeIs(200);
$I->seeResponseContainsJson($data);
```

Record is not updated because raw body was not parsed
