### ISSUE TITLE
The use statement with non-compound name 'XxxTester' has no effect

### ISSUE THREAD

**Issue by twlz0ne** [Codeception/Codeception#2574]
```sh
➜  codecept generate:cest api Example
➜  codecept run api Example -vvv
Codeception PHP Testing Framework v2.1.4
Powered by PHPUnit 4.8.18 by Sebastian Bergmann and contributors.

  Rebuilding ApiTester...

  [ErrorException]
  The use statement with non-compound name 'ApiTester' has no effect

Exception trace:
 () at /path/to/project/tests/api/ExampleCest.php:2
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /path/to/project/vendor/codeception/codeception/src/Codeception/Lib/Parser.php:174
 Codeception\Lib\Parser::includeFile() at /path/to/project/vendor/codeception/codeception/src/Codeception/Lib/Parser.php:174
 Codeception\Lib\Parser::includeFile() at /path/to/project/vendor/codeception/codeception/src/Codeception/Lib/Parser.php:130
 Codeception\Lib\Parser::getClassesFromFile() at /path/to/project/vendor/codeception/codeception/src/Codeception/Lib/TestLoader.php:158
 Codeception\Lib\TestLoader->addCest() at n/a:n/a
 call_user_func() at /path/to/project/vendor/codeception/codeception/src/Codeception/Lib/TestLoader.php:95
 Codeception\Lib\TestLoader->loadTest() at /path/to/project/vendor/codeception/codeception/src/Codeception/SuiteManager.php:97
 Codeception\SuiteManager->loadTests() at phar:///usr/local/bin/codecept/src/Codeception/Codecept.php:202
 Codeception\Codecept->runSuite() at phar:///usr/local/bin/codecept/src/Codeception/Codecept.php:172
 Codeception\Codecept->run() at phar:///usr/local/bin/codecept/src/Codeception/Command/Run.php:184
 Codeception\Command\Run->execute() at phar:///usr/local/bin/codecept/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/codecept/codecept:34
 require_once() at /usr/local/bin/codecept:7
```
Seems could not load `tests/_support/ApiTester.php`.

tests/api/ExampleCest.php

```php
1 <?php
2 use \ApiTester;
3
4 class ExampleCest
5 {
6     public function _before(ApiTester $I)
7     {
8     }
9
10     public function _after(ApiTester $I)
11     {
12     }
13
14     // tests
15     public function tryToTest(ApiTester $I)
16     {
17     }
18 }
```
api.suite.yml

```yaml
class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - Laravel5:
            environment_file: .env.testing
        - REST:
            depends: laravel5
```

codeception.yml

``` yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql

```
