### ISSUE TITLE
Codeception WebDriver doesn't clear all cookies between tests while working with multiple domains

### ISSUE THREAD

**Issue by Asera** [Codeception/Codeception#2586]
When test ends WebDriver cleares only cookies from the domain we were on at the end of the test. Cookies of all other domains can still be used in the next tests.

Reproduction description:

In first test in Cest we go to first domain, which creates cookie in browser, then go to some other domain which also creates cookie and finish first test. We expect that cookies between tests will be fully cleared but if we go back to first domain in second test we will find out that previous test cookies were not deleted. In example below we try to make facebook login in first test and then go to some other domain before test ending. In the second test we go to facebook domain and find out that we are already logged in as user from previous test.

WebDriver Settings:

```
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            restart: false
            clear_cookies: true
            url: 'http://url/'
            browser: firefox
            port: 4444
```

tests example:

```
class SimpleCest
{
    public function testCookieNoException(AcceptanceTester $I)
    {
        $I->amOnUrl('https://www.facebook.com/');

        $facebookLoginPage = new \Page\FacebookLoginPage($I);
        $facebookLoginPage->makeFacebookLogin($facebookUser['email'], $facebookUser['password']);

        // To check if we have logged in
        $I->makeScreenshot('after_fb_reg');

        $I->amOnUrl('http://someOtherUrl');
    }

    public function testCookieRegenerate(AcceptanceTester $I)
    {
        $I->amOnUrl('https://www.facebook.com/');

        // To check that we are not logged in
        $I->makeScreenshot('must_be_login_page');
    }
}
```
