### ISSUE TITLE
Testing a Chrome extension

### ISSUE THREAD

**Issue by jerome-intelligence** [Codeception/Codeception#2616]
I am trying to test a chrome extension with Codeception following instructions from this link:
http://blog.releasematic.com/2013/12/29/automation-testing-chrome-extensions/
#1) With the browser Chrome opened

It is easy to open my extension directly using this kind of address:
**chrome-extension://[ID of the extension]/popup.html**
#2) Trying to test it from Coception

I still cannot run the chromedriver with the extension.

I've got some ideas following those links
https://sites.google.com/a/chromium.org/chromedriver/extensions
https://sites.google.com/a/chromium.org/chromedriver/capabilities

I believe that I should setup the acceptance.suite.yml properly with something like:

``` YAML
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://localhost:8080
            browser: firefox
            window_size: maximize
            ignoreZoomSetting: true
        - \Helper\Acceptance

env:
    chrome:
         modules:
            config:
                WebDriver:
                    browser: 'chrome'

    firefox:
     # nothing changed

    chromeext:
         modules:
            config:
                WebDriver:
                    browser: 'chrome'
                    capabilities:
                      chromeOptions:
                          args: 'load-extension=/[Path to my extension]/extension/'
```

As you can see I want to set a new environement called 'chromeext'. I tried so many variations...
Both 'chrome' and 'firefox' are working.
# 3a) Is it possible to open the chromedriver with an extension loaded?
# 3b) If possible; Can you lead me to write a proper environement?
