### ISSUE TITLE
Unit tests does not use Group Object

### ISSUE THREAD

**Issue by sergeyklay** [Codeception/Codeception#2617]
**codeception.yml**
```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Group\Abc
```

**tests/_support/Group/Abc.php**
```php
<?php
namespace Group;

use Codeception\Event\TestEvent;
use Codeception\Platform\Group;

class Abc extends Group
{
    public static $group = 'abc';

    public function _before(TestEvent $e)
    {
        $this->writeln('we are here');
        $e->getTest()->markTestSkipped('WE SKIP TEST');
    }

    public function _after(TestEvent $e)
    {
    }
}
```

**tests/unit/SomeTest.php**
```php
<?php

use Codeception\TestCase\Test;

/**
 * @group abc
 */
class SomeTest extends Test
{
    /**
     * @var UnitTester
     */
    protected $tester;

    protected function _before()
    {
       // $this->getScenario()->group(\Group\Abc::$group); // abc
    }

    protected function _after()
    {
    }

    public function testFoo()
    {
        $this->assertTrue(false);
    }
}
```

```
$ vendor/bin/codecept run -g abc
Codeception PHP Testing Framework v2.1.4
Powered by PHPUnit 4.8.19 by Sebastian Bergmann and contributors.
[Groups] abc 

Unit Tests (126) --------------------------------------------------------------
Test foo (SomeTest::testFoo)                                               Fail
-------------------------------------------------------------------------------


Time: 1.43 seconds, Memory: 17.25Mb

There was 1 failure:

---------
1) Test foo (SomeTest::testFoo)
Failed asserting that false is true.
#1  <...>/tests/unit/SomeTest.php:26
#2  SomeTest->testFoo

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

This can be fixed by changing [`Codeception\SuiteManager`](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/SuiteManager.php#L132) from 
```php
if (!empty($groups) && $test instanceof TestCase\Interfaces\ScenarioDriven && null !== $test->getScenario()) {
    $test->getScenario()->group($groups);
}
```

to 
```php
if (!empty($groups) && null !== $test->getScenario()) {
    $test->getScenario()->group($groups);
}
```
But in this case I get an `PHPUnit_Framework_SkippedTestError` **exception**:
```
Trying to test foo (SomeTest::testFoo)... we are here


                                        
  [PHPUnit_Framework_SkippedTestError]  
  WE SKIP TEST                          
                                        

...
<backtrace here>
...
```

1. This is bug?
2. How to correctly skip grouped tests (e.g. in case of non-compliance to dependencies)

Thanks
