### ISSUE TITLE
Using environment does not work with code coverage

### ISSUE THREAD

**Issue by drodil** [Codeception/Codeception#2634]
Hi,

I am trying to run codecoverage for my project with codeception. Here is my build/codeception.yml file:

```yml
actor: Tester
paths:
    tests: ../tests
    log: ../tests/_output
    data: ../tests/_data
    helpers: ../tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 2048M
coverage:
    enabled: true
    remote: false
    remote_context_options:
        http:
            timeout: 60
        ssl:
            verify_peer: false
    blacklist:
        include:
            - ../db/*
            - ../data/*
            - ../config/*
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```

I have defined the following environments in tests/acceptance.yml:
```yml
class_name: AcceptanceTester
modules:
    enabled: [WebDriver, AcceptanceHelper]
    config:
        WebDriver:
            url: 'http://localhost/project/'
            browser: firefox
env:
    ci:
        modules:
            config:
                WebDriver:
                    url: 'https://server1.example.com/project/'
                    host: server1.example.com
                    browser: firefox
                    window_size: 1920x1080
    ci-mbv:
        modules:
            config:
                WebDriver:
                    url: 'https://server1.example.com/project-mbv/'
                    host: server1.example.com
                    browser: firefox
                    window_size: 1920x1080
```

When I run the following command:

```
php codecept.phar run -f -vvv -c build/codeception.yml --xml build/logs/junit.xml --html build/logs/junit.html --coverage-html build/coverage/html --coverage-xml build/coverage/converage.xml --env ci-mbv
```

I will get the error:

```
The "/var/lib/jenkins/workspace/project/build/../tests/acceptance.ci-mbv/" directory does not exist.  
```

The tests are created in subfolders under tests folder (acceptance/, unit/ and api/). Why does the codeception add the environment to end of the test folder? How can I prevent that or am I doing something wrong? This does not work even with remote option set as true - the error in that case is "Suite acceptance-ci-mbv was not loaded". 

Here is the codeception exception backtrace:

```
Exception trace:
 () at /var/lib/jenkins/workspace/project/vendor/symfony/finder/Finder.php:656
 Symfony\Component\Finder\Finder->in() at /var/lib/jenkins/workspace/project/vendor/codeception/codeception/src/Codeception/Lib/TestLoader.php:112
 Codeception\Lib\TestLoader->loadTests() at /var/lib/jenkins/workspace/project/vendor/codeception/codeception/src/Codeception/SuiteManager.php:95
 Codeception\SuiteManager->loadTests() at /var/lib/jenkins/workspace/project/vendor/codeception/codeception/src/Codeception/Codecept.php:199
 Codeception\Codecept->runSuite() at /var/lib/jenkins/workspace/project/vendor/codeception/codeception/src/Codeception/Codecept.php:191
 Codeception\Codecept->run() at /var/lib/jenkins/workspace/project/vendor/codeception/codeception/src/Codeception/Command/Run.php:262
 Codeception\Command\Run->runSuites() at /var/lib/jenkins/workspace/project/vendor/codeception/codeception/src/Codeception/Command/Run.php:189
 Codeception\Command\Run->execute() at /var/lib/jenkins/workspace/project/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/lib/jenkins/workspace/project/vendor/symfony/console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at /var/lib/jenkins/workspace/project/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /var/lib/jenkins/workspace/project/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at /var/lib/jenkins/workspace/project/vendor/codeception/codeception/codecept:28
```
Thanks for help!
