### ISSUE TITLE
BUG! - "Can't swap PDO instance while within transaction" on 2.1.5 + Laravel 5.1

### ISSUE THREAD

**Issue by punchi** [Codeception/Codeception#2659]
I have a nested transaction with \DB::beginTransaction(); on Laravel 5.1.27

With codecept 2.1.4, all is fine. After updating to 2.1.5...

When executing a test with Codeception, this error is returned:

[RuntimeException]
Can't swap PDO instance while within transaction.

Tested again by going back to 2.1.4 and worked fine again.

**Comment by janhenkgerritsen** [comment]
I refactored the Laravel 5 module for the 2.1.5 release, so that will probably be the cause of your issue. However, I need more details to look into this. 

Can you show me your Codeception and suite configuration? And an example of the failing test case? And if you can show me a sample of the tested application code as well that would be great.

**Comment by punchi** [comment]
functional.suite.yml
```
# Codeception Test Suite Configuration
#
# Suite for functional (integration) tests
# Emulate web requests and make application process them
# Include one of framework modules (Symfony2, Yii2, Laravel5) to use it

class_name: FunctionalTester
modules:
    enabled:
        - Laravel5:
            environment_file: .env.testing
            cleanup: true
        - \Helper\Functional
        - Asserts
```

codeception.yml
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'mysql:host=XXX;dbname=XXX'
            user: 'XXX'
            password: 'XXX'
coverage:
    enabled: true
    include:
        - app/*
    exclude:
        - app/Console/Kernel.php
        - app/Events/*
        - app/Exceptions/*
        - app/Jobs/*
```

The test is irrelevant, I changed it many times this only happens when in the code you have a nested \DB::beginTransaction();

This fails on 2.1.5, but works on 2.1.4:
```
\DB::beginTransaction();
$this->create($something);
\DB::commit();

public function create($something)
{
    \DB::beginTransaction();
    <SQL>
    \DB::commit();
}
```

If you delete one of the transaction blocks, works fine on 2.1.5
