### ISSUE TITLE
Laravel5 module headers are not sent in codeception v2.1.5

### ISSUE THREAD

**Issue by mnmcan** [Codeception/Codeception#2678]
```
class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - Laravel5:
            environment_file: .env.testing
            cleanup: false # true will run all test cases in transactions
        - Asserts
        - REST:
            depends: Laravel5
            url: '/api/v1/'
            part: Json
```
We have a configuration like above
in 2.1.4 everything works correctly. in 2.1.5 any headers we set with haveHttpHeader or amBearerAuthenticated not being sent
