### ISSUE TITLE
Selenium 2 Webdriver not working

### ISSUE THREAD

**Issue by sameernyaupane** [Codeception/Codeception#2680]
Hi,

I just added the Webdriver module for acceptance testing, but I seem to get an error while running a acceptance test:

my version:

```
"require-dev" : {
		"codeception/codeception": "2.1.5"
	},
```

my acceptance suit yml config:

```
modules:
    enabled:
        - WebDriver:
            url: 'http://www.localhost.loc/'
            browser: firefox
            window_size: 1024x768
            wait: 10
            capabilities:
                unexpectedAlertBehaviour: 'accept'
                firefox_profile: '/Users/paul/Library/Application Support/Firefox/Profiles/codeception-profile.zip.b64'
        - \Helper\Acceptance
```

I get the following error:

```
Fatal error: Class 'Facebook\WebDriver\Remote\WebDriverCapabilityType' not found in D:\UniServerZ2\vhosts\blackeyetravels\vendor\codeception\codeception\src\Codeception\Module\WebDriver.php on line 194
```

Any suggestions would be helpful, thanks
