### ISSUE TITLE
Firefox Profile Not Working Properly for Selenium Webdriver

### ISSUE THREAD

**Issue by sameernyaupane** [Codeception/Codeception#2690]
I am doing acceptance tests with Selenium 2 Webdriver and the tests seem to run fine.

But I have an issue with firefox profile. If I zip a firefox profile and encode it to base64 then add it to my acceptance config, I still get a fresh profile without the saved settings which I had in the profile.

My acceptance config

```
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: 'http://www.blackeyetravels.loc'
            browser: firefox
            window_size: 1024x768
            wait: 0
            capabilities:
                unexpectedAlertBehaviour: 'accept'
                #firefox_profile: 'C:\Users\Lenovo\AppData\Roaming\Mozilla\Firefox\Profiles\mh7bdpwx.Codeception.zip.b64'
        - \Helper\Acceptance
```

Commenting the firefox_profile or keeping it intact, both do the same, they start a new profile(not the one I defined).

Have I missed something with setting up firefox profiles?

Thanks
