### ISSUE TITLE
Laravel application not started correctly in Codeception 2.1.*

### ISSUE THREAD

**Issue by elimentz** [Codeception/Codeception#2691]
After upgrading to Codeception 2.1, I can't run my unit tests for my project any more. Well I can run them, but they all fail except for the first one (see error message below)

```php
---------
1) ProductTypeTest::testEnabledForComparison

  [ErrorException] Undefined index: WEB_URL

#1  /var/www/htdocs/vendor/vendorName/packageName/src/Vendor/Package/PackageServiceProvider.php:36
#2  /var/www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:531
#3  /var/www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:74
#4  /var/www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:507
#5  /var/www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
#6  /var/www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
#7  /var/www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:208
#8  /var/www/htdocs/tests/unit/base/BaseUnitTestCase.php:20
#9  /var/www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Testing/ApplicationTrait.php:34
#10 /var/www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:36
```

From what I can tell, Codeception tries to load the application again, but does so without reading in the.env file, which causes the error. Point is that I haven't changed anything to my setup, the only thing that has changed is the version of Codeception. The tests work fine in v2.0.16

Anyone know what this could be? My stack:
- PHP 5.6
- Laravel 5.1.28
- Codeception 2.1.5
- c3 v2.0.5

**Comment by janhenkgerritsen** [comment]
In your stack trace I see references to `Illuminate/Foundation/Testing/TestCase.php`, but you cannot use the Laravel test classes with Codeception.

What does your suite configuration file look like?

**Comment by elimentz** [comment]
@janhenkgerritsen Why would you think that, I've been using them for over a year in multiple projects? Again, it all works fine in `v2.0.*`

Anyways, here are my configuration files:

- codeception.yml
```yml
actor: Guy
paths:
    tests: tests
    log: tests/_log
    data: tests/_data
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=db'
            user: 'user'
            password: 'pwd'
            dump: tests/_data/dump.sql
            populate: true
            cleanup: true
        PhpBrowser:
            url: http://appname.dev/
        REST:
            depends: PhpBrowser
            url: http://appname.dev/api/v1/
        Laravel5:
            environment_file: .env.testing
```
- unit.suite.yml
```yml
class_name: UnitTester
modules:
    enabled:
        - Laravel5
        - Asserts
        - UnitHelper
```
- functional.suite.yml
```yml
class_name: FunctionalTester
modules:
    enabled:
        - Db
        - Laravel5
        - FunctionalHelper
```

For full disclore I will also include my base test case class that all my unit tests extend:
```php
class BaseUnitTestCase extends Illuminate\Foundation\Testing\TestCase {

    protected $baseUrl = 'http://appname.dev';


    public function setUp()
    {
        parent::setUp();

        App::setLocale('en');
    }

    public function createApplication()
    {
        $app = require __DIR__ .'/../../../bootstrap/app.php';

        $app->make( Illuminate\Contracts\Console\Kernel::class )->bootstrap();

        return $app;
    }

}
```
