### ISSUE TITLE
Headers not being sent for REST module

### ISSUE THREAD

**Issue by garyrutland** [Codeception/Codeception#2738]
Trying to get the REST module working and having some issues getting the headers sent.
I need the content type to be set to application/json and have been trying variations on the following:
```yaml
    class_name: ApiTester
    modules:
        enabled:
            - REST:
                depends: PhpBrowser
                url: /
                part: Json
            - PhpBrowser:
                url: http://web/
                headers:
                    Content-Type: "application/json"
```

I found the following issue as well and tried variations on this without any luck: https://github.com/Codeception/Codeception/issues/2401

With debug turned on all I see is this: [Request headers] []

The version I'm running is: Codeception PHP Testing Framework v2.1.5

Thanks,
Gary
