### ISSUE TITLE
[RuntimeException] Call to undefined method AcceptanceTester::seeInDatabase

### ISSUE THREAD

**Issue by ipanardian** [Codeception/Codeception#2749]
My Configuration in codeception.yml
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=loket_new'
            user: 'root'
            password: '123123'
            populate: false
            cleanup: false
            reconnect: true
```
  But when i ran test, error raised. 
```
$I = new AcceptanceTester($scenario);   
$I->wantTo('Booking One Ticket');  
$I->click('Beli Tiket');  
$I->seeInDatabase('invoice', ['invoice_code' => 'ABCDEF']);
```
