### ISSUE TITLE
Cannot use SQL dump to run my acceptance tests.

### ISSUE THREAD

**Issue by beedge72** [Codeception/Codeception#276]
I have placed a dump of my sites live database into tests/_data/dump.sql as suggested in the docs. 

However, when I run my acceptance tests the live database is always used. 

Am I correct in thinking that it should be referencing my dump.sql instead of my live database?

**Comment by davidjeddy** [comment]
Follow up for anyone trying to figure this out:

The DB config goes in `acceptance.yml`, make sure to run the `build` command.
```
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - Db
    config:
        PhpBrowser:
            url: http://localhost:8080/index-test.php
        Db:
            cleanup: true
            dsn: 'mysql:host=192.168.33.11;dbname=trades_test'
            dump: 'codeception/_data/dump.sql'
            password: ''
            populate: true
            user: 'root'
```
