### ISSUE TITLE
Exception from Phalcon module

### ISSUE THREAD

**Issue by Zaszczyk** [Codeception/Codeception#2774]
When I have more than 1 test I got exception:
```
  [Codeception\Exception\ModuleException]
  Phalcon1: Dependency injector container must implement DiInterface
```

My unit.suite.yml:
```
class_name: UnitTester
modules:
    enabled:
        - Phalcon2:
            bootstrap: 'apps/config/bootstrap.php'
            populate: false
            cleanup: false
        - Asserts
        - Db
        - \Helper\Unit
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=test'
            user: 'test'
            password: 'test'
            dump: 'tests/_data/dump.sql'
```

Phalcon version: 2.1.x
Codepception version: 2.1.5
