### ISSUE TITLE
Passing Environment variables into config

### ISSUE THREAD

**Issue by DavertMik** [Codeception/Codeception#2779]
There should be a way to pass environment variables into our global and suite configs. That's useful to pass credentials using them. I'm sure this is important feature and should be landed in 2.2

But I have some doubts about syntax on using variables:

```yaml
password: {{PASSWORD}}
# vs
password: %PASSWORD% #Symfony-style
# vs
password: $PASSWORD # php style
# vs you name it...
```

what would you prefer?
