### ISSUE TITLE
[PHPUnit_Framework_Exception] Laravel 4 module

### ISSUE THREAD

**Issue by IgorKostine** [Codeception/Codeception#2833]
Hi !
I try to add the Laravel 4 module, I get an error when I execute the command

`php codecept.phar run acceptance`

> [PHPUnit_Framework_Exception]
> Argument 1 passed to Symfony\Component\HttpKernel\Client::__construct() must be an instance of Symfony\Component\HttpKernel\HttpKernelInterface, instance of Codeception\Module\Laravel4 given, called in phar:///var/www/[...]/codeception/codecept.phar/src/Codeception/Module/
>   Laravel4.php on line 129 and defined

here is my acceptance.suite.yml

```
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
        - Db
        - \Helper\Acceptance
        - Laravel4
    config:
        PhpBrowser:
            url: '[...]'
        Db:
            dsn: 'pgsql:host=/var/run/postgresql;dbname=[...]'
            user: '[...]'
            password: '[...]'
            populate: false
            cleanup: false
            reconnect: true
        Laravel4:
            cleanup: true
            unit: false
            filters: true
            environment: 'local'
```
