### ISSUE TITLE
WebDriver::_after() for [restart:true, clear_cookies:true]

### ISSUE THREAD

**Issue by sasha-x** [Codeception/Codeception#2884]
Current implementation of [WebDriver::_after()](https://github.com/Codeception/Codeception/blob/2.1/src/Codeception/Module/WebDriver.php#L324-L337) seems to don't clean cookie after test on config options 

``` yml
restart:true 
clear_cookies:true
```

For phantomjs it leads to pass test at first time and fail others untill phantomjs manually restarted.
Are there some reasons for such behavior and don't do this?

``` php
    //clean cookie first and quit next, if need
    public function _after(TestInterface $test)
    {
        if ($this->config['clear_cookies'] && isset($this->webDriver)) {
            $this->webDriver->manage()->deleteAllCookies();
        }
        if ($this->config['restart'] && isset($this->webDriver)) {
            $this->webDriver->quit();
            // RemoteWebDriver consists of four parts, executor, mouse, keyboard and touch, quit only set executor to null,
            // but RemoteWebDriver doesn't provide public access to check on executor
            // so we need to unset $this->webDriver here to shut it down completely
            $this->webDriver = null;
        }
    }
```

My environment is:

``` yml
# acceptance.suite.yml
...
    config:
        WebDriver:
            url: http://<my site>
            browser: phantomjs
            restart: true
            window_size: 1366x1024
            clear_cookies: true
```

`nohup phantomjs --webdriver=4444 > /dev/null 2>&1 &`

``` bash
$ phantomjs -v
1.9.7
```

``` php
/* LoginCept.php */
$I = new AcceptanceTester($scenario);
$I->wantTo('ensure that login works');
$I->amOnPage('/');
$I->see(<My Login form>);
...
```
