### ISSUE TITLE
Codeception process freezes (hangs) at end of tests

### ISSUE THREAD

**Issue by babichalex** [Codeception/Codeception#2886]
I'm trying to run some codeception api tests. When they finishes, codeception process hangs immediately after the message about success or failure is shown, that causes freezing of my virtual machine too (codeception process consumes all RAM). I'm running tests like this:

`./bin/codecept build`
`./bin/codecept run --env=test`

codeception.yml:

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 2048M
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
env:
    test:
        modules:
            config:
                Db:
                    dsn: 'mysql:host=localhost;dbname=api_test'
                    user: 'testuser'
                    password: 'test'
                    dump: tests/_data/dump.sql
                    cleanup: true
                Doctrine2:
                    cleanup: true
                Symfony2:
                    app_path: 'app/'
                    environment: 'test'
        coverage:
            enabled: true
            include:
                - src/*
```
api.suite.yml:

```
class_name: ApiTester
modules:
    enabled: [Symfony2, Doctrine2, ApiHelper, REST, Asserts, Cli]
    config:
        Symfony2:
            environment: test
        Doctrine2:
            cleanup: true
            depends: Symfony2
        REST:
            depends: Symfony2
            url: http://test.mysite.com/api/
```

tests results:

```
Time: 8.47 minutes, Memory: 1678.75Mb

OK (399 tests, 1060 assertions)
```
