### ISSUE TITLE
How to keep Firefox open when using WebDriver

### ISSUE THREAD

**Issue by salarmehr** [Codeception/Codeception#2893]
Opening and closing filrefox take a while. How to force opening a new tab and keeping/closing it after ending of test?

**Comment by DavertMik** [comment]
Opening tab is not a part of webdriver functionality, actually you can send `Ctrl+T` and `Ctrl-F4` keys to browser to do that, but that's not an elegant solution and relies on platform.

If you need faster testing just set 

```
restart: false
```

in WebDriver config. Browser won't be reopened but cookies will be cleand after tests

**Comment by salarmehr** [comment]
@DavertMik I added `restart:false` to it. But I see no difference. It yet open ff, run test and close it.

**Comment by DavertMik** [comment]
Probably something wrong with formatting in config. Could you paste it here?

**Comment by salarmehr** [comment]
Here it is:

```
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
                 url: 'http://mehr.dev/'
                 browser: firefox
                 restart: false
```
