### ISSUE TITLE
Tests not working globally in Symfony2

### ISSUE THREAD

**Issue by clytemnestra** [Codeception/Codeception#2914]
I'm following [this ](http://codeception.com/09-04-2015/using-codeception-for-symfony-projects.html#.Vu8QjuJ96Ht) guide and tests run just fine if I download codeception with composer and run it with ``php bin/codecept run``

However, if I install it globally as told [here](http://codeception.com/quickstart#.Vu8PreJ96Hs) and run the command from the same project I get
 ``PHP Fatal error:  Class 'Symfony\Bundle\FrameworkBundle\FrameworkBundle' not found in /var/www/test/app/AppKernel.php on line 11
``

The project is a newly generated Symfony 2.8 one. What am I missing?

**Comment by poznet** [comment]
the same  here

**Comment by raistlin** [comment]
Sorry I don't use global installation.
Did you enable and configure Symfony2 and Doctrine2 modules?

**Comment by clytemnestra** [comment]
Yes, exactly like in the guide.

```yaml
modules:
    enabled:
        - Symfony2:
            app_path: '../../app'
            var_path: '../../app'
        - Doctrine2:
            depends: Symfony2
        - \AcmeBundle\Helper\Functional
```
