### ISSUE TITLE
Got empty response when using $I->amOnPage()

### ISSUE THREAD

**Issue by ohfang** [Codeception/Codeception#2932]
```php
<?php
$I = new ApiTester($scenario);
$I->wantTo('do something');
$I->amOnPage('http://api.qijiayoudao.com/account');
// $I->sendGET('http://api.qijiayoudao.com/account');
$data = $I->grabResponse();
debug::log($data);
$I->seeResponseIsJson();
$I->seeResponseCodeIs(200);
$I->seeResponseContainsJson(['status' => false]);
```

response is empty, so the `seeResponseContainsJson` assertion fails!
but if I use `$I->sendGET($sameUrl);`, then everything is OK.

**Comment by DavertMik** [comment]
Yep. `amOnPage` does not belong to REST module so doesn't store responses. Use `sendGet` for it. If you use Codeception 2.1 I'd recommend you to hide PhpBrowser module in depends section, so you won't be confused anymore:

```yaml
modules:
    enabled:
        REST:
             url: http://localhost/api/v1
            depends: PhpBrowser
```

Thus, don't use `amOnPage` in REST testing
