### ISSUE TITLE
How i can send custom header in WebDriver?

### ISSUE THREAD

**Issue by maxgu** [Codeception/Codeception#2935]
I used PhpBrowser method
```php
$this->setHeader('X-Requested-With', 'Codeception');
```
and now i use `phantomjs` and get error
```shell
[RuntimeException] Call to undefined method AcceptanceTester::setHeader
```
My config:
```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: 'http://localhost:8080/'
            browser: phantomjs
        - \Helper\Acceptance
        - \Helper\Fixtures
        - Db
```
