### ISSUE TITLE
WebDriver::switchToIframe() vs InnerBrowser::switchToIframe()

### ISSUE THREAD

**Issue by ijstanley** [Codeception/Codeception#2967]
Hi, I'm using Codeception 2.1.7.

When I'm using WebDriver alongside any module that extends InnerBrowser and run codecept build, there are no errors reported but the resulting *TesterActions file contains two separate method definitions with the same name: ```switchToIFrame()```

``` php
...
     * @see \Codeception\Lib\InnerBrowser::switchToIframe()
     */
    public function switchToIframe($name) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('switchToIframe', func_get_args()));
    }
...
     * @see \Codeception\Module\WebDriver::switchToIFrame()
     */
    public function switchToIFrame($name = null) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('switchToIFrame', func_get_args()));
    }
...
```

This results in the following error:
```
PHP Compile Error &#039;yii\base\ErrorException&#039; with message &#039;Cannot redeclare _generated\WidgetAcceptanceTesterActions::switchToIFrame()&#039;
```

The relevant config yml looks like:
``` yml
class_name: WidgetAcceptanceTester
modules:
    enabled:
        - WebDriver
        - Yii2
    config:
        WebDriver:
            url: 'http://localhost:8002'
            browser: 'firefox'
        Yii2:
            configFile: 'tests/config/acceptance.php'
```

This also occurs when I use REST (which depends on PhpBrowser/InnerBrowser):

``` yml
class_name: WidgetAcceptanceTester
modules:
    enabled:
        - PhpBrowser
        - REST
        - WebDriver
    config:
        WebDriver:
            url: 'http://localhost:8002'
            browser: 'firefox'
        PhpBrowser:
            url: 'http://localhost:8002'
        REST:
            url: 'http://localhost:8002'
            depends: 'PhpBrowser'
```

Am I doing anything wrong? I'm currently hacking it by commenting out WebDriver's method before building (I'm not needing the method at the moment).

Thanks for your attention.

**Comment by Naktibalda** [comment]
Don't enable WebDriver and any of InnerBrowser modules in the same suite.
It is no longer possible in 2.2. #2470

http://codeception.com/03-05-2016/codeception-2.2.-upcoming-features.html#conflicts

**Comment by ijstanley** [comment]
Thanks for your response. I will be sure to avoid this.

It does however seem potentially counter-intuitive to me. I can see me (and others) needing to check a REST API response between browser interactions. An example is checking interaction event logs, something like:

- Load page
- Check API for logged page view event
- Click button
- Check API for logged click event
...

Is WebDriver capable of performing REST requests or would I need to use some other method (potentially another composer package) to complete this?

**Comment by Naktibalda** [comment]
The article explains this use case:

> If you were mixing WebDriver with PhpBrowser in order to use REST API inside acceptance tests, you can still have it. Don’t enable PhpBrowser but set it as dependent module for REST:

```yaml
modules:
    enabled:
        - WebDriver:
            url: http://localhost/
            browser: firefox
        - REST:
            url: http://localhost/api
            depends: PhpBrowser
```
