### ISSUE TITLE
Config being passed into module is not an array

### ISSUE THREAD

**Issue by spamoom** [Codeception/Codeception#2989]
I've submitted the below to the module developer who cannot reproduce, so may be a codeception issue? (site5/phantoman#42)

Hi There,

Codeception version = 2.1.7

My config:
```yml
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\LaravelEnvironmentSwitcher
        - WebDriver:
            browser: phantomjs
            url: http://acceptance-tests/
        - \Helper\Acceptance
        - Codeception\Extension\Phantoman
    config:
        Codeception\Extension\Phantoman:
            debug: true
```

I'm getting the following error on build and run of codeception

```bash
$  ./vendor/bin/codecept build
Building Actor classes for suites: acceptance, functional, unit
PHP Warning:  array_merge(): Argument #2 is not an array in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 22

Warning: array_merge(): Argument #2 is not an array in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 22
PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 77

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 77


PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 77

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 77
Starting PhantomJS Server
PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
Waiting for the PhantomJS server to be reachablePHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
.PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 70
Stopping PhantomJS ServerPHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 77

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 77

PHP Notice:  Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 77

Notice: Undefined index: silent in /Users/sam/code/www/clients/good-food-talks/vendor/codeception/codeception/src/Codeception/Extension.php on line 77
PhantomJS server stopped


  [Codeception\Exception\ExtensionException]
  Codeception\Extension\Phantoman
  PhantomJS server never became reachable


build [-c|--config [CONFIG]]
```

Any ideas what it could be? Seems a ModuleContainer is being passed into the construct instead of an array

**Comment by Naktibalda** [comment]
Change it to:
```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\LaravelEnvironmentSwitcher
        - WebDriver:
            browser: phantomjs
            url: http://acceptance-tests/
        - \Helper\Acceptance
        - \Codeception\Extension\Phantoman:
            debug: true
```

**Comment by DavertMik** [comment]
`Codeception\Extension\Phantoman` is not a module, so it should not be declared this way.

Please add it into `codeception.yml` file into `extensions` section just as [it is described in their repo](https://github.com/site5/phantoman#enabling-phantoman-with-defaults):

```yaml
extensions:
    enabled:
        - Codeception\Extension\Phantoman
```
