### ISSUE TITLE
Using modules only in default environment

### ISSUE THREAD

**Issue by ijstanley** [Codeception/Codeception#3006]
I'm needing to disable certain modules when using certain environments e.g. in one case I have an environment for running all tests locally, this uses a class extended from WebDriver:

```
...
modules:
    enabled:
        - WebDriver
        - OtherHelper
...
env:
    local:
        modules:
            enabled:
                - \Helper\LocalWebDriverHelper
...
```

How could I go about disabling WebDriver when using the local environment? I know moving it to its own environment is an option but I'm wondering if there a way to do this without having to always specify an environment.

I was hoping there would be a default environment so I could have done:

```
...
modules:
    enabled:
        - OtherHelper
...
env:
    default:
        modules:
            enabled:
                - WebDriver
    local:
        modules:
            enabled:
                - \Helper\LocalWebDriverHelper
...
```

or a disabled key so I could have done:

```
...
modules:
    enabled:
        - WebDriver
        - OtherHelper
...
env:
    local:
        modules:
            enabled:
                - \Helper\LocalWebDriverHelper
            disabled:
                - WebDriver
...
```

Neither of these appear to work and I can't find any documentation related to this. Any ideas?

Thanks for your time.
