### ISSUE TITLE
Possible enh. introduce new module DbPool

### ISSUE THREAD

**Issue by Ragazzo** [Codeception/Codeception#301]
So in different situations it is good to have more then 1 database (i think module SecondDb maybe was designed for that) so in this way i suggest to make new module that will have different number of database connection pools to manipulate, very useful i think. For example config file:

```
DbPool:
  pools:
      node1:
          class: 'YourValidConnectionClass' //"Db" by default
          charset: "utf-8"
          dsn: "valid dsn here"
          user: "valid user here"
          password: "pass"
          dump: "dump/path/some.sql"
          populate: true
          cleanup:
      node2:
          dsn: "valid dsn2 here"
          user: "valid user2 here"
          password: "pass2"
          dump: "dump/path/some2.sql"
          populate: true
          cleanup:
      ....
      nodeN:
          dsn: "valid dsnN here"
          user: "valid userN here"
          password: "passN"
          dump: "dump/path/someN.sql"
```

in the module implementation there will be all standard methods from Db module and one additional for selecting active node like:

```
$I->amInDatabase('node name');
$I->seeInDatabase();
```

@DavertMik maybe you have some suggestions also? i think this can also replace SecondDb module too.
