### ISSUE TITLE
Problem with Webdriver and firefox

### ISSUE THREAD

**Issue by abbeshamza** [Codeception/Codeception#3010]
I'm using Webdriver with firefox as a browser.
I'm trying to create a scenario for login but codeception fail to login.

this is my scenario :
```php
$email = "member@test.com";
$pwd="123456";

$I->amOnUrl('http://localhost/~hab/cooperons/front/login');
$I->fillField('input[name="username"]', $email);
$I->fillField('input[name="password"]',$pwd );
$I->click("//button[@aria-label='Se connecter']");
```
and this is my acceptance config : 
```yaml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Filesystem
        - FunctionalHelper


    config:
        WebDriver:
            url: ''
            browser: 'firefox'
            wait: 4
            window_size: 1024x768
            restart: true
            port: 4444
            capabilities:
                unexpectedAlertBehaviour: 'accept'
```
