### ISSUE TITLE
Unable to work with Chrome browser using Selenium webdriver

### ISSUE THREAD

**Issue by SSyar** [Codeception/Codeception#3042]
Starting selenium + chrome driver with this is command
`java -Dwebdriver.chrome.driver=chromedriver.exe -jar selenium.jar`
It start the server
This is my acceptance.suite.yml file
```
class_name: AcceptanceTester
modules:
       enabled:
          - WebDriver:
             url: ''
             browser: chrome
             window_size: 1280x768
curl:
               CURLOPT_TIMEOUT: 60
```
This is what i am receiving as error when i try to execute the test case
```
  [Facebook\WebDriver\Exception\UnknownServerException]
  unknown error: cannot parse capability: proxy
  from unknown error: must be a dictionary
    (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.2 x86_64) (WARNING: The server d
  id not provide any stacktrace information)
  Command duration or timeout: 518 milliseconds
  Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
  System info: host: 'FR301-216', ip: '172.16.102.106', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_65'
  Driver info: org.openqa.selenium.chrome.ChromeDriver
```
