### ISSUE TITLE
Codeception DB module exception

### ISSUE THREAD

**Issue by FaheemSultan** [Codeception/Codeception#3075]
i'm trying to connect to my db in codeception. provided following configurations in my api.suite.dist.yml and codeception.dist.yml file (i didn't know where to provide configurations so i provide in both api.suite.dist.yml  and codeception.dist.yml)

here is my api.dist.suite.yml

```yaml
class_name: ApiTester
modules:
    enabled:
        - PhpBrowser:
            url: http://192.168.1.143
        - REST:
            depends: PhpBrowser
            url: https://dev-tv.dna.fi/api/user/guest/epg
        - \Helper\Api
        - Db:
            dsn: 'mysql:host=127.0.0.1;dbname=db'
            user: 'username'
            password: 'passsword'
```
and here is my codeception.dist.yml

```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'mysql:host=127.0.0.1;dbname=db'
            user: 'username'
            password: 'password'
```

and this is the response i get 
```
 [Codeception\Exception\ModuleException]                                                                                         
  Db: SQLSTATE[28000] [1045] Access denied for user 'webapiuser'@'localhost' (using password: YES) while creating PDO connection  
                                                                                                                                  

run [-c|--config CONFIG] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]
```
