### ISSUE TITLE
Yaml parsing error when running functional tests with Symfony2 module

### ISSUE THREAD

**Issue by MAXakaWIZARD** [Codeception/Codeception#3082]
Here's my `functional.suite.yml` config
```yaml
class_name: FunctionalTester
modules:
    enabled:
        - Symfony2:
            environment: 'test'
            cache_router: true
            debug: true
        - Doctrine2:
            depends: Symfony2
        - \Helper\Functional
```
When running `codecept run functional` I'm getting such error:
`[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]                     
  The file "/path/to/app/config/assets.yml" does not contain valid YAML.`
`[Symfony\Component\Yaml\Exception\ParseException]                            
  Found unknown escape character "\." at line 8 (near "apply_to: "\.less$"").`
If I comment this line, there's another YAML parsing error from one of the bundles.

But I'm sure this is valid YAML since application runs just fine.
