### ISSUE TITLE
[RFC] Same methods names in different modules

### ISSUE THREAD

**Issue by Ragazzo** [Codeception/Codeception#313]
So to avoid this we need some mechanism, possible solutions:
- prefix/suffix methods with module name.

``` php
$I->db1_seeInDatabase();
$I->db2_seeInDatabase();
$I->seleniumMain_click();
$I->seleniumSlave_selectOption();
```
- make modules available through DI, something in this way:

``` php
$I->db1->seeInDatabase();
$I->db2->seeInDatabase();
$I->seleniumMain->click();
$I->seleniumSlave->selectOption();
```

Output will be the same, maybe with some notes of which module method was executed, but i think this info must be printed only in debug mode. As for me i vote for second method, because it is more flexible then prefix/suffix and more readable, can be made easy with `__call()` override or DI through properties. @DavertMik what do u think of this?

Also after this one will be solved, we no more need some modules named `DbPool` or `{somename}Pool` because modules can be accessed via aliases that was configured in suite config, for example see Yii1 `components`  part in config.

About aliases of modules, suite can be like this:

``` yaml
class_name: WebGuy
modules:
    enabled:
        - Selenium2
        - WebHelper
    config:
        SeleniumMain:
            class: '\Codeception\Module\Selenium2'
            url: 'http://localhost/yii_codecept/index.php'
            browser: firefox
            delay: 1000
        SeleniumSlave:
            class: '\Codeception\Module\Selenium2'
            url: 'http://localhost/someotherproj/index.php'
            browser: firefox
            delay: 1000
//same as for multiple databases
```
