### ISSUE TITLE
Laravel4 + codeception 2.1.5+ missing autoload

### ISSUE THREAD

**Issue by djeux** [Codeception/Codeception#3134]
I have created a module called _support\Helper\Init.php which is defined like this in functional.suite.yaml

```yaml
modules:
    enabled:
        - Laravel4
        - \Helper\Functional
        - Asserts
        - \Helper\Init
        - REST:
             depends: Laravel4
```

Before upgrading to 2.1.5 this code was working as intended.

```php
public function _beforeSuite($settings = [])
{
    parent::_beforeSuite($settings);

    \Mail::pretend(true);
}
```

After upgrade to 2.1.5+, it throws this
```
PHP Fatal error:  Class 'Mail' not found in /var/www/project/app/tests/_support/Helper/Init.php on line 14
```

Anything changed in autoloading process? I have checked changelog but can't seem to find the change that broke this.
