### ISSUE TITLE
[Regression] grabFromCurrentUrl() doesn't work with REST in v2.2

### ISSUE THREAD

**Issue by konstin** [Codeception/Codeception#3197]
After upgrading to v2.2, `grabFromCurrentUrl()` does no longer return the url requested using `sendGET()` but instead errors after printing `[LogicException] The page history is empty.`. This change is not mentioned in the release notes.

#### Minimal example
The following example works v2.1 but fails in v2.2
**acceptance.suite.yml:**
```
class_name: AcceptanceTester
modules:
    enabled:
        - REST:
            depends: PhpBrowser
            url: http://localhost:8080
        - PhpBrowser
```

**acceptance/grabUrlCept.cept:**
```
$I = new AcceptanceTester($scenario);
$I->wantTo('I want to retrieve the current URL');
$I->sendGET('/');
$I->grabFromCurrentUrl();
```
