### ISSUE TITLE
Db module's cleanup operation hangs indefinitely "Waiting for table metadata lock" (MySQL)

### ISSUE THREAD

**Issue by motin** [Codeception/Codeception#3229]
Using codeception 2.2.1

After the first test, codeception hangs indefinitely on:

```
Scenario --
```

MySQL shows that a query `drop table foo` is active with PROCESSLIST_STATE set to "Waiting for table metadata lock"

The foo table is about the tenth table being dropped. 

```
------------
TRANSACTIONS
------------
Trx id counter 3157747
Purge done for trx's n:o < 3157617 undo n:o < 0 state: running but idle
History list length 330
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 3157515, not started
MySQL thread id 3195, OS thread handle 0x7fcca75b9700, query id 1722662 172.17.0.22 6101e6448f1b5d4a Waiting for table metadata lock
drop table `foo`
---TRANSACTION 3138876, not started
MySQL thread id 3012, OS thread handle 0x7fcca767c700, query id 1722665 192.168.99.1 root init
SHOW ENGINE INNODB STATUS
---TRANSACTION 0, not started
MySQL thread id 3011, OS thread handle 0x7fcca763b700, query id 1718616 192.168.99.1 root cleaning up
---TRANSACTION 3157614, ACTIVE 4 sec
MySQL thread id 3199, OS thread handle 0x7fcca75fa700, query id 1722637 172.17.0.22 6101e6448f1b5d4a cleaning up
Trx read view will not see trx with id >= 3157615, sees < 3157615
```

Killing the query is the only way to interrupt codeception and get back to the shell:

```
Scenario --

  [Codeception\Exception\ModuleException]
  Db: SQLSTATE[70100]: \Unknown error>>: 1317 Query execution was interrupted


Exception trace:
 () at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Module/Db.php:270
 Codeception\Module\Db->cleanup() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Module/Db.php:226
 Codeception\Module\Db->_before() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:58
 Codeception\Subscriber\Module->before() at n/a:n/a
 call_user_func() at /app/dna/vendor/symfony/event-dispatcher/EventDispatcher.php:184
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /app/dna/vendor/symfony/event-dispatcher/EventDispatcher.php:46
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:124
 Codeception\PHPUnit\Listener->fire() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/PHPUnit/Listener.php:95
 Codeception\PHPUnit\Listener->startTest() at /app/vendor/neam/yii-dna-test-framework/vendor/phpunit/phpunit/src/Framework/TestResult.php:388
 PHPUnit_Framework_TestResult->startTest() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Test/Test.php:68
 Codeception\Test\Test->run() at /app/vendor/neam/yii-dna-test-framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php:753
 PHPUnit_Framework_TestSuite->run() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:98
 Codeception\PHPUnit\Runner->doEnhancedRun() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/SuiteManager.php:152
 Codeception\SuiteManager->run() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Codecept.php:209
 Codeception\Codecept->runSuite() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Codecept.php:178
 Codeception\Codecept->run() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Command/Run.php:329
 Codeception\Command\Run->runSuites() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Command/Run.php:256
 Codeception\Command\Run->execute() at /app/vendor/neam/yii-dna-test-framework/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /app/vendor/neam/yii-dna-test-framework/vendor/symfony/console/Application.php:815
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/neam/yii-dna-test-framework/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /app/vendor/neam/yii-dna-test-framework/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/src/Codeception/Application.php:103
 Codeception\Application->run() at /app/vendor/neam/yii-dna-test-framework/vendor/codeception/codeception/codecept:33
```

Global codeception.yml:

```
paths:
    tests: ./codeception
    log: ./codeception/_log
    data: ./codeception/_data
    helpers: ./codeception/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
modules:
    config:
        Db:
            dsn: 'mysql:host=localdb;port=3306;dbname=db_test'
            user: '...'
            password: '...'
            dump: ./codeception/_data/dump.sql
            populate: true
            cleanup: true
            reconnect: true
        MailCatcher:
            url: 'http://mailcatcher'
            port: '25'
```

Test suit yml:

```
class_name: CodeGuy
modules:
    enabled: [Db, CodeHelper, Asserts]
```
