### ISSUE TITLE
SOAP and WebDriver

### ISSUE THREAD

**Issue by eXorus** [Codeception/Codeception#3250]
Hello,

Why SOAP doesn't work with WebDriver like REST do it ?

This is working for REST : 

``` yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            browser: firefox
            url: http://localhost/myapp
            host: localhost
            port: 4446
        - REST:
            url: http://localhost/myapp
            depends: PhpBrowser
        - \Helper\Acceptance
```

This is NOT working for SOAP :

``` yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            browser: firefox
            url: http://localhost/myapp
            host: localhost
            port: 4446
        - SOAP:
            url: http://localhost/myapp
            endpoint: locahost
            depends: PhpBrowser
        - \Helper\Acceptance
```

Result will be
  [Codeception\Exception\ModuleConfigException]  
  PhpBrowser module is not configured!                              

  Options: url are required  
  Please, update the configuration and set all the required fields

Is there any other solution ? it nice and very fast to call API at the beginning of acceptance test to construct some data.
