### ISSUE TITLE
[Codeception\Exception\ConfigurationException]   Suite app was not loaded

### ISSUE THREAD

**Issue by RomaGilyov** [Codeception/Codeception#3279]
Hello, lately start to get this exception while api testing:

```
        [Codeception\Exception\ConfigurationException]   

     Suite app was not loaded
```

My api.suite.yml:

```yaml
     class_name: ApiTester

     modules:

    enabled:

        - \Helper\Api

        - Asserts

        - Filesystem

        - REST:

            depends: Laravel5

        - Laravel5:

            environment_file: .env.testing

            url: http://api.dev

```

Codeception 2.2.1
Laravel 5.2

How to solve this issue? 

Thanks for attention. 
With best regards
Roman
