### ISSUE TITLE
Some modules are not loaded from suite config in 2.2.2

### ISSUE THREAD

**Issue by Mitrichius** [Codeception/Codeception#3292]
There is modules section of my suite config:
```
modules:
    enabled:
        - \Helper\CustomAsserts
        - \Helper\Api
        - \Helper\Export
        - \Helper\Common
        - Asserts
        - PhpBrowser:
            url: 'http://export.lc'
        - REST:
           depends: PhpBrowser
           url: 'http://export.lc/'
```

When I run _build_ command in 2.2.2, first two helpers aren't loaded:
```
\ExportTester includes modules: PhpBrowser, REST, \Helper\Export, \Helper\Common, Asserts
 -> RhApiTesterActions.php generated successfully. 0 methods added
```

Same config on 2.2.1: 
```
\ExportTester includes modules: \Helper\CustomAsserts, \Helper\Api, \Helper\Export, \Helper\Common, Asserts, PhpBrowser, REST
 -> RhApiTesterActions.php generated successfully. 0 methods added
```

I've changed helpers' order with same result: first two are ignored. 
As w/a: I moved Rest and PhpBrowser modules to the beginning, all helpers were loaded.

**Comment by nnnikolay** [comment]
I can confirm the same behaviour

With following config file

    enabled:
        - \Helper\Functional
        - REST:
            depends: PhpBrowser
            url: http://test.app/
        - Db

it does not work

With that version

    enabled:
        - REST:
            depends: PhpBrowser
            url: http://test.app/
        - \Helper\Functional
        - Db

it works fine on 2.2.2

**Comment by DavertMik** [comment]
I couldn't reproduce it personally but I this is my first priority to work on

**Comment by Mitrichius** [comment]
@DavertMik, looks like it's reproduced only when some modules are enabled in global config. 
[github-3292.zip](https://github.com/Codeception/Codeception/files/347316/github-3292.zip)

**Comment by glensc** [comment]
i can confirm similar problem when i have .dist and .dist.yml files present:

my `acceptance.dist.yml`:
```
class_name: AcceptanceTester
modules:
    enabled:
        - Filesystem
        - PhpBrowser:
            url: http://localhost/eventum/
        - \Helper\Acceptance

```

and `acceptance.yml`:
```
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost/~glen/eventum-setup/
```

if i renamed "enabled" to "enabled2" in `acceptance.yml` problem disappeared,

looks like issue of merging two configs?

**Comment by DavertMik** [comment]
Thanks @Mitrichius I'm using your sample to reproduce it as well.

Looks like this bug is far more deeper and looks like appeared in 2.1. When arrays are merged from global and local configs values arrays are overridden and arrays are not merged.

**Comment by loesalleman** [comment]
Hi, since updating to 2.2.3 I experience the following exception when running my tests locally:[Codeception\Exception\ModuleConflictException]  Helper\PhantomWebDriver module conflicts with Helper\ExtendedWebDriver

PhantomWebDriver and ExtendedWebDriver are both custom extensions on the WebDriver module.

I work with config files acceptance.suite.yml and acceptance.suite.dist.yml (see below). The problem occurs when I run --env phantomjs. It looks like that, although running locally, codeception loads the default module from the dist.yml file concurrently with my local --env phantomjs specified module. Changing the enabled modules in the files confirmes this behaviour. 
I do not expect this to be the desired behaviour and expect this to be a bug resulting from the mentioned fix, am I right @DavertMik  ? Thanks in advance.

acceptance.suite.yml:
```
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\ExtendedWebDriver:
env:
    phantomjs:
        modules:
            enabled:
                - \Helper\PhantomWebDriver:
```
acceptance.suite.dist.yml:
```
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\ExtendedWebDriver:
env:
    phantomjs:
        modules:
            enabled:
                - \Helper\ExtendedWebDriver:
```

**Comment by DavertMik** [comment]
If those modules share extend the same class they will conflict, this is expected behavior. They should not be used together. Probably they both instantiate browser session and this is not something you expect to.

Sorry I have little understanding on what your extended helpers do but I have several suggestions that might help you. 

1. override `_conflicts` method of PhantomWebDriver:

```php
    public function _conflicts()
    {
        return 'Codeception\Lib\Interfaces\Web';
    }
// change to 
    public function _conflicts()
    {
        return null;
    }
```
this will disable conflict checks for this module.

2. Probably cleaner approach, make PhantomWebDriver not to extend WebDriver module but to connect to `\Helper\ExtendedWebDriver` as it is described in [documentation](http://codeception.com/docs/06-ModulesAndHelpers#Accessing-Other-Modules)

```php
$this->getModule('\HelperExtendedWebDriver')->...
// you can get webdriver instance:
$this->getModule('\HelperExtendedWebDriver')->webDriver
```

3. You can also disable a module in environment, so if you use PhantomJS helepr you can inherit it from ExtendedWebDriver and enable only it in tests:

```yaml
env:
    phantomjs:
        modules:
            disabled:
                - \Helper\ExtendedWebDriver:
            enabled:
                - \Helper\PhantomWebDriver:
```
---

Sorry for the mess with this issue but this was definitely a bug in merging conflicts. Now when conflicts were merged properly you got an error.
