### ISSUE TITLE
jQuery events not firing correctly

### ISSUE THREAD

**Issue by jj-barlow** [Codeception/Codeception#3297]
Codeception 2.2.2 with PhantomJS 2.1.1.

On my given page I have a select element, managed by the jQuery.on('change') event for when a user modifies it. When this happens the JS does a window.location.assign using the value assigned by the selected option to effectively refresh the page with new data, appending an &ID=somevalue onto the end of it.

The test doesn't appear to be following the location.assign or even firing the change event at all. I attempted to call the line manually by doing $I->executeJS('window.location.assign("someurl")'); to no avail.

**Comment by DavertMik** [comment]
Did you try to run it in real browser with Selenium? PhantomJS can be unstable by itself

**Comment by jj-barlow** [comment]
I've got everything running in a web server inside a Docker container, PhantomJS is running in the background in WebDriver mode on port 4444. My acceptance.suite.yml file is as follows.

```
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - \Helper\Acceptance
    config:
        WebDriver:
            url: http://localhost/php
            browser: firefox
            restart: true
            clear_cookies: true
            unexpectedAlertBehaviour: accept
            http_proxy: direct
            capabilities:
                javascriptEnabled: true
                nativeEvents: true
                webStorageEnabled: true
                phantomjs.cli.args: ['--ignore-ssl-errors=true']
```

Hope this makes sense, I assume everything is setup the way it should be.
