### ISSUE TITLE
cannot get the rawBody in controller when I use $I->sendPost

### ISSUE THREAD

**Issue by JunelanMe** [Codeception/Codeception#3313]
1. I config the yii2 and the rest in the functional yml.
```yaml
modules:
 enabled:
      - Yii2
      - REST
config:
      Yii2:
 configFile: 'config/functional.php'
```
2. the following is the port of Controller and the Cest code

ArchiveController:
```php
    public function actionTest(){
        $req = Yii::$app->request;
        $initData = json_decode($req->getRawBody());
        codecept_debug("begin to print rawBody");
        codecept_debug($initData);
    }
```
Cest:
```php
    public function testxxx(FunctionalTester $I, $scenario)
    {
        $I = new ArchiveBasicSteps($scenario);
        $I->signInA7('admin001@vagrant.com' , '222222');

        Yii::$app->request->setRawBody("xxxxxxx");
        codecept_debug(Yii::$app->request->getRawBody());
        $I->sendPOST('/archive/test',array("1"=>"2"));
        $I->seeResponseContains("XXXXXX");
    }
```
when  I run the testxxx the output under "begin to print rawBody" in Controller always empty
