### ISSUE TITLE
 [phpunit] Codeception\Exception\InjectionException: Service di is not defined

### ISSUE THREAD

**Issue by esayr** [Codeception/Codeception#3333]
UserTest.php
```php
<?php

namespace App\Test\Unit\Models;

use App\Model\User;

class UsersTest extends \Codeception\Test\Unit {

    protected function _before() {
        $this->user = new User;
    }

    public function testGetSource() {
        $this->assertEquals($this->user->getSource(), 'users');
    }
}
```

unit.suite.yml
```yml
class_name: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
        - Phalcon:
            bootstrap: 'tests/_config/bootstrap.php'
```

`codecept run`  works as expected

BUT, when I Run `ant phpunit`  The following error is returned

```shell
phpunit:
  [phpunit] PHPUnit 5.3.2 by Sebastian Bergmann and contributors.
  [phpunit]
  [phpunit] Runtime:       PHP 5.6.19 with Xdebug 2.3.3
  [phpunit] Configuration: /data/www/insurance.com/build/phpunit.xml
  [phpunit]
  [phpunit] E                                                                   1 / 1 (100%)
  [phpunit]
  [phpunit] Time: 547 ms, Memory: 19.75Mb
  [phpunit]
  [phpunit] There was 1 error:
  [phpunit]
  [phpunit] 1) App\Test\Unit\Models\UsersTest::testGetSource
  [phpunit] Codeception\Exception\InjectionException: Service di is not defined and can't be accessed from a test
  [phpunit]
  [phpunit] /data/www/insurance.com/vendor/codeception/codeception/src/Codeception/Test/Metadata.php:182
  [phpunit] /data/www/insurance.com/vendor/codeception/codeception/src/Codeception/Test/Unit.php:49
  [phpunit]
  [phpunit] FAILURES!
```
