### ISSUE TITLE
Parameters token replacement with complex structure

### ISSUE THREAD

**Issue by neoascetic** [Codeception/Codeception#3339]
Given `settings.yml` containing

```
api:
  db:
    host: 127.0.0.1
    database: db
    username: user
    password: pass
```

and `codeception.yml` containing

```
params:
  - settings.yml
```

I want `acceptance.yml` parameters replacement

```
modules:
  enabled:
    - Db:
        dsn: 'mysql:host=%api.db.host%;dbname=%api.db.database%'
        user: '%api.db.username%'
        password: '%api.db.password%'
```

resulting in

```
modules:
  enabled:
    - Db:
        dsn: 'mysql:host=127.0.0.1;dbname=db'
        user: user
        password: pass
```
