### ISSUE TITLE
Variable in config file

### ISSUE THREAD

**Issue by cajoy** [Codeception/Codeception#334]
I have following config file for development:

```
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
    config:
        PhpBrowser:
            url: 'http://site.dev'
```

How can I set PhpBrowser.url as variable? Let's say I can get variable data from server environment. And would like to use the same config for DEVELOPMENT and PRODUCTION environments without amending config file each time.

something like:

```
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
    config:
        PhpBrowser:
            url: $url
```

Is there any pre-parser of YAML files? Or any way to pass variable to YAML file?

Probably I can create wrapper what will update URL before each test run but that's not the case...

Thanks..
