### ISSUE TITLE
Error when using Recorder Extension on Codeception 2.2.2

### ISSUE THREAD

**Issue by KrileZero** [Codeception/Codeception#3356]
Hi,

Recorder Extension is not working in codeception 2.2.2 , but it is okay in version 2.1 . 

OS: Windows 7
Codeception Version: 2.2.2

**codeception.yml**
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Recorder
    config:
        Codeception\Extension\Recorder:
            delete_successful: false
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```

**Sample Cest**
```
<?php
class sampleCest
{
    public function _before(AcceptanceTester $I)
    {
    }
    public function _after(AcceptanceTester $I)
    {
    }
    // tests
    public function tryToTest(AcceptanceTester $I)
    {
        $I->amOnPage("/");
    }
}
```

**Output in Terminal**
```
Charles@Charles-PC MINGW64 /d/Automation/Project1
$ vendor/bin/codecept run
Codeception PHP Testing Framework v2.2.2
Powered by PHPUnit 5.4.7 by Sebastian Bergmann and contributors.

Acceptance Tests (1) ---------------------------------------
⏺ Recording ⏺ step-by-step screenshots will be saved to D:\Automation\Project1\tests/_output/</info>
Directory Format: record_5790b0d7ec4de_{testname} ----
E sampleCest: Try to test (0.59s)


  [PHPUnit_Framework_Exception]
  file_put_contents(D:\Automation\Project1\tests/_output/\record_5790b0d7ec4de_sa
  mpleCest:tryToTest\index.html): failed to open stream: Invalid argument

```
