### ISSUE TITLE
var_path ignored in Symfony3 setup

### ISSUE THREAD

**Issue by benr77** [Codeception/Codeception#3361]
Using Codeception 2.2 and Symfony 3.0.8.

The `bootstrap.php.cache` is location in `<project-root>/var`. So to tell Codeception where to find it you must specify the `var_path` option as stated in the docs.

functional.suite.yml

```
class_name: FunctionalTester
modules:
  enabled:
    - Symfony2:
        app_path: 'app'
        var_path: 'var'
        environment: test
    - Doctrine2:
        depends: Symfony
    - \Helper\Functional
```

However, this ignores the var_path setting and gives me the error `Symfony bootstrap file not found in PROJECT_ROOT/app/bootstrap.php.cache` (i.e. using the default **app** directory).

Weirdly, if I change the value to something slightly different then it picks it up - e.g. `var_path: 'varXXX'` will result in the error `Symfony bootstrap file not found in PROJECT_ROOT/varXXX/bootstrap.php.cache`

To get this to work correctly, I ALSO have to specify the var_path in codeception.yml:

codeception.yml

```
modules:
  config:
    Symfony:
      environment: 'test'
      app_path: 'app'
      var_path: 'var'
```

If I only specify the var_path in one of the two config files, it is ignored and the default value of "app" is used.

I presume this is a bug with the merging of the two config locations.
