### ISSUE TITLE
Acceptance tests writing in testing db and reading from production

### ISSUE THREAD

**Issue by ivan-atanasov** [Codeception/Codeception#3368]
I am using Laravel5, Codeception 2.2.2 and phantomjs 2.1.1. For unit and functional tests everything works fine. My problem is with Acceptance tests.
Here is my acceptance.suite.yml
````
class_name: AcceptanceTester
modules:
  enabled: [WebDriver, Db, \Helper\Acceptance]
  config:
     WebDriver:
       url: http://domain.dev
       browser: phantomjs
       window_size: maximize
     Db:
       dsn: 'mysql:host=localhost;dbname=database_testing'
       user: 'homestead'
       password: 'secret'
       dump: tests/_data/dump.sql
       cleanup: true
````

Each time I run the tests, they write in the **database_testing** database, but after that, they try to read from **database_production**. A simple example is when I try to test logging in of a user. I create the user in the setUp() method and the record is created in **database_testing**. But when I actually test the logging in, the test try to read from **database_production**.

I cleared Laravel's config cache, I tried creating a separate environment in Codeception to run the acceptance tests in, but no luck. I also tried setting **clanup: false** - no luck.
