### ISSUE TITLE
REST module tests report 0% coverage 

### ISSUE THREAD

**Issue by leetuanchinh** [Codeception/Codeception#3371]
I use Phalcon Framework.

File OrtherController
```php
public function detailAction($cityId)
{         
    $dataRoutes = $this->ortherService->getCityDetail($cityId);
    return $this->response($dataRoutes);
}
```

File codeception.yml
```yaml
coverage:
    enabled: true
    remote: true
    c3_url: 'http://t4l.local/index-test.php'
    include:
        - apps/*
        - libraries/*
```
File DetailCept.php
```php
<?php 
$I = new ApiTester($scenario);
$I->wantTo('perform actions and see result');
$I->sendGET('orther/citydetail/4529');
$I->seeResponseCodeIs(\Codeception\Util\HttpCode::OK); // 200
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'data' => [
        'city_id' => "4529"
    ]
]);
```
I run this command

> ./vendor/bin/codecept run --coverage --coverage-xml --coverage-html

Output

> Code Coverage Report:
>   2016-07-25 07:53:19
> 
>  Summary:
>   Classes:  7.59% (11/145)
>   Methods:  0.00% (0/486)
>   Lines:    0.00% (0/11085)
> 
> Remote CodeCoverage reports are not printed to console
> 
> HTML report generated in coverage
> XML report generated in coverage.xml

I open file tests/_output/api.remote.coverage/index.html. 
Observe : not coverage and always report 0%
I tried codeception 2.2.2 & 2.2.3 , it doesn't work

Plz help me.
