### ISSUE TITLE
Phalcon functional coverage REQUEST_TIME

### ISSUE THREAD

**Issue by gimler** [Codeception/Codeception#3374]
I get unit tests with coverage to work. But the functional tests only works without coverage.

If i try `phpdbg -qrr bin/codecept run functional --coverage` i get the following exception:
```
[PHPUnit_Framework_Exception]  
  Undefined index: REQUEST_TIME
```
tests/functional.suite.yml
```
class_name: FunctionalTester
modules:
    enabled:
        - REST:
            depends: Phalcon
        - \Helper\Functional
        - Phalcon:
            bootstrap: 'app/config/bootstrap.php'
            cleanup: true
            savepoints: true
```

app/config/bootstrap.php
```
require_once __DIR__ . '/../../vendor/autoload.php';

use Phalcon\Mvc\Micro;
use Phalcon\Di\FactoryDefault;
use Phalcon\Mvc\Micro\Collection as MicroCollection;

$di = new FactoryDefault();

$di->set('collection.auth', function () {
    $auth = new MicroCollection();
    $auth->setHandler('Controller\Auth', true);
    $auth->get('/login', 'loginAction');

    return $auth;
});

$app = new Micro($di);
$app->mount($app['collection.auth']);

return $app;
```
