### ISSUE TITLE
API REST Cannot declare class Symfony\Component\HttpFoundation [...] because the name is already in use in [...]/var/bootstrap.php.cache

### ISSUE THREAD

**Issue by jpsymfony** [Codeception/Codeception#3393]
#### What are you trying to achieve?

I'm trying to launch all my tests (unit + api) in Symfony3.1. When I separately launch them, everything goes well, but if I launch /vendor/bin/codecept run, unit tests are properly launched and are successful, but the api test always fails and are not lauched.
### Details
- Codeception version: 2.2.3
- PHP Version: 7
- Operating System: Ubuntu
- Installation type: Composer
- Suite configuration:

``` yml
class_name: ApiTester
modules:
    enabled:
        - \AppBundle\Helper\Api
        - REST:
            url: /v1
            depends: Symfony
        - Doctrine2:
            depends: Symfony
        - Symfony:
            app_path: '../../app'
            var_path: '../../var'
```

Here's my codeception.yml

``` yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
include:
    - src/AppBundle
coverage:
    enabled: true
    whitelist:
        include:
            - src/*
        exclude:
            - src/AppBundle/Entity/*
            - src/AppBundle/tests/*
            - src/AppBundle/codeception.yml
```

Any idea how I could do? I have the following call stack:

```
Call Stack:
    0.0003     366728   1. {main}() /var/www/metadata/vendor/codeception/codeception/codecept:0
    0.0491    4670576   2. Codeception\Application->run() /var/www/metadata/vendor/codeception/codeception/codecept:33
    0.0491    4670576   3. Symfony\Component\Console\Application->run() /var/www/metadata/vendor/codeception/codeception/src/Codeception/Application.php:103
    0.0507    4815576   4. Symfony\Component\Console\Application->doRun() /var/www/metadata/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
    0.0508    4815576   5. Symfony\Component\Console\Application->doRunCommand() /var/www/metadata/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
    0.0508    4815576   6. Symfony\Component\Console\Command\Command->run() /var/www/metadata/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:815
    0.0512    4818056   7. Codeception\Command\Run->execute() /var/www/metadata/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
    0.1006    6650440   8. Codeception\Command\Run->runIncludedSuites() /var/www/metadata/vendor/codeception/codeception/src/Codeception/Command/Run.php:261
    0.1042    6657592   9. Codeception\Command\Run->runSuites() /var/www/metadata/vendor/codeception/codeception/src/Codeception/Command/Run.php:298
    0.1660    9802776  10. Codeception\Codecept->run() /var/www/metadata/vendor/codeception/codeception/src/Codeception/Command/Run.php:329
    0.1676    9807696  11. Codeception\Codecept->runSuite() /var/www/metadata/vendor/codeception/codeception/src/Codeception/Codecept.php:178
    0.1693   10023184  12. Codeception\SuiteManager->initialize() /var/www/metadata/vendor/codeception/codeception/src/Codeception/Codecept.php:207
    0.1693   10023184  13. Codeception\Module\Symfony->_initialize() /var/www/metadata/vendor/codeception/codeception/src/Codeception/SuiteManager.php:81
```

I followed it but the problem comes from the SuiteManager, when it calls the _initialize method of my AppBundle\Helper\Api which is quite simple:

``` php
<?php
namespace AppBundle\Helper;

// here you can define custom actions
// all public methods declared in helper class will be available in $I

class Api extends \Codeception\Module
{
    /**
     * Checks over the given HTTP header and (optionally)
     * its value, asserting that are there
     *
     * @param $header
     * @param $value
     */
    public function seeHttpHeaderLike($header, $value)
    {
        $header = $this->getModule('REST')->grabHttpHeader($header);
        $this->assertRegExp($value, $header);
    }
}
```

I always have the same error:
Fatal error: Cannot declare class Symfony\Component\HttpFoundation\FileBag, because the name is already in use in [...]/var/bootstrap.php.cache on line 308

If I removed some code calling the FileBag (request attributes), I have the same error but with Symfony\Component\HttpFoundation\Request

Thanks in advance
