### ISSUE TITLE
Issue with grabbing text from <td> tag with webdriver module

### ISSUE THREAD

**Issue by p-saxena** [Codeception/Codeception#3405]
Hello,
I am trying to grab value from `<td>` tag. The html structure is as follows:
```html
<tr ng-click="selectVariation('baa34c70-57c7-11e6-9589-c9db35d7d7c5'); toggleMainImage(500)" data-index="2" class="selected">
        <td class="selector">
            <input type="radio" ng-value="'baa34c70-57c7-11e6-9589-c9db35d7d7c5'" value="baa34c70-57c7-11e6-9589-c9db35d7d7c5" name="3ed43cb0-fbd5-11e4-9e07-879c14e1f343" ng-model="product.variation_selection" class="ng-pristine ng-untouched ng-valid">
        </td>
        <td class="year">2015</td>
        <td class="condition">Very good</td>
        <td class="price">€7,150
                            <del class="hidden-xs">€7,750</del>
        </td>
```
[html_structure.txt](https://github.com/Codeception/Codeception/files/401109/html_structure.txt)

I am trying to grab value '2015' from `<td class="year">2015</td>`
I am using  WebDriver module and so tried with methods like `grabTextFrom` and `grabValueFrom`. But I get error in both cases .

> console output:
PHP Fatal error:  Call to a member function runStep() on null in /home/watchmaster/work/ttm_fe_portal/tests/_support/_generated/AcceptanceTesterActions.php on line 1513

FATAL ERROR. TESTS NOT FINISHED.
Call to a member function runStep() on null 

I have this test:
```php
const SELECTED_YEAR_STOCKITEM='.selected .year';
return $this->grabTextFrom(self::SELECTED_YEAR_STOCKITEM);
```
I tried to use `grabValueFrom` method as well but I get same error.

Other details are:
* Codeception version: 2.1.7 
* PHP Version: 5.6
* Operating System: Ubuntu 15.10
* Installation type: Phar

```yml
modules:
  enabled:
      - WebDriver:
      - \Helper\EnvSpecificHelper
      - \Helper\DbHelper
      - Asserts
      - Db
  config:
    WebDriver:
      host: localhost
      port: 4444
      browser: firefox
      window_size: 1024x768
      url: 'https://www.watchmaster.com/de'
      capabilities:
        unexpectedAlertBehaviour: 'accept'
    \Helper\EnvSpecificHelper:
      languageCode: de_DE
      environment: testing-de_DE

      <<: *testingSimpleUrls_de_DE
      <<: *country_de_DE```
```
