### ISSUE TITLE
Laravel4 unable to keep authentication

### ISSUE THREAD

**Issue by djeux** [Codeception/Codeception#3406]
I'm using codeception 2.1.11 (last version that supports Laravel 4).

Running a test 

```php
public function testProcess(FunctionalTester $I)
	{
		$user = UserAccount::find(1);

		$I->amGoingTo('open page without beeing logged in');

		$I->amOnPage('/site/pay?to=asdfasdfadf&amount=0.10');
		$I->seeResponseCodeIs(200);
		$I->see('You must be logged in to view this page!', '.sb-msg');

		$I->amLoggedAs($user);

		$I->seeAuthentication();

		$I->amGoingTo('try open page being logged in');
		$I->amOnPage('/site/pay?to=asdfasdfadf&amount=0.10');

		$I->dontSee('You must be logged in to view this page!', '.sb-msg');
	}

```

After calling $I->amOnPage() the second time the login state does not persist. And I am unable to fetch the logged in user from the controller

```php
class SiteController extends BaseController 
{

    public function __construct(AuthManager $auth)
    {
        $this->beforeFilter('auth');
        $this->auth = $auth;
        $this->user = $auth->user(); // $auth->user() IS NULL, but should be the logged in user
    }

}
```

**Comment by janhenkgerritsen** [comment]
Can you show me your suite configuration file?

**Comment by djeux** [comment]
```yaml


class_name: FunctionalTester
modules:
    enabled:
        - Laravel4:
            cleanup: false
        - \Helper\Functional
        - Asserts
        - \Helper\Init
        - REST:
             depends: Laravel4


```

**Comment by janhenkgerritsen** [comment]
Can you try to place the Laravel4 module below the REST module in your suite config file, so it looks like this:

```
class_name: FunctionalTester
modules:
    enabled:
        - \Helper\Functional
        - Asserts
        - \Helper\Init
        - REST:
             depends: Laravel4
        - Laravel4:
             cleanup: false
```

**Comment by djeux** [comment]
Now there's an error with \Helper\Init

Class 'Artisan' not found.

```php
public function _before(TestCase $testCase)
	{
		\Artisan::call('migrate', ['--seed' => true]);
	}
```

**Comment by djeux** [comment]
Even if I comment it out, the problem still exists

**Comment by janhenkgerritsen** [comment]
Can you try to move \Helper\Init after the Laravel 4 module in the suite configuration?

**Comment by djeux** [comment]
Now it looks like 
```yaml

class_name: FunctionalTester
modules:
    enabled:
        - \Helper\Functional
        - Asserts
        - REST:
             depends: Laravel4
        - Laravel4:
             cleanup: false
        - \Helper\Init

```

But the problem is still there
