### ISSUE TITLE
File being renamed

### ISSUE THREAD

**Issue by sp0tteh** [Codeception/Codeception#342]
Hey,

I am trying to use TestGuy to upload a file using the PhpBrowser module.

I have added a pdf file into the "tests/_data" directory.
I have tested uploading this file using chrome and it works fine.

This is the line I'm using to attach the file:

```
$i->attachFile('filename', 'test.pdf');
```

and here is the config:

```
class_name: TestGuy
modules:
    enabled: 
        - TestHelper
        - Laravel4
        - PhpBrowser
    config:
        PhpBrowser:
            url: 'http://localhost:8000'
```

I can see the file does upload, however the file name is re-named, and it changes on each upload:

```
a5756b1bfd51dc39f5aea9c3edff985d34e2de47.pdf
a825de2dcb025b4fe9a00c9a23b8680602c74635.pdf
```

If i look at $_FILES i see:

```
Array ( [filename] => Array ( [name] => 1a036eb9730dd0fe0dea4614a81e99f4940ab213.pdf [type] => application/pdf [tmp_name] => /tmp/php1ZBuhy [error] => 0 [size] => 2399732 ) )
```

Any idea on where this might be happening?
