### ISSUE TITLE
Multiple environment configurations not working

### ISSUE THREAD

**Issue by maxfysho** [Codeception/Codeception#3441]
#### What are you trying to achieve?

I am trying to run a collection of tests using two environment configurations as outlined here (http://codeception.com/docs/07-AdvancedUsage)

Running the following command "codecept run acceptance --env dev,mobile -g screenshot -vvv"
#### What do you get instead?

Only the last environment configuration in list was used

> Provide console output if related. Use `-vvv` mode for more details.
#### Environment file dev.yml

``` yml
# `dev` environment config goes here
modules:
    enabled:
         - WebDriver:
             url: https://test.fysho.com
```
#### Environment file mobile.yml

``` yml
# `mobile` environment config goes here
modules:
    enabled:
         - WebDriver:
             window_size: 375x667
```

``` bash
odeception PHP Testing Framework v2.2.3
Powered by PHPUnit 5.4.7 by Sebastian Bergmann and contributors.
[Groups] screenshot 

Acceptance (dev, mobile) Tests (3) --------------------------------------------------------------------
Modules: WebDriver, \Helper\Acceptance
-------------------------------------------------------------------------------------------------------
landing: Navigate to Default Landing Page
Signature: landing:Navigate to Default Landing Page
Test: tests/acceptance/landing.feature:Navigate to Default Landing Page
Scenario --
 As a visitor
 I want to be able to findout a little about fysho
 So that I can decide whether or not to sign up
 Given i am a vistor 
   I am on page "/user/logout"
  [GET] http://local.fysho.com/user/logout
 When i navigate to fysho 
   I am on page "/"
  [GET] http://local.fysho.com/
 Then i see the landing page 
   I see in title "Fysho - Find Fishing Reports"
   I see "FIND FISHING REPORTS IN","h1"
   I see "SIGN UP",".nav"
   I see "LOGIN",".nav"
 And i take a screenshot called "landing" 
   I make screenshot "landing"
  Screenshot saved to /Users/Max/Documents/Development/PHP/Fysho/app/tests/_output/debug/landing.png
 PASSED 

login: Can navigate to login directly
Signature: login:Can navigate to login directly
Test: tests/acceptance/login.feature:Can navigate to login directly
Scenario --
 As a visitor
 I want to login to my account
 So that I can begin to use Fysho
 Given i am a vistor 
   I am on page "/user/logout"
  [GET] http://local.fysho.com/user/logout
 When i navigate to "login" page 
   I am on page "/login"
  [GET] http://local.fysho.com/login
 Then i see the "user-login" form 
   I see element "form#user-login"
 And i see the "name" input 
   I see element "input",{"name":"name"}
 And i see the "pass" input 
   I see element "input",{"name":"pass"}
 And i see the "login" submit button 
   I see "Login",".form-submit"
 And i see the "facebook" login button 
   I see "LOGIN WITH Facebook",".hybridauth-widget-provider"
 And i see the "g mail" login button 
   I see "LOGIN WITH GMail",".hybridauth-widget-provider"
 And i take a screenshot called "login" 
   I make screenshot "login"
  Screenshot saved to /Users/Max/Documents/Development/PHP/Fysho/app/tests/_output/debug/login.png
 PASSED 

signup: Can navigate to signup directly
Signature: signup:Can navigate to signup directly
Test: tests/acceptance/signup.feature:Can navigate to signup directly
Scenario --
 As a visitor
 I want to sign up to Fysho
 So that I can begin to use Fysho
 Given i am a vistor 
   I am on page "/user/logout"
  [GET] http://local.fysho.com/user/logout
 When i navigate to "signup" page 
   I am on page "/signup"
  [GET] http://local.fysho.com/signup
 Then i see the "user-register-form" form 
   I see element "form#user-register-form"
 And i see the "mail" input 
   I see element "input",{"name":"mail"}
 And i see the "firstname" input 
   I see element "input",{"name":"firstname"}
 And i see the "surname" input 
   I see element "input",{"name":"surname"}
 And i see the "dob[day]" dropdown 
   I see element "select",{"name":"dob[day]"}
 And i see the "dob[month]" dropdown 
   I see element "select",{"name":"dob[month]"}
 And i see the "dob[year]" dropdown 
   I see element "select",{"name":"dob[year]"}
 And i see the "gender" input 
   I see element "input",{"name":"gender"}
 And i see the "create an account" submit button 
   I see "Create An Account",".form-submit"
 And i see the "facebook" sign up button 
   I see "SIGN UP WITH Facebook",".hybridauth-widget-provider"
 And i see the "g mail" sign up button 
   I see "SIGN UP WITH GMail",".hybridauth-widget-provider"
 And i take a screenshot called "signup" 
   I make screenshot "signup"
  Screenshot saved to /Users/Max/Documents/Development/PHP/Fysho/app/tests/_output/debug/signup.png
 PASSED 

-------------------------------------------------------------------------------------------------------


Time: 18.57 seconds, Memory: 18.50MB

OK (3 tests, 21 assertions)
```

> Provide test source code if related
### Details
- Codeception version: 2.2.3
- PHP Version: 5.5.26 
- Operating System: OS X El Capitan Version 10.11.5
- Installation type: Phar
- List of installed packages (consolidation/annotated-command       1.0.1  Initialize Symfony Console commands from annotated comm...
  consolidation/output-formatters       1.0.0  Format text by applying transformations provided by plu...
  dnoegel/php-xdg-base-dir              0.1    implementation of xdg base directory specification for php
  drush/drush                           8.1.3  Drush is a command line shell and scripting interface f...
  jakub-onderka/php-console-color       0.1  
  jakub-onderka/php-console-highlighter v0.3.2 
  nikic/php-parser                      v2.1.0 A PHP parser written in PHP
  pear/console_table                    v1.3.0 Library that makes it easy to build console style tables.
  phpdocumentor/reflection-docblock     2.0.4  
  psr/log                               1.0.0  Common interface for logging libraries
  psy/psysh                             v0.7.2 An interactive shell for modern PHP.
  symfony/console                       v2.8.8 Symfony Console Component
  symfony/finder                        v2.8.8 Symfony Finder Component
  symfony/polyfill-mbstring             v1.2.0 Symfony polyfill for the Mbstring extension
  symfony/var-dumper                    v2.8.8 Symfony mechanism for exploring and dumping PHP variables
  symfony/yaml                          v2.8.8 Symfony Yaml Component)
- Suite configuration:

``` yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://local.fysho.com
            browser: phantomjs 
        - \Helper\Acceptance
gherkin:
    contexts:
        default: 
            - AcceptanceTester
            - Step\Acceptance\Landing
            - Step\Acceptance\Login
```

**Comment by Naktibalda** [comment]
Your command was `codecept run acceptance --env dev,mobile -g screenshot -vvv`
Use `codecept run acceptance --env dev --env mobile -g screenshot -vvv` instead.

Using comma separated list of environments merges configuration of 2 environments.

> To run tests in all 3 browsers, just list all the environments:
> 
> $ php codecept run acceptance --env phantom --env chrome --env firefox
> 
> and tests will be executed 3 times, each time in a different browser.
> 
> It’s also possible to merge multiple environments into one configuration by using comma as a separator:
> 
> $ php codecept run acceptance --env dev,phantom --env dev,chrome --env dev,firefox
> 
> Configuration is merged in the given order. This way you can easily create multiple combinations of your environment configurations.

**Comment by maxfysho** [comment]
Naktibalda, I may not have been clear in my previous post. 

I am trying to merge the two previous environment configurations together to run a single test run.

I am expecting to run the test suite on my dev environment at a mobile resolution. 

This is why I have used a comma. 

That being said the configurations are not being merged as outlined in the documentation, codecept is only using the last environment configuration in the comma separated string.

**Comment by pmandeep** [comment]
@maxfysho 

I was facing the similar issue when merging the environments. I was able to solve it as follows

This is how my codeception.yml looks like:
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs

settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    strict_xml: true
```

my acceptance.yml
```
class_name: AcceptanceTester

modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver:
            url: ''
            browser: ''
```

my env in the envs folder 
chrome.yml
```
modules:
    config:
        WebDriver:
            browser: chrome
            port: 4444
```

dev env:
```
modules:
    config:
        WebDriver:
            url: 'https://dev.site.....'
```

now when I use the merge command it works as expected.

**Comment by jumale** [comment]
I have the same issue here (Codeception v2.2.6).
Two comma-separated environments are merged correctly only if the environment-specific parameters are not defined in the default configuration.
### This does not work:
```yaml
modules:
    enabled: [WebDriver]
    config:
        WebDriver:
            url: http://localhost:8080
            browser: firefox

env:
    chrome:
        modules:
            config:
                WebDriver:
                    browser: chrome
    remote:
        modules:
            config:
                WebDriver:
                    url: http://remote.server.com
```
This will be run remotely, but in firefox
```bash
$ vendor/bin/codecept run acceptance --env chrome,remote
```
This will be run in chrome, but locally
```bash
$ vendor/bin/codecept run acceptance --env remote,chrome
```

### But this will work correctly:
```yaml
modules:
    enabled: [WebDriver]
    config:
        WebDriver: {} # no default url and browser

env:
    chrome:
        modules:
            config:
                WebDriver:
                    browser: chrome
    remote:
        modules:
            config:
                WebDriver:
                    url: http://remote.server.com
```
But in this case our default configuration is empty, which make impossible to run tests without a specified environment

**Comment by jumale** [comment]
It seems I have found the issue.
For example, we have default configuration:
```yaml
WebDriver:
    url: http://localhost:8080
    browser: firefox
```
and env `chrome` is:
```yaml
WebDriver:
    browser: chrome
```
and env `remote` is:
```yaml
WebDriver:
    url: http://remote.server.com
```

### Step 1
[At this moment](https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Configuration.php#L384) all environment configs are merged with the default configuration.
So that after this step our environment configurations look like:
```yaml
# chrome
WebDriver:
    browser: chrome
    url: http://localhost:8080 # merged from default config
```
```yaml
# remote
WebDriver:
    browser: firefox # merged from default config
    url: http://remote.server.com
```

### Step 2
And now [at this moment](https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Codecept.php#L189) we merge all current environment configs. And of course if we have current environment like `chrome,remote` then the `browser: firefox` from the remote config will override `browser: chrome` from the chrome config
