### ISSUE TITLE
Cannot use decorated EntityManager extended from Doctrine2 EntityManagerDecorator

### ISSUE THREAD

**Issue by akbwm** [Codeception/Codeception#3459]
#### What are you trying to achieve?
Using custom EntityManager implementation via decorated Symfony2 service definition
services.yml
```yml
 my.em.decorator:
        public: false
        class: AppBundle\MyEntityManagerDecorator
        decorates: doctrine.orm.entity_manager
        arguments: 
            - "@my.em.decorator.inner"
```

MyEntityManagerDecorator.php
```php
class MyEntityManagerDecorator extends Doctrine\ORM\Decorator\EntityManagerDecorator
{
...
}
```

#### What do you get instead?
Exception, because of Doctrine2 module checking against EntityManager instead of EntityManagerInterface
Doctrine2.php:151
```php
        if (!($this->em instanceof \Doctrine\ORM\EntityManager)) {
            throw new ModuleConfigException(
                __CLASS__,
                "Connection object is not an instance of \\Doctrine\\ORM\\EntityManager.\n"
                . "Use `connection_callback` or dependent framework modules to specify one"
            );
        }
```

> Provide console output if related. Use `-vvv` mode for more details.

```bash
  [Codeception\Exception\ModuleConfigException]                            
  Doctrine2 module is not configured!                                      
                                                                           
  Connection object is not an instance of \Doctrine\ORM\EntityManager.     
  Use `connection_callback` or dependent framework modules to specify one
```
> Provide test source code if related

Any test suite using Doctrine2 module

### Details

* Codeception version: 2.1.7
* PHP Version: 5.5.9
* Operating System: ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
modules:
    config:
        Doctrine2:
            depends: Symfony2
        Symfony2:
            app_path: 'app'
            environment: 'test'
            debug: false
```
