### ISSUE TITLE
Disable auto-logout when using "api" as a "guard" option Laravel 5

### ISSUE THREAD

**Issue by mohamed-atef** [Codeception/Codeception#3483]
#### What are you trying to achieve?
I'm using Laravel native "api" authentication module instead of JWT package of Dingo so I have changed the configuration in auth.php ("guard" => "web") to ("guard"=>"api") after that every time I run the test I get an exception.

#### What do you get instead?
I got Excetion 
`[ErrorException]
  call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\TokenGuard' does not have a method 'logout'` .
> Provide console output if related. Use `-vvv` mode for more details.

```bash
[ErrorException]
  call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Auth\TokenGuard' does not have a method 'logout'` 
```

The fast solution was to comment the lines
`//        if (isset($this->app['auth'])) {
//            $this->app['auth']->logout();
//        }`
in the _after method inside the "vendor/codeception/codeception/src/Codeception/Module/Laravel5.php".

> Provide test source code if related

```php
/*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],
```
### Details

* Codeception version: 2.2.4
* PHP Version:7.0.8
* Operating System: Linux Mint 18
* Installation type:  Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - Asserts
        - Filesystem
        - REST:
            depends: Laravel5
            url: http://api-test.dev/api
        - Laravel5:
            environment_file: .env.test
```
