### ISSUE TITLE
Access to helper properties in test code

### ISSUE THREAD

**Issue by stdex** [Codeception/Codeception#3486]
Codeception version 2.2.4

Try to connect helper (default path in /_support/Helper/) for suite.

```yml
class_name: ApiTester
modules:
    enabled: 
        - Helper\Api
```
```php
<?php
namespace Helper;
Api extends \Codeception\Module
{
	public $test;
	public function _beforeSuite($settings = [])
	{
		$this->test = "123";
	}
}
```

Call in cest function, try to get this field:
```php
var_dump($I->test);
```

Return me error:
[PHPUnit_Framework_Exception] Undefined property: ApiTester::$test
