### ISSUE TITLE
Disable persistentServices on Symfony Kernel reboot

### ISSUE THREAD

**Issue by EnricoGsell** [Codeception/Codeception#3497]
#### What are you trying to achieve?
I have a simple REST api and trying to test default CRUD behaviour.
I am using Symfony 2.8 with the [DoctrineExtensions::SoftDeleteable](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/softdeleteable.md) being enabled on the affected Entity. So when I am executing the request for DELETE on the Entity it gets soft deleted, on the next request I disable the doctrine filter for SoftDeleteable on the EntityManager, so I can retrieve the soft deleted entity again and delete it again (which results in a hard delete).
The next test file is doing the same on a different end point/entity.

#### What do you get instead?
The second test file fails because the doctrine service does not get recreated and therefore the filter on the EntityManager is still disabled.
This happens due to the doctrine and entity manager services are treat as persistent services inside the Codeception\Module\Symfony and Codeception\Lib\Connector\Symfony classes.
Removing the part where the stored **persistentServices** replace the ones from the rebooted container inside **Codeception\Lib\Connector\Symfony::rebootKernel** would solve the issue for me.

```php
class Symfony extends \Symfony\Component\HttpKernel\Client
{
....
    /**
     * Reboot kernel
     *
     * Services from the list of persistent services
     * are updated from service container before kernel shutdown
     * and injected into newly initialized container after kernel boot.
     */
    public function rebootKernel()
    {

        if ($this->container) {
            foreach ($this->persistentServices as $serviceName => $service) {
                if ($this->container->has($serviceName)) {
                    $this->persistentServices[$serviceName] = $this->container->get($serviceName);
                }
            }
        }

        $this->kernel->shutdown();
        $this->kernel->boot();
        $this->container = $this->kernel->getContainer();

        if ($this->container->has('profiler')) {
            $this->container->get('profiler')->enable();
        }

        #NOTE: Do not replace rebooted services
//        foreach ($this->persistentServices as $serviceName => $service) {
//            $this->container->set($serviceName, $service);
//        }
    }
```

So why are there persistent services in the first place? Shouldn't the request being execute as isolated as possible? Could a new configuration option be implemented that we are able to disabled the usage of persistentServices?

### Details

* Codeception version: 2.2.4 (happens since >=2.1.8)
* Symfony version: 2.8.11
* PHP Version: 5.5.9
* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

global codeception.yml
```yml
paths:
    tests: tests
    log: tests/_log
    data: tests/_data
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: -1
    log: true
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=wmtest_symfony'
            user: 'root'
            password: 'xxxxx'
            dump: tests/_data/dump.sql
        PhpBrowser:
            url: 'http://127.0.0.1:80/app_test.php'
        REST:
            depends: Symfony
        Symfony:
            app_path: 'app'
            environment: 'test'
            debug: false
            rebootable_client: true
            debug: true
            part: SERVICES
        Doctrine2:
            depends: Symfony
groups:
    # add 2 tests to db group
    testGroup: [tests/api/auth/rolesCept.php, tests/api/auth/customersCept.php]
coverage:
    enabled: true
    include:
        - src/*.php
    exclude:

#api.suite.yml
class_name: ApiGuy
modules:
    enabled: 
        - Db
        - Doctrine2
        - ApiHelper
        - REST
        - Asserts

```
api.suite.yml
```yml
class_name: ApiGuy
modules:
    enabled: 
        - Db
        - Doctrine2
        - ApiHelper
        - REST
        - Asserts
```
