### ISSUE TITLE
AngularJS module not running Recorder extension 

### ISSUE THREAD

**Issue by riyunoa** [Codeception/Codeception#3508]
I'm trying to use the Recorder extension for acceptance tests with the AngularJS module but it's not running. This is odd because when I run with just the WebDriver module, Recorder does work. 

acceptance.suite.yml:

```
class_name: AcceptanceTester
modules:
enabled:
    - AngularJS
    - Db
config:
    AngularJS:
        url: 'http://back.juniper.dev/'
        host: 'localhost'
        port: '4444'
        browser: 'phantomjs'
        window_size: '1024x768'
coverage:
    enabled: false
    remote: false
```

codeception.yml:

```
...
extensions:
    enabled: [Codeception\Extension\Recorder]
    config:
        Codeception\Extension\Recorder:
            delete_successful: false
...
```

**Comment by DavertMik** [comment]
Oh, sorry, looks like you didn't specify the proper module in this case. I should have notices this earlier :(

**Comment by riyunoa** [comment]
@DavertMik what should the module be? Thanks!

**Comment by fnagel** [comment]
Same question here: how to configure in order to make it work with AngularJS and the Recorder?

**Comment by fnagel** [comment]
Works with this config:

```
actor: AcceptanceTester
modules:
    enabled:
        - AngularJS:
            url: 'https://myapp.vm/app_test.php'
            browser: phantomjs

extensions:
    enabled:
        - Codeception\Extension\Recorder:
            module: AngularJS
```
