### ISSUE TITLE
Passing session is not working for Codeception 2.2.4

### ISSUE THREAD

**Issue by jltoo** [Codeception/Codeception#3510]
### Details

After updating codeception to 2.2.4, My logged in session was not passed anymore after redirecting to a different page.

Issue does not occur to: Codeception version 2.2.3
- Codeception version:  2.2.4
- PHP Version: 5.6
- Operating System: Windows 7
- Suite configuration:

``` yml

class_name: AcceptanceTester
modules:
    enabled:
        - Asserts:
        - WebDriver:
            url: http://qa.test.com
            browser: chrome
            window_size: maximize
            request_timeout: 120
            connection_timeout: 120
            delay: 1
            wait: 1
            restart: false
            clear_cookies: false
        - \Helper\Acceptance
```
