### ISSUE TITLE
CodeCoverage Filter fails to work with file paths

### ISSUE THREAD

**Issue by sbacic** [Codeception/Codeception#3519]
Here is the coverage section of my codeception.yml.

```
coverage:
    enabled: true
    whitelist:
      include:
          - src/*.php
      exclude:
          - src/Config.php
          - src/autoloader.php
          - src/Cli.php
          - src/cli/*
          - src/backup/*
```

- Codeception will show Config.php, autoloader.php and Cli.php in the coverage reports, even though it shouldn't.  
- The wildcard dirs src/cli/* and src/backup/* won't be shown, which is expected. 
- If I add asterixes, such as `src/Config.*` the filter for that file works properly.

I have been unable to reproduce the bug in a clean environment, so I suspect it has something to do with the tests and/or code in the project I'm working on. Here is a pull request that fixes the issue: https://github.com/Codeception/Codeception/pull/3518

My guess is that because file paths are relative, something confuses Codeception about where these files are. This is not a problem for asterixed paths because they are handled differently than regular ones.

I will probably upload the project I'm working on in the next few days, so that you can reproduce the bug. 

EDIT: Bug seems to be caused by chdir in setUpBeforeClass. See pull request for details and this repo: https://github.com/sbacic/cctest for a reproduction of the bug.
