### ISSUE TITLE
`-g` and `@dataProvider` Incompatibility

### ISSUE THREAD

**Issue by davidcochrum** [Codeception/Codeception#3535]
When a `-g` group argument is used, the `@dataProvider` annotation seems to be ignored and the entire test skipped with no explanation in versions 2.2.3+.

v2.2.3 and 2.2.4:
```bash
bin/codecept run unit -vvv -g Bar

Codeception PHP Testing Framework v2.2.3
Powered by PHPUnit 5.4.8 by Sebastian Bergmann and contributors.
[Groups] Bar 

  Rebuilding UnitTester...

Unit Tests (0) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Asserts, Mockery, \Helper\Unit
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 110 ms, Memory: 10.00MB

No tests executed!
```

v2.2.2 and below (as expected):
```bash
bin/codecept run unit -vvv -g Bar

Codeception PHP Testing Framework v2.2.2
Powered by PHPUnit 5.4.8 by Sebastian Bergmann and contributors.
[Groups] Bar 

  Rebuilding UnitTester...

Unit Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Asserts, Mockery, \Helper\Unit
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ FooTest: Me | #0 (0.0s)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 154 ms, Memory: 10.00MB

OK (1 test, 1 assertion)
```

Source:
```php
<?php
/**
 * @group Bar
 */
class FooTest extends \Codeception\Test\Unit
{
    /**
     * @dataProvider meData
     */
    public function testMe($data)
    {
        $this->assertTrue($data);
    }

    public function meData()
    {
        return [[true]];
    }
}
```

### Details

* Codeception version: 2.2.3+
* PHP Version: 7.0.11
* Operating System: macOS Sierra
* Installation type: Composer
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    whitelist:
        include:
            - app/classes/*
            - lib/Sonnys/*
```
