### ISSUE TITLE
Laravel 5 - Add seeding capabilities

### ISSUE THREAD

**Issue by edno** [Codeception/Codeception#3552]
It would be nice to have seeding capabilities for the **Laravel5** module.

Currently, we can decide if we want to run the migration but there's no option for seeding.

Suggestion of implementation at module configuration level:
```yaml
modules:
    enabled:
        - Laravel5:
            seeders:
                  - UsersTableSeeder
                  - PostsTableSeeder
                  - CommentsTableSeeder
```
Ideally testing seeders would be to store under the `tests` folder instead of the `migrate` folder.
