### ISSUE TITLE
Cannot setup remote code coverage right

### ISSUE THREAD

**Issue by Horki** [Codeception/Codeception#3564]
#### What are you trying to achieve?

I'm trying to achieve a code coverage for remote API
example is -> [here](https://github.com/Horki/remotecoverage)
#### What do you get instead?

I got tons of error in php.ini

> Provide console output if related. Use `-vvv` mode for more details.

``` bash
TestEndpointsCest: Test endpoint returns 200
Signature: TestEndpointsCest:testGetTestEndpoint
Test: tests/api/TestEndpointsCest.php:testGetTestEndpoint
Scenario --
 I send get "/test"
  [Request] GET http://localhost:8888/test
  [Request Headers] []
  [Page] http://localhost:8888/test
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"Host":["localhost:8888"],"Connection":["close"],"X-Powered-By":["PHP/5.6.10"],"X-Codeception-CodeCoverage-Error":["Could not write error to log file (C3_CODECOVERAGE_MEDIATE_STORAGE/error.txt), original message: Data path is not defined Codeception config by key "paths: data""],"Set-Cookie":["CODECEPTION_CODECOVERAGE_ERROR=Could+not+write+error+to+log+file+%28C3_CODECOVERAGE_MEDIATE_STORAGE%2Ferror.txt%29%2C+original+message%3A+Data+path+is+not+defined+Codeception+config+by+key+%22paths%3A+data%22"],"Content-Type":["application/json"]}
  [Response] {"status":200,"data":"this is some test","error":false}
 I see response code is 200
 I see response is json
 I see response contains json {"status":200,"data":"this is some test","er...}
 PASSED
```

> Provide test source code if related

``` php
// paste test
```
### Details
- Codeception version: v2.2.5
- PHP Version: 5.6
- Operating System: Os X 10.12
- Installation type: Composer
- List of installed packages (`composer show`)
- API (remote) configuration (codeception.yml):

``` yml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  support: tests/_support
  envs: tests/_envs
settings:
  bootstrap: _bootstrap.php
  colors: true
  memory_limit: 1024M
extensions:
  enabled:
      - Codeception\Extension\RunFailed
coverage:
enabled: true
remote: true
include:
  - src/*
```
- Codeception repo configuration (codeception.yml):

``` yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    # url of file which includes c3 router.
    # As in http://codeception.com/docs/11-Codecoverage#Local-Server
    c3_url: 'http://localhost:8888'
```
- Codeception api suite configuration (api.suite.yml):

``` yml
class_name: ApiTester
modules:
    enabled:
        - REST:
            url: http://localhost:8888
            depends: PhpBrowser
```
