### ISSUE TITLE
Problem with functional, acceptance and xdebug

### ISSUE THREAD

**Issue by matiux** [Codeception/Codeception#3599]
Hi,
I would like to debug of an acceptance test with xdebug and phpstorm but unfortunately it doesn't stop on breakpoint that I have put on controller method

Xdebug and Phpstorm are properly configured, because unit test works and it stop on breakpoint. Function and acceptance doesn't work

```bash
Acceptance Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Acceptance, PhpBrowser, REST
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GetJwtTokenCept: Get JWT token by supplying credentials
Signature: GetJwtTokenCept
Test: tests/acceptance/GetJwtTokenCept.php
Scenario --
 As a client
 So that I have token with which access to APIs
 I send post "action",{"user":"pinco","password":"pallo"}
  [Request] POST http://foo.domain.com.local/api/action {"user":"pinco","password":"pallo"}
  [Request Headers] []
  [Page] http://foo.domain.com.local/api/action
  [Response] 200
  [Request Cookies] {"XDEBUG_SESSION_START":"PHPSTORM","XDEBUG_SESSION":"PHPSTORM"}
  [Response Headers] {"Date":["Tue, 11 Oct 2016 13:06:00 GMT"],"Server":["Apache/2.4.23 (Debian)"],"Cache-Control":["no-cache"],"Content-Length":["13"],"Connection":["close"],"Content-Type":["application/json"]}
  [Response] {"token":"a"}
 I see response code is 200
 I see cookie "XDEBUG_SESSION_START"
  [Cookie Jar] ["XDEBUG_SESSION_START=PHPSTORM; domain=foo.domain.com.local; path=/","XDEBUG_SESSION=PHPSTORM; domain=foo.domain.com.local; path=/"]
 I see cookie "XDEBUG_SESSION"
  [Cookie Jar] ["XDEBUG_SESSION_START=PHPSTORM; domain=foo.domain.com.local; path=/","XDEBUG_SESSION=PHPSTORM; domain=foo.domain.com.local; path=/"]
 I see http header "Content-Type","application/json"
 I see response is json 
 I see response json matches json path "$.token"
 I see response matches json type {"token":"string:regex(\/[\\w\\.]+\/)"}
 PASSED
```

### Details

* Codeception version 2.2.5
* PHP Version: PHP 7.0.11-1
* Operating System: Debian Stretch
* Installation type: Composer
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - PhpBrowser:
            url: http://foo.domain.com.local
            cookies:
                cookie-1:
                    Name: XDEBUG_SESSION_START
                    Value: PHPSTORM
                    HttpOnly: false
                cookie-2:
                    Name: XDEBUG_SESSION
                    Value: PHPSTORM
                    HttpOnly: false
        - REST:
            depends: PhpBrowser
            url: http://foo.domain.com.local
```

**Comment by Naktibalda** [comment]
Have you configured xdebug in configuration of your webserver?

**Comment by matiux** [comment]
Hi @Naktibalda 
uhm... can you supply me an example?

This i my functional.suite.yml

```
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - \Helper\Functional
        - PhpBrowser:
            url: http://foo.domain.com
```
