### ISSUE TITLE
WebDriver http_proxy configuration does nothing

### ISSUE THREAD

**Issue by webward09** [Codeception/Codeception#3601]
#### What are you trying to achieve?
Use a proxy with Webdriver. I have tried using http_proxy on its own, and with http_proxy_port. Neither has any effect.
#### What do you get instead?
The proxy is not used at all. I can tell this as I am monitoring the proxy (squid) logs.

> Provide test source code if related

```php
$I = new AcceptanceTester($scenario);
$I->wantTo("Test a proxy");
$I->amOnUrl('http://www.budweiser.com/');

```
### Details

* Codeception version: 2.2.3
* PHP Version: 5.5.7
* Operating System: Windows
* Installation type: Phar
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver:
            url: 'http://10.1.2.90/'
            browser: firefox
            http_proxy: 10.1.2.90:8881

```
