### ISSUE TITLE
Db: could not find mysql driver while creating PDO connection

### ISSUE THREAD

**Issue by mc388** [Codeception/Codeception#3605]
#### What are you trying to achieve?
I want to connect to the database.

The whole environment is setup with docker. For codeception I am using [this docker container](https://hub.docker.com/r/codeception/codeception/)

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Codeception PHP Testing Framework v2.2.5
Powered by PHPUnit 5.6.1 by Sebastian Bergmann and contributors.


  [Codeception\Exception\ModuleException]
  Db: could not find mysql driver while creating PDO connection


Exception trace:
 () at /repo/src/Codeception/Module/Db.php:219
 Codeception\Module\Db->connect() at /repo/src/Codeception/Module/Db.php:174
 Codeception\Module\Db->_initialize() at /repo/src/Codeception/SuiteManager.php:81
 Codeception\SuiteManager->initialize() at /repo/src/Codeception/Codecept.php:207
 Codeception\Codecept->runSuite() at /repo/src/Codeception/Codecept.php:178
 Codeception\Codecept->run() at /repo/src/Codeception/Command/Run.php:329
 Codeception\Command\Run->runSuites() at /repo/src/Codeception/Command/Run.php:256
 Codeception\Command\Run->execute() at /repo/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /repo/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at /repo/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at /repo/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at /repo/src/Codeception/Application.php:103
 Codeception\Application->run() at /repo/codecept:33
```
> Provide test source code if related

```php
<?php


class AuthCest
{
    /** @var string */
    private $email;

    public function _before(AcceptanceTester $I)
    {
        $this->email = 'john.doe@example.com';
    }

    public function _after(AcceptanceTester $I)
    {
    }

    public function checkRegister(AcceptanceTester $I)
    {
        $I->am('user');
        $I->wantTo('register to website');
        $I->amOnPage('/en/login');
        $I->fillField('#register-name','John Doe');
        $I->fillField('#register-email',$this->email);
        $I->click('Register Now');
        $userId = $I->grabFromDatabase('users', 'id', array('email' => $this->email));
    }
}
```
### Details

* Codeception version: 2.2.5
* PHP Version: 7.0
* Operating System: Docker container
* Suite configuration:

`codeception.yml`

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'mysql:host=mysql;dbname=eventerza'
            user: 'root'
            password: 'pw'
```

`tests/acceptance.suite.yml`

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - Db
        - PhpBrowser:
            url: http://web/
        - \Helper\Acceptance
```
