### ISSUE TITLE
[PHPUnit_Framework_Exception] implode(): Invalid arguments passed

### ISSUE THREAD

**Issue by Prazmok** [Codeception/Codeception#3608]
I wanted to test homepage using functional tester `amOnRoute` method which is part of Symfony module. As a result I get an error:

```bash
1) DefaultControllerCest: Check if default page response is correct
 Test  tests/functional/AppBundle/Controller/DefaultControllerCest.php:homepageTest
                                                                     
  [PHPUnit_Framework_Exception] implode(): Invalid arguments passed  
                                                                     

Scenario Steps:

 1. $I->amOnRoute("app_homepage",{"_locale":"en"}) at tests/functional/AppBundle/Controller/DefaultControllerCest.php:20

/path/to/project/vendor/codeception/codeception/src/Codeception/Module/Symfony.php:480
/path/to/project/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:191
/path/to/project/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:238
/path/to/project/vendor/codeception/codeception/src/Codeception/Lib/InnerBrowser.php:330
/path/to/project/vendor/codeception/codeception/src/Codeception/Module/Symfony.php:324
/path/to/project/vendor/codeception/codeception/src/Codeception/Step.php:259
/path/to/project/vendor/codeception/codeception/src/Codeception/Scenario.php:69
/path/to/project/tests/_support/_generated/FunctionalTesterActions.php:76
/path/to/project/tests/functional/AppBundle/Controller/DefaultControllerCest.php:20
/path/to/project/vendor/codeception/codeception/src/Codeception/Lib/Di.php:121
/path/to/project/vendor/codeception/codeception/src/Codeception/Test/Cest.php:135
/path/to/project/vendor/codeception/codeception/src/Codeception/Test/Cest.php:147
/path/to/project/vendor/codeception/codeception/src/Codeception/Test/Cest.php:81
/path/to/project/vendor/codeception/codeception/src/Codeception/Test/Test.php:82
/path/to/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:753
/path/to/project/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:98
/path/to/project/vendor/codeception/codeception/src/Codeception/SuiteManager.php:162
/path/to/project/vendor/codeception/codeception/src/Codeception/Codecept.php:209
/path/to/project/vendor/codeception/codeception/src/Codeception/Codecept.php:178
/path/to/project/vendor/codeception/codeception/src/Codeception/Command/Run.php:329
/path/to/project/vendor/codeception/codeception/src/Codeception/Command/Run.php:256
/path/to/project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:257
/path/to/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:829
/path/to/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
/path/to/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
/path/to/project/vendor/codeception/codeception/src/Codeception/Application.php:103
/path/to/project/vendor/codeception/codeception/codecept:33
```

```php
use \FunctionalTester;

class DefaultControllerCest
{
    public function homepageTest(FunctionalTester $I)
    {
        $I->wantTo('Check if default page response is correct');
        $I->amOnRoute('app_homepage', ['_locale' => 'en']);
    }
}
```

I digged a little bit deeper and found probable cause of problem in `$profile->getCollection('security')->getRoles()`. My Symfony security.yml configuration looks like

```yml
security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

```

### Details

* Codeception version: 2.2.5
* PHP Version: 7.0.8
* Operating System: OS X 10.11.6 (15G1004)
* Installation type: Composer
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        - Symfony2:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'
        - Doctrine2:
            depends: Symfony2
        - \Helper\Functional
```
