### ISSUE TITLE
Yii2 module don't call _fixtures() method of Cest class

### ISSUE THREAD

**Issue by sashsvamir** [Codeception/Codeception#3612]
I'm tried to add `_fixture()` method to my Cest classes on any suites, but Yii2 module on 169 line: `method_exists($test, self::TEST_FIXTURES_METHOD)` always return false value and loading fixture is passing;
I'm try to debug this moment, on 169 line, $test contain "Codeception\Test\Case" class and have property $testClassInstance with my current Cest class. But when i tried check to any exist method by calling `method_exist($test, 'exist_method_name')` of this Cest class, that always return false value, only methods of "Codeception\Test\Case" can be finded (ex. calling method_exist($test, "test") return true).

* Codeception version: 2.2.5
* PHP Version: 5.5.37
* Operating System: os x
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:
codeception.yml
```yml
namespace: productEav\tests\backend
actor: Tester
paths:
    tests: .
    log: ./_output
    data: ./_data
    support: ./_support
settings:
    bootstrap: ../../../../../tests/codeception/backend/_bootstrap.php
    colors: true
    memory_limit: 1024M
    log: true
extensions:
    enabled:
        - Codeception\Extension\RunFailed
config:
    test_entry_url: http://shop-back/index-test.php
```
unit.suite.yml
```yml
class_name: UnitTester
modules:
    enabled:
        - Asserts
        - productEav\tests\backend\Helper\Unit
        - Yii2:
            configFile: '../../../../tests/codeception/config/backend/unit.php'
```

**Comment by Oxyaction** [comment]
Issuing the same problem while running Cest file. In `Yii2::_before()#169` `$test` is `Codeception\Test\Cest` instance and no the instance of my Cest test class.

codeception version: __2.2.5__

**Comment by primipilus** [comment]
Imho their is an error in ```codeception/codeception/src/Codeception/Module/Yii2.php``` on line 170
```$this->haveFixtures(call_user_func($test, self::TEST_FIXTURES_METHOD));```
must be ```$this->haveFixtures(call_user_func([$test, self::TEST_FIXTURES_METHOD]));```

**Comment by michaelarnauts** [comment]
The change of @primipilus fixes it.

**Comment by DavertMik** [comment]
Thanks @primipilus

**Comment by sashsvamir** [comment]
Excuse me, argument `$test` in `_before` method of **Yii2 module** still contain `Codeception\Test\Cest` class when `Cest` test was used and `method_exists($test, self::TEST_FIXTURES_METHOD)` return `false` although my Cest class have `_fixtures` method.
May be i'm wrong, but my composer.json have _"codeception/codeception": "2.2.x-dev"_ branch and i think i have last update (_5fbe312_) of codeception.
Also fix from **@primipilus** resolve another problem but current issue still no pass:
Yii2 module **don't call _fixtures() method of Cest** class.

**Comment by primipilus** [comment]
I thing it's not a bug.

here example that works for me
```php
class OneCest
{
    public function _before(AcceptanceTester $I)
    {
        $I->haveFixtures($this->_fixtures());
    }

    public function _after(AcceptanceTester $I)
    {
    }

    // tests
    public function tryToTest(AcceptanceTester $I)
    {
    }

    public function _fixtures()
    {
        return [
            'users'     => [
                'class'    => UserFixture::class,
                'dataFile' => '@tests/codeception/welcome/tests/unit/fixtures/data/models/users.php',
            ],
            'customers' => [
                'class'    => CustomerFixture::class,
                'dataFile' => '@tests/codeception/welcome/tests/unit/fixtures/data/models/customers.php',
            ],
        ];
    }
}
```
and config acceptance.suite.yml
```
class_name: AcceptanceTester
modules:
    enabled:
        - \tests\codeception\welcome\tests\Helper\Acceptance
        - Yii2:
            configFile: 'tests/config/unit.php'
```
