### ISSUE TITLE
Fails to inject Step dependency into Cest

### ISSUE THREAD

**Issue by chrisrichard** [Codeception/Codeception#3618]
I created step Foo using codecept generate:stepobject acceptance Foo. This worked OK before switching to PHP7.

```bash
Test  tests/acceptance/myTestsCest.php:test1
                                                                                                                                     
[InjectionException] Failed to inject dependencies in instance of 'MyTestsCest'. Class Step\Acceptance\Foo does not exist  
```                                                                                                                               

```php
<?php
use Step\Acceptance\Foo;

class MyTestsCest {

    function test1(Foo $I) {
```

### Details

* Codeception version: 2.2.5
* PHP Version: 7
* Operating System: Ubuntu
* Installation type: Composer
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - \Helper\Acceptance
        - Asserts
        - Db
        - Doctrine2
    config:
        WebDriver:
            url: 'http://test.myco.dev'
            browser: chrome
            wait: 0
            window_size: 1440x1080
        Db:
            dsn: 'pgsql:host=localhost;dbname=myco'
            user: 'myuser'
            password: '...'
            dump: tests/_data/dump.sql
            populate: true
            cleanup: false
        Doctrine2:
            connection_callback: ['MyCo\Base', 'getManager']
            cleanup: false
```
