### ISSUE TITLE
[REST] Preconfigured Content-Type header changes to application/x-www-form-urlencoded when request data is provided

### ISSUE THREAD

**Issue by evpav** [Codeception/Codeception#3619]
Suite configuration:

``` yml
class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - REST:
            url: http://localhost/
            depends: PhpBrowser
            part: Json
        - PhpBrowser:
            url: http://localhost/
            headers:
                Accept: application/json
                Content-Type: application/json

```

test:

``` php
$I->sendPOST('user/login');
// on server: $_SERVER["HTTP_CONTENT_TYPE"] === 'application/json'
$I->sendPOST('user/login', ['username' => 'test', 'password' => 'test']);
// on server: $_SERVER["HTTP_CONTENT_TYPE"] === 'application/x-www-form-urlencoded'
```

Codeception version 2.2.5

Also these preset headers are not showing up in the verbose output:

```
 I send post "user/login"
  [Request] POST http://localhost/user/login []
  [Request Headers] []

 I send post "user/login",{"username":"test","password":"test"}
  [Request] POST http://localhost/user/login {"username":"test","password":"test"}
  [Request Headers] []
```
