### ISSUE TITLE
Upgrade from 2.0.16 to 2.2.5? 

### ISSUE THREAD

**Issue by TroyAlchemy** [Codeception/Codeception#3632]
Hello,

We have a very large acceptance suite that was built and runs daily using Codeception 2.0.16.  We have a number of our own modules for inserting test data via an old API.

We would like to upgrade to Codeception 2.2.5.  However, after installing Codeception 2.2.5, we cannot run our test suites at all.

The error we receive is ... (additional details at bottom)

  [Codeception\Exception\ConfigurationException]
  Module WebHelper could not be found and loaded

So clearly, the new version has loading changes that affect our suite.

My question is this:  Are there any migration instructions that will help us with this upgrade?  We have searched the codeception site and don't see any.  Could you please steer us in the right direction?

Thank you
Troy

Addtional Details ...

* Codeception version: 2.016 ==> 2.2.5
* PHP Version: 5.6.9
* Operating System: CentOS
* Installation type: Phar 
* Codeception PROJECT configuration:

```yml
namespace: SM
paths:
    tests: tests
    log: tests/_log
    data: tests/_data
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
    strict_xml: true
modules:
    config:
        Db:
            dsn: 'mysql:host=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;dbname=DB_NAME'
            user: 'USER'
            password: '********'
            dump: tests/_data/dump.sql
            populate: false
            cleanup : false
```
* Acceptance Suite configuration:

```yml
class_name: WebGuy
modules:
    enabled:
        - WebDriver
        - WebHelper
        - SistemWSClient
        - TestingSupportWSClient
        - Db
        - TempFileManager
        - Asserts

    config:
        WebDriver:
            # change the client name if you like.  it must exist before you run the test.
            # if you change the client name, change it everywhere below!
            url: 'http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/codeception'
            # it is easier and usually faster to run tests with firefox.
            # if you want to use Chrome, you'll need to install the separate webdriver interface (ChromeDriver).
            # if you want to use IE (SLOW!), you'll need to install the separate webdriver interface (IEDriver).
            browser : firefox
            # if you are running tests and the browser on your own system, then 127.0.0.1 will work.
            # if not, do ipconfig (or ifconfig on linux) to determine the IP address of browser and put it here.
            host: xxxxxxxxxxxxx
            #host: 127.0.0.1
            port: 4444
            wait: 0
            restart: true
            capabilities:
                unexpectedAlertBehaviour: 'accept'

        SistemWSClient:
            url: 'http://xxxxxxxxxxxxxxxxxxx/codeception/plugins/sistem/public/sistem_webservices.php'

        TestingSupportWSClient:
            url: 'http://xxxxxxxxxxxxxxxxxxxx/codeception/rest.php'

        Db:
            # get the values below from your custom_confg.php file
            # or http://trudolph01.alchemy-eng.com/codeception/tools/editcc.php
            dsn: 'mysql:host=xxxxxxxxxxxxxxxx;port=3306;dbname=xxxxxxxxxxxxxx'
            user: 'xxxxxxx'
            password: 'xxxxxxx'
            # don't change the ones below.
            dump: 'some/dump/file'
            populate: false
            cleanup: false
```
