### ISSUE TITLE
[Laravel 5.3] Db modules populate not working

### ISSUE THREAD

**Issue by truongle7793** [Codeception/Codeception#3649]
#### What are you trying to achieve?

I only want the sql dump to only load at the start of the api suite so i set up
          populate: true
          cleanup: false
#### What do you get instead?

But i got told that the table already exist ?

> Provide console output if related. Use `-vvv` mode for more details.

``` bash
[RuntimeException]
  Error Output:
    [Codeception\Exception\ModuleException]
    Db: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'cities'
     already exists
```

a couple a days ago it is running fine, i think it have something to do with the newer codeception version.
but when i turn the setting to:
          populate: true
          cleanup: true
It is running fine but it is re-load the sql dump each test which i do not want.
### Details
- Codeception version: 2.2.6
- PHP Version: 5.6.25
- Operating System: windows wamp localhost
- Installation type: Composer
- List of installed packages (`composer show`)
- Suite configuration:

``` yml
class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - Db
        - REST:
            url: /my-url/
            depends: PhpBrowser
            depends: Laravel5
    config:
        Laravel5:
          cleanup: true
          environment_file: .env.testing
        Db:
          dsn: 'mysql:host=localhost;dbname=testing-db'
          user: 'root'
          password: ''
          dump: 'tests/_data/dump.sql'
          populate: true
          cleanup: false
```
