### ISSUE TITLE
Multiple gherkin step definition for method

### ISSUE THREAD

**Issue by gimler** [Codeception/Codeception#3670]
#### What are you trying to achieve?
Multiple gherkin step definition for method

#### What do you get instead?

> bin/codecept gherkin:steps functional

```bash
Steps from default context:
+-------------------------------------------------------------------------------+---------------------------------------+
| Step                                                                          | Implementation                        |
+-------------------------------------------------------------------------------+---------------------------------------+
| I click :value                                                                | FunctionalTester::press               |
+-------------------------------------------------------------------------------+---------------------------------------+
```

FunctionalTester.php
```php
    /**
     * @Then I click :value
     * @Then I click :value in :context
     */
    public function press($link, $context = null)
    {
        $this->click($link, $context);
    }
```
### Details

* Codeception version: Codeception version 2.2.6
* PHP Version:
PHP 5.6.27 (cli) (built: Oct 15 2016 19:56:04) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

* Operating System:
linux
* Installation type: Phar || Composer
composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        - WebDriver:
             host: phantomjs
             port: 8643
             url: 'http://www.example.com/'
             browser: phantomjs
        - \Helper\Functional
```
