### ISSUE TITLE
Can't use seeResponseMatchesJsonType for sequential arrays

### ISSUE THREAD

**Issue by disharmonized** [Codeception/Codeception#3672]
#### What are you trying to achieve?

I have test data:
```javascript
{
"languages": ["en", "ru", "de"]
}
```
I want to check, that all elements in `languages` are strings, using `seeResponseMatchesJsonType` from `AcceptanceTester`.

#### What do you get instead?

Unfortunately, i got no idea, how to go that. As workaround, i use such code:
```php
<?php
$I = new AcceptanceTester($scenario);
$I->wantTo('Test that languages as strings');
$I->sendGET('/getLanguages');
//workaround
$languages = $I->grabDataFromResponseByJsonPath("$.languages.*");
foreach ($languages as $language) {
    $I->assertInternalType('string', $language);
}

//seeResponseMatchesJsonType variant (i dont know how)
/*
$I->seeResponseMatchesJsonType([
    // ??? 
], '???');
*/
```
Have you any clue, how to achieve that?
### Details

* Codeception version: 2.2
* PHP Version: 5.6
* Operating System: Ubuntu 16.04
* Installation type: Composer
* Suite config:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - REST:
            depends: PhpBrowser
        - PhpBrowser:
            url: 'http://127.0.0.1:8001'
        - Asserts
        - \Helper\Acceptance
```
