### ISSUE TITLE
fatal error when using RunFailed extension

### ISSUE THREAD

**Issue by dwenaus** [Codeception/Codeception#3679]
#### What are you trying to achieve?
at end of running tests I'm trying to run the failed tests

#### What do you get instead?
I get a fatal error that my test classes are already loaded. which makes sense because I already ran them. and now I'm trying to re-run them to test the failed tests again. 

> Provide console output if related. Use `-vvv` mode for more details.

```bash
cd wp-content/plugins/programs-tests && php vendor/bin/wpcept run -g failed --xml $file.xml --env ci
Codeception PHP Testing Framework v2.2.3
Powered by PHPUnit 4.8.27 by Sebastian Bergmann and contributors.
[Groups] failed 

Slow-acceptance (ci) Tests (0) -----------------------------------------------
------------------------------------------------------------------------------
PHP Fatal error:  Cannot declare class payments\BraintreeCest, because the name is already in use in /home/ubuntu/programs/wp-content/plugins/programs-tests/slow-browser/payments/BraintreeCest.php on line 7

Fatal error: Cannot declare class payments\BraintreeCest, because the name is already in use in /home/ubuntu/programs/wp-content/plugins/programs-tests/slow-browser/payments/BraintreeCest.php on line 7

```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.2.3
* PHP Version: 7
* Operating System: ubuntu
* Installation type: Phar || Composer composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: BrowserTester
modules:
    enabled:
        - WebDriver
        - BrowserHelper
        - MailCatcher
        # we could create an ExternalHelper and call BrowserHelper there if needed
    config:
        WebDriver:
            url: 'http://tests.programs.dev'
            curl:
              CURLOPT_TIMEOUT: 60
            browser: phantomjs
            window_size: 1400x900
            wait: 0.1
            connection_timeout: 60
            request_timeout: 60
            capabilities:
                unexpectedAlertBehaviour: 'accept'
                takesScreenshot: false
        MailCatcher:
            url: 'http://127.0.0.1'
            port: '1080'

```
