### ISSUE TITLE
Sqlite database is not cleaned after last test

### ISSUE THREAD

**Issue by richardbrinkman** [Codeception/Codeception#3680]
#### What are you trying to achieve?
Run this test:
```php
class LastTestCleanedTest extends \Codeception\Test\Unit {
        /**
        * @var \UnitTester
        */
        protected $tester;

        public function testHaveInDatabase() {
                $this->tester->haveInDatabase('users', ['username' => 'John', 'email' => null]);
                $this->tester->seeInDatabase('users', ['email' => null]);
        }

        public function testDatabaseIsCleaned() {
                $this->tester->dontSeeInDatabase('users', ['email' => null]);
        }
}
```
After running ```codecept run``` the database does not show John as expected. However if I remove the second test like so:
```php
class LastTestCleanedTest extends \Codeception\Test\Unit {
        /**
        * @var \UnitTester
        */
        protected $tester;

        public function testHaveInDatabase() {
                $this->tester->haveInDatabase('users', ['username' => 'John', 'email' => null]);
                $this->tester->seeInDatabase('users', ['email' => null]);
        }
}
```
John does appear in the (sqlite) database. It should have been cleaned.

### Details

* Codeception version: 2.2.6
* PHP Version: 7.0.8
* Operating System: Lubuntu
* Installation type: Composer
* List of installed packages (`composer show`): none other than codeception/codeception and its dependencies
* Suite configuration:

```yml
# paste suite config here
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'sqlite:tests/_data/sqlite.db'
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```
tests/_data/dump.sql:
```sql
DROP TABLE IF EXISTS users;
CREATE TABLE USERS(username VARCHAR(20) NOT NULL PRIMARY KEY, email VARCHAR(20));
```
