### ISSUE TITLE
$I->acceptPopup() doesn't work with certain Chrome versions in Selenium

### ISSUE THREAD

**Issue by Suseika** [Codeception/Codeception#3681]
When I use `$I->acceptPopup()` in acceptance tests, with certain versions of Chrome in Selenium it fails with the following message after a web page has fired a `confirm()` dialog:

```
$ ./codecept run acceptance CompanyCreationCest:checkAddressHeaderIndex
Codeception PHP Testing Framework v2.2.4
Powered by PHPUnit 5.4.8 by Sebastian Bergmann and contributors.

Acceptance Tests (1) ---------------------------------------

                                                                                                                      
  [Facebook\WebDriver\Exception\UnexpectedAlertOpenException]                                                         
  unexpected alert open                                                                                               
    (Session info: chrome=53.0.2785.143)                                                                              
    (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 4.7.0-1-amd64 x  
  86_64) (WARNING: The server did not provide any stacktrace information)                                             
  Command duration or timeout: 3 milliseconds: null                                                                   
  Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'                                     
  System info: host: '3e41af4da722', ip: '172.24.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.7.0-1-amd6  
  4', java.version: '1.8.0_45-internal'                                                                               
  Driver info: org.openqa.selenium.chrome.ChromeDriver                                                                
  Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/  
  tmp/.com.google.Chrome.ip6Q9W}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=  
  false, version=53.0.2785.143, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=tr  
  ue, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabl  
  ed=true, cssSelectorsEnabled=true}]                                                                                 
  Session ID: 238a176edc49c77b361fb85b56601241                                                                        
                                                                                                                      

run [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]
```

The test is the following:

```php
    public function checkAddressHeaderIndex(AcceptanceTester $I)
    {
        $page = new CompanyCreatePage($I);
        $page->open();
        $I->dontSee('Shipping Address 2');
        $I->click('.wrapper_shipping button.add-item');
        $I->see('Shipping Address 2');
        $I->click('.wrapper_shipping button.remove-item');
        $I->acceptPopup();
        $I->dontSee('Shipping Address 2');
    }
```
I use selenium in a docker container. Here is the relevant part of my `docker-compose.yml`:

```yml
  selenium-hub:
    image: selenium/hub:2.50.0
    expose:
      - "4444"
  selenium-chrome:
    image: selenium/node-chrome:2.50.0
    links:
      - "selenium-hub"
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    expose:
      - "5555"
```

The test will throw the exception if I use `selenium/node-chrome` and `selenium/hub` Docker images of version 2.50.0 or later (the test doesn't throw the exception when both selenium/node-chrome and selenium/hub have version 2.49.1, for instance).

Refer to https://hub.docker.com/r/selenium/node-chrome/tags/ for Selenium Docker images versions.

### Details

* Codeception version: 
2.2.4
* PHP Version:
```
PHP 5.6.18 (cli) (built: Mar  2 2016 23:05:33) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```
* Operating System:
In a Docker container:
```
# uname -a
Linux c16d068676b3 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 GNU/Linux
```
* Installation type: Phar || Composer
Composer
* List of installed packages (`composer show`)
I don't think it matters
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Asserts
        - Yii2
    config:
        WebDriver:
            url: http://nginx/index-test.php
            host: 'selenium-hub'
            port: 4444
            browser: chrome
            window_size: 1280x1024
        Yii2:
          part: [init, orm, fixtures] # allow to use AR methods
          cleanup: false # don't wrap test in transaction
          entryScript: web/index-test.php
          configFile: _config/acceptance.php
```
