### ISSUE TITLE
Yii2 "There is no active transaction" since update from 2.2.5 to 2.2.6

### ISSUE THREAD

**Issue by schmunk42** [Codeception/Codeception#3682]
#### What are you trying to achieve?

Running functional test with check for `404`.

#### What do you get instead?

```bash
  [PDOException]                  
  There is no active transaction
```

```php
$I->amOnPage('/xx');
$I->seeResponseCodeIs(404);
```
### Details

* Codeception version: 2.2.6
* PHP Version: 7.0
* Operating System: Linux (Docker)
* Installation type: Composer
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        - Filesystem
        - Yii2
    config:
        Yii2:
            configFile: 'codeception/_config/test.php'
```

If I replace my base Docker image with an older version which had 2.2.5, tests pass.

**Comment by Naktibalda** [comment]
Add `cleanup: false` parameter to Yii2 module.

```yml
    config:
        Yii2:
            configFile: 'codeception/_config/test.php'
            cleanup: false
```

Like here: https://github.com/yiisoft/yii2-app-basic/blob/master/codeception.yml
