### ISSUE TITLE
LocalServer doesn't use the suite config url

### ISSUE THREAD

**Issue by gimler** [Codeception/Codeception#3688]
#### What are you trying to achieve?
LocalServer doesn't use get parameter from suite url

#### What do you get instead?
```bash
Functional Tests (1) ---------------------------------------
Modules: WebDriver, \Helper\Functional
------------------------------------------------------------
loginCept: 
Signature: loginCept
Test: tests/functional/loginCept.php
Scenario --
  [GET] http://www.example.local/index.php/
```

src/Codeception/Coverage/Subscriber/LocalServer.php:157
```php
$this->module->amOnPage('/');
```
Here the url from the suite config should be used. How can i access them?

### Details

* Codeception version: 2.2.6
* PHP Version: 5.6
* Suite configuration:

```yml
modules:
    enabled:
        - WebDriver:
             host: phantomjs
             port: 8643
             url: 'http://www.example.local/index.php?key=4bv5tho45'
```
