### ISSUE TITLE
Module Soap with PhpBrowser - Response not shown in verbose output

### ISSUE THREAD

**Issue by Noles** [Codeception/Codeception#3690]
#### What are you trying to achieve?
Test soap with PhpBrowser in verbose mode including Soap response
#### What do you get instead?
No Soap response in output

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Scenario --
 I send soap request "user_create","<?xml version=\"1.0\"?>\n<data><uid>iTest123<\/uid><username>test123@work<\/username>..."
  [Request] <soapenv:Envelope xmlns:ns="User" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"></soapenv:Header><soapenv:Body xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><ns:user_create><data><uid>iTest123</uid><username>test123</username></data></ns:user_create></soapenv:Body></soapenv:Envelope>
  [Response] {}
 I see soap response contains structure "<user_createResponse/>"
  [Structure] <?xml version="1.0"?>
  <user_createResponse/>
  
 FAIL
```
> Expected output

```php
Scenario --
 I send soap request "user_create","<?xml version=\"1.0\"?>\n<data><uid>iTest123<\/uid><username>test123@work<\/username>..."
  [Request] <soapenv:Envelope xmlns:ns="User" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"></soapenv:Header><soapenv:Body xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><ns:user_create><data><uid>iTest123</uid><username>test123@work</username></data></ns:user_create></soapenv:Body></soapenv:Envelope>
  [Response] <?xml version="1.0" encoding="UTF-8"?>
  <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Body><SOAP-ENV:Fault><faultcode>SOAP-ENV:Server</faultcode><faultstring>User exists</faultstring></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
  
 I see soap response contains structure "<user_createResponse/>"
  [Structure] <?xml version="1.0"?>
  <user_createResponse/>
  
 FAIL
```
### Details

* Codeception version: 
* PHP Version: 5.4
* Operating System: Ubuntu 16.04
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost/web
        - \Helper\Acceptance
        - SOAP:
            depends: PhpBrowser
            endpoint: 'http://localhost/web/soap.php'
            schema: 'User'
```
