### ISSUE TITLE
_reconfigure not works as expected in Yii2

### ISSUE THREAD

**Issue by jiangjiang99** [Codeception/Codeception#3695]
#### What are you trying to achieve?
I tried to "reconfigure" the configFile with functional.yml

1、this is my functional.yml

```
config:
        Yii2:
            configFile: 'config/functional.php'
        Db:
            dsn: 'mysql:host=127.0.0.1;dbname=ucx_t'
            user: 'ucx_t'
            password: 'ucx_t'
            cleanup: false
        MongoDb:
            dsn: 'mongodb://localhost:27017/com-foxit-storage'
            user: 'mongo'
            password: 'mongo'
            cleanup: false
```

2、Helper code

```php
class FunctionalHelper extends \Codeception\Module
{
public function _beforeSuite($settings = array()) {
        $this->getModule('Yii2')->_reconfigure(["configFile"=>"config/cloudfunctional.php"]);
        codecept_debug($this->getModule('Yii2'));
    }
}
```

#### What do you get instead?
"reconfigure"configFile fail , it is still load the configure  of" configFile: 'config/functional.php'"

3、I print out the" $this->getModule('Yii2')"

I paste the part of print out

```
[config:protected] => Array
          (
              [cleanup] => 
              [entryScript] => 
              [entryUrl] => http://localhost/index-test.php
              [configFile] => config/cloudfunctional.php
          )



[backupConfig:protected] => Array
          (
              [cleanup] => 
              [entryScript] => 
              [entryUrl] => http://localhost/index-test.php
              [configFile] => config/cloudfunctional.php
          )
```

it is show configFile  reconfigure success
but test still fail when I see Element

4、but when I use _setConfig,the test success 

```php
class FunctionalHelper extends \Codeception\Module
{
public function _beforeSuite($settings = array()) {
        $this->getModule('Yii2')->_setConfig(["configFile"=>"config/cloudfunctional.php"]);
        codecept_debug($this->getModule('Yii2'));
    }
}
```

why  use "_reconfigure" fail

* Codeception version: 2.2.4
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
