### ISSUE TITLE
Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist

### ISSUE THREAD

**Issue by githubjeka** [Codeception/Codeception#3715]
#### What are you trying to achieve?
Install [advanced Yii2](https://github.com/yiisoft/yii2-app-advanced)

run tests
```
Time: 7.66 seconds, Memory: 28.00MB

OK (24 tests, 67 assertions)
```

Add to site/index code:
```php
    public function actionIndex()
    {
        $tr = \Yii::$app->db->beginTransaction();
        $tr->commit();
        return $this->render('index');
    }
```
run tests

```php
>  [yii\db\Exception] SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1

ERRORS!
Tests: 24, Assertions: 66, Errors: 1.
```

### Details

* Codeception version: 2.2.6
* PHP Version:  7.0.5 
* Operating System: Windows 10 
* Mysql 5.7.10

**Comment by githubjeka** [comment]
I tried:
```yaml
class_name: FunctionalTester
modules:
    enabled:
        - Yii2:
          cleanup: false
```

try to set in http://www.yamllint.com/ is Valid :(

To fix my problem need to use
```yaml
class_name: FunctionalTester
modules:
    enabled:
        - Yii2:
                                                                            cleanup: false
```

F%^%k

**Comment by githubjeka** [comment]
@DavertMik 
Is't correct ?
```yaml
class_name: FunctionalTester
modules:
    enabled:
        - Yii2: {cleanup: false}
```

Why that?
```
 [Symfony\Component\Yaml\Exception\ParseException]  Malformed inline YAML string { at line 6 (near "Yii2: {")
```

**Comment by DavertMik** [comment]
> Is it correct ?

No, there is no `{}` in YAML format. YAML is set with spaces. In your 1st config you didn't specify space for `cleanup: false` as it was required.

In your working example you had more than enough spaces. Just remember, 4 spaces is usually OK for yaml. THis conifg should work as well

```yml
class_name: FunctionalTester
modules:
    enabled:
        - Yii2:
            cleanup: false
```
