### ISSUE TITLE
WebDriver->waitForText()

### ISSUE THREAD

**Issue by davidjeddy** [Codeception/Codeception#3721]
#### What are you trying to achieve?
Clarity in documentation.

#### What do you get instead?
Confusion until trial and error proved theorem.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
---------
1) LoginCept: Ensure login page works
 Test  ./acceptance/LoginCept.php
                                                    
  [Facebook\WebDriver\Exception\TimeOutException]   

Scenario Steps:

 15. $I->waitForText("Incorrect us...",5,"#login-form ...") at acceptance/LoginCept.php:23

```
> Provide test source code if related

```php
$I->waitForText('Username or email cannot be blank.', 10, '.help-block');
$I->waitForText('Password cannot be blank.', 10, '.help-block');
```
### Details

* Codeception version:  2.2.6
* PHP Version: 5.6.x
* Operating System: Moby Linux (docker container
* Installation type: composer
* List of installed packages na
* Suite configuration:

```yml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
  enabled:
    - Db
    - tests\codeception\frontend\AcceptanceHelper
    - tests\codeception\common\_support\FixtureHelper
    - WebDriver
  config:
    Db:
      dsn: %TEST_DB_DSN%
      user: %TEST_DB_USERNAME%
      password: %TEST_DB_PASSWORD%
      populate: true
      cleanup: true
      dump: ../common/_data/data.sql
    REST:
     url: 'http://localhost:%HTTP_PORT%/api/v1/'
    Yii2:
      configFile: 'codeception/config/acceptance.php'
      entryScript: 'index-test.php'
      part: [email, fixtures, init, orm]
    WebDriver:
      url: 'http://localhost:%HTTP_PORT%'
      cleanup: true
      browser: phantomjs
      window_size: 1280x720
      capabilities:
        unexpectedAlertBehaviour: 'accept'
      port: %PHANTOM_PORT%
```

#### Description
The documentation for waitForText (and by extension *Element) states `Waits up to $timeout seconds for the given string to appear on the page.`. The example shows a simple class selector. The issue arises then the n+1 element has a class that the content would appear in. waitFor*() functions as if only the first instance is the authoritative location, ignoring all others.

#### Goal
Clarify behavior in documentation or expand waitFor() to watch ALL markup elements that match the provided selector.
