### ISSUE TITLE
Uncaught Error in Yii2 module (travis)

### ISSUE THREAD

**Issue by brezzhnev** [Codeception/Codeception#3726]
#### What are you trying to achieve?

Run acceptance tests on Travis CI (local works fine).
Job log available at: https://travis-ci.org/brezzhnev/Test.Tour-booking-system/jobs/175091310#L463
I'm using basic Yii2 template.

#### What do you get instead?

I see next error

```bash
PHP Fatal error:  Uncaught Error: Call to a member function resetPersistentVars() on null in /home/travis/build/brezzhnev/Test.Tour-booking-system/vendor/codeception/base/src/Codeception/Module/Yii2.php:195
Stack trace:
#0 /home/travis/build/brezzhnev/Test.Tour-booking-system/vendor/codeception/base/src/Codeception/Subscriber/Module.php(68): Codeception\Module\Yii2->_after(Object(Codeception\Test\Cest))
#1 [internal function]: Codeception\Subscriber\Module->after(Object(Codeception\Event\TestEvent), 'test.after', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /home/travis/build/brezzhnev/Test.Tour-booking-system/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Codeception\Event\TestEvent), 'test.after', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /home/travis/build/brezzhnev/Test.Tour-booking-system/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.after', Object(Codeception\E in /home/travis/build/brezzhnev/Test.Tour-booking-system/vendor/codeception/base/src/Codeception/Module/Yii2.php on line 195
```
My acceptance test includes this code

```php
/**
 * Ensure that index page works
 * @param AcceptanceTester $I
 */
public function indexPageWorks(AcceptanceTester $I)
{
    $I->amOnPage(Url::toRoute('/booking/index'));
    $I->see('Bookings');
}
```
### Details

* Codeception version: 2.2.3
* PHP Version: 7.0.13
* Operating System: Ubuntu 16.04 (local), Travis - unknown 
* Installation type: Composer
* Suite configuration:

**acceptance.suite.yml**

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: 'http://127.0.0.1:8888'
            browser: phantomjs
        - Yii2:
            part: orm
            entryScript: index-test.php
            cleanup: false
```

**.travis.yml**

```yml
language: php

php:
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - psql -c 'create database "test.tour-booking-system";' -U postgres
  - php yii migrate --interactive=0
  - php -S localhost:8888 -t web > /dev/null 2>&1 &
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
  - composer install --prefer-source

services:
  - postgresql

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - travis_retry composer update --dev --prefer-dist --no-interaction
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php

script:
  - |
    vendor/bin/codecept build
    vendor/bin/codecept run
```
