### ISSUE TITLE
Get environment on which tests are running

### ISSUE THREAD

**Issue by rohankoid** [Codeception/Codeception#3741]
#### Get environment on which tests are running

```yml
   class_name: AcceptanceTester
    modules:
        enabled:
            - \Helper\Acceptance
            - WebDriver:
                 url: https://staging.needhelp.com                 
    env:
        firefox:
             modules:
                config:
                    qa_user: qauser1@gmail.com
                    WebDriver:
                        browser: 'firefox'
                        capabilities:
                            platform: Windows 7
    
        chrome:
             modules:
                config:
                    qa_user: qauser2@gmail.com
                    WebDriver:
                        browser: 'chrome'
                        capabilities:
                            platform: Windows 8.1
```

```bash
 $ codecept run acceptance UserCest.php --env firefox --env chrome
```

```php
class UserCest extends BaseAcceptance
    {
        public function login(AcceptanceTester $I)
        {
            $I->amOnPage("/");
            $I->see('Sign In');
            $env = $I->getConfig('env'); 
    //something like this ?? which would return 'firefox' for the instance it is running as environment firefox. 
            
            $I->fillField($this->usernameField, $this->username);
            $I->fillField($this->passwordField, $this->password);
        }

```
I am trying to get --env variable on which the test is running. 
### Details

* Codeception version: 2.2.6
* Suite configuration: acceptance

(Not sure if this is right platform to post this)
