### ISSUE TITLE
PhpBrowser does not honouring <base href=""> meta tag

### ISSUE THREAD

**Issue by hubbyist** [Codeception/Codeception#3764]
#### What are you trying to achieve?
By using PhpBrowser trying to click an anchor link.
page url is in 'http://example.com/sitefolder/folder/service/panel' format.
page is containing `<base href="http://example.com/sitefolder/folder/"/>` tag.
anchor href attribute is  "service/action".
after click operation current URL must be 'http://example.com/sitefolder/folder/service/action.
 
#### What do you get instead?
current URL becomes 'http://example.com/sitefolder/folder/service/service/action' as if there is no `<base href="">` meta tag in the page. From a normal browser link is working.

> Provide test source code if related

```php
    $I->amOnPage('/service/panel');
    $I->seeLink('Action', 'service/action');
    $I->click(['link' => 'Action']);
    $I->seeCurrentUrlEquals('http://example.com/sitefolder/folder/service/action');
```
### Details

* Codeception version: Codeception version 2.2.6
* PHP Version: PHP 7.0.8-0ubuntu0.16.04.3
* Operating System: linux mint 18.0
* Installation type: Phar
* List of installed packages (`composer show`) : none
* Suite configuration: 

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - Asserts
        - PhpBrowser:
            url: http://example.com/sitefolder/folder
        - \Module\RESTAPI:
            depends: PhpBrowser
        - Db:
            dsn: 'pgsql:host=localhost;dbname=dbname'
            user: 'username'
            password: 'password'
            dump: dump.sql
            populate: true
            cleanup: false
            reconnect: false
```
