### ISSUE TITLE
Yii2 module hangs forever during test run.

### ISSUE THREAD

**Issue by StalkAlex** [Codeception/Codeception#3769]
#### What are you trying to achieve?
Just run our tests. First test is using several fixtures and **InitDbFixture** among of them. Second test is using only one fixture(not InitDbFixture).

#### What do you get instead?
After second test Codeception hangs for a infinite time

### Details
Before 2.2.6 when *cleanup* parameter had false as a default value everythinkg was ok. I know I can set it in config but it's not a decision. 

If I won't use InitDbFixture everything is working.

* Codeception version: 2.2.6
* PHP Version: 7.0.12
* Operating System:
* Installation type: Composer
* Suite configuration:

```yml
# Codeception Test Suite Configuration

# suite for unit (internal) tests.
# RUN `build` COMMAND AFTER ADDING/REMOVING MODULES.

class_name: UnitTester
modules:
   enabled:
      - Asserts
      - Yii2
      - Db
      - Mockery
   config:
      Yii2:
        part: [init, orm, fixtures]
        configFile: 'tests/codeception/_config/unit.php'
#        cleanup: false
      Db:
          dsn: 'pgsql:host=localhost;port=5432;dbname=test'
          user: 'user'
          password: 'user'
          db: 'test'
          populate: false
          cleanup: false
          reconnect: false
```
