### ISSUE TITLE
Non-array argument supplied to foreach when trying to generate code coverage

### ISSUE THREAD

**Issue by grahamsutt12** [Codeception/Codeception#3778]
#### What are you trying to achieve?
I am trying to generate a code coverage report.

#### What do you get instead?
When trying to run tests with code coverage, I get the following error:

```bash
PHP Warning:  Invalid argument supplied for foreach() in /Users/graham1/Documents/Projects/PHP/tax-framework/vendor/codeception/codeception/src/Codeception/Coverage/Filter.php on line 74
```

This happens when trying to run the following commands:

```bash
codecept run unit --coverage
```

or 

```bash
codecept run unit --coverage-html
```

### Details

* Codeception version: 2.2
* PHPUnit Version: 5.6.7
* PHP Version: 7.0.1
* Operating System: Mac OS Sierra
* Installation type: Composer
* List of installed packages (`composer show`):

```
behat/gherkin                      v4.4.5 Gherkin DSL parser for PHP 5.3
codeception/codeception            2.2.6  BDD-style testing framework
doctrine/instantiator              1.0.5  A small, lightweight utility to instantiate objects in PHP with...
facebook/webdriver                 1.2.0  A PHP client for WebDriver
guzzlehttp/guzzle                  6.2.2  Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.3.0  Guzzle promises library
guzzlehttp/psr7                    1.3.1  PSR-7 message implementation
myclabs/deep-copy                  1.5.5  Create deep copies (clones) of your objects
phpdocumentor/reflection-common    1.0    Common reflection classes used by phpdocumentor to reflect the ...
phpdocumentor/reflection-docblock  3.1.1  With this component, a library can provide support for annotati...
phpdocumentor/type-resolver        0.2.1  
phpspec/prophecy                   v1.6.2 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          4.0.3  Library that provides collection, processing, and rendering fun...
phpunit/php-file-iterator          1.4.2  FilterIterator implementation that filters files based on a lis...
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  1.0.8  Utility class for timing
phpunit/php-token-stream           1.4.9  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.6.7  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.2  Mock Object library for PHPUnit
psr/http-message                   1.0.1  Common interface for HTTP messages
psr/log                            1.0.2  Common interface for logging libraries
sebastian/code-unit-reverse-lookup 1.0.0  Looks up which function or method a line of code belongs to
sebastian/comparator               1.2.2  Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.1  Diff implementation
sebastian/environment              2.0.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 2.0.0  Provides the functionality to export PHP variables for visualiz...
sebastian/global-state             1.1.1  Snapshotting of global state
sebastian/object-enumerator        2.0.0  Traverses array structures and object graphs to enumerate all r...
sebastian/recursion-context        2.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resou...
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-host...
symfony/browser-kit                v3.1.7 Symfony BrowserKit Component
symfony/console                    v3.1.7 Symfony Console Component
symfony/css-selector               v3.1.7 Symfony CssSelector Component
symfony/debug                      v3.1.7 Symfony Debug Component
symfony/dom-crawler                v3.1.7 Symfony DomCrawler Component
symfony/event-dispatcher           v3.1.7 Symfony EventDispatcher Component
symfony/finder                     v3.1.7 Symfony Finder Component
symfony/polyfill-mbstring          v1.3.0 Symfony polyfill for the Mbstring extension
symfony/yaml                       v3.1.7 Symfony Yaml Component
webmozart/assert                   1.2.0  Assertions to validate method input/output with nice error mess...

```

* Suite configuration (codeception.yml):

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
coverage:
    enabled: true
    include: src/*
```

**Comment by grahamsutt12** [comment]
The problem was solved for me when adding the following to the `vendor/codeception/codeception/src/Codeception/Coverage/Filter.php` file:

Changed the problem line on Line 74 from this:

```php
foreach ($coverage['whitelist']['include'] as $fileOrDir) { ... }
```

by typecasting the `$coverage['whitelist']['include']` to an `array` like so:

```php
foreach ((array) $coverage['whitelist']['include'] as $fileOrDir) { ... }
```

**Comment by grahamsutt12** [comment]
Seems that this error may also be caused because of a misconfiguration in my `codeception.yml` file.

I removed the typecast to `array` for `$coverage['whitelist']['include']` that I had mentioned in my previous comment and adjusted my `codeception.yml` to go from this:

```yml
coverage:
    enabled: true
    include: src/*
```

to this:

```yml
coverage:
    enabled: true
    whitelist:
        include:
            - src/*
```

and everything also worked fine when I reran tests with code coverage.

Any idea if this should require a fix to avoid silently failing?
