### ISSUE TITLE
Shortened output for steps

### ISSUE THREAD

**Issue by schmunk42** [Codeception/Codeception#3788]
#### What are you trying to achieve?

Run tests, seeing steps and their parameters `codecept run --steps`

```
11) StoreCept: Ensure that store ui works
 Test  tests/codeception/acceptance/prod/app/StoreCept.php
 Step  Fill field "input[name="login-form[login]"]","admin"
 Fail  Field by name, label, CSS or XPath element with 'input[name="login-form[login]"]' was not found.

Scenario Steps:

 4. $I->fillField("input[name="login-form[login]"]","admin") at tests/codeception/_support/AcceptanceTester.php:29
 3. $I->amOnPage("/user/security/login") at tests/codeception/_support/AcceptanceTester.php:28
 2. $I->dontSeeElementInDOM(".site-error .alert") at tests/codeception/acceptance/prod/app/StoreCept.php:7
 1. $I->amOnPage("/store") at tests/codeception/acceptance/prod/app/StoreCept.php:6
```
#### What do you get instead?

Shortened `(...")` output like

```
---------
31) HomeCept: Ensure that home page works
 Test  codeception/functional/HomeCept.php
 Step  See response code is 200
 Fail  Expected HTTP Status Code: 200 (OK). Actual Status Code: 404 (Not Found)
Failed asserting that 404 matches expected 200.

Scenario Steps:

 3. $I->seeResponseCodeIs(...0) at codeception/functional/HomeCept.php:10
 2. $I->seeElement(...") at codeception/functional/HomeCept.php:9
 1. $I->amOnPage(...") at codeception/functional/HomeCept.php:8
```
### Details

* Codeception version: 2.2.6
* PHP Version: 7.0
* Operating System: Alpine (Docker)
* Installation type: Composer (global)
* Suite configuration:

```yml
actor: Tester
paths:
    tests: codeception
    log: codeception/_output
    data: codeception/_data
    support: codeception/_support
    envs: codeception/_envs
settings:
    #shuffle: true
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Yii2:
            configFile: 'codeception/_config/main.php'
cleanup: false
config:
    test_entry_url: http://web:80/index.php
coverage:
    enabled: true
    c3_url: http://web/
    remote: false
    whitelist:
        include:
            - ../src/*.php
            - ../vendor/dmstr/*.php
            - ../vendor/hrzg/*.php
        exclude:
            - ../src/commands/*
            - ../src/migrations/*
```
