### ISSUE TITLE
"is " translated into "is not " in test output

### ISSUE THREAD

**Issue by hubbyist** [Codeception/Codeception#3801]
#### What are you trying to achieve?
Trying to see response which echos "is OK" phrase with $I->dontSeeResponseContains("ERROR") statement.

#### What do you get instead?
Test works but console test report shows "is OK" translated to "is not OK".

### Details
Only 'is OK' translated to 'is not OK'. 'isOK' or 'is-OK' is untouched.

* Codeception version: Codeception version 2.2.6
* PHP Version: PHP 7.0.8-0ubuntu0.16.04.3
* Operating System: linux mint 18.0
* Installation type: Phar
* List of installed packages (composer show) : none
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - Asserts
        - PhpBrowser:
            url: http://example.com/sitefolder/folder
        - \Module\RESTAPI:
            depends: PhpBrowser
        - Db:
            dsn: 'pgsql:host=localhost;dbname=dbname'
            user: 'username'
            password: 'password'
            dump: dump.sql
            populate: true
            cleanup: false
            reconnect: false
```
