### ISSUE TITLE
WaitforElementVisible is not working in 2.2.4

### ISSUE THREAD

**Issue by mkhalid20** [Codeception/Codeception#3815]
#### What are you trying to achieve?
I am trying to implement codeception in my project using webdriver and selenium. somehow i update the latest version 2.2.4 but $I->waitForElementVisible('#agree_button', 30); is not working in my project. can anyone suggest me the way how i can fix this issue. 
#### What do you get instead?
Unable to locate element:

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 

```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:  2.2.4
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
paths:
    tests: tests
    log: tests/log
    data: tests/data
    support: tests/support
    envs: tests/envs
settings:
    shuffle: true
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
    lint: true
modules:
    config:
        AMQP:
            host: 'localhost'
            port: '5672'
            username: 'guest'
            password: 'guest'
            vhost: '/'
            queues: [queue1, queue2]

extensions:
    enabled: [Codeception\Extension\RunFailed]

coverage:
    enabled: true
    include:
        - src/Codeception/Command/*
        - src/Codeception/Module/Symfony1.php
        - src/Codeception/Module/Symfony2.php
        - src/Codeception/Module/Doctrine1.php
        - src/Codeception/Module/Doctrine2.php
        - src/Codeception/Module/Kohana.php
        - src/Codeception/Module/SocialEngine.php
        - src/Codeception/Module/ZF1.php
```
