### ISSUE TITLE
Issue while setting up local testing environment with docker for parallel execution

### ISSUE THREAD

**Issue by p-saxena** [Codeception/Codeception#3817]
Hi All,

I am trying to set up local testing environment with docker for parallel execution. 
For this I pulled docker container for selenium grid, firefoxnode and chromenode from hub.docker.com

I configured successfully the docker-compose.yml file to register firefox and chrome node on hub.
I see both these node on grid console.

The issue I am facing is I am not able to launch my tests on any node registered on hub. 

When I try to execute tests with the following command:

```
./vendor/bin/codecept run acceptance --env testing-de_DE
```

I get following exception:                                                                                                            

```
  [Facebook\WebDriver\Exception\UnknownCommandException]                                                                                                                                                   
  GET /session/8e9400ff-7c27-4f53-8e9f-0b4939f12654/log/types did not match a known command                                                                                                                
  Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'                                                                                                                     
  System info: host: '81377a00d579', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-34-generic', java.version: '1.8.0_91'                                                        
  Driver info: org.openqa.selenium.firefox.FirefoxDriver                                                                                                                                                   
  Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, firefoxOptions={args=[], profile=UEsDBBQACAgIAGoyhUkAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJ  
  U0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3U  
  RU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90g  
  HysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N  
  6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/X  
  pELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQM6zAyIvdF4ixSbjadQhq87UXtRpTwwx+uBN3NjtyE9u4mIjc1WDVn+Ii4+I4xBhJwU04p6JEKH6nMxvfr0an02th/SKMQZyAfbE9Iy7Djzy83e5PTd  
  XN9NTpSg2Gl1FrlErekg9nrH9KOu24F+6Ot+TTm5nQ0zi3ZqJRBGXdGk/zMkqQHHJa+Br7/1gvW1//L6cUaYEDJFzGYmweTS/L/LsjJVlV4OW1xW+/d6qcv4GrUR27WQKrFPy6oO6sS023Mdb/wfaaNjI5AG98KOiIu0Szo4wGi3yqTVE4mNC+TMLrPre1X6aPsVYLd  
  l/ANQSwcIy87bUaYDAAC2DAAAUEsBAhQAFAAICAgAajKFScvO21GmAwAAtgwAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA2wMAAAAA}, appBuildId=20160922113459, version=49.0.1, platform=LINUX, proxy={}, co  
  mmand_id=1, specificationLevel=0, acceptSslCerts=false, processId=171, browserVersion=49.0.1, platformVersion=4.4.0-34-generic, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, t  
  akesScreenshot=true, takesElementScreenshot=true, platformName=linux, device=desktop, unexpectedAlertBehaviour=accept}]                                                                                  
  Session ID: 8e9400ff-7c27-4f53-8e9f-0b4939f12654                           
```

**content of my docker-compose.yml file is:**

```yaml
seleniumhub:
  image: selenium/hub
  ports:
    - 4444

firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 5555
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 5555
  links:
    - seleniumhub:hub
```

**content of acceptance.suite.yml file is:**

```yaml
class_name: AcceptanceTester

modules:
    enabled:
      - WebDriver:
          host: localhost
          port: 4444
          browser: firefox
          window_size: 1024x768
          url: 'http://localhost/'
          capabilities:
            unexpectedAlertBehaviour: 'accept'
      - \Helper\EnvSpecificHelper
      - \Helper\DbHelper
      - Asserts
      - Db
    config:
      Db:
        dsn: 
        user: 
        password: 
        populate: false
        cleanup: false
        dump: _data/migrations.sql
      \Helper\DbHelper:
        dsn: 
        user: 
        password: 
        populate: false
        cleanup: false
      WebDriver:
        host: localhost
        port: 4444
        browser: firefox
        url: 'http://localhost/'

env:
  testing-de_DE:
    modules:
      config:
        WebDriver:
          host: localhost
          port: 4444
          browser: firefox
          window_size: 1024x768
          url: 'https://xxxx.com/de'
          capabilities:
            unexpectedAlertBehaviour: 'accept'
          \Helper\EnvSpecificHelper:
```

I have placed my env file 'testing-de_DE' in _envs folder and its content is:

```yaml
modules:
  config:
    WebDriver:
      host: localhost
      port: 4444
      browser: firefox
      window_size: 1024x768
      url: 'https://xxxx.com/de'
      capabilities:
        unexpectedAlertBehaviour: 'accept'
      \Helper\EnvSpecificHelper:

      <<: *testingSimpleUrls_de_DE
      <<: *country_de_DE
      <<: *PDP
      <<: *NEWARRIVALS
      <<: *DISCOUNT
      <<: *Redirects
      <<: *TRADEIN
      <<: *RELATEDREFERENCES 
```

* Codeception version: 5.4.8
* Operating System: Ubuntu 16.04
* Installation type: Composer
