### ISSUE TITLE
HTML Resultprinter :: wrong MetaSteps when using Namespaces and inheritance 

### ISSUE THREAD

**Issue by mstaatz** [Codeception/Codeception#3818]
#### What are you trying to achieve?
Proper grouped HTML - Reports with MetaSteps

#### What do you get instead?
Only one big metastep including all steps from all metasteps, in unordered sorting.
Also tested if metasteps where found like in this Bug Report:
[https://github.com/Codeception/Codeception/issues/3523](https://github.com/Codeception/Codeception/issues/3523)

and yes... they where found. Maybe Information that comes from "debug_backtrace" is not correct. Have no idea.!?

> Folder structure of project

```php
tests/
|-- _data/
|-- _envs
|-- _output/
|-- _support/
|-- acceptance/
|-- functional/
	|-- Integration/
	|   |-- PhpBrowser/
	|   |   |-- DE/
	|   |   |   | -- DemoCest.php
	|   |-- DemoCest.php
	|-- Live/
	|-- _bootstrap.php
|-- unit/
|-- _bootstrap.php
|-- acceptance.suite.yml
|-- functional.suite.yml
|-- unit.suite.yml

```

> Files and Sourcecode
```php
// functional/_bootstrap.php
<?php
use Codeception\Util\Autoload;
$path = dirname(__FILE__);
Autoload::addNamespace(
    'Integration',
    $path . '/Integration'
);
Autoload::addNamespace(
    'Live',
    $path . '/Live'
);

// functional/Integration/PhpBrowser/DemoCest.php
<?php
namespace Integration\PhpBrowser;
use \FunctionalTester;

class DemoCest
{
    /**
     * @var \FunctionalTester
     */
    protected $tester;

    /**
     * @var \Page
     */
    protected $page;

    // also tested public function _demo1() with no difference
    protected function demo1()
    {
        $I = $this->tester;
        $upgradeCenterPage = $this->page;

        $I->wantTo('See a list of billings.');
        $upgradeCenterPage->login();
        $upgradeCenterPage->logout();
    }
}

// functional/Integration/PhpBrowser/DE/DemoCest.php
<?php
namespace Integration\PhpBrowser\DE;
use \FunctionalTester;

class DemoCest extends \Integration\PhpBrowser\DemoCest
{
    /**
     * @var \FunctionalTester
     */
    protected $tester;

    /**
     * @var \Page
     */
    protected $page;

    public function _before(FunctionalTester $I, \Page\Acceptance\Integration\DE\UpgradeCenterCustomerData $upgradeCenterPage)
    {
        $this->tester = $I;
        $this->page = $upgradeCenterPage;
    }

    public function demo1FG()
    {
        parent::demo1();
    }
}

```

> Screenshot of result.html

![bildschirmfoto 2016-12-06 um 09 22 09](https://cloud.githubusercontent.com/assets/2380482/20918243/4bbd3b0e-bb96-11e6-9105-994d08b63394.png)

### Details

(i have this also tested on my local mac with PHP 5.6.25, all other thing are same)

* Codeception version: 2.2.7
* PHP Version: 7.0.4
* Operating System: Suse Linux Enterprice
* Installation type: Composer
* List of installed packages (`composer show`)

behat/gherkin                               v4.4.5 Gherkin DSL parser for PHP 5.3
captbaritone/mailcatcher-codeception-module 1.2.1  Test emails in your Codeception acceptance tests
codeception/codeception                     2.2.7  BDD-style testing framework
codeception/robo-paracept                   0.2.0  Codeception Parallel Execution Tasks via Robo Task Runner
codegyre/robo                               0.7.2  Modern task runner
consolidation/robo                          0.7.2  Modern task runner
doctrine/instantiator                       1.0.5  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                          1.2.0  A PHP client for WebDriver
guzzlehttp/guzzle                           6.2.2  Guzzle is a PHP HTTP client library
guzzlehttp/promises                         1.3.0  Guzzle promises library
guzzlehttp/psr7                             1.3.1  PSR-7 message implementation
henrikbjorn/lurker                          1.2.0  Resource Watcher.
jakoch/phantomjs-installer                  2.1.1  A Composer package which installs the PhantomJS binary (Linux, Windows, Mac) into `/bin` of your project.
myclabs/deep-copy                           1.5.5  Create deep copies (clones) of your objects
phpdocumentor/reflection-common             1.0    Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock           3.1.1  With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is ...
phpdocumentor/type-resolver                 0.2.1  
phpseclib/phpseclib                         2.0.4  PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
phpspec/prophecy                            v1.6.2 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                   4.0.3  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                   1.4.2  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                   1.2.1  Simple template engine.
phpunit/php-timer                           1.0.8  Utility class for timing
phpunit/php-token-stream                    1.4.9  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                             5.7.2  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects                3.4.2  Mock Object library for PHPUnit
psr/http-message                            1.0.1  Common interface for HTTP messages
psr/log                                     1.0.2  Common interface for logging libraries
sebastian/code-unit-reverse-lookup          1.0.0  Looks up which function or method a line of code belongs to
sebastian/comparator                        1.2.2  Provides the functionality to compare PHP values for equality
sebastian/diff                              1.4.1  Diff implementation
sebastian/environment                       2.0.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                          2.0.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state                      1.1.1  Snapshotting of global state
sebastian/object-enumerator                 2.0.0  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context                 2.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations               1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                           2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
symfony/browser-kit                         v3.2.0 Symfony BrowserKit Component
symfony/config                              v3.2.0 Symfony Config Component
symfony/console                             v3.2.0 Symfony Console Component
symfony/css-selector                        v3.2.0 Symfony CssSelector Component
symfony/debug                               v3.2.0 Symfony Debug Component
symfony/dom-crawler                         v3.2.0 Symfony DomCrawler Component
symfony/event-dispatcher                    v3.2.0 Symfony EventDispatcher Component
symfony/filesystem                          v3.2.0 Symfony Filesystem Component
symfony/finder                              v3.2.0 Symfony Finder Component
symfony/polyfill-mbstring                   v1.3.0 Symfony polyfill for the Mbstring extension
symfony/process                             v3.2.0 Symfony Process Component
symfony/yaml                                v3.2.0 Symfony Yaml Component
webmozart/assert                            1.2.0  Assertions to validate method input/output with nice error messages.

* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - PhpBrowser:
            url: --- Snip ----
        - \Helper\Functional
        - \Helper\Email:
            url: --- Snip ----
            port: 1080
        - MailCatcher
    config:
        MailCatcher:
            url: --- Snip ----
            port: 1080

env:
    ewe-int:
        modules:
            enabled:
                - REST:
                    depends: PhpBrowser
                    url: --- Snip ----
    ewe-live:
        modules:
            enabled:
                - REST:
                    depends: PhpBrowser
                    url: --- Snip ----

    ews-int:
        modules:
            enabled:
                - PhpBrowser:
                    url: --- Snip ----
                - \Helper\Functional
                - SOAP:
                    depends: PhpBrowser
                    endpoint: --- Snip ----
                    schema: --- Snip ----

    ews-live:
        modules:
            enabled:
                - PhpBrowser:
                    url: -- Snip --
                - \Helper\Functional
                - SOAP:
                    depends: PhpBrowser
                    endpoint: --- Snip ----
                    schema: --- Snip ----

groups:
    functional-integration: tests/_data/functional-integration
    functional-live: tests/_data/functional-live
    functional-live-per-hour: tests/_data/functional-live-per-hour
```
