### ISSUE TITLE
Order of enabled modules changes ability to run tests

### ISSUE THREAD

**Issue by victorb** [Codeception/Codeception#382]
So I have the following functional test:

``` PHP
<?php
$I = new TestGuy($scenario);
$I->wantTo('see the landing page works');
$I->amOnPage('/');
$I->see('This is my anchor tag', 'a');
```

And the following config:

``` YAML
class_name: TestGuy
modules:
    enabled: [REST, PhpBrowser, Db, ZF1, TestHelper]

    config:
        Db:
            dsn: 'mysql:host=127.0.0.1;dbname=circle_test'
            user: 'ubuntu'
            password: ''
            dump: tests/_data/dump.sql
            populate: true
            cleanup: false
        ZF1:
            env: 'testing'
            app_path: '*/application'
            lib_path: 'library'
            config: '*/application/configs/application.ini'
        REST:
            url: 'http://test.*.com:8000'
            timeout: 90
        PhpBrowser:
            url: 'http://test.*.com:8000'
```

and a html page with some anchor tags. Everything works fine but if I switch to a different order in the modules enabled configuration, the tests fails.

Example of failing config:

``` YAML
class_name: TestGuy
modules:
    enabled: [Db, ZF1, TestHelper, REST, PhpBrowser]

    config:
        Db:
            dsn: 'mysql:host=127.0.0.1;dbname=circle_test'
            user: 'ubuntu'
            password: ''
            dump: tests/_data/dump.sql
            populate: true
            cleanup: false
        ZF1:
            env: 'testing'
            app_path: '*/application'
            lib_path: 'library'
            config: '*/application/configs/application.ini'
        REST:
            url: 'http://test.*.com:8000'
            timeout: 90
        PhpBrowser:
            url: 'http://test.*.com:8000'
```

Which order you use for enabled modules shouldn't really affect the ability to run tests, right?

(\* is just masking of the name, not really the url I use)
