### ISSUE TITLE
PhantomJs 2.1.1- Unable to Switch to Iframe with executeInSelenium function (as there is no name for my iframe) and this is resulting my test case fail when I ran using phantom

### ISSUE THREAD

**Issue by rajabhaskar** [Codeception/Codeception#3848]
#### I have a vimeo video frame on my webpage. Trying to switch to Iframe in PhantomJs 2.1.1 which is failing to access the elements inside it, whereas I am able get this TC working in Chrome and Firefox with the same code.
```js
$this->executeInSelenium(function (Facebook\WebDriver\Remote\RemoteWebDriver $webDriver)use ($video_iframe, $locatorType){
$webDriver->switchTo()->frame($webDriver->findElement(WebDriverBy::$locatorType($video_iframe)));
});

$this->click(".hd"); // .hd is the css locator for video quality adjuster button on play progress bar. 
```
####

> **Console Ouput:**
```
 CSS or XPath element with '.hd' was not found

1) Landing.feature: i am on /landing
 Test  src/xxxxxxx/Tests\acceptance\Landing.feature:i am on /landing
 Step  Move mouse over ".hd"
 Fail  CSS or XPath element with '.hd' was not found.

Scenario Steps:

 22. $I->moveMouseOver(".hd")
 21. $I->getLocator("common","vimeo_playing_button")
 20. $I->getLocator("common","vimeo_video_quality_button")
 19. $I->executeInSelenium("Closure") // here we have the switch to ifram code

```

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.2.1
* PHP Version:7.0.7
* PhantomJs Version: 2.1.1

```yml
modules:
    enabled:
        - WebDriver

config:
        WebDriver:
            url: 'https://xxx.yyyyy.com'
            browser: phantomjs
            wait: 2
            window_size: maximize
            clear_cookies: false
            capabilities:
                  unexpectedAlertBehaviour: 'accept'
                  handlesAlerts: true
```
