### ISSUE TITLE
Unable to emulate mobile chrome.

### ISSUE THREAD

**Issue by rdok-linkwise** [Codeception/Codeception#3858]
#### What are you trying to achieve?
Run tests in chrome mobile emulation: Reproduce invalid UI output, occurring when accessing from mobile. 

#### What do you get instead?
UI output is valid. No emulation happened. Of course manually emulating the device, the output is invalid. 

### Details

* Codeception version: 2.2
* PHP Version: 5.5.9
* Operating System: Ubuntu 14.04
* Installation type: Composer
* Selenium: 3.0.1
* Chrome driver: [2.26](https://chromedriver.storage.googleapis.com/index.html?path=2.26/)
* Suite configuration:

```yml
env:
    top:
         modules:
            config:
                WebDriver:
                    browser: 'chrome'
                    window_size: 360x640 # Logically this should not be needed
                    capabilities:
                      platform: ANDROID
                      browserName: chrome
                      mobileEmulation:
                        deviceName: 'Galaxy S5'
```

[Codeception browser capabilities](https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities#browser-specific-capabilities)  
[Capabilities & ChromeOptions](https://sites.google.com/a/chromium.org/chromedriver/capabilities) Search: mobileEmulation

**Comment by Naktibalda** [comment]
It isn't an issue of Codeception.

**Comment by rdok-linkwise** [comment]
@Naktibalda OK thanks. 

Wasn't sure the below configuration was correct. 

```
                      mobileEmulation:
                        deviceName: 'Galaxy S5'
```

**Comment by rdok-linkwise** [comment]
I was right, my configuration was incorrect.  

So if you need to start codeception tests in mobile emulation mode here's the environment section you need to use:

```yml
env:
    top:
         modules:
            config:
                WebDriver:
                    browser: 'chrome'
                    window_size: 360x640
                    capabilities:
                       platform: ANDROID
                       browserName: chrome
                       chromeOptions:
                            mobileEmulation:
                                 deviceName: 'Samsung Galaxy S4'
```

Just putting the mobile resolution is not enough. We need to put the tests in mobile emulation. 

E.g. when using chosen jquery plugin. Simply resizing to a mobile size, said library seemed to be working correctly.  However, when testing from an actual mobile device it was not. The above configuration achieves this.
