### ISSUE TITLE
Db module not loads dump correctly

### ISSUE THREAD

**Issue by ashgaliyev** [Codeception/Codeception#3867]
#### What are you trying to achieve?

I try to load sql dump (5 mb), created by mysqldump command

#### What do you get instead?

Db module loads not all tables

### Details

* Codeception version: 2.2.7
* PHP Version: PHP 7.0.14-2+deb.sury.org~trusty+1
* Operating System: Linux vagrant-ubuntu-trusty-64 3.13.0-91-generic #
* Installation type: Phar

```yml

class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://ts.vglocal/
        - \Helper\Acceptance
        - Db:
           dsn: 'mysql:host=localhost;dbname=ts_test'
           user: 'root'
           password: 'root'
           dump: tests/ts_test.sql
           populate: true
```

When I try to load by hands (populate: false) it works normally. 

Maybe should add some extra option for Db module (e.g. unsafe: true) to load dump line by line how it presented here http://stackoverflow.com/questions/19751354/how-to-import-sql-file-in-mysql-database-using-php ?
