### ISSUE TITLE
WebDrive's wait not exists

### ISSUE THREAD

**Issue by caiquecastro** [Codeception/Codeception#3875]
#### What are you trying to achieve?

I'm trying to delay the assertion on WebDriver. But it seems the wait method for WebDrive is not available anymore.

#### What do you get instead?

Before, I used to call $I->wait(10) to wait 10 seconds before some kind of assertion.

### Details

* Codeception version: 2.2.7
* PHP Version: 5.6.11
* Operating System: 
* Installation type: Composer
* Suite configuration:

```yml
class_name: ShopTester
modules:
    enabled:
        - WebDriver:
              url: https://www.test.dev
              browser: chrome
        - \Helper\Shop
```
