### ISSUE TITLE
Running code with XDEBUG option enabled, getting: Fatal error: Call to a member function getCookieJar() on null in ....vendor\codeception\codeception\src\Codeception\Module\REST.php on line 102

### ISSUE THREAD

**Issue by andsol** [Codeception/Codeception#3883]
#### What do you get instead?
If its null catch this case

> Provide console output if related. Use `-vvv` mode for more details.

```bash
FATAL ERROR. TESTS NOT FINISHED.
Call to a member function getCookieJar() on null 
in C:\Web\api\vendor\codeception\codeception\src\Codeception\Module\REST.php:102
PHP Fatal error:  Call to a member function getCookieJar() on null in C:\Web\api\vendor\codeception\codeception\src\Codeception\Module\REST.php on line 102
PHP Stack trace:
PHP   1. {main}() C:\Php\codecept.phar:0
PHP   2. require_once() C:\Php\codecept.phar:7
PHP   3. Codeception\Application->run() phar://C:/Php/codecept.phar/codecept:36
PHP   4. Symfony\Component\Console\Application->run() phar://C:/Php/codecept.phar/src/Codeception/Application.php:103
```
### Details

* Codeception version: ^2.2
* PHP Version: 7
* Operating System: win
* Installation type: Composer

```yml
# Codeception API suite configuration
class_name: ApiTester
modules:
    enabled:
        - Db
        - REST:
#            url: https://api.forextime.com
            depends: PhpBrowser
            part: Json
            xdebug_remote: true
```
