### ISSUE TITLE
./vendor/bin/codecept: line 1: ../codeception/codeception/codecept: No such file or directory

### ISSUE THREAD

**Issue by kcloze** [Codeception/Codeception#3889]
According to this issues: [https://github.com/Codeception/Codeception/issues/3684](https://github.com/Codeception/Codeception/issues/3684)

```
vendor/bin/codecept is a symlink to ../codeception/codeception/codecept so that require_once call works correctly.
```

**I know there is something wrong with symlink.we cann't make symlink in virtualbox share folder.
but how to deal with this problem,I must make the code in the share folder in virtulbox, can we remove this path dependence?**

### Details

* Codeception version: 2.2.7
* PHP Version:7.0
* Operating System:linux with virtualbox share folder

```yml
class_name: ApiTester
modules:
    enabled:
        - REST:
            depends: PhpBrowser     
            url: http://localhost/
```
