### ISSUE TITLE
Laravel queries stop working when using Db module for cleanup of acceptance tests

### ISSUE THREAD

**Issue by NerdsvilleCEO** [Codeception/Codeception#3898]
#### What are you trying to achieve?
I am trying to clear the database during each acceptance test run, so that I could remove all the serialized data, and I finally got that working successfully, but to do that I had to use a different DB name so that I could drop and recreate the database.

Process:
  1-3 works already
  1. Drop database if exists
  2. Recreate DB with user as owner
  3. Laravel migrations/seed
  4. Laravel queries in controller

#### What do you get instead?
It is saying that the relation doesn't exist
QueryException in Connection.php line 770:
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "blogposts" does not exist
LINE 1: select * from "blogposts"
^ (SQL: select * from "blogposts")
in Connection.php line 770
at Connection->runQueryCallback('sele

### Details

* Codeception version: 2.2.7
* PHP Version: 5.6.29
* Operating System: Centos 7.3
* Installation type: Composer

* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: "pgsql:host=10.0.1.4;dbname=anotherdb"
            user: ''
            password: ''
            dump: tests/_data/dump.sql

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: 'http://localhost:8000'
            browser: phantomjs
            window_size: maximize
        - Db
        - Laravel5:
            part: ORM
            run_database_migrations: true
            run_database_seeder: true
            database_seeder_class: DatabaseSeeder
            environment_file: .env.testing
        - \Helper\Acceptance
```
