### ISSUE TITLE
Codeception fatal error occurred when $I->executeJs(); command has been used in Firefox 50.1.0

### ISSUE THREAD

**Issue by cer06** [Codeception/Codeception#3910]
#### What are you trying to achieve?
I'm trying to execute a javascript using $I->executeJS(); in firefox 50.1.0. 

Note:
I tried the following command on Google Chrome and its working without any issue.

 
#### What do you get instead?
Then an error in the terminal occurs

"Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2 bytes) in C:\dri-automation\codeception\vendor\symfony\console\Application.php on line 1083"

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
https://cloud.githubusercontent.com/assets/19658473/21912707/877ea922-d962-11e6-9655-155dfd90dc27.png
 
```
> Provide test source code if related
```
class TestCest
{
   public function test(AcceptanceTester $I)
    {
       $I->amOnUrl("http://www.google.com");
       $I->executeJS("alert('hello world');");
    }
}
```

```php
// paste test
```
### Details

* Codeception version: 2.2.3
* PHP Version: 5.6.11
* Operating System: Win 8
* Installation type: Composer
* List of installed packages (`"codeception/codeception": "2.*",
 		"codeception/verify": "*",
 		"phpoffice/phpexcel": "1.8.0"`)
* Gecko version: v0.12.0 64 bit
* Selinium Server: 3.0.1
* Suite configuration:
```yml
# paste suite config here
class_name: AcceptanceTester
modules:
    enabled:
        - Asserts:
        - WebDriver:
            url: https://www.samplesite.com/
            browser: chrome
            window_size: maximize
            request_timeout: 120
            connection_timeout: 120
            delay: 1
            wait: 1
            restart: false
            clear_cookies: false
        - \Helper\Acceptance
```
