### ISSUE TITLE
Friends don't have their own cookies in PhpBrowser

### ISSUE THREAD

**Issue by insightfuls** [Codeception/Codeception#3911]
#### What are you trying to achieve?

Two users logged into a web site and one performs an action which affects the other. In very pseudo code, something like this:

```
$fred=$I->haveFriend();
$I->login("grace");
$fred->does(function(AcceptanceTester $I){
    $I->login("fred");
    $I->doSomething();
});
$I->seeTheConsequences();
```

#### What do you get instead?

The problem is that friends don't seem to have independent cookies. When the code gets to `$I->seeTheConsequences()` the main tester ($I) has hijacked Fred's session because Fred's call to `$I->login("fred")` has replaced the cookie from `$I->login("grace")`.

### Details

* Codeception version: 2.2.7
* PHP Version: 5.6
* Operating System: Mac OS X
* Installation type: Phar
* List of installed packages: none via composer; don't believe it is relevant anyway
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - \Module\PhpBrowser:
            url: http://localhost:8989/WebInterface.php
```
