### ISSUE TITLE
[?] Manage .env file according to --env flag

### ISSUE THREAD

**Issue by eXorus** [Codeception/Codeception#3920]
Hello,

I need your help because I don't understand how to do that with codeception.

I have different environment for testing:

- https://stage.company.com with TOKEN_API=xxxxxx
- https://stage-{id}.company.com with TOKEN_API=yyyyyy

I would like to:
- have TOKEN_API in .env file to protect my secret
- run codecept with --env flag to run to stage or stage-1 or stage-2 ...

How do you manage that because I can't figure out how to load specific .env file according to the --env flag I give.

Thanks for your help

The only solution I found for the moment is:

codeception.yml
```yml
env:
    stage:
        modules:
            config:
                WebDriver:
                    url: https://stage.company.com
    stage-branch:
        modules:
            config:
                WebDriver:
                    url: https://stage-%BRANCH_ID%.company.com
```

use only one .env file
```yml
BRANCH_ID="1234"
TOKEN_API_STAGE="xxxxxx"
TOKEN_API_STAGE-BRANCH="yyyyyy"
```

And in my Cest file I need to do something like this:
```php
if ($scenario->current('env') == 'stage') return getenv('TOKEN_API_STAGE')
else return getenv('TOKEN_API_STAGE-BRANCH')
```
