### ISSUE TITLE
Yii2 HTTP_HOST was hard code as localhost

### ISSUE THREAD

**Issue by tphanx** [Codeception/Codeception#3940]
#### What are you trying to achieve?
I try to support multiple site on Yii2 by load data base on host info Yii::$app->request->getHostInfo(), but I get localhost event the entryUrl was set not localhost.

The HTTP_HOST should be same as entryUrl "site1.frontend.loc"

#### What do you get instead?
Yii::$app->request->getHostInfo() return localhost

$_SERVER data as below:

array (
  'SCRIPT_FILENAME' => 'index-test.php',
  'SCRIPT_NAME' => '/index-test.php',
  'SERVER_NAME' => 'site1.frontend.loc',
  'SERVER_PORT' => '80',
  'HTTPS' => false,
  'REQUEST_TIME' => 1484986347,
  'REQUEST_TIME_FLOAT' => 1484986347.2003591,
  'HTTP_REFERER' => 'http://localhost/offer/view?id=100002',
  'HTTP_HOST' => 'localhost',
  'REQUEST_URI' => '/offer/view?id=100002',
  'REQUEST_METHOD' => 'POST',
)

### Details

* Codeception version: 2.2.8
* PHP Version: 7.0.0
* Operating System: Windows
* Installation type: Composer
* Suite configuration:

```yml
namespace: frontend\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'
            entryUrl: 'http://site1.frontend.loc/index-test.php'
```

**Comment by Naktibalda** [comment]
Have you configured any hostname routes?

**Comment by edno** [comment]
Did you try to follow Yii2 recommendation concerning [getHostInfo()](http://www.yiiframework.com/doc-2.0/yii-web-request.html#getHostInfo()-detail) by setting `hostInfo`?

**Comment by tphanx** [comment]
> Have you configured any hostname routes?

Do you mention Yii2 codecept module? I did configure the entryUrl and the SERVER_NAME was extracted from there, I think HTTP_HOST should be the same. However now, it's localhost.

> Did you try to follow Yii2 recommendation concerning getHostInfo() by setting hostInfo?

This function will return the HTTP_HOST first, then SERVER_NAME, if it returns SERVER_NAME here then it's correct for my case

I did export the $_SERVER var and it was as below...
```php
array (
'SCRIPT_FILENAME' => 'index-test.php',
'SCRIPT_NAME' => '/index-test.php',
'SERVER_NAME' => 'site1.frontend.loc',
'SERVER_PORT' => '80',
'HTTPS' => false,
'REQUEST_TIME' => 1484986347,
'REQUEST_TIME_FLOAT' => 1484986347.2003591,
'HTTP_REFERER' => 'http://localhost/offer/view?id=100002',
'HTTP_HOST' => 'localhost',
'REQUEST_URI' => '/offer/view?id=100002',
'REQUEST_METHOD' => 'POST',
)
```
In this case the HTTP_HOST should same as SERVER_NAME

**Comment by edno** [comment]
`HTTP_HOST` is returning the hostname from client request, and I would assume that the client request was requesting `localhost` and not `site1.frontend.loc` as you can see in `HTTP_REFERER`.
There's a good article about [SERVER_NAME Versus HTTP_HOST](http://shiflett.org/blog/2006/mar/server-name-versus-http-host).

**Comment by edno** [comment]
I had a look at the Yii2 module, and requests served by Codeception are build upon [Yii2 routes](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html), hence the URLs are served by Yii2.
```php
/**
     * To support to use the behavior of urlManager component
     * for the methods like this: amOnPage(), sendAjaxRequest() and etc.
     * @param $method
     * @param $uri
     * @param array $parameters
     * @param array $files
     * @param array $server
     * @param null $content
     * @param bool $changeHistory
     * @return mixed
     */
protected function clientRequest($method, $uri, array $parameters = [], array $files = [], array $server = [], $content = null, $changeHistory = true)
    {
        if (is_array($uri)) {
            $uri = Yii::$app->getUrlManager()->createUrl($uri);
        }
        return parent::clientRequest($method, $uri, $parameters, $files, $server, $content, $changeHistory);
    }
```
I would guess that in your case the issue is somehow in related with your Yii2 configuration.

**Comment by tphanx** [comment]
@edno you are correct, in my scenario above. there are two requests.

The test case is executed and submit the second request... and the generated url from the first request has already incorrect. it should be http://site1.frontend.loc/offer/view?id=100002

And the entryUrl was setup correctly as http://site1.frontend.loc/index-test.php
Why the HTTP_HOST was set as localhost instead of site1.frontend.loc?

If I'm wrong, please let me know where can I configure it?

Thanks a lot.

**Comment by edno** [comment]
Can you share an example of test with those 2 requests

**Comment by tphanx** [comment]
It's quite easy... you can test functional login with advanced or basic app-template.

Suite configuration:

```yml
namespace: frontend\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'
            entryUrl: 'http://dev.frontend.loc/index-test.php'
```

Write a bootstrap for the application and in the bootstrap trace the $_SERVER variable to see the data
- before submit the from trace the $_SERVER data
```php
array (
...
'SCRIPT_FILENAME' => 'index-test.php',
'SCRIPT_NAME' => '/index-test.php',
'SERVER_NAME' => 'site1.frontend.loc',
...
)
```

there is no HTTP_HOST

- when submit the form trace the $_SERVER you will get full data as below

```php
array (
  'SCRIPT_FILENAME' => 'index-test.php',
  'SCRIPT_NAME' => '/index-test.php',
  'SERVER_NAME' => 'dev.frontend.loc',
  'SERVER_PORT' => '80',
  'HTTPS' => false,
  'REQUEST_TIME' => 1484995362,
  'REQUEST_TIME_FLOAT' => 1484995362.5979531,
  'HTTP_REFERER' => 'http://localhost/index-test.php?r=site%2Fcontact',
  'HTTP_HOST' => 'localhost',
  'REQUEST_URI' => '/index-test.php?r=site%2Fcontact',
  'REQUEST_METHOD' => 'POST',
)
```
