### ISSUE TITLE
Suggestion: update http://codeception.com/for/laravel according to the latest version docs

### ISSUE THREAD

**Issue by marcelopm** [Codeception/Codeception#3941]
On http://codeception.com/for/laravel the api config looks like this:

```yaml
class_name: ApiTester
modules:
    enabled:
        - REST:
            url: /api/v1
            depends: Laravel5
        - \ApiBundle\Helper\Api
    config:
        - Laravel5:
            environment_file: .env.testing
```

However, ApiTester class seems to have changed namespace from \ApiBundle\Helper\Api to \Helper\Api in the latest version. The place for options such, as environment_file, has changed as well. I could only make it work using it like this:

```yaml
class_name: ApiTester
modules:
    enabled:
        - REST:
            url: /api/v1
            depends: Laravel5
        - \Helper\Api
        - Laravel5:
            environment_file: .env.testing
```

Reference: http://codeception.com/docs/modules/Laravel5
