### ISSUE TITLE
Yii2 Connector. db component is required now

### ISSUE THREAD

**Issue by unVooDoo** [Codeception/Codeception#3967]
#### What are you trying to achieve?
Want to run Yii2 tests without 'db' component. Don't need db in project

#### What do you get instead?
Getting: [yii\base\InvalidConfigException] Unknown component ID: db
'db' component is mandatory because of these rows:
https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/Connector/Yii2.php#L61
```php
public function resetApplication()
    {
        if ($this->app->db !== null && $this->app->db->transaction !== null) {
            $this->app->db->transaction->rollBack();
        }
        $this->app = null;
    }
```

There should be additional check for db component like:
```php
public function resetApplication()
    {
        if ($this->app->has('db') && $this->app->db !== null && $this->app->db->transaction !== null) {
            $this->app->db->transaction->rollBack();
        }
        $this->app = null;
    }
```
this way it works fine

> Provide console output if related. Use `-vvv` mode for more details.

```bash
1) ClientCest: Want to login client
 Test  tests/api/ClientCest.php:login
                                                              
  [yii\base\InvalidConfigException] Unknown component ID: db 
```

### Details

* Codeception version: 2.2.8
* PHP Version: 7.1
* Operating System: Centos 7
* Installation type: Composer

```yml
class_name: ApiTester
modules:
    enabled:
      - REST:
          url: 'http://localhost/v1/'
          depends: Yii2
      - \Helper\Api
      - Asserts
    config:
        - Yii2
```
PR: #3968
