### ISSUE TITLE
PhpBrowser - curl CURLOPT_USERAGENT option in yml configuration file not working?

### ISSUE THREAD

**Issue by oprog** [Codeception/Codeception#399]
in acceptance.suite.yml

```yml
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
    config:
        PhpBrowser:
            url: 'http://127.0.0.1'
            curl: 
                CURLOPT_USERAGENT: 'Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36'
```

running a simple test I still get the default user agent string:
> Guzzle/3.3.1 curl/7.27.0 PHP/5.4.16, Symfony2 BrowserKit

Any hint? is it a bug?
