### ISSUE TITLE
switchToIFrame requires an argument since 2.2.9 in generated class

### ISSUE THREAD

**Issue by ruudvanderweijde** [Codeception/Codeception#3998]
#### What are you trying to achieve?

`switchToIFrame` without a parameter fails in `2.2.9` in generated class when using `browser` test (see config below).

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
[Exception] Failed to execute command after 8 tries, with error: The given selector frame#,iframe# is either invalid or does not result in a WebElement. The following error occurred:
[22:43:10][Step 7/8] InvalidSelectorError: An invalid or illegal selector was specified
```

> Provide test source code if related

# Code execution
```php
            $I->switchToIFrame('form_selector');
            $I->fillField('foo', 'bar');
            $I->switchToIFrame();
```

# Generated code:
```php
    # version 2.2.8
    public function switchToIFrame($name = null) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('switchToIFrame', func_get_args()));
    }

    # version 2.2.9
    public function switchToIFrame($name) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('switchToIFrame', func_get_args()));
    }
```

# Generated class head
```php
<?php
 //[STAMP] 9fcc62c5fe55db9c3eeb7db11e8cda34

namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\PhpBrowser;

trait AcceptanceTesterActions
{
  ...
}
```

### Details

* Codeception version: 2.2.9
* PHP Version: any
* Operating System: any
* Installation type: Composer
* List of installed packages (`composer show`)
* Config:

```
class_name: AcceptanceTester
modules:
    enabled:
        - AcceptanceHelper:
           param1: ...
           param2: ...

env:
    php:
        modules:
            enabled:
                - AcceptanceHelper
                - PhpBrowser:
                    url: 'https://www.example.com/'

    browser:
        modules:
            enabled:
                - AcceptanceHelper
                - WebDriver:
                    url: 'https://www.example.com'
                    browser: firefox
                    window_size: 1024x768
```
