### ISSUE TITLE
Test name is different in `startTest` and `endTest` methods

### ISSUE THREAD

**Issue by SvetlanaZem** [Codeception/Codeception#4005]
#### What are you trying to achieve?
1) I created a test with an uppercase letter in `wantTo` parameter: 
```
<?php
class MyTestCest {
    public function editTest(\AcceptanceTester $I)
    {
        $I->wantTo("edit Content");
    }
}
```

2) I've implemented custom `ResultPrinter` and override `startTest` and `endTest` methods.

```
class PhpStorm_Codeception_ReportPrinter extends PHPUnit_TextUI_ResultPrinter
{
    public function startTest(PHPUnit_Framework_Test $test)
    {
        $testName              = \Codeception\Test\Descriptor::getTestAsString($test);
        $this->write("\nSTARTED: $testName\n");
    }

    public function endTest(PHPUnit_Framework_Test $test, $time)
    {
        $testName              = \Codeception\Test\Descriptor::getTestAsString($test);
        $this->write("\nENDED: $testName\n");

    }
}
```

3) I've executed the test with custom result printer.

I expect to see the same test name in `startTest` and `endTest`.
```
STARTED: MyTestCest: Edit Content

ENDED: MyTestCest: Edit Content
```

#### What do you get instead?
Test name from `endTest` method doesn't have an uppercase letter.
```
STARTED: MyTestCest: Edit Content

ENDED: MyTestCest: Edit content
``` 

It happens because of method `wantTo` in `Actor` class:
```
abstract class Actor
{
...
    public function wantTo($text)
    {
        $this->scenario->setFeature(mb_strtolower($text, 'utf-8'));
    }
}

```

### Details

* Codeception version: 2.2.8
* PHP Version: 7.1.1
* Operating System: Ubuntu
* Installation type: Composer
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    lint: false
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql

```
