### ISSUE TITLE
fillField switches focus halfway through the input

### ISSUE THREAD

**Issue by xikky** [Codeception/Codeception#4022]
#### What are you trying to achieve?
Insert text in an input using fillField(). 

#### What do you get instead?
If the text to input contains the numeric character '6', '6' is skipped and input continues on the next element ( as if 'tab' was pressed on the browser to focus on next element )

# paste output here
`
$I->fillField( "//input[@id='test']", 'asdf6qwert' );
`
Produces the following:

![image](https://cloud.githubusercontent.com/assets/8024321/23104385/220f6a4e-f6cd-11e6-9b65-1ac2e8e8da3f.png)

### Details

* Codeception version: 2.2.9
* PHP Version: 7.0.13
* Operating System: Xubuntu 4.12
* Installation type: Composer
* List of installed packages (`composer show`)
`{                                                                                                                        "require": {                                                                                                             "codeception/codeception": "^2.2"                                                                                }                                                                                                                }`
* Suite configuration:

```
class_name: AcceptanceTester
   modules: 
       enabled: 
           - WebDriver                                                                                                      
       config:                                                                                                                  
           WebDriver:                                                                                                              
               url: http://www.webbot.dev/                                                                                          
               browser: chrome                                                                                                      
               restart: true                                                                                                       
               window_size: maximize
               clear_cookies: true                                                                                                  
               options:                                                                                                                
                    cleanSession: true
```

Loading selenium as follows:
`java -Dwebdriver.chrome.driver=chromedriver -jar ../selenium-server-standalone-3.0.1.jar -timeout 0`

chromedriver version 2.27
