### ISSUE TITLE
Codeception with Selenium is unable to use DB data for Sign-In in Laravel 5.3.

### ISSUE THREAD

**Issue by Aqeel222** [Codeception/Codeception#4023]
#### All other things like clicking and typing happens but I can't login as a user - it redirects back to /login instead of /home

here is my test code.
```php 
<?php
$I = new FunctionalTester($scenario);
$I->am('aqeel and doing testing project');
$I->wantTo('test for sign up page');

$I->amOnPage('/');
$I->click('Login');
$I->wait(10);
$I->seeCurrentUrlEquals('/login');

$I->fillField('email','aqeel.contrive@gmail.com');
$I-> fillField('password','123456');

$I-> click('Login');

$I -> wait(10);

$I->seeCurrentUrlEquals('/home');
```

here is my functional.suite.yml file
```yml
## Codeception Test Suite Configuration
#
# Suite for functional (integration) tests
# Emulate web requests and make application process them
# Include one of framework modules (Symfony2, Yii2, Laravel5) to use it

class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - WebDriver:
                             url: 'http://local.adexpress-web.com/'
                             browser: firefox
                             environment_file: .env.testing
        - \Helper\Functional
```

here is my codeception.yml file
```yml
# actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:

        Db:
            dsn: 'mysql:host=localhost;dbname=adexpress_laravel;'
            user: 'root'
            password: ''
            dump: tests/_data/dump.sql
            populate: flase
            cleanup: false
            reconnect: true
```

this is .env.testing file
```php
// APP_ENV=local
APP_KEY=base64:rQNVZeOtr4HkFMBSYcmEXrAI6J+q8jLlf2IWyplvPjs=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://local.adexpress-web.com/

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=adexpress_laravel
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=
```

this is ```composer show``` output

```bash
# barryvdh/laravel-dompdf               v0.7.1  A DOMPDF Wrapper for Laravel
behat/gherkin                         v4.4.5  Gherkin DSL parser for PHP 5.3
classpreloader/classpreloader         3.1.0   Helps class loading performance by generating a single PHP file containing all of the autoloaded files for a specific use case
codeception/codeception               2.2.9   BDD-style testing framework
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base directory specification for php
doctrine/inflector                    v1.1.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                 1.0.5   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
dompdf/dompdf                         v0.7.0  DOMPDF is a CSS 2.1 compliant HTML to PDF converter
facebook/webdriver                    1.3.0   A PHP client for WebDriver
fzaninotto/faker                      v1.6.0  Faker is a PHP library that generates fake data for you.
guzzlehttp/guzzle                     6.2.2   Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1  Guzzle promises library
guzzlehttp/psr7                       1.3.1   PSR-7 message implementation
hamcrest/hamcrest-php                 v1.2.2  This is the PHP port of Hamcrest Matchers
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
jeremeamia/SuperClosure               2.3.0   Serialize Closure objects, including their context and binding
laravel/framework                     v5.3.30 The Laravel Framework.
laravelcollective/html                v5.3.1  HTML and Form Builders for the Laravel Framework
league/flysystem                      1.0.35  Filesystem abstraction: Many filesystems, one API.
league/fractal                        0.15.0  Handle the output of complex data structures ready for API output.
maatwebsite/excel                     2.1.10  An eloquent way of importing and exporting Excel and CSV in Laravel 4 with the power of PHPExcel
mockery/mockery                       0.9.8   Mockery is a simple yet flexible PHP mock object framework for use in unit testing with PHPUnit, PHPSpec or any other testing framework. Its...
modelizer/selenium                    v1.2.2  Selenium Package for laravel 5.
monolog/monolog                       1.22.0  Sends your logs to files, sockets, inboxes, databases and various web services
mtdowling/cron-expression             v1.2.0  CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
myclabs/deep-copy                     1.6.0   Create deep copies (clones) of your objects
nesbot/carbon                         1.22.1  A simple API extension for DateTime.
nikic/php-parser                      v3.0.4  A PHP parser written in PHP
paragonie/random_compat               v2.0.4  PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phenx/php-font-lib                    0.4     A library to read, parse, export and make subsets of different types of font files.
phenx/php-svg-lib                     0.1     A library to read, parse and export to PDF SVG files.
phpdocumentor/reflection-common       1.0     Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.1   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a Doc...
phpdocumentor/type-resolver           0.2.1
phpoffice/phpexcel                    1.8.1   PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpspec/prophecy                      v1.6.2  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             4.0.5   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.8   Utility class for timing
phpunit/php-token-stream              1.4.9   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.7.14  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.4.3   Mock Object library for PHPUnit
phpunit/phpunit-selenium              3.0.3   Selenium Server integration for PHPUnit
psr/http-message                      1.0.1   Common interface for HTTP messages
psr/log                               1.0.2   Common interface for logging libraries
psy/psysh                             v0.8.1  An interactive shell for modern PHP.
ramsey/uuid                           3.5.2   Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
sebastian/code-unit-reverse-lookup    1.0.0   Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.4   Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.1   Diff implementation
sebastian/environment                 2.0.0   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    2.0.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1   Snapshotting of global state
sebastian/object-enumerator           2.0.1   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           2.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0   Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
swiftmailer/swiftmailer               v5.4.6  Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                   v3.2.4  Symfony BrowserKit Component
symfony/console                       v3.1.10 Symfony Console Component
symfony/css-selector                  v3.1.10 Symfony CssSelector Component
symfony/debug                         v3.1.10 Symfony Debug Component
symfony/dom-crawler                   v3.1.10 Symfony DomCrawler Component
symfony/event-dispatcher              v3.2.4  Symfony EventDispatcher Component
symfony/finder                        v3.1.10 Symfony Finder Component
symfony/http-foundation               v3.1.10 Symfony HttpFoundation Component
symfony/http-kernel                   v3.1.10 Symfony HttpKernel Component
symfony/polyfill-mbstring             v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-util                 v1.3.0  Symfony utilities for portability of PHP codes
symfony/process                       v3.1.10 Symfony Process Component
symfony/routing                       v3.1.10 Symfony Routing Component
symfony/translation                   v3.1.10 Symfony Translation Component
symfony/var-dumper                    v3.1.10 Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.2.4  Symfony Yaml Component
tijsverkoyen/css-to-inline-styles     2.2.0   CssToInlineStyles is a class that enables you to convert HTML-pages/files into HTML-pages/files with inline styles. This is very useful when...
vlucas/phpdotenv                      v2.4.0  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
webmozart/assert                      1.2.0   Assertions to validate method input/output with nice error messages.
yajra/laravel-datatables-oracle       v6.24.4 jQuery DataTables API for Laravel 4|5

```

### Details

* Codeception version:   "codeception/codeception": "^2.2",
* PHP Version:  7.0.6
* Operating System: windows 8.1
* Installation type: Composer

Am i missing something? any kind of help will be appreciated.
