### ISSUE TITLE
Codeception with Symfony 3.1, Kernel class not found

### ISSUE THREAD

**Issue by tompiard** [Codeception/Codeception#4056]
I'm trying to run Codeception with the Symfony module enabled. It works great without the module, but if I enable it I get this error as soon as I run some test: 

```
Codeception PHP Testing Framework v2.2.9
Powered by PHPUnit 5.7.9 by Sebastian Bergmann and contributors.
PHP Fatal error:  Class 'Symfony\Component\HttpKernel\Kernel' not found in /var/www/myproject/app/AppKernel.php on line 6
```

I try several config, the problem remains the same. Get the same result with -vvv param.

* Codeception version: 2.2.9
* PHP Version: 7.1
* Symfony version: 3.1/3.2
* Installation type: composer

```yml
class_name: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: '../../../app'
            var_path: '../../../var'
        - Doctrine2:
            depends: Symfony
        - \App\AppBundle\Helper\Functional
```

Thanks !
