### ISSUE TITLE
[RuntimeException] Suite '' could not be found - YII2

### ISSUE THREAD

**Issue by ahmednawazbutt** [Codeception/Codeception#4067]
#### What do you get instead?

```bash
[RuntimeException]           
  Suite '' could not be found

```

before that, I was getting the below message
```bash
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Yii' not found
```
I have not idea what i did that caused the new error to appear. but they still seem to be inter-linked at some point.

##### Here is my code in my Test File named as: common\modules\ofilesgallery\tests\unit\models\FilemgtStatusTest;

```php

namespace common\modules\ofilesgallery\tests\unit\models;

use common\modules\ofilesgallery\models\FilemgtStatus;
use common\modules\ofilesgallery\fixtures\FilemgtStatusFixture;
// use common\modules\ofilesgallery\fixtures\FilemgtStatusFixture;

class FilemgtStatusTest extends \Codeception\Test\Unit
{
    public function fixtures()
    {
        return [
            'FilemgtStatus' => FilemgtStatusFixture::className()
        ];
    }
    
    public function testNoData()
    {
        $model = new FilemgtStatus([
            'name' => null,
            'color' => null,
        ]);
        expect('error message should be set against name', $model->errors)->hasKey('name');
        expect('error message should be set against name', $model->color)->hasKey('color');
    }
}
```

##### Here is my fixture file named as: common\modules\ofilesgallery\fixtures\common\modules\ofilesgallery\fixtures
```bash
public $modelClass = 'common\modules\ofilesgallery\models\FilemgtStatus';
	public $depends = 
	[
	   
	];
```
### Details

Please let me know if you need something more to help.

* Codeception version: 
* PHP Version:
* Operating System: Linux
* Installation type: Composer Update
* List of installed packages (`composer show`)

codeception/base                        2.2.9    BDD-style testing framework
codeception/codeception                 2.2.9    BDD-style testing framework
codeception/specify                     0.4.6    BDD code blocks for PHPUnit and Codeception
codeception/verify                      0.3.3    BDD assertion library for PHPUnit

* Suite configuration:

### codeception.yml
```yml
namespace: common\modules\ofilesgallery\tests

actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    colors: true
modules:
    config:
        Yii2:
            configFile: '/../../config/test-local.php'
    
```
