### ISSUE TITLE
Fail on low coverage

### ISSUE THREAD

**Issue by Kolyunya** [Codeception/Codeception#4078]
#### What are you trying to achieve?
Restrict minimal code-coverage via CI specifying `low_limit` in config. I expect to get exit code distinct from `0` when coverage is lover than `low_limit`.

#### What do you get instead?
`codecept run unit --coverage` doesn't fail (process return code is `0`) when actual coverage is lower than `low_limit`.

### Details

* Codeception version: 2.2.9
* PHP Version: 7.1.3
* Operating System: GNU/Linux
* Installation type: Composer
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    low_limit: 80
    high_limit: 90
    include:
        - src/*
```
