### ISSUE TITLE
How to start Symfony server automatically

### ISSUE THREAD

**Issue by maximelebastard** [Codeception/Codeception#4118]
#### What are you trying to achieve?

I would like to declare some commands to run before running the tests. One of these commands is to launch the Symfony test server: 
```
app/console server:run -e test -p 30080
```

I'd like to do the same with the PhantomJS headless server.

The best way for me to do it would be by declaring a "before commands hook" in the codeception.yml or in the *.suite.yml files.

#### What do you get instead?

I hacked an acceptance Helper to run the commands, but that's really really ugly, not reliable and badly designed:

```php
class Acceptance extends \Codeception\Module
{
	public function _beforeSuite($settings = array()){
		// Start servers
		$this->startPhantomJs();
		$this->startSymfonyServer();
	}
	
	public function _afterSuite($settings = array()){
		// Stop servers
		$this->killPhantomJs();
		$this->killSymfonyServer();
	}
	
	protected function startPhantomJs(){
		echo("\n Starting Phantom JS \n");
		$command =  'phantomjs --webdriver 4444' . ' > ./phantomjs.log >&1 & echo $!; ';
		$pid = exec($command, $output);
		$this->phantomJsPid = $pid;
		sleep(3); // Waiting the start
		
		echo("\n Phantom JS started on process $pid \n");
		
	}
	
	protected function killPhantomJs(){
		if(isset($this->phantomJsPid)){
			echo("\n Stoping Phantom JS on PID ".$this->phantomJsPid." \n");
			exec("kill " . $this->phantomJsPid);
		}
	}
	
	protected function startSymfonyServer(){
		echo("\n Starting Symfony server \n");
		$command =  'php app/console server:run -e test -p 30080' . ' > ./phantomjs.log >&1 & echo $!; ';
		$pid = exec($command, $output);
		$this->symfonyServerPid = $pid;
		sleep(3); // Waiting the start
		
		echo("\n Symfony server started on process $pid \n");
	}
	
	protected function killSymfonyServer(){
		if(isset($this->symfonyServerPid)){
			echo("\n Stoping Symfony server on PID ".$this->symfonyServerPid." \n");
			exec("kill " . $this->symfonyServerPid);
		}
	}
}
```

### Details

* Codeception version:  2.2.9
* PHP Version: 5.6.30
* Operating System: Mac OS X Sierra
* Installation type: Composer
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://127.0.0.1:30080/
            browser: 'phantomjs'
        - WsBundle\Helper\Acceptance
        - Codeception\Module\Asserts
        - Cli
```

**Comment by Naktibalda** [comment]
You could use [phpbuiltinserver](https://github.com/tiger-seo/PhpBuiltinServer) extension for starting "Symfony server" automatically.

As for running custom commands, it is a good idea for another extension, but I don't see it implemented any time soon. You are welcome to implement it.

**Comment by maximelebastard** [comment]
It works fine ! I did the same for phantomjs.

Here is my codeception.yml at root of my Symfony project:
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
include:
    - src/AppBundle
    - src/UserBundle
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\PhpBuiltinServer
        - Codeception\Extension\Phantoman
    config:
      Codeception\Extension\PhpBuiltinServer:
        hostname: 127.0.0.1
        port: 30080
        autostart: true
        documentRoot: web
        router: web/app_test.php
        directoryIndex: app_test.php
        startDelay: 1
        phpIni: /opt/local/etc/php56/php.ini
        suites: ['acceptance']
      Codeception\Extension\Phantoman:
        path: '/usr/local/bin/phantomjs'
        suites: ['acceptance']
```
