### ISSUE TITLE
Modules configuration inheritance with includes

### ISSUE THREAD

**Issue by maximelebastard** [Codeception/Codeception#4122]
Hi,

#### What are you trying to achieve?

My project is structured like this:
```
Project
-AppBundle/
    -tests/
        -api.suite.yml
    -codeception.yml
-UserBundle/
    -tests/
        -acceptance.suite.yml
    -codeception.yml
-tests/
    -_data
        -dump.sql
-codeception.yml
```

I'd like to use the Db module with all my tests, with the same configuration.

Here is my **/codeception.yml**
```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
include:
    - src/AppBundle
    - src/UserBundle
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\PhpBuiltinServer
        - Codeception\Extension\Phantoman
modules:
  enabled:
        - Db
  config:
    Db:
      dsn: 'mysql:host=localhost;dbname=ctests'
      user: 'ctests'
      password: ''
      dump: 'tests/_data/dump.sql'
      populate: true
      cleanup: true
      reconnect: true
    config:
      Codeception\Extension\PhpBuiltinServer:
        hostname: 127.0.0.1
        port: 30080
        autostart: true
        documentRoot: web
        router: web/app_test.php
        directoryIndex: app_test.php
        startDelay: 1
        phpIni: /opt/local/etc/php56/php.ini
      Codeception\Extension\Phantoman:
        path: '/usr/local/bin/phantomjs'
        suites: ['acceptance']
```

Here is my **AppBundle/tests/api.suite.yml** where I use my modules:
```yaml
class_name: ApiTester
modules:
  enabled:
        - \Helper\Api
        - REST:
            url: http://localhost:30080/api/
            depends: PhpBrowser
            part: Json
```

#### What do you get instead?

If I keep it like this, Db module is not enabled ; probably because the api.suite.yml modules configuration overrides the /codeception.yml one.

If I try to enable the Db module in my api.suite.yml module, I get an error saying that Db module is not configured.

I have to put my Db module configuration in every suite I use, which is not nice.

I'd like to be able to mutualize my Db configuration for all my suites but also be able to use some additional modules on some suites (REST for Api test suites and not for acceptation testing for example).

### Details

* Codeception version: 2.2.9
* PHP Version: 5.6
* Operating System: Mac OS X Sierra
* Installation type: Composer
