### ISSUE TITLE
Drag&drop isn't working properly

### ISSUE THREAD

**Issue by bylasnoches** [Codeception/Codeception#4152]
#### I tried to drag lower blue square towards the upper one.
Please check the code and video below.

#### As I understand after the square was dragged, it transfers to the top of the page(oudside the screen) and then it drops. Beacuse of it was dropped outside the screen it returns to its initial position.

```php
$I->amOnPage('/');
$I->scrollTo('//*[@id="dragging"]');
$I->wait(3);
$I->dragAndDrop('//*[@id="drag-2"]', '//*[@id="drag-1"]');
$I->wait(5);
```

And here's video with dragging's proccess:
https://youtu.be/YJEiUd5HQrU
Testing link -  http://interactjs.io/

* Codeception version: 2.2.8
* PHP Version: 5.6.30-10+deb.sury.org~xenial+2
* Operating System: Linux Mint 18 Sarah 64-bit
* Installation type: Composer
* Selenium: selenium-server-standalone-3.3.1
* Google chrome: Version 58.0.3029.81 (64-bit)
* ChromeDriver: 2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5)
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
        # add framework module here
        - WebDriver
        - Asserts
    config:
        WebDriver:
            url: 'http://interactjs.io'
            browser: 'chrome'
            window_size: 'maximize'
```
