### ISSUE TITLE
Check a checkbox without ID in multiple rows - yii2 Codeception

### ISSUE THREAD

**Issue by ahmednawazbutt** [Codeception/Codeception#4155]
####  What are you trying to achieve?
Click a Checkbox against a record and then delete the selected record in yii2 using codeception testing enviroment

#### What do you get instead?
Fail  Checkbox or Radio by Label or CSS or XPath element with '#message-grid > table > tbody > tr > td:nth-child(1) > input[type="checkbox"]' was not found.

or
Fail  Link or Button or CSS or XPath element with '//*[@data-key="1"]/td[@class="text-center"]/input[@type="checkbox" and @value="1"]' was not found.

> Here is my Error Log:

```bash
1) MessageCest: Sent_mark un read with selection
 Test  tests/acceptance/models/MessageCest.php:Sent_MarkUnReadWithSelection
 Step  Click "//*[@data-key="1"]/td[@class="text-center"]/input[@type="checkbox" and @value="1"]"
 Fail  Link or Button or CSS or XPath element with '//*[@data-key="1"]/td[@class="text-center"]/input[@type="checkbox" and @value="1"]' was not found.

Scenario Steps:

 8. $I->click("//*[@data-key="1"]/td[@class="text-center"]/input[@type="checkbox" and @value="1"]") at tests/acceptance/models/MessageCest.php:162
 7. $I->wait(3) at tests/acceptance/models/MessageCest.php:33
 6. $I->dontSee("Incorrect username or password") at tests/acceptance/models/MessageCest.php:31
 5. $I->click(".btn-success") at tests/acceptance/models/MessageCest.php:30
 4. $I->fillField("#loginform-password","offneo123") at tests/acceptance/models/MessageCest.php:26
 3. $I->fillField("#loginform-username","admin1") at tests/acceptance/models/MessageCest.php:25


FAILURES!
Tests: 1, Assertions: 1, Failures: 1.

```
> Here is my MessageCest class method:

```php
public function Sent_MarkUnReadWithSelection(AcceptanceTester $I)
    {
        $idmessage = 1;
        $xPath_Checkbox = '//*[@data-key="'. $idmessage .'"]/td[@class="text-center"]/input[@type="checkbox" and @value="'. $idmessage .'"]';
        
//         $selector = '#message-grid > table > tbody > tr > td:nth-child(1) > input[type="checkbox"]';
//         $I->see('//*[@data-key="1" and @class="unread"]')
        $I->click($xPath_Checkbox);
        $I->click('a#mark-unread');
        
    }
```
### Details

* Codeception version: 2.2.9
* PHP Version: > 5.4
* Operating System: Linux
* Installation type: Composer

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Yii2:
           part:
              [init, orm]
    config:
        WebDriver:
            url: 'http://localhost/TestProject/'
            browser: phantomjs
            window_size: 1920x1310
            capabilities:
              webStorageEnabled: true

```
