### ISSUE TITLE
cannot load modal window in codeception testing

### ISSUE THREAD

**Issue by ahmednawazbutt** [Codeception/Codeception#4159]
#### its more like if we click a button that opens a bootstrap modal window with right-click of mouse and then ask to open the target link in new window. The link is POST only. So if I click it in new window, I should get an error and thats what I am getting all the time.

> **Method Not Allowed (405)**

> Here is the console log for the method output

```bash
1) MessageCest: Compose message no values
 Test  tests/acceptance/models/MessageCest.php:ComposeMessageNoValues
 Step  See "Write message","h4.modal-title"
 Fail  Element located either by name, CSS or XPath element with 'h4.modal-title' was not found.

Scenario Steps:

 15. $I->see("Write message","h4.modal-title") at tests/acceptance/models/MessageCest.php:204
 14. $I->click(".btn-success") at tests/acceptance/models/MessageCest.php:203
 13. // I am going to Open the modal window to Compose a Message
 12. $I->seeInTitle("Messages") at tests/acceptance/models/MessageCest.php:295
 11. $I->see("Compose","a#composeBtn") at tests/acceptance/models/MessageCest.php:294
 10. $I->see("Messages") at tests/acceptance/models/MessageCest.php:293


FAILURES!
Tests: 1, Assertions: 5, Failures: 1.

```
> Here is my method code for it:
````bash
    public function ComposeMessageNoValues(AcceptanceTester $I)
    {
        $this->loadHomePage($I);    //  Loads the homepage for us
        
        $I->amGoingTo('Open the modal window to Compose a Message');
        
        $I->click('.btn-success');  //  Compose button
        $I->see(T::t('main', 'Write message'), 'h4.modal-title');

        $I->amGoingTo('Compose a message with no values at all');
        
        $I->click(T::t('main', 'Send'));    //  Send button
        
        $I->see(T::t('main', 'To cannot be blank.'), 'p.help-block.help-block-error');
        $I->see(T::t('main', 'Subject cannot be blank.'), 'p.help-block.help-block-error');
        $I->see(T::t('main', 'Content cannot be blank.'), 'p.help-block.help-block-error');
    }
````
### Details

* Codeception version: 2.2.9
* PHP Version: >5.4
* Operating System: Linux 16.0
* Installation type: Composer
* Suite configuration:

> Acceptance Suite configuration data
```yml

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Yii2:
           part:
              [init, orm]
    config:
        WebDriver:
            url: 'http://localhost/ProjectName/'
            browser: phantomjs
            window_size: 1920x1310
            capabilities:
              webStorageEnabled: true

```
