### ISSUE TITLE
$I->fillfield don't work with Selenium WebDriver

### ISSUE THREAD

**Issue by gonbabence** [Codeception/Codeception#4160]
#### What are you trying to achieve?
I tried an simple fillField, but it quits with exception. I using 
* selenium server 3.3.1
* Codeception 2.2.10.
* Firefox Browser

```bash
[Facebook\WebDriver\Exception\UnrecognizedExceptionException] Expected [object Undefined] undefined to be a string
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
```

```php
<?php
use \AcceptanceTester;

class TestCest
{
    public function testTest(\AcceptanceTester $I)
    {
        $I->amOnPage('/');
        $I->wait(5);
        $I->fillField('#lst-ib', "asdasdasdsdasdas");
        $I->wait(10);
    }
}
```
### Details

* Codeception version: 2.2.10
* PHP Version: 5.6
* Operating System: Windows 10
* Installation type: Composer

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: https://google.com
            browser: firefox
        - \Helper\Acceptance
```

 Please check this because it's a major problem.
