### ISSUE TITLE
Using Acceptance Tester in Laravel Controller

### ISSUE THREAD

**Issue by jkbennemann** [Codeception/Codeception#4162]
#### I want to use the syntax from codeception in my laravel controller to provide users of my app, to create custom test cases.
E.g: the appliaction maintaince multiple wordpress site. Lets assume the user updates a plugin via the dashboard. After that he wants to know whether the site is still working or not. Therefore the user should be able to create custom tests, for his wordpress site.
$I->amOnPage('/shop');
$I->see(...)
...

If the test passes, everything is fine. If not, I want to inform the user via mail or just provide him with different infos, why the site crashed...

### Details

* Codeception version: 
* PHP Version: 5.6
* Operating System: macOS Sierra
* Installation type: Composer
* List of installed packages:
- Symphony
- Laravel
- PHPUnit
- psr
- classpreloader
* Suite configuration:

Codeception.yml
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    include:
      - app/config/*.php
      - app/controllers/*.php
      - app/models/*.php
modules:
    enabled:
        - Db:
           dsn: 'mysql:host=localhost;dbname=my_database'
           user: 'root'
           password: ''
           dump: 'tests/_data/db_test_setup.sql'
           populate: false
           cleanup: true
           reconnect: true
```
Acceptance.suit.yml
```
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: 'http://site.localhost.de'
            auth: ['my_user', 'my_password']
            curl:
                CURLOPT_RETURNTRANSFER: true
            #cookies:
            #    cookie-1:
            #        Name: userName
            #        Value: john.doe
            #    cookie-2:
            #        Name: authToken
            #        Value: 1abcd2345
            #        Domain: subdomain.domain.com
            #        Path: /admin/
            #        Expires: 1292177455
            #        Secure: true
            #        HttpOnly: false
        - \Helper\Acceptance
    config:
          WebDriver:
              url: 'http://site.localhost.de'
              browser: 'chrome'
```
