### ISSUE TITLE
How can I destroy the session set using saveSessionSnapshot(). 

### ISSUE THREAD

**Issue by kjnanda** [Codeception/Codeception#4200]
#### What are you trying to achieve?
I need to destroy the session when the user clicks on logout. 
#### What do you get instead?
The session remains alive even after logout.

This is my login file.

```php
public function loginAsAdmin($wpUserName, $wpPassword)
{
    $I = $this->tester;

    $I->amOnPage('/wp-admin');

    if ($I->loadSessionSnapshot('login')) {
        return;
    }

    $I->seeElement(self::$wpUserNameField);
    $I->fillfield(self::$wpUserNameField, $wpUserName);

    $I->seeElement(self::$wpPasswordField);
    $I->fillfield(self::$wpPasswordField, $wpPassword);

    $I->seeElement(self::$wpSubmitButton);
    $I->click(self::$wpSubmitButton);
    $I->wait(5);

    $I->saveSessionSnapshot('login');
}
```
### Details

* Codeception version: 2.2.10
* PHP Version: 
* Operating System: OS X
* Installation type:  Composer
* List of installed packages (`composer show`) I am Using lucatume/wp-browser package for codeception
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WPWebDriver
    config:
        WPWebDriver:
            host: 'hub-cloud.browserstack.com'
            port: 80
            browser: 'firefox'
            url: ''
            adminUsername: ''
            adminPassword: ''
            adminPath: '/wp-admin'
            capabilities:
               'browserstack.user': ''
               'browserstack.key': ''
              'os': 'OS X'
              'os_version': 'sierra'
              'browserstack.debug': 'true'
```
