### ISSUE TITLE
haveFakeRepository in the Doctrine module doesn't work

### ISSUE THREAD

**Issue by laszlo-karpati** [Codeception/Codeception#4211]
#### What are you trying to achieve?
Use the doctrine module's haveFakeRepository action.

#### What do you get instead?
MyTestCest.php
``` .php
$I->haveFakeRepository('Entity\User', array('findByUsername' => function($username) {  return null; }));
```

console output:
```bash
...
Scenario --
 I have fake repository "AppBundle:UniqueItem",{"getUniqueContentBySlug":"Clo...}
  [Warning] Repository can't be mocked, the EventManager class doesn't have "repositories" property
```

As I see, they removed the "repositories" property from the EntityManager, and made it accessible through the repositoryFactory:
https://github.com/doctrine/doctrine2/commit/7eb744126ba5081ea51441a893dd950046777383

### Details

* Codeception version: 2.2.10
* PHP Version: 5.6
* Operating System: Ubuntu 14.04
* Installation type: Composer
* Suite configuration:

unit.suit.yml:
```yml
# paste suite config here
class_name: UnitTester
modules:
    enabled:
        - \AppBundle\Helper\Unit
        - Symfony2:
            app_path: '../../app'
            var_path: '../../app'
        - Doctrine2:
            depends: Symfony2
            cleanup: true
        - Asserts:
```
