### ISSUE TITLE
Colors missing on functional tests only (Windows)

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4244]
#### What are you trying to achieve?
When running tests with `bin/codecept run`, I get colored output in all suites (Windows PowerShell). But when I run `bin/codecept run functional -c src/AppBundle`, I don't get colors.

### Details

* Codeception version: 2.3.0
* Operating System: Windows 10

codeception.yml:  
```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Recorder:
            delete_successful: true # keep screenshots of successful tests
include:
    - src/*Bundle
```

functional.suite.yml:
```yml
class_name: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: '../../app'
            var_path: '../../app'
        - Doctrine2:
            depends: Symfony
            cleanup: false # Do not roll back the transaction at the end of each test
        - \AppBundle\Helper\Functional
```
