### ISSUE TITLE
Populator dont work properly

### ISSUE THREAD

**Issue by bIbI4k0** [Codeception/Codeception#4247]
#### What are you trying to achieve?
Import data to database via populator dont work properly. If I set option `dump: true` with option `populator: <command>` in config, populator works properly. 
I think problem is here:
`vendor/codeception/codeception/src/Codeception/Lib/DbPopulator.php:84:`
```php
        if (!$this->config['dump']) { // want  'populator' key? 
            codecept_debug("[Db] No dump file found. Skip loading the dump using the populator command.");
            return false;
        }
```

#### What do you get instead?
Data not imported to db.

> Provide console output if related. Use `-vvv` mode for more details.
```
...
  [Db] No dump file found. Skip loading the dump using the populator command.
...
```

### Details

* Codeception version: 2.3.1
* PHP Version: 7
* Operating System: ubuntu 17.04
* Installation type: Composer
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost/
        - \Helper\Acceptance
        - REST:
            depends: PhpBrowser
            url: http:/localhost/rest/
        - Db:
            dsn: 'mysql:host=localhost;dbname=test'
            user: root
            password: root
            populate: true
            populator: 'CURDIR=`pwd` && cd ./_data/db/ && ./importer.py && cd "$CURDIR"'
            cleanup: true
            reconnect: false
```
