### ISSUE TITLE
_reconfigure not working?

### ISSUE THREAD

**Issue by ghost** [Codeception/Codeception#426]
Try to reconfigure the working URL on the fly, but this doesn't seem to work

Here is my acceptance.suite.yml 

```
class_name: WebGuy
modules:
   enabled: [Selenium2,WebHelper]

   config:
      Selenium2:

         url: 'http://localhost'

         browser: firefox
         capabilities:
             unexpectedAlertBehaviour: 'accept'
```

Here is my webHelper.php

```
namespace Codeception\Module;

class WebHelper extends \Codeception\Module
{
     public function switchUrl($url)
  {
    $this->_reconfigure(array('url' => 'http://'.$url));
  }
}
```

Here's my test

```
$I = new WebGuy($scenario);

$I->amOnPage('/'); 

$I->switchUrl("http://www.google.com");

$I->amOnPage('/'); 
```

Then i  run the test

```
php codecept.phar  run --steps tests/acceptance/test1Cept.php 

```

Output is

````Suite acceptance started
Running leden/ledenCept.php
Scenario:
- I am on page "/"
- I switch url "http://www.google.com"
- I am on page "/"

```

*Firefox starts
*goes to /  on localhost
* Should go to google, but doesn't, it reloads localhost

Any ideas?
```
