### ISSUE TITLE
Issue with coverage reports under "One Runner for Multiple Applications"

### ISSUE THREAD

**Issue by piccagliani** [Codeception/Codeception#427]
According to [manual](http://codeception.com/docs/08-Customization#One-Runner%2Cfor%2CMultiple%2CApplications), reports and logs for multiple applications will be merged and stored into log directory that is defined in root configuration.

So, in the following situation, I expect coverage reports would be stored into root <code>log</code> directory.
- codeception.yml

```
include:
  - src/AppA
  - src/AppB
paths:
  log: log
settings:
  colors: false
```
- src/AppA/codeception.yml (excerpt)

```
paths:
    log: tests/_log
coverage:
    enabled: true
```
- src/AppB/codeception.yml (excerpt)

```
paths:
    log: tests/_log
coverage:
    enabled: true
```

But coverage reports were actually stored in <code>src/AppB/tests/_log</code>.
