### ISSUE TITLE
Question: How to use amOnPage() When Webdriver and Rest modules enabled?

### ISSUE THREAD

**Issue by erhankilic** [Codeception/Codeception#4275]
Hello,

I'm trying to use **webdriver** and **rest** modules at the same time because I need to get some data from api and create assertion according to that data.

Here is my suite config;

```
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://website.net
            browser: chrome
            wait: 4
            window_size: maximize
            restart: true
        - REST:
            url: http://api.website.net/api
            depends: PhpBrowser
        - \Helper\Acceptance
env:
    firefox:
         modules:
            config:
                WebDriver:
                    browser: 'firefox'
```

It works, nothing to worry about but how can I send a get request to api? When I use `$I->amOnPage('/v1/for-example');` it tries to go to the main websie, not api.

Thanks.
