### ISSUE TITLE
[AMQP] Infinity channel creation

### ISSUE THREAD

**Issue by Tekill** [Codeception/Codeception#4280]
#### What are you trying to achieve?
Remove infinity channel creation or make it optional. We have about 700+ tests with enabled AMQP module with `cleanup=true` option. When we cleanup all queues before test module send one request per queue. Every request create new channel and if you have a lot of queues (~20) it will create 14 000+ active channels in RAM memory. These channels die only after execution all test so we have huge memory overhead and CPU usage.

#### What do you get instead?
New channel per method call, 20 000+ active channels in RAM memory, huge CPU usage. When the RabbitMQ Server breaks memory threshold, raises a memory alarm and blocks all connections that are publishing messages.  https://www.rabbitmq.com/memory.html

### Details

* Codeception version: 2.2
* PHP Version: 7.1
* Operating System: Ubuntu 16.04, RabbitMQ 3.6.9
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
modules:
         enabled:
             - AMQP:
                 host: 'localhost'
                 port: '5672'
                 username: 'guest'
                 password: 'guest'
                 vhost: '/'
                 queues: 
                     - one
                     - two
                     ...
                     - twenty
```
