### ISSUE TITLE
Empty response using SOAP with Laravel5

### ISSUE THREAD

**Issue by brezzhnev** [Codeception/Codeception#4288]
#### What are you trying to achieve?

I'm trying to send a request to SOAP service. 

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 I send soap request "PerformTransaction"
  [Request] <soapenv:Envelope xmlns:ns="" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"></soapenv:Header><soapenv:Body xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><ns:PerformTransaction></ns:PerformTransaction></soapenv:Body></soapenv:Envelope>
  [Response] 
 PASSED 
```
> Provide test source code if related

```php
public function PerformTransaction(ApiTester $I)
{
    $I->sendSoapRequest('PerformTransaction');
}
```
### Details

* Codeception version: 2.2.11
* PHP Version: 7.1.5
* Operating System: Linux
* Installation type: Composer
* Suite configuration:

```yml
class_name: ApiTester
modules:
    enabled:
        - \Helper\Api
        - Asserts
        - Db
        - REST:
            depends: Laravel5
        - SOAP:
            endpoint: http://example.local/v1/gateways/test
            depends: Laravel5
        - Laravel5:
            environment_file: .env.testing
            cleanup: false
```
