### ISSUE TITLE
HTTP Auth & Password with non-URL-safe characters

### ISSUE THREAD

**Issue by adimit** [Codeception/Codeception#4289]
#### What are you trying to achieve?

Test a site behind HTTP Auth. The password contains special characters, like `!`, `?`, `@`, etc.

#### What do you get instead?

>  `[InvalidArgumentException] Unable to parse URI: https://user:password!?@myurl.com`

Settings in `.yml`:

```
  local: # don't modify environment
  stage:
    modules:
      config:
        WebDriver:
          url: 'https://user:password!?@myurl.com'
```

### Details

* Codeception version: 2.3.0
* PHP Version: 5.6
* Operating System: Linux
* Installation type: Composer
