### ISSUE TITLE
Can not start codeception with chrome 59 in headless mode

### ISSUE THREAD

**Issue by johndoejdg** [Codeception/Codeception#4312]
#### What are you trying to achieve?
I trying start codeception with chrome=59.0.3071.86 in headless mode by providing in args 'headless':

```
tests/acceptance.suite.yml:
      - WebDriver:
          url: https://crm.test
          browser: chrome
          window_size: maximize
          clear_cookies: false
          capabilities:
              chromeOptions:
                  prefs:
                    download.default_directory: '/var/www/crm/tests/_data/market_documents'
                  args:
                    ['disable-infobars', 'headless', 'disable-gpu']
```

#### What do you get instead?
Tests could not start and fall down with error:
                                                                                                                                                                                     

>   [Facebook\WebDriver\Exception\UnknownServerException] unknown error: cannot get automation extension
> from unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html
>   (Session info: headless chrome=59.0.3071.86)
>   (Driver info: chromedriver=2.29,platform=Linux 4.10.13-1-ARCH x86_64) (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 10.01 seconds
> Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
> System info: host: 'test_machine', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.13-1-ARCH', java.version: '1.8.0_121'
> Driver info: org.openqa.selenium.chrome.ChromeDriver
> Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29, userDataDir=/tmp/.org.chromium.Chromium.FgXN4d}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.86, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
> Session ID: 588174371e59db7c773f8d7460987195  

```bash
php -dxdebug.remote_enable=1 -dxdebug.remote_autostart=1 -dxdebug.idekey=PHPStorm vendor/bin/codecept run -f --steps acceptance Clients
```
### Details

* Codeception version: 2.3.2
* PHP Version: 7.1.5  x86_64
* Operating System: Linux test_machine 4.10.13-1-ARCH
* Installation type: Composer
* List of installed packages:

>     "codeception/codeception": "^2.3.2",
>     "codeception/verify": "~0.3.3",

* Suite configuration:

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
      - Db:
          cleanup: false
          dsn: 'mysql:host=localhost;dbname=db_test'
          password: 'PASSWORD'
          populate: false
          user: 'root'
      - WebDriver:
          url: https://crm.test
          browser: chrome
          window_size: maximize
          clear_cookies: false
          capabilities:
              chromeOptions:
                  prefs:
                    download.default_directory: '/var/www/app/tests/_data/downloads'
                  args:
                    ['disable-infobars', 'headless', 'disable-gpu']
      - \Helper\Acceptance
      - Asserts
      - Yii2:
          configFile: 'config/test.php'
          part: ORM
          cleanup: false # don't wrap test in transaction
          entryScript: 'index-dev.php'
```

**Comment by Naktibalda** [comment]
It is an issue of chromedriver,
I found that you have to set useAutomationExtension capability to false.
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1754
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1749#c8

**Comment by JacquesJahnichen** [comment]
Hello, 

Have you success to use codeception with chrome 'headless' ? If yes do you use your suite.yml like that ? 

```
    driver-chrome:
        modules:
            config:
              WebDriver:
                  browser: chrome
                  capabilities:
                    useAutomationExtension : false,
                    args:
                      ['disable-infobars', 'headless', 'disable-gpu']
```

And do you run selenium server with chrome driver linux ? 

`java -Dwebdriver.chrome.driver="chromedriver-linux64" -jar selenium-server-standalone-3.4.0.jar`

**Comment by mirao** [comment]
Headless mode works for me with Linux Chrome 59 and chromedriver 2.29/2.30, but only if I disable the webdriver option `window_size: maximize`.
The capability `useAutomationExtension : false` doesn't help

**Comment by johndoejdg** [comment]
@mirao your solution works. Just deleted window_size: maximize.

Working config:
```
class_name: AcceptanceTester
modules:
    enabled:
      - Db:
          cleanup: false
          dsn: 'mysql:host=localhost;dbname=crm_test'
          password: 'qweewq'
          populate: false
          user: 'root'
      - WebDriver:
          url: https://crm.test
          browser: chrome
          clear_cookies: false
          capabilities:
              chromeOptions:
                  prefs:
                    download.default_directory: '/var/www/crm/tests/_data/market_documents'
                  args:
                    ['disable-infobars', 'headless', 'disable-gpu', 'useAutomationExtension=false']
      - \Helper\Acceptance
      - Asserts
      - Yii2:
          configFile: 'config/test.php'
          part: ORM
          cleanup: false # don't wrap test in transaction
          entryScript: 'index-dev.php'
```
