### ISSUE TITLE
No-exit Option is ignored when deprecation warnings happen.

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [Codeception/Codeception#4316]
#### What are you trying to achieve?
I ran codeception using jenkins, the tests pass AND I am using the --no-exit option, so the exit code should be 0. 
 
#### What do you get instead?
but the exit code is 1, leading to a failed build. Reason seems to be the deprecation notices - because if I remove this module from my acceptance.suite.yml
```yml
        - Doctrine2:
            depends: Symfony
            populate: true
            cleanup: true
```
deprecation notice and exit code get back to normal.
(Without this deprecation notices I get the exit code of 1 only when I omit the --no-exit option AND have at least one failing test. As it should be.)

This is the end of the output of the test run:
```bash
Time: 8.92 seconds, Memory: 32.00MB

OK (3 tests, 7 assertions)

Remaining deprecation notices (6)

Setting the "doctrine" pre-defined service is deprecated since Symfony 3.3 and won't be supported anymore in Symfony 4.0: 3x
    3x in Application::run from Codeception

Setting the "doctrine.orm.default_entity_manager" pre-defined service is deprecated since Symfony 3.3 and won't be supported anymore in Symfony 4.0: 3x
    3x in Application::run from Codeception
```

### Details

* Codeception version: 2.2.3
* PHP Version: 7.1.5
* Operating System: Windows 7
* Installation type: Composer
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost/reactex/web/app.php
        - \Helper\Acceptance
        - Doctrine2:
            depends: Symfony
            populate: true
            cleanup: true
        - REST:
            url: /
            depends: PhpBrowser
            part: Json
    config:
        - Symfony:
            var_path: 'var'
            app_path: 'app'
```
