### ISSUE TITLE
Firefox - failed to start browser: permission denied

### ISSUE THREAD

**Issue by jin78** [Codeception/Codeception#4321]
I tried to run acceptance tests using Selenium/Firefox.

Error message when trying to run all acceptance tests: 
Failed to start browser /usr/local/bin/firefox: permission denied (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'ene-natl-pc-139.natl.enercoop.org', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-0.bpo.2-amd64', java.version: '1.8.0_131'
Driver info: driver.version: FirefoxDriver

### Details

* Codeception version: 2.2.2.9
* PHP Version: 5.6
* Operating System: Debian 8.8 [custom]
* Installation type: Composer
- **Drivers installed:** gecko and chrome in **__"/usr/local/bin"__**
- Firefox install locations:
=> debian default: _/usr/bin/firefox_ ( which is a ESR version  )
=> latest version manually installed: /usr/local/bin/firefox/firefox where the last firefox is the actual executable. **/usr/local/bin/firefox/ permissions on directory and subdirctories and files: 777**

So lets break it down:
- Is selenium running? Yes
- Does firefox run when opening it with the terminal using '/usr/local/bin/firefox'? Yes
- Is the issue related to acceptance tests being run? No. These tests run correctly using Chrome driver.

```yml
## Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
             url: https://some-url.com/
             browser: firefox
```
Now - based on the error message: "Failed to start browser /usr/local/bin/firefox" - it seems like Codeception does not point to the right place since "/usr/local/bin/firefox/" is a directory and not the actual executable file.

Can we specify a custom absolute path to any given browser in Codeception configugation? If so, how?
