### ISSUE TITLE
REST entry url with Yii 2 module

### ISSUE THREAD

**Issue by nkovacs** [Codeception/Codeception#4332]
#### What are you trying to achieve?

Use the Yii2 module with the REST module.

#### What do you get instead?

```bash
[yii\base\InvalidConfigException] Unable to determine the path info of the current request. 
```
> Provide test source code if related

```php
<?php

$I = new ApiTester($scenario);
$I->sendGET('/v1/auth/token');
```
### Details

* Codeception version: 2.3.3
* PHP Version: 7.0.19-1~dotdeb+8.1 
* Operating System: Debian 8
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - \Helper\Api
        - REST:
            url: /api
            depends: Yii2
            part: Json
    config:
        Yii2:
            configFile: 'codeception/config/functional.php'
            entryUrl: http://web:8080/testweb/index-test.php
```

If I change `url` in REST's config to `/testweb/index-test.php/api` (or even the absolute url), it works, but I don't want to do that.

According to http://codeception.com/docs/modules/Yii2#URL, I should be able to use `$I->sendGET(['/v1/auth/token']);` (it says "for all codeception commands that use url"), but that doesn't work, because the REST module assumes it is a string.
