### ISSUE TITLE
HTML code coverage not generated

### ISSUE THREAD

**Issue by elimentz** [Codeception/Codeception#4336]
#### What are you trying to achieve?
I have a Laravel 5.4 project in which I use CodeCeption to run my unit tests. Tests are running just fine, both unit and functional tests. I also want to generate a code coverage report in HTML but this fails. The code coverage report is generated and printed in console, but no HTML version is generated

```bash
$ vendor/bin/codecept run --coverage-html -vvv
Codeception PHP Testing Framework v2.2.12
Powered by PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

  Rebuilding AcceptanceTester...

Acceptance Tests (0) -----------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Acceptance, Asserts, REST, PhpBrowser, Laravel5
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Rebuilding ApiTester...

Api Tests (0) ------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Api, Asserts, REST, PhpBrowser, Laravel5
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Rebuilding CliTester...

Cli Tests (0) ------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Cli, Asserts, Db, REST, PhpBrowser, Laravel5
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Functional Tests (9) -----------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Functional, Asserts, Db, Laravel5
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# tests go here
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Unit Tests (11) ----------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: \Helper\Unit, Laravel5
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# tests go here
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 12.55 seconds, Memory: 42.25MB

OK (20 tests, 38 assertions)


Code Coverage Report:
  2017-06-17 20:42:12

 Summary:
  Classes: 16.00% (4/25)
  Methods: 11.38% (14/123)
  Lines:    4.45% (54/1214)

\App\Models::User
  Methods:  77.78% ( 7/ 9)   Lines:  87.50% ( 28/ 32)
Remote CodeCoverage reports are not printed to console

```

### Details

* Codeception version: 2.2.12 || c3: 2.0.12
* PHP Version: 5.6.30
* Operating System: ~ubuntu16.04.1+deb.sury.org+1
* Installation type: Composer
* XDebug version: 2.5.4
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        REST:
            depends: PhpBrowser
            url: http://my-url.dev/api
        Laravel5:
            environment_file: .env.testing
coverage:
    enabled: true
    remote: false
    include:
        - app/Console/*
        - app/Http/*
        - app/Models/*
    exclude:
        - app/Console/Kernel.php
        - app/Http/Kernel.php

```
