### ISSUE TITLE
Cannot pass to next page via amOnPage function

### ISSUE THREAD

**Issue by Paintras** [Codeception/Codeception#4350]
Hello,
I'm tying to make order on my page. Everything was working smoothly. I have choosed specific item that i wanted. I have added it to the cart. Moving on in cart by choosing specific transportation and type of payment. but when i moved the section when you have to fill in personal info i've crashed into problem. Clicking on to move to the page that i wanted passes. Than i wrote function amOnPage with argument of page that i wanted and it passes aswell, but when i'm trying to see if element that i want to fill is here it fails and when I try to check if there is an element from previous page it pass. So it's acting like am on page that I was before, even when i clicked on moved forward and wrote amOnPage function. Thank you for all advices.

		$I->click("Pro kluky");
		$I->see("Auta");
		$I->click("Auta");
		$I->click("Traktor Kubota + vlek");
		$I->amOnPage("/traktor-kubota-vlek");
		$I->click("Do košíku");//adding "to the cart"
		//this is making order of specific item
		
		
		$I->amOnPage("/objednavka");
		$I->click("Pokračovat v objednávce");
		$I->amOnpage("/doprava-a-platba");
		$I->seeElement(['xpath' => '//*[@id="payment_for_1003"]/div[2]']);
		$I->click(['xpath' => '//*[@id="payment_for_1003"]/div[2]']); 
		$I->click(['xpath' => '//*[@id="delivery_methods"]/div[1]']);
		$I->click("Pokračovat v objednávce");//this should forward me to the "/dorucovaci-udaje"
		$I->amOnPage('/dorucovaci-udaje');
		$I->seeElement(['xpath'=>'//*[@id="ibod"]/div']);//this should fail but it pass, element is not on page "/dorucovaci udaje"
		$I->seeElement(['xpath' => '//*[@id="email"]']);//this should pass, but it fails

* Codeception version: 2.1
* PHP Version: 7.1.4
* Operating System: Windows 10
* Installation type: Composer
* List of installed packages (`composer show`)
- I am using webception
* Suite configuration:

```yml
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
        - REST
    config:
        REST:
            depends: PhpBrowser
            url: 'https://www.bambule.cz/'
            timeout: 90
            depends: WebHelper
        PhpBrowser:
            url: 'https://www.bambule.cz/'
            curl:
                CURLOPT_RETURNTRANSFER: true
                CURLOPT_FOLLOWLOCATION: true
```
