### ISSUE TITLE
Can't include custom extension

### ISSUE THREAD

**Issue by hger92** [Codeception/Codeception#4354]
#### What are you trying to achieve?
I would like to include my custom extension.
#### What do you get instead?

```bash
Codeception PHP Testing Framework v2.3.2
Powered by PHPUnit 6.1.4 by Sebastian Bergmann and contributors.


  [Codeception\Exception\ConfigurationException]
  Class `Codeception\Extension\Failure` is not defined. Autoload it or include into '_bootstrap.php' file of 'tests' directory


Exception trace:
 () at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/src/Codeception/Subscriber/ExtensionLoader.php:83
 Codeception\Subscriber\ExtensionLoader->bootExtensions() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/src/Codeception/Subscriber/ExtensionLoader.php:40
 Codeception\Subscriber\ExtensionLoader->bootGlobalExtensions() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/src/Codeception/Codecept.php:80
 Codeception\Codecept->__construct() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/src/Codeception/Command/Run.php:295
 Codeception\Command\Run->execute() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/vendor/symfony/console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/src/Codeception/Application.php:103
 Codeception\Application->run() at phar://C:/Users/Gergely/Google Drive/workspace/auto-test-squared/out/Tests/Codeception/codecept.phar/codecept:36
 require_once() at C:\Users\Gergely\Google Drive\workspace\auto-test-squared\out\Tests\Codeception\codecept.phar:7

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]
```
> /tests/_support/Helper/Failure.php

```php
<?php

/**
 * Created by AutoTestSquared
 */

namespace Codeception\Extension;

class Failure extends \Codeception\Extension
{

    public static $events = ["test.fail" => "testFailed", "result.print.after" => "printData"];

    public function testFailed(\Codeception\Event\FailEvent $e) {
		
    }

    public function printData(\Codeception\Event\PrintResultEvent $e) {
		
    }
}
```
> /codeception.yml

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
settings:
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Failure
modules:
    enabled:
        - Asserts
        - Helper\Common
        - PhpBrowser:
            url: BLANK
        - REST:
            url: BLANK
            depends: PhpBrowser

```
> /tests/_bootstrap.php

```php
<?php

include_once __DIR__.'/_support/Helper/Failure.php';
```
### Details

* Codeception version: 2.3.2
* PHP Version: 7.0.10
* Operating System: Windows 10
* Installation type: Phar
