### ISSUE TITLE
Symfony: Set the 'Request Context'

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4356]
Apparently, in functional tests the Twig function `url()` always returns an URL starting with `http://localhost/`. I'm figuring this is because the "Request Context" is missing, as described here: http://symfony.com/doc/current/console/request_context.html

I tried both ways described there:
* `$context = $I->grabService('router')->getContext();` (and so forth) inside a test
* Setting the parameters globally

However, nothing works :-(

**Comment by Naktibalda** [comment]
Do you specify hostname in your tests?

Please provide example of suite configuration and one test.

**Comment by ThomasLandauer** [comment]
```yml
class_name: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: 'app'
            var_path: 'app'
        - Doctrine2:
            depends: Symfony
            cleanup: false # Do not roll back the transaction at the end of each test
        - REST:
            depends: Symfony
        - Asserts
        - \Helper\Functional
```

```php
    public function tryMe (FunctionalTester $I)
    {
        $I->amOnPage('/my-page');
        // ...
    }
```

When I give a full URL `$I->amOnPage('http://www.example.com/my-page');`,  
I get `[ExternalUrlException] Codeception\Module\Symfony can't open external URL`

And when I start the test with `$I->amOnUrl('http://www.example.com');` ,  
I get `[RuntimeException] Call to undefined method FunctionalTester::amOnUrl`

=> So how/where can I specify the hostname?
