### ISSUE TITLE
API data not transferred correctly

### ISSUE THREAD

**Issue by elimentz** [Codeception/Codeception#4365]
#### What are you trying to achieve?
I'm trying to send POST request to a controller in my app. The request is sent correctly, but the HTTP headers and request data are not transmitted correctly, so the test fails

```php
class SalesControllerCest {

    /**
     * @covers \App\Http\Controllers\SalesController::processOrderHook()
     */
    public function testProcessOrderHook(\ApiTester $I)
    {
        $content = '{"order":{"id":2768,"order_number":2768}}';

        $I->haveHttpHeader('X-Wc-Webhook-Signature', 'vflmAP07BGCKdpC4=');
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendPOST('/processOrder', $content);
        $response = $I->grabResponse();

        file_put_contents('tests/_support/error.html', $response);
        dd('done');
    }

}
```

### Source code
```php
class SalesController extends Controller {

    public function processOrderHook(Request $req)
    {
        $body = $req->getContent();
        $signature = $req->header('X-Wc-Webhook-Signature');

        $data = json_decode($body);

        if( !$this->checkSignature($signature, 'FooBar', $body) ) {
            return Response::json( array( 'error' => 'Signature does not match' ) );
        }

        return Response::json( array( 'success' => 'OK' ) );
    }
}
```
### Response
- My signature is empty

I have no idea what I'm doing wrong or how I can fix this...

### Details

* Codeception version: 2.3.3 || c3: 2.0.12
* PHP Version: 5.6.30
* Operating System: ~ubuntu16.04.1+deb.sury.org+1
* Installation type: Composer
* XDebug version: 2.5.4
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        REST:
            depends: PhpBrowser
            url: http://my-url.dev/api
        Laravel5:
            environment_file: .env.testing
coverage:
    enabled: true
    remote: false
    include:
        - app/Console/*
        - app/Http/*
        - app/Models/*
    exclude:
        - app/Console/Kernel.php
        - app/Http/Kernel.php

```
