### ISSUE TITLE
Include “Tests” folder in another folder - RuntimeException 

### ISSUE THREAD

**Issue by JacquesJahnichen** [Codeception/Codeception#4372]
#### What are you trying to achieve?

I try to inclue my "Tests" folder in an "App" folder.

#### What do you get instead?
```
  [RuntimeException]                                                                
  Suite 'App\Tests\acceptance\MYTestCest.php' could not be found
```

#### My codeception.yml

```
actor: Tester
paths:
    tests: App/Tests
    log: App/Tests/_output
    data: App/Tests/_data
    support: App/Tests/_support
    envs: App/Tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```

#### For information its working with no app folder and this codeception.yml

```
actor: Tester
paths:
    tests: Tests
    log: Tests/_output
    data: Tests/_data
    support: Tests/_support
    envs: Tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```

### Details

* Codeception version: 2.3
* PHP Version: 5.6
* Operating System: Linux or Windows
* Installation type: Phar
