### ISSUE TITLE
Web driver error when running Codeception from Windows 7

### ISSUE THREAD

**Issue by mayooran99** [Codeception/Codeception#4408]
I am running my codeception acceptance test in a Windows 7 machine which is causing the below mentioned issue.

```
Signature: somethingSearchCept
Test: tests\acceptance\test\tstCases_somethingSearch\somethingSearchCept.php
Scenario --
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set

  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into 'D:\Training\codeception\tests/_out
put\' dir
 ERROR

  /
 Codeception\Test\Cept: test
   I am on page "/"
  [GET] https://www.google.com/
PHP Fatal error:  Call to a member function get() on null in phar://D:/Training/
codeception/codecept.phar/src/Codeception/Module/WebDriver.php on line 729

Fatal error: Call to a member function get() on null in phar://D:/Training/codec
eption/codecept.phar/src/Codeception/Module/WebDriver.php on line 729



FATAL ERROR. TESTS NOT FINISHED.
Call to a member function get() on null
in phar://D:/Training/codeception/codecept.phar/src/Codeception/Module/WebDriver
.php:729
```
this is the error on debug mode

When I run it from a Windows 10 machine, it runs fine and executes the acceptance tests. Below is the configuration yml I am having.

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed`
```
The Selenium web driver version I am using is 3.4.0. PHP version is 5.6. I have downloaded the latest chrome driver version 2.30. What am I doing wrong here? Any help would be much appreciated.
