### ISSUE TITLE
Issue With Coverage

### ISSUE THREAD

**Issue by Fenikkusu** [Codeception/Codeception#4409]
I'm trying to run code coverage on a project but am getting an odd outcome. If I run the tests using a wildcard include, I end up with lines being ignored that are not marked as such. If I run it manually specifying each file (only two atm), It'll properly mark some lines properly as not covered. However, to make it further curious, I have to enable the show_uncovered flag to actually show all uncovered files.

In hindsight, I am presuming that 'show_uncovered' must be enabled for it to actually flag uncovered lines in uncovered methods. I assumed that the flag was more to enable coverage of files that had no tests.

Regardless of show_uncovered, I'm unable to understand why using the wildcard fails while direct works.

SS1
![ss1](https://user-images.githubusercontent.com/5033618/28400457-3c50767a-6ce1-11e7-9e44-dff0dabd069c.png)

```yml
settings:
    bootstrap: _bootstrap.php
coverage:
    enabled: true
    show_uncovered: true
    whitelist:
        include:
            #- src/*.php
            - src/WebToken/Firebase.php
            - src/WebToken/AbstractToken.php
        exclude:
            - src/phalcon_bootstrap.php
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
actor: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```
SS2
![ss2](https://user-images.githubusercontent.com/5033618/28400456-3c50560e-6ce1-11e7-8da2-8b40e4ca2b23.png)
```yml
settings:
    bootstrap: _bootstrap.php
coverage:
    enabled: true
    show_uncovered: true
    whitelist:
        include:
            - src/*.php
            #- src/WebToken/Firebase.php
            #- src/WebToken/AbstractToken.php
        exclude:
            - src/phalcon_bootstrap.php
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
actor: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed

```
