### ISSUE TITLE
use other namespace models error

### ISSUE THREAD

**Issue by uncode** [Codeception/Codeception#4410]
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 Test  tests/unit/ExampleTest.php:testSomeFeature
                                             
  [Error] Class 'app\models\User' not found  
                                             
#1  ExampleTest->testSomeFeature
#2  phar:///usr/local/bin/codecept/codecept:36
#3  /usr/local/bin/codecept:7
```
> Provide test source code if related

```php
class ExampleTest extends \Codeception\Test\Unit{
...
    public function testSomeFeature()
    {
        $user = new \app\models\User;
    }
}
```
### Details

* Codeception version: Codeception 2.3.4
* PHP Version: PHP 7.1.6 (cli) (built: Jun 23 2017 08:42:14) ( NTS )
* Operating System: MacOs 10.12.5 (16F73)
* Installation type: composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
 $cat unit.suite.yml 
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests.

actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit

```
