### ISSUE TITLE
HTML Report wrong steps/substeps nesting

### ISSUE THREAD

**Issue by eramahatra** [Codeception/Codeception#4413]
#### What are you trying to achieve?
When using webdrive, I want my steps to be repeated in my HTML report anytime i run the test.
#### What do you get instead?
The html report instead shows only my step once, even if i repeat it in the same suite.
So on for the substeps which then are nested in the wrong steps !

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# codecept run acceptance --html
```
> Provide test source code if related

```php
$I->amDoingSomething($a);
$I->amDoingAnotherThing($b);
$I->comment("this line appears at end of report but it should be in the middle");
$I->amDoingSomething($c);
$I->amDoingAnotherThing($d);
```
### Details

* Codeception version: 
* PHP Version: 2.3.4
* Operating System: ubuntu
* Installation type: Phar
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - AcceptanceHelper
        - Asserts
        - WebDriver:
            port: 4444
            browser: chrome
            url:
            host: localhost
```
