### ISSUE TITLE
Recorder does not produce index file and new record

### ISSUE THREAD

**Issue by Paintras** [Codeception/Codeception#4429]
Hello guys,
I have started using recorder extension because of using PhantomJS. In my first project it worked well, but than I started new one in new folder and now it makes screen, but do not generate index.html file so I cannot play slideshow. Also how the records works ? It create one correct record and than it does not generate new one for the same test and only makes two screenshot.  Thank you for optional help.
Here is config:

codeception.yml:
```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Recorder
 
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```

acceptance.suite.yml:
```yml
class_name: AcceptanceTester

modules:
    enabled:
        - WebDriver
        
config:
        WebDriver:
            url: 'http://bambule.cz'
            browser: 'chrome'
            window_size: maximize
            capabilities: # uncomment this to run headless
                chromeOptions:
                  args: ["--headless", "--disable-gpu"]
                  binary: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'
            wait: 1.5
            curl:
                CURLOPT_RETURNTRANSFER: true
                CURLOPT_FOLLOWLOCATION: true

                
extensions:
     enabled:
          - Codeception\Extension\Recorder:
            delete_successful: false
```
