### ISSUE TITLE
Exception is thrown when I call switchToPreviousTab() method with basic configuration

### ISSUE THREAD

**Issue by Paintras** [Codeception/Codeception#4438]
Hello guys,
here are some details of my problem. Thank you for all optional help. It means alot.

#### What are you trying to achieve?
I am trying to call method switchToPreviousTab() from Webdriver module

#### What do you get instead?
When it came to the method. It throws me exception
[RuntimeException] Call to undefined method AcceptanceTester::switchToPreviousTab

> Provide test source code if related
```<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');
$I->amOnPage("/");
$I->click("body > header > div > nav > ul:nth-child(1) > li:nth-child(2) > a");//opens up second tab
$I->wait(3);
$I->switchToPreviousTab();
$I->wait(3);
```
### Details
When I am checking fail screenshot it show me that it actually switches to previous tab before throwing exception.  I created new codeception project and this was my first test when I came to the problem. I have checked acceptanceTesters action and there was no method implementing this method. I was trying other methods from webdriver module and none of them had this issue.

* Codeception version: 2.1.11
* PHP Version: 5
* Operating System: Windows 10
* Installation type: Phar
* Suite configuration:
class_name: AcceptanceTester

modules:
    enabled:
        - WebDriver
        
    config:
        WebDriver:
            url: 'http://asko-cz-branch-redesign.linux-dev.cz/'
            browser: 'chrome'
            window_size: maximize
            # capabilities: # uncomment this to run headless
                # chromeOptions:
                  # args: ["--headless", "--disable-gpu"]
                  # binary: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'
            wait: 1.5
# extensions:
     # enabled:
          # - Codeception\Extension\Recorder:
            # delete_successful: false
```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
    log: tests/_output
    helpers: tests/_support/Helper
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M

extensions:
    enabled:
        - Codeception\Extension\RunFailed

```
