### ISSUE TITLE
Yii2 cleanup does not work

### ISSUE THREAD

**Issue by csabike2** [Codeception/Codeception#4445]
#### What are you trying to achieve?
I would clean up my database after each test.

#### What do you get instead?
Nothing. All test data stays in database

### Details

* Codeception version: 2.3.3
* PHP Version: PHP 7.0.18
* Operating System: Vagrant (Ubuntu 16.04)
* Installation type: Comes with Yii2 Advanced template
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://phoenix.vagrant.test/
            browser: chrome
            host: 192.168.85.1
            capabilities:
              chromeOptions:
                args:
                  - start-fullscreen
        - Yii2:
            part: [orm, fixtures]
            transaction: false # don't wrap test in transaction
            cleanup: true # don't cleanup the fixtures
            entryScript: index-test.php
        - Db:
            dsn: 'mysql:host=127.0.0.1;dbname=phoenix_test'
            user: 'root'
            password: ''
            dump: 'tests/_data/phoenix_test_dump.sql'
            populate: true # run populator before all tests
            cleanup: true # run populator before each test
            populator: 'mysql -u $user -h $host $dbname < $dump'
```
