### ISSUE TITLE
The PHPUnit_Util_Filter class override doesn't works with PHPUnit 6 with \PHPUnit\Util\Filter

### ISSUE THREAD

**Issue by drudoi** [Codeception/Codeception#4488]
#### What are you trying to achieve?
See what PHP notice or warning was triggered in the application.

#### What do you get instead?
We've updated PHPUnit from 5 to 6, and now when functional tests with PHPBrowser module are run the next is seen:
```bash
PHP Fatal error:  Method PHPUnit\Framework\Exception::__toString() must not throw an exception, caught PHPUnit\Framework\Exception: Undefined index: SCRIPT_NAME in /var/www/html/app/config/app.php on line 0



FATAL ERROR. TESTS NOT FINISHED.
Method PHPUnit\Framework\Exception::__toString() must not throw an exception, caught PHPUnit\Framework\Exception: Undefined index: SCRIPT_NAME 
in /var/www/html/app/config/app.php:0
```
instead of PHP notice or warning reporting.

### Synopsis
When PHP notice/warning happens, it is thrown as `\PHPUnit\Framework\Exception` from error handler. If called `__toString` method (e.g. in logger), it calls `\PHPUnit\Util\Filter::getFilteredStackTrace`, which contains string
```php
$script = realpath($GLOBALS['_SERVER']['SCRIPT_NAME']);
```
and `SCRIPT_NAME` is not defined in `$_SERVER` superglobal during PHPBrowser call.

For PHPUnit 5 class `PHPUnit_Util_Filter` is overrided in codeception (`src/Codeception/PHPUnit/Overrides/Filter.php`) and has no such strings, but there is no override for class rename in PHPUnit 6. 

### Details
* Codeception version: 2.3.5
* PHP Version: 7.0.20 (cli) (built: Jul  4 2017 00:52:20) ( NTS )
* Operating System: linux (got on Debian/openSUSI/Arch)
* Installation type: Composer
* List of installed packages (`composer show`)
```bash
# I can't provide whole list of an application dependencies, phpunit/* are:
phpunit/php-code-coverage    5.2.2 
phpunit/php-file-iterator    1.4.2
phpunit/php-text-template    1.2.1
phpunit/php-timer            1.0.9
phpunit/php-token-stream     2.0.1
phpunit/phpunit              6.2.4
phpunit/phpunit-mock-objects 4.0.4
```
* Suite configuration:
```yml
class_name: FunctionalTester
modules:
    enabled:
        - MongoDb:
            dsn: mongodb://mongo:27017/******
            populate: false
            dump_type: mongodump
            dump: tests/_data/dump
        - Phalcon:
            bootstrap: 'app/config/bootstrap.php'
            cleanup: true
            savepoints: true
        - REST:
            depends: Phalcon
            url: 'http://localhost'
        - Asserts
        - \Helper\Functional
```
