### ISSUE TITLE
Lines with both "elseif" and "is_string()" fail to get included in coverage report

### ISSUE THREAD

**Issue by CJDennis** [Codeception/Codeception#4494]
#### What are you trying to achieve?
All valid, executed code should appear in the coverage report.

#### What do you get instead?
In lines such as the following:
```php
    elseif (is_string($value)) {
      return true;
    }
```
only the `return` line is covered, not the `elseif` line. If a space is inserted between `else` and `if`, both lines get covered.
```php
    else if (is_string($value)) {
      return true;
    }
```

See attached demonstration class and Codeception test class for source code.
### Details

* Codeception version: 2.3.5 for PHP 5.4+
* PHP Version: 7.1.7
* Operating System: Windows 10
* Installation type: Phar
* Suite configuration:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    shuffle: true
    colors: true
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    low_limit: 60
    high_limit: 90
    remote: false
    blacklist:
        include:
            - tests/*
```

[is_string.class.php.txt](https://github.com/Codeception/Codeception/files/1290231/is_string.class.php.txt)
[IsStringTest.php.txt](https://github.com/Codeception/Codeception/files/1290232/IsStringTest.php.txt)
