### ISSUE TITLE
Laravel5 - test database not cleaned up between tests

### ISSUE THREAD

**Issue by solshark** [Codeception/Codeception#4504]
#### What are you trying to achieve?
I'm running few tests at once and expect database will be reset and seeded with initial values. My seeder create predefined user with defined email which should be unique. I expect user will be re-created before each test.

#### What do you get instead?
Looks like database not cleaned up:
```bash
/var/www/html # ./vendor/bin/codecept run functional
Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

Functional Tests (2) -------------------------------------------------------------------------------------------------------------------------------------------
✔ DashboardCest: Try to see channels list (0.42s)
E LoginCest: Try login (0.06s)
----------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 1.66 seconds, Memory: 22.00MB

There was 1 error:

---------
1) LoginCest: Try login
 Test  tests/functional/LoginCest.php:tryLogin

  [Illuminate\Database\QueryException] SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.email (SQL: insert into "users" ("email", "password", "name", "updated_at", "created_at") values (***@gmail.com, $***, ***, 2017-09-13 07:29:06, 2017-09-13 07:29:06))
```
### Details

* Codeception version: 2.3.5
* PHP Version: 7.1.9
* Operating System: Alpine Linux 3.4
* Installation type: Composer
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        # add a framework module here
        - Laravel5:
            environment_file: .env.testing
            run_database_migrations: true      # not required to run seeding
            run_database_seeder: true          # required to use this feature
            database_seeder_class: DatabaseSeeder
            cleanup: true
        - \Helper\Functional
```

```php
<?
...
        'sqlite_testing' => [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ],
...
```
