### ISSUE TITLE
seeResponseMatchesJsonType throws PHP exception

### ISSUE THREAD

**Issue by Konzertheld** [Codeception/Codeception#4517]
I am trying to use this code in a Cept:
```
$I->seeResponseMatchesJsonType([
    'id' => 'integer',
    'playerMin' => 'integer',
    'playerMax' => 'integer',
    'ageMin' => 'integer',
    'duration' => 'integer',
    'name' => 'string',
    'publisher' => 'string',
    'feature' => 'string',
    'number' => 'string',
    'numberHuman' => 'string',
    'fund' => 'string',
    'lentTo' => 'string',
    ]);
```

But I receive:

 ```
Test  tests/api/RetrieveGameCept.php
                                                                                                  
  [PHPUnit\Framework\Exception] array_key_exists() expects parameter 2 to be array, string given  
                                                                                                  

Scenario Steps:

 5. $I->seeResponseMatchesJsonType({"id":"integer", "playerMin":"integer","playerMax":"integer","ageMin":"integer","duration":"integer","name":"string","publisher":"string","feature":"string","number":"strin...}) at tests/api/RetrieveGameCept.php:9
```

Other tests (seeResponseContainsJson, seeResponseIsJson) work.

* Codeception version: 2.3.5
* PHP Version: 7.1.9
* Operating System: Arch
* Installation type: Phar
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - REST:
            url: http://localhost/spielenacht/api/
            depends: PhpBrowser
            part: Json
```
Test succeeds when I remove the code cited above. :-(
