### ISSUE TITLE
Remote code coverage is extremely slower than no coverage

### ISSUE THREAD

**Issue by kenjis** [Codeception/Codeception#4524]
#### What are you trying to achieve?

Faster remote code coverage reporting with Codeception/Selenium.

#### What do you get instead?

I set up to get remote code coverge according to <http://codeception.com/docs/11-Codecoverage>.

When I run tests without `--coverage-html`:
> Time: 2.67 minutes, Memory: 12.00MB

When I run tests with `--coverage-html`:
> Time: 49.76 minutes, Memory: 38.00MB

It takes more than 18x time, when I try to get coverage.
Is it normal?

### Details

* Codeception version: 2.3.3
* PHP Version: 5.6.26(remote), 7.0.22(local)
* Operating System: CentOS 6.8(remote), Mac OS X 10.11.6(local)
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# acceptance.suite.yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: https://foo:bar@192.168.0.1/home
            browser: 'chrome'
        - \Helper\Acceptance
coverage:
    c3_url: https://foo:bar@192.168.0.1
    enabled: true
    remote: true
    remote_context_options:
        ssl:
            verify_peer: false
            verify_peer_name: false
    include:
        - application/controllers/*
        ...
    exclude:
        - application/views/*.twig
        ...
```
