### ISSUE TITLE
Parameters for each suite

### ISSUE THREAD

**Issue by verschoof** [Codeception/Codeception#453]
Hi,

I was a bit playing with codeception and saw the `_bootstrap.php` to setup parameters.
If I want to define some parameters to use in my test for my own environment I have to ignore this `_bootstrap.php` file to prevent that I get other settings from another developer.
But is it also possible to define a function in there? If that is possible you want to keep `_bootstrap.php` in version control. so then the `_bootstrap.php` is not the right file to define your parameters.

With parameters I mean to set your local API url (api.loc) for example.

I was thinking to setup the parameters into the `*.suite.yml` files like this:

``` yml
class_name: ApiGuy
modules:
    enabled: [PhpBrowser, REST, ApiHelper, Db]
    config:
        PhpBrowser:
            url: http://api.loc
        REST:
            url: http://api.loc
        Db:
            dsn:      'mysql:host=localhost;dbname=api'
            user:     user
            password: password
            dump:     tests/_data/dump-20130719.sql
            populate: true
            cleanup:  false

parameters:
    apiUrl:         http://api.loc
    key:            secret api key
    format:         JSON
```

I choose for the `*.suite.yml` files because this file is already developer specific. 

And in each test you can do the next to get the parameters:

``` php
$parameters = $this->getParameters();
$apiUrl     = $parameters['apiUrl'];
```

I already have created this local but i'm waiting for feedback before I create a pull request.
