### ISSUE TITLE
Can not use schema when checking database entries on MS SQL

### ISSUE THREAD

**Issue by gzres** [Codeception/Codeception#4542]
#### What are you trying to achieve?
I want to check data from table in different schema instead of default [dbo] using  `seeInDatabase` 

#### What do you get instead?
Error during executing SQL query.

If I use as table name: `account.Note`:
```bash
[PDOException] SQLSTATE[HY000]: General error: 208 Invalid object name 'account.Note'. [208] (severity 16) [(null)]
```

And when I provide table name with schema in this way: [account]. [Note]:
```bash
[PDOException] SQLSTATE[HY000]: General error: 102 Incorrect syntax near '='. [102] (severity 15) [(null)]
```
> Example of using method:

```php
$I->seeInDatabase('[account].[Note]', ['ID' => 1]);
```
### Details

* Codeception version: v2.3.5
* PHP Version: 7.1.8
* Operating System: ubuntu 16.04
* Installation type: Composer
* Suite configuration:

```yml
class_name: ApiTester
modules:
    enabled:
        - Asserts
        - \ApiHelper
        - REST:
            url: http://localhost:8074
            depends: PhpBrowser
        - Db:
            dsn: "dblib:host=xxx.xxx.xxx.xxx;dbname=xxxxxx;charset=utf8"
            user: xxxxxxx
            password: xxxxxxxxx
            dump: 'tests/resources/db/db-schema.sql'
            populate: true # run populator before all tests
```
