### ISSUE TITLE
Running functional test using BDD is too slow

### ISSUE THREAD

**Issue by Cyansilver** [Codeception/Codeception#4551]
#### What are you trying to achieve?

- Run the functional test using gherkin should be fast

#### What do you get instead?
- It's too slow. Only one Scenario in one feature file but it takes ~6s to finish

```bash
vendor/bin/codecept run functional --no-rebuild -v

Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

Functional Tests (1) ----------------------------------------------------------------------------------
Modules: REST, Laravel5, \Helper\Functional, DataFactory
-----------------------------------------------------
✔ create: Happy Path (0.80s)
------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 6.23 seconds, Memory: 43.50Mb

```
### Details

* Codeception version: v2.3.6
* PHP Version: 5.6
* Operating System: centos 7
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - REST:
            depends: Laravel5
        - \Helper\Functional
        - Laravel5:
            environment_file: .env.testing
            cleanup: false
        - DataFactory:
            factories: tests/_support/factories
            depends: Laravel5
```
