### ISSUE TITLE
Incompatible with PHP less than 7

### ISSUE THREAD

**Issue by svdmitrij** [Codeception/Codeception#4553]
#### What are you trying to achieve?

I tried to run codeception.phar in PHP 5.6 (also PHP 5.4 is the same)

#### What do you get instead?

I get the Parse error

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Parse error:  syntax error, unexpected ‘?’ in phar:///home/myname/public_html/codeception/_tools/codeception/codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 845
```
> Provide test source code if related

In the codecept.phar/vendor/phpunit/phpunit/src/Framework/TestCase.php on line 845:
```php
$configurationFilePath = $GLOBALS['__PHPUNIT_CONFIGURATION_FILE'] ?? '';
```
### Details

* Codeception version: 2.3.6
* PHP Version: 4.6.30
* Operating System: CentOS 6, Ubuntu 14.04
* Installation type: Phar
* List of installed packages (symfony/yaml v3.3.9 Symfony Yaml Component)
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
                url: 'http://localhost'
        - \Helper\Acceptance
```
