### ISSUE TITLE
Acceptance tests hangs when test fails in PHP 7.1.9

### ISSUE THREAD

**Issue by mahkali** [Codeception/Codeception#4560]
#### What are you trying to achieve?
I am doing an acceptance test, I am submitting a form, testing if a string is in source.

#### What do you get instead?
The acceptance test hangs when a test fails.

Note: when I reproduce the test in php 5.6 it all works fine.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
SearchCest: Try to search
Signature: SearchCest:tryToSearch
Test: acceptance\SearchCest.php:tryToSearch
Scenario --
 I am going to Search
 I am on page "/search"
  [Request Headers] []
  [Page] /search
  [Response] 302
  [Request Cookies] []
  [Response Headers] {"Date":["Wed, 11 Oct 2017 12:47:23 GMT"],"Server":["Apache/2.4.27 (Win64) OpenSSL/1.0.2l PHP/7.1.9"],"X-Powered-By":["PHP/7.1.9"],"Set-Cookie":["PHPSESSID=pl7gd7ms1smrt828d687peg63j; path=/"],"Expires":["Thu, 19 Nov 1981 08:52:00 GMT"],"Cac
he-Control":["no-store, no-cache, must-revalidate"],"Pragma":["no-cache"],"Location":["http://localhost/wabbit_demo/www/nl/search"],"Content-Length":["4"],"Content-Type":["text/html; charset=UTF-8"]}
  [Redirecting to] http://localhost/wabbit_demo/www/nl/search
  [Page] http://localhost/wabbit_demo/www/nl/search
  [Response] 200
  [Request Cookies] {"PHPSESSID":"pl7gd7ms1smrt828d687peg63j"}
  [Response Headers] {"Date":["Wed, 11 Oct 2017 12:47:23 GMT"],"Server":["Apache/2.4.27 (Win64) OpenSSL/1.0.2l PHP/7.1.9"],"X-Powered-By":["PHP/7.1.9"],"Expires":["Thu, 19 Nov 1981 08:52:00 GMT"],"Cache-Control":["no-store, no-cache, must-revalidate"],"Pragma":[
"no-cache"],"Transfer-Encoding":["chunked"],"Content-Type":["text/html; charset=UTF-8"]}
 I can see in current url "/search"
 I submit form ".search-form",{"q":"email123@tremani.nl","s":"OR","w":1}
  [Uri] http://localhost/wabbit_demo/www/nl/search?q=email123%40tremani.nl&expand=&s=OR&w=1
  [Method] GET
  [Parameters] {"q":"email123@tremani.nl","expand":"","s":"OR","w":1}
  [Request Headers] []
  [Page] http://localhost/wabbit_demo/www/nl/search?q=email123%40tremani.nl&expand=&s=OR&w=1
  [Response] 200
  [Request Cookies] {"PHPSESSID":"pl7gd7ms1smrt828d687peg63j"}
  [Response Headers] {"Date":["Wed, 11 Oct 2017 12:47:23 GMT"],"Server":["Apache/2.4.27 (Win64) OpenSSL/1.0.2l PHP/7.1.9"],"X-Powered-By":["PHP/7.1.9"],"Expires":["Thu, 19 Nov 1981 08:52:00 GMT"],"Cache-Control":["no-store, no-cache, must-revalidate"],"Pragma":[
"no-cache"],"Transfer-Encoding":["chunked"],"Content-Type":["text/html; charset=UTF-8"]}
 I expect Zoeken
 I don't see "Zoeken"
```
> Provide test source code if related

```php
$string =  'email123@tremani.nl';
            $I->amGoingTo('Search');
            $I->amOnPage('/search');
            $I->canSeeInCurrentUrl('/search');
            $I->submitForm('.search-form',
                [
                    'q' =>$string,
                    's' => 'OR',
                    'w' => 1
                ]
            );
            $I->expect('Zoeken');
            $I->dontSee('Zoeken');
```
### Details

* Codeception version: 2.3.6
* PHP Version: 7.1.9
* Operating System: Windows 10 Pro
* Installation type: Composer 
* List of installed packages (`composer show`)
* Suite configuration:

codeception.yml
```yml
paths:
    tests: .
    output: ./_output
    data: ./_data
    support: ./_support
settings:
    bootstrap: ./_bootstrap.php
actor_suffix: Tester
coverage:
    enabled: true
    low_limit: 40
    high_limit: 80
    include:
        - ../components/*
        - ../models/*
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```

acceptance.yml
```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost/wabbit_demo/www/index-test.php
        - \Helper\Acceptance
```

**Comment by Naktibalda** [comment]
Does Codeception hang after any failed assertion or after this particular one only?

**Comment by mahkali** [comment]
In my case, after any assertion that fails

**Comment by mahkali** [comment]
It seems that a composer update fixed it. Unsure what the problem was, but it might have to do with PhpUnit 6.4.1 to 6.4.3. Thank you :)

**Comment by mahkali** [comment]
Unfortunately it still hangs, I came in a situation where all my tests passed so I assumed it was fixed. This issue is not resolved.

Please find attached my composer.lock. (saved as .txt) I stripped the private repo's for your convenience.

[composer.txt](https://github.com/Codeception/Codeception/files/1387909/composer.txt)

**Comment by danielbanshee** [comment]
Same problem here on  a macbook running high sierra. Codeception hangs on EVERY acceptance test which fails (e.g. if I set a selector which is not there).
Thanks for your help!

**Comment by snoopdoc1972** [comment]
Now logged in with my new github account. The previous ghost entry is mine.... It would be great if this bug is fixed... please tell me if I can help.

**Comment by Naktibalda** [comment]
Could you do some function tracing or debugging with xdebug to see on what function call it gets stuck?

Are you using PhpBrowser too or a WebDriver?

**Comment by snoopdoc1972** [comment]
I use WebDriver. How can I do function tracing?

**Comment by Naktibalda** [comment]
The common thing in failure handling of PhpBrowser and WebDriver is that they save page source to file. I wonder if it could be a fault of file_put_contents.
Does Codeception get stuck if a method of another module or helper class fail?

**Comment by snoopdoc1972** [comment]
Hmm... I dont know. I am really new to codeception. I just tried a little acceptance test, which was really easy to config and it works like a charm if there is no failure. How can we test this? 

This is acceptance.suite.yml:
```yml
actor: AcceptanceTester
extensions:
    enabled:
        - Codeception\Extension\RunProcess:
            0: java -Dwebdriver.chrome.driver=./tests/tools/chromedriver -jar ./tests/tools/selenium-server-standalone.jar
            sleep: 2
modules:
    enabled:
        - WebDriver
        - \Helper\Acceptance
    config:
        WebDriver:
            url: 'http://localpanathletica.de:80'
            browser: chrome
            window_size: 1024x768
            clear_cookies: true
            start: false
```

This is codeception.yml:
```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: I
extensions:
#    enabled: (tried this enabled and disabled)
#        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    include:
        - src/*
settings:
    colors: false
```

**Comment by snoopdoc1972** [comment]
This is acceptance.php in Helper folder:
```php
<?php
namespace Helper;

// here you can define custom actions
// all public methods declared in helper class will be available in $I

class Acceptance extends \Codeception\Module
{

    public function startBrowser()
    {
        $this->getModule('WebDriver')->_initializeSession();
    }

    public function changeBrowser($browserName)
    {
        $this->getModule('WebDriver')->_restart(['browser' => $browser]);
    }

    public function closeBrowser()
    {
        $this->getModule('WebDriver')->_closeSession();
    }

}

```

And this is a first test: FirstCest.php
```php
<?php


class FirstCest
{
    public function _before(AcceptanceTester $I)
    {

        $I->startBrowser();
    }

    public function _after(AcceptanceTester $I)
    {

        $I->closeBrowser();

    }

    // tests
    public function tryToTest(AcceptanceTester $I)
    {


        $I->amOnUrl('http://localpanathletica.de/home');

        $I->see('REGISTRIERE');
        $I->see('ANMELDEN');

        $I->click('#linkloginlogout');
        $I->fillField(
            '#email_1',
            'ade72@test.local'
        );
        $I->fillField(
            '#passwort_1',
            '1234'
        );
        $I->click('submit');

        $I->see('Hier ist Deine Hauptseite, ade72');
        $I->canSee('ABMELDEN');

        //the following selector is NOT in the code, so this should raise a failure!
        $I->seeElementInDOM("linkloginlogouti");


    }
}

```

**Comment by snoopdoc1972** [comment]
If I change the last selector name from the non-existing "linkloginlogouti" to the existing "linkloginlogout" (yes, I just added an i at the end of the name... :-) ) it works without fail.

**Comment by Naktibalda** [comment]
Could you do some simple debugging?

Please open Codeception/Module/WebDriver.php file, find _failed method and try putting die(); in various places. Does Codeception hang or die when you run a failing test? Try to identify the function call which separates dies from hangs.

**Comment by snoopdoc1972** [comment]
Hi Naktibalda, I think I found location of the problem:

The next finishes with with exit code 0:

```php
public function _failed(TestInterface $test, $fail)
    {
        $this->debugWebDriverLogs($test);
        $filename = preg_replace('~\W~', '.', Descriptor::getTestSignature($test));
        $outputDir = codecept_output_dir();
        die;
        $this->_saveScreenshot($report = $outputDir . mb_strcut($filename, 0, 245, 'utf-8') . '.fail.png');
        $test->getMetadata()->addReport('png', $report);
        $this->_savePageSource($report = $outputDir . mb_strcut($filename, 0, 244, 'utf-8') . '.fail.html');
        $test->getMetadata()->addReport('html', $report);
        $this->debug("Screenshot and page source were saved into '$outputDir' dir");
    }
```

Putting the die; after $this->_saveScreenshot(...) will make coedecption hang:
```php
public function _failed(TestInterface $test, $fail)
    {
        $this->debugWebDriverLogs($test);
        $filename = preg_replace('~\W~', '.', Descriptor::getTestSignature($test));
        $outputDir = codecept_output_dir();
        $this->_saveScreenshot($report = $outputDir . mb_strcut($filename, 0, 245, 'utf-8') . '.fail.png');
        die;
        $test->getMetadata()->addReport('png', $report);
        $this->_savePageSource($report = $outputDir . mb_strcut($filename, 0, 244, 'utf-8') . '.fail.html');
        $test->getMetadata()->addReport('html', $report);
        $this->debug("Screenshot and page source were saved into '$outputDir' dir");
    }
````

When I dived into _this->saveScreenshot, I went deeper into $this->webDriver->takeScreenshot function; the die; inside before the call of $screenshot=$this->execute... brought a real die on a failing test:
```php
public function takeScreenshot($save_as = NULL)
    {

        die;
        $screenshot = $this->execute(DriverCommand::SCREENSHOT);
        if ($save_as) {
            file_put_contents(
                $save_as,
                $screenshot
            );
        }

        return $screenshot;
    }
````
Putting the die; after this line, codeception hangs:
```php
public function takeScreenshot($save_as = NULL)
    {


        $screenshot = $this->execute(DriverCommand::SCREENSHOT);
        die;
        if ($save_as) {
            file_put_contents(
                $save_as,
                $screenshot
            );
        }

        return $screenshot;
    }
```

So THIS is the line of code which make the test run hang:
```php
$screenshot = $this->execute(DriverCommand::SCREENSHOT);
```
..inside of public function takeScreenshot.

I use the newest webdriver for mac 64 bit.

I hope this helps!

**Comment by Naktibalda** [comment]
This doesn't explain original issue which was reported against PhpBrowser.

If execute screenshot hangs, it is probably a fault of chromedriver, please run the same test with Firefox.

How long did the longest "hang" take? There should be a curl timeout. I don't remember what it is, but I think that it should be 30 seconds.

**Comment by snoopdoc1972** [comment]
It does not stop, I waiting for about 15 minutes....

**Comment by snoopdoc1972** [comment]
Firefox and geckodriver was a good idea - working. :-) So.... what do you recommend now: Waiting for a chromedriver update? Do you use friefox or chrome for development in general if I may ask?

**Comment by snoopdoc1972** [comment]
Oh.. I was too fast.... now I get another error: Undefined index: ELEMENT.
Why is that so complicated?

**Comment by snoopdoc1972** [comment]
When I use geckodriver, I have another strange error:

```php
$I->amOnUrl('http://localpanathletica.de/home');

        $I->see('REGISTRIERE');
        $I->see('ANMELDEN');
```

Above runs fine, no errors (as it should be).
If I add a click I get the error: 'Failed asserting that on page /home'. Why that?

**Comment by snoopdoc1972** [comment]
I get more errors with firefox than with chrome.... chromedriver has only this one problem. That is definitely too complicated for writing tests.... too much time for configuration for me.

**Comment by Naktibalda** [comment]
I don't use WebDriver at work, I only use it when I try to reproduce or fix some reported bug in Codeception. 

Here is a similar bug reported for headless chrome: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1845
Also this: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1871

**Comment by snoopdoc1972** [comment]
I found another strange behaviour: When I start selenium using the RunProcess in acceptance.suite.yml, I got the errors I told you before (not stopping on errors, hanging). My acceptance.suite.yml is this:
```yml
actor: AcceptanceTester
extensions:
    enabled:
        - Codeception\Extension\RunProcess:
           0: java -Dwebdriver.chrome.driver=./tests/tools/chromedriver -jar ./tests/tools/selenium-server-standalone.jar
           sleep: 3
modules:
    enabled:
        - WebDriver
        - \Helper\Acceptance
    config:
        WebDriver:
            url: 'http://localpanathletica.de:80'
            browser: chromedriver
```

When I run the line
```bash
java -Dwebdriver.chrome.driver=./tests/tools/chromedriver -jar ./tests/tools/selenium-server-standalone.jar
```
directly in my terminal command line, it works.... codeception stops at failures and shows me the error.
Maybe it has to do with the RunProcess?
