### ISSUE TITLE
Call to undefined method Codeception\Lib\Connector\Laravel5::setAuth()

### ISSUE THREAD

**Issue by joelwmale** [Codeception/Codeception#4565]
#### What are you trying to achieve?

Test my API on Laravel 5.5

#### What do you get instead?

The error:

`Call to undefined method Codeception\Lib\Connector\Laravel5::setAuth()`

```
1) TeamAttendanceTest: Get ajax team attendance
 Test  tests/api/TeamAttendanceTest.php:testGetAjaxTeamAttendance

  [Error] Call to undefined method Codeception\Lib\Connector\Laravel5::setAuth()

#1  Codeception\Module\REST->amDigestAuthenticated
#2  /Users/joel/Code/cms/tests/_support/_generated/ApiTesterActions.php:227
#3  /Users/joel/Code/cms/tests/api/TeamAttendanceTest.php:24
#4  TeamAttendanceTest->testGetAjaxTeamAttendance
```
> Provide test source code if related

```
        $i = $this->tester;
        $i->wantTo('Get team attendance');
        $i->amDigestAuthenticated('user@user.com', 'abc123');
        $i->haveHttpHeader('Content-Type', 'application/x-www-form-urlencoded');
        $i->sendGET('/teams/team-attendance');
        $i->seeResponseCodeIs(\Codeception\Util\HttpCode::OK); // 200
        $i->seeResponseIsJson();
        $i->seeResponseContains('{"result":"ok"}');
```
### Details

* Codeception version: 2.3.6
* PHP Version: 7.1.8
* Operating System: MacOS High Sierra
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: ApiTester
modules:
    enabled:
        - REST:
            url: /api
            depends: Laravel5
        - \Helper\Api
    config:
        - Laravel5:
            environment_file: .env
```

### More information

My Laravel API uses the auth middleware using a session, instead of a token, but the above test returns the above error of undefined method.
