### ISSUE TITLE
Cant use $I->wait() and $I->amLoggedInAs() in same testcase

### ISSUE THREAD

**Issue by piliugin** [Codeception/Codeception#4571]
#### What are you trying to achieve?
I try to use both functions `$I->wait()` and `$I->amLoggedInAs()` in acceptance test
#### What do you get instead?
I tried enable both modules (WebDriver and Yii2)
```yml
actor: AcceptanceTester
modules:
    enabled:
        - Yii2
        - WebDriver
```
And got error while run acceptance test:
```bash
 [Codeception\Exception\ModuleConflictException]                                                      
  Yii2 module conflicts with WebDriver                                                                 
                                                                                                       
  --                                                                                                   
  This usually happens when you enable two modules with the same actions but with different backends.  
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one suite,                    
  as they implement similar methods but use different drivers to execute them.                         
  You can load a part of module (like: ORM) to avoid conflict.
```

There are no error If I set `part` param for Yii2 module:
```yml
actor: AcceptanceTester
modules:
    enabled:
        - Yii2
        - WebDriver
    config:
        Yii2:
            part: [orm, fixtures, email, init]
```
But function `amLoggedInAs` does not present in generated AcceptanceTester.php.

If I set up only Yii2 module in acceptance.suite.yml:
```yml
actor: AcceptanceTester
modules:
    enabled:
        - Yii2
```
I have not function `wait()` in this case, because this is part of WebDriver module.

I tried to solve it by adding `@part init` [here](https://github.com/Codeception/Codeception/blob/d3332831fa87641680c1b5eb2647f68b2b6ec200/src/Codeception/Module/Yii2.php#L275) and adding "init" inside `part` param of Yii2 module.

After that both functions enable in generated AcceptanceTester.php. But this is bad solution because my changes will be overwritten after composer update.

> Provide test source code if related

```php
$I = new AcceptanceTester($scenario);
$I->wantTo('ensure that profile page works properly');

$I->amOnPage(Yii::$app->homeUrl);
$I->click('[href="/profile"]');
$I->wait(1);
$I->see('Authentication');

$I->amLoggedInAs(1);
...
```
### Details

* Codeception version: 2.3.6
* PHP Version: 5.6.31
* Operating System: Debian GNU/Linux 8.8 (jessie)
* Installation type: Composer
