### ISSUE TITLE
Error handles requiers 5 arguments while some Symfony components throws error with 4

### ISSUE THREAD

**Issue by saimaz** [Codeception/Codeception#4574]
By simply running tests I get an exception because of error handle expected more parameters.

Codeception file: https://github.com/Codeception/Codeception/blob/2.3.6/src/Codeception/Subscriber/ErrorHandler.php#L59

Symfony file where it throws an error:
https://github.com/symfony/symfony/blob/v3.3.10/src/Symfony/Component/Translation/Loader/YamlFileLoader.php#L45

Most likely it will be fixed in 3.4 version of the Symfony. But still, it would be nice to have BC.

#### What do you get instead?
```
  [ArgumentCountError] Too few arguments to function Codeception\Subscriber\ErrorHandler::errorHandler(), 4 passed in .....vendor/symfony/symfony/src/Symfony/Component/Translation/Loader/YamlFileLoader.php on line 45 and exactly 5 expected

```
Details:

* Codeception version: 2.3.6
* PHP Version: 7.1.8
* Operating System: ubuntu
* Installation type: Composer
* List of installed packages: https://paste.laravel.io/7db76453-1f82-4bfa-881b-eb74bedd1d4d
* Suite configuration:

```yml
class_name: ApiTester
modules:
    enabled:
        - REST:
            url: http://localhost:8000
            depends: Symfony
            part: Json
        - Doctrine2:
            depends: Symfony
        - Db:
            dsn: 'mysql:host=127.0.0.1;dbname=eld_test'
            user: 'root'
            password: 'root'
            dump: 'tests/Codecept/_data/dump.sql'
            populate: true
            cleanup: false
            reconnect: true
        - Asserts
        - \Helper\Api
    config:
        Symfony:
            app_path: 'app'
            var_path: 'app'
            part: Json

```
