### ISSUE TITLE
user-agent header gets overwritten

### ISSUE THREAD

**Issue by Somebi** [Codeception/Codeception#4576]
Only by changing to User-Agentt header appears inside printed by php headers list.
```
modules:
    config:
        PhpBrowser:
          headers:
            User-Agentt: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
```
PHP received headers inside acceptance test:
```
[HTTP_USER_AGENTT] => Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

[HTTP_USER_AGENT] => Symfony2 BrowserKit
```

This is not working:
```
modules:
    config:
        PhpBrowser:
          headers:
            User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
```
