### ISSUE TITLE
run codeception with WebDriver and PhpBrowser

### ISSUE THREAD

**Issue by florent-amo** [Codeception/Codeception#4581]
Hi everyone,
I am upgrading codeception from 1.8.7 to 2.3.5.

In 1.8.7, I would like to execute both WebDriver and PhpBrowser Modules in same time.
Indeed, I generally use WebDriver but in some case I need HTTP Response Code. It's why PhpBrowser is required because WebDriver can't do it.

Traditionally, in our application, code was like that:

```
class AcceptanceTester extends \Codeception\Actor
{
    use _generated\AcceptanceTesterActions;

     * Log into the application with $user account
     * @param type $user
     * @param type $pwd
     */
    public function logIn($user, $pwd) {
        $this->amOnPage('/login');
        $this->fillField('MEMBERS_LOGIN', $user);
        $this->fillField('MEMBERS_PASSWORD', $pwd);
        $this->click('LOGIN');
        $this->dontSeeInCurrentUrl('/login/process');
        $this->logInPhpBrowser($user, $pwd);
    }
}
```

As you can see, the action to Log into our application call logInPhpBrowser

Here is an extract of our TestHelper where the code of this function is located.

```
namespace Helper;

use PDO;


class TestHelper extends \Codeception\Module {

    /** Log in at given url and see html code to check if any redirection occured


     * $code HTTP code expected
     * $redirect si a true ne vérifie pas que la page n'a pas était redirigé

    public function checkPageExists($page, $code = 200, $redirect = FALSE) {
        $this->getModule('WebDriver')->amOnPage($page);
        $this->getModule('PhpBrowser')->amOnPage($page);
        $this->assertEquals
          ($code, $this->getModule('PhpBrowser')->session->getStatusCode());
        if (!$redirect) {
            $this->getModule('WebDriver')->seeCurrentUrlEquals($page);
            $this->debug('Webdrivers ok');
            $this->getModule('PhpBrowser')->seeCurrentUrlEquals($page);
            $this->debug('PhpBrowser ok');
        }
    }

    public function logInPhpBrowser($user, $pwd) {
        $this->getModule('PhpBrowser')->amOnPage('/login');
        $this->getModule('PhpBrowser')->fillField('MEMBERS_LOGIN', $user);
        $this->getModule('PhpBrowser')->fillField('MEMBERS_PASSWORD', $pwd);
        $this->getModule('PhpBrowser')->click('LOGIN');
        $this->getModule('PhpBrowser')->dontSeeInCurrentUrl('/login/process');
    }

```

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Powered by PHPUnit 5.7.22 by Sebastian Bergmann and contributors.


[Codeception\Exception\ModuleConflictException]
  WebDriver module conflicts with PhpBrowser
--
  This usually happens when you enable two modules with the same actions but with different backends.
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one suite,
  as they implement similar methods but use different drivers to execute them.
  You can load a part of module (like: ORM) to avoid conflict.


Exception trace:
 () at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/codeception/codeception/src/Codeception/Lib/ModuleContainer.php:481
 Codeception\Lib\ModuleContainer->validateConflict() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/codeception/codeception/src/Codeception/Lib/ModuleContainer.php:461
 Codeception\Lib\ModuleContainer->validateConflicts() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/codeception/codeception/src/Codeception/SuiteManager.php:69
 Codeception\SuiteManager->__construct() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/codeception/codeception/src/Codeception/Codecept.php:185
 Codeception\Codecept->runSuite() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/codeception/codeception/src/Codeception/Codecept.php:157
 Codeception\Codecept->run() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/codeception/codeception/src/Codeception/Command/Run.php:341
 Codeception\Command\Run->execute() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/codeception/codeception/src/Codeception/Application.php:103
 Codeception\Application->run() at /home/server/www/cashbox-dev/data/tests/product/codeception/vendor/codeception/codeception/codecept:36

```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.3.5
* PHP Version: 5.6
* Operating System: Ubuntu 14.04
* Installation type: Composer
* List of installed packages (`composer show`)
```
behat/gherkin                      v4.4.5 Gherkin DSL parser for PHP 5.3
codeception/codeception            2.3.5  BDD-style testing framework
doctrine/instantiator              1.0.5  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.4.1  A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.0  Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1 Guzzle promises library
guzzlehttp/psr7                    1.4.2  PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.6.1  Create deep copies (clones) of your objects
phpdocumentor/reflection-common    1.0.1  Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  3.2.2  With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.3.0
phpspec/prophecy                   v1.7.2 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          4.0.8  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.2  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1  Simple template engine.
phpunit/php-timer                  1.0.9  Utility class for timing
phpunit/php-token-stream           1.4.11 Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.7.22 The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.4  Mock Object library for PHPUnit
psr/http-message                   1.0.1  Common interface for HTTP messages
psr/log                            1.0.2  Common interface for logging libraries
sebastian/code-unit-reverse-lookup 1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator               1.2.4  Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.3  Diff implementation
sebastian/environment              2.0.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 2.0.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state             1.1.1  Snapshotting of global state
sebastian/object-enumerator        2.0.1  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context        2.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
stecman/symfony-console-completion 0.7.0  Automatic BASH completion for Symfony Console Component based applications.
symfony/browser-kit                v3.3.9 Symfony BrowserKit Component
symfony/console                    v3.3.9 Symfony Console Component
symfony/css-selector               v3.3.9 Symfony CssSelector Component
symfony/debug                      v3.3.9 Symfony Debug Component
symfony/dom-crawler                v3.3.9 Symfony DomCrawler Component
symfony/event-dispatcher           v3.3.9 Symfony EventDispatcher Component
symfony/finder                     v3.3.9 Symfony Finder Component
symfony/polyfill-mbstring          v1.5.0 Symfony polyfill for the Mbstring extension
symfony/process                    v3.3.9 Symfony Process Component
symfony/yaml                       v3.3.9 Symfony Yaml Component
webmozart/assert                   1.2.0  Assertions to validate method input/output with nice error messages.
```
* Suite configuration:

```yml
paths:
    tests: tests/acceptance
    output: tests/_output
    support: tests/_support
    data: tests/_data
    envs: tests/_envs


modules:
    config:
        \Helper\DbHelper:
            dsn: mysql:dbname=cashbox_dev1;host=localhost;charset=utf8
            user: cashbox_dev1
            password: cashbox1
            populate: true
            cleanup: true
            initDb: /home/server/db/sources/cashbox-dev/Mysql/initdb
            dumpPath: /home/server/db/sources/cashbox-dev/Mysql/Data/data-test.sql
            database: cashbox_dev1
            env: cashbox_dev
        PhpBrowser:
            url: http://cashbox-dev1.florent.amo-soft.lan/

# suite config
suites:
    acceptance:
        actor: AcceptanceTester
        path: .
        modules:
            enabled:
                - WebDriver:
                    url: http://192.168.56.215/
                    browser: firefox
                    host: 192.168.56.216
                    port: 4444
                    wait: 0
                - \Helper\TestHelper
            disabled:
                - PhpBrowser


#extensions: [\Helper\DbHelper, PhpBrowser]
# additional paths


settings:
    shuffle: false
    lint: true
```

#### Thanks in advance for your response

// paste test
```
### Details

* Codeception version: 
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by Naktibalda** [comment]
Don't enable PhpBrowser, make it a dependency of TestHelper.

```yaml
        modules:
            enabled:
                - WebDriver:
                    url: http://192.168.56.215/
                    browser: firefox
                    host: 192.168.56.216
                    port: 4444
                    wait: 0
                - \Helper\TestHelper
                    depends:
                         PhpBrowser
```

TestHelper must implement Codeception\Lib\Interfaces\DependsOnModule interface.
And these 2 methods must be added:

```php
    public function _depends()
    {
        return ['Codeception\Module\PhpBrowser' => 'PhpBrowser is a mandatory dependency of TestHelper'];
    }

    public function _inject(\Codeception\Module\PhpBrowser $phpBrowser)
    {
        $this->phpBrowser = $phpBrowser;
    }
```

Look at REST, SOAP and Doctrine modules if you need more examples.

**Comment by florent-amo** [comment]
Thanks for quick answer,

Seems to be better and allow to use both Modules ,
 
but I still have a problem because when I try to run a test using checkJustOneInList I get an error due to DbHelper module.

Here's the code of my test
```
public function add(AcceptanceTester $I) {
        $I->wantTo('Vérifie que la page existe');
        $I->logIn('ADMIN', 'ADMIN');
        $I->checkPageExists('/CommonBusiness/adm-forms/add');
        $I->fillField('DF_FORMS_SHORT_FORM', 'SHORT');
        $I->fillField('DF_FORMS_FULL_TITLE', 'TITLE');
        $I->click('.box-form-actions button');
        $I->checkJustOneInList('DF_FORMS'
                , array('DF_FORMS_SHORT_FORM' => 'SHORT'
            , 'DF_FORMS_FULL_TITLE' => 'TITLE'
        ));

        // check in list
        $I->checkPageExists('/CommonBusiness/adm-forms/list');
        // clique sur le boutton pour afficher toute la liste
        if ($I->seePageHasElem('a[class="btn-page-view-all paginate-btn"]') == 'true') {
            $I->click('a[href="/CommonBusiness/adm-forms/list/dgpage/all"]');
            // attente du chargement de la requête ajax
            $I->wait(3);
        }
        $I->see('SHORT', '//*[@oldtitle="SHORT"]');

        $I->logOut();
    }
```

And what I get

```
1) AdmFormsCest: Vérifie que la page existe
 Test  tests/acceptance/Business/controllers/AdmFormsCest.php:add
                                                                               
  [ModuleException] Codeception\Module: Module DbHelper couldn't be connected  
                                                                               

Scenario Steps:

 11. $I->checkJustOneInList("DF_FORMS",{"DF_FORMS_SHORT_FORM":"SHORT","DF_FORMS_FULL_TITLE":"TITLE"}) at tests/acceptance/Business/controllers/AdmFormsCest.php:27
 10. $I->click(".box-form-actions button") at tests/acceptance/Business/controllers/AdmFormsCest.php:23
 9. $I->fillField("DF_FORMS_FULL_TITLE","TITLE") at tests/acceptance/Business/controllers/AdmFormsCest.php:22

 8. $I->fillField("DF_FORMS_SHORT_FORM","SHORT") at tests/acceptance/Business/controllers/AdmFormsCest.php:21
 7. $I->checkPageExists("/CommonBusiness/adm-forms/add") at tests/acceptance/Business/controllers/AdmFormsCest.php:20
 6. $I->logInPhpBrowser("ADMIN","ADMIN") at tests/_support/AcceptanceTester.php:37

#1  /home/server/www/cashbox-dev/data/tests/product/codeception/tests/_support/Helper/TestHelper.php:64
#2  /home/server/www/cashbox-dev/data/tests/product/codeception/tests/_support/Helper/TestHelper.php:97
#3  Helper\TestHelper->checkJustOneInList
#4  /home/server/www/cashbox-dev/data/tests/product/codeception/tests/_support/_generated/AcceptanceTesterActions.php:3008
#5  /home/server/www/cashbox-dev/data/tests/product/codeception/tests/acceptance/Business/controllers/AdmFormsCest.php:27
#6  AdmFormsCest->add

ERRORS!
Tests: 4, Assertions: 25, Errors: 1.
```

**Comment by Naktibalda** [comment]
This exception is thrown by `getModule('DbHelper')`.
Change it to `getModule('\\Helper\\DbHelper')`

**Comment by florent-amo** [comment]
Wow, seems to work ! 
THANKS !

**Comment by charlesdeb** [comment]
As I'm new to Codeception, it took me quite a while to work out how to make a `TestHelper` - although it still doesn't quite work. Here is what I did:

1. Put a file called `TestHelper.php` in `tests\_support\Helper`
2. It contains:
```
<?php
namespace Helper;

use Codeception\Lib\Interfaces\DependsOnModule;

class TestHelper extends \Codeception\Module implements DependsOnModule
{
  public function _depends()
  {
      return ['Codeception\Module\PhpBrowser' => 'PhpBrowser is a mandatory dependency of TestHelper'];
  }

  public function _inject(\Codeception\Module\PhpBrowser $phpBrowser)
  {
      $this->phpBrowser = $phpBrowser;
  }
}

?>
```
3. In my acceptance.yml file, there was a missing colon in the sample code above after the `- \Helper\TestHelper` line. It needs to look more like:
```
    - WebDriver:
        url: %main_app_url%
        window_size: false # disabled in ChromeDriver
        port: 9515
        browser: chrome
    - \Helper\Acceptance
    - \Helper\TestHelper:
        depends:
          PhpBrowser
```
With that all done, I am a little closer to getting this to run. However, I am now getting this error

```
PHP Notice:  Undefined index: url in /folder-root/vendor/codeception/codeception/src/Codeception/Module/PhpBrowser.php on line 249
```
 related to a missing 'url' config parameter from said line 249.

```
$defaults['base_uri'] = $this->config['url'];
```
All of my tests fail. This is not surprising since I am not specifying a `url` in the yml file above. But I am not sure where to do that. Suggestions?

Also, is there a way to specify in the tests themselves which get run by PhpBrowser (much faster) and which get run by WebDriver (much slower, but needed for Javascript stuff) 

Also I am getting another error which is probably not related - but I don't get it when running WebDriver or PhpBrowser by themselves. 

```
3x DEPRECATION: Calling the "Symfony\Component\BrowserKit\Client::getInternalResponse()" method before the "request()" one is deprecated since Symfony 4.1 and will throw an exception in 5.0. /folder-root/vendor/symfony/browser-kit/Client.php:208
```

**Comment by Naktibalda** [comment]
1. Specify `url` in configuration of PhpBrowser module.
```yaml
modules:
  config:
     phpBrowser:
       url: 'xxx',
```

2. Put PhpBrowser and WebDriver tests to different suites.

3. Deprecation message depends on your test code, please share it and the code of your TestHelper.
My guess is that you are using PhpBrowser method to inspect response after performing request using WebDriver.
