### ISSUE TITLE
Symfony2 Module Request Dependency Injection in Controller doesnt work

### ISSUE THREAD

**Issue by bennsel** [Codeception/Codeception#4597]
#### What are you trying to achieve?

Functional Test for a symfony2 controller with a Request object as a Controller Argument

#### What do you get instead?

Dependency Injection of Request doesnt work. 
```php
Controller "Neusta\ClubPortal\Svw\CampBundle\Controller\DefaultController::indexAction()" requires that you provide a value for the "$request" argument (because there is no default value or because there is a non optional argument after this one).
```
### Details

* Codeception version: 2.3.6
* PHP Version: 7.0.23
* Operating System: Linux
* Installation type: Composer
* Usage Description from Symfony: https://symfony.com/doc/2.8/controller.html#the-request-object-as-a-controller-argument
* Suite configuration:

codeception.yml in root
```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed

include:
    - Source/Symfony/src/Neusta/ClubPortal/CampBundle
```
codeception.yml in bundle
```yml
namespace: CampBundle
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```
Controller
```php
<?php

namespace Neusta\ClubPortal\Svw\CampBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Neusta\ClubPortal\SystemBundle\Connector\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/camp")
 */
class DefaultController extends Controller
{
    /**
     * @Route("/", name="camp")
     * @param Request $request
     * @return Response
     */
    public function indexAction(Request $request)
    {

        return $this->render(
            'CampBundle:Default:index.html.twig',
            [
                'foo' => 'bar'
            ]
        );
    }
}

```

IndexCest.php
```php
<?php
namespace CampBundle;
use CampBundle\FunctionalTester;
class IndexCest
{

    // tests
    public function tryToTest(FunctionalTester $I)
    {
        $I->amOnRoute('camp');
        $I->seeNumberOfElements('.o-shadow-box', 1);
    }
}

```
