### ISSUE TITLE
zero-fill coverage and nameapace frontend\tests

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4610]
#### What are you trying to achieve?
test coverage on acceptance tests (yii2 advanced template, part "frontend")
with c3.php
 
#### What do you get instead?
zero-fill coverage. 

```sh
OK (2 tests, 13 assertions)


Code Coverage Report:   
  2017-11-08 14:24:01   
                        
 Summary:               
  Classes:  0.00% (0/2) 
  Methods:  0.00% (0/7) 
  Lines:    0.00% (0/52)
```
Inside c3tmp all is ok (IMHO)
`data!=null`
```
cat php-code/frontend/tests/_output/c3tmp/codecoverage.serialized 
O:43:"SebastianBergmann\CodeCoverage\CodeCoverage":20:{s:51:"SebastianBergmann\CodeCoverage\CodeCoveragedriver";O:44:"SebastianBergmann\CodeCoverage\Driver\Xdebug":1:{s:59:"SebastianBergmann\CodeCoverage\Driver\XdebugcacheNumLines";a:0:{}}s:51:"SebastianBergmann\CodeCoverage\CodeCoveragefilter";O:37:"SebastianBergmann\CodeCoverage\Filter":1:{s:55:"SebastianBergmann\CodeCoverage\FilterwhitelistedFiles";a:2:{s:45:"/var/www/html/frontend/models/ContactForm.php";b:1;s:53:"/var/www/html/frontend/controllers/SiteController.php";b:1;}}s:51:"SebastianBergmann\CodeCoverage\CodeCoveragewizard";O:46:"SebastianBergmann\CodeUnitReverseLookup\Wizard":3:{s:59:"SebastianBergmann\CodeUnitReverseLookup\WizardlookupTable";a:0:{}s:64:"SebastianBergmann\CodeUnitReverseLookup\WizardprocessedClasses";a:0:{}s:66:"SebastianBergmann\CodeUnitReverseLookup\WizardprocessedFunctions";a:0:{}}s:56:"SebastianBergmann\CodeCoverage\CodeCoveragecacheTokens";b:0;s:79:"SebastianBergmann\CodeCoverage\CodeCoveragecheckForUnintentionallyCoveredCode";b:0;s:66:"SebastianBergmann\CodeCoverage\CodeCoverageforceCoversAnnotation";b:0;s:74:"SebastianBergmann\CodeCoverage\CodeCoveragecheckForUnexecutedCoveredCode";b:0;s:76:"SebastianBergmann\CodeCoverage\CodeCoveragecheckForMissingCoversAnnotation";b:0;s:75:"SebastianBergmann\CodeCoverage\CodeCoverageaddUncoveredFilesFromWhitelist";b:1;s:79:"SebastianBergmann\CodeCoverage\CodeCoverageprocessUncoveredFilesFromWhitelist";b:0;s:65:"SebastianBergmann\CodeCoverage\CodeCoverageignoreDeprecatedCode";b:0;s:54:"SebastianBergmann\CodeCoverage\CodeCoveragecurrentId";N;s:49:"SebastianBergmann\CodeCoverage\CodeCoveragedata";a:1:{s:53:"/var/www/html/frontend/controllers/SiteController.php";a:17:{i:20;a:2:{i:0;s:9:"checkHome";i:1;s:17:"updateSelfAccount";}i:24;a:2:{i:0;s:9:"checkHome";i:1;s:17:"updateSelfAccount";}i:25;a:2:{i:0;s:9:"checkHome";i:1;s:17:"updateSelfAccount";}i:28;N;i:37;a:2:{i:0;s:9:"checkHome";i:1;s:17:"updateSelfAccount";}i:38;N;i:47;a:0:{}i:48;a:0:{}i:49;a:0:{}i:50;a:0:{}i:52;a:0:{}i:55;a:0:{}i:57;a:0:{}i:58;a:0:{}i:61;N;i:70;a:1:{i:0;s:9:"checkHome";}i:71;N;}}s:57:"SebastianBergmann\CodeCoverage\CodeCoverageignoredLines";a:0:{}s:64:"SebastianBergmann\CodeCoverage\CodeCoveragedisableIgnoredLines";b:0;s:50:"SebastianBergmann\CodeCoverage\CodeCoveragetests";a:2:{s:9:"checkHome";a:2:{s:4:"size";s:7:"unknown";s:6:"status";N;}s:17:"updateSelfAccount";a:2:{s:4:"size";s:7:"unknown";s:6:"status";N;}}s:86:"SebastianBergmann\CodeCoverage\CodeCoverageunintentionallyCoveredSubclassesWhitelist";a:0:{}s:58:"SebastianBergmann\CodeCoverage\CodeCoverageisInitialized";b:0;s:72:"SebastianBergmann\CodeCoverage\CodeCoverageshouldCheckForDeadAndUnused";b:1;s:51:"SebastianBergmann\CodeCoverage\CodeCoveragereport";N;}
```
xml also have non-zero values

I will trace around this error and in this code I can see suspend data

https://github.com/Codeception/Codeception/blob/10192427bdd8d1c63c231105bdc189a76636f8f6/src/Codeception/Coverage/Subscriber/RemoteServer.php#L58-L62

debug achive 
```php
$destFile = "/project/frontend/tests/_output/frontend\tests.acceptance.remote.coverage.xml";
$suite = "frontend\tests.acceptance";
```

console output if related. 

```bash
$ docker-compose -f docker-codeception-run/docker-compose.yml up -d
Creating network "dockercodeceptionrun_default" with the default driver
Creating dockercodeceptionrun_db_1
Creating dockercodeceptionrun_browser_1
Creating dockercodeceptionrun_php_1
Creating dockercodeceptionrun_nginx_1
Creating dockercodeceptionrun_codecept_1
$ docker-compose -f docker-codeception-run/docker-compose.yml run --rm --entrypoint bash codecept
root@f605d18a32a8:/project# cd /project/frontend/ && codecept run acceptance --coverage --coverage-xml --coverage-html

Warning: Cannot declare class PHPUnit_Framework_Assert, because the name is already in use in /repo/shim.php on line 17

Call Stack:
    1.2740     372328   1. {main}() /repo/codecept:0
    1.3960     398184   2. require_once('/repo/autoload.php') /repo/codecept:7
    1.4106    2165448   3. include_once('/repo/shim.php') /repo/autoload.php:45
    1.4130    2424800   4. class_alias(???, ???) /repo/shim.php:17

Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

Frontend\tests.acceptance Tests (2) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
✔ HomeCest: Check home (2.69s)
✔ UpdateSelfAccountCest: Ensure that self account update works (32.23s)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 50.88 seconds, Memory: 18.00MB

OK (2 tests, 13 assertions)


Code Coverage Report:   
  2017-11-08 15:13:16   
                        
 Summary:               
  Classes:  0.00% (0/2) 
  Methods:  0.00% (0/7) 
  Lines:    0.00% (0/52)

Remote CodeCoverage reports are not printed to console

HTML report generated in coverage
XML report generated in coverage.xml
root@f605d18a32a8:/project/frontend# 



```
[test source code if related](https://github.com/bscheshirwork/yii2-app-advanced-rbac/tree/8c98f8b5b41da6ff89bc3e266f3f27d429884298/frontend/tests)

### Details
* docker-compose [docker-compose.yml](https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/blob/master/docker-codeception-run/docker-compose.yml)
* Codeception version: 
* PHP Version: 7.1.11
* Operating System:
* Installation type: Phar and docker Codeception 
* List of installed packages (`composer show`)
* Suite configuration:

[frontend/codeception.yml](https://github.com/bscheshirwork/yii2-app-advanced-rbac/blob/8c98f8b5b41da6ff89bc3e266f3f27d429884298/frontend/codeception.yml)
```yml
namespace: frontend\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'
coverage:
    # from nginx-conf-test/nginx.conf
    c3_url: http://nginx:8080/index-test.php
    # redefine `php-code/codeception.yml` for `c3.php`. Relative to `c3.php` dir:
    # $config_file = realpath(__DIR__) . DIRECTORY_SEPARATOR . $_SERVER['HTTP_X_CODECEPTION_CODECOVERAGE_CONFIG'];
    remote_config: frontend/codeception.yml
    enabled: true
    remote: true
    include:
        - models/*
        - controllers/*
    exclude:
        - assets/*
        - config/*
        - runtime/*
        - views/*
        - web/*
        - tests/*

```
