### ISSUE TITLE
I can't see an element - Fail..element was not found.

### ISSUE THREAD

**Issue by Soufraz** [Codeception/Codeception#4620]
#### What are you trying to achieve?
Access a page and wait for the ajax of jquery ui tabs finish and then fill a field. Probably is something about wait ajax contents. Others simple tests to see pages and submit forms works perfectly.

#### What do you get instead?
The tests says that the element does not exists yet.

**Codeception log**
```bash
root@39004c40c529:/var/www/project# ./composer_vendor/bin/codecept run --steps tests/acceptance
Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 5.7.21 by Sebastian Bergmann and contributors.

Acceptance Tests (1) ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FirstCest: Create company works
Signature: FirstCest:createCompanyWorks
Test: tests/acceptance/FirstCest.php:createCompanyWorks
Scenario --
 I do login
   I am on page "/users/login"
   I fill field "username","rafael"
   I fill field "user_password","mypassword"
   I click "Log In"
 I am on page "/companies/add"
 I wait 5
 I fill field {"name":"company_name"},"The Tested Company"
 FAIL

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 8.99 seconds, Memory: 12.00MB

There was 1 failure:

---------
1) FirstCest: Create company works
 Test  tests/acceptance/FirstCest.php:createCompanyWorks
 Step  Fill field {"name":"company_name"},"The Tested Company"
 Fail   element with name 'company_name' was not found.

Scenario Steps:

 7. $I->fillField({"name":"company_name"},"The Tested Company") at tests/acceptance/FirstCest.php:35
 6. $I->wait(5) at tests/acceptance/FirstCest.php:34
 5. $I->amOnPage("/companies/add") at tests/acceptance/FirstCest.php:33
 4. $I->click("Log In") at tests/_support/AcceptanceTester.php:31
 3. $I->fillField("user_password","mypassword") at tests/_support/AcceptanceTester.php:30
 2. $I->fillField("username","rafael") at tests/_support/AcceptanceTester.php:29


FAILURES!
Tests: 1, Assertions: 0, Failures: 1.
```

**My test**
```php
    public function createCompanyWorks(AcceptanceTester $I)
    {
        $I->doLogin();

        $I->amOnPage('/companies/add');
        $I->wait(5);
        $I->fillField(['name' => 'company_name'], 'The Tested Company');
    }
```
### Details

* Codeception version: ^2.3
* PHP Version: 7.1
* Operating System: Ubuntu 14.04
* Installation type: Composer

**project\tests\acceptance.suite.yml**
```yml
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://sigep.local
            browser: phantomjs
            window_size: 1024x768
        - \Helper\Acceptance
```

**Comment by Naktibalda** [comment]
Try to use [waitForElement ](http://codeception.com/docs/modules/WebDriver#waitForElement ) instead of waiting for a fixed amount of time.
```php
$I->waitForElement(['name' => 'company_name'], 30);
$I->fillField(['name' => 'company_name'], 'The Tested Company');
```

**Comment by Soufraz** [comment]
```
  [Facebook\WebDriver\Exception\NoSuchElementException] {"errorMessage":"Unable to find element with name 'company_name'","request":{"headers":{"Accept":"application/json","Content-Leng
th":"46","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:4444"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"name\",\"value\":\"company_name\"}","url":"/el
ement","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","pr
otocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/712f9590-c88c-11e7-861a-8516251805d5/element"}}
```

**Comment by Naktibalda** [comment]
I just noticed that you are using PhantomJS.
Does your test work with a real browser?

**Comment by Soufraz** [comment]
I am running into docker. Is there another solution?

**Comment by Naktibalda** [comment]
[Headless Chrome](http://phptest.club/t/how-to-run-headless-chrome-in-codeception/1544)

**Comment by Soufraz** [comment]
The chrome driver installation was perfect. I can start and see its version. But when I ran the tests, I get this in the chrome driver log:

```
root@39004c40b539:/# chromedriver --url-base=/wd/hub
Starting ChromeDriver 2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4) on port 9515
Only local connections are allowed.
Starting ChromeDriver 2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4) on port 9515
Only local connections are allowed.
Port not available. Exiting...
```

And here my acceptance.suite.yaml:

```
actor: AcceptanceTester
modules:
   enabled:
      - \Helper\Acceptance
      - WebDriver:
         url: http://project.local
         window_size: false # disabled in ChromeDriver
         port: 9515
         browser: chrome
         capabilities:
             chromeOptions: # additional chrome options
                args: ["--headless", "--disable-gpu"]
                binary: "/usr/bin/chromedriver"
```

**Comment by DavertMik** [comment]
are you running it from within docker? 0.o
in this case you just need to download a proper docker container and run it like:

```
docker run --net=host selenium/standalone-chrome 
```

**Comment by Soufraz** [comment]
Ok. But what is the problem in use docker with headless browser?

**Comment by Soufraz** [comment]
Another question is, I don't need to user selenium with chrome. Do I?

**Comment by Soufraz** [comment]
My working solution without selenium using docker:

Google Chrome 62.0.3202.94
ChromeDriver 2.33

```
actor: AcceptanceTester
modules:
   enabled:
      - \Helper\Acceptance
      - WebDriver:
         url: http://project.local
         window_size: false # disabled in ChromeDriver
         port: 9515
         browser: chrome
         capabilities:
             chromeOptions: # additional chrome options
                args: ["--headless", "--disable-gpu", "--no-sandbox"]
                binary: "/usr/bin/google-chrome"
```
