### ISSUE TITLE
Module\Yii2: force set $config->['transaction'] to false inside of Acceptance tests

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4628]
#### What are you trying to achieve?
don't use transaction mechanism in Acceptance tests

#### What do you get instead?

usage depends of config
https://github.com/Codeception/Codeception/blob/b1d96dad56bb3dbc5185d7dcb7913db441c121b6/src/Codeception/Module/Yii2.php#L156-L158
https://github.com/Codeception/Codeception/blob/b1d96dad56bb3dbc5185d7dcb7913db441c121b6/src/Codeception/Module/Yii2.php#L194-L200

### Details

* Codeception version: 2.3
* PHP Version:7.1.11
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
# See docker-codeception-run/docker-compose.yml: "ports" of service "nginx" is null; the selenium service named "chrome"
# See nginx-conf/nginx.conf: listen 8080 for frontend; listen 8081 for backend
        - WebDriver:
            url: http://nginx:8080/
            host: browser
            port: 4444
            browser: chrome
        - \bscheshirwork\Codeception\Module\DbYii2Config:
            dump: ../common/tests/_data/dump.sql #relative path from "codeception.yml"
            populate: true
            cleanup: true
        - Yii2:
            part:
              - email
              - ORM
              - Fixtures
            cleanup: true # remove fixture in _after and load fixture in _before. In this case data from fixtures insert to db AFTER DbYii2Config populate
            transaction: false # don't wrap test in transaction. Acceptance tests use another db connection; i.e. transaction has no effect.
        - Asserts
        - common\tests\Helper\Acceptance

```

**Comment by samdark** [comment]
Why not using transactions?

**Comment by samdark** [comment]
Or do you mean that you want to turn it off via config but you can not?

**Comment by bscheshirwork** [comment]
> Why not using transactions?

Acceptance browser (in my cese it is a Selenium) use another connection to db; I am right?

**Comment by samdark** [comment]
What do you mean by another? Do you have multiple connections?

**Comment by bscheshirwork** [comment]
Someone like "another instance of connection handler". Another process. Another (separated) request. Use same db connection settings for connect.

**Comment by samdark** [comment]
I don't get it :(

**Comment by bscheshirwork** [comment]
@samdark в разных приложениях - 

тестовом, которое подключается к коду через коннектор (в вендорах или phar) `src/Codeception/Lib/Connector/Yii2.php` модуля 

и том, которое запускает сервер по запросу от эмулятора браузера (точка входа `frontend/web/index-test.php`)

соединения к базе `yii2\db\Connection::$pdo`, естественно, не один экземпляр класса `PHP PDO`. Соответственно и естественно, транзакция не имеет смысла - происходящее в транзакции никак не скажется на тестируемой базе.

Учитывая скрытую магию задания этого параметра, в случае если он не указан,
https://github.com/Codeception/Codeception/blob/b1d96dad56bb3dbc5185d7dcb7913db441c121b6/src/Codeception/Module/Yii2.php#L156-L158
создаётся путаница.

**Comment by samdark** [comment]
А, вот оно что... да, это будут два разных соединения и да, это не сразу очевидно. Что предлагаете сделать? Изменить умолчание совсем или изменить его только для этого типа тестов?

@DavertMik думаю, без тебя не обойдёмся...

**Comment by bscheshirwork** [comment]
Думаю, идеально зашла бы проверка на текущего тестера
```yml
class_name: AcceptanceTester
```
либо же осветить этот момент в документации поподробнее и объяснить всем и каждому, как задавать эту пару параметров для случая `acceptance.suite.yml`:
```yml
class_name: AcceptanceTester
modules:
    enabled:
        - Yii2:
            cleanup: true
            transaction: false
```
и в чём её смысл.

С учётом того, что ещё встречаются [проблемы](https://github.com/Codeception/Codeception/issues/4617) с историческим `_before`, это будет не лишним
