### ISSUE TITLE
Module\Yii2: force insert fixtures data to db (loadedFixtures not representative if used after another Codeception module who clear db)

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4629]
#### What are you trying to achieve?
I set config of yii module to
```yml
modules:
    enabled:
        - Yii2:
            cleanup: false
```
I set in acceptance helper
```php
    /**
     * @param \Codeception\TestInterface $test
     */
    public function _after(\Codeception\TestInterface $test){
        /** @var \Codeception\Module\Yii2 $module */
        $module = $this->getModule('Yii2');
        foreach ($module->loadedFixtures as $fixture) {
            $fixture->unloadFixtures();
            $fixture->loadFixtures();
        }

        parent::_after($test);
    }
```
if I cleanup db in another module 
```yml
class_name: AcceptanceTester
modules:
    enabled:
        - Db:
            populate: true
            cleanup: true
```
the `loadedFixtures` is not representative to data in databases, but not reload.
https://github.com/Codeception/Codeception/blob/b1d96dad56bb3dbc5185d7dcb7913db441c121b6/src/Codeception/Module/Yii2.php#L210

### Details

* Codeception version: 2.3
* PHP Version:7.1.11
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

base config (who work around this issue)
```yml
# paste suite config here
class_name: AcceptanceTester
modules:
    enabled:
# See docker-codeception-run/docker-compose.yml: "ports" of service "nginx" is null; the selenium service named "chrome"
# See nginx-conf/nginx.conf: listen 8080 for frontend; listen 8081 for backend
        - WebDriver:
            url: http://nginx:8080/
            host: browser
            port: 4444
            browser: chrome
        - \bscheshirwork\Codeception\Module\DbYii2Config:
            dump: ../common/tests/_data/dump.sql #relative path from "codeception.yml"
            populate: true
            cleanup: true
        - Yii2:
            part:
              - email
              - ORM
              - Fixtures
            cleanup: true # remove fixture in _after and load fixture in _before. In this case data from fixtures insert to db AFTER DbYii2Config populate
            transaction: false # don't wrap test in transaction. Acceptance tests use another db connection; i.e. transaction has no effect.
        - Asserts
        - common\tests\Helper\Acceptance
```
