### ISSUE TITLE
Feature request: skip certain tests by default

### ISSUE THREAD

**Issue by CJDennis** [Codeception/Codeception#4632]
I would like to be able to mark some tests as "dangerous" and not run them unless they are specifically included. I don't think there is currently a configuration option that would allow this.

Something like:
```
optional-groups:
  dangerous:
    - tests/unit/DatabaseTest.php
    - tests/unit/PaymentTest.php
  slow:
    - tests/unit/SemiPrimeFactoringTest.php
```

Then, when Codeception is run, it skips these tests unless specified with `-g dangerous -g slow`.
