### ISSUE TITLE
[Queue] Configuration parameter endpoint is missing in AmazonSQS lib

### ISSUE THREAD

**Issue by gitis** [Codeception/Codeception#4645]
#### What are you trying to achieve?
Trying to pass custom endpoint to AmazonSQS lib in order to be able to assert queue using [localstack](https://github.com/localstack/localstack)
#### What do you get instead?
There is no such option.

Working configuration.
```yml
actor: FunctionalTester
modules:
    enabled:
        - Queue:
            type: 'aws_sqs'
            key: 'foobar'
            secret: 'foobar'
            region: 'eu-central-1'
            version: 'latest'
```

Needed configuration
```yml
actor: FunctionalTester
modules:
    enabled:
        - Queue:
            type: 'aws_sqs'
            key: 'foobar'
            secret: 'foobar'
            region: 'eu-central-1'
            version: 'latest'
            endpoint: 'http://localstack:4576'
```
