### ISSUE TITLE
Webdriver url option is ignored

### ISSUE THREAD

**Issue by Somebi** [Codeception/Codeception#4662]
```
# http://codeception.com/docs/modules/WebDriver
modules:
    enabled:
        - WebDriver
    config:
        WebDriver:
            # http://codeception.com/docs/modules/WebDriver#Configuration
            browser: 'firefox'
            url: 'http://some-domain.com/'
            window_size: maximize
            # capabilities:
               # https://sites.google.com/a/chromium.org/chromedriver/capabilities
               # chromeOptions:
```
