### ISSUE TITLE
Unit Test Code Coverage partially appears to work, shows no coverage.

### ISSUE THREAD

**Issue by n0nag0n** [Codeception/Codeception#4666]
#### What are you trying to achieve?
I would like code coverage to show lines, methods, and classes that are covered. I am only testing unit testing on my local machine, no other tests currently. I have included c3.php just in case, with no change in results. Tried to also set remote: true, and remote: false with similar results. When I use `--coverage-html` I get the same result as the console and everything is showing as having no coverage.
#### What do you get instead?
Output happens, but everything shows 0/[total_number]

> Provide console output if related. Use `-vvv` mode for more details.

```bash
$: codecept run unit --coverage -vvv
Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 6.3.1 by Sebastian Bergmann and contributors.

Unit Tests (5) ----------------------------------------------------------------------------------
Modules: Asserts, \Helper\Unit
------------------------------------------------------------------------------------------------
✔ Root_DomainTest: Get root domain (0.01s)
------------------------------------------------------------------------------------------------


Time: 500 ms, Memory: 14.00MB

OK (1 tests, 2 assertions)


Code Coverage Report:      
  2017-12-06 12:10:20      
                           
 Summary:                  
  Classes:  0.00% (0/97)   
  Methods:  0.00% (0/1521) 
  Lines:    0.00% (0/34707)

```
> Provide test source code if related
Here's an example of a test that should cover something at least...
```php
<?php
	include_once("/path/to/Root_Domain.php");
	class Root_DomainTest extends \Codeception\Test\Unit {
		public function testGetRootDomain() {
			$Root_Domain = new Root_Domain;
			$root_domains = $Root_Domain->getRootDomain('4');
			$this->assertGreaterThan(1, count($root_domains));
			
			$filtered_root_domains = $Root_Domain->getRootDomain('4', 'id');
			$this->assertEquals(1, count($filtered_root_domains));
		}
        }
```
### Details

* Codeception version: 2.3.6
* PHP Version: 7.1.11
```ini
# xdebug settings
coverage_enable=On
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_port=9000
xdebug.remote_host=127.0.0.1
xdebug.remote_autostart=0
xdebug.profiler_enable=0
xdebug.profiler_output_dir="/tmp/"
```
* Operating System: Mac OS High Sierra
* Installation type: Phar
* List of installed packages (`composer show`)
* Suite configuration: 
```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    error_level: "E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_NOTICE"
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: false
    include:
        - includes/classes/*
        - includes/models/*
modules:
    config:
        Db:
            dsn: 'mysql...'
            user: ''
            password: ''
            populate: false
            cleanup: false
```

**Comment by Naktibalda** [comment]
Is the class that you are testing in one of directories listed in coverage include setting?

**Comment by n0nag0n** [comment]
Yes, it is includes/models/Root_Domain.php It displays in the HTML report.
![image](https://user-images.githubusercontent.com/2322095/33691802-d5593f0c-da9e-11e7-8ff9-81a38c7d0c94.png)

**Comment by n0nag0n** [comment]
If it matters, I actually installed Codeception using `brew install codeception` and it's located at `/usr/local/bin/codecept`

**Comment by Naktibalda** [comment]
Then `require_once("includes/models/Root_Domain.php");` at the top of your test file should work.
 
Probably whitelisted paths don't match paths that are actually included.

**Comment by n0nag0n** [comment]
So my file structure is:
```
root/
codeception.yml
--tests/
----unit/
------Root_DomainTest.php
--includes/
----models/
------Root_Domain.php
```

One other note is that I have tests/unit/_bootstrap.php that includes a bootstrap of my project, db connection, some vars, and other such things. In fact the Root_Domain.php file is already included in the _bootstrap.php as it's a pretty global model that's needed everywhere.

So what options can I try? It appears I'm whitelisting the correct directories as it's finding all my classes/models as it should. Code coverage just never tracks what code is executed. Is there some test/profile I can dive into to find out what is getting executed?

**Comment by Naktibalda** [comment]
Have you tried to test your codebase using PHPUnit?
Doing that would make it clear if it is an issue of Codeception or PhpCodeCoverage library.

**Comment by n0nag0n** [comment]
I'm doing that as we speak/type :)

**Comment by n0nag0n** [comment]
So I think it has something similar to do with this https://github.com/Codeception/AspectMock/issues/114

The issue is my bootstrap file includes some of my models on load, and then when code coverage runs with processUncoveredFilesFromWhitelist="true" it tries to "re-include" those files. For whatever reason when it runs `include_once` from php-code-coverage, it throws the error that my class has already been declared. If I make that setting "false" it runs just fine, but again does not show any coverage on classes/methods/lines. 

So the only error I can think of on this is that because of my setup, when this function runs (from php-code-coverage) and runs include_once, no error is throw in Codeception showing the include_once error.
```php
protected function initializeData()
    {
        $this->isInitialized = true;
        if ($this->processUncoveredFilesFromWhitelist) {
            $this->shouldCheckForDeadAndUnused = false;
            $this->driver->start(true);
            foreach ($this->filter->getWhitelist() as $file) {
                if ($this->filter->isFile($file)) {
                    include_once($file);
                }
            }
            $data     = [];
            $coverage = $this->driver->stop();
            foreach ($coverage as $file => $fileCoverage) {
                if ($this->filter->isFiltered($file)) {
                    continue;
                }
                foreach (\array_keys($fileCoverage) as $key) {
                    if ($fileCoverage[$key] === Driver::LINE_EXECUTED) {
                        $fileCoverage[$key] = Driver::LINE_NOT_EXECUTED;
                    }
                }
                $data[$file] = $fileCoverage;
            }
            $this->append($data, 'UNCOVERED_FILES_FROM_WHITELIST');
        }
    }
```

Looks like in order to make this work (if this really is the problem) I may have to redesign my bootstrap file to include the bare minimum, and whatever classes are included, just exclude them from the whitelist. But I don't have time to do that at the moment....maybe in some distant lifetime I can.

**Comment by Naktibalda** [comment]
You should start using autoloading, it is a decade old feature of PHP.

**Comment by n0nag0n** [comment]
I agree, but this is old legacy code I'm working with here that's 7 years old.

**Comment by n0nag0n** [comment]
So if anyone cares for the answer, I rewrote a part of our legacy code to use autoloading and then it looks like I just needed to whitelist the tests directory as well.

```yaml
coverage:
    enabled: true
    remote: false
    include:
        - includes/classes/*
        - includes/models/*
        - tests/unit/*
```
