### ISSUE TITLE
reporters config owerrite by default in included suites

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4667]
#### What are you trying to achieve?

I try to use redefine printer (may be resolve some problem on php 7.2)

```php
<?php

namespace common\tests;


/**
 * Class Report overrides \Codeception\PHPUnit\ResultPrinter\Report constructor
 * to change default output to STDOUT and prevent some tests from fail when
 * they can not be executed after headers have been sent.
 */
class Report extends \Codeception\PHPUnit\ResultPrinter\Report
{
    /**
     * Report constructor.
     * @inheritdoc
     * @param null $out
     * @param array $groups
     * @param array $excludeGroups
     */
    public function __construct($out = null, array $groups = [], array $excludeGroups = [])
    {
        if ($out === null) {
            $out = STDOUT;
        }

        parent::__construct($out, $groups, $excludeGroups);
    }

    /**
     * @inheritdoc
     */
    public function flush()
    {
        if ($this->out !== STDOUT) {
            parent::flush();
        }
    }
}
```

in yii2-app-advanced...

I set into common config `codeception.yml`
```yml
# global codeception file to run tests from all apps
include:
    - common
    - frontend
    - backend
paths:
    log: console/runtime/logs
settings:
    colors: true
reporters:
    report: common\tests\Report
```
I want to use this in included suites...

#### What do you get instead?

Code of redefine printer newer use.

I try to trace it.

In https://github.com/Codeception/Codeception/blob/75a1f48f291323083caebed7d0244de96ff8c008/src/Codeception/Command/Run.php#L387

config will be load from included suite, i.e. from `backend/codeception.yml`
```yml
namespace: backend\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'
```

and some strange merged: in
https://github.com/Codeception/Codeception/blob/75a1f48f291323083caebed7d0244de96ff8c008/src/Codeception/Configuration.php#L168-L177

my definition of `reporters: report:` ignored. Catch default value and 
in 
https://github.com/Codeception/Codeception/blob/75a1f48f291323083caebed7d0244de96ff8c008/src/Codeception/Configuration.php#L183

share it global instead reporters from top-level(global) config.

This is correct?

### Details

* Codeception version: Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.
* PHP Version:7.2.0
* Operating System:debian scratch
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```
