### ISSUE TITLE
 Declaration of Codeception\Coverage\DummyCodeCoverage::stop()  should be compatible with SebastianBergmann\CodeCoverage\CodeCoverage::stop()

### ISSUE THREAD

**Issue by jmolinas** [Codeception/Codeception#4668]
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 Declaration of Codeception\Coverage\DummyCodeCoverage::stop($append = true, $linesToBeCovered = Array, array $linesToBeUsed = Array) should be compatible with SebastianBergmann\CodeCoverage\CodeCoverage::stop($append =
   true, $linesToBeCovered = Array, array $linesToBeUsed = Array, $ignoreForceCoversAnnotation = false)
```
> Provide test source code if related

```php
vendor/bin/codecept run --coverage
```
### Details

* Codeception version: 
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: false
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    include:
        - application/controllers/*
        - application/Service/*
    exclude:
        - application/views/*
```
