### ISSUE TITLE
Accessing an ActorClass from helpers

### ISSUE THREAD

**Issue by Jacek-fstack** [Codeception/Codeception#4677]
Hey, I have a problem - what approach do I use if I want to group my actions?
I know there are stepObjects, but these are only to extend certain functionality, as far as I understand. 
How would I go about grouping actions like
AccountHelper - for registering a new account, logging in actions
BillingHelper - for handling billing related stuff etc.
BUT
I want to be able to call from the helpers all Actor actions, so
`$user = $this->getModule('Webdriver');
   $user->amOnPage('/admin/user/login');
   $user->click('.registerLink');`
When I use this from my AccountHelper class, only the amOnPage gets executed, and it passes, nothing after that is executed and it passes. I am assuming it's because click is handled by actor class?
So how do I group my actions so not everything is in the WebGuy class?

**Comment by Jacek-fstack** [comment]
Okay, so maybe to be clearer I will explain the situation and what I want to accomplish, because maybe I went about it the wrong way.
Until now we declared all custom actions in WebGuy.php
So we would do something like
`public function logIn($login, $password){
      $this->amOnPage('/admin/user/login');
      $this->fillField('#email', $login);
      $this->fillField('#password', $password);
      $this->click('#submit');

      $this->canSeeInCurrentUrl('/admin/account/dashboard');
    }`

But after some time the WebGuy started to blow up really quickly, and we want to avoid having to maintain a class that is 2k lines long, because of the conflicts and all-around confusion.
So the question is - how can I group these actions into separate files / classes so it would be easier to maintain, but we would still be able to call them like $I->doSomething(); from the tests that are going to use these functions?

**Comment by Naktibalda** [comment]
> So the question is - how can I group these actions into separate files / classes so it would be easier to maintain, but we would still be able to call them like $I->doSomething(); from the tests that are going to use these functions?

Use helpers.

**Comment by Jacek-fstack** [comment]
Yes, that is what I was doing, BUT I cannot access the actor methods from helpers.

**Comment by Naktibalda** [comment]
The only problem with your example is that, if I remember correctly, module names are case sensitive.
so `$user = $this->getModule('WebDriver');`

But Step objects would fit your use case better.

**Comment by Jacek-fstack** [comment]
So 
` $user = $this->getModule('WebDriver');`
results in   [ModuleException] Codeception\Module: Module WebDriver couldn't be connected
and `webdriver`
```public function registerNewAccount($email = null, $password = 'xxxxx'){
        if (is_null($email)) {
            $email = 'jacektestingacc+'.substr(md5(rand()), 0, 7).'@gmail.com';
        }
        $this->email = $email;
        $user = $this->getModule('Webdriver');
        $user->amOnPage('/admin/user/login');
        $user->click('.registerLink');
        $user->see('Start your 14-Day Free Trial');
        $user->fillField('firstName',  'John');
        $user->fillField('lastName',  'Doe');
[...]```
results in executing ONLY the 
`$user->amOnPage('/admin/user/login');`
and everything after that is just skipped.

and StepObjects, as far as I saw, only extend a class, right? I want to be able to do multiple classes, that I can access any time, in any part of the app, by calling from $I->dosomething();

**Comment by Naktibalda** [comment]
`[ModuleException] Codeception\Module: Module WebDriver couldn't be connected`
It means that WebDriver is not enabled in that particular test suite.

What version of Codeception do you use?

**Comment by Jacek-fstack** [comment]
2.3.5
Not sure what you mean by WebDriver is not enabled? Whatever I put into the WebGuy.php works perfectly, without an issue.
and my acceptance suite is
```
class_name: WebGuy
modules:
    enabled:
        - \Helper\Web
        - Db
        - \Helper\AccountHelper
        - Webdriver:
            url: 'https://xxx.com'
            browser: chrome
            window_size: 1024x768
            restart: true
            clear_cookies: true
            wait: 10
            port: 9515
            capabilities:
                chromeOptions:
                    args:
                        ["--headless", "--disable-gpu"]
                    binary: "/usr/bin/google-chrome"
extensions:
    enabled:
        - \Extension\TestDb
```
