### ISSUE TITLE
Doctrine mapping issue only in tests

### ISSUE THREAD

**Issue by SchabrechtsK** [Codeception/Codeception#4683]
#### What are you trying to achieve?
Test my Api calls. 
So any postman request will correctly output json, the tests for api suite however will fail on `seeResponseIsJson` because it for some reason returns HTML with an error on the Doctrine mapping. Only happens within codeception.

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
1) LoginControllerCest: See if i can login
 Test  tests/api/Apibundle/Controller/LoginControllerCest.php:tryToTest
 Step  See response is json
 Fail  Invalid json: <!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <title>    [Semantical Error] The annotation &quot;@Doctrine\ORM\Mapping\Id&quot; in property AppBundle\Entity\User::$id does not exist, or could not be auto-loaded. (500 Internal Server Error)
</title>
...
```
> Provide test source code if related

```php
<?php
namespace test\Apibundle\Controller;

use test\ApiTester;

class LoginControllerCest
{
    public function _before(ApiTester $I)
    {
    }

    public function _after(ApiTester $I)
    {
    }

    // tests
    public function tryToTest(ApiTester $I)
    {
        $I->wantTo('see if I can login');
        $I->sendAjaxPostRequest('api/login');
        $I->seeResponseIsJson();
    }
}
```
### Details

* Codeception version: 2.3.6
* PHP Version: PHP 7.0.18-0ubuntu0.16.10.1 (cli) ( NTS )
* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`):
```
"require": {
        "php": ">=7.0",
        "symfony/symfony": "3.2.*",
        "api-platform/core": "^2.0",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^3.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "dunglas/action-bundle": "^0.3",
        "nelmio/cors-bundle": "^1.4",
        "phpdocumentor/reflection-docblock": "^3.0",
        "friendsofsymfony/user-bundle": "~2.0",
        "eightpoints/guzzle-bundle": "^5.3",
        "sg/datatablesbundle": "1",
        "stof/doctrine-extensions-bundle": "^1.2",
        "poken/sdk": "dev-master#8a46fbaf0ac51ce2030e41740bde451c0f0fa2e4",
        "leezy/pheanstalk-bundle": "3.1",
        "twig/extensions": "^1.5",
        "lexik/translation-bundle": "~4.0",
        "wamania/zip-streamed-response-bundle": "^1.0",
        "codeception/codeception": "^2.3",
        "behat/behat": "^3.3",
        "behat/symfony2-extension": "^2.1",
        "behat/mink": "^1.7",
        "behat/mink-goutte-driver": "^1.2",
        "behat/mink-extension": "^2.2",
        "behat/mink-selenium2-driver": "^1.3",
        "behatch/contexts": "^2.7",
        "graylog2/gelf-php": "^1.5",
        "knplabs/doctrine-behaviors": "~1.1",
        "a2lix/translation-form-bundle": "^2.1"
    },
    "require-dev": {
        "api-platform/schema-generator": "^1.2",
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0",
        "phing/phing": "^2.16",
        "squizlabs/php_codesniffer": "^2.8",
        "phpunit/phpunit": "^5.0",
        "doctrine/doctrine-fixtures-bundle": "^2.3"
    },
```
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - \test\Helper\Api
        - Symfony:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'
        - REST:
            url: /
            depends: Symfony
        - Doctrine2:
            depends: Symfony
            cleanup: true # All doctrine queries will be wrapped in a transaction, which will be rolled back at the end of each test
```
