### ISSUE TITLE
codecept clean is not recursive

### ISSUE THREAD

**Issue by davidnewcomb** [Codeception/Codeception#4685]
When you run `codecept clean` it only cleans the current project. It ignores the `include` directives in the `codeception.xml`.
When you run `codecept run` it recurses into the project folders (listed in `include`) and runs their tests. Clean should do the same.

### Details

* Codeception version: 2.3.7
* PHP Version: 5.6
* Operating System: Mac
* Installation type: Composer

**yii-application/codeception.yml**

```yml
# global codeception file to run tests from all apps
include:
    - common
    - frontend
    - backend
paths:
    log: console/runtime/logs
settings:
    colors: true
```

**yii-application/frontend/codeception.yml**

```yml
namespace: frontend\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'
```

Currently you have to go into each folder and run a separate clean command for each sub-project or you have to specify which project you are talking about e.g. `codecept clean -- -c frontend`. While that works, it does mean you have to keep track of your sub-projects externally as well as having them listed in the `codeception.yml` top level file.
