### ISSUE TITLE
WebDriver $I->fillField() incompatible with Chrome 63 headless and chromedriver 2.34

### ISSUE THREAD

**Issue by still-dreaming-1** [Codeception/Codeception#4692]
#### What are you trying to achieve?
WebDriver code: `$I->fillField(array('id' => $elementId), $textToFillItWith);` should not trigger an error for a valid page with that id for an element you can fill with text. In this case we are using it with a username text box.
#### What do you get instead?
Codeception error: `element with id 'x' was not found.` (x is in place of the id, but it actually shows the real id in this message).

### Details

* Codeception version: 2.3.7 (also tested with 2.3.6, same error)
* PHP Version: 7.1
* Operating System: Ubuntu 16.04.3 LTS
* Installation type: Composer
* Suite configuration:

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
extensions:
    enabled:
        - Codeception\Extension\RunProcess:
            0: ./test_dependencies/chromedriver-2.34/chromedriver --url-base=/wd/hub
            sleep: 1
modules:
    enabled:
        - WebDriver:
            url: 'https://the.url.i.am.testing.com/'
            browser: chrome
            window_size: false
            port: Y(actual port number in file)
            capabilities:
                chromeOptions:
                    args: ["--headless", "--disable-gpu"]
                    binary: "/usr/bin/google-chrome"
        - \Helper\Acceptance
```
As you can see we are using Chrome in headless mode. This was working until we updated to Chrome 63.0.3239.84 and chromedriver 2.34 (which is required for Chrome 63). When this was all working we were on Chrome 62.0.3202.94-1 and chromedriver 2.32. [Here is a change](https://sites.google.com/a/chromium.org/chromedriver/downloads) that stands out to me for chromedriver 2.33: 

> Updates to FindElement command as per new w3c spec.

This is the spec Google is going off for FindElement: https://w3c.github.io/webdriver/webdriver-spec.html#dfn-find-element

Apparently this is what they changed: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1985

They changed the type of error message returned for problems with the input parameters.

If I change my code to search for a 'name' instead of an 'id', I get the same kind of error message, except it cannot find an element with that name.
