### ISSUE TITLE
Appium driver with codeception and web driver on testobject

### ISSUE THREAD

**Issue by saiedtrife** [Codeception/Codeception#4693]
I am trying to use appium-driver with codeception, and also I will need to use webdriver to run on testobject (to test on real device).

I have to yml file:

1-first one is in _envs for testobject configuration:
```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            depends: \Appium\AppiumDriver
            url: 'https://google.com'
            host: 'eu1.appium.testobject.com'
            port: 80
            browser: chrome
            capabilities:
                testobject_api_key: '59C5F26F52F947E78CE8EFDFAF019599'
                platformName: 'Android'
                platformVersion: '7'
                testobject_device: Samsung_Galaxy_Note_II_N7100_real
                testobject_appium_version: 1.7.1
```
and second its on acceptance.suit.yml:
```yml
class_name: AcceptanceTester
modules:
    enabled:
            - \Appium\AppiumDriver
            - Asserts
            - Mailer
            - \Helper\Acceptance
```
when I am trying to run the test on testobject like this:

`vendor/bin/codecept run tests/acceptance/testCept.php  -vvv --env testobject`

I am getting:
```
 [Codeception\Exception\ModuleConflictException]                                                      
  Appium\AppiumDriver module conflicts with WebDriver                                                  

  --                                                                                                   
  **This usually happens when you enable two modules with the same actions but with different backends.  
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one suite,                    
  as they implement similar methods but use different drivers to execute them.                         
  You can load a part of module (like: ORM) to avoid conflict.**
```
is there anyway work around to solve this conflict ?
