### ISSUE TITLE
AppKernel name only

### ISSUE THREAD

**Issue by Mark1Z** [Codeception/Codeception#4695]
```php
# codeception/codeception/src/Codeception/Module/Symfony.php:282

        $possibleKernelClasses = [
            'AppKernel', // Symfony Standard
            'App\Kernel', // Symfony Flex
        ];
        foreach ($possibleKernelClasses as $class) {
            if (class_exists($class)) {
                $refClass = new \ReflectionClass($class);
                if ($refClass->getFileName() === $file->getRealpath()) {
                    return $class;
                }
            }
        }

        throw new ModuleRequireException(
            __CLASS__,
            "Kernel class was not found in $file. "
            . "Specify directory where file with Kernel class for your application is located with `app_path` parameter."
        );
```
### Details
Code listed above disables possibility to run tests with kernels named different than AppKernel.

* Codeception version: 2.3.7
* PHP Version: 7.1.9
* Operating System: Linux Ubuntu
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

**Comment by VolCh** [comment]
What kernel name causes a problem?

**Comment by DavertMik** [comment]
I think if it causes a problem kernel name should be added to the config.

**Comment by Mark1Z** [comment]
I'm using app/Kernels/Frontend/FrontendKernel and yml config:
```yml
class_name: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: '../../app/Kernels/Frontend'
            var_path: '../../var'
            environment: 'test'
        - Doctrine2:
            depends: Symfony
        - \frontend\Helper\Functional
```

and got error from codeception:

Kernel class was not found in /var/www/html/tests/white_label/../../app/Kernels/WhiteLabel/WhiteLabelKernel.php. Specify directory where file with Kernel class for your application is located with `app_path` parameter.

If I add FrontendKernel here:
```php
$possibleKernelClasses = [
            'FrontendKernel',
            'AppKernel', // Symfony Standard
            'App\Kernel', // Symfony Flex
        ];
```
all seems to be fine. As I see, this code was added for symfony 4 in one of last commits, because it was working for me before.
