### ISSUE TITLE
`browser: firefox` ignored when `chromeOptions:` present (in acceptance.suite.yml)

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#4702]
#### What are you trying to achieve?
Use Firefox

#### What do you get instead?
Chrome

### Details

* Codeception version: 2.3.7
* Operating System: Windows 10
* Suite configuration:

```yml
class_name: AcceptanceTester
extensions:
    enabled:
        - Codeception\Extension\RunProcess:
            - java -jar "..."
modules:
    enabled:
        - Symfony:
            part: services
        - Doctrine2:
            depends: Symfony
            cleanup: false
        - WebDriver:
            url: '...'
            browser: firefox
            window_size: 1400x1000
            wait: 5
            capabilities:
                chromeOptions:
# As soon as I uncomment these two lines, I get Chrome (i.e. `browser:` setting from above gets ignored).
# When I leave them commented out, I get Firefox.
#                    prefs:
#                        download.default_directory: "..."
        - Asserts
        - \Helper\Acceptance

```
