### ISSUE TITLE
REST sendGET() change url if called multiply in same test

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4708]
#### What are you trying to achieve?
`sendGET()` still work
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
class NoticeCest
{
    public function tryToGetNotice(FunctionalTester $I)
    {
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('notice'); // v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // v1/v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // v1/v1/v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // v1/v1/v1/v1/notice in $_SERVER['REQUEST_URI']
    }
}
```
### Details

* Codeception version: v2.3.6
* PHP Version: 7.2
* Operating System: Debian Scrutch
* Installation type:  Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
suite_namespace: api\tests\functional
actor: FunctionalTester
modules:
    enabled:
        - Asserts
        - \api\tests\Helper\Functional
        # add a framework module here
        - REST:
            url: v1/
            depends: Yii2
        - \bscheshirwork\Codeception\Module\DbYii2Config:
            dump: ../common/tests/_data/dump.sql #relative path from "codeception.yml"
            populate: true
            cleanup: true
        - Yii2
```

**Comment by Naktibalda** [comment]
Does it help if you change your `REST: url:` setting to `url: /v1/` ?

**Comment by bscheshirwork** [comment]
fresh 2.3.8 Codeception produced
```php
class NoticeCest
{
    public function tryToGetNotice(FunctionalTester $I)
    {
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('notice'); // /v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // /v1/v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // /v1/v1/v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // /v1/v1/v1/v1/notice in $_SERVER['REQUEST_URI']
    }
}
```
I try set 
> REST: url: setting to url: /v1/ 

well
```php
class NoticeCest
{
    public function tryToGetNotice(FunctionalTester $I)
    {
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendGET('notice'); // /v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // /v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // /v1/notice in $_SERVER['REQUEST_URI']
        $I->sendGET('notice'); // /v1/notice in $_SERVER['REQUEST_URI']
    }
}
```

**Comment by bscheshirwork** [comment]
```yml
suite_namespace: api\tests\functional
actor: FunctionalTester
modules:
    enabled:
        - Asserts
        - \api\tests\Helper\Functional
        # add a framework module here
        - \bscheshirwork\Codeception\Module\DbYii2Config:
            dump: ../common/tests/_data/dump.sql #relative path from "codeception.yml"
            populate: true
            cleanup: true
        - REST:
            url: /v1/
            depends: Yii2 # module with depends of Yii2 will be set after module DbYii2Config
        - Yii2:
            cleanup: true # remove fixture in Module\Yii2::_after and load fixture in  Module\Yii2::_before. In this case data from fixtures insert to db AFTER DbYii2Config populate
            transaction: true # enable directly
            forceLoadFixtures: true
```
