### ISSUE TITLE
Failed to load custom profile with selenium grid

### ISSUE THREAD

**Issue by nymo** [Codeception/Codeception#4716]
#### What are you trying to achieve?
Load a custom firefox profile when running codeception on a selenium grid.
#### What do you get instead?
Tmp profile is loaded instead: Capabilities [{moz:profile=C:\Users\SA-W7Selenium\AppData\Local\Temp\4\rust_mozprofile.PCUWmeWRMzIj
> Provide console output if related. Use `-vvv` mode for more details.

```bash
[Facebook\WebDriver\Exception\UnknownServerException]
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'W2KSELENIUM5', ip: '192.168.50.47', os.name: 'Windows Server 2008 R2', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_131'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{moz:profile=C:\Users\SA-W7Selenium\AppData\Local\Temp\4\rust_mozprofile.PCUWmeWRMzIj, rotatable=false, timeouts={implicit=0.0, pageLoad=300000.0, script=30000.0}, pageLoadStrategy=normal, moz:headless=false, platform=ANY, proxy=Proxy(manual, http=webproxy.schmid.local:8080), moz:accessibilityChecks=false, acceptInsecureCerts=false, browserVersion=57.0.3, platformVersion=6.1, moz:processID=3864.0, browserName=firefox, javascriptEnabled=true, platformName=windows_nt, moz:webdriverClick=false}]
Session ID: 310e2420-ff33-40c2-a304-21ebf677b6fc

```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.3.6
* PHP Version: 5.6
* Operating System: Windows
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Asserts
    config:
        WebDriver:
            url: https://www.remotewebsite.com
            host: jenkins
            browser: firefox
            window_size: maximize
            clear_cookies: true
            capabilities:
                unexpectedAlertBehaviour: 'accept'
                firefox_profile: 'C:\\seleniumdriver\\profile.zip.b64'
```
