### ISSUE TITLE
Implement FirefoxProfile from php-webdriver

### ISSUE THREAD

**Issue by klokocka** [Codeception/Codeception#4730]
#### What are you trying to achieve?

Be able to dynamically control Firefox profile (creation, preferences, extensions, etc.) from Codeception as I can do in [php-webdriver](https://github.com/facebook/php-webdriver/wiki/FirefoxProfile).

Is there a way to call those php-webdriver functions from acceptance.suit.yml or elsewhere?

#### What do you get instead?

The only way how I am able to interact with the firefox profile is loading a pre-created static profile.

### Details

* Codeception version: Codeception 2.3.6
* PHP Version: PHP 5.6.30
* Operating System: Debian GNU/Linux 8 (jessie)"
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Asserts
    config:
        WebDriver:
            url: https://www.remotewebsite.com
            host: jenkins
            browser: firefox
            window_size: maximize
            clear_cookies: true
            capabilities:
                unexpectedAlertBehaviour: 'accept'
                firefox_profile: 'C:\\seleniumdriver\\profile.zip.b64'
```
