### ISSUE TITLE
Can't run single test from the main project when "include" is present in codeception config

### ISSUE THREAD

**Issue by AdrianSkierniewski** [Codeception/Codeception#4733]
Hi,

I have the main project with codeception tests, but besides that, I have some packages inside vendor dir with their own tests too. I'd like to run some tests from the main project by specifying their path.
When I run all tests, everything works. Tests from main projects are run before those from the vendor dir. But when I just want to run a single test from the main project I'm getting an error below:
```
 Suite 'tests/unit/ExampleUnitTest.php' could not be found 
``` 
Here is the exact command:
```
/var/www$ ./vendor/bin/codecept run tests/unit/ExampleUnitTest.php 
```
To fix this issues I need to remove include section from my codeception config.
I tried to debug why this happening and I found that when I have "includes" in my cfg it doesn't run this part https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Command/Run.php#L325

### Details

* Codeception version: 2.3.7
* PHP Version: 7.1
* Suite configuration:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
coverage:
    enabled: true
    remote: false
    include:
        - app/Http/*
        - app/User.php
    exclude:
        - app/Http/Kernel.php
#include:
#    - vendor/xxx/yyyy  # it works when I comment those out
#    - vendor/xxx/zzz    
settings:
    bootstrap: _bootstrap.php
    lint: true
    shuffle: true
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed

```
