### ISSUE TITLE
 Class '\Helper\Unit' not found 

### ISSUE THREAD

**Issue by allen0817** [Codeception/Codeception#4734]
> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
<?php
class AppTest extends \Codeception\Test\Unit
{
    public function testValidation()
    {

    }
}
```
### Details
Uncaught Error: Class '\Helper\Unit' not found in C:\Users\Administrator\AppData
\Roaming\Composer\vendor\codeception\codeception\src\Codeception\Configuration.p
hp:313

* Codeception version:2.3
* PHP Version:7.0.12
* Operating System:windows
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
unit.suite.yml
actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
```
