### ISSUE TITLE
Wrong order of loaded modules

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4746]
#### What are you trying to achieve?
I prepare this config `functional.suite.yml`
```yml
suite_namespace: api\tests\functional
actor: FunctionalTester
modules:
    enabled:
        - Asserts
        - \api\tests\Helper\Functional
        # add a framework module here
        - REST:
            url: v1/
            depends: Yii2
        - \bscheshirwork\Codeception\Module\DbYii2Config:
            dump: ../common/tests/_data/dump.sql #relative path from "codeception.yml"
            populate: true
            cleanup: true
        - Yii2:
            cleanup: true # remove fixture in Module\Yii2::_after and load fixture in  Module\Yii2::_before. In this case data from fixtures insert to db AFTER DbYii2Config populate
            transaction: false # true = SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
            #transaction: true # enable directly
            forceLoadFixtures: true
```
I expect 
Modules put to storage (and will be run all time `foreach ($this->modules as $module)` in `/src/Codeception/Subscriber/Module.php` ) in this order:
```
        Asserts
        \api\tests\Helper\Functional
        REST
        \bscheshirwork\Codeception\Module\DbYii2Config
        Yii2
```

#### What do you get instead?
https://github.com/Codeception/Codeception/blob/1e7e9efe81f2ede1852e96ffe2526f9d0fd77023/src/Codeception/Subscriber/Module.php#L36
$suite->getModules() return this order
```
        Asserts
        \api\tests\Helper\Functional
        REST
        Yii2
        \bscheshirwork\Codeception\Module\DbYii2Config
```
I think this `depends`
```yml
        - REST:
            depends: Yii2
```
move the Yii2 module up.
 

### Details

* Codeception version: c746b57
* PHP Version:7.2.1
* Operating System:debian scratch
* Installation type: Composer on Docker image
* List of installed packages (`composer show`)
* Suite configuration:
