### ISSUE TITLE
Db module and utf8 characters in output

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4750]
#### What are you trying to achieve?
I try to use 
```
$I->seeInDatabase('user', ['username' => 'Юзер кирилицей']);
```
My Cest file is a utf8
I expect see simple text in output

#### What do you get instead?

I can see u-codes in output. This is correct?
```bash
cenario --
  [yii\db\Connection::open] 'Opening DB connection: mysql:........'
  [Database] Transaction started
 I see in database "user",{"username":"Юзер кирилицей"}
  [Query] SELECT count(*) FROM `user` WHERE `username` = ? 
  [Parameters] ["u042eu0437u0435u0440 u043au0438u0440u0438u043bu0438u0446u0435u0439"]
 FAIL 

  [Database] Transaction cancelled; all changes reverted.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 6.64 seconds, Memory: 18.00MB

There was 1 failure:

---------
1) .......
 Step  See in database "user",{"username":"Юзер кирилицей"}
 Fail  No matching records found for criteria {"username":"\u042e\u0437\u0435\u0440 \u043a\u0438\u0440\u0438\u043b\u0438\u0446\u0435\u0439"} in table user
Failed asserting that 0 is greater than 0.

 1. $I->seeInDatabase("user",{"username":"Юзер кирилицей"}) at .........

/repo/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:117
/repo/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:62
/repo/vendor/phpunit/phpunit/src/Framework/Assert.php:2116
/repo/vendor/phpunit/phpunit/src/Framework/Assert.php:687
/repo/src/Codeception/Util/Shared/Asserts.php:86
/repo/src/Codeception/Module/Db.php:481
/repo/src/Codeception/Step.php:260
/repo/src/Codeception/Scenario.php:72
........
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:2.3
* PHP Version:7.2.1
* Operating System:Debian scrutch
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
suite_namespace: api\tests\functional
actor: FunctionalTester
modules:
    enabled:
        - Asserts
        - \api\tests\Helper\Functional
        # add a framework module here
        - \bscheshirwork\Codeception\Module\DbYii2Config:
            dump: ../common/tests/_data/dump.sql #relative path from "codeception.yml"
            populate: true
            cleanup: true
        - REST:
            url: v1/
            depends: Yii2
        - Yii2:
            cleanup: true # remove fixture in Module\Yii2::_after and load fixture in  Module\Yii2::_before. In this case data from fixtures insert to db AFTER DbYii2Config populate
            transaction: false # true = SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
            #transaction: true # enable directly
            forceLoadFixtures: true
```
