### ISSUE TITLE
assertInstanceOf produce double slashes

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4751]
#### What are you trying to achieve?
assertInstanceOf display correct class name
#### What do you get instead?
assertInstanceOf display double slashes
for example in Cest class
```php
        $I->assertInstanceOf(self::class, $this);
```
produced someone like this
```bash
... 
I assert instance of "api\tests\functional\SomeCest","api\\tests\\functional\\SomeCest"
 PASSED 
...
```
### Details

* Codeception version:2.3
* PHP Version:7.2.1
* Operating System:
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
suite_namespace: api\tests\functional
actor: FunctionalTester
modules:
    enabled:
        - Asserts
...
```
