### ISSUE TITLE
Debian on php 7.2 image have problem with libssl-dev; we can use Alpine3.7 with libressl

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4757]
#### What are you trying to achieve?
I try to enable code coverage with https throw set `remote_context_options`
I have error with 
https://github.com/Codeception/Codeception/blob/be8a6a5c642f267650f56a00931640e46f880e07/src/Codeception/Coverage/Subscriber/LocalServer.php#L131-L133

#### What do you get instead?

```bash
  [PHPUnit\Framework\Exception (2)]                                                                                                                                                                 
  file_get_contents(): Unable to set local cert chain file `/var/www/html/api/tests/_data/client01.crt'; Check that your cafile/capath settings include details of your certificate and its issuer  
```
So... I change base image to alpine 3.7
https://github.com/bscheshirwork/docker-codeception-yii2/blob/alpine3.7/Dockerfile
error with "Unable to set local cert chain file" gone away.

This is example for difference between test environment and production environment. I think we can use codeception with alpine image (too) for this reason (same environment, same behavior).

### Details

* Codeception version:2.3
* PHP Version:7.2.1
* Operating System: debian:stretch-slim
* Installation type: Composer
* Suite configuration:

```yml
namespace: api\tests
actor_suffix: Tester
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'
coverage:
    # from nginx-conf-test/nginx.conf
    c3_url: https://dev.api:8084/index-test.php
    remote_context_options:
        ssl:
            verify_peer: true
            allow_self_signed: true
            cafile: /var/www/html/api/tests/_data/ca.crt
            local_cert: /var/www/html/api/tests/_data/client01.crt
            local_pk: /var/www/html/api/tests/_data/client01.key
            #passphrase: 'client01 crt example pass phrase'
    # redefine `php-code/codeception.yml` for `c3.php`. Relative to `c3.php` dir:
    remote_config: api/codeception.yml
    enabled: true
    include:
        - common/controllers/*
        - common/models/*
        - modules/v1/*
    exclude:
        - config/*
        - rest/*
        - runtime/*
        - tests/*

```

related 
#3760
https://github.com/docker-library/php/issues/564
