### ISSUE TITLE
Laravel5 module - testing cross multiple database connections

### ISSUE THREAD

**Issue by sazo** [Codeception/Codeception#4761]
#### What are you trying to achieve?
Trying to make test cross database connections using the Laravel5 module. It only starts transactions for the default connection ATM.

#### What do you get instead?
Did not want to copy our massive non-trivial output - so will show it with a quick fx. 

Testing on a non-default database connect is not rolled back

```php
class Product extend Illuminate\Database\Eloquent\Model {
       $connection = 'default'
}

class Payment extend Illuminate\Database\Eloquent\Model {
       $connection = 'payment'
}

class Test {
    public function testProduct(){
          factory(Product::class)->create();
          $this->tester->seeNumRecords(1, Product::class);
    }

    public function testProductWorksWithTransactions(){
          factory(Product::class)->create();
          $this->tester->seeNumRecords(1, Product::class);
    }

    public function testPayment(){
          factory(Payment::class)->create();
          $this->tester->seeNumRecords(1, Payment::class);
    }

    public function testPaymentFailesSeesToRecords(){
          factory(Payment::class)->create();
          $this->tester->seeNumRecords(1, Payment::class);
    }
}
```

### Details

* Codeception version: 2.3.7
* PHP Version: 7.0
* Operating System: Linux
* Installation type: Composer
* Suite configuration:

```yml
actor: GraphQLTester
modules:
    enabled:
        - \App\Administration\TestExamples\Tests\Helper\GraphQL
        - Asserts
        - Laravel5:
            environment_file: .env.testing
            root: '../../../'
```

#### Suggestions
I have thought of a solution :
Make a new configuration variable 'database_transactions' which specific what database connections you are testing. The configuration could also bee additonal database. But it makes it more flexible if you have the explicitly options.
So if no 'database_transactions' just start the default database connection

```yml
actor: GraphQLTester
modules:
    enabled:
        - \App\Administration\TestExamples\Tests\Helper\GraphQL
        - Asserts
        - Laravel5:
            environment_file: .env.testing
            root: '../../../'
            database_transactions: 
                - default
                - payment
```
