### ISSUE TITLE
Error reporting for LAST include test suite forgot prefix of test folder

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4764]
#### What are you trying to achieve?
full path (relative) to Cest file in each case  
for example
```sh
1) FirstErrorCest: Ensure that works
 Test  ../frontend/tests/acceptance/FirstErrorCest.php:test
...
2) SecondErrorCest: Ensure that works
 Test  ../backend/tests/acceptance/SecondErrorCest.php:test
```
for all case, independence of order of include

#### What do you get instead?
full path for first 
split to `test/...`

first
```bash
1) FirstErrorCest: Ensure that works
 Test  ../frontend/tests/acceptance/FirstErrorCest.php:test
...
2) SecondErrorCest: Ensure that works
 Test  tests/acceptance/SecondErrorCest.php:test

```
second
```bash
1) SecondErrorCest: Ensure that works
 Test  ../backend/tests/acceptance/SecondErrorCest.php:test
...
2) FirstErrorCest: Ensure that works
 Test  tests/acceptance/FirstErrorCest.php:test
```
third
```sh
1) FirstErrorCest: Ensure that works
 Test  ../frontend/tests/acceptance/FirstErrorCest.php:test
...
2) SecondErrorCest: Ensure that works
 Test  ../backend/tests/acceptance/SecondErrorCest.php:test
```

### Details

* Codeception version:2.3
* PHP Version:7.2.1
* Operating System:alpine
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

first
```yml
# global codeception file to run tests from all apps
include:
    - common
    - api
    - frontend
    - backend
paths:
    log: console/runtime/logs
settings:
    colors: true
coverage:
    enabled: true
```
second
```yml
# global codeception file to run tests from all apps
include:
    - common
    - api
    - backend
    - frontend
paths:
    log: console/runtime/logs
settings:
    colors: true
coverage:
    enabled: true
```
third
```yml
# global codeception file to run tests from all apps
include:
    - common
    - frontend
    - backend
    - api
paths:
    log: console/runtime/logs
settings:
    colors: true
coverage:
    enabled: true
```
