### ISSUE TITLE
Issue running tests as group with custom DB module

### ISSUE THREAD

**Issue by sunomad** [Codeception/Codeception#4774]
#### What are you trying to achieve?
I want to run a few tests from a single Cest file as a group, using @group annotation, and get a normal output saying all tests have passed: 
```bash
OK (5 tests, xx assertions)
```

#### What do you get instead?
While all tests run and pass, I get this output: 

```bash
Acceptance Tests (5) -----------------------------------------------------------------------------------------------------------------------------------
✔ SomethingCest: Test description 1 (26.39s)
✔ SomethingCest: Test description 2 (12.03s)
✔ SomethingCest: Test description 3 (11.62s)
✔ SomethingCest: Test description 4 (21.49s)
✔ SomethingCest: Test description 5 (5.02s)
--------------------------------------------------------------------------------------------------------------

[Codeception\Exception\ModuleConfigException]                     
Db module is not configured!                                      
                                                                    
Options: dsn, user, password are required                         
Please, update the configuration and set all the required fields
```
This message is not wrong, the DB module is not configured. But that is because I extended it to be compatible with our sharded database. So why would this exception be thrown? 
Running the whole Cest file at once works fine. 

### Details

* Codeception version: 2.3.8
* PHP Version: 7.1.13
* Operating System: Ubuntu 16.04
* Installation type: Phar 
* codeception.yml:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        \Helper\DbSharding:  # This helper class is extending Codeceptions Db module, so all configuration options are the same
            dsn: 'mysql:host=%DB_HOST%;dbname=%DB_DATABASE%;charset=utf8'   
            user: '%DB_USERNAME%'
            password: '%DB_PASSWORD%'
            dump: dump.sql                  # we dont use a dump because the file would be too big
            populate: false
            cleanup: false
params:
    - .env    # to get params from .env (Laravel style)
```
