### ISSUE TITLE
$I->maximizeWindow(); don't work in _before or in test.

### ISSUE THREAD

**Issue by petrisorionel** [Codeception/Codeception#4776]
#### What are you trying to achieve?

I'm trying to maximize window chrome by using $I->maximizeWindow(); in _before or in test.

#### What do you get instead?

Chrome window don't maximize.

> Provide test source code if related

```php
$I->amOnPage('/');
$I->wait(20);
```
### Details

* Codeception version: 
* PHP Version: 
* Operating System: macOS High Sierra
* Installation type: Phar 
* Suite configuration:

```yml
# acceptance.suite.yml
class_name: AcceptanceTester
modules:
    enabled:
      - WebDriver
      - \Helper\Acceptance
      - Asserts
    config:
        WebDriver:
            url: http://www.google.com
            port: 4444
            browser: 'chrome'

# codeception.yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```
