### ISSUE TITLE
Transactional tests is not considering sequence in Postresql. Yii2

### ISSUE THREAD

**Issue by StalkAlex** [Codeception/Codeception#4777]
#### What are you trying to achieve?
I have two functional suites. `RegistrationCest` and `LoginCest`. First suite uses fixtures, it creates fake users. When first suite run, user table contains several users from fixture and one admin record. Important thing is admin was created by app init script before test run and when suite started it was already been there.
First suite runs successfully. Then in second `RegistrationCest` I get next error
```bash
[yii\db\IntegrityException] SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "user_pkey"
DETAIL:  Key (id)=(1) already exists.
```
And it's true, because admin record has id = 1.  But it's bug, during registration new user should has been created with next id = 2.  Problem is in the first test, it reset seqeunce for user table when Codeception applied fixtures and then didn't restore them back.

If I run RegistrationCest alone, it runs ok.

### Details

* Codeception version: 2.37
* PHP Version: 7.1
* Operating System: Alpine
* Installation type: Composer

```yml
class_name: FunctionalTester
modules:
    enabled:
      - Filesystem
      - Yii2
      - REST
      - Asserts
#      - Db
    config:
        Yii2:
            configFile: 'tests/codeception/_config/functional.php'
            transaction: true
            cleanup: false
        REST:
            depends: Yii2
```
