### ISSUE TITLE
Firefox fail to run tests

### ISSUE THREAD

**Issue by zhex900** [Codeception/Codeception#4780]
Hi,

I am trying to run acceptance test on firebox. I can run the same tests in chrome but not in firefox. I have raise this issue with zalenium. Please refer to this [post](https://github.com/zalando/zalenium/issues/415#issuecomment-360285075). The problem seems to be with Codeception binding.

Is there a way to solve this?

* Codeception version:  2.3.7
* PHP Version: 7.2.1
* Operating System: OSX 
* Installation type: Phar 
* Selenium: docker dosel/zalenium

```yml
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
             url: https://myapp
             host: 192.168.64.2
             window_size: false 
             port: 4444
             browser: firefox # 'firefox' (port 4444) or 'firefox'  or phantomjs (port 8910)

        - \Helper\Acceptance
```
