### ISSUE TITLE
error is coming: Class Codeception\Extension\RunFailed

### ISSUE THREAD

**Issue by flik** [Codeception/Codeception#4784]
#### What are you trying to achieve?
Test should run

#### What do you get instead?
dev@development:/var/www/htdocs/mweb/codeception-zf-tutorial$ ./codecept.phar run
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
Codeception PHP Testing Framework v1.8.7
Powered by PHPUnit 3.7.37 by Sebastian Bergmann.

  [Codeception\Exception\Configuration]
  Class Codeception\Extension\RunFailed not defined. Please include it in global '_bootstrap.php' file of 'tests' directory

run [-c|--config="..."] [--report] [--html] [--xml] [--tap] [--json] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage] [--no-exit] [--defer-flush] [-g|--group="..."] [-s|--skip="..."] [--skip-group="..."] [--env="..."] [suite] [test]

> Provide console output if related. Use `-vvv` mode for more details.
dev@development:/var/www/htdocs/mweb/codeception-zf-tutorial$ ./codecept.phar run
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
Codeception PHP Testing Framework v1.8.7
Powered by PHPUnit 3.7.37 by Sebastian Bergmann.

  [Codeception\Exception\Configuration]
  Class Codeception\Extension\RunFailed not defined. Please include it in global '_bootstrap.php' file of 'tests' directory

run [-c|--config="..."] [--report] [--html] [--xml] [--tap] [--json] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage] [--no-exit] [--defer-flush] [-g|--group="..."] [-s|--skip="..."] [--skip-group="..."] [--env="..."] [suite] [test]

```bash
dev@development:/var/www/htdocs/mweb/codeception-zf-tutorial$ ./codecept.phar run
PHP Warning:  Module 'xmlreader' already loaded in Unknown on line 0
Codeception PHP Testing Framework v1.8.7
Powered by PHPUnit 3.7.37 by Sebastian Bergmann.



  [Codeception\Exception\Configuration]
  Class Codeception\Extension\RunFailed not defined. Please include it in global '_bootstrap.php' file of 'tests' directory



run [-c|--config="..."] [--report] [--html] [--xml] [--tap] [--json] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage] [--no-exit] [--defer-flush] [-g|--group="..."] [-s|--skip="..."] [--skip-group="..."] [--env="..."] [suite] [test]


```
> Provide test source code if related

```php
 // tests
    public function tryToTest(AcceptanceTester $I)
    {
		
		//$I = new TestGuy($scenario);
		$I->wantTo('check login page');
		
		$I->amOnUrl('http://darw-bo.moveon-ui.com/');
		$I->see('Email');
```
### Details

* Codeception version: Requires: PHP 5.3 and higher + CURL  1.8 Release

* PHP Version: 5.3.14
* Operating System: Windows 10
* Installation type: Phar 
* List of installed packages (`composer show`)
* Suite configuration:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
    log: tests/_logs
    actor_suffix: Tester
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=xxxxxxx'
            user: 'root'
            password: 'xxxx'
extensions:
    enabled:
        - Codeception\Extension\RunFailed

```
