### ISSUE TITLE
[Yii2] functional REST amHttpAuthenticated() not set on next calls

### ISSUE THREAD

**Issue by yurii-github** [Codeception/Codeception#4785]
#### What are you trying to achieve?
Authenticate via HTTP for all future requests in the current test

#### What do you get instead?
On first call header is set but future calls are without header

```php
    public function someTest(\FunctionalTester $I)
    {
        $I->amHttpAuthenticated('some', 'stuff');
        $I->sendGET('/some/protected/link');
        $I->seeResponseCodeIs(200);

        $I->sendGET('/some/protected/link');
       $I->seeResponseCodeIs(200); // But I see FORBIDDEN
```

workaround

```php
    public function someTest(\FunctionalTester $I)
    {
        $I->amHttpAuthenticated('some', 'stuff');
        $I->sendGET('/some/protected/link');
        $I->seeResponseCodeIs(200);

       $I->amHttpAuthenticated('some', 'stuff'); // <--- WORKAROUND
       $I->sendGET('/some/protected/link');
       $I->seeResponseCodeIs(200); 
```

### Details

Codeception version: Codeception 2.3.7
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - \Helper\Functional
        - Filesystem
        - Yii2:
            part: [orm, fixtures ]
        - REST:
            depends: Yii2

```
