### ISSUE TITLE
Unable to generate code coverage for REST module.

### ISSUE THREAD

**Issue by zeeshanbashir** [Codeception/Codeception#4792]
#### What are you trying to achieve?
I need to get code coverage for my REST module. All tests are passed but its showing 0% in code coverage report
#### What do you get instead?

![screen shot 2018-01-30 at 11 21 29 am](https://user-images.githubusercontent.com/6536027/35553101-ea54096e-05af-11e8-837c-51f5ac9b8dd5.png)

### Details
* Codeception version:2.3.7
* PHP Version: PHP 7.1.10
* Xdebug: 2.5.5
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: false
    c3_url: 'http://hub-api.tajawal.local'
    include:
        - app/*
    exclude:
        - app/Console/*
    low_limit: 30
    high_limit: 65
    remote_context_options:
        http:
            timeout: 60
        ssl:
            verify_peer: false

```

**Comment by zeeshanbashir** [comment]
@Naktibalda @DavertMik any solution for this?

**Comment by Naktibalda** [comment]
@zeeshanbashir You gave content of your codecept.yml file,
Please add configuration of suite too - which module are you using for making request?

You are making a general statement that code coverage is not working with REST module which is not true, because it works for me with:
```yml
modules:
    enabled:
        - \Helper\Functional
        - REST:
            depends: ZF1
```
