### ISSUE TITLE
ide phpstrom2017.2 unit mock method make not visible

### ISSUE THREAD

**Issue by sanchezzzhak** [Codeception/Codeception#4801]
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
E:\Server\php7\php.exe C:/Users/PHPdev/AppData/Local/Temp/ide-codeception.php run --report -o "reporters: report: PhpStorm_Codeception_ReportPrinter" --no-ansi --no-interaction -c E:\Server2\nginx\www\local-project1.dev\codeception.yml tests\unit\models\VipFallTest.php
Testing started at 13:35 ...
Codeception PHP Testing Framework v2.3.8
Powered by PHPUnit 6.5.5 by Sebastian Bergmann and contributors.


Time: 421 ms, Memory: 16.00MB

OK (1 test, 0 assertions)
```
> Provide test source code if related
```php
<?php
namespace app\tests\unit\models;
class VipFallTest extends \Codeception\Test\Unit
{
    /**
     * @var \UnitTester
     */
    protected $tester;

    protected function _before()
    {
    }

    protected function _after()
    {
    }
    public function testProcessFallStat()
    {
        $m = $this->makeEmpty('app\models\VipFall');
    }
}
```
### Details
![Screenshot](http://cropme.ru/s/i/2/6/5571f2c9.png)

* Codeception version:
* PHP Version: 7.2
* Operating System: Windows7
* Installation type: Phar version 2.3.8

```yml
# Codeception Test Suite Configuration

# suite for unit (internal) tests.
# RUN `build` COMMAND AFTER ADDING/REMOVING MODULES.
class_name: UnitTester
modules:
    enabled:
      - Asserts
      - Yii2:
          part: [init, orm, fixtures, email]
          configFile: 'tests/_config/unit.php'
```
maybe you need to configure additionally?
