### ISSUE TITLE
Codeception SF4 service already initialized

### ISSUE THREAD

**Issue by hmonglee** [Codeception/Codeception#4806]
Hello,
I'm using Codeception in SF4 project.

Here my api.suite.yml :
```yml
actor: ApiTester
modules:
    enabled:
        - Symfony:
            app_path: src
            environment: test
            em_service: doctrine.orm.client_entity_manager
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - REST:
            depends: Symfony
            part: Json
            url: 'http://localhost/api'
        - \Helper\Api
        - Asserts
```

When I launch my test I have this error : `[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException] The "doctrine.orm.client_entity_manager" service is already initialized, you cannot replace it.`

If I try again, no error. If I remove the cache, same error the first time.

Thank you for the help.
