### ISSUE TITLE
HTTP header problem

### ISSUE THREAD

**Issue by HakanDmr** [Codeception/Codeception#4810]
I just simply send POST request to my REST service! However, Codeception changes http header keys. 
Why are you changing HTTP Header keys? 
What we have to do for using custom HTTP header key names?

**HTTP Header (Expected)**
Key: X-appAuth_Key 
Key: iosAppVersion

**But got these**
Key: X-Appauth-Key
Key: Iosappversion

> Therefore, service returns HTTP 401 Unauthorized!

```php
$I = new ApiTester($scenario);
$I->wantTo('Check web service health');
$I->haveHttpHeader('X-appAuth_Key', 'xxxxxxxx');
$I->haveHttpHeader('iosAppVersion', 1000);
$I->sendPOST('ping');
$I->seeResponseCodeIs(\Codeception\Util\HttpCode::OK);
$I->seeResponseIsJson();
```
### Details

* Codeception version: v2.3.8
* PHP Version: 7.2
* Operating System: Windows
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - REST:
            url: http://xxxx.com/v2/
            depends: PhpBrowser
            part: Json
```
