### ISSUE TITLE
 Module WebHelper could not be found and loaded

### ISSUE THREAD

**Issue by flik** [Codeception/Codeception#4811]
#### What are you trying to achieve?
trying to run command build

#### What do you get instead?
```
 ./vendor/bin/codecept build
Building Actor classes for suites: acceptance, api, functional, unit

In ModuleContainer.php line 80:

  Module WebHelper could not be found and loaded


build

```

Scenario Steps:```

 ./vendor/bin/codecept build
Building Actor classes for suites: acceptance, api, functional, unit

In ModuleContainer.php line 80:

  Module WebHelper could not be found and loaded

build

```
### Details

* Codeception version: ^2.3
* PHP Version: PHP 7.0.13 (cli) (built: Nov  8 2016 13:45:28) ( ZTS )
* Operating System: Windows 10
* Installation type:   Composer
{
    "require": {
        "doctrine/orm": "*",
        "guzzlehttp/guzzle": "~6.0"
    },
    "require-dev": {
        "codeception/codeception": "^2.3"
    }
}

* Suite configuration: 

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
    log: tests/_logs
    actor_suffix: Tester
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
modules:
    config:
extensions:
    enabled:
        - Codeception\Extension\RunFailed

```

Acceptance.suite.yml
```
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: WebGuy
modules:
    enabled:
        - WebDriver
        - WebHelper
    config:
        WebDriver:
            url: 'http://github.com'
            browser: 'firefox'
```
