### ISSUE TITLE
Can't load php environment file as a param in codeception.yml

### ISSUE THREAD

**Issue by bogdan-dubyk** [Codeception/Codeception#4845]
#### What are you trying to achieve?

I want to make acceptance tests work with testing DB on pure PHP project adding custom env php file to codeception.yml

```yml
params:
    - config_testing.php
```

#### What do you get instead?

After running `build` I'm getting the error:

`[05-Mar-2018 13:59:51 UTC] PHP Warning:  array_merge(): Argument #2 is not an array in /vendor/codeception/codeception/src/Codeception/Configuration.php on line 740
[05-Mar-2018 13:59:51 UTC] PHP Stack trace:
[05-Mar-2018 13:59:51 UTC] PHP   1. {main}() /vendor/codeception/codeception/codecept:0
[05-Mar-2018 13:59:51 UTC] PHP   2. Codeception\Application->registerCustomCommands() /vendor/codeception/codeception/codecept:41
[05-Mar-2018 13:59:51 UTC] PHP   3. Codeception\Application->readCustomCommandsFromConfig() /vendor/codeception/codeception/src/Codeception/Application.php:33
[05-Mar-2018 13:59:51 UTC] PHP   4. Codeception\Configuration::config() /vendor/codeception/codeception/src/Codeception/Application.php:55
[05-Mar-2018 13:59:51 UTC] PHP   5. Codeception\Configuration::prepareParams() /vendor/codeception/codeception/src/Codeception/Configuration.php:173
[05-Mar-2018 13:59:51 UTC] PHP   6. array_merge() /vendor/codeception/codeception/src/Codeception/Configuration.php:740
`

Digging into the code I found that for .php files`ParamsLoader` using just `require` and in my case, it's returning `true` instead of file content. As I know `require` returning true only if the file is already included at this point. But I'm not using this file in other places...

* Codeception version: 2.4
* PHP Version: 7.1
* Operating System: Ubuntu 17.10 (using docker)
* Installation type: Composer
* Only codeception
* Suite configuration:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: "mysql:host=%MYSQL_HOST%:3306dbname=%MYSQL_DATABASE%"
            user: "%MYSQL_USER%"
            password: "%MYSQL_PASSWORD%"
            dump: 'tests/_data/dump.sql'
            populate: true # run populator before all tests
            cleanup: true # run populator before each test
            populator: 'mysql -u $user -h $host $dbname < $dump'
params:
    - .env.php
```
