### ISSUE TITLE
Cest function tests with @before annotations doesn't check target method annotations

### ISSUE THREAD

**Issue by ibraimedina** [Codeception/Codeception#4865]
#### What are you trying to achieve?  
I'm trying to annotate a method with `@before` targeting to a `method A`. But `method A` has a `@env` annotation that's not checked by codeception (via dependency injection).   

#### What do you get instead?
What happens is that `method A` is executed regardless env I did put in the command line.

> Provide test source code if related

```php
/**
 * @env mobile
 */
protected function methodA(AcceptanceTester $I) {
	// do anything
}

/**
 * @before methodA
 */
public function myTestMethod(AcceptanceTester $I) {
	// do anything
}
```
### Details

* Codeception version: 2.4.0
* PHP Version: 7.1.6
* Operating System: MacOS 10.13.2
* Installation type: Phar
* List of installed packages (`composer show`): not using composer
* Suite configuration: 

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - \Helper\Acceptance
```

* mobile env configuration: 

```yml
modules:
    config:
        WebDriver:
            url: http://localhost
            port: 9515
            browser: chrome
            capabilities:
                chromeOptions: # additional chrome options
                    mobileEmulation:
                        deviceName: Galaxy S5
                    args:
                        - window-size=360,640
                        - user-data-dir=tests/_userdata
                        - no-proxy-server
```
