### ISSUE TITLE
Select default environment via ENV variable

### ISSUE THREAD

**Issue by schmunk42** [Codeception/Codeception#4883]
#### What are you trying to achieve?

Run codeception commands against a (another) specific environment by default, eg. `chrome` instead of `firefox` without changing the actual suite config.

#### What do you get instead?

There is only a CLI option `--env`; I'd like to set somehing like `CODECEPTION_ENV`.

### Details

* Codeception version: 2.4.0
* PHP Version: 7.2
* Operating System: Arch Linux
* Installation type: Composer
* Suite configuration:

```yml
class_name: E2eTester
modules:
    enabled:
        - \Helper\E2e
        - WebDriver
        - Asserts
    config:
        WebDriver:
            browser: firefox
            host: firefox
            port: 4444
            window_size: 1024x768
            restart: true
            url: http://web:80/
env:
    firefox:
      modules:
        config:
          WebDriver:
            browser: firefox
            host: firefox
    # Can be configured as Docker selenium container
    chrome:
      modules:
        config:
          WebDriver:
            browser: chrome
            host: chrome
    # Can be configured from modern.ie and selenium java standalone driver
    ie:
      modules:
        config:
          WebDriver:
            browser: 'internet explorer'
            host: 192.168.99.1
            port: 14444
            window_size: 1024x768
            restart: true
            url: http://192.168.99.1:32779/

```
