### ISSUE TITLE
Collect different tests from different folders and run it

### ISSUE THREAD

**Issue by terrasoff** [Codeception/Codeception#4884]
i have multiple (nested) modules and common bootstrap. I want to organize my application next way:

[root]
-- module1
--- services
---- tests
----- functional
----- unit
-- module2
--- services
---- tests
----- functional
----- unit

Main idea is to have tests in service namespace. So i try to do it like this
**root/codeception.yml**
```yml
include:
  - module1
  - module2
```

**root/module1/codeception.yml**
```yml
namespace: module1
include:
  - services/*/tests
settings:
  bootstrap: bootstrap.php # common bootstrap
  colors: false
```
I want this **common bootstrap** to be common for all services' tests, but i have to define this file for each suite. I've a lot of services and don't want to define bootstrap for each of them. 

Is there a possibility to set up common bootstrap (and modules as well) for all services tests? No to repeat configuration. Should be a way to collect different tests from different folders and run it.
