### ISSUE TITLE
haveInRepository() for Doctrine2 module doesn't actually put entity into database

### ISSUE THREAD

**Issue by romelako** [Codeception/Codeception#4908]
I have a test where I use `haveInRepository()` to create a test entity in the database, then I visit a page which attempts to query the database for that test entity. However, it appears that haveInRepository() doesn't actually put the entity into the database.

Here is some example code:

**test:**
```
    // tests
    public function testSomeFeature()
    {
        $id = $this->tester->haveInRepository(Lead::class, [
            ... // removed for brevity
        ]);

        $this->tester->sendGET("test_database/".$id, []);
        $this->tester->seeResponseContainsJson([
            "exists"    => true
        ]);
    }
```

**controller:**
```
    /**
     * @Route("/test_database/{id}", name="test_database")
     * @param EntityManagerInterface $em
     */
    public function testDatabaseAction($id, EntityManagerInterface $em)
    {
        $lead = $em->getRepository("AppBundle:Lead")->findOneById($id);
        
        return new JsonResponse([
            "exists"    => $lead != null 
        ]);
    }
```

**response:**
```
1) TestDatabaseTest: Some feature
 Test  tests/functional/TestDatabaseTest.php:testSomeFeature
Response JSON does not contain the provided JSON

- Expected | + Actual
@@ @@
Array (
-    'exists' => true
+    'exists' => false
)

```

Is this intended?

**Comment by Naktibalda** [comment]
Which framework module do you use in functional tests?
Is Doctrine module dependent on it?

**Comment by romelako** [comment]
This is for Symfony and I'm using Doctrine2 which depends on it. Here are my settings:

```
actor: FunctionalTester
modules:
    enabled:
        # add a framework module here
        - Symfony
        - Doctrine2:
            depends: Symfony
        - REST:
            depends: PhpBrowser
            url: 'http://www.creditsite.com/app_dev.php/'
        - \Helper\Functional
```

**Comment by DavertMik** [comment]
Actually, it does:

https://github.com/Codeception/Codeception/blob/2.4/src/Codeception/Module/Doctrine2.php#L329

But tests are executed inside a transaction and rolled back afterwards, so data exists only inside a scope of a test. You are using REST client over PhpBrowser module so it connects to database externally and doesn't see this values.

I'd recommend you to use REST with Symfony2 so you could do requests internally and work with Doctrine entitines saved into transactions.

```yml
        - Doctrine2:
            depends: Symfony
        - REST:
            depends: Symfony
            url: 'http://www.creditsite.com/app_dev.php/'
```
