### ISSUE TITLE
[Yii2] how to set $_SERVER in functional tests

### ISSUE THREAD

**Issue by yurii-github** [Codeception/Codeception#4938]
#### What are you trying to achieve?
I want to set global variables, $_SERVER['REMOTE_ADDR'] for example
I've tried bootstrap, in-test, configs, etc

#### What do you get instead?
$_SERVER['REMOTE_ADDR'] stays NULL

Example:

`Yii::$app->getRequest()->getUserIP()`

Config for codeception

```yml
actor: FunctionalTester
modules:
    enabled:
        - Yii2
        - \Helper\Functional
```

I guess it is not related, but I'm using includes for codeception to run tests on several projects with one run, something like advanced template does

regards

**Comment by nnrudakov** [comment]
You can try do this through `Helper\Functional` like this (in my cases it's works):
```php
$this->getModule('Yii2')->client->setServerParameter('key', 'value');
```

**Comment by yurii-github** [comment]
@nnrudakov thanks! 

it works, but to make it work I had to add more variables

```
class Functional extends \Codeception\Module
{
    public function _before(TestInterface $test)
    {
        parent::_before($test);

        /** @var Yii2 $yii2 */
        $yii2 = $this->getModule('Yii2');
        
        $yii2->client->setServerParameters([
            'REMOTE_ADDR' => '127.0.0.1',
            'SCRIPT_FILENAME' => '@frontend/web/index.php',
            'SCRIPT_NAME' => '/index.php'
        ]);
    }
}
```

very strange

**Comment by yurii-github** [comment]
ok, checked Yii2 class, and I see that I must set config

```
modules:
    config:
        Yii2:
            entryUrl: 'https://localhost'
            entryScript: '/index.php'
            configFile: 'tests/config-test.php'
```
and use setServerParameter() because setServerParameters() just overwrites ALL other Server vars

BUT 

1. why it does not say I didn't set it?
2. why SERVER['REMOTE_ADDR'] is not set?
