### ISSUE TITLE
Old code in Composer repository

### ISSUE THREAD

**Issue by DiscipleOfShinku** [Codeception/Codeception#4973]
#### What are you trying to achieve?

Install latest version of Codeception.

#### What do you get instead?

When I run acceptance tests I get an error:
> PHP Fatal error:  Call to a member function getApplication() on null in /home/.../Yii/basic/vendor/codeception/codeception/src/Codeception/Module/Yii2.php on line 315

Turns out there is an old version of the file with no [Restore null check for client in Yii2](https://github.com/Codeception/Codeception/commit/5e3530a665ef74519c9c6f8663356d48c9da3d54) changes.
Reinstallation with Composer cache clearing did not help.

The same is with [codecept.phar](http://codeception.com/codecept.phar) file.

### Details

* Codeception version: 2.4.1
* PHP Version: 7.2.5-1+0\~20180505045740.21+stretch\~1.gbpca2fa6
* Operating System: Debian buster/sid
* Installation type: Composer
* List of installed packages (`composer show`)

> behat/gherkin                               v4.5.1   Gherkin DSL parser for PHP 5.3
> bower-asset/bootstrap                       v3.3.7   The most popular front-end framework for developing responsive, mobile first projects on the web.
> bower-asset/inputmask                       3.3.10   Inputmask is a javascript library which creates an input mask.  Inputmask can run against vanilla javascript, j...
> bower-asset/jquery                          3.2.1   
> bower-asset/punycode                        v1.3.2  
> bower-asset/typeahead.js                    v0.11.1 
> bower-asset/yii2-pjax                       2.0.7.1 
> captbaritone/mailcatcher-codeception-module 1.2.1    Test emails in your Codeception acceptance tests
> cebe/markdown                               1.1.2    A super fast, highly extensible markdown parser for PHP
> codeception/codeception                     2.4.1    BDD-style testing framework
> codeception/phpunit-wrapper                 6.0.9    PHPUnit classes used by Codeception
> codeception/specify                         0.4.6    BDD code blocks for PHPUnit and Codeception
> codeception/stub                            1.0.2    Flexible Stub wrapper for PHPUnit's Mock Builder
> codeception/verify                          0.4.0    BDD assertion library for PHPUnit
> doctrine/instantiator                       1.0.5    A small, lightweight utility to instantiate objects in PHP without invoking their constructors
> ezyang/htmlpurifier                         v4.10.0  Standards compliant HTML filter written in PHP
> facebook/webdriver                          1.5.0    A PHP client for Selenium WebDriver
> flow/jsonpath                               0.3.4    JSONPath implementation for parsing, searching and flattening arrays
> fzaninotto/faker                            v1.7.1   Faker is a PHP library that generates fake data for you.
> guzzlehttp/guzzle                           6.3.3    Guzzle is a PHP HTTP client library
> guzzlehttp/promises                         v1.3.1   Guzzle promises library
> guzzlehttp/psr7                             1.4.2    PSR-7 message implementation that also provides common utility methods
> myclabs/deep-copy                           1.7.0    Create deep copies (clones) of your objects
> phpdocumentor/reflection-common             1.0.1    Common reflection classes used by phpdocumentor to reflect the code structure
> phpdocumentor/reflection-docblock           3.3.2    With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve informat...
> phpdocumentor/type-resolver                 0.4.0   
> phpspec/php-diff                            v1.1.0   A comprehensive library for generating differences between two hashable objects (strings or arrays).
> phpspec/prophecy                            1.7.6    Highly opinionated mocking framework for PHP 5.3+
> phpunit/php-code-coverage                   4.0.8    Library that provides collection, processing, and rendering functionality for PHP code coverage information.
> phpunit/php-file-iterator                   1.4.5    FilterIterator implementation that filters files based on a list of suffixes.
> phpunit/php-text-template                   1.2.1    Simple template engine.
> phpunit/php-timer                           1.0.9    Utility class for timing
> phpunit/php-token-stream                    1.4.12   Wrapper around PHP's tokenizer extension.
> phpunit/phpunit                             5.7.27   The PHP Unit Testing framework.
> phpunit/phpunit-mock-objects                3.4.4    Mock Object library for PHPUnit
> psr/http-message                            1.0.1    Common interface for HTTP messages
> psr/log                                     1.0.2    Common interface for logging libraries
> sebastian/code-unit-reverse-lookup          1.0.1    Looks up which function or method a line of code belongs to
> sebastian/comparator                        1.2.4    Provides the functionality to compare PHP values for equality
> sebastian/diff                              1.4.3    Diff implementation
> sebastian/environment                       2.0.0    Provides functionality to handle HHVM/PHP environments
> sebastian/exporter                          2.0.0    Provides the functionality to export PHP variables for visualization
> sebastian/global-state                      1.1.1    Snapshotting of global state
> sebastian/object-enumerator                 2.0.1    Traverses array structures and object graphs to enumerate all referenced objects
> sebastian/recursion-context                 2.0.0    Provides functionality to recursively process PHP variables
> sebastian/resource-operations               1.0.0    Provides a list of PHP built-in functions that operate on resources
> sebastian/version                           2.0.1    Library that helps with managing the version number of Git-hosted PHP projects
> swiftmailer/swiftmailer                     v5.4.9   Swiftmailer, free feature-rich PHP mailer
> symfony/browser-kit                         v3.4.9   Symfony BrowserKit Component
> symfony/console                             v3.4.9   Symfony Console Component
> symfony/css-selector                        v3.4.9   Symfony CssSelector Component
> symfony/debug                               v3.4.9   Symfony Debug Component
> symfony/dom-crawler                         v3.4.9   Symfony DomCrawler Component
> symfony/event-dispatcher                    v3.4.9   Symfony EventDispatcher Component
> symfony/finder                              v3.4.9   Symfony Finder Component
> symfony/polyfill-mbstring                   v1.8.0   Symfony polyfill for the Mbstring extension
> symfony/process                             v3.4.9   Symfony Process Component
> symfony/yaml                                v3.4.9   Symfony Yaml Component
> webmozart/assert                            1.3.0    Assertions to validate method input/output with nice error messages.
> yiisoft/yii2                                2.0.15.1 Yii PHP Framework Version 2
> yiisoft/yii2-bootstrap                      2.0.8    The Twitter Bootstrap extension for the Yii framework
> yiisoft/yii2-composer                       2.0.6    The composer plugin for Yii extension installer
> yiisoft/yii2-debug                          2.0.13   The debugger extension for the Yii framework
> yiisoft/yii2-faker                          2.0.4    Fixture generator. The Faker integration for the Yii framework.
> yiisoft/yii2-gii                            2.0.7    The Gii extension for the Yii framework
> yiisoft/yii2-swiftmailer                    2.0.7    The SwiftMailer integration for the Yii framework

* Suite configuration:
```
 class_name: AcceptanceTester
 extensions:
     enabled:
         - Codeception\Extension\RunProcess:
             0: java -jar -Dwebdriver.chromium.driver="/usr/bin/chromedriver" -Dwebdriver.chrome.driver="/usr/bin/chromedriver" -Dwebdriver.gecko.driver="/opt/selenium/geckodriver" "/opt/selenium/selenium-server-standalone-3.12.0.jar"
             sleep: 5
 modules:
     enabled:
         - Db:
             dsn: 'mysql:host=localhost;dbname=yii2_basic_tests'
             user: 'root'
             password: ''
             dump: 'tests/_data/dump.sql'
             populate: true
             cleanup: false
             populator: 'mysql -u $user -h $host $dbname < $dump'
         - WebDriver:
             url: https://hotel.localhost/
             browser: chromium
         - Yii2:
             part: orm
             entryScript: index-test.php
             cleanup: false
```

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    memory_limit: 1024M
    colors: true
modules:
    config:
        Yii2:
            configFile: 'config/test.php'
            cleanup: false

# To enable code coverage:
coverage:
    enabled: true
    whitelist:
        include:
            - models/*
            - controllers/*
```
