### ISSUE TITLE
Make test fail on hook function (ex: _after())

### ISSUE THREAD

**Issue by hungtin** [Codeception/Codeception#4977]
#### What are you trying to achieve?

After the test finish I want to validate data generated from the execution of test case.
And when the validation fail, I want to mark the test was failed as well. And keep running on others testcase.

#### What do you get instead?

But if I throw Exception or call fail() function of \Codeception\Module from hook function, it will stop the whole running process. 

```bash
In Assert.php line 2627:
codeception    |
codeception    |   [PHPUnit\Framework\AssertionFailedError]
codeception    |   validation failed
codeception    |
codeception    |
codeception    | Exception trace:
codeception    |  PHPUnit\Framework\Assert::fail() at /repo/src/Codeception/Util/Shared/Asserts.php:438
codeception    |  Codeception\Module->fail() at /project/tests/_support/Helper/Assert/HookHelper.php:75
codeception    |  Helper\Assert\HookHelper->_after() at /repo/src/Codeception/Subscriber/Module.php:66
codeception    |  Codeception\Subscriber\Module->after() at /repo/vendor/symfony/event-dispatcher/EventDispatcher.php:212
codeception    |  Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /repo/vendor/symfony/event-dispatcher/EventDispatcher.php:44
codeception    |  Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /repo/vendor/codeception/phpunit-wrapper/src/Listener.php:133
codeception    |  Codeception\PHPUnit\Listener->fire() at /repo/vendor/codeception/phpunit-wrapper/src/Listener.php:119
codeception    |  Codeception\PHPUnit\Listener->endTest() at /repo/vendor/phpunit/phpunit/src/Framework/TestResult.php:409
codeception    |  PHPUnit\Framework\TestResult->endTest() at /repo/src/Codeception/Test/Test.php:111
codeception    |  Codeception\Test\Test->run() at /repo/vendor/phpunit/phpunit/src/Framework/TestSuite.php:760
codeception    |  PHPUnit\Framework\TestSuite->run() at /repo/vendor/codeception/phpunit-wrapper/src/Runner.php:114
codeception    |  Codeception\PHPUnit\Runner->doEnhancedRun() at /repo/src/Codeception/SuiteManager.php:157
codeception    |  Codeception\SuiteManager->run() at /repo/src/Codeception/Codecept.php:189
codeception    |  Codeception\Codecept->runSuite() at /repo/src/Codeception/Codecept.php:158
codeception    |  Codeception\Codecept->run() at /repo/src/Codeception/Command/Run.php:355
codeception    |  Codeception\Command\Run->execute() at /repo/vendor/symfony/console/Command/Command.php:252
codeception    |  Symfony\Component\Console\Command\Command->run() at /repo/vendor/symfony/console/Application.php:865
codeception    |  Symfony\Component\Console\Application->doRunCommand() at /repo/vendor/symfony/console/Application.php:241
codeception    |  Symfony\Component\Console\Application->doRun() at /repo/vendor/symfony/console/Application.php:143
codeception    |  Symfony\Component\Console\Application->run() at /repo/src/Codeception/Application.php:108
codeception    |  Codeception\Application->run() at /repo/codecept:42
codeception    |
codeception    | run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]
codeception    |
codeception    |
codeception    | Fatal error: Uncaught RuntimeException: Command Did Not Finish Properly in /repo/src/Codeception/Subscriber/ErrorHandler.php on line 101
codeception    |
codeception    | Call Stack:
codeception    |     0.0004     406872   1. {main}() /repo/codecept:0
codeception    |     0.0937    5449040   2. Codeception\Application->run() /repo/codecept:42
codeception    |     0.0937    5449040   3. Codeception\Application->run() /repo/src/Codeception/Application.php:108
codeception    |
codeception    | RuntimeException: Command Did Not Finish Properly in /repo/src/Codeception/Subscriber/ErrorHandler.php on line 101
codeception    |
codeception    | Call Stack:
codeception    |     0.0004     406872   1. {main}() /repo/codecept:0
codeception    |     0.0937    5449040   2. Codeception\Application->run() /repo/codecept:42
codeception    |     0.0937    5449040   3. Codeception\Application->run() /repo/src/Codeception/Application.php:108
codeception    |    20.0648   11972616   4. Codeception\Subscriber\ErrorHandler->shutdownHandler() /repo/src/Codeception/Subscriber/ErrorHandler.php:0
```
> Provide test source code if related

```php
 public function _after($test) {
   if  (!$ok) {
      $this->fail("validation failed");
   }
       
}
```
### Details

* Codeception docker container: 2.4.1

```yml
actor: AcceptanceTester
settings:
  bootstrap: _bootstrap.php
modules:
    enabled:
      - \Helper\InceptionWebDriver
      - \Helper\Acceptance
      - \Helper\Assert\DbHelper
      - \Helper\Assert\HtmlHelper
      - \Helper\Assert\MailHelper
      - \Helper\Assert\FtpHelper
      - \Helper\Assert\DownloadHelper
      - \Helper\Assert\HookHelper
      - \Helper\Assert\ScreenshotHelper
      - \Helper\Assert\AssertBaseHelper
      - MultiDb
    config:
      \Helper\InceptionWebDriver:
        url: 'https://localhost/'
        host: 'hub'
        port: 4444
        browser: chrome
        clear_cookies: false
        capabilities:
          unexpectedAlertBehaviour: 'accept'
          elementScrollBehavior: true
      MultiDb:
        connections:
          ne_user_server1:
            dsn: mysql:host=db;dbname=%E2E_TEST_SCHEMA%
            user: 'next-engine'
            password: ''
            dump: 'tests/_data/always_sql/always_ne_user_all.sql'
            populate: true
          ne_user_server2:
            dsn: mysql:host=db;dbname=%E2E_COMPARE_SCHEMA%
            user: 'next-engine'
            password: ''
            dump: 'tests/_data/always_sql/always_ne_user_all.sql'
            populate: true

```
