### ISSUE TITLE
Codeception submitForm doesn't respect name fields when using integers or "integers"

### ISSUE THREAD

**Issue by jonny7** [Codeception/Codeception#4985]
#### What are you trying to achieve?
Submit a form with this kind of make up (using Yii2):
```php
$I->submitForm('#submit-form', [
     'person' => 5,
     5 => 'Yes',
     '6' => 'No',
]); 
```
I would expect that the submitted array would maintain key value index. Especially if the index is a string, but contains integers.
#### What do you get instead?
Anything that is an integer or integer represented as a string is replaced and re-indexed from 0
```
{...,"0":"","person":5,"1":"Yes","2":"No"}
```
### Details

* Codeception version:
* PHP Version: 7.1.1
* Operating System: Windows
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: FunctionalTester
modules:
    enabled:
      - Asserts
      - Filesystem
      - Yii2:
          configFile: 'config/web.php'
          #part: [orm, fixtures] 
          transaction: true   #(default: true) wrap all database connection inside a transaction and roll it back after the test. Should be disabled for acceptance testing..
          cleanup: true  
```
