### ISSUE TITLE
havehttpheader doesn't work

### ISSUE THREAD

**Issue by a13hander** [Codeception/Codeception#5001]
#### What are you trying to achieve?

'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Mobile Safari/537.36'

#### What do you get instead?
Symfony BrowserKit

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
$I->haveHttpHeader('User-Agent', 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Mobile Safari/537.36');
$I->amOnUrl('http://localhost');
$I->seeResponseCodeIs(HttpCode::OK);
```
### Details

* Codeception version:2.4
* PHP Version:7.2
* Operating System:Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: ''
```

**Comment by Naktibalda** [comment]
A working way (we have a [test ](https://github.com/Codeception/Codeception/blob/c50789a9a62cc0eefc0252e88a5f04f8c47b55f4/tests/unit/Codeception/Module/PhpBrowserTest.php#L687)for it), is to set User-Agent header in configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: ''
            headers:
                'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Mobile Safari/537.36'
```
