### ISSUE TITLE
The report.xml file structure provided by phpunit and codeception is different

### ISSUE THREAD

**Issue by sapzape** [Codeception/Codeception#5004]
The format of the report.xml file obtained after testing with phpunit differs from the report.xml file obtained after code execution.

report sample after running phpunit
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="75" assertions="164" failures="0" errors="0" time="25.978013">
    <testsuite name="Feature Tests" tests="60" assertions="149" failures="0" errors="0" time="24.027709">
      <testsuite name="Tests\Feature\AgeCategoryTest" file="/home/travis/build/tititoof/sas_judo/tests/Feature/Admin/AgeCategoryTest.php" tests="6" assertions="19" failures="0" errors="0" time="2.349255">
        <testcase name="testIndexStatus" class="Tests\Feature\AgeCategoryTest" file="/home/travis/build/tititoof/sas_judo/tests/Feature/Admin/AgeCategoryTest.php" line="40" assertions="2" time="0.416466"/>
        <testcase name="testStoreStatus" class="Tests\Feature\AgeCategoryTest" file="/home/travis/build/tititoof/sas_judo/tests/Feature/Admin/AgeCategoryTest.php" line="50" assertions="6" time="0.503893"/>
		...
      </testsuite>
      <testsuite name="Tests\Feature\AlbumTest" file="/home/travis/build/tititoof/sas_judo/tests/Feature/Admin/AlbumTest.php" tests="5" assertions="13" failures="0" errors="0" time="3.937930">
        <testcase name="testIndexAction" class="Tests\Feature\AlbumTest" file="/home/travis/build/tititoof/sas_judo/tests/Feature/Admin/AlbumTest.php" line="28" assertions="2" time="0.333698"/>
		...
      </testsuite>
	  ...
  </testsuite>
</testsuite>
```

report sample after running codeception
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="unit" tests="41" assertions="93" errors="0" failures="0" skipped="0" time="0.285144">
        <testcase file="/home/www/test/test/tests/unit/case/model/modelTagUnitCest.php" name="testGetById" class="modelTagUnitCest" assertions="2" time="0.045005"/>
        <testcase file="/home/www/test/test/tests/unit/case/model/modelTagUnitCest.php" name="testGetAll" class="modelTagUnitCest" assertions="1" time="0.001119"/>
        <testcase file="/home/www/test/test/tests/unit/case/model/modelTagUnitCest.php" name="testInsert" class="modelTagUnitCest" assertions="1" time="0.003246"/>
        <testcase file="/home/www/test/test/tests/unit/case/model/modelTagUnitCest.php" name="testUpdate" class="modelTagUnitCest" assertions="2" time="0.032069"/>
	<testcase file="/home/www/test/test/tests/unit/case/service/Reports/serviceReportsRunUnitCest.php" name="testUpdateReportVersion" class="serviceReportsRunUnitCest" assertions="2" time="0.085060"/>
        <testcase file="/home/www/test/test/tests/unit/case/service/Tags/serviceTagsCommonUnitCest.php" name="testGetAllTag" class="serviceTagsCommonUnitCest" assertions="2" time="0.017860"/>
        <testcase file="/home/www/test/test/tests/unit/case/service/Tags/serviceTagsCommonUnitCest.php" name="testUpdateTag" class="serviceTagsCommonUnitCest" assertions="2" time="0.001434"/>
        ...
    </testsuite>
</testsuites>
```

When executed with codeception, the entire result is output as a unit under suite unit.
I am trying to link the test result to sonarqube, but it seems that the format is wrong and the failure occurs.
If I am using something wrong, I would like to ask phpunit what to do to get the results.

Below is the configuration information.

* Codeception version: 2.4.1
* PHP Version: 7.0.22
* Operating System: Window 10, CentOS 7.4.1708
* Installation type: Composer
* Suite configuration:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
    log: tests/_output
actor_suffix: Tester
coverage:
    enabled : true
    include:
      - cont/*
    # url of file which includes c3 router.
    remote_context_options:
        ssl:
            verify_peer: false
settings:
  bootstrap: bootstrap.php
  log: true
  strict_xml: true
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```
