### ISSUE TITLE
I can not include a custom method in Helper.

### ISSUE THREAD

**Issue by petrisorionel** [Codeception/Codeception#5005]
#### What are you trying to achieve?

I want to add a custom method in Helper (AcceptanceTester.php). If I add this method in another Helper is possible to user, but when I do that is not possible to use methods from AcceptanceTester helper, because AcceptanceTester extends \Codeception\Actor and I need to extend \Codeception\Module.

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Codeception\Actor::__construct(), 0 passed in /acceptance-testing/vendor/codeception/codeception/src/Codeception/Test/Loader/Cest.php on line 36 and exactly 1 expected in /acceptance-testing/vendor/codeception/codeception/src/Codeception/Actor.php:18
Stack trace:
#0 /acceptance-testing/vendor/codeception/codeception/src/Codeception/Test/Loader/Cest.php(36): Codeception\Actor->__construct()
#1 /acceptance-testing/vendor/codeception/codeception/src/Codeception/Test/Loader.php(134): Codeception\Test\Loader\Cest->loadTests('...')
#2 /acceptance-testing/vendor/codeception/codeception/src/Codeception/SuiteManager.php(95): Codeception\Test\Loader->loadTests(NULL)
#3 /acceptance-testing/vendor/codeception/codeception/src/Codeception/Actor.php on line 18
LBUO0007:acceptance-testing $ 

```
> Provide test source code if related

```php
<?php


/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void comment($description)
 * @method \Codeception\Lib\Friend haveFriend($name, $actorClass = NULL)
 *
 * @SuppressWarnings(PHPMD)
*/
class AcceptanceTester extends \Codeception\Actor
{
    use _generated\AcceptanceTesterActions;

    /**
     * Define custom actions here
     */

    public function makeScreenshotAcceptance($element, $name = null)
    {
        $webdriver = new Codeception\Module\WebDriver();
        if (empty($name)) {
            $name = $element . (date("_Y-m-d_H-i-s_"));
        }
        var_dump(codecept_log_dir());
        $screenName = codecept_log_dir() . DIRECTORY_SEPARATOR . $name . '.png';
        try {
            $this->$webdriver->_saveScreenshot($screenName);
            \Codeception\Util\Debug::debug("Screenshot saved to $screenName");
        } catch (\Exception $e)
        {
            print $e;
        }
    }

}
```
### Details

* Codeception version: 2.3
* PHP Version: 7.0
* Operating System: MAC OS
* Installation type: Composer

```yml
class_name: AcceptanceTester
modules:
    enabled:
      - WebDriver
      - \Helper\Acceptance
      - Asserts
      - Db
    config:
        WebDriver:
            url: '%PORTAL%'
            port: 4444
            browser: 'chrome'
            wait: 0.8
            clear_cookies: true
            capabilities:
                chromeOptions:
                    args: ['start-fullscreen']
                    prefs:
                        download.default_directory: 'tests/_output'
        Db:
          dsn: '%DSN%'
          user: '%DB_USERNAME%'
          password: '%DB_PASSWORD%'
          reconnect: true
```

**Comment by Naktibalda** [comment]
Why don't you add it to \Helper\Acceptance ?

**Comment by petrisorionel** [comment]
```
class_name: AcceptanceTester
modules:
    enabled:
      - \Helper\Acceptance
      - Asserts
      - Db
    config:
        \Helper\Acceptance:
            url: '%PORTAL%'
            port: 4444
            browser: 'chrome'
            wait: 0.8
            clear_cookies: true
            capabilities:
                chromeOptions:
                    args: ['start-fullscreen']
                    prefs:
                        download.default_directory: 'tests/_output'
        Db:
          dsn: '%DSN%'
          user: '%DB_USERNAME%'
          password: '%DB_PASSWORD%'
          reconnect: true

```

```
<?php
namespace Helper;

// here you can define custom actions
// all public methods declared in helper class will be available in $I

use Codeception;

class Acceptance extends Codeception\Module\WebDriver
{

    public function takeScreen($element, $name = null)
    {
        if (empty($name)) {
            $name = $element . (date("_Y-m-d_H-i-s_"));
        }
        $debugDir = codecept_log_dir() . 'debug';
        if (!is_dir($debugDir)) {
            mkdir($debugDir, 0777);
        }
        $screenName = $debugDir . DIRECTORY_SEPARATOR . $name . '.png';
        try {
            $this->_saveScreenshot($screenName);
            \Codeception\Util\Debug::debug("Screenshot saved to $screenName");
        } catch (\Exception $e)
        {
            print $e;
        }
    }
}
```

```
<?php


/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void comment($description)
 * @method \Codeception\Lib\Friend haveFriend($name, $actorClass = NULL)
 *
 * @SuppressWarnings(PHPMD)
*/
class AcceptanceTester extends \Codeception\Actor
{
    use _generated\AcceptanceTesterActions;

    /**
     * Define custom actions here
     */

}

```


And from what I see generate a function in AcceptanceTesterActions.php

```
/**
     * [!] Method is generated. Documentation taken from corresponding module.
     *
     *
     * @see \Helper\Acceptance::takeScreen()
     */
    public function takeScreen($element, $name = null) {
        return $this->getScenario()->runStep(new \Codeception\Step\Action('takeScreen', func_get_args()));
    }
```

HOW TO USE?

```
<?php

class TestCest
{
    public function LoginPage(AcceptanceTester $I)
    {
        $I->wantTo('check UI from login page.');
        $I->see('Sign in to start your session');
        $I->see('Remember Me');
        $I->see('Sign in');
        $I->see('Reset Password');
        $I->takeScreen('AllText_Found');
    }
}
```
