### ISSUE TITLE
Add new option to Recorder extension to disable recording of specified steps

### ISSUE THREAD

**Issue by sspat** [Codeception/Codeception#5014]
#### What are you trying to achieve?

Exclude some steps from the Recorder extension generated pages.
For example, when using the DataFactory module, the test record gets polluted by a lot of `have` and `haveMultiple` steps that do not produce any change on the tested page and their according screenshots are all the same.

#### What do you get instead?

Cannot do this currently by simply configuring the Recorder extension.

#### Proposal

Add a configuration option to Recorder extension to allow ignoring specified steps by their name.

```yaml
extensions:
    enabled:
        - Codeception\Extension\Recorder:
            module: WebDriver
            ignore_steps:
              - have
              - haveMultiple
```
