### ISSUE TITLE
Define ENV within Test

### ISSUE THREAD

**Issue by johannesschobel** [Codeception/Codeception#5016]
Hey @DavertMik , @Naktibalda and community,

currently, I am trying to write `Acceptance` tests for my application. However, my application has 2 different domains (i.e., realms)
* `www.example.com` : for the normal "user" interacting with the web application
* `admin.example.com` : for the administrators in order to manage the application

Both "realms" (www and admin) are maintained within one PHP application (laravel, btw)

As the overall configuration for these "realms" does not significantly differ, I created a custom environment for the acceptance tests, like so:

```yml
env:
    admin:
        modules:
            config:
                PhpBrowser:
                    url: 'http://admin.example.com'
    www:
        modules:
            config:
                PhpBrowser:
                    url: 'http://www.example.com'
```

Next, I create a `CEST` that contains my respective testing logic, like so:
```
class TestFrontPageCest
{

   public function testUserFrontPage(AcceptanceTester $I) { }
   public function testAdminFrontPage(AcceptanceTester $I) { }

}
```

Obviously, both functions **must** use their respective environment, because the `url` changes (`www` vs `admin`). How can I achieve this **programmatically**?

I am aware, that I can add annotations, like so:
```php
/**
 * @env admin
 */
public function testAdminFrontPage(...)
```
in order to execute this test method **only** when in the `--env admin` flag is added..
```bash
codecept run --env admin
```
Drawback would be, that i need to call all environments manually.. 

However, what i really would do is just call
```bash
codecept run
```
and the respective environment is automatically applied.

Does Codeception allow for something like this? Or how can i achieve this behaviour?
Thank you very much for your help! You guys are awesome!

Cheers
