### ISSUE TITLE
Trait '_generated/*TesterActions' not found

### ISSUE THREAD

**Issue by kickthemooon** [Codeception/Codeception#5017]
#### What are you trying to achieve?
Im trying to run a test,

#### What do you get instead?
Im suddenly getting this error `Trait '_generated/*TesterActions' not found`.

### Details
When I go look under _generated the file *TesterActions is still there but its empty.
It happens when codeception tries to rebuild the class.

* Codeception version: 2.2.10
* PHP Version: 7.0
* Operating System: Windows 10 / Vagrant
* Installation type: Composer

```
class_name: SomeTestTester
modules:
    enabled:
        - REST:
            url: https://domain.com/api
            depends: PhpBrowser
            part: Json
        - \Helper\ConfiguratorHelper
        - Db
        - Asserts

```

I have the feeling that it has something to do Line seperation between windows and linux 
but im not sure.
