### ISSUE TITLE
cant connect to webdriver vagrant to ubuntu server

### ISSUE THREAD

**Issue by mitch367** [Codeception/Codeception#5034]
this is probably going to be the simplest issue ever... just want someone to confirm if i need to change more codeception configuration or if its nothing to do with codeception... sorry in advance

#### What are you trying to achieve?
run tests from codeception (using vagrant) to a ubuntu server where selenium is installed

#### What do you get instead?
  [ConnectionException] Can't connect to Webdriver at http://x.x.x.x:4444/wd/hub. Please make sure that Selenium Server or PhantomJS is running.

> Provide console output if related. Use `-vvv` mode for more details.

1) GetToHomePageCest: Perform actions and see result
 Test  tests/acceptance/GetToHomePageCest.php:EPPGDPR

  [ConnectionException] Can't connect to Webdriver at http://x.x.x.x:4444/wd/hub. Please make sure that Selenium Serveror PhantomJS is running.

/home/vagrant/website/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:1429
/home/vagrant/website/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:413
/home/vagrant/website/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:56
/home/vagrant/website/vendor/symfony/event-dispatcher/EventDispatcher.php:212
/home/vagrant/website/vendor/symfony/event-dispatcher/EventDispatcher.php:44
/home/vagrant/website/vendor/codeception/phpunit-wrapper/src/Listener.php:131
/home/vagrant/website/vendor/codeception/phpunit-wrapper/src/Listener.php:100
/home/vagrant/website/vendor/phpunit/phpunit/src/Framework/TestResult.php:395
/home/vagrant/website/vendor/codeception/codeception/src/Codeception/Test/Test.php:75
/home/vagrant/website/vendor/phpunit/phpunit/src/Framework/TestSuite.php:755
/home/vagrant/website/vendor/codeception/phpunit-wrapper/src/Runner.php:106
/home/vagrant/website/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
/home/vagrant/website/vendor/codeception/codeception/src/Codeception/Codecept.php:189
/home/vagrant/website/vendor/codeception/codeception/src/Codeception/Codecept.php:158
/home/vagrant/website/vendor/codeception/codeception/src/Codeception/Command/Run.php:355
/home/vagrant/website/vendor/symfony/console/Command/Command.php:264
/home/vagrant/website/vendor/symfony/console/Application.php:874
/home/vagrant/website/vendor/symfony/console/Application.php:228
/home/vagrant/website/vendor/symfony/console/Application.php:130
/home/vagrant/website/vendor/codeception/codeception/src/Codeception/Application.php:108
/home/vagrant/website/vendor/codeception/codeception/package/bin:37
/home/vagrant/.composer/vendor/codeception/codeception/autoload.php:12
/home/vagrant/.composer/vendor/codeception/codeception/codecept:7

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

```php
public function EPPGDPR(AcceptanceTester $I)
    {
        $I->wantTo('perform actions and see result');
        $I->amOnPage('/customer/account/create/');
        $I->see('Create New Customer Account');
        $I->fillField('//*[@id="firstname"]', 'test');
        $I->fillField('//*[@id="lastname"]', 'test');
        $I->selectOption('country_id', 'BN');
        $I->fillField('//*[@id="email_address"]', 'yourname@domain.com');
        $I->fillField('//*[@id="password"]', 'hello');
        $I->fillField('//*[@id="password-confirmation"]', 'hello1');
        $I->click('//*[@id="form-validate"]/div/div[1]/button');
        $I->see('Please enter the same value again.');
        try {
            $I->fillField('//*[@id="password"]', 'This1sPassword!');
            $I->fillField('//*[@id="password-confirmation"]', 'This1sPassword!');
            $I->click('//*[@id="form-validate"]/div/div[1]/button');
        } catch (\Exception $e) {
            $I->comment('cant do this');
        }
        $I->checkOption('//*[@id="terms_of_use"]');
        $I->wait(10);

    }
```
### Details

basically we have had codeception tests running via a selenium grid on vagrant but the time came to move selenium to its own server (ubuntu), so installed selenium on it and changed to host IP and port within codeception to match, tried to run a test but it says it cant connect, not entirely sure if this is an issue with the setup on the server or if there is more we need to do to the codeception configuration...
we still have to run vagrant to run tests but it should still be able to connect to the ubuntu server... (and yes it is running)

* Codeception version: 2.4
* PHP Version: 7.0.0
* Operating System: Win7 Enterprise
* Installation type: Composer

```yml
actor: AcceptanceTester
modules:
    enabled:
#        - PhpBrowser:
        - Laravel5:
            part: ORM
            cleanup: false
        - Db:
            dsn: 'mysql:dbname=#####;host=localhost'
            user: #######
            password: ######
            cleanup: false
        - Asserts
        - \Helper\Acceptance
        - WebDriver:
            host: 'x.x.x.x' (server)
            port: 4444
            url: http://(sitename)
            window_size: 1280x768
            browser: chrome
            capabilities:
              browser_name: chrome
```
