### ISSUE TITLE
Acceptance Tests with Laravel 5 fails to load defined Environment

### ISSUE THREAD

**Issue by johannesschobel** [Codeception/Codeception#5051]
Hey @DavertMik and community,

i am trying to properly test my Laravel 5 application, I have developed. In this context, i want to unit, api and acceptance test respective platform.

While the `unit` and `api` tests work as expected, I stumbled upon a weird behaviour in the `acceptance` tests.

#### acceptance.suite.yml Configuration:
``` yml
actor: AcceptanceTester
modules:
    enabled:
        - Laravel5:
            url: 'http://app.local'
            part: ORM
            run_database_migrations: true
            run_database_seeder: true
            database_seeder_class: \TestingSeeder
            environment_file: .env.testing
        - PhpBrowser:
            url: 'http://app.local'
```
Basically, I am using using the `Laravel5` package (only the `ORM` part!) in order to boot up laravel for the requests the `acceptance tests` perform. Note that I am specifically loading the `.env.testing` environment file. This environment, in turn, defines a in-memory database, sets specific values for route-throttling, and so on.

The configuration of the suite works, I am able to "load" a specific site..
However, now I am performing an `acceptance test` to login a user, like this:
``` php
public function test_if_login_works(AcceptanceTester $I)
{
    $userdata = [
	'email' => 'admin@local.host',
        'password' => 'testing'
    ];
    
    // setup a user so we can login with respective user
    $this->createDummyUser($userdata);

    $I->amOnPage('http://app.local/login');
    $I->fillField('email', $userdata['email']);
    $I->fillField('password', $userdata['password']);
    $I->click('login');

    $I->see('Welcome Admin');
}
```

The problem is as follows.. The `createDummyUser()` method creates the `User` in the aforementioned `testing database` (which is defined in the `.env.testing` file!). Then it makes the request to the "underlying" Laravel5 application. This environment, however, **is not passed** to Laravel itself - so Laravel boots with the default `.env` environment configuration. This configuration, in turn, has another database setup. So, the actual `$I->click('login');` does not work - because there is no such user defined (at least not in **this** particular database!)

I am actually aware, that the following page (https://codeception.com/for/laravel) reads:
> Acceptance tests will be executed in development environment using real web server, so settings from `.env.testing` can’t be passed to them. You can also use Eloquent to create data for acceptance tests. This way you can use data factories and models to prepare and cleanup data for tests. You should enable `Laravel5` module with `ORM` part to add ActiveRecord methods.

If I `dump(env('APP_ENV'))` in my Test Code it shows the expected `testing` value from the `.env.testing` file. However, if I use the same line in the Controller method that is invoked by the `->amOnPage()` method, i get `local` - which is defined in the `.env` file!

However, it is not clear to my, **WHY** this limitation exists. Consider, for example, the `REST` module (which I use for my `api` tests).

#### api.suite.yml Configuration:
``` yml
actor: ApiTester
modules:
    enabled:
        - Asserts
        - Laravel5:
            url: 'http://api.app.local'
            part: ORM
            run_database_migrations: true
            run_database_seeder: true
            database_seeder_class: \TestingSeeder
            environment_file: .env.testing
        - REST:
            depends: Laravel5
```

This is - basically - the exact same configuration for the `Laravel5` module.

### Question:
I want to use the dedicated `testing` environment that is used in my api tests to be used in my acceptance tests. How can i manage to solve this issue?
I already experimented with something like
``` yml
modules:
    enabled:
         - PhpBrowser:
            depends: Laravel5
```
but it did not work either..

While googling for this issue, i found some weird ideas that suggested to append specific cookies to each request and implement a new middleware in the actual application that switches the environment based on such cookies - but that seems more hindering than actual useful!

Thank you very much for your help - I really appreciate your time and effort on this awesome project!
All the best,
Johannes
