### ISSUE TITLE
Assertion failure inside Module's _after() is crashing suite

### ISSUE THREAD

**Issue by dimitrismitsis** [Codeception/Codeception#5053]
#### What are you trying to achieve?
Make an assertion inside the `_after()` function defined in a Module 

#### What do you get instead?
Instead of the test failing, it's passing, I'm getting an error message that the assertion failed but instead of the suite to continue, it's crashing with an Unhandled RuntimeException

This is working as expected though when instead of _after(), I use _afterStep().

> Provide console output if related. Use `-vvv` mode for more details.

```bash
~/localSites/wpml/app/public$ cc run acceptance Core/Auto_Draft_Sample_Permalink_Cest --steps --env chrome
Codeception PHP Testing Framework v2.4.3
Powered by PHPUnit 6.5.8 by Sebastian Bergmann and contributors.

Acceptance (chrome) Tests (1) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  [RunProcess] Starting codeception/vendor/enm1989/chromedriver/bin/chromedriver --url-base=/wd/hub || chromedriver --url-base=/wd/hub
Auto_Draft_Sample_Permalink_Cest: Auto_draft_permalink
Signature: Core\Auto_Draft_Sample_Permalink_Cest:auto_draft_permalink
Test: codeception/acceptance/Core/Auto_Draft_Sample_Permalink_Cest.php:auto_draft_permalink
Scenario --
 I login 
   I am on page "/wp-login.php/"
   I wait 3
   I fill field "#user_login","admin"
   I fill field "#user_pass","1"
   I click "#wp-submit"
   I grab word press auth cookie 
   I grab word press login cookie 
 Page\WordPress\Settings_Permalinks_Page: switch_to_pretty_permalinks 
   I debug is enabled 
   I am on page "/wp-admin/options-permalink.php"
   I debug is enabled 
   I check option "#custom_selection"
   I fill field "#permalink_structure","/%postname%/"
   I execute js "\n  var element = document.getElementById("wpadminbar");\n  if (element !== "undefined" && element !== null) {\n    element.style.display = "none";\n   }"
   I click "#submit"
   I wait for js "return jQuery.active == 0",10
   I execute js "return jQuery(':animated').length"
 Page\OTGS_Test_Page: show 
   I debug is enabled 
   I am on page "/wp-admin/post-new.php"
   I debug is enabled 
 Page\OTGS_Test_Page: switch_admin_language "el"
   I grab from current url 
   I am on page "/wp-admin/post-new.php?lang=el&admin_bar=1"
 Page\WordPress\Post_Add_New_Page: set_title "CC auto-draft"
   I wait for js "return jQuery.active == 0",10
   I execute js "return jQuery(':animated').length"
   I execute js "return document.readyState"
   I fill field "#title","CC auto-draft"
   I wait for js "return jQuery.active == 0",10
   I execute js "return jQuery(':animated').length"
 Page\WordPress\Post_Add_New_Page: set_content "test content"
   I scroll to "#content-html",0,-40
   I click "#content-html"
   I fill field "#content","test content"
 I wait 4
 Page\WordPress\Post_Add_New_Page: i_see_string_in_post_permalink "/cc-auto-draft/?lang=el"
   I grab text from "//span[@id="sample-permalink"]//a"
   I assert contains "/cc-auto-draft/?lang=el","http://wpml.cc/cc-auto-draft/?lang=el"
 PASSED 


In Constraint.php line 117:
                                                                     
  Failed asserting that file "wp-content/debug.log" does not exist.  
                                                                     

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]

PHP Fatal error:  Uncaught RuntimeException: Command Did Not Finish Properly in /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 101
PHP Stack trace:
PHP   1. {main}() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/codecept:0
PHP   2. Codeception\Application->run() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/codecept:42
PHP   3. Symfony\Component\Console\Application->run() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/src/Codeception/Application.php:108

Fatal error: Uncaught RuntimeException: Command Did Not Finish Properly in /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 101

Call Stack:
    0.0003     370536   1. {main}() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/codecept:0
    0.0651    5889456   2. Codeception\Application->run() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/codecept:42
    0.0651    5889456   3. Symfony\Component\Console\Application->run() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/src/Codeception/Application.php:108

RuntimeException: Command Did Not Finish Properly in /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 101

Call Stack:
    0.0003     370536   1. {main}() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/codecept:0
    0.0651    5889456   2. Codeception\Application->run() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/codecept:42
    0.0651    5889456   3. Symfony\Component\Console\Application->run() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/src/Codeception/Application.php:108
   36.4327   12654488   4. Codeception\Subscriber\ErrorHandler->shutdownHandler() /Users/dim/localSites/wpml/app/public/codeception/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:0
```
> Provide test source code if related

```php
	public function _after( TestInterface $test ) {
		$this->assertFileNotExists( $this->debug_log_path );
	}
```
### Details

* Codeception version: 2.4.3
* PHP Version: 7.0.3
* Operating System: MacOs and Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: Tester
paths:
    tests: codeception
    log: codeception/_output
    data: codeception/_data
    support: codeception/_support
    envs: codeception/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    enabled:
        - \Helper\Acceptance
        - WPWebDriver
        - Asserts
        - Cli
        - Filesystem
        - WPCliDb
        - CheckDebugLog
        - WPDb
        - WPLoad
        - WPCLI
        - OTGSCli
    config:
        WPWebDriver:
            url: 'http://wpml.cc'
            adminUsername: '-'
            adminPassword: '-'
            adminPath: '/wp-admin/'
            log_js_errors: true
            restart: true
        WPCliDb:
            dump: codeception/_data/dump.sql
            cleandump: codeception/_data/cleandb.sql
            dump1: codeception/_data/german-default.sql
            dump2: codeception/_data/german-default-no-english.sql
            oldUrl: 'http://wpml.cc'
            newUrl: 'http://wpml.cc'
        WPDb:
            dsn: 'mysql:host=mysql;dbname=cctests'
            user: 'root'
            password: 'root'
            dump: codeception/_data/dump.sql
            populate: false
            cleanup: false
            reconnect: false
            url: 'http://wpml.cc'
            urlReplacement: false
            tablePrefix: 'wp_'
        CheckDebugLog:
            debug: false
            debugLog: true
            WPPath: ''
        WPCLI:
            path: /builds/wpml
            throw: true
        WPLoad:
            path: 'wp-load.php'
extensions:
    enabled: [Codeception\Extension\RunFailed]
```
