### ISSUE TITLE
[Facebook\WebDriver\Exception\UnknownServerException]   java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by hive-4-apps** [Codeception/Codeception#5062]
#### What are you trying to achieve?
I would like to run acceptance tests with a webdriver which permit to use javascript ( for example : to close window alerts ).
I´m using the wp-browser project.
I tried with selenium/chrome and the chrome driver directly.

#### What do you get instead?
The chrome browser opened with the right page but after it closed without doing any action and I got this error : 

> [Facebook\WebDriver\Exception\UnknownServerException]
  java.net.ConnectException: Connection refused: connect

### Details
I´m using wampserver and virtualhost to access on localhost to my wordpress.

* Codeception version: 2.4.0
* PHP Unit : 6.5.7
* Operating System: Windows 10
* Installation type: Composer - wp-browser
* List of installed packages wp-browser (last version - 06/06/2018)
* acceptance.suite.dist.yml: 
   
```
   class_name: AcceptanceTester
   modules:
       enabled:
            - AcceptanceHelper
            - WPWebDriver
            - WPDb
            - AcceptanceHelper
            - WPFilesystem
        config:
            WPLoader:
                wpDebug: true
                plugins: ['my-plugin/MyPlugin.php']
                activatePlugins: ['my-plugin/MyPlugin.php']
            WPWebDriver:
                url: '%WP_URL%'
                browser: chrome
                adminUsername: 'admin'
                adminPassword: 'admin'
                adminPath: '/wp-admin'
            WPDb:
                dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
                user: %DB_USER%
                password: %DB_PASSWORD%
                dump: 'tests/_data/dump.sql'
                populate: false
                cleanup: false
                reconnect: false
                url: '%WP_URL%'
                tablePrefix: 'wp_'
            WPFilesystem:
                wpRootFolder: '%WP_ROOT_FOLDER%'
                themes: '/wp-content/themes'
                plugins: '/wp-content/plugins'
                mu-plugins: '/wp-content/mu-plugins'
                uploads: '/wp-content/uploads'
```
* .env
  WP_URL="http://localhost/wordpress-4.9.6/wordpress/" 
  ou 
  WP_URL="http://4-9-6-en.wp-dev" //virtualhost version
