### ISSUE TITLE
Reorders tests by dependent tests

### ISSUE THREAD

**Issue by githubjeka** [Codeception/Codeception#5078]
#### What are you trying to achieve?

On page https://codeception.com/docs/07-AdvancedUsage#Dependencies

>Codeception reorders tests so dependent tests will always be executed before the tests that rely on them.

```php
/**
 * @depends \businessTest\unit\LoginTest::testInitForm
 */
class AuthEmployeeTest extends \Codeception\Test\Unit
```

#### What do you get instead?

```bash
codecept run -v -f

S AuthEmployeeTest: True handle 
S AuthEmployeeTest: False handle
+ LoginTest: Init form (1.88s)
+ LoginTest: Wrong login (0.81s)
+ LoginTest: Wrong password (1.50s)
---------------------------------------------------------------------


Time: 5.41 seconds, Memory: 12.00MB

There were 2 skipped tests:

---------
1) AuthEmployeeTest: True handle
 Test  tests\unit\AuthEmployeeTest.php:testTrueHandle
This test depends on "LoginTest::testInitForm" to pass.

---------
2) AuthEmployeeTest: False handle
 Test  tests\unit\AuthEmployeeTest.php:testFalseHandle
This test depends on "LoginTest::testInitForm" to pass.
```

### Details

* Codeception version: Codeception 2.4.2
* PHP Version: php 7.2
* Operating System: Windows

```yml
namespace: businessTest
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'tests\config\test-local.php'
```

PhpUnit [has orders for tests](https://phpunit.readthedocs.io/en/7.1/organizing-tests.html?highlight=order#composing-a-test-suite-using-xml-configuration). How it used in Codeception?
