### ISSUE TITLE
How can I stop the browser from restarting before each test in a group?

### ISSUE THREAD

**Issue by alexiel15** [Codeception/Codeception#5103]
#### What are you trying to achieve?

I want to stop the browser from restarting in each test from a certain group.
I'd like NOT to move these tests to a different suite.
Ideally, I want to redefine the config before the first test in a group is executed, and for it to stay changed for each test in a group.

#### What do you get instead?

I tried to user _before in Group Object:

```
<?php

namespace Group;

class PayForm extends \Codeception\GroupObject
{
    public static $group = "pay_form";

    public function _before(\Codeception\Event\TestEvent $e)
    {
        var_dump("BEFORE GROUP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");

        $this->getModule('WebDriver')->_reconfigure(['restart' => false]);
    }
}
```
But the code from _before is executed before each test, not once before a whole group, as I wanted.

### Details

* Codeception version: 2.4
* PHP Version: 5.6
* Operating System: Ubuntu 16.04
* Installation type: Composer
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
      - Asserts
      - \Helper\Acceptance
      - \Helper\HelperDb
      - \Helper\HelperMixedAcceptance
      - Db
      - WebDriver
    config:
        WebDriver:
            url: 'http://realty.ngs.ru'
            browser: chrome
            restart: true
```
