### ISSUE TITLE
Problem with coverage if tests and cests in same suite

### ISSUE THREAD

**Issue by agilov** [Codeception/Codeception#5105]
#### What are you trying to achieve?
Get code coverage from acceptance and unit tests both in one suite.

I have suites where i store acceptance and unit tests in same directory. 

Actually all the tests near the source code. (golang testing style)

![2018-08-02_00-00-18](https://user-images.githubusercontent.com/825624/43548716-500bb384-95e7-11e8-974c-625fbce83787.png)

And everything is well. Tests working fine and very comfortable to work with tests this way. 
But one problem - i can get only units coverage or only acceptance coverage. 

(If i turn off webdriver - i get units coverage, otherwise acceptance coverage)

The golang testing style in PHP is just an experiment, but i really like it. 
If only i can find the way to get total coverage without manual merging .cov files.

#### What do you get instead?
Get code coverage only from acceptance

### Details

* Codeception version: 2.4.x-dev
* PHP Version: 7.2
* Operating System: Ubuntu 18
* Installation type:  Composer
* Codeception configuration:

```yml
actor: Tester
paths:
    tests: modules
    output: tests/_output
    log: tests/_output
    data: tests/_data
    helpers: tests/_support

settings:
    bootstrap: _tests.php
    memory_limit: 1024M
    colors: true

modules:
    config:
        Yii2:
            configFile: 'config/web_tests.php'
            part: [orm, fixtures, email]
            entryScript: index-test.php
            cleanup: false
    enabled:
        - Yii2
        - Cli
        - WebDriver:
            url: 'http://127.0.0.1:8881'
            window_size: false
            wait: 1 # seconds
            port: 4444
            browser: chrome
            capabilities:
                chromeOptions:
                    args: ["--headless", "--disable-gpu", "window-size=1366x768", "--no-sandbox"]

coverage:
    c3_url: 'http://127.0.0.1:8881/index-test.php'
    enabled: true
    exclude:
        - modules/**/*_Test.php
        - modules/**/*_Cest.php

    include:
        - modules/*/models/*
        - modules/*/controllers/*
        - modules/*/components/*
        - modules/*/commands/*
```

* Suite configuration:

```yml
class_name: UnitTester
```
