### ISSUE TITLE
action sendGET Cant be called

### ISSUE THREAD

**Issue by zong0828** [Codeception/Codeception#5123]
i wanna do something test.

this is my code.

```php
    public function tryToTest(ApiTester $I)
    {
        //$I->amHttpAuthenticated('service_user', '123456');
        //$I->haveHttpHeader('Content-Type', 'application/x-www-form-urlencoded');
        $url = '/Persons/hi';
        $params = [];
        $I->sendGET($url,$params);
        $I->seeResponseCodeIs(\Codeception\Util\HttpCode::OK); // 200
        $I->seeResponseContains('HI');

    }
```
but i always get action sendGET cant be called
any config i miss to do? 

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:2.45
* PHP Version:7
* Operating System:OS
* Installation type:  Composer 
* List of installed packages (`composer show`)
* Suite configuration:

This is my suite config : 
```yml
actor: ApiTester
modules:
  enabled: [Helper\Api, PhpBrowser, REST, Db]
  config:
    PhpBrowser:
      url: '127.0.0.1/'
    REST:
      depends: PhpBrowser
      url: '127.0.0.1/'
    Db:
      dsn: 'mysql:host=127.0.0.1;port=3306;dbname=test'
      user: 'root'
      password: 'secret'
```
