### ISSUE TITLE
[Doctrine2 + DataFactory]  [Error] Cannot access private property App\Entity\Entity::$property 

### ISSUE THREAD

**Issue by joelmedeiros** [Codeception/Codeception#5133]
#### What are you trying to achieve?
I'm trying to generate a fake entity with relationed entities such as:

User has N permissions

Working with ManyToMany or OneToMany on Doctrine2 and SF4 the entity generated for this relationship is: 

```php

class User {
    
     /**
     * @var \Doctrine\Common\Collections\ArrayCollection|Contract[]
     * @ORM\OneToMany(targetEntity="UserPermission",inversedBy="user")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id", referencedColumnName="user_id")
     * })
     */
     private $permissions;

    /**
     * @return Collection|UserPermission[]
     */
    public function getPermissions(): Collection
    {
        return $this->permissions;
    }

    /**
     * @param UserPermission $permission
     * @return self
     */
    public function addPermission(UserPermission $permission): self
    {
        if (!$this->permissions->contains($permission)) {
            $this->permissions[] = $permission;
            $permission->setUser($this);
        }

        return $this;
    }

    /**
     * @param UserPermission $permission
     * @return self
     */
    public function removePermission(UserPermission $permission): self
    {
        if ($this->permissions->contains($permission)) {
            $this->permissions->removeElement($permission);
            // set the owning side to null (unless already changed)
            if ($permission->getUser() === $this) {
                $permission->setUser(null);
            }
        }

        return $this;
    }
}

class UserPermission {
 ...
}
```
As you can see, User class does not have "setPermission", and I think that's the problem. 

#### What do you get instead?

```bash
#  [Error] Cannot access private property App\Entity\User::$permissions  
```
on _beforeSuite method:

```php

$factory = $this->getModule('DataFactory');

$factory->_define(UserPermission::class, ['fieldx'=> Faker::fieldx()]);
$factory->_define(User::class, ['permissions'=> 'entity|' . UserPermission::class]);
// neither $factory->_define(User::class, ['permissions'=> 'entity[2]|' . UserPermission::class]);

```
### Details

* Codeception version: v2.4.5
* PHP Version: 7.1
* Operating System: CentOs
* Installation type: Composer
* List of installed packages (`composer show`) : 
league/factory-muffin                v3.0.1             The goal of this pa...
league/factory-muffin-faker          v2.0.0             The goal of this pa...
codeception/codeception              2.4.5              BDD-style testing f...
codeception/phpunit-wrapper          7.2.0              PHPUnit classes use...
codeception/stub                     2.0.4              Flexible Stub wrapp...

* Suite configuration:

```yml
modules:
    enabled:
        - Asserts
        - \Helper\Unit
        - Db
        - Doctrine2:
            depends: Symfony
            cleanup: true
            em: master
        - DataFactory:
            depends: Doctrine2
        - \Helper\Factories
        - Symfony:
            app_path: 'src'
            var_path: 'var'
            environment: 'local'
        - MongoDb
```
