### ISSUE TITLE
[Doctrine2 + DataFactory] [Doctrine\ORM\ORMInvalidArgumentException] Multiple non-persisted new entities were found through the given association graph

### ISSUE THREAD

**Issue by joelmedeiros** [Codeception/Codeception#5134]
#### What are you trying to achieve?

Trying to use this feature: 

```php
<?php
public function _beforeSuite()
{
     $factory = $this->getModule('DataFactory');
     // let us get EntityManager from Doctrine
     $em = $this->getModule('Doctrine2')->_getEntityManager();

     $factory->_define(User::class, [

         // generate random user name
         // use League\FactoryMuffin\Faker\Facade as Faker;
         'name' => Faker::name(),

         // get real company from database
         'company' => $em->getRepository(Company::class)->find(),

         // let's generate a profile for each created user
         // receive an entity and set it via `setProfile` method
         // UserProfile factory should be defined as well
         'profile' => 'entity|'.UserProfile::class
     ]);
}

```

The factory does not understand that persistent entity already exists and try to persist "company" again, not making the relation on existent entity;

#### What do you get instead?

But my entities returns:

```bash
[Doctrine\ORM\ORMInvalidArgumentException] Multiple non-persisted new entities were found through the given association graph:

 * A new entity was found through the relationship 'App\Entity\MyEntity#fieldRelationed' that was not configured to cascade persist operations for entity: App\Entity\MyEntity@000000002829cf440000000053ea6752. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'App\Entity\EntityRelationed#__toString()' to get a clue.

```

### Details

* Codeception version: v2.4.5
* PHP Version: 7.1
* Operating System: CentOs
* Installation type: Composer
* List of installed packages (`composer show`) : 
league/factory-muffin                v3.0.1             The goal of this pa...
league/factory-muffin-faker          v2.0.0             The goal of this pa...
codeception/codeception              2.4.5              BDD-style testing f...
codeception/phpunit-wrapper          7.2.0              PHPUnit classes use...
codeception/stub                     2.0.4              Flexible Stub wrapp...

* Suite configuration:

```yml
modules:
    enabled:
        - Asserts
        - \Helper\Unit
        - Db
        - Doctrine2:
            depends: Symfony
            cleanup: true
            em: master
        - DataFactory:
            depends: Doctrine2
        - \Helper\Factories
        - Symfony:
            app_path: 'src'
            var_path: 'var'
            environment: 'local'
        - MongoDb
```
