### ISSUE TITLE
file_get_contents(http://localhost:7777/c3/report/clear): failed to open stream: Address not available

### ISSUE THREAD

**Issue by OtezVikentiy** [Codeception/Codeception#5139]
#### What are you trying to achieve?
i'm trying to get the full report about codecoverage
#### What do you get instead?
file_get_contents(http://localhost:7777/c3/report/clear): failed to open stream: Address not available
> Provide console output if related. Use `-vvv` mode for more details.

```bash
bash-4.3# php vendor/bin/codecept run  --coverage --coverage-xml --coverage-html
Cannot load Xdebug - it was already loaded
Codeception PHP Testing Framework v2.4.5
Powered by PHPUnit 7.2.7 by Sebastian Bergmann and contributors.

Acceptance Tests (0) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In ErrorHandler.php line 83:
                                                                                                          
  file_get_contents(http://localhost:7777/c3/report/clear): failed to open stream: Address not available  
                                                                                                          

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite> [<test>]]


Fatal error: Uncaught RuntimeException: Command Did Not Finish Properly in /app/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 101

Call Stack:
    0.0003     406128   1. {main}() /app/vendor/codeception/codeception/codecept:0
    0.1121    7216472   2. Codeception\Application->run() /app/vendor/codeception/codeception/codecept:42
    0.1122    7216472   3. Codeception\Application->run() /app/vendor/codeception/codeception/src/Codeception/Application.php:108

RuntimeException: Command Did Not Finish Properly in /app/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 101

Call Stack:
    0.0003     406128   1. {main}() /app/vendor/codeception/codeception/codecept:0
    0.1121    7216472   2. Codeception\Application->run() /app/vendor/codeception/codeception/codecept:42
    0.1122    7216472   3. Codeception\Application->run() /app/vendor/codeception/codeception/src/Codeception/Application.php:108
    0.1879   10880016   4. Codeception\Subscriber\ErrorHandler->shutdownHandler() /app/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:0

```

### Details

* Codeception version: 2.3
* PHP Version: 7.2
* Operating System: ubuntu 16.04
* Installation type: Composer

```yml
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
extensions:
  enabled:
    - Codeception\Extension\RunFailed
coverage:
  enabled: true
  remote: false
  include:
    - src/*
  exclude:
    - src/Entity/*
  c3_url: 'http://localhost:7777'
params:
  - .env.test
```
