### ISSUE TITLE
Unable to run functional or acceptance tests with --coverage

### ISSUE THREAD

**Issue by dmitry-grasevich** [Codeception/Codeception#515]
When I tried run functional test I got an error:
dmitry@dmitry:/var/www/lsp.local/httpdocs/protected$ codecept run functional AgencyCest.php --coverage
Codeception PHP Testing Framework v1.6.6
Powered by PHPUnit 3.7.24 by Sebastian Bergmann.

Suite functional started


                                                                                                                                     
  [ErrorException]                                                                                                                   
  file_get_contents(http://lsp.local/index.php/c3/report/clear): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found  
                                                                                                                                     
                                                                                                                                     


run [-c|--config="..."] [--report] [--html] [--xml] [--tap] [--json] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage] [--no-exit] [--defer-flush] [-g|--group="..."] [-s|--skip="..."] [--skip-group="..."] [suite] [test]

In the older versions of Codeception this error was not occur. For example:
dmitry@dmitry:/var/www/lsp.local/httpdocs/protected$ codecept run functional AgencyCest.php --coverage
Codeception PHP Testing Framework v1.6.4.2
Powered by PHPUnit 3.7.22 by Sebastian Bergmann.

Suite functional started
Trying to create agency (AgencyCest.createAgency)
Scenario:
* As a Admin
* I am on page "/"
...

I used Yii1, my codeception.yml is:
```yml
coverage:
    enabled: true
    include:
      - components/*.php
      - controllers/*.php
      - models/*.php
      - modules/*.php
      - extensions/DarwinApps/*.php
    exclude:
        - runtime/*
        - models/Pdf.php
        - models/Rtf.php
        - models/cfb.php
        - components/behaviors/WithRelatedBehavior.php
        - yiic
        - yiic.bat
        - yiic.php
paths:
    tests: tests/codeception
    log: tests/codeception/_log
    data: tests/codeception/_data
    helpers: tests/codeception/_helpers
    groups: tests/codeception/_groups
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
```

**Comment by bkuhl** [comment]
I'm experiencing this error as well when attempting to run remote code coverage on my Laravel 4 application.  According to the logs, Laravel doesn't know what to do with the route.

**Comment by adamwinn** [comment]
I have the same error too.  codeception 2.0.11.

`codecept run functional --coverage-html` and `codecept run unit --coverage-html` work fine.

But if I don't include the suite name and include coverage it will fail.  ie. `codecept run --coverage-html` fails with 
`[yii\base\ErrorException]                                                                                                                               
  file_get_contents(http://localhost/index-test.php//c3/report/clear): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error`

**Comment by nateritter** [comment]
@bkuhl @adamwinn and @eddiejaoude, 

I just solved this problem myself. I'm using Laravel 4.2, and had to create a new route to point to the file like this:

```
Route::get('/c3.php', function () {
        include '../c3.php';
    });
```

And then in codeception.yml, I have this: 

```
coverage:
    enabled: true
    remote: false
    c3_url: 'http://whatever.dev/c3.php'
```

(change `whatever.dev` to your local/testing environment domain)

**Comment by adamwinn** [comment]
@nateritter That worked great for me using Yii2!

**Comment by nateritter** [comment]
Outstanding! Glad to hear it!

**Comment by bkuhl** [comment]
@nateritter I'm still having trouble in the Laravel app where everything runs without errors but no coverage is generated.  Would you mind posting more details about your overall config?  Since I'm not experiencing the issue documented here, if you could post them on http://stackoverflow.com/questions/27948621/laravel-codeception-acceptance-test-coverage-routes-not-recognized I'd appreciate it!

**Comment by montogeek** [comment]
@nateritter I cant get this working, I setup the Laravel route, require the file, it runs but report 0 in everything:

```yaml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
coverage:
    enabled: true
    remote: true
    include:
        - app/*
    exclude:
        - app/controllers/BaseController.php
        - app/views/*
        - app/storage/*
        - app/start/*
        - app/lang/*
        - app/database/*
        - app/config/*
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```

```php
Route::get('/c3/{extra}', function () {
    require base_path('c3.php');
})->where('extra', '.*');
```

Obviously I have tests

![screen shot 2015-05-05 at 00 20 51](https://cloud.githubusercontent.com/assets/1002461/7467359/a61996fa-f2bc-11e4-86cc-c71d5b7584e7.png)

Report

![screen shot 2015-05-05 at 00 21 52](https://cloud.githubusercontent.com/assets/1002461/7467369/c1bad3e2-f2bc-11e4-9601-24fd230dace0.png)

I am running the coverage tests inside a Vagrant VM.
Laravel 4.1
CentOS 6.2
PHP 5.4

**Comment by nateritter** [comment]
Hi @montogeek. I'm sorry, I am not sure how to debug your particular scenario.  I had trouble troubleshooting my own setup. Perhaps @bkuhl's solution above might help? Or someone else?  Sorry I can't be of more help at this point.

**Comment by montogeek** [comment]
:( I have already tried with the `c3_url` setting, xdebug.remote_enable is true, etc.. No idea why is not working :(

**Comment by montogeek** [comment]
Uhmm, I just tried it again in another VM:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

PHP
```
PHP 5.6.0-1+deb.sury.org~trusty+1 (cli) (built: Aug 28 2014 14:55:42)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

Getting 0% coverage again.

Can please somebody tell me what should I check or something? I am really frustrated :(

**Comment by montogeek** [comment]
Ok, I upgraded to 2.0.13, run the test again and got 0%, then remove PHPBrowser module form functional tests and finally I got a nice report :D.

What is wrong with that package, or do I need to add some extra config, this was my settings:
```yaml
        PhpBrowser:
            url: 'http://new-monitores.app'
```

**Comment by rafaelbdb** [comment]
I have a fresh install of Codeception 2.1.0, and using a simple test page with only phpinfo() (no frameworks). When I run:
```
php codecept.phar run acceptance ExampleCest.php -f -d --coverage --coverage-html --html
```

I get this error message:
```
  [PHPUnit_Framework_Exception]
  file_get_contents(http://localhost/c3/report/clear): failed to open
  stream: HTTP request failed! HTTP/1.1 404 Not Found
```

My codeception.yml:
```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
coverage:
        enabled: true
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql
```

My acceptance.suite.yml:
```
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
    config:
        WebDriver:
            url: 'http://localhost'
            browser: 'chrome'
            window_size: 1024x768
            coverage:
                enabled: true
                remote: false
                c3_url: 'http://localhost/c3.php'
```

My test.php file:
```
<?php
    include '../../c3.php';
    phpinfo();
?>
```

My ExampleCest.php:
```
<?php
use \AcceptanceTester;

class ExampleCest
{
    public function _before(AcceptanceTester $I)
    {
    }

    public function _after(AcceptanceTester $I)
    {
    }

    // tests
    public function tryToTest(AcceptanceTester $I)
    {
        $I->amOnPage('/test.php');
        $I->waitForText('PHP Version', 10);
    }
}
```

What am I doing wrong?

**Comment by Naktibalda** [comment]
You haven't uploaded c3.php to your server.

http://codeception.com/docs/11-Codecoverage#Remote-CodeCoverage

**Comment by rafaelbdb** [comment]
Thank you @Naktibalda!! It works!

**Comment by rafaelbdb** [comment]
Now I'm facing another problem... Local tests worked perfectly, but when I try remote I get this error:

```
[PHPUnit_Framework_Exception]
  file_get_contents(http://sol:8030/bootstrap.php/c3/report/clear): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
```
Both codeception and acceptance ymls files are already configured with

```
coverage:
      enabled: true
      remote: true
      c3_url: 'http://myremoteapp.com/bootstrap.php'
```

And bootstrap.php has the include for c3.php. What can be wrong?

One detail: my app uses Phalcon2.
