### ISSUE TITLE
Using methods from another namespace?

### ISSUE THREAD

**Issue by WinstonN** [Codeception/Codeception#5153]
#### What are you trying to achieve?
I am trying to reuse code across different test namespaces 
I based my setup around this: https://stackoverflow.com/questions/31184936/how-to-add-multiple-codeception-suites-to-different-folders-in-one-project

I have my project looking like this
```
src
├── general
│   ├── codeception.yml
│   └── tests
│       ├── acceptance
│       ├── acceptance.suite.yml
│       ├── _data
│       ├── functional
│       ├── functional.suite.yml
│       ├── _output
│       ├── _support
│       ├── unit
│       └── unit.suite.yml
├── projectA
│   ├── codeception.yml
│   └── tests
│       ├── acceptance
│       ├── acceptance.suite.yml
│       ├── _data
│       ├── _envs
│       ├── functional
│       ├── functional.suite.yml
│       ├── _output
│       ├── _support
│       ├── unit
│       └── unit.suite.yml
└── projectB
    ├── codeception.yml
    └── tests
        ├── acceptance
        ├── acceptance.suite.yml
        ├── _data
        ├── functional
        ├── functional.suite.yml
        ├── _output
        ├── _support
        ├── unit
        └── unit.suite.yml
```
I would like to use methods in helpers in general in project A & B

My codeception.yml in the root of src looks like

```
include:
    - src/*
paths:
    log: _log
    output: _output
settings:
    colours: true
    memory_limit: 1024M
    bootstrap: _bootstrap.php

```

#### What do you get instead?
[InjectionException] Failed to inject dependencies in instance of 'project\homepage\viewCest'. Class general\Helper\Acceptance does not exist

> Provide test source code if related

```php
<?php
namespace project\homepage;
use project\AcceptanceTester;
use project\Page\Homepage as HomePage;
use general\Helper\Acceptance as GeneralHelper;

class viewCest
{

    public function _before(AcceptanceTester $I)
    {
    }

    public function _after(AcceptanceTester $I)
    {
    }

    // tests
    public function viewHomepage(AcceptanceTester $I, GeneralHelper $G)
    {
        codecept_debug($G);
        $I->comment(HomePage::$comment);
        $I->amOnPage("/");
        $I->seeInTitle(HomePage::$title);
        $I->makeScreenshot('Homepage');
    }
}

```
### Details

* Codeception version: Codeception PHP Testing Framework v2.4.6
* PHP Version: PHP 7.2.7-0ubuntu0.18.04.2
* Operating System: Docker ubuntu:18.04
* Installation type: Phar
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
  enabled:
  - Asserts
  - Filesystem
  - WebDriver
  - \project\Helper\Acceptance
#  - \general\Helper\Acceptance // not working

  config:
    WebDriver:
      url: 'https://www.domain.com/'
      host: 'localhost'
      port: 9515
      cssSelectorsEnabled: true
      log_js_errors: false
      restart: true
      browser: chrome
      window_size: maximize
      capabilities:
        chromeOptions:
          args: ['--headless', '--disable-gpu', '--no-sandbox', "--window-size=1366,768", '--no-zygote', '--disable-extensions','--user-data-dir=/tmp/user-data','--hide-scrollbars','--v=99','--single-process','--data-path=/tmp/data-path','--ignore-certificate-errors','--homedir=/tmp','--disk-cache-dir=/tmp/cache-dir']
          binary: "/usr/bin/google-chrome"
groups:
  homepage: [tests/acceptance/homepage]
  catalog: [tests/acceptance/catalog]
  customer: [tests/acceptance/customer]
  checkout: [tests/acceptance/checkout]
  # red line tests
  redline: ['tests/acceptance/homepage',
            'tests/acceptance/catalog',
            'tests/acceptance/checkout']


```
The complete error output

```bash
🐳  codeception codeception # php codecept.phar run -c src/project -g homepage acceptance --debug -vv;
Codeception PHP Testing Framework v2.4.6
Powered by PHPUnit 6.5.9 by Sebastian Bergmann and contributors.
[Groups] homepage 

                                                                   
  [Codeception\Exception\ConfigurationException]                   
  Module \general\Helper\Acceptance could not be found and loaded  
                                                                   

Exception trace:
 () at phar:///codeception/codecept.phar/src/Codeception/Lib/ModuleContainer.php:80
 Codeception\Lib\ModuleContainer->create() at phar:///codeception/codecept.phar/src/Codeception/SuiteManager.php:67
 Codeception\SuiteManager->__construct() at phar:///codeception/codecept.phar/src/Codeception/Codecept.php:186
 Codeception\Codecept->runSuite() at phar:///codeception/codecept.phar/src/Codeception/Codecept.php:158
 Codeception\Codecept->run() at phar:///codeception/codecept.phar/src/Codeception/Command/Run.php:466
 Codeception\Command\Run->runSuites() at phar:///codeception/codecept.phar/src/Codeception/Command/Run.php:361
 Codeception\Command\Run->execute() at phar:///codeception/codecept.phar/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///codeception/codecept.phar/vendor/symfony/console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///codeception/codecept.phar/vendor/symfony/console/Application.php:228
 Symfony\Component\Console\Application->doRun() at phar:///codeception/codecept.phar/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at phar:///codeception/codecept.phar/src/Codeception/Application.php:108
 Codeception\Application->run() at phar:///codeception/codecept.phar/codecept:37
 require_once() at /codeception/codecept.phar:7

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--] [<suite>] [<test>]

```

**Comment by llstarscreamll** [comment]
Given the next structure:

```bash
├── User
│   ├── Tests
│   │   ├── api
│   │   │   ├── _bootstrap.php
│   │   ├── api.suite.yml
│   │   ├── _bootstrap.php
│   │   └── _support
│   │       └── Helper
│   │           └── Api.php
├── Account
│   ├── Tests
│   │   ├── unit
│   │   │   ├── _bootstrap.php
│   │   ├── unit.suite.yml
│   │   ├── _bootstrap.php
│   │   └── _support
│   │       └── Helper
│   │           └── Unit.php
```

If you want Unit.php helper from Account to work in User api suite, you should load the namespace in `User/tests/_bootstrap.php`:
```php
<?php
// This is global bootstrap for autoloading
\Codeception\Util\Autoload::addNamespace('\Account\Helper', __DIR__.'/../../Account/Tests/_support/Helper');
```
In your `User/codeception.yml`:

```yml
namespace: User
paths:
    tests: Tests
    output: Tests/_output
    data: Tests/_data
    support: Tests/_support
    envs: Tests/_envs
settings:
    bootstrap: _bootstrap.php
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```
And your `User/Tests/api.suite.yml`:

```yml
actor: ApiTester
modules:
    enabled:
        - Asserts
        - \User\Helper\Api
        - \Account\Helper\Unit
```
