### ISSUE TITLE
running seeInDatabase and/or seeNumRecords multiple times in same function fails

### ISSUE THREAD

**Issue by Hexoplon** [Codeception/Codeception#5154]
I have a unit test testAddBook that will try to add three new books to a database using functions from a DBModel class. The test generates a new book to be added, calls the function that adds the book to the db, and then verifies that the book made it to the database by checking for an increased row count by using seeNumRecords and by checking for an entry matching the one that was generated with seeInDatabase. This process is repeated two more times within this same test function

When I run my test it always fails the second time seeNumRecords or seeInDatabase is called, the first is always a success and finds the first added book. But when I print out all the books that getBookList() can find in the database the books have been added correctly.

I've tried looking around for a possible solution, but have been out of luck so far.
Here is the output from the unit test
```bash
BookCollectionTest: Add book  [Query] SELECT count(*) FROM `book` 
  [Query] SELECT count(*) FROM `book` WHERE `id` = ? AND `title` = ? AND `author` = ? AND `description` = ? 
  [Parameters] [4,"New book","Some author",""]
  Array
  (
      [0] => Book Object
          (
              [id] => 1
              [title] => Jungle Book
              [author] => R. Kipling
              [description] => A classic book.
          )
  
      [1] => Book Object
          (
              [id] => 2
              [title] => Moonwalker
              [author] => J. Walker
              [description] => 
          )
  
      [2] => Book Object
          (
              [id] => 3
              [title] => PHP & MySQL for Dummies
              [author] => J. Valade
              [description] => Written by some smart gal.
          )
  
      [3] => Book Object
          (
              [id] => 4
              [title] => New book
              [author] => Some author
              [description] => 
          )
  
      [4] => Book Object
          (
              [id] => 5
              [title] => New book
              [author] => Some author
              [description] => Some description
          )
  
  )
  
  [Query] SELECT count(*) FROM `book` 
✖ BookCollectionTest: Add book (0.01s)

The number of found rows (4) does not match expected number 5 for criteria [] in table book
Failed asserting that 4 matches expected 5.
```
It seems to still be using the old row count. The first seeNumRecord should return 4, which it does. The second one however should return 5. (the database starts with three books)

Here is the source code for my test. Once I get it working I'll replace some of the repeated code with a helper function :)

```php
public function testAddBook()
        {
            $testValues = [
                'title' => 'New book',
                'author' => 'Some author',
                'description' => ''
            ];
            $book = new Book($testValues['title'], $testValues['author'], $testValues['description']);
            $this->dbModel->addBook($book);

            // Id was successfully assigned
            $this->assertEquals(4, $book->id);

            // Check if entry exists in database
            $this->tester->seeNumRecords(4, 'book');
            $this->tester->seeInDatabase('book', [
                'id' => 4,
                'title' => $testValues['title'],
                'author' => $testValues['author'],
                'description' => $testValues['description']
            ]);

            //Test #2
            $testValues = [
                'title' => 'New book',
                'author' => 'Some author',
                'description' => 'Some description'
            ];
            $book = new Book($testValues['title'], $testValues['author'], $testValues['description']);
            $this->dbModel->addBook($book);


            // Id was successfully assigned
            $this->assertEquals(5, $book->id);

            // Display list of books retrieved from database to Codeception debug console
            $booklist = $this->dbModel->getBookList();
            codecept_debug($booklist);


            // Check if entry exists in database
            $this->tester->seeNumRecords(5, 'book');
            $this->tester->seeInDatabase('book', [
                'id' => 5,
                'title' => $testValues['title'],
                'author' => $testValues['author'],
                'description' => $testValues['description']
            ]);
            //test #3
            $testValues = [
                'title' => "<script>document.body.style.visibility='hidden'</script>",
                'author' => "<script>document.body.style.visibility='hidden'</script>",
                'description' => "<script>document.body.style.visibility='hidden'</script>"
            ];
            $book = new Book($testValues['title'], $testValues['author'], $testValues['description']);
            $this->dbModel->addBook($book);

            // Id was successfully assigned
            $this->assertEquals(6, $book->id);

            // Check if entry exists in database
            $this->tester->seeNumRecords(6, 'book');
            $this->tester->seeInDatabase('book', [
                'id' => 6,
                'title' => $testValues['title'],
                'author' => $testValues['author'],
                'description' => $testValues['description']
            ]);
        }
```
### Details

* Codeception version: 2.4.5
* PHP Version: 7.0.30-0ubuntu0.16.04.1 
* Operating System: Ubuntu Gnome 16.04
* Installation type: Composer

```yml
# codeception.yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
modules:
    enabled:
        - Db:
            dsn: 'mysql:host=x.x.x.x;dbname=test;charset=utf8;'
            user: 'xxx'
            password: 'xxx'
            dump: 'tests/_data/test.sql'
            populate: true # run populator before all tests
            cleanup: true # run populator before each test
extensions:
    enabled:
        - Codeception\Extension\RunFailed

# unit.suite.yml
actor: UnitTester
modules:
    enabled:
       - Db
       - Asserts
       - \Helper\Unit
```
