### ISSUE TITLE
Codeception and bamboo quarantine test

### ISSUE THREAD

**Issue by Elverslane** [Codeception/Codeception#5159]
#### What are you trying to achieve?
I try to run my tests in bamboo with a couple tests in quarantine and get successful build
#### What do you get instead?
Instead i get failed build with report error and still a couple tests in quarantine
> Provide console output if related. Use `-vvv` mode for more details.

```bash
FAILURES!
--
04-Sep-2018 18:29:06 | Tests: 14, Assertions: 75, Failures: 2.
04-Sep-2018 18:29:06 | Failing task since return code of [/var/bamboo/home/temp/TESTPROJECT-TZ-RSS-131-ScriptBuildTask-5571916222707338857.sh] was 1 while expected 0
04-Sep-2018 18:29:06 | Finished task 'codeception start' with result: Failed
04-Sep-2018 18:29:06 | Skipping execution of task 'Report' as it is disabled
04-Sep-2018 18:29:06 | Starting task 'Report' of type 'com.atlassian.bamboo.plugins.testresultparser:task.testresultparser.junit'
04-Sep-2018 18:29:06 | Parsing test results under /var/bamboo/home/xml-data/build-dir/230457349/TESTPROJECT-TZ-RSS...
04-Sep-2018 18:29:06 | Failing task since 2 failing test cases were found.
04-Sep-2018 18:29:06 | Changing Task Result to SUCCESS as all failed tests were quarantined.
04-Sep-2018 18:29:06 | Finished task 'Report' with result: Success


```

### Details

* Codeception version: 2.4.1
* PHP Version: 7.0
* Operating System: linux
* Installation type:  Composer 
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    auto_smoke:
      name: 'base'
      status: 200
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Teststatistics
        - DetailReporter

```

ideas?
