### ISSUE TITLE
Why is the `seeResponseCodeIsSuccessful()` method not allowed after setting the `part` parameter?

### ISSUE THREAD

**Issue by chelys-cheng** [Codeception/Codeception#5183]
In the `REST` module, when I set the `part` parameter, I found that some methods like `seeResponseCodeIsSuccessful()` are not generated in Trait `ApiTesterActions`.
After reading the source code of the `REST` module, I know that it is through `Reflection` to limit the generation of a particular method, but I think `seeResponseCodeIsSuccessful()` is similar to `dontSeeResponseCodeIs($code)`. Why not use it in the above situation?
### Details

* Codeception version: 2.4.4
* PHP Version: 7.1.16
* Operating System: Centos 7
* Installation type: Yii2 default
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - REST:
            # url:
            depends: Yii2
            part: Json
    config:
        - Yii2
```
