### ISSUE TITLE
Codeception selenium webdrive no db connection (docker network)

### ISSUE THREAD

**Issue by user3748173** [Codeception/Codeception#5186]
#### What are you trying to achieve?
I am using docker-compose to test Wordpress plugin. I am trying to log into wordpress admin area with acceptance test and "see" the "Dashboard" word (Docker-compose file containers have ip addresses). 
#### What do you get instead?
Chrome WebDrive is displaying Wordpress login page without css. When clicked to "**log in**" button error occurs `localhost refused to connect`. Chrome docker container error is: `[SEVERE]: bind() returned an error, errno=99: Cannot assign requested address (99)` 
#### What have I done so far?
- I have found out that all is fine if I am not adding "networks" "subnet" ip address to docker compose in to wordpress container (I need ip address in another application).  
- I have tried Firefox but it is also not working.
- I found this [answer](https://stackoverflow.com/questions/51159068/codeception-with-selenium-in-docker-container-not-able-to-see-site-to-test-it) about how to create something similar. I tried it, but some how it is not working for me. Also I do not understand where comes ip address "host: 172.22.1.5" and the answer does not mention how the codeception is installed (**the place of installation**). I am not sure if it is the solution to my issue.

**If this is not the right place for that question then please tell me where might I find solution to my issue** _(It is hard to find the right place to ask because the issue is related to: Docker-compose, Codeception, networking  and Selenium image.)_? (The stackoverflow answer shows lack of interest in the Q&A site about such posts. So posting there that question would be pointless. )

#### How I have set up the system: 
**I have installed codeception to my wordpress container /home/codeception using:**` docker-php-ext-install pdo_mysql ` and  `wget http://codeception.com/codecept.phar` 

#### Docker-compose code:

```
version: '2'

services:
  wordpress_test:
    container_name: wp_test
    restart: always
    image: wordpress
    depends_on:
      - test_db
    ports:
      - 8080:80
    networks:
      vpcbr:
        ipv4_address: 10.7.0.5
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    tty: true
  test_db:
    container_name: wp_db
    restart: always
    image: mysql:5.7
    ports:
      - "3306"
    networks:
      vpcbr:
        ipv4_address: 10.7.0.6
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  firefox:
    image: selenium/node-firefox:3.14.0-europium
    depends_on:
      - selenium-hub-wp
    environment:
      HUB_HOST: selenium-hub-wp
      HUB_PORT: 4444
    networks:
      vpcbr:
        ipv4_address: 10.7.0.12
  chrome:
    image: selenium/node-chrome:3.14.0-europium
    depends_on:
      - selenium-hub-wp
    environment:
      HUB_HOST: selenium-hub-wp
      HUB_PORT: 4444
    networks:
      vpcbr:
        ipv4_address: 10.7.0.11
  selenium-hub-wp:
    image: selenium/hub:3.14.0-europium
    container_name: selenium-hub-wp
    ports:
      - "4444:4444"
    networks:
      vpcbr:
        ipv4_address: 10.7.0.10
networks:
    vpcbr:
        driver: bridge
        ipam:
          config:
            - subnet: 10.7.0.0/16
              gateway: 10.7.0.1
```
acceptance.suite.yml:
```
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
                url: http://_network_ip_address_:8080
                host: _network_ip_address_
                browser: chrome
                wait: 30
        - \Helper\Acceptance
```

### Details

* Codeception version: Installed by command mentioned above.
* Docker Version:  18.03.1-ce
* OS: OSX High Sierra
* Installation type: .phar file
