### ISSUE TITLE
 [ConnectionException] Can't connect to Webdriver at http://127.0.0.1:9515/wd/hub. Please make sure that Selenium Server or PhantomJS is running. 

### ISSUE THREAD

**Issue by chenxiumiao** [Codeception/Codeception#5193]
#### What are you trying to achieve?
open chrome and click something When I install chromedriver
#### What do you get instead?

```bash
UserCest: Try to test
Signature: UserCest:tryToTest
Test: tests/acceptance/UserCest.php:tryToTest
Scenario --
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '/Users/cx/Downloads/code/fangPHP/data/web/CV/tests/_output/' dir
 ERROR 


1) UserCest: Try to test
 Test  tests/acceptance/UserCest.php:tryToTest
                                                                                                                                                    
  [ConnectionException] Can't connect to Webdriver at http://127.0.0.1:9515/wd/hub. Please make sure that Selenium Server or PhantomJS is running.  
                                                                                                                                                    
#1  phar:///usr/local/bin/codecept/src/Codeception/Module/WebDriver.php:1449
#2  phar:///usr/local/bin/codecept/src/Codeception/Module/WebDriver.php:426
#3  Codeception\Subscriber\Module->before
#4  phar:///usr/local/bin/codecept/vendor/symfony/event-dispatcher/EventDispatcher.php:212
#5  phar:///usr/local/bin/codecept/vendor/symfony/event-dispatcher/EventDispatcher.php:44
#6  phar:///usr/local/bin/codecept/codecept:37
#7  /usr/local/bin/codecept:7

> Provide console output if related. Use `-vvv` mode for more details.
```
> Provide test source code if related

```php
	public function tryToTest ( AcceptanceTester $I )
	{
		
		$I->amOnPage( '_enter.php?m=user&a=login' );
		$I->seeInTitle('用户登入');
		$I->fillField( 'email' , 'sipc@115.com');
		$I->fillField( 'password' , 'sipc115');
		$I->click('登入');
		$I->wait( 5);
		$I->seeInTitle( '我的简历');
	}
```
### Details

* Codeception version:2.4.6
* PHP Version:7.2.9
* Operating System:MAC
* Installation type: Phar 
* List of installed packages (`composer show`) erusev/parsedown 
* Suite configuration:
```yml
actor: AcceptanceTester
modules:
  enabled:
  - WebDriver:
      url: 'http://localhost/'
      window_size: false # disabled in ChromeDriver
      port: 9515
      browser: chrome
      capabilities:
        chromeOptions: # additional chrome options
  - \Helper\Acceptance
```

**Comment by Naktibalda** [comment]
Have you started Selenium or ChromeDriver as documented at https://codeception.com/docs/modules/WebDriver?

`2. Launch ChromeDriver: chromedriver --url-base=/wd/hub`

**Comment by fakercx** [comment]
yes,I did it.But it also tell me Can't connect to Webdriver

**Comment by jirismika** [comment]
Similar here here and I am also on Mac.

- Codeception version: 2.5.0, 
- PHP version: 7.1.19
- Operating System: macos 10.14
- Installation type: composer

```yml
class_name: AcceptanceTester

modules:
  enabled:
  - WebDriver
  - Asserts
  config:
    WebDriver:
      url: 'http://project.url'
      browser: 'chrome'
      host: 'chromeonnetwork.url'
      port: '9515'
      window_size: false
      restart: true
      pageload_timeout: 15
      wait: 15
      capabilities:
        chromeOptions:
          args: ["--headless", "--no-sandbox", "--disable-gpu", "window-size=1920x1080"]
          binary: "/usr/bin/chromium"

env:
  phantomjs:
    modules:
      config:
        WebDriver:
          browser: 'phantomjs'
          host: 'phantom.in.cee-systems.com'
          port: '8910'
          window_size: 1920x1080
          restart: true
          capabilities:
            unexpectedAlertBehaviour: 'accept'

  localchrome:
    modules:
      config:
        WebDriver:
          host: 'localhost'
          browser: 'chrome'
          port: '9515'
          window_size: false
          capabilities:
            args: ["--headless",  "--disable-gpu"]
```


```
../vendor/bin/codecept run acceptance --env localchrome -vvv

Codeception PHP Testing Framework v2.5.0
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Running with seed:

Acceptance (localchrome) Tests (28) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: WebDriver, Asserts
...

Scenario --
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '/projectDir/tests/../temp/codeception/' dir
 ERROR
...

Time: 1.16 seconds, Memory: 10.00MB

There were 28 errors:
1) ...
[ConnectionException] Can't connect to Webdriver at http://localhost:9515/wd/hub. Please make sure that Selenium Server or PhantomJS is running.

/projectDir/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:1449
/projectDir/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:426
/projectDir/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:56
/projectDir/vendor/symfony/event-dispatcher/EventDispatcher.php:212
/projectDir/vendor/symfony/event-dispatcher/EventDispatcher.php:44
/projectDir/vendor/codeception/phpunit-wrapper/src/Listener.php:133
/projectDir/vendor/codeception/phpunit-wrapper/src/Listener.php:102
/projectDir/vendor/phpunit/phpunit/src/Framework/TestResult.php:386
/projectDir/vendor/codeception/codeception/src/Codeception/Test/Test.php:75
/projectDir/vendor/phpunit/phpunit/src/Framework/TestSuite.php:733
/projectDir/vendor/codeception/phpunit-wrapper/src/Runner.php:109
/projectDir/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
/projectDir/vendor/codeception/codeception/src/Codeception/Codecept.php:191
/projectDir/vendor/codeception/codeception/src/Codeception/Codecept.php:180
/projectDir/vendor/codeception/codeception/src/Codeception/Command/Run.php:492
/projectDir/vendor/codeception/codeception/src/Codeception/Command/Run.php:387
/projectDir/vendor/symfony/console/Command/Command.php:255
/projectDir/vendor/symfony/console/Application.php:948
/projectDir/vendor/symfony/console/Application.php:250
/projectDir/vendor/symfony/console/Application.php:148
/projectDir/vendor/codeception/codeception/src/Codeception/Application.php:108
/projectDir/vendor/codeception/codeception/codecept:43

```
(shortened test names and projectDir)

**Comment by jirismika** [comment]
Similar here here and I am also on Mac. Trying to run local headless chrome tests.

- Codeception version: 2.5.0, 
- PHP version: 7.1.19
- Operating System: macos 10.14
- Installation type: composer

```yml
class_name: AcceptanceTester

modules:
  enabled:
  - WebDriver
  - Asserts
  config:
    WebDriver:
      url: 'http://project.url'
      browser: 'chrome'
      host: 'chrome.onnetwork.url'
      port: '9515'
      window_size: false
      restart: true
      pageload_timeout: 15
      wait: 15
      capabilities:
        chromeOptions:
          args: ["--headless", "--no-sandbox", "--disable-gpu", "window-size=1920x1080"]
          binary: "/usr/bin/chromium"

env:
  phantomjs:
    modules:
      config:
        WebDriver:
          browser: 'phantomjs'
          host: 'phantom.onnetwork.url'
          port: '8910'
          window_size: 1920x1080
          restart: true
          capabilities:
            unexpectedAlertBehaviour: 'accept'

  localchrome:
    modules:
      config:
        WebDriver:
          host: 'localhost'
          browser: 'chrome'
          port: '9515'
          window_size: false
          capabilities:
            args: ["--headless",  "--disable-gpu"]
```


```
../vendor/bin/codecept run acceptance --env localchrome -vvv

Codeception PHP Testing Framework v2.5.0
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Running with seed:

Acceptance (localchrome) Tests (28) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: WebDriver, Asserts
...

Scenario --
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '/projectDir/tests/../temp/codeception/' dir
 ERROR
...

Time: 1.16 seconds, Memory: 10.00MB

There were 28 errors:
1) ...
[ConnectionException] Can't connect to Webdriver at http://localhost:9515/wd/hub. Please make sure that Selenium Server or PhantomJS is running.

/projectDir/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:1449
/projectDir/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php:426
/projectDir/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:56
/projectDir/vendor/symfony/event-dispatcher/EventDispatcher.php:212
/projectDir/vendor/symfony/event-dispatcher/EventDispatcher.php:44
/projectDir/vendor/codeception/phpunit-wrapper/src/Listener.php:133
/projectDir/vendor/codeception/phpunit-wrapper/src/Listener.php:102
/projectDir/vendor/phpunit/phpunit/src/Framework/TestResult.php:386
/projectDir/vendor/codeception/codeception/src/Codeception/Test/Test.php:75
/projectDir/vendor/phpunit/phpunit/src/Framework/TestSuite.php:733
/projectDir/vendor/codeception/phpunit-wrapper/src/Runner.php:109
/projectDir/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
/projectDir/vendor/codeception/codeception/src/Codeception/Codecept.php:191
/projectDir/vendor/codeception/codeception/src/Codeception/Codecept.php:180
/projectDir/vendor/codeception/codeception/src/Codeception/Command/Run.php:492
/projectDir/vendor/codeception/codeception/src/Codeception/Command/Run.php:387
/projectDir/vendor/symfony/console/Command/Command.php:255
/projectDir/vendor/symfony/console/Application.php:948
/projectDir/vendor/symfony/console/Application.php:250
/projectDir/vendor/symfony/console/Application.php:148
/projectDir/vendor/codeception/codeception/src/Codeception/Application.php:108
/projectDir/vendor/codeception/codeception/codecept:43

```
(shortened test names and projectDir)
