### ISSUE TITLE
Using Db Module in Extension not loading dump sql (2.5 release)

### ISSUE THREAD

**Issue by njaw** [Codeception/Codeception#5195]
#### What are you trying to achieve?
Using the Db module in an extension to load my dump file when I add a specific group to a test.

#### What do you get instead?
The dump is not loaded when I specify the group. This is working fine in v2.4.5 but not in v2.5. I am using the Symfony framework. I am wondering if this has anything to do with the update for multi db support or not and if I am missing some new configuration parameter with this last update.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Nothing to show
```
> Provide test source code if related

```php
namespace Codeception\Extension;

use Codeception\Event\TestEvent;
use Codeception\Events;
use Codeception\Extension;

class DbReloader extends Extension
{
    public static $events = [
        Events::TEST_BEFORE => 'beforeTest'
    ];

    public function beforeTest(TestEvent $e)
    {
        $test = $e->getTest();
        $groups = $test->getMetadata()->getGroups();

        if (in_array('reload_db', $groups)) {
            $db = $this->getModule('Db');
            $db->_loadDump();
            $db->_before($test);
        }
    }
}
```
### Details

* Codeception version: 2.5
* PHP Version: 7.0.18
* Operating System: ubuntu 16
* Installation type: Composer
* List of installed packages (`composer show`): too much to display
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - Asserts
        - REST:
            depends: PhpBrowser
            url: http://test-api.local/app_dev.php
        - Sequence:
             prefix: '_'
        - Db
```

* Codeception configuration:

```yml
actor: Tester
paths:
    tests: Tests
    log: Tests/_output
    data: Tests/_data
    support: Tests/_support
    envs: Tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    log: true
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\DbReloader

modules:
    enabled:
    config:
        Db:
            dsn: "mysql:host=test-db;dbname=test"
            user: "test"
            password: "test"
            dump: 'Tests/_data/dump.sql'
            populate: true
            cleanup: false
            reconnect: false

```
