### ISSUE TITLE
Cookies is invalid of API config

### ISSUE THREAD

**Issue by Sun-FreePort** [Codeception/Codeception#5196]
composer of Codeception:
```json
// ...other code
        "codeception/base": "^2.4.0",
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3",
        "guzzlehttp/guzzle": "^6.3"
//...other code
```

In tests/api.suite.yml：
```
actor: ApiTester
modules:
    enabled:
        - \Helper\Api
        - Filesystem
        - REST:
              url: http://www.maoer-web.com
              depends: PhpBrowser
              part: Json
              cookies:
                login-token:
                  Name: token
                  Value: 5ba37859e205392110402430|67cafd5911d21a8e|1537439833|dde838a5f56a8485
```

1. Update `index.php` to `echo $_COOKIE['token'];exit;`
2. I run `./vendor/bin/codecept run`, result is *Fail  response is empty*

Environment:
System - Windows 10
PHP - 7.2.6 64bit
Nginx - 1.14.0 32bit
Framework - Yii2

---

Note: all composer package:
```
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.15",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiidoc/yii2-redactor": "*",
        "philippfrenzel/yii2fullcalendar": "^2.5",
        "linslin/yii2-curl": "*",
        "kucha/ueditor": "*",
        "yiisoft/yii2-redis": "^2.0",
        "index0h/yii2-log": "^0.0.3"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*",

        "codeception/base": "^2.4.0",
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3",
        "guzzlehttp/guzzle": "^6.3"
    },
```
