### ISSUE TITLE
Running all the tests from acceptance throws an error after the first test is passing

### ISSUE THREAD

**Issue by axeaxel** [Codeception/Codeception#5206]
#### What are you trying to achieve?
Run all the tests from acceptance

codecept --debug run --steps tests/acceptance

#### What do you get instead?
First test is running and passing, but the other test that follow I have an error

> Provide console output if related. Use `-vvv` mode for more details.

```bash
 [Facebook\WebDriver\Exception\NoAlertOpenException] No modal dialog is currently open
Build info: version: '3.8.0', revision: '924c4067df', time: '2017-11-30T11:37:19.049Z'
System info: host: 'CB-002-DT', ip: '10.135.128.29', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 62.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 2704, moz:profile: C:\Users\alex.chircu.CB-002..., moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: XP, platformName: XP, platformVersion: 10.0, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: f61d9713-4ef1-4b9f-b8c3-9e1690bd5a95
```
> Provide test source code if related

```php
// paste test
```
### Details

Codeception version: 2.4.6
PHP Version: 7.2.4
Operating System: Windows 10
Installation type: Phar || Composer
List of installed packages (composer show)
behat/gherkin v4.5.1 Gherkin DSL parser for PHP 5.3
doctrine/instantiator 1.1.0 A small, lightweight utility to instantiate objects in PHP without invok...
facebook/webdriver 1.6.0 A PHP client for Selenium WebDriver
guzzlehttp/guzzle 6.3.3 Guzzle is a PHP HTTP client library
guzzlehttp/promises v1.3.1 Guzzle promises library
guzzlehttp/psr7 1.4.2 PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy 1.8.1 Create deep copies (clones) of your objects
phar-io/manifest 1.0.3 Component for reading phar.io manifest information from a PHP Archive (P...
phar-io/version 2.0.1 Library for handling version information and constraints
phpdocumentor/reflection-common 1.0.1 Common reflection classes used by phpdocumentor to reflect the code stru...
phpdocumentor/reflection-docblock 4.3.0 With this component, a library can provide support for annotations via D...
phpdocumentor/type-resolver 0.4.0
phpspec/prophecy 1.8.0 Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage 6.0.7 Library that provides collection, processing, and rendering functionalit...
phpunit/php-file-iterator 2.0.1 FilterIterator implementation that filters files based on a list of suff...
phpunit/php-text-template 1.2.1 Simple template engine.
phpunit/php-timer 2.0.0 Utility class for timing
phpunit/php-token-stream 3.0.0 Wrapper around PHP's tokenizer extension.
phpunit/phpunit 7.3.5 The PHP Unit Testing framework.
psr/http-message 1.0.1 Common interface for HTTP messages
sebastian/code-unit-reverse-lookup 1.0.1 Looks up which function or method a line of code belongs to
sebastian/comparator 3.0.2 Provides the functionality to compare PHP values for equality
sebastian/diff 3.0.1 Diff implementation
sebastian/environment 3.1.0 Provides functionality to handle HHVM/PHP environments
sebastian/exporter 3.1.0 Provides the functionality to export PHP variables for visualization
sebastian/global-state 2.0.0 Snapshotting of global state
sebastian/object-enumerator 3.0.3 Traverses array structures and object graphs to enumerate all referenced...
sebastian/object-reflector 1.1.1 Allows reflection of object attributes, including inherited and non-publ...
sebastian/recursion-context 3.0.0 Provides functionality to recursively process PHP variables
sebastian/resource-operations 1.0.0 Provides a list of PHP built-in functions that operate on resources
sebastian/version 2.0.1 Library that helps with managing the version number of Git-hosted PHP pr...
symfony/browser-kit v4.1.4 Symfony BrowserKit Component
symfony/console v4.1.4 Symfony Console Component
symfony/css-selector v4.1.4 Symfony CssSelector Component
symfony/dom-crawler v4.1.4 Symfony DomCrawler Component
symfony/event-dispatcher v4.1.4 Symfony EventDispatcher Component
symfony/finder v4.1.4 Symfony Finder Component
symfony/polyfill-ctype v1.9.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring v1.9.0 Symfony polyfill for the Mbstring extension
symfony/process v4.1.4 Symfony Process Component
symfony/yaml v4.1.4 Symfony Yaml Component
theseer/tokenizer 1.1.0 A small library for converting tokenized PHP source code into XML and po...
webmozart/assert 1.3.0 Assertions to validate method input/output with nice error messages.
* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
    - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=Localhost'
            user: 'root'
            password: ''
            dump: tests/_data/dump.sql
            cleanup: true # reLoad dump between tests
            populate: true # Load dump before all tests
            reconnect: true
coverage:
    enabled: true
```
