### ISSUE TITLE
Travis builds fails randomly each time while running codeception acceptance test cases and works after I restart the build

### ISSUE THREAD

**Issue by kjnanda** [Codeception/Codeception#5228]
#### What are you trying to achieve?

I am running the acceptance test cases for my wordpress site and plugin. This was working as expected but since 8 days I am having a problem whenever the build runs. It fails at random point. Sometimes X test case fails and next times that same test case works and other fails.

Restarting build solves the problem but that is not the proper solution.

#### What do you get instead?

Each time build fails cause of different functions. Like sometimes it fails because some selector is not found, sometimes gives error because of some function. And those works after restarting the build.

> Provide console output if related. Use `-vvv` mode for more details.

```[Facebook\WebDriver\Exception\NoSuchElementException] no such element: Unable to locate element: {"method":"id","selector":"user-activity"}```

```[Facebook\WebDriver\Exception\UnknownServerException] [browserstack.local] is set to true but local testing through BrowserStack is not connected. ```

```The command "sudo ee stack install" failed and exited with 1 during .```

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.4.5
* PHP Version: 7.1.16
* Operating System: MAC OS X
* Installation type: Phar || Composer composer.phar
* List of installed packages (`composer show`) - I am Using lucatume/wp-browser package for codeception
* Suite configuration:

```yml

class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WPWebDriver
        - Asserts
    config:
        WPWebDriver:
            host: 'hub-cloud.browserstack.com'
            port: 80
            browser: 'chrome'
            url: 'http://automation.wp.me/'
            adminUsername: ''
            adminPassword: ''
            adminPath: '/wp-admin'
            capabilities:
                'browserstack.user': ''
                'browserstack.key': '%BROWSERSTACK_ACCESS_KEY%'
                'os': 'OS X'
                'os_version': 'sierra'
                'browserstack.debug': 'true'
                'browserstack.networkLogs': 'true'
                'build': '%TRAVIS_BUILD_NUMBER%'
                'project': 'Core-rtMedia Automation'
                'browserstack.local': 'true'
```
