### ISSUE TITLE
Yii2 tests \Yii::$app->end(); after redirect is canceled redirect for functional test

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#5240]
#### What are you trying to achieve?

```
                        \Yii::$app->controller->redirect(\Yii::$app->getUser()->getReturnUrl());
                        \Yii::$app->end();
```
for real apps and accptance tests correctly redirect and show only new page

#### What do you get instead?

        \Yii::$app->end(); after redirect is not apply redirect for functional test

I should use redirect in tests. This is terrible 
        $I->amOnPage(Url::toRoute('/'));

Or, may be, all redirect is failure.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php

```
### Details

* Codeception version: Codeception PHP Testing Framework v2.5.0
Powered by PHPUnit 7.1.5 by Sebastian Bergmann and contributors.

* PHP Version:7.2.10
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
suite_namespace: backend\tests\functional
actor: FunctionalTester
modules:
    enabled:
        - \bscheshirwork\Codeception\Module\DbYii2Config:
            dump: ../common/tests/_data/dump.sql #relative path from "codeception.yml"
            populate: true
            cleanup: true
        - Yii2
        - Asserts
        - common\tests\Helper\Functional

```
