### ISSUE TITLE
Laravel5 - How to set up custom API http headers

### ISSUE THREAD

**Issue by thureos** [Codeception/Codeception#5242]
#### What are you trying to achieve?
Customize the http headers when using:
```php
$this->getModule('Laravel5')->_request()
```
#### What do you get instead?
I cannot use my API as it needs some headers to be set.

### Details

* Codeception version: 2.5.0
* PHP Version: 7.2.7
* Operating System: Linux
* Installation type: Composer

```yml
class_name: ApiTester
modules:
    enabled:
        - Helper\Api
        - Asserts
        - REST:
            depends: Laravel5
            headers:
                header: "value"
        - Laravel5:
            depends: PhpBrowser
            environment_file: .env
            cleanup: false
            url: http://localhost
            headers:
                header: "value"
```
