### ISSUE TITLE
Waitlock issue

### ISSUE THREAD

**Issue by Bartheyrman22** [Codeception/Codeception#5263]
#### What are you trying to achieve?
Using Db Module with parameter according to configuration example.
waitlock: 10
#### What do you get instead?
The following error message

```bash
PHP Fatal error:  Call to undefined method Codeception\Module\Db::__getDriver() in ./vendor/codeception/codeception/src/Codeception/Module/Db.php on line 510
```

### Details

* Codeception version: 2.5
* PHP Version: 5.6
* Operating System: Tested on Linux and Windows 10
* Installation type: Composer
* List of installed packages (`composer show`)
codeception/codeception            2.5.0
codeception/phpunit-wrapper     6.0.10
codeception/stub                         2.0.4

```yml
actor: FunctionalTester
modules:
    enabled:
        - \Helper\Functional
        - Db:
            dsn: 'mysql:host=%HOSTNAME%;dbname=%DATABASE%'
            user: '%USERNAME%'
            password: '%PASSWORD%'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: true
            reconnect: true
            waitlock: 10
```
