### ISSUE TITLE
JUnit no testcases in xml

### ISSUE THREAD

**Issue by gimler** [Codeception/Codeception#5282]
#### What are you trying to achieve?

JUnit output of my acceptance suite only gherkin feature files. The file does not contain any testcase entry. It works with unit and functional test.

It seems to be phpunit incompatibility with 7.4.x. With phpunit 7.3.5 it works.
see for changes https://github.com/sebastianbergmann/phpunit/compare/7.3.5...7.4.0 (most files are tests)

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="acceptance" tests="0" assertions="2" errors="0" failures="0" skipped="0" time="0.000000">
    <testcase ...>
    .....
  </testsuite>
</testsuites>
```

#### What do you get instead?

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="acceptance" tests="0" assertions="2" errors="0" failures="0" skipped="0" time="0.000000"/>
</testsuites>
```
### Details

* Codeception version: 2.5.1
* PHPUnit: 7.4.4
* PHP Version: 7.2.12
* Operating System: Linux
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
class_name: AcceptanceTester
modules:
  enabled:
  - WebDriver:
      host: chrome
      url: 'https://localhost'
      browser: chrome
  - \Helper\Acceptance
```
