### ISSUE TITLE
Codeception acceptance tests  doesn't load pages with coverage flag

### ISSUE THREAD

**Issue by voodooism** [Codeception/Codeception#5288]
#### What are you trying to achieve?
I'm trying to test my Yii2 application by codeception.
I want to see coverage of my code.
I running selenium server:
java -jar -Dwebdriver.chrome.driver=chromedriver /path/to/selenium-server-standalone-3.141.59.jar 
And i run my test in the following way: 
./vendor/bin/codecept run tests/acceptance/callIn/FinishCallCest.php:submitBlank --coverage
#### What do you get instead?
When i run codeception acceptance test without "--coverage" everything works fine.

But if I run the same with the --coverage flag, the following happens:
1. localhost:8080 likn opens and I see in my browser the message "NOT FOUND 404" from Yii2
2. Redirecting to   http://localhost:8080/index-test.php?r=call-in%2Ffinish-call&callId=1 
 and i  get "HTTP 500 ERROR" in my browser

> Here is console output if related. 
```bash
Destroying application
  Starting application
  [ConnectionWatcher] watching new connections
  [Fixtures] Loading fixtures
  [Fixtures] Done
  [GET] http://test:test@localhost:8080/
  [Cookies] [{"domain":"localhost","httpOnly":true,"name":"_csrf","path":"/","secure":false,"value":"60c0fdef20b4ef26022db8cc1882e1b48748818d9f27cf76e028ba5c587c89f6a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22WznRaBoXqDZcCmvGuLD3vDkPOLHgRXND%22%3B%7D"},{"domain":"localhost","expiry":1543607482.820953,"httpOnly":true,"name":"_identity","path":"/","secure":false,"value":"dacb46519512cd901d6c8ceafb494a3d2893b6cf41a196e111c9c522aa4605c9a%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A77%3A%22%5B%22corebofs000080000ktnhd8g9vnbio68%22%2C%22corebofs000080000ktnhd8g9vnbio68%22%2C18000%5D%22%3B%7D"},{"domain":"localhost","expiry":2174309482,"httpOnly":false,"name":"CODECEPTION_CODECOVERAGE","path":"/","secure":false,"value":"{\"CodeCoverage\":\"submitBlankFinishForm\",\"CodeCoverage_Suite\":\"acceptance\",\"CodeCoverage_Config\":null}"},{"domain":"localhost","httpOnly":true,"name":"PHPSESSID","path":"/","secure":false,"value":"e3e9hs9h83hcbdhlne29retj6n"}]
 I am on page "/index-test.php?r=call-in%2Ffinish-call&callId=1"
  [GET] http://test:test@localhost:8080/index-test.php?r=call-in%2Ffinish-call&callId=1
 I wait 5
 I click "//*[@id="w3"]/div[1]/div[1]/h4/a"
  [Selenium server Logs] 
  14:51:20.417 INFO - Capabilities are: {
    "browserName": "chrome"
  }
  14:51:20.417 INFO - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
  14:51:20.849 INFO - Detected dialect: OSS
  14:51:20.881 INFO - Started new session 183fe70c213f5061283786a122f5651a (org.openqa.selenium.chrome.ChromeDriverService)
  
  [Selenium browser Logs] 
  14:51:22.825 SEVERE - http://test:test@localhost:8080/ - Failed to load resource: the server responded with a status of 404 (Not Found)
  14:51:24.651 SEVERE - http://test:test@localhost:8080/index-test.php?r=call-in%2Ffinish-call&callId=1 - Failed to load resource: the server responded with a status of 500 (Internal Server Error)
  
  [Selenium driver Logs]  EMPTY 
  Screenshot and page source were saved into '/var/www/ozon/tests/_output/' dir
 FAIL 

  Destroying application
  [ConnectionWatcher] no longer watching new connections
  [ConnectionWatcher] closing all (0) connections
  Suite done, restoring $_SERVER to original

```
> Provide test source code if related

```php
    public function _before(AcceptanceTester $I)
    {
        $I->amOnPage(Url::toRoute(['/call-in/finish-call', 'callId' => 1 ]));

    }

    public function submitBlankFinishForm(AcceptanceTester $I)
    {
        $I->wait(5);
        $I->click('//*[@id="w3"]/div[1]/div[1]/h4/a');
        $I->wait(5);
        $I->see('Close call', '//*[@id="w1"]/div[4]/button');
        $I->click('//*[@id="w1"]/div[4]/button');
    }
```
### Details

* Codeception version: 2.5.1
* PHP Version: 7.2 
* Operating System: Linux Mint 19 Cinnamon
* Installation type: Composer 
* Codeception.yml configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    memory_limit: 1024M
    colors: true
modules:
    config:
        Yii2:
            configFile: 'config/test.php'
            cleanup: false
coverage:
    c3_url: http://localhost:8080/index-test.php/
    enabled: true
    whitelist:
        include:
            - models/*
            - controllers/*
config:
    test_entry_url: http://localhost:8080/idnex-test.php

```
acceptance.suite.yml configuretion:
```yml
class_name: AcceptanceTester
modules:
    enabled:
#        - PhpBrowser:
#            url: 'http://localhost:8080'
#            auth: ['test', 'test']
        - Yii2:
            part: [orm] # allow to use AR methods
            cleanup: false
        - WebDriver:
            url: 'http://test:test@localhost:8080'
            auth: ['test', 'test']
            browser: chrome
            restart: true
            window_size: 1024x768
```
