### ISSUE TITLE
Build an aggregated code coverage report

### ISSUE THREAD

**Issue by terrasoff** [Codeception/Codeception#5302]
I try to get a full code coverage report.

I have three kind of tests: 
- acceptance
- functional
- unit

And configuration codeception.yml is
```yml
...
coverage:
  enabled: true
  include:
    - src/*
  remote: true
```

I run codeception to build a code coverage report 
```bash
codecept run --coverage --html
```
and i get different kind of reports accordingly (in an output directory):
- acceptance.remote.coverage/*
- functional.remote.coverage/*
- unit.remote.coverage/*

Different parts of a code are tested with different tests. Is there a possibility to get an aggregated report (with full coverage) instead of 3 separate reports?
