### ISSUE TITLE
Job status does not update correctly

### ISSUE THREAD

**Issue by hoangnkvti** [Codeception/Codeception#5312]
#### What are you trying to achieve?
I used codeception with Saucelabs. But after run test, job status is same as test output status. It is always complete

#### What do you get instead?
Job status always is complete

### Details

* Codeception version: 2.5
* PHP Version: 7.2
* Operating System: MacOS 10.14
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: https://example.url
            host: '******:******@ondemand.saucelabs.com'
            browser: chrome
            capabilities:
                platform: 'Windows 10'
        - \Helper\Acceptance
extensions:
    enabled: [Codeception\Extension\RunFailed]
```
