### ISSUE TITLE
Run codeception api tests on test environment 

### ISSUE THREAD

**Issue by Cedric-talentnet** [Codeception/Codeception#5314]
Running codeception api tests on a different server without changing my APP_ENV to "test" in the .env file. For allowing the possibility to automatically run the tests without changing any files.

Something like the possibility of running:
APP_ENV=test codecept run api

Or allowing to override the environment variables defined in the .env from a specific file.

* Codeception version:  last
* PHP Version: 7.2.12
* Operating System: Ubuntu
* Installation type: Composer

**Comment by Naktibalda** [comment]
Which module are you using in your tests?

**Comment by Cedric-talentnet** [comment]
This is my api.suite.yml

actor: ApiTester
modules:
    enabled:
        - REST:
              url: '%API_TEST_URL%'
              depends: PhpBrowser
              part: Json

coverage:
    enabled: false

I'm not using the cleanup etc, i have a custom method doing that with a mongorestore command called in the _before.

**Comment by Cedric-talentnet** [comment]
In fact i've found a solution, it i change to 

```yml
actor: ApiTester
modules:
    enabled:
    - Symfony:
          app_path: 'src'
          environment: 'test'
    - REST:
          url: /
          depends: Symfony
          part: Json
```
No i can correctly connect to the test env. I only need to find why now the response are not complete json response like for example:
 "{"message":"Something happened and we could not create your account. Please refresh your browser and try again."}"
But only the content of the message instead, returned as a string.
example:
"Something happened and we could not create your account. Please refresh your browser and try again."
But thanks for you help already.
