### ISSUE TITLE
Group flag doesn't work anymore in codecept.phar 2.5.1

### ISSUE THREAD

**Issue by leonardor** [Codeception/Codeception#5318]
I try to run codecept.phar version 2.5.1 with -g flag to select only the tests I am interested in to run.

After I run the command like that:

`php codecept.phar run functional -g group_name -vvv --debug`

and it just outputs this after a long time:

```
Codeception PHP Testing Framework v2.5.1
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
Running with seed:

[Groups] group_name
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to al
locate 262144 bytes) in phar://C:/workspace/laravel/workbench/application/codecept.phar/src/Codeception/Test/Cest.php on line 160
```

There are 48 files in the functional suite folder and as far as I understand it first parses the annotations of all tests and then identifies the groups, and at one point it gets stuck at one test and method in particular.

I tried to remove one by one the test files and see which causes the problem and I have identified it. There is a test which has a method that is 51 characters long. If  I remove one character and if its name fits exactly 50 characters long the suite runs perfectly.

I can't figure out if this is a Codeception problem of a PHPUnit problem.

* Codeception version: 2.5.1
* PHP Version: 7.1.5
* Operating System: Windows 10
* Installation type: Phar
* List of installed packages (`composer show`)
```
platform:
  composer-plugin-api 1.0.0    The Composer Plugin API
  ext-bcmath          7.1.5    The bcmath PHP extension
  ext-calendar        7.1.5    The calendar PHP extension
  ext-ctype           7.1.5    The ctype PHP extension
  ext-curl            7.1.5    The curl PHP extension
  ext-date            7.1.5    The date PHP extension
  ext-dom             20031129 The dom PHP extension
  ext-filter          7.1.5    The filter PHP extension
  ext-hash            1.0      The hash PHP extension
  ext-iconv           7.1.5    The iconv PHP extension
  ext-json            1.5.0    The json PHP extension
  ext-libxml          7.1.5    The libxml PHP extension
  ext-mbstring        7.1.5    The mbstring PHP extension
  ext-mcrypt          7.1.5    The mcrypt PHP extension
  ext-mysqlnd         0        The mysqlnd PHP extension
  ext-openssl         7.1.5    The openssl PHP extension
  ext-pcre            7.1.5    The pcre PHP extension
  ext-PDO             7.1.5    The PDO PHP extension
  ext-Phar            2.0.2    The Phar PHP extension
  ext-readline        7.1.5    The readline PHP extension
  ext-Reflection      7.1.5    The Reflection PHP extension
  ext-session         7.1.5    The session PHP extension
  ext-SimpleXML       7.1.5    The SimpleXML PHP extension
  ext-SPL             7.1.5    The SPL PHP extension
  ext-tokenizer       7.1.5    The tokenizer PHP extension
  ext-wddx            7.1.5    The wddx PHP extension
  ext-xml             7.1.5    The xml PHP extension
  ext-xmlreader       7.1.5    The xmlreader PHP extension
  ext-xmlwriter       7.1.5    The xmlwriter PHP extension
  ext-zip             1.13.5   The zip PHP extension
  ext-zlib            7.1.5    The zlib PHP extension
  lib-curl            7.54.0   The curl PHP library
  lib-iconv           1.15     The iconv PHP library
  lib-libxml          2.9.4    The libxml PHP library
  lib-openssl         1.0.2.11 The openssl PHP library
  lib-pcre            8.38     The pcre PHP library
  php                 7.1.5    The PHP interpreter

available:

```
* Suite configuration:

```yml
class_name: FunctionalTester
settings:
    bootstrap: _bootstrap.php
modules:
    enabled:
        - \Helper\Functional
        - Asserts
        - Cli
        - PhpBrowser:
            url: http://some_url
        - REST:
            depends: PhpBrowser
            part: Json
groups:
    # add all tests from a directory to api group
    frontend: [tests/functional/frontend]
    backend: [tests/functional/backend]

env:
    frontend:
        modules:
            config:
                PhpBrowser:
                    url: http://some_url
                    curl:
                        CURLOPT_TIMEOUT: 10
                REST:
                    depends: PhpBrowser
                    part: Json
                    timeout: 10
    backend:
        modules:
            config:
                PhpBrowser:
                    url: http://some_url
                    curl:
                        CURLOPT_TIMEOUT: 10
                REST:
                    depends: PhpBrowser
                    part: Json
                    timeout: 10

```
