### ISSUE TITLE
Doctrine `cleanup: true` not working

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5326]
#### What are you trying to achieve?

Rollback the transcation.

#### What do you get instead?

Changes are kept in the database.

> Provide console output if related. Use `-vvv` mode for more details.

The output does start with:
> Scenario --
  [Database] Transaction started
  [Database] Transaction started

But this is *not* shown at the end of the output (no matter if the test passes or not):
> [Database] Transaction cancelled; all changes reverted.

### Details

* Codeception version: 2.5.2
* Symfony version: 4.2.1
* PHP Version: 7.2.10
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: 'src'
            environment: 'test'
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - REST:
            depends: Symfony
        - Asserts
        - \App\Tests\Helper\Functional
```
