### ISSUE TITLE
Issue with remote coverage report for functional tests

### ISSUE THREAD

**Issue by rjlmartins** [Codeception/Codeception#5330]
#### What are you trying to achieve?

The coverage report for the functional tests API

#### What do you get instead?

The tests execute, but i got an error while generating the coverage report

```bash
In RemoteServer.php line 55:

  internal corruption of phar "/tmp/C3Zi0zxE.tar" (__HALT_COMPILER(); not found)
```
The .tar file contains some script tags, and redirect to login

```php
cat /tmp/C3JP50Je.tar
<script type="text/javascript" src="../admin/WN.js"></script><script type="text/javascript">WN.loginNow();</script>
```
### Details

* Codeception version: 2.5.2
* PHP Version: 7.1.25
* Operating System: Ubuntu
* Installation type: Composer
* xDebug Version: 2.6.1
* c3.php is included on my index.php file
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - PhpBrowser:
           url: "%phpbrowser_url%"
           auth: ["%phpbrowser_user%", "%phpbrowser_password%"]
           curl:
               CURLOPT_RETURNTRANSFER: true
        - REST:
            url: "%rest_url%"
            depends: PhpBrowser
        - \core\Helper\Functional
coverage:
    enabled: true
    remote: true
    c3_url: "%phpbrowser_url%index.php"
    include:
        - ../admin/*.php
    exclude:
        - ../admin/data/*
```

What might be missing on my configuration?

Since i'm using PhpBrowser based on specific authentication, do i need to do something special so that the coverage steps over this authentication?

Thanks.
