### ISSUE TITLE
Different results if I run one test and all test in same time

### ISSUE THREAD

**Issue by ilijastojkovic** [Codeception/Codeception#5333]
#### What are you trying to achieve?
Right now, I have some strange behaviour while running functional tests. If I run one file `codecept run functional /FunctionalFolder/Services/ServiceOneCest`, all tests are success - as expected. But in secound case, when I run all created tests `codecept run functional /FunctionalFolder`, some tests are finished as expected, while some others are failed. 

Somehow, in _before() section, are not executed all dependeces.

```
class ServiceOneCest
{
public function _before(FunctionalTester $I)
 {
            $this->entityManager = $I->grabServiceFromContainer(EntityManager::class);
            $this->entity = $this->entityManager->getRepository(Entity::class)
            ->findOneBy([
                'name' => 'test'
            ]);
         
        if (!$entity) {
            $this->entity = $I->have(Entity::class, ['name' => 'test']);
        }
}

public function testSomething(FunctionalTester $I)
{
      $I->assertEquals('test', $this->entity->getName());
      // here I catch error message [Error] Call to a member function getName() on null
      // it only happend when I run more then one test file
}
}

//also exist some other test file

class ServiceTwoCest
{
}
```

I expect same results if I run one test file or more. I need to say, don't have any dependece between test data created in `_before()`

Please, if you see any reason or my bad code/configuration anything, give me handsup. If you have some other questions, please feel free to contact me.

### Details 

* Codeception version: 2.5.1
* PHP Version:PHP 7.1.25
* Operating System: ubuntu16.04.1
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:
```
actor: FunctionalTester
modules:
    enabled:
        - ZF2
        - Asserts
        - \Helper\Functional
        - Doctrine2:
            depends: ZF2
        - DataFactory:
            depends: Doctrine2
        - \Helper\Factories
    config:
        Doctrine2:
            cleanup: true
```
