### ISSUE TITLE
Call to undefined function Codeception\Module\codecept_absolute_path()

### ISSUE THREAD

**Issue by komandakycto** [Codeception/Codeception#5338]
#### What are you trying to achieve?
I create test docker-compose file like in docs https://codeception.com/docs/12-ParallelExecution
and trying to run tests as `docker-compose run --rm codecept run acceptance`.
My project source code already have codeception. All composer depends are installed.
If I run tests in my develop environment tests works. If I run tests into php-fpm container tests works.
But if I run tests in codeception container tests isn't work. My docker-compose.yml:
```yml
version: '3'
services:
  codecept:
    image: codeception/codeception
    depends_on:
      - php-fpm
      - nginx
    volumes:
      - ../../:/project
  php-fpm:
    restart: always
    links:
      - postgresql
    build: ./php
    ports:
      - '9090:9000'
    volumes:
      - ../../:/var/www/html/
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
  postgresql:
    build:
      ./postgresql
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      - backend
  nginx:
    image: nginx:alpine
    links:
      - php-fpm
    ports:
      - '8081:80'
    volumes:
      - ../../:/var/www/html/
      - ./nginx/config:/etc/nginx/conf.d/
    networks:
      backend:
        aliases:
          - test.local
networks:
  backend:
    driver: bridge
```

#### What do you get instead?

```bash
Codeception PHP Testing Framework v2.3.9
Powered by PHPUnit 6.5.8 by Sebastian Bergmann and contributors.

Fatal error: Uncaught Error: Call to undefined function Codeception\Module\codecept_absolute_path() in /project/vendor/codeception/base/src/Codeception/Module/Yii2.php on line 242

Error: Call to undefined function Codeception\Module\codecept_absolute_path() in /project/vendor/codeception/base/src/Codeception/Module/Yii2.php on line 242

Call Stack:
    0.0002     405792   1. {main}() /repo/codecept:0
    0.0974    8447496   2. Codeception\Application->run() /repo/codecept:42
    0.0974    8447496   3. Codeception\Application->run() /repo/src/Codeception/Application.php:108
    0.1068    8671880   4. Codeception\Application->doRun() /repo/vendor/symfony/console/Application.php:143
    0.1072    8671880   5. Codeception\Application->doRunCommand() /repo/vendor/symfony/console/Application.php:241
    0.1072    8671880   6. Codeception\Command\Run->run() /repo/vendor/symfony/console/Application.php:865
    0.1087    8679176   7. Codeception\Command\Run->execute() /repo/vendor/symfony/console/Command/Command.php:252
    0.1251    9308920   8. Codeception\Codecept->run() /repo/src/Codeception/Command/Run.php:355
    0.1336    9315512   9. Codeception\Codecept->runSuite() /repo/src/Codeception/Codecept.php:158
    0.1346    9353936  10. Codeception\SuiteManager->__construct() /repo/src/Codeception/Codecept.php:186
    0.1414    9826952  11. Codeception\Lib\ModuleContainer->create() /project/vendor/codeception/base/src/Codeception/SuiteManager.php:67
    0.1432    9929288  12. Codeception\Lib\Di->instantiate() /project/vendor/codeception/base/src/Codeception/Lib/ModuleContainer.php:92
    0.1432    9929576  13. ReflectionClass->newInstanceArgs() /project/vendor/codeception/base/src/Codeception/Lib/Di.php:84
    0.1463   10135536  14. Codeception\Module\Yii2->__construct() /project/vendor/codeception/base/src/Codeception/Lib/Di.php:84
    0.1463   10135536  15. Codeception\Module\Yii2->_setConfig() /repo/src/Codeception/Module.php:76
    0.1464   10136232  16. Codeception\Module\Yii2->validateConfig() /repo/src/Codeception/Module.php:98

```
### Details

* Codeception version: 2.3.9
* PHP Version: PHP 7.2.4 (cli)
* Operating System: Linux Mint
* Installation type: Composer
* Suite configuration:

```yml
# paste suite config here
class_name: ApiTester
modules:
    enabled:
        - REST:
            depends: PhpBrowser
            url: '%BASE_URL%/index-test.php'
            part: [json]
        - Yii2:
            part: [orm, fixtures]
            transaction: false
            entryScript: index-test.php
        - Asserts
```
