### ISSUE TITLE
Run groups with -c options not working

### ISSUE THREAD

**Issue by komandakycto** [Codeception/Codeception#5343]
#### What are you trying to achieve?
I have project structure
-root
---api
----tests
------api/
------functional/
------unit/
------api.suite.yml
------functional.suite.yml
------unit.suite.yml
----codeception.yml
--backend/
--common/
-codeception.yml

For run api test I execute command and tests work perfectly
```sh
php vendor/bin/codecept run -c api api
```
Now I want run tests from group. I have a three group in `api/tests/_groups/`
I change my `api/codeception.yml` and add
```yml
groups:
    paracept_*: tests/_groups/paracept_*
```
And execute command but tests not working
```sh
php vendor/bin/codecept run -c api api -g paracept_2
```
#### What do you get instead?
Group not selected and tests is empty

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# php vendor/bin/codecept run -c api api -g paracept_2 -vvv
Codeception PHP Testing Framework v2.5.2
Powered by PHPUnit 7.5.1 by Sebastian Bergmann and contributors.
Running with seed: 

[Groups] paracept_2 

Api\tests.api Tests (0) -------------------------------------------------------------------------------------------------------------------------------------------------
Modules: REST, PhpBrowser, Yii2, Asserts, Filesystem
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  Suite done, restoring $_SERVER to original
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 668 ms, Memory: 12.00MB

```
### Details

* Codeception version:
* PHP Version: PHP 7.1.22 (cli) (built: Sep 15 2018 04:13:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.22, Copyright (c) 1999-2018, by Zend Technologies
* Operating System: Linux Mint 19 Cinnamon
* Installation type: Composer
* Suite configuration:

```yml
namespace: api\tests
actor: Tester
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
params:
    - ./../.env
modules:
    enabled:
      - Filesystem
      - Yii2
      - REST
    config:
        Yii2:
            configFile: 'config/test.php'
reporters:
    report: PHPUnit\Util\Log\TeamCity
groups:
    paracept_*: tests/_groups/paracept_*
```
My root codeception.yml
```yml
# global codeception file to run tests from all apps
include:
    - api
    - common
    - console
paths:
    log: console/runtime/logs
settings:
    colors: true
```
