### ISSUE TITLE
Cannot run parallel execution for phalcon project

### ISSUE THREAD

**Issue by xdn27** [Codeception/Codeception#5352]
Hallo guys

I want to setup and run test my phalcon project with codeception parallel execution

Before getting this error, I have faced error with pdo extension not found but I can solved by installed the pdo_mysql inside the dockerfile.

Then I get error again when run the test, I guess the error appear because there is no phalcon extension installed on codeception image. I have tried to install manually via dockerfile and inside the container with bash but never success, there are always error with some package not found or not installable etc.

This the error output on console

```bash
==== Redirecting to Composer-installed version in vendor/codeception ====
Codeception PHP Testing Framework v2.5.2
Powered by PHPUnit 4.8.36-1-g18e5f52e8 by Sebastian Bergmann and contributors.
Running with seed: 


  [Connecting To Db] {"config":{"populate":false,"cleanup":true,"reconnect":false,"waitlock":0,"dump":null,"populator":null,"dsn":"mysql:host=mysql;dbname=db_test","user":"root","password":"root"},"options":[]}
  [Db] Connected to default db_test

Acceptance Tests (48) ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: WebDriver, Asserts, \Helper\Acceptance, Db, Phalcon
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
AutoresponderCest: Checking autoresponder list page
Signature: AutoresponderCest:checkAutoresponderList
Test: tests/acceptance/AutoresponderCest.php:checkAutoresponderList
Scenario --
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Fatal error: Uncaught Error: Class 'Phalcon\DI\FactoryDefault' not found in /application/app/config/bootstrap.php on line 2

Error: Class 'Phalcon\DI\FactoryDefault' not found in /application/app/config/bootstrap.php on line 2

```

This is sample of test code

```php
<?php
use \Facebook\WebDriver\WebDriverElement;

class  AutoresponderCest
{
	public  function  _before(AcceptanceTester  $I)
	{
		$I->amOnPage('/');
		$I->fillField('email', 'test');
		$I->fillField('password', 'test');
		$I->click('.btn-block');
	}

	public  function  checkAutoresponderList(AcceptanceTester  $I)
	{
		$I->wantTo('Checking autoresponder list page');
		$I->amOnPage('/autoresponders');
		$I->see('Manage Autoresponders');
		$I->wantTo('Checking table');
		$I->waitForElementVisible('select[name=datatable_length]', 1);
		$I->selectOption('select[name=datatable_length]', 50);
		$I->waitForElementChange('#datatable tbody', function(WebDriverElement  $el){
			return  $el->isDisplayed();
		});
	}
}
```
### Details

* Codeception version: 2.5
* PHP Version: 7.2
* Operating System: ubuntu
* Installation type: Composer
* Suite configuration:

```yml
actor: Tester
paths:
        tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs

settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    log: true
    
coverage:
    enabled: true
    whitelist:
    include:
        - app/*
extensions:
    enabled:
        - Codeception\Extension\RunFailed

modules:
    enabled:
        - Phalcon:
            part: services
            bootstrap: 'app/config/bootstrap.php'
            # bootstrap: 'public/index.php'
            cleanup: true

    config:
        Db:
            dsn: 'mysql:host=mysql;dbname=db_test'
            user: 'root'
            password: 'root'
            # dump: tests/_data/dump.sql
            cleanup: true
        WebDriver:
            host: chrome.vm
            url: http://app.vm/
            browser: chrome
            port: 4444
            window_size: 1200x768
            restart: true

error_level: "E_ALL | E_STRICT"
```

 Hope there is a solution or explanation

Update
/application/app/config/bootstrap.php
```php
<?php
$di = new \Phalcon\DI\FactoryDefault();
return new \Phalcon\Mvc\Application($di);
```

**Comment by sergeyklay** [comment]
@xdn27 Could you please provide content of the `/application/app/config/bootstrap.php` file.

**Comment by xdn27** [comment]
> @xdn27 Could you please provide content of the `/application/app/config/bootstrap.php` file.

Ok @sergeyklay

**Comment by sergeyklay** [comment]
There is no `Phalcon\DI\FactoryDefault` class. Please use the proper namespace: `Phalcon\Di\FactoryDefault` and recheck again.

**Comment by xdn27** [comment]
I guess the problem is not in that class, because I have tried a test locally (I mean not use parallel execution) and it's work fine.

**Comment by sergeyklay** [comment]
@xdn27 How do you use parallel execution? Is it docker-based solution? If so I'll need to the docker image. Otherwise I'll need the steps to reproduce at my home laptop. Let's assume I have fresh Ubuntu installed w/o nothing.

**Comment by xdn27** [comment]
Ya.. I was using docker-compose with nginx web server, mysql, selenium chrome and codeception image
This is the docker-compose for codeception

```yml
codecept:
      container_name: codecept
      build: codeception
      working_dir: /application
      depends_on:
        - chrome
        - webserver
        - php-fpm
        - traefik
        - mysql
      volumes:
        - ./application/myapp:/application
        - ./application/myapp/tests:/application/tests
        - ./application/myapp/codeception.yml:/application/codeception.yml
      networks:
        vm:
```

This is a dockerfile for codeceptioon
```
FROM codeception/codeception

RUN apt-get update \
    && curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh | bash \
    && apt-get install -y php7.2-phalcon=3.4.2-2+php7.2 \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

RUN docker-php-ext-install \
    pdo_mysql
```
As you can see, I try to install phalcon extension here but it cannot. This the output
```
The following packages have unmet dependencies:
 php7.2-phalcon : Depends: phpapi-20170718
E: Unable to correct problems, you have held broken packages.
```
And I dont know why I cannot install the phpapi-20170718 (here the problem)

The steps I run, just with "sudo docker-compose up", then run "docker-compose run --rm codecept run acceptance" on another tab in the same directory
