### ISSUE TITLE
Why yii2 connector catch only HttpException?

### ISSUE THREAD

**Issue by Sentoki** [Codeception/Codeception#5357]
#### What are you trying to achieve?

I try test (with api test and yii2 module) that application return correct api anwers with correct error info in case wrong input.

#### What do you get instead?

I get error that passes by my custom error handler that should prepare response data.

1) I validate input, found error
2) Throw InvalidArgumentException that should be handled by my code and i expect that this method should be called: https://github.com/Codeception/Codeception/blob/198769e19a3f4f313b623386e1d558f5bfcce61d/src/Codeception/Lib/Connector/Yii2.php#L340
3) But because InvalidArgumentException is not HttpException i get here: https://github.com/Codeception/Codeception/blob/198769e19a3f4f313b623386e1d558f5bfcce61d/src/Codeception/Lib/Connector/Yii2.php#L343 and assertion failed

```php
$I->seeResponseContainsJson(['error_message' => 'some message']);
```
So why only HttpException allowed to be processed by error handler in test environment? 

### Details

* Codeception version: 2.5.2
* PHP Version: 7.0.33
* Operating System: ubuntu18.04.1
* Installation type: Composer
* Suite configuration:

```yml
actor: ApiTester
modules:
    config:
      Yii2:
        configFile: '../lib/yii/config/api_test.php'
        transaction: false
    enabled:
        - REST:
              depends: Yii2
        - Db:
            dsn: 'pgsql:host=localhost;dbname=test'
            user: 'test'
            password: 'test'
            cleanup: true
paths:
  output: '_output'
  tests: ''
  data: '_data'
  support: '_support'
settings:
  bootstrap: _bootstrap.php
coverage:
  enabled: true
  include:
  - ../lib/*
  exclude:
  - ../lib/yii/vendor/*
  - ../lib/yii/runtime/*

```
