### ISSUE TITLE
Merging Acceptance and unit coverage

### ISSUE THREAD

**Issue by jcheron** [Codeception/Codeception#5368]
#### What are you trying to achieve?
I have acceptance tests and unit tests that work perfectly.
Acceptance tests and unit tests run on the same physical files (identical paths).
I would like to get the total coverage of these tests

#### What do you get instead?
The 2 generated xml files refer to the same tested files (identical paths and namespaces), however acceptance coverage (from local web server)  and  unit tests coverage are not merged.
total coverage only considers local unit tests, although the coverage is a local coverage!

I know it's not a new problem, and has been met by others.
But I did not find the answer anywhere, see also:
- https://github.com/Codeception/Codeception/issues/655
- https://github.com/Codeception/Codeception/issues/1679
- https://github.com/Codeception/Codeception/issues/3245

I run the tests with the following command:
```bash
./vendor/bin/codecept build && ./vendor/bin/codecept run --coverage-xml --fail-fast
```
### Details
* Codeception version: 2.5.2
* PHP Version: 7.2.13
* Operating System: Debian ? (Scrutinizer-ci)
* Installation type: Composer
* Xdebug (remote_enable): on
* c3 installed on the web server

### unsuccessful attempts
  - I tried setting the `remote` value to true, it did not change anything

#### with remote: true
The `--coverage-xml` option generates:
  - in `_output`local folder: 
        - `acceptance.remote.coverage.xml` -> **ok for acceptance (813 Ko)**
        - `coverage.xml` -> **ok for unit (866 Ko)**
        - `coverage.serialized`
  - in `_output/c3tmp` remote folder: 
        - `codecoverage.clover.xml`
        - `codecoverage.serialized`

#### with remote: false
The `--coverage-xml` option generates:
  - in `_output`local folder: 
        - `coverage.xml` -> **no merge = only unit results (866 Ko)**
        - `coverage.serialized`
  - in `_output/c3tmp` remote folder: 
        - `codecoverage.serialized`

#### With the option `work_dir`
see https://github.com/Codeception/Codeception/issues/5302
No more result
If I only run the acceptance tests,
```bash
./codecept run acceptance --coverage --coverage-xml
```
the result is empty:
```
Time: 23.05 seconds, Memory: 10.00MB
OK (20 tests, 39 assertions)

Code Coverage Report:
  2019-01-30 11:12:24

 Summary:
  Classes:  0.00% (0/199)
  Methods:  0.00% (0/1773)
  Lines:    0.00% (0/13282)
```

In both cases, no merge was done, while the files tested are the same.

  - I tried to use [phpcov](https://github.com/sebastianbergmann/phpcov) . See also https://github.com/Codeception/Codeception/issues/3245#issuecomment-228812484
    - I generate coverage files in serialized format (--coverage)
    - After the tests, I copy the remote file in the same folder that the local
    - phpcov produces an xml file that results in the same coverage... 

```bash
./vendor/bin/codecept build && ./vendor/bin/codecept run --coverage
cp tests/fw/prj-test-admin/tests/_output/c3tmp/codecoverage.serialized tests/_output/remote.codecoverage.serialized
./vendor/bin/phpcov merge tests/_output/ --clover tests/_output/clover.xml
```
#### The local codeception.yml file:
```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: false
    work_dir: '/build/'    
    c3_url: 'http://dev.local/prj-test-admin'
    include:
        - tests/fw/prj-test-admin/Project/*
```

#### The codeception.yml file on the local web server:
The web root folder is `tests/fw`
```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: false
    work_dir: '/build/tests/fw/prj-test-admin/'    
    c3_url: 'http://dev.local/prj-test-admin'
    include:
        - Project/*
```

**Comment by jcheron** [comment]
I misinterpreted the sentence from the documentation:
`In this case remote Code Coverage results won’t be merged with local ones, if this option is enabled. Merging is possible only in case a remote and local files have the same path. But in case of running tests on a remote server we are not sure of it.`
I had a double configuration of codeception, one in local, the other on the web server, making sure that the tested files have the same path...
But obviously, it's not possible that way.

I found the solution by modifying the file structure so that the same Codeception client could test all the files (with only 1 configuration):
```
webRoot(http://dev.local)/
       └ tests/
       └ webFiles/
       └ filesToTest
       codeception.yml
```
The `codeception.yml` file:
```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: false
    c3_url: 'http://dev.local'

    include:
        - filesToTest/*
```
Everything works perfectly!
