### ISSUE TITLE
Problems with fillField on real device with safari

### ISSUE THREAD

**Issue by elijah0107** [Codeception/Codeception#5370]
#### What are you trying to achieve?
I am trying to fill field on real device with browser safari. But after but after going to the next step, value in input becomes empty
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
        $I->amOnPage(CartPage::$acceptanceRoute);
        $I->wait(2);
        $I->waitForElementVisible(CartPage::$checkoutButtonSelector);
        $I->click(CartPage::$checkoutButtonSelector);
        $I->wait(3);
        $I->fillField(OrderForm::$inputEmailFieldSelector, 'bfhjsadf@jafgvadfhgdf.eu');
        $I->wait(2);
        $I->fillField(OrderForm::$inputNameFieldSelector, 'test');
        $I->appendField(OrderForm::$inputNameFieldSelector, 'test');
        $I->click(OrderPage::$newOrderSendOrderButtonSelector);
```
### Details

* Codeception version: 2.5.5
* PHP Version: 5.6
* Operating System: MacOS
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: Acceptance_mobileTester
modules:
    enabled:
        - WebDriver
        - Asserts
        - tests\AcceptanceHelper
    config:
        WebDriver:
            host: seleniumhub
            url:
            browser: safari
env:
    iphone:
           modules:
               enabled:
                  - WebDriver
                  - Asserts
               config:
                   WebDriver:
                      host: 0.0.0.0
                      port: 4723
                      url: ***
                      browser: safari
                      restart: true
                      timeout: 100
                      capabilities:
                          browserName: safari
                          xcodeOrgId: '79C4Q93M59'
                          xcodeSigningId: 'iPhone Developer'
                          platformName: 'iOS'
                          platformVersion: '12.1.2'
                          deviceName: 'iPhone'
                          udid: 'f325b6bc5fe21a3fc9657ed75a28df4c438c3c83'
                          useNewWDA: false
                          newCommandTimeout: 7200
                          automationName: 'XCUITest'
                          autoAcceptAlerts: true
                          fullReset: false
                          noReset: true
                          nativeInstrumentsLib: true
                          connection_timeout: 500cd
                          request_timeout: 500
                          skipUnlock: true
                          clearSystemFiles: true
                          showIOSLog: true
                          safariInitialUrl: about:blank
                          CURLOPT_TIMEOUT: 900
```
