### ISSUE TITLE
Change specific config value in specific test

### ISSUE THREAD

**Issue by markodemo1305** [Codeception/Codeception#5388]
One setting which is set in global config file for all browsers needs to be changed in one test only.

Config file:
```yml
chrome:
    modules:
      config:
        \Common\Module\Driver\BrowserStack:
          capabilities:
            browser: chrome
            browserstack.chrome.enablePopups: true

  firefox:
    modules:
      config:
        \Common\Module\Driver\BrowserStack:
          capabilities:
            browser: firefox
            browserstack.firefox.enablePopups: true

  safari:
    modules:
      config:
        \Common\Module\Driver\BrowserStack:
          capabilities:
            browser: safari
            browserstack.safari.enablePopups: true
```

For one test only, browserstack.safari.enablePopups should be set to false. 
Is there any way to do this for all browsers in single test run?
