### ISSUE TITLE
[Facebook\WebDriver\Exception\UnknownServerException] unknown error: operation is unsupported on Android

### ISSUE THREAD

**Issue by elijah0107** [Codeception/Codeception#5390]
#### What are you trying to achieve?
I want to run tests on Android table on the notmobile website
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
[Facebook\WebDriver\Exception\UnknownServerException] unknown error: operation is unsupported on Android
  (Session info: chrome=72.0.3626.105)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.15.0-45-generic x86_64)  
                                                                                                                                                                                                                                                                                
#1  /project/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:114
#2  /project/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:326
#3  /project/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:547
#4  /project/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
#5  /project/vendor/facebook/webdriver/lib/WebDriverWindow.php:104
#6  /project/vendor/symfony/event-dispatcher/EventDispatcher.php:212
#7  /project/vendor/symfony/event-dispatcher/EventDispatcher.php:44
#8  /repo/autoload.php:12
#9  /repo/codecept:7

```
> Provide test source code if related

```php
 if ($I->waitPageElement(CatalogPage::$minQtyFilterIdSelector)) {
            $I->click(CatalogPage::$minQtyFilterIdSelector);
            $I->click(CatalogPage::$minQtySecondCheckBoxSelector);
            $I->waitForElementVisible(CatalogPage::$popUpWithFoundItemsSelector);
            $I->checkOption(CatalogPage::$minQtyFirstCheckBoxSelector);
            $I->waitForElementVisible(CatalogPage::$popUpWithFoundItemsSelector);
            $I->click(CatalogPage::$showButtonOnPopUpSelector);
            $I->waitForElementVisible(CatalogPage::$filterFlagSelector);
            $I->waitForText('2', 4, CatalogPage::$spanFilterFlagQty);
            $I->see('Минимальная партия');
        } else {
            return $I->fail('Фильтр не найден');
        }
        $I->click(CatalogPage::$filterFlagSelector);
        $I->waitForElement(CatalogPage::$chosenFiltersPopUpSelector);
        $I->scrollTo(CatalogPage::$secondCheckBoxInPopUpSelector);
        $I->click(CatalogPage::$secondCheckBoxInPopUpSelector);
        $I->wait(2);
        $I->click(CatalogPage::$showButtonInChosenFiltersPopUpSelector);
        $I->waitForText('1', 4, CatalogPage::$spanFilterFlagQty);
```
### Details

* Codeception version:
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
asus:
        modules:
            enabled:
                - WebDriver
                - Asserts
            config:
                WebDriver:
                    host: asus
                    url: ****
                    browser: chrome
                    port: 4723
                    restart: true
                    capabilities:
                        browserName: chrome
                        platformName: Android
                        deviceName: Asus
                        platformVersion: 5.0.2
```
