### ISSUE TITLE
Error with chromedriver 2.46

### ISSUE THREAD

**Issue by JorisVanEijden** [Codeception/Codeception#5401]
#### What are you trying to achieve?
Use chromedriver to run tests.

#### What do you get instead?
```
[Facebook\WebDriver\Exception\UnrecognizedExceptionException] invalid argument: invalid 'expiry'
(Session info: chrome=72.0.3626.81)
(Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.9.125-linuxkit x86_64)

#1  /var/www/html/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:158
#2  /var/www/html/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:326
#3  /var/www/html/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:547
#4  /var/www/html/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
#5  /var/www/html/vendor/facebook/webdriver/lib/WebDriverOptions.php:55
#6  Codeception\Module\WebDriver->loadSessionSnapshot
```

### Details

* Codeception version: 2.5.3
* PHP Version: 7.1
* Operating System: Any
* Installation type: Composer
* Suite configuration:

```yml
modules:
    enabled:
        -
          WebDriver:
            browser: chrome
            capabilities:
              javascriptEnabled: true
              resourceTimeout: 300000
            host: %WEBDRIVER_HOST%
            url: %WEBSITE_URL%
```

Chromedriver 2.45 works fine.
In 2.46 they added extra cookie validation (https://chromium-review.googlesource.com/c/chromium/src/+/1366925)
