### ISSUE TITLE
Local Codecoverage for Unit / Integration doesn't run if AcceptanceSuite has WebDriver

### ISSUE THREAD

**Issue by tgaertner** [Codeception/Codeception#5405]
I want to run local Unit and Integration Tests with codecoverage

If I configure a Webdriver in Acceptance.suite.yml - coverage tests for Unit and Integration fails with error-message: file_get_contents(http://web/c3/report/clear): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found

My call: codecept run --coverage --coverage-xml --coverage-html Unit

* Codeception version: 2.3.9
* PHP Version: 7.2.14
* Operating System: DDEV Docker 
* Installation type: CakePHP App via Composer

* config:

```yml
coverage:
    enabled: true
    show_only_summary: false
    include:
        - src/*
    exclude:
        - src/TestSuite/*
        - src/Template/*
```

* Acceptance.suite.yml

```yml
actor: AcceptanceTester
namespace: App\TestSuite\Codeception
suite_namespace: App\Test\Acceptance
modules:
    enabled:
        - WebDriver:
             url: 'http://web'
             browser: chrome # 'chrome' or 'firefox'
             host: selenium
        - \App\TestSuite\Codeception\Helper\Acceptance
```

If I change this to:
```yml
actor: AcceptanceTester
namespace: App\TestSuite\Codeception
suite_namespace: App\Test\Acceptance
modules:
    enabled:
        - \App\TestSuite\Codeception\Helper\Acceptance
```
codecoverage like above works.
I don't want to configure the remote stuff with c3... I just need local testing for this.
