### ISSUE TITLE
Delete request always times out when using http headers

### ISSUE THREAD

**Issue by SimonTod** [Codeception/Codeception#5413]
#### What are you trying to achieve?
I am trying to test my API, every thing works excepts the Delete method.
My API works, as I am able to test the Delete method myself using a custom curl command ran in bash console.
But what happens with my codeception configuration is a curl timeout error
```
[GuzzleHttp\Exception\ConnectException] cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
``` 
on the Delete method when i set some headers. If I remove the headers, the request will return something, but of course it does not do what I want, as the API needs these headers in order to work.

### Details

* Codeception version: 2.5.2
* PHP Version: 7.1.24
* Operating System: debian
* Installation type: Composer
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - \Helper\HttpCodeHelper
        - \Helper\DbHelper
        - \Helper\Building
        -  Asserts
        - Cli
        - Symfony
        - REST
        - Db
    config:
        Symfony:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'
        REST:
            url: 'http://%API_HOST_AND_PORT%/'
            depends: PhpBrowser
            part: Json
        PhpBrowser:
            url: 'http://%API_HOST_AND_PORT%/'
            headers:
                header: {value}
                Content-Type: application/json
        Db:
            dsn: 'mysql:host=%BDD_MYSQL_HOST%;dbname=%BDD_MYSQL_DATABASE%'
            user: '%BDD_MYSQL_USER%'
            password: '%BDD_MYSQL_PASSWORD%'
```

**Comment by Naktibalda** [comment]
I've seen something like this with Node.js app (I used curl or wget in command line).
I think that it is a bug of your API and it could be caused by http keepalive feature or something similar.

**Comment by SimonTod** [comment]
One more thing to notice is that on my dev environement everything works like it should, I get this problem my test environment. We use docker containers on both of these environment so that we keep them very similar

**Comment by SimonTod** [comment]
I found out where the problem came from.
My container was using a proxy to make request. And this proxy was rejecting any DELETE requests.
I managed to setup codeception and force it to not use a proxy.
Here is the config I used: 
```yml
actor: ApiTester
modules:
    enabled:
        - \Helper\HttpCodeHelper
        - \Helper\DbHelper
        - \Helper\Building
        -  Asserts
        - Cli
        - Symfony
        - REST
        - Db
    config:
        Symfony:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'
        REST:
            url: 'http://%API_HOST_AND_PORT%/'
            depends: PhpBrowser
            part: Json
        PhpBrowser:
            url: 'http://%API_HOST_AND_PORT%/'
            proxy: ''
            headers:
                header: {value}
                Content-Type: application/json
        Db:
            dsn: 'mysql:host=%BDD_MYSQL_HOST%;dbname=%BDD_MYSQL_DATABASE%'
            user: '%BDD_MYSQL_USER%'
            password: '%BDD_MYSQL_PASSWORD%'
```
Note the `proxy: ''` line under the `PhpBrowser` configuration.
I was surprised this proxy configuration was not documentated on your website. 
Maybe it could be added.
