### ISSUE TITLE
Doctrine2 haveInRepository and Entities with constructors

### ISSUE THREAD

**Issue by krukru** [Codeception/Codeception#5420]
#### What are you trying to achieve?
I am trying to inject Entities into the repository. The entities have a constructor which accepts a single argument (but the issue can be reproduces with any number of arguments greater than or equal to 1).

#### What do you get instead?
I get the following error

```bash
 [ArgumentCountError] Too few arguments to function App\Entity\Foo::__construct(), 0 passed and exactly 1 expected 
```
> Provide test source code if related

```php
// FooTest.php

$I->haveInRepository(Foo::class, [
    'bar' => 'baz',
]);
```
```php
// src/Entity/Foo.php

namespace App\Entity;

class Foo
{
    private $bar;
 
    public function __construct(string $bar)
    {
        $this->bar = $bar;
    }

}

```
### Details

* Codeception version: 2.5.4
* PHP Version: 7.2.12
* Operating System: macOS Mojave 10.14.3
* Installation type: Composer
* Suite configuration:

```yml
// functional.suite.yml

actor: FunctionalTester
modules:
    enabled:
        - Asserts
        - REST
        - Doctrine2
        - \App\Tests\Helper\Functional
    config:
        Symfony:
            app_path: 'src'
            environment: 'test'
        REST:
            depends: Symfony
            url: '/v1'
        Doctrine2:
            depends: Symfony
```

Looking at the code it would seem that this line causes the exception https://github.com/Codeception/Codeception/blob/2.5/src/Codeception/Module/Doctrine2.php#L369

There are two solutions that I can think of. The first one would be to provide an optional third parameter to all doctrine2 module methods, which would be the optional constructor arguments that get passed into `newInstance()`, or even better `newInstanceArgs()` since this method wrapps a variable number of arguments into a single array.
The second solution is to use `newInstanceWithoutConstructor()`, which is what I think consumers really want in most cases, since they are setting the object properties directly via reflection. This approach has concerns regarding backward compatibility with existing tests though.
