### ISSUE TITLE
Invalid argument 'path' when using webdriver with coverage

### ISSUE THREAD

**Issue by jeckel** [Codeception/Codeception#5437]
#### What are you trying to achieve?

I have a simple (for now) project where I want to implement BDD tests with coverage.
Everything works fine with PHPBrowser.

But the project will become more complex, so I want to switch to WebDriver with Selenium Chrome.

BDD tests are working fine with WebDriver, but when I wen to enable coverage, there is an error (I think related to some coockies)

#### What do you get instead?
Test: 
```
Feature: Homepage
  Check home page rendering

  Scenario: try homepage
    Given I am on "/"
    Then I should see "Hello World"

  Scenario: try homepage bob
    Given I am on "/?name=bob"
    Then I should see "Hello bob"
```

`AcceptanceTester.php`:
```php
class AcceptanceTester extends \Codeception\Actor
{
    use _generated\AcceptanceTesterActions;

   /**
    * Define custom actions here
    */

    /**
     * @Given I am on :arg1
     */
    public function iAmOn($arg1)
    {
        $this->amOnPage($arg1);
    }

    /**
     * @Then I should see :arg1
     */
    public function iShouldSee($arg1)
    {
        $this->see($arg1);
    }
}
```

Codeception.yml:
```
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed

coverage:
    enabled: true
    include:
        - public/*.php

modules:
    config:
        WebDriver:
            url: 'http://web/'
            host: 'selenium'
            port: 4444
            browser: chrome
```


Output :
```
---------
1) Homepage: try homepage
 Test  tests/acceptance/homepage.feature:try homepage
                                                                                                                                                                                                                                                                      
  [Facebook\WebDriver\Exception\UnrecognizedExceptionException] invalid argument: invalid 'path'
  (Session info: chrome=73.0.3683.75)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.15.0-46-generic x86_64)  
                                                                                                                                                                                                                                                                      
#1  /var/www/project/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:158
#2  /var/www/project/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:326
#3  /var/www/project/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:547
#4  /var/www/project/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
#5  /var/www/project/vendor/facebook/webdriver/lib/WebDriverOptions.php:55
#6  /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:212
#7  /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:44
#8  /repo/autoload.php:12
#9  /repo/codecept:7
```

I updated everything to latest version.

All the source code is available here : https://github.com/jeckel/circleci-sandbox
