### ISSUE TITLE
Facebook Module - Site login

### ISSUE THREAD

**Issue by sp0tteh** [Codeception/Codeception#547]
Error

```
Guzzle\Http\Exception\CurlException: [curl] 35: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol [url] https://www.facebook.com:80
```

Cest Test

```
$I->wantToTest('log in to site using Facebook');
$I->haveFacebookTestUserAccount(); // create facebook test user
$I->haveTestUserLoggedInOnFacebook(); // so that facebook will not ask us for login and password
$fbUserFirstName = $I->grabFacebookTestUserFirstName();
$I->amOnPage('/login2');
$I->see('Login');
$I->click('.facebook_connect');
$I->see('Welcome');
```

config

```
class_name: TestGuy
modules:
    enabled: [Filesystem, TestHelper, PhpBrowser, Facebook]
    config:
        PhpBrowser:
            url: 'http://localhost:8000'
        Facebook:
            app_id: 'id'
            secret: 'secret'
            test_user:
                name: FacebookGuy
                permissions: [email]
```

If i change to port 443 then i get the following

```
 $phpBrowser->_sendRequest('https://www.facebook.com:433');
```

```
Guzzle\Http\Exception\CurlException: [curl] 35: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol [url] https://www.facebook.com:80/platform/test_account_login.php?user_id=100006695524397&n=SxQI0OfIwVkU3mb
```

Seems port 80 is being added even if the request is https
