### ISSUE TITLE
REST module 'execute()' prefixes slash to url which already have leading slash

### ISSUE THREAD

**Issue by nicholascus** [Codeception/Codeception#5473]
#### What are you trying to achieve?
Consistency in URL construction when both PhpBrowser and REST module are used.

#### What do you get instead?

Requests sent with REST module get leading slash doubled. So server get log full of
192.168.176.9 - - [17/Apr/2019:01:05:58 +1000] "POST //

```yml
actor: FunctionalTester
modules:
    enabled:
        - REST:
            url: 'http://%HOST%:%PORT%/'
            depends: PhpBrowser
        - \Helper\Functional
        - PhpBrowser:
            url: 'http://%HOST%:%PORT%/'
        - Asserts
```
