### ISSUE TITLE
Laravel, Doctrine and CodeCeption in bitbucket pipelines?

### ISSUE THREAD

**Issue by kvanleeuwen** [Codeception/Codeception#5476]
Hello,

I am trying to set-up codeception with laravel and as ORM: Doctrine (from Symphony). I I have created a pipeline in bitbucket. Now my unit.suite.yml contains the following configuration:
```yaml
actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - Laravel5:
            environment_file: .env.testing
            cleanup: true
```

Default = because this is the the default config setting in de config/database.php 

this error occurs if I run my bitbucket-pipelines.yml (and it calls codeception to run the unit tests):

Doctrine2 module is not configured!                           
                                                                
  EntityManager can't be obtained.                              
                                                                
  Please specify either `connection_callback` config option     
  with callable which will return instance of EntityManager or  
  pass a dependent module which are Symfony or ZF2              
  to connect to Doctrine using Dependency Injection Container   

Does anyone have an idea why this occurs?

Thanks in advance!

Kevin
