### ISSUE TITLE
Selenium2::executeInSelenium() not working!

### ISSUE THREAD

**Issue by rooseveltrp** [Codeception/Codeception#548]
Hi,

I am getting started with Codeception and so far very impressed with the overall setup and the flexibility of this awesome testing framework.

I am using Selenium2 module and so far it is working great. The problem started when I tried to maximize the window by using the executeInSelenium() method.

The error I am receiving is:

> RuntimeException: Call to undefined method WebGuy::executeInSelenium
##### acceptance.suite.yml

``` yml
class_name: WebGuy
modules:
   enabled: [Selenium2]
   config:
      Selenium2:
         url: 'http://localhost/myapp'
         browser: firefox
         capabilities:
             unexpectedAlertBehaviour: 'accept'
```
##### MyCept.php

``` php
<?php
$i = new WebGuy($scenario);

$i->wantTo('see if I can install my app by running the installer');

$i->executeInSelenium(function(\WebDriver\Session $webdriver) {
  $webdriver->maximizeWindow();
});
```

I downloaded the codecept.phar file from the http://codeception.com/thanks page.

Any ideas why I am getting this error?
