### ISSUE TITLE
Inconsistency between html and xml reports

### ISSUE THREAD

**Issue by thureos** [Codeception/Codeception#5481]
#### What are you trying to achieve?
I want both html and xml reports to be consistent
#### What do you get instead?
HTML report outputs the right information meanwhile the XML report does not mark the failed step as failed (Check last step on images below)
> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
    public function iShouldSeeSubscribedToBrandCodeViaApi($emailAddress, $brandCode)
    {
        $consumerGuid = $this->grabFromDatabase("<TABLE>", "<COLUMN>", ['emailAddress' => $emailAddress]);
        $url = "https://<API-URL>";
        $response = \Httpful\Request::get($url)->send();
        $expected = ['subscribed' => true];
        $this->helperAssertEquals($expected, (array)$response->body);
    }
```
### Details

![screenshot 369](https://user-images.githubusercontent.com/5049215/56610400-57662300-65dd-11e9-9ed4-96befbbf6588.jpg)
![screenshot 370](https://user-images.githubusercontent.com/5049215/56610405-59c87d00-65dd-11e9-99a5-7c4f251e8314.jpg)

* Codeception version:
* PHP Version: 7.2.17
* Operating System: Docker 
* Installation type: Composer
* List of installed packages (`composer show`)
`
behat/gherkin                        v4.6.0 
codeception/codeception              2.5.5  
codeception/phpunit-wrapper          7.7.1  
codeception/stub                     2.1.0  
codeception/visualception            1.0.2  
doctrine/instantiator                1.2.0  
facebook/webdriver                   1.6.0  
guzzlehttp/guzzle                    6.3.3  
guzzlehttp/promises                  v1.3.1 
guzzlehttp/psr7                      1.5.2  
incenteev/composer-parameter-handler v2.1.3 
myclabs/deep-copy                    1.9.0  
nategood/httpful                     0.2.20 
phar-io/manifest                     1.0.3  
phar-io/version                      2.0.1  
phpdocumentor/reflection-common      1.0.1  
phpdocumentor/reflection-docblock    4.3.0  
phpdocumentor/type-resolver          0.4.0
phpspec/prophecy                     1.8.0  
phpunit/php-code-coverage            6.1.4  
phpunit/php-file-iterator            2.0.2  
phpunit/php-text-template            1.2.1  
phpunit/php-timer                    2.1.1  
phpunit/php-token-stream             3.0.1  
phpunit/phpunit                      7.5.8  
pimple/pimple                        v3.2.3 
psr/container                        1.0.0  
psr/http-message                     1.0.1  
psr/log                              1.1.0  
ralouphie/getallheaders              2.0.5  
sebastian/code-unit-reverse-lookup   1.0.1  
sebastian/comparator                 3.0.2  
sebastian/diff                       3.0.2  
sebastian/environment                4.1.0  
sebastian/exporter                   3.1.0  
sebastian/global-state               2.0.0  
sebastian/object-enumerator          3.0.3  
sebastian/object-reflector           1.1.1  
sebastian/recursion-context          3.0.0  
sebastian/resource-operations        2.0.1  
sebastian/version                    2.0.1  
silex/silex                          v2.3.0 
symfony/browser-kit                  v4.2.5 
symfony/console                      v4.2.5 
symfony/contracts                    v1.0.2 
symfony/css-selector                 v4.2.5 
symfony/debug                        v4.2.5 
symfony/dom-crawler                  v4.2.5 
symfony/event-dispatcher             v4.2.5 
symfony/filesystem                   v4.2.5 
symfony/finder                       v4.2.5 
symfony/http-foundation              v4.2.5 
symfony/http-kernel                  v4.2.5 
symfony/polyfill-ctype               v1.11.0
symfony/polyfill-mbstring            v1.11.0
symfony/process                      v4.2.5 
symfony/routing                      v4.2.5 
symfony/yaml                         v4.2.5 
theseer/tokenizer                    1.1.2  
webmozart/assert                     1.4.0
`
* Suite configuration:

```yml

actor: AcceptanceTester

modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver:
            host: <IP>
            url: 'about:blank'
            browser: chrome
            pageload_timeout: 30
        - VisualCeption:
            maximumDeviation: 0
            saveCurrentImageIfFailure: true
            referenceImageDir: 'VisualCeption/'
            currentImageDir: 'debug/visual/'
            report: true
        - Db:
            dsn: '<DSN>'
            user: '<USER>'
            password: '<PASSWORD>'

env:
    chrome:
        modules:
          config:
            WebDriver:
              host: <IP>
              browser: 'chrome'
              pageload_timeout: 30
              url: 'about:blank'
              capabilities:
                seleniumProtocol: 'WebDriver'
                chromeOptions:
                  useAutomationExtension: false
                  args: [ "--disable-infobars", "--disable-gpu", "--dns-prefetch-disable", "--ignore-certificate-errors", "--disable-browser-side-navigation", "--start-maximized", "--headless", "--user-agent='Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'"]
```
