### ISSUE TITLE
duplicate declaration of canSeeCookie()

### ISSUE THREAD

**Issue by Tscheffrey** [Codeception/Codeception#5500]
#### What are you trying to achieve?

I am trying to execute codeception with two comma-separated parameters:

```sh
./codecept.phar run -c ../.. --env fast,prod
```

#### What do you get instead?

The method `canSeeCookie()` appears to be generated twice in `_support/_generated/AcceptanceTesterActions.php`.

```sh
PHP Fatal error:  Cannot redeclare Company\Test\Site\_generated\AcceptanceTesterActions::canSeeCookie() in /Users/username/Sites/example.localhost/tests/_support/_generated/AcceptanceTesterActions.php on line 180
```
Everything works just fine if if execute it with only one --env parameter

### Details

* Codeception version: 3.0.0
* PHP Version: 7.0.33
* Operating System: macOS
* Installation type: Phar
* Suite configuration: 

`acceptance.suite.yml`:

```yml
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - Asserts
```

`codeception.yml`:

```yml
namespace: Company\Test\Site
actor: Tester
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    shuffle: true
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        WebDriver:
            url: 'http://example.localhost'
            browser: chrome
env:
    local:
    stage:
        modules:
            config:
                WebDriver:
                    url: 'http://prev.example.de'
                    browser: chrome
    prod:
        modules:
            config:
                WebDriver:
                    url: 'http://example.com'
                    browser: chrome
    fast:
```
