### ISSUE TITLE
DataFactory Module setLocale Not Working

### ISSUE THREAD

**Issue by dimacros** [Codeception/Codeception#5501]
#### Config Extended DataFactory.php
> The setLocale configuration is specified in the package: https://github.com/thephpleague/factory-muffin

```php

namespace Helper;

use Codeception\Module\DataFactory as BaseDataFactory;
use League\FactoryMuffin\Faker\Facade as Faker;

class DataFactory extends BaseDataFactory
{
    public function _beforeSuite($settings = [])
    {
        parent::_beforeSuite($settings);
       
        Faker::setLocale('es_PE'); //Not Working
    }
}

```
### Details

* Codeception version: 3.0
* PHP Version: 7.2.17
* Operating System: Linux
* Installation type:  Composer
* Suite **api.suite.yml** configuration:

```yml
class_name: ApiTester
modules:
    enabled:
        - Symfony:
            app_path: 'app'
            var_path: 'var'
            environment: 'test'
        - REST:
            url: /api
            depends: Symfony
        - Doctrine2:
            cleanup: true
            depends: Symfony
        - Helper\DataFactory:
            cleanup: true
            depends: Doctrine2
            factories: tests/_support/factories
        - \Helper\Api
```
