### ISSUE TITLE
Test automatic fill of "select" fields with ajax, Codeception

### ISSUE THREAD

**Issue by allanquartermaine** [Codeception/Codeception#5512]
### What steps will reproduce the problem?
I'm trying to run a Web Service test with codeception to a form. This form has fields to fill or select. The content of some `select` fields depends of previous `select` fields (for instance, when I select the intended country in `select country` field, the `select currency` field is populated withe the corresponding currency of the country.  I'm stuck in testing this behavior. 

```
        $I->amOnPage('/sign_up.php');
        $I->fillField('#firstName', 'Carlos');
        $I->fillField('#lastName', 'Alarcón');
        $I->fillField('#Born','1980-05-17');
        $I->selectOption('#country','Chile');
        $I->haveHttpHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF- 
        8');
        $I->sendPOST('http://localhost/8tours/model/currency_model.php', 'country_id=1');
        $I->canSeeResponseCodeIs(200);
        $I->seeResponseContains('[{"currency_id":"24","country_id":"1","currency_name":"Chilean 
        peso"}]');
        $I->seeInField('#currency', 'Chilean peso'); //this field throws me an error
```

### What's expected?
I expect the tester is able to detect the json data that is now available in the `currency` field for selecting (and various other fields that are filled after the user pick a country in `select country`

> Provide console output if related. Use `-vvv` mode for more details.

```bash

Api Tests (1) -----------------------------------------------------------------------------------------------------------------------x SignUpCest: Sign up (0.32s)
-------------------------------------------------------------------------------------------------------------------------------------

Time: 716 ms, Memory: 10.00 MB

There was 1 failure:

---------
1) SignUpCest: Sign up
 Test  tests\api\SignUpCest.php:signUp
 Step  See in field "#currency","Chilean peso"
 Fail  Failed asserting that `Chilean peso` is in select's value: array (
  0 => '',
)
Failed asserting that an array contains 'Chilean peso'.

Scenario Steps:

 11. $I->seeInField("#currency","Chilean peso") at tests\api\SignUpCest.php:26
 10. $I->seeResponseContains("[{"currency_id":"24","country_id":"1","currency_name":"Chilean peso"}]") at tests\api\SignUpCest.php:25 
 9. $I->canSeeResponseCodeIs(200) at tests\api\SignUpCest.php:24
 8. $I->sendPOST("http://localhost/8proy/model/currency_model.php","country_id=1") at tests\api\SignUpCest.php:23
 7. $I->haveHttpHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8") at tests\api\SignUpCest.php:22
 6. $I->selectOption("#country","Chile") at tests\api\SignUpCest.php:21

Artifacts:

Body: [{"currency_id":"24","country_id":"1","currency_name":"Chilean peso"}]
Response: C:\xampp\htdocs\8proy\tests/_output\SignUpCest.signUp.fail.html

FAILURES!
Tests: 1, Assertions: 3, Failures: 1.
PS C:\xampp\htdocs\8proy>
```
> Provide test source code if related

```php
```
### Details

* Codeception version: 3.0
* PHP Version: 7
* Operating System: Windows 10
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - REST:
            url: http://localhost/8proy
            depends: PhpBrowser
        - \Helper\Api
        - PhpBrowser:
            url: http://localhost/8proy
        - \Helper\Acceptance
        - Db:
             dsn: 'mysql:host=localhost;dbname=tour;port=3306'
             user: 'allan'
             password: 'Allan2222'
```
