### ISSUE TITLE
Download a file in headless mode

### ISSUE THREAD

**Issue by kingpinzs** [Codeception/Codeception#5518]
#### What are you trying to achieve?
Download a file in headless mode
#### What do you get instead?
Does not download the file and does not throw an error
> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php

```
### Details

* Codeception version: 3.0.1
* PHP Version: PHP 7.3.2
* Operating System: mac os Mojave 10.14.4
* Installation type:  Composer
* List of installed packages (`composer show`)
behat/gherkin                      v4.6.0     Gherkin DSL parser for PHP 5.3
codeception/codeception            3.0.1      BDD-style testing framework
codeception/phpunit-wrapper        8.0.4      PHPUnit classes used by Codeception
codeception/stub                   2.1.0      Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.2.0      A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.6.0      A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.3      Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1     Guzzle promises library
guzzlehttp/psr7                    1.5.2      PSR-7 message implementation that also provides common utility methods
hoa/consistency                    1.17.05.02 The Hoa\Consistency library.
hoa/console                        3.17.05.02 The Hoa\Console library.
hoa/event                          1.17.01.13 The Hoa\Event library.
hoa/exception                      1.17.01.16 The Hoa\Exception library.
hoa/file                           1.17.07.11 The Hoa\File library.
hoa/iterator                       2.17.01.10 The Hoa\Iterator library.
hoa/protocol                       1.17.01.14 The Hoa\Protocol library.
hoa/stream                         1.17.02.21 The Hoa\Stream library.
hoa/ustring                        4.17.01.16 The Hoa\Ustring library.
myclabs/deep-copy                  1.9.1      Create deep copies (clones) of your objects
phar-io/manifest                   1.0.3      Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1      Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1      Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.1      With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.4.0     
phpspec/prophecy                   1.8.0      Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          7.0.3      Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          2.0.2      FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1      Simple template engine.
phpunit/php-timer                  2.1.1      Utility class for timing
phpunit/php-token-stream           3.0.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    8.1.5      The PHP Unit Testing framework.
psr/http-message                   1.0.1      Common interface for HTTP messages
ralouphie/getallheaders            2.0.5      A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup 1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.2      Diff implementation
sebastian/environment              4.2.2      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0      Provides the functionality to export PHP variables for visualization
sebastian/global-state             3.0.0      Snapshotting of global state
sebastian/object-enumerator        3.0.3      Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1      Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.1      Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1      Library that helps with managing the version number of Git-hosted PHP projects
symfony/browser-kit                v4.2.8     Symfony BrowserKit Component
symfony/console                    v4.2.8     Symfony Console Component
symfony/contracts                  v1.1.0     A set of abstractions extracted out of the Symfony components
symfony/css-selector               v4.2.8     Symfony CssSelector Component
symfony/dom-crawler                v4.2.8     Symfony DomCrawler Component
symfony/event-dispatcher           v4.2.8     Symfony EventDispatcher Component
symfony/finder                     v4.2.8     Symfony Finder Component
symfony/polyfill-ctype             v1.11.0    Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.11.0    Symfony polyfill for the Mbstring extension
symfony/process                    v4.2.8     Symfony Process Component
symfony/yaml                       v4.2.8     Symfony Yaml Component
theseer/tokenizer                  1.1.2      A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.4.0      Assertions to validate method input/output with nice error messages.
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        #- PhpBrowser:
        - WebDriver:  
            url:*
            port: 9515
            browser: chrome
            restart: false
            clear_cookies: true
      capabilities:
                 "goog:chromeOptions": # additional chrome options
                      args: ["headless", "disable-web-security"]
                      prefs: 
                            download.default_directory: '/Users/*/codecept_test'
                            download.prompt_for_download: false
                            download.directory_upgrade: true
                            safebrowsing.enabled: false
                            safebrowsing.disable_download_protection: true
                            Page.setDownloadBehavior: {behavior: 'allow', downloadPath: '/Users/*/codecept_test'}
        - \Helper\Acceptance
    step_decorators:
        - Codeception/Step/TryTocodecept_test
        - Codeception/Step/Retry
        - Codeception/Step/ConditionalAssertion
```
