### ISSUE TITLE
How to change _generated folder name?

### ISSUE THREAD

**Issue by KartaviK** [Codeception/Codeception#5519]
#### What are you trying to achieve?

Change default name of `_generated` folder

#### What do you get instead?

I really hate underscore in folders' names and i can't find in docs support for it.

### Details

* Codeception version:
* PHP Version: 7.2
* Operating System: XUbuntu
* Installation type: Composer
* Suite configuration:

```yml
actor: Tester
paths:
  tests: tests
  log: tests/Output
  data: tests/Data
  support: tests/Support
  envs: tests/Envs
namespace: Wearesho\Tests
settings:
  bootstrap: bootstrap.php
  colors: true
  memory_limit: 1024M
extensions:
  enabled:
    - Codeception\Extension\RunFailed
coverage:
  enabled: true

```
