### ISSUE TITLE
PhpBrowser faulty host header handling

### ISSUE THREAD

**Issue by emulgeator** [Codeception/Codeception#5537]
#### What are you trying to achieve?
In my suite configuration I have the following relevant parts:
```yml
    config:
        PhpBrowser:
            url: http://nginx
            headers:
                Host: api.project.docker
```
I'd expect that a request should be made to **http://nginx** with sending a HTTP_HOST header with the value **api.project.docker**

#### What do you get instead?
Since I upgraded from **codeception 2.5.6** (what depended on **symfony/browser-kit 3.3.6**) to **3.0.1** (what depends on **symfony/browser-kit 4.3.0**)  what happens is that the called host is replaced by the set HOST header value.
So **http://api.project.docker** will ba called

This happens in `\Symfony\Component\BrowserKit\Client::request()` for whatever reason. 
Still I think this probably should be handled in Codeception.
I've found[ this ](https://github.com/symfony/symfony/issues/11775#issuecomment-54351701) what could be relevant here.

### Details
* Codeception version: 3.0.1
* PHP Version: 7.2.16
* Operating System: Ubuntu Linux
* Installation type: Composer
