### ISSUE TITLE
404 Issues with Apache Virtual Hosts

### ISSUE THREAD

**Issue by vlucas** [Codeception/Codeception#554]
There seems to be a problem with requests from `PhpBrowser` to virtual hosts with domain names. I have a project setup locally using [Bullet](http://bulletphp.com) on a domain something like `http://myapp.dev`, and every request ends up with a 404 error and the default Apache 404 page displaying. I am not quite sure why this is, but the problem can be (kind of) solved by adding a port to the URL:

```
class_name: ApiGuy
modules:
    enabled: [ApiHelper, REST, PhpBrowser]
    config:
      PhpBrowser:
        url: http://myapp.dev:80/
      REST:
        url: http://myapp.dev:80/
```

The only issue is that then any redirects or subsequent links generated from the app won't have the port number, so subsequent requests will still fail unless changes are made everywhere in the app or in the framework URL generator/helper itself.

This article highlights the issue (Laravel specific solution, but still happens with my non-Laravel sites):
http://thomasgr.im/shares/2013/quick-fix-to-codeception-phpbrowser-throwing-404-errors-testing-laravel-app-on-virtual-host/

I am not even sure how to debug this, because I don't know why this wouldn't be working in the first place.
