### ISSUE TITLE
Cannot select option with PhpBrowser

### ISSUE THREAD

**Issue by cosinus90** [Codeception/Codeception#5547]
#### What are you trying to achieve?
I'd like to select an option of the following html code

```
 <select id="_payment_type" name="payment_type" required="" class="form-control">
 	<option>За показы</option>
 	<option>За размещение</option>
	<option>qwerty</option>
 </select>
```

#### What do you get instead?
 [InvalidArgumentException] Input "payment_type" cannot take "" as a value (possible values: За показы, За размещение, qwerty).

> Provide console output if related. Use `-vvv` mode for more details.

```bash


```
> Provide test source code if related

```php
			$I->selectOption('#_payment_type', 'qwerty');
```
### Details

* Codeception version: 3.0.1
* PHP Version: 7.2
* Operating System: CentOS 6
* Installation type: Phar
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://maza.biz/insta
        - \Helper\Acceptance
        - Db:
            dsn: 'mysql:host=localhost;dbname=insta_test'
            user: 'baza'
            password: '9x'
            dump: 'tests/_data/database.sql'
            populate: false  # run populator before all tests
            cleanup: false # run populator before each test
            reconnect: true
            waitlock: 10
    step_decorators:
        - \Codeception\Step\ConditionalAssertion    
```
