### ISSUE TITLE
Module WebDriver not be found

### ISSUE THREAD

**Issue by nemozar** [Codeception/Codeception#5572]
* Codeception version: 3.0.2
* PHP Version: PHP 7.3.3
* Operating System: ubuntu
* Installation type: Composer
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://73.mfc/
        - \Helper\Acceptance
        - WebDriver
            url: http://73.mfc/
            browser: firefox
    step_decorators: ~        
```

when i exec `vendor/bin/codecept build` or `./vendor/bin/codecept init acceptance` have error:
Module WebDriver url: http://73.mfc/ browser: firefox could not be found an  
  d loaded

Selenium standalone: selenium-server-andalone-3.141.59.jar
