### ISSUE TITLE
BrowserKit\Client::$maxRedirects does not exist 

### ISSUE THREAD

**Issue by kapcus** [Codeception/Codeception#5576]
I would like to start with API tests for Symfony application but still getting following - Thx for any help

```bash
1) LoginCest: Login as admin
 Test  tests/api/LoginCest.php:loginAsAdmin
                                                                                                    
  [ReflectionException] Property Symfony\Component\BrowserKit\Client::$maxRedirects does not exist 
```
```php
//tests/api/LoginCest.php
<?php

class LoginCest
{
	public function _before(ApiTester $I)
	{
	}

	public function loginAsAdmin(\ApiTester $I)
	{
		$I->sendPOST('api/login-check', ['name' => 'admin', 'password' => 'xxxx']);
	}
}
```
```php
//tests/_bootstrap.php
<?php
putenv('SYMFONY_DEPRECATIONS_HELPER=weak');

define('PROJECT_ROOT', realpath(__DIR__ . '/..'));
require_once PROJECT_ROOT . '/vendor/autoload.php';
```
* Codeception version: 3.0.x-dev
* PHP Version: 7.2.10
* Operating System: RHEL 7
* Installation type: Composer

```yml
#tests/api.suite.yml
actor: ApiTester
modules:
    enabled:
        - Symfony:
              app_path: 'src'
              environment: 'test'
        - REST:
              url: /v1
              depends: Symfony
              part: Json
        - Doctrine2:
              depends: Symfony
              cleanup: true
        - \Helper\Api
```

```yml
#codeception.yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    bootstrap: ../_bootstrap.php

params:
    - .env
```
```json
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-sockets": "*",
        "api-platform/api-pack": "^1.2",
        "lexik/jwt-authentication-bundle": "^2.6",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/console": "4.3.*@dev",
        "symfony/dotenv": "4.3.*@dev",
        "symfony/flex": "^1.1",
        "symfony/framework-bundle": "4.3.*@dev",
        "symfony/messenger": "4.3.*@dev",
        "symfony/templating": "4.3.*@dev",
        "symfony/twig-bundle": "4.3.*@dev",
        "symfony/yaml": "4.3.*@dev",
        "webonyx/graphql-php": "^0.13.0"
    },
    "require-dev": {
        "codeception/codeception": "3.0.x-dev",
        "dg/bypass-finals": "1.1.*",
        "doctrine/doctrine-fixtures-bundle": "^3.1",
        "phpstan/phpstan": "^0.11.4",
        "phpstan/phpstan-doctrine": "^0.11.2",
        "phpstan/phpstan-phpunit": "^0.11.0",
        "symfony/browser-kit": "4.3.*@dev",
        "symfony/test-pack": "^1.0",
        "symfony/var-dumper": "4.3.*@dev",
        "symfony/web-server-bundle": "4.3.*@dev",
        "symplify/easy-coding-standard": "^5.4"
    }
```
