### ISSUE TITLE
[ExternalUrlException] Codeception\Module\Symfony can't open external URL

### ISSUE THREAD

**Issue by kapcus** [Codeception/Codeception#5577]
I try to test API of my application which contains following microservices, 

**auth** at http://auth:8080
**backend** at http://backend:8080

Therefore I need to be able to call different hostnames. 

I am getting following error message

`[ExternalUrlException] Codeception\Module\Symfony can't open external URL: http://auth:8080/api/login-check`

Is there any way how to call different microservices with Codeception and these modules? If not, is there any other option?

Thx
jan

```php
<?php

class LoginCest
{
	public function _before(ApiTester $I)
	{
	}

	public function loginAsAdmin(\ApiTester $I)
	{
		$I->sendPOST('api/login-check', ['name' => 'admin', 'password' => 'xxxx']);
		$I->seeResponseCodeIs(200);
	}
}
```

* Codeception version: 3.0.x-dev
* PHP Version: 7.2.10
* Operating System: RHEL 7
* Installation type: Composer

```yml
actor: ApiTester
modules:
    enabled:
        - Symfony:
              app_path: 'src'
              environment: 'test'
        - REST:
              url: 'http://auth:8080/'
              depends: Symfony
        - Doctrine2:
              depends: Symfony
              cleanup: true
        - \Helper\Api
```

```json
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-sockets": "*",
        "api-platform/api-pack": "^1.2",
        "lexik/jwt-authentication-bundle": "^2.6",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/console": "4.3.*@dev",
        "symfony/dotenv": "4.3.*@dev",
        "symfony/flex": "^1.1",
        "symfony/framework-bundle": "4.3.*@dev",
        "symfony/messenger": "4.3.*@dev",
        "symfony/templating": "4.3.*@dev",
        "symfony/twig-bundle": "4.3.*@dev",
        "symfony/yaml": "4.3.*@dev",
        "webonyx/graphql-php": "^0.13.0"
    },
    "require-dev": {
        "codeception/codeception": "3.0.x-dev",
        "dg/bypass-finals": "1.1.*",
        "doctrine/doctrine-fixtures-bundle": "^3.1",
        "phpstan/phpstan": "^0.11.4",
        "phpstan/phpstan-doctrine": "^0.11.2",
        "phpstan/phpstan-phpunit": "^0.11.0",
        "symfony/browser-kit": "4.3.*@dev",
        "symfony/test-pack": "^1.0",
        "symfony/var-dumper": "4.3.*@dev",
        "symfony/web-server-bundle": "4.3.*@dev",
        "symplify/easy-coding-standard": "^5.4"
    }

**Comment by Naktibalda** [comment]
Either setup domain based routes in your app or use PhpBrowser module for testing over HTTP.

**Comment by kapcus** [comment]
I have used PhpBrowser and it works. Thx

Now I can use following this in Cest
```php
$_ENV['AUTH_URL']
$_ENV['BACKEND_URL']
```

while having following config

```php
<?php
//tests/codeception/_bootstrap.php
putenv('SYMFONY_DEPRECATIONS_HELPER=weak');

define('PROJECT_ROOT', realpath(__DIR__ . '/../..'));
require_once PROJECT_ROOT . '/vendor/autoload.php';

\Codeception\Util\Autoload::addNamespace('MyApp\Tests\Api', PROJECT_ROOT . '/tests/codeception/api');
```
```yml
#.env
BACKEND_URL=http://backend:8080
AUTH_URL=http://auth:8080
```

```yml
#tests/codeception/api.suite.yml
actor: ApiTester
modules:
    enabled:
        - Symfony:
              app_path: 'src'
              environment: 'dev'
        - Asserts
        - REST:
              depends: PhpBrowser
        - Doctrine2:
              depends: Symfony
              cleanup: true
        - \Helper\Api
```

```yml
paths:
    tests: tests/codeception
    output: tests/codeception/_output
    data: tests/codeception/_data
    support: tests/codeception/_support
    envs: tests/codeception/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    bootstrap: ../_bootstrap.php

params:
    - .env
```

**Comment by Naktibalda** [comment]
You are going to test BACKEND_URL, right?
Then set it in configuration of REST module:

```yml
        - REST:
              depends: PhpBrowser
              url: '%BACKEND_URL%'
```

There should only be a few different request to auth service, so create helper methods for them and use full URL in requests.

Probably you want to remove Symfony module from this suite completely.
