### ISSUE TITLE
[REST] Async concurrent requests?

### ISSUE THREAD

**Issue by krukru** [Codeception/Codeception#5591]
#### What are you trying to achieve?
I am trying to test concurrent REST requests.

#### What do you get instead?
I cannot make two concurrent REST requests since the first one is blocking until it gets the response from the server

> Provide test source code if related

```php
    public function tryToTestConncurency(FunctionalTester $I)
    {
        $I->sendPOST('/produce');
        $I->sendPOST('/consume');
        $I->sendPOST('/consume');
        
        // Assert that only one resource was consumed
    }
```
### Details

* Codeception version: 3.0.2
* PHP Version: 7.3.3
* Operating System: mac
* Installation type: composer
* Suite configuration:

```yml
actor: FunctionalTester
modules:
    enabled:
        - Symfony:
            part: Services
        - Asserts
        - REST
        - Doctrine2
    config:
        Symfony:
            app_path: 'src'
            environment: 'test'
        REST:
            depends: Symfony
            url: '/api'
        Doctrine2:
            depends: Symfony
```
