### ISSUE TITLE
Return type hint of generated function needs fully qualified class name to work properly

### ISSUE THREAD

**Issue by Luc45** [Codeception/Codeception#5592]
#### What are you trying to achieve?
I'm trying to make my module's return type-hint to be recognized in Cest.

#### What do you get instead?
`$I->build_document()` is not aware of what it is returning, thus I do not get features such as autocomplete.

\Helper\Builders
```php
use Project\Tests\Support\Builders\DocumentBuilder;

/**
 * @return DocumentBuilder
 */
public function build_document(): DocumentBuilder {
	return DocumentBuilder::build(); // simplified for example purposes
}
```

This is the generated function for it:

```php
/**
 * [!] Method is generated. Documentation taken from corresponding module.
 *
 * @return DocumentBuilder
 *
 * @see \Helper\Builders::build_document()
 */
public function build_document() {
    return $this->getScenario()->runStep(new \Codeception\Step\Action('build_document', func_get_args()));
}
```

If I change the `@return` to a fully-qualified class name at `\Helper\Builders`, the type-hint works correctly:

```php
/**
 * @return \Project\Tests\Support\Builders\DocumentBuilder
 */
public function build_document(): DocumentBuilder {
	return DocumentBuilder::build(); // simplified for example purposes
}
```

Generated function, then:

```php
/**
 * [!] Method is generated. Documentation taken from corresponding module.
 *
 * @return \Tribe\Tests\Support\Builders\DocumentBuilder
 *
 * @see \Helper\Builders::build_document()
 */
public function build_document() {
    return $this->getScenario()->runStep(new \Codeception\Step\Action('build_document', func_get_args()));
}
```

With this change, `$I->build_document()` autocompletes correctly in Cests.

Just a heads up for folks that might be facing this issue. It might be useful to add that information to the **Reusing Test Code** documentation or generate the functions using fully qualified class names.

https://codeception.com/docs/06-ReusingTestCode

### Details

* Codeception version: 3.0.1
* PHP Version: 7.0.33
* Operating System: Ubuntu
* Installation type: Composer

```yml
actor: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - \Helper\Builders
        - WPBrowser
        - WPDb
        - WPLoader
        - WPFilesystem
    config:
        WPLoader:
            loadOnly: true
```
