### ISSUE TITLE
Yii2 example acceptance configuration gives conflict

### ISSUE THREAD

**Issue by mikehaertl** [Codeception/Codeception#5634]
#### What are you trying to achieve?

I tried to run acceptance tests with Selenium under docker using the Yii2 module as shown in the example on [this](https://codeception.com/for/yii) page.  I've just added the `host:` setting for `WebDriver` under which my Selenium container is reachable in the docker network.

I'm also confused as why there is a `entryScript` configuration option. As I understand it I am responsible to make the application available with test configuration somewhere so that Selenium can connect to it. So what is this option used for? Documentation is very unclear IMO.

If I leave aways the Yii2 module the `AcceptanceTester` is missing methods like `seePageNotFound()`.

#### What do you get instead?

```
[Codeception\Exception\ModuleConflictException]                                                      
  WebDriver module conflicts with Yii2                                                                 
  --                                                                                                   
  This usually happens when you enable two modules with the same actions but with different backends.  
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one suite,                    
  as they implement similar methods but use different drivers to execute them.                         
  You can load a part of module (like: ORM) to avoid conflict.
```

### Details

* Codeception version: 3.0.3
* PHP Version: as in .phar file
* Operating System: Linux
* Installation type: Phar
* List of installed packages: as in .phar file
* Suite configuration:

### 
```yml
# config at tests/acceptance.yml
modules:
    enabled:
        - WebDriver:
            url: http://127.0.0.1:8080/
            browser: firefox
            # Added by me:
            host: test-selenium-chrome
        - Yii2:
            part: [orm, fixtures] # allow to use AR methods
            cleanup: false # don't wrap test in transaction
            entryScript: index-test.php
# paste suite config here
```
