### ISSUE TITLE
Webdriver Timeout Exception

### ISSUE THREAD

**Issue by M1ke** [Codeception/Codeception#5638]
#### What are you trying to achieve?

Running a test suite

#### What do you get instead?

```
[Facebook\WebDriver\Exception\TimeOutException]                                                                               
  timeout                                                                                                                       
    (Session info: chrome=64.0.3282.119)                                                                                        
    (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.4.0-157-generic x86_64)
```

> Provide test source code if related

This does not seem to be related to specific tests, just to running a lot of tests (~30mins) in one go

### Details

* Codeception version: 2.5.6
* PHP Version: 7.1
* Operating System: Linux
* Installation type: Composer
* List of installed packages (`composer show`) not relevant
* Suite configuration:

```yml
modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver
        - Db
        - Asserts
        - \Helper\Email
        - \Helper\Populate
        - \Helper\DbTest
        - \Helper\TenancyContractHelper
        - \Helper\Debug
        - \Helper\Unit
    config:
        WebDriver:
            url: 'http://test.local/'
            browser: 'chrome'
            host: 'xxxx_selenium'
            window_size: 1280x960
            capabilities:
                javascriptEnabled: true
                phantomjs.cli.args: ['--ignore-ssl-errors=true']
```

I imagine the timeout might be legitimate but it shouldn't hose the whole test suite - it should probably fail that test and then continue with tests. The issue means that one test failing this way can stop the suite running and prevent any test output from being discovered.
