### ISSUE TITLE
It's not possible to use absolute paths for paths.* keys in codeception.yaml

### ISSUE THREAD

**Issue by maks-rafalko** [Codeception/Codeception#5642]
#### What are you trying to achieve?

We need to have absolute paths in the `codecption.yml`:

```yaml
paths:
    tests: /tmp/codeception/tests
    output:  /tmp/codeception/tests/_output
    data: /tmp/codeception/tests/_data
    support: /tmp/codeception/tests/_support
    envs: /tmp/codeception/tests/_envs
actor_suffix: Tester
extensions:
    enabled: [Codeception\Extension\RunFailed]
```

#### What do you get instead?

Instead, with the config above, we an error:

```bash
In Finder.php line 601:
The "/tmp/codeception//tmp/codeception/tests" directory does not exist.
```

### Details

* Codeception version: 3.0.2
* PHP Version: 7.2
* Operating System: any
* Installation type: Composer

# Why do we need it?

[We are trying](https://github.com/infection/infection/issues/45) to integrate Codeception as a new Test Framework in [Infection](https://github.com/infection/infection) and the absence of this trivial feature blocks us.

Infection creates different config files (`codeception.yml`) for each mutant (process) and those config files are usually located in system `tmp` folders, e.g. in `/var/folders/q6/mnkj_c654qgf2028jcjc21pm0000gn/T/infection/d2f708bf86dac2885189a671c29fd74b`.

Then, we run codeception like

```bash
codecept run -c /var/folders/q6/mnkj_c654qgf2028jcjc21pm0000gn/T/infection/d2f708bf86dac2885189a671c29fd74b/codeceptionXYZ.yml
```

Please note, that both PHPUnit and PHPSpec support absolute paths in the config files.

# Any alternatives?

There is an ugly workaround with relative paths:

```yaml
paths:
    tests: ../../../../../../../tmp/codeception/tests
    ...
```

which is then converted to

```
/var/folders/q6/mnkj_c654qgf2028jcjc21pm0000gn/T/infection/d2f708bf86dac2885189a671c29fd74b/codeceptionXYZ.yml/../../../../../../tmp/codeception/tests
```

Related to https://github.com/Codeception/Codeception/issues/5611
