### ISSUE TITLE
Make it possible to set coverage report in the config file

### ISSUE THREAD

**Issue by maks-rafalko** [Codeception/Codeception#5643]
#### What are you trying to achieve?

To be able to set coverage report type in the `codeception.yml`, not in the command line.

```yaml
# codeception.yml
...

coverage:
    logging:
        - phpunit
        - clover
        - crap4j
        - html
```

where `logging` is just an example.

#### How other test framework do it?

PHPUnit:

```xml
<phpunit>
    ...
    <logging>
        <log type="coverage-html" target="/path/to/tmp"/>
    </logging>
</phpunit>
```

PhpSpec (in a [custom extension](https://github.com/leanphp/phpspec-code-coverage#configuration)):

```yaml
extensions:
    LeanPHP\PhpSpec\CodeCoverage\CodeCoverageExtension:
        format:
            - text
            - html
```

#### What do you get instead?

It's possible to set coverage report types [in the command line only](https://codeception.com/docs/11-Codecoverage#local-codecoverage)

```bash
codecept run --coverage --coverage-xml --coverage-html
```

### Details

* Codeception version: 3.0.2
* PHP Version: 7.2
* Operating System: any
* Installation type: Composer

---

Related to https://github.com/infection/infection/issues/45
