### ISSUE TITLE
Acceptance test deletes database table

### ISSUE THREAD

**Issue by kmmathis** [Codeception/Codeception#567]
Installed Codeception through composer with the `"codeception/codeception": "1.6.*@dev"` requirement.

When I run an acceptance test, the table that I'm checking actually gets deleted from my database. Below is my config and test code, and the resulting error after running `codecept run`. I am absolutely positive the 'users' table exists before I run the test. Immediately after, it is gone.

codeception.yml

``` YAML
paths:
    tests: tests
    log: tests/_log
    data: tests/_data
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=codecept'
            user: 'root'
            password: 'root'
            dump: tests/_data/dump.sql
```

tests/acceptance/AddUsersCept.php

``` php
<?php
$I = new WebGuy($scenario);
$I->wantTo('add a new user and see it in database');
$I->amOnPage('/');
$I->fillField('email', 'email@address.com');
$I->click('Add User');
$I->seeInDatabase('users', ['email' => 'email@address.com']);
```

The error message

```
1) Couldn't add a new user and see it in database in AddUsersCept.php

PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'codecept.users' doesn't exist
```
