### ISSUE TITLE
Can I mix api (rest with phpBrowser) and acceptance (with WebDriver) tests ?

### ISSUE THREAD

**Issue by borgogelli** [Codeception/Codeception#5673]
I'm trying to run both api (rest with phpBrowser) and acceptance tests (with WebDriver/Selenium)

### The problem

Everything is right if I run;

`codecept run acceptance`
or
`codecept run api`

But if I run 

`codecept run`

I got errors from every api methods called

`[RuntimeException] Action 'sendPOST' can't be called`
or 
`[RuntimeException] Action 'haveHttpHeader' can't be called`

#### codeception.yml

```yml
params: 
    - env
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    shuffle: false
    lint: true
```

#### acceptance.suite.yml

```yml
actor: AcceptanceTester
path: .
modules:
    enabled:
        - WebDriver:
            url: http://192.168.0.2
            host: 192.168.0.1
            browser: chrome
        - \Helper\Acceptance
        
# add Codeception\Step\Retry trait to AcceptanceTester to enable retries
step_decorators:
    - Codeception\Step\ConditionalAssertion
    - Codeception\Step\TryTo
    - Codeception\Step\Retry    

```
#### api.suite.yml

```yml
actor: ApiTester
modules:
    enabled:    
        - REST:
            url: 
            depends: PhpBrowser
            part: Json
            url: http://192.168.0.2

```

 
### Details

* Codeception version: 3.0.3
* PHP Version: 7.1.1
* Operating System: Widnows 10
* Installation type: Phar
