### ISSUE TITLE
Question: More flexible or fine granular steps ignoring in Recorder extension?

### ISSUE THREAD

**Issue by reinholdfuereder** [Codeception/Codeception#5679]
#### What are you trying to achieve?
Based on my workaround for #5678 I'd like to ignore only certain usages of a step (i.e. one with specific parameters) namely `waitForElementVisible('.kg_load', 5)`, instead of all of them (`waitForElementVisible`).

This is the workaround implementation in a method within a PageObject class:
```php
  /**
   * @return self
   */
  protected function waitForLoadingBoxNotVisible(): self {
    if ($this->isAcceptanceTestWithWebDriver()) {
      try {
        $this->getAcceptanceTesterWebDriver()->waitForElementVisible('.kg_load', 5);
      } catch (\Facebook\WebDriver\Exception\NoSuchElementException $e) {
        //$this->getAcceptanceTester()->comment('Ignoring failing waiting for visible loading box: ' . $e->getMessage());
      }
      $this->getAcceptanceTesterWebDriver()->waitForElementNotVisible('.kg_load');
    }
    return $this;
  }
```

Ideally, but I fear this requires major refactorings and is out-of-scope, I think I might even prefer to ignore this PageObject `waitForLoadingBoxNotVisible` method altogether (as long as it succeeds)...

#### What do you get instead?
Seemingly currently I could ignore ALL `waitForElementVisible` steps, which is not really what I want -- due to being rather paranoid ;-)

Some naive debug logs of the available `\Codeception\Step` object show:
```
step tostring: wait for element visible ".kg_load",5
name: Step
action: waitForElementVisible
meta step action: openRandomConfiguratorAndAddToCart
getPhpCode: $I->waitForElementVisible(".kg_load",5)
getHumanizedActionWithoutArguments: wait for element visible
```
... that is in theory regex/wildcards based on `$step` (i.e. its toString) or `$step->getPhpCode(...)` might allow something like this, but I am not sure you would really like that (in a PR)?

### Details

* Codeception version: 3.0.3
* PHP Version: 7.2
* Operating System: Linux
* Installation type: Phar
* Suite configuration:

```yml
...
extensions:
  enabled:
    - Codeception\Extension\RunFailed
    - Codeception\Extension\Recorder:
        delete_successful: false
        delete_orphaned: true
        error_color: red
        # Only this variant would work:
        #ignore_steps: [waitForElementVisible]
        # Either one of these variants would be my goal (I think):
        #ignore_steps: ['waitForLoadingBoxNotVisible']
        #ignore_steps: ['I wait for element visible ".kg_load",5']
...
```
