### ISSUE TITLE
Codeception as a docker service - Problem accessing project classes

### ISSUE THREAD

**Issue by dariofilipe95** [Codeception/Codeception#5715]
FMI: Project in docker. 
Services in docker-compose:
- php
- nginx
- mysql
- codeception

#### What are you trying to achieve?
While developing an unit test and trying to access an entity (e.g.), and having codeception declared as a docker service, i found out that i haven't access to my php classes, unless in the composer of my project i add the codeception there too. Then, when i run the codeception service (container), i will have access to them, but only because i required them in the composer of my project. This is bad cause it makes me to control the version of codeception in two places... It forced to me to abandon the docker approach and having it required in the my composer, since it wouldn't make any sense having in both places.

#### What do you get instead?
Error while trying to access my classes through their respective namespace.

```php
<?php

namespace App\Tests\unit;

use \Codeception\Stub\Expected;
use App\Entity\DummyClass;

class DummyTest extends \Codeception\Test\Unit
{
...
    protected function _before()
    {
        // CRASHES HERE
        $dummy = new DummyClass();
        ...
    }
```
### Details

* Codeception version: 3.1.1
* PHP Version: 7.3
* Symfony 4.3
* Operating System: Ubuntu 18.04
* Installation type: Docker
* Unit Suite configuration:
```yml
actor: UnitTester
modules:
    enabled:
        - Asserts
        - Symfony:
            app_path: 'src'
            environment: 'dev'
    step_decorators: ~  
```
      

* Codeception configuration:
```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    strict_xml: true
params:
    - .env

```

* docker-compose.yml configuration:
```yml
version: '3.3'

services:
    mysql:
      image: mysql:8.0
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=...
        - MYSQL_DATABASE=...
        - MYSQL_USER=...
        - MYSQL_PASSWORD=...
      ports:
        - "3306:3306"
      volumes:
        - db-data:/var/lib/mysql
      networks:
        - x

    webserver:
      image: nginx:alpine
      working_dir: /srv/prc
      depends_on:
        - php
      volumes:
          - .:/srv/prc
          - ./setup/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"
      networks:
        - x

    php:
      build:
        context: .
        dockerfile: setup/php/Dockerfile
      working_dir: /srv/prc
      depends_on:
        - mysql
      volumes:
        - .:/srv/prc:cached
      networks:
        - x

volumes:
  db-data:

networks:
  x:
```

* docker-compose-test.yml configuration:
```yml
version: '3.3'

services:
    codeception:
    # IF VERSION CHANGE, CHANGE IT ALSO IN COMPOSER (declared in both sides)
        image: codeception/codeception:3.1.0
        depends_on:
          - webserver
          - chrome_node
        working_dir: /srv/prc
        volumes:
          - ./:/srv/prc
        networks:
          - prcnet
        entrypoint: /srv/prc/bin/test-wait_for_hub.sh codecept

```

It is possible that my explanation ain't the best one, so feel free to ask any questions.

I thank you all in advance for your attention.
In case this is not a bug and there is a workaround for this, please do share. As they say, sharing is caring :) 

cumps!
