### ISSUE TITLE
Click on XPath with special characters

### ISSUE THREAD

**Issue by umadgen** [Codeception/Codeception#5726]
Hello !

I have a problem with XPATH and special character "ç".

#### What are you trying to achieve?
I try to click on element with the text "Façade", i use xpath for this.

#### What do you get instead?
I get a error "CSS or XPATH malformed"

> retryClick('//a[@class="accordion-toggle"]/span[text()="Façade"]/preceding::a[1]');
$I->   I click "//a[@class="accordion-toggle"]/span[text()="Fa ade"]/preceding::a[1]"
  Retrying #1 in 500ms
  Retrying #2 in 1000ms
  Retrying #3 in 2000ms
  Retrying #4 in 4000ms
error CSS or XPath locator is malformed: //a[@class="accordion-toggle"]/span[text()="Fa ade"]/preceding::a[1]

`$this->tester->retryClick('//a[@class="accordion-toggle"]/span[text()="Façade"]/preceding::a[1]');`

### Details

* Codeception version: 3.0.3
* PHP Version: 7.3
* Operating System: Windows 10
* Installation type: Phar 

```yml
# suite config
suites:
    acceptance:
        actor: AcceptanceTester
        path: .
        modules:
            enabled:
                - WebDriver:
                    url: 'mywebsite'
                    browser: chrome
                    wait: 5
                - \Helper\Acceptance
                
        # add Codeception\Step\Retry trait to AcceptanceTester to enable retries
        step_decorators:
            - Codeception\Step\ConditionalAssertion
            - Codeception\Step\TryTo
            - Codeception\Step\Retry
                
extensions:
    enabled: [Codeception\Extension\RunFailed]

params: 
    - env

gherkin: []    

# additional paths
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs

settings:
    shuffle: false
    lint: true
```

I do a lot of research but i've found nothing.
