### ISSUE TITLE
How to implement listeners from phpunit.xml to codeception?

### ISSUE THREAD

**Issue by activeNathan** [Codeception/Codeception#5736]
#### What are you trying to achieve?
Trying to get report of slow tests and would like to use [johnkary/phpunit-speedtrap](https://github.com/johnkary/phpunit-speedtrap) which requires setting a listener in phpunit.xml and it is not clear to me how to emulate this for codeception.

#### What do you get instead?
We don't get the report after runs for slow tests per speedTrap.

### Details
Listener setup in phpunit.xml:
```xml
<listeners>
	<listener class="JohnKary\PHPUnit\Listener\SpeedTrapListener">
		<arguments>
			<array>
				<element key="slowThreshold">
					<integer>500</integer>
				</element>
				<element key="reportLength">
					<integer>5</integer>
				</element>
			</array>
		</arguments>
	</listener>
</listeners>
```

* Codeception version: 3.1.1
* PHP Version: 7.2.22
* Operating System: Linux
* Installation type: Composer
* Suite configuration:

```yml
actor: Tester
paths:
    tests: .
    log: _output
    data: _data
    support: _support
    envs: _envs
bootstrap: _bootstrap.php
settings:
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    remote: false
    c3_url: 'https://<something>'
    remote_config: ../../../../../../../tests/
    include:
        - ../classes/*.php
params:
    - env.php
```
