### ISSUE TITLE
Codeception Db Module deleting my DATABASE!

### ISSUE THREAD

**Issue by gusdecool** [Codeception/Codeception#574]
I user Codeception version 1.6.7

Following with this tutorial here http://codeception.com/docs/modules/Db
I tried this Db config:

```
paths:
    tests: tests
    log: tests/_log
    data: tests/_data
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
modules:
    enabled: [Db]
    config:
      Db:
        dsn: 'mysql:host=localhost;dbname=test_codeception'
        user: 'gusdecool'
        password: 'gusdecool'
        dump: 'tests/_data/dump.sql'
        populate: true
        cleanup: false
```

And this is the code for my AcceptanceTesting

``` php
<?php
$user = 'gusdecool';
$pass = 'gusdecool';

/** @var $scenario \Codeception\Scenario */
$I = new WebGuy($scenario);
$I->wantTo('Do successful login');
$I->amOnPage('/index.php');
$I->fillField('user', $user);
$I->fillField('pass', $pass);
$I->click('input[type="submit"]');
$I->see('Hello, '.$user);
$I->amGoingTo('Testing check database');
$I->seeInDatabase('user', array('name'=>'gusdecool', 'pass'=>'123456'));
```

And then everytime i use `run` command, my actual database table is deleted!!!
and no database is dumped in `tests/_data/dump.sql`

Why this happening?
