### ISSUE TITLE
Can i use sendGet method from acceptance tests ?

### ISSUE THREAD

**Issue by Gadzillion** [Codeception/Codeception#5742]
#### What are you trying to achieve?

Use the code below in acceptance tests.

```
    $I->sendGET('$this->config["url"]');
    $I->seeResponseCodeIs(200); 
```

### Details

Codeception version: 3.1.2
PHP Version: 7.2.23
Operating System: Linux Mint
Installation type: Composer

**Comment by Naktibalda** [comment]
Yes, you can, if REST module is enabled and configured correctly.

**Comment by Gadzillion** [comment]
@Naktibalda thx u, i made like you said

```
actor: AcceptanceTester
modules:
  enabled:
    - WebDriver
    - \Helper\Acceptance
    - Asserts
    - REST:
        depends: PhpBrowser
        shortDebugResponse: 300 # only the first 300 chars of the response
  config:
    WebDriver:
      url: ***
      browser: chrome
      port: 9515
      restart: true
      wait: 3
      clear_cookies: true
      debug_log_entries: 200

env:
  chrome:
    modules:
      config:
        WebDriver:
          capabilities:
            unexpectedAlertBehaviour: 'dismiss'
            chromeOptions:
              w3c: false
```

TestCest.php

```
        $I->sendGET($this->config['url']);
        $I->seeResponseCodeIs(200);
```

Can i grab [Response] header without ```sendGET``` ?

**Comment by Naktibalda** [comment]
There is no way to check response status using WebDriver.

**Comment by Gadzillion** [comment]
@Naktibalda thx, i improved my code and i now i'm getting an error
```
Call to undefined method AcceptanceTester::tryTograbTextFrom 
```

```
actor: AcceptanceTester
modules:
  enabled:
    - WebDriver
    - \Helper\Acceptance
    - Asserts
    - REST:
        depends: PhpBrowser
        shortDebugResponse: 300
  step_decorators:
    - Codeception/Step/TryTo
    - Codeception/Step/Retry
    - Codeception/Step/ConditionalAssertion
```
