### ISSUE TITLE
Deprecation warnings are not testable

### ISSUE THREAD

**Issue by CJDennis** [Codeception/Codeception#5757]
#### What are you trying to achieve?
I'm trying to test that a method is deprecated. Codeception inherits PHPUnit's `expectDeprecation()`, so in theory it should work.

#### What do you get instead?
`Failed asserting that exception of type "PHPUnit\Framework\Error\Deprecated" is thrown.`

This code works in PHPUnit but not in Codeception:

```php
  public function testShouldRaiseADeprecationWarning() {
    $this->expectDeprecation();
    trigger_error('', E_USER_DEPRECATED);
  }
```
### Details

* Codeception version: 3.1
* PHP Version: 7.3
* Operating System: Windows
* Suite configuration:

```yml
paths:
    tests: tests-codeception
    output: tests-common/_output
    data: tests-codeception/_data
    support: tests-codeception/_support
    envs: tests-codeception/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    include:
        - src/*
    low_limit: 50
    high_limit: 100
```
