### ISSUE TITLE
Why set the config values are not allowed for modules like Doctrine2? 

### ISSUE THREAD

**Issue by reypm** [Codeception/Codeception#5770]
#### What are you trying to achieve?

I have a custom helper which is extending from Doctrine2 module:

```php
namespace Helper;

use Codeception\Module\Doctrine2;

class CasePriorityHelper extends Doctrine2
{
    // ...
}
```

and I do not want to have the helper enabled for each suite meaning I would like to use the `_inject` built-in functionality as for example:

```php
<?php

declare(strict_types=1);

namespace App\Tests\api\Priority;

use ApiTester;
use Helper\CasePriorityHelper;

class SetCasePriorityCest
{
    /** @var CasePriorityHelper */
    private $casePriorityHelper;

    protected function _inject(CasePriorityHelper $casePriorityHelper)
    {
        $this->casePriorityHelper = $casePriorityHelper;
    }

    /**
     * @param ApiTester $I
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function _before(ApiTester $I)
    {
        $this->resourceId = $this->casePriorityHelper->getLastResourceId();
    }
}
```

Is there a way to set such dependency? Any workaround?

#### What do you get instead?

When I run the api suite I got the following error:

> Failed to inject dependencies in instance of 'App\Tests\api\Priority\SetCasePriorityCest'. Failed to inject dependencies in instance of 'Helper\CasePriorityHelper'. Failed to resolve dependency 'Codeception\Lib\Interfaces\DoctrineProvider'.

And I know the problem is caused because I am not "enabling" the helper in the suite configuration file as it should be, ie:

```yml
- \Helper\CasePriorityHelper:
    depends: Symfony
```

### Details

* Codeception version: 3.1.2
* PHP Version: 7.2.23
* Operating System: Ubuntu
* Installation type: Composer
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - Asserts
        - Symfony:
              app_path: 'src'
              environment: 'test'
        - REST:
              url: 'http://drm-case-v2'
              depends: PhpBrowser
              part: Json
              timeout: 90 # or 90000, same thing
        - PhpBrowser:
              url: 'http://localdevelopment.local'
              headers:
                  Accept: application/json
                  Content-Type: application/json
                  Cookie: XDEBUG_SESSION=PHPSTORM
              curl:
                  CURLOPT_RETURNTRANSFER: true
                  CURLOPT_TIMEOUT: 600
        - Db:
            dsn: '%DB_DRIVER%:host=%DB_HOSTNAME%;dbname=db_local'
            user: '%DB_USERNAME%'
            password: '%DB_PASSWORD%'
            cleanup: true
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - \Helper\Api
        - \Helper\DbHelper
        - \Helper\ArrayHelper
        - \Helper\ExtendedDoctrine2:
            depends: Symfony
            cleanup: true
```
