### ISSUE TITLE
WebDebug is not working

### ISSUE THREAD

**Issue by agarzon** [Codeception/Codeception#579]
Following the examples for WebDebug, doesn't work.
Running 

``` shell
$I->makeAScreenshot();
```

I got:

``` shell
 RuntimeException: Call to undefined method WebGuy::makeAScreenshot
```

And in my acceptance.suite.yml

``` yaml
modules:
    enabled:
        - PhpBrowser
        - WebDebug
        - WebHelper
```
