### ISSUE TITLE
Functional not showing exception

### ISSUE THREAD

**Issue by gusdecool** [Codeception/Codeception#580]
From this page: http://codeception.com/docs/05-FunctionalTests
It said, functional test will show exception. But tried it, it didn't show notice of exception?

Config

```
# Codeception Test Suite Configuration

# suite for functional (integration) tests.
# emulate web requests and make application process them.
# (tip: better to use with frameworks).

# RUN `build` COMMAND AFTER ADDING/REMOVING MODULES.

class_name: TestGuy
modules:
    enabled: [Filesystem, TestHelper, PhpBrowser]
    config:
            PhpBrowser:
                url: 'http://localhost/test-codeception/'
error_level: "E_ALL & ~E_STRICT & ~E_DEPRECATED"
```

Page tested

``` php
<?php
function throwAja() {
    throw new RuntimeException('maho lu', 555);
}

if(isset($_POST['name'])) {
    try {
        throwAja();
    } catch (RuntimeException $e) {
        echo $e->getMessage();
    }
}
?>
<form id="form" action="" method="post">
    <input name="name" />
    <input type="submit" />
</form>
```

Functional Cept

``` php
<?php
$I = new TestGuy($scenario);
$I->wantTo('Test exception');
$I->amOnPage('/functional.php');
$I->submitForm('#form', array('name'=>'show exception'));
$I->see('maho');
```

And the test didn't said if i throw exception @_@

```
Codeception PHP Testing Framework v1.6.7
Powered by PHPUnit 3.7.25 by Sebastian Bergmann.

Suite functional started
Trying to test exception (FunctionalCept.php)
Scenario:
* I am on page "/functional.php"
* I submit form "#form",{"name":"show exception"}
* I see "maho"
    PASSED  



Time: 325 ms, Memory: 12.25Mb

OK (1 test, 1 assertion)
```
