### ISSUE TITLE
symfony/process missing

### ISSUE THREAD

**Issue by zdenekgebauer** [Codeception/Codeception#5816]
#### What are you trying to achieve?
run acceptance tests with Phpbrowser and builtin server 

#### What do you get instead?
```
In RunProcess.php line 66:
Codeception\Extension\RunProcess
symfony/process package is required
```
### Details

* Codeception version: 4.0.1
* PHP Version: 7.3
* Operating System: Win10
* Installation type: Composer
* List of installed packages (`composer show`)
```
  "require-dev": {
    "codeception/codeception": "^4.0",
    "codeception/module-asserts": "^1.1",
    "codeception/module-phpbrowser": "^1.0"
}
```
* Suite configuration:

```yml
extensions:
    enabled:
        - Codeception\Extension\RunProcess:
          - php -S 127.0.0.1:8000 -t tests/default_web

```
* Workaround:
```bash
composer require symfony/process --dev
```
