### ISSUE TITLE
CodeCoverage slows down between test suites

### ISSUE THREAD

**Issue by tweber68** [Codeception/Codeception#5817]
#### Acceleration of CodeCoverage

I suggest to adapt Configuration.php function mergeConfigs line 674:

currently:
```
return array_merge_recursive($a2, $a1);
```

to:
```
return array_merge(array_unique(array_merge_recursive($a2, $a1), SORT_REGULAR));
```

#### What is the problem?

I had the problem that lots of calls of `mergeConfigs()` made the internally handled `$this->config` variable explode. 
```php
$a = ['a','b','c'];
$b = ['a','b','c'];

var_export(array_merge_recursive($a,$b));
```

output:
```
array (
  0 => 'a',
  1 => 'b',
  2 => 'c',
  3 => 'a',
  4 => 'b',
  5 => 'c',
)
```

I think this is not intended. In my project `$this->config` of Codeception/Lib/ModuleContainer should contain 5 entries, but it grew up to 100000s of entries by this logic.

### Details

* Codeception version: 4.0.2
* PHP Version: 7.2
* Operating System: Ubuntu 16.04
* Installation type: Composer
* List of installed packages (`composer show`):
```
behat/gherkin                      v4.6.0             Gherkin DSL parser for PHP 5.3
codeception/codeception            4.0.2              BDD-style testing framework
codeception/lib-asserts            1.10.1             Assertion methods used by Codeception core and Asserts module
codeception/module-asserts         1.1.1              Codeception module containing various assertions
codeception/module-cli             1.0.0              Codeception module for testing basic shell commands and shell output
codeception/module-filesystem      1.0.2              Codeception module for testing local filesystem
codeception/module-mongodb         1.0.0              MongoDB module for Codeception
codeception/phpunit-wrapper        8.1.1              PHPUnit classes used by Codeception
codeception/stub                   3.6.0              Flexible Stub wrapper for PHPUnit's Mock Builder
composer/ca-bundle                 1.2.6              Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
composer/xdebug-handler            1.4.0              Restarts a process without Xdebug.
dnode/dnode                        v0.1.3             DNode RPC protocol for PHP 5.3
doctrine/instantiator              1.3.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
domnikl/statsd                     2.10.0             a PHP client for statsd
evenement/evenement                v1.0.0             Événement is a very simple event dispatching library for PHP 5.3
geoip2/geoip2                      v2.10.0            MaxMind GeoIP2 PHP API
guzzlehttp/guzzle                  6.5.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.6.1              PSR-7 message implementation that also provides common utility methods
league/iso3166                     2.1.4              ISO 3166-1 PHP Library
maxmind-db/reader                  v1.6.0             MaxMind DB Reader API
maxmind/web-service-common         v0.6.0             Internal MaxMind Web Service API
mongodb/mongodb                    1.2.0              MongoDB driver library
myclabs/deep-copy                  1.9.4              Create deep copies (clones) of your objects
opis/closure                       3.5.1              A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
osi/dsp-bid-mocker                 dev-master 10fa71b Sends from template and dsp-config generated bid requests to a URL and checks the reponses
osi/DVT                            v1.0.7             DeviceDetect is tool to detect type of devices
osi/lib-common                     v2.2.169           osi/lib-common
osi/protobuf                       dev-master 043ee1a for Google Protobuf usage
osi/syscheck                       v1.0.27            Syscheck tool for check system requirement of project.
pdepend/pdepend                    2.6.1              Official version of pdepend to be handled with Composer
phar-io/manifest                   1.0.3              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1              Library for handling version information and constraints
phpdocumentor/reflection-common    2.0.0              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.4              With this component, a library can provide support for annotations via DocBlocks or otherwise retriev...
phpdocumentor/type-resolver        1.0.1              A PSR-5 based resolver of Class names, Types and Structural Element Names
phpmailer/phpmailer                v5.2.9             PHPMailer is a full-featured email creation and transfer class for PHP
phpmd/phpmd                        2.8.1              PHPMD is a spin-off project of PHP Depend and aims to be a PHP equivalent of the well known Java tool...
phpspec/prophecy                   1.10.1             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          7.0.10             Library that provides collection, processing, and rendering functionality for PHP code coverage infor...
phpunit/php-file-iterator          2.0.2              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  2.1.2              Utility class for timing
phpunit/php-token-stream           3.1.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    8.5.2              The PHP Unit Testing framework.
psr/cache                          1.0.1              Common interface for caching libraries
psr/container                      1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                   1.0.1              Common interface for HTTP messages
psr/log                            1.1.2              Common interface for logging libraries
ralouphie/getallheaders            3.0.3              A polyfill for getallheaders.
react/event-loop                   v0.2.7             Event loop abstraction layer that libraries can use for evented I/O.
react/socket                       v0.2.6             Library for building an evented socket server.
react/stream                       v0.2.6             Basic readable and writable stream interfaces that support piping.
riimu/kit-phpencoder               v2.4.0             Highly customizable alternative to var_export for PHP code generation
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2              Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.2              Diff implementation
sebastian/environment              4.2.3              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.2              Provides the functionality to export PHP variables for visualization
sebastian/global-state             3.0.0              Snapshotting of global state
sebastian/object-enumerator        3.0.3              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.1              Provides a list of PHP built-in functions that operate on resources
sebastian/type                     1.1.3              Collection of value objects that represent the types of the PHP type system
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
spatie/async                       0.0.4              Asynchronous and parallel PHP with the PCNTL extension
squizlabs/php_codesniffer          3.5.3              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of co...
symfony/config                     v4.4.2             Symfony Config Component
symfony/console                    v3.4.0             Symfony Console Component
symfony/contracts                  v1.1.8             A set of abstractions extracted out of the Symfony components
symfony/css-selector               v5.0.2             Symfony CssSelector Component
symfony/debug                      v4.4.2             Symfony Debug Component
symfony/dependency-injection       v4.4.2             Symfony DependencyInjection Component
symfony/event-dispatcher           v4.2.8             Symfony EventDispatcher Component
symfony/filesystem                 v5.0.2             Symfony Filesystem Component
symfony/finder                     v3.4.0             Symfony Finder Component
symfony/http-foundation            v5.0.2             Symfony HttpFoundation Component
symfony/mime                       v5.0.2             A library to manipulate MIME messages
symfony/options-resolver           v5.0.2             Symfony OptionsResolver Component
symfony/polyfill-ctype             v1.13.1            Symfony polyfill for ctype functions
symfony/polyfill-intl-idn          v1.13.1            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring          v1.13.1            Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.13.1            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                    v3.4.0             Symfony Process Component
symfony/yaml                       v3.4.0             Symfony Yaml Component
theseer/tokenizer                  1.1.3              A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.6.0              Assertions to validate method input/output with nice error messages.
```

* Suite configuration:

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
    helpers: tests/_support
bootstrap: _bootstrap.php
settings:
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    enabled:
        - MongoDb:
            dsn: 'mongodb://localhost:27017/dsp_qatest'
            user: ''
            password: ''
            populate: false
            cleanup: false
            
coverage:
    enabled: true
    include:
        - buyer/*
    exclude:
        - buyer/Rtb/Util/PHP*
        - buyer/Rtb/Util/SharedMemoryInterface.php      
        - buyer/Rtb/Service/Adapters/Mobfox
        - buyer/Rtb/Service/Adapters/Mobfoxbanner
        - buyer/Rtb/Service/Adapters/Liverail
        - buyer/Rtb/Service/Adapters/Pubmatic
        - buyer/Rtb/Service/Adapters/Rubicon
        - buyer/Rtb/Model/DAO/JS/PlacementStatisticsDailyMap.js
        - buyer/Rtb/Model/DAO/JS/PlacementStatisticsDailyReduce.js
        - buyer/Rtb/Util/functions.php
        - buyer/Rtb/Model/DAO/MongoConnection.php
        
env:
    devel:
         modules:
            config:
                MongoDb:
                    dsn: 'mongodb://localhost:27017/dsp_qatest'
                    user: ''
                    password: ''
                    populate: false
                    cleanup: false

    production:
         modules:
            config:
                MongoDb:
                    dsn: 'mongodb://localhost:27017/dsp_qatest'
                    user: ''
                    password: ''
                    populate: false
                    cleanup: false

```
