### ISSUE TITLE
global configuration, bootstrap: _bootstrap.php does not work

### ISSUE THREAD

**Issue by mipon** [Codeception/Codeception#5819]
#### What are you trying to achieve?

As explained in this [page](http://phptest.club/t/bootstrap-deprecations-in-3-0/2196), trying to gt rid of the deprecated setting, `bootstrap` in the global configuration. I'd like to avoid setting it in each suite configuration.

#### What do you get instead?

The specified bootstrap file is not loaded. 

This doesn't load `_bootstrap.php`.
```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
bootstrap: _bootstrap.php
settings:
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```

However, this still works with the warning `DEPRECATION: 'settings: bootstrap: _bootstrap.php' option is deprecated! Replace
 it with: 'bootstrap: _bootstrap.php' (not under settings section). See https://
bit.ly/2YrRzVc`.
```yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
settings:
    colors: true
    memory_limit: 1024M
    bootstrap: _bootstrap.php
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```

### Details

* Codeception version: 4.0.1 (downloaded with a link saying v4.0.2 but it says 4.0.1)
* PHP Version: 7.3
* Operating System: Windows 10
* Installation type: Phar
* Suite configuration:

```yml
actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
    step_decorators: ~
error_level: "E_ALL ^ E_NOTICE"
```
