### ISSUE TITLE
How set user-agent in acceptance tests

### ISSUE THREAD

**Issue by omeluhin89** [Codeception/Codeception#5831]
Hi, i want set user-agent in acceptance tests. I use WebDriver
I set this parametrs:
```class_name: AcceptanceTester
modules:
    enabled:
        - Asserts
        - WebDriver
        - tests\AcceptanceHelper
    params:
        - env
    config:
        WebDriver:
            host: seleniumhub
            url: ""
            browser: chrome
            window_size: 1024x768
            restart: true
            capabilities:
                userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 SimaTerminal/567"
extensions:
    enabled:
        - Codeception\Extension\Recorder
env:
    # Запуск тестов на backend
    slcom:
        modules:
            config:
                WebDriver:
                    url: https://testben.ru
                    browser: chrome
                    window_size: 1024x768
                    restart: true
    slcom_production:
        modules:
            config:
                WebDriver:
                    url: https://test.com
                    browser: chrome
                    window_size: 1024x768
                    restart: true```

But this don't work ((
What am I doing wrong?

**Comment by Naktibalda** [comment]
I looked at https://tarunlalwani.com/post/selenium-change-user-agent-different-browsers/ 
and https://stackoverflow.com/questions/50375628/how-to-change-useragent-string-in-runtime-chromedriver-selenium

UserAgent is not a capability, but it is possible to change it through chromeOptions.
It should look like this (not tested):
```yml
capabilities:
  "goog:chromeOptions":
    args:
    - "user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36 SimaTerminal/567"
```
