### ISSUE TITLE
API testing with modules: REST + Symfony 

### ISSUE THREAD

**Issue by cassianotartari** [Codeception/Codeception#5833]
#### What are you trying to achieve?
It's my first test, I'm studying Codeception to implement it at my company. I'm trying to test a customer creation in my api created with a symfony bundle.

#### What do you get instead?
A 404, not found, because I can't set the scheme of the request. My api route only accept https requests, so the symfony application returns not found for the route because is using port 80.

```
 I have http header "Content-Type","application/json"
 I send post "/customers/?token=marketplace",{"identityNumber":"54039023000139","companyName":"Razao empresa","tradeName":"Fantasia empresa","responsible":"Rep empresa","freeStateRegistration":true,"...}
  [Request] POST platform/api/customers/?token=marketplace {"identityNumber":"54039023000139","companyName":"Razao empresa","tradeName":"Fantasia empresa","responsible":"Rep empresa","freeStateRegistration":true,"stateRegistration":"123456789","primaryPhone":"48 32222222","secondPhone":"48 32222222","address":{"postCode":"88117030","city":"Nome Cidade","state":"Estado","country":"pais","street":"rua teste","district":"bairro","complement":"Casa","number":998},"email":"cliente@clientehost.com","enabled":false,"customerType":{"referenceCode":"default.customer"}}
  [Request Headers] {"Content-Type":"application/json"}
  [Page] platform/api/customers/?token=marketplace
  [Response] 404
  [Request Cookies] []
  [Response Headers] {"cache-control":["no-cache"],"date":["Wed, 29 Jan 2020 18:18:25 GMT"],"execution-time":["Not Handle"],"content-type":["text/html; charset=UTF-8"],"Set-Cookie":[{}]}
  [Response] <!DOCTYPE html>

```
> Provide test source code if related

```php
    public function createCustomerViaAPI(ApiTester $I)
    {
        $body = '
            {
               "identityNumber": "54039023000139",
               "companyName": "Razao empresa",
               "tradeName": "Fantasia empresa",
               "responsible": "Rep empresa",
               "freeStateRegistration": true,
               "stateRegistration": "123456789",
               "primaryPhone": "48 32222222",
               "secondPhone": "48 32222222",
               "address": {
                  "postCode": "88117030",
                  "city": "Nome Cidade",
                  "state": "Estado",
                  "country": "pais",
                  "street": "rua teste",
                  "district": "bairro",
                  "complement": "Casa",
                  "number": 998
               },
               "email": "cliente@clientehost.com",
               "enabled": false,
               "customerType": {
                  "referenceCode": "default.customer"
               }
            }
        ';

        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendPOST('/customers/?token=marketplace', json_decode($body, true));
        $I->seeResponseCodeIs(\Codeception\Util\HttpCode::CREATED);
        $I->seeResponseIsJson();

    }
```
### Details

* Codeception version: 4.0.3
* PHP Version: 5.6.38
* Operating System: Ubuntu 18.04.3
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```
composer show |grep codeception
codeception/codeception              4.0.3              BDD-style testing f...
codeception/lib-asserts              1.1.1              Assertion methods u...
codeception/lib-innerbrowser         1.3.0              Parent library for ...
codeception/module-doctrine2         1.0.1              Doctrine2 module fo...
codeception/module-phpbrowser        1.0.0              Codeception module ...
codeception/module-rest              1.1.0              REST module for Cod...
codeception/module-symfony           1.0.0              Codeception module ...
codeception/module-webdriver         1.0.1              WebDriver module fo...
codeception/phpunit-wrapper          6.0.18             PHPUnit classes use...
codeception/stub                     2.1.0              Flexible Stub wrapp...

symfony/symfony                      v2.8.44            The Symfony PHP fra...
```

```yml
#api.suite.yml
actor: ApiTester
class_name: ApiTester
modules:
    enabled:
        - Symfony:
            app_path: '../../../../../../app'
            var_path: '../../../../../../app'
            environment: 'test'
        - REST:
            url: '/platform/api'
            depends: Symfony
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - \ApiBundle\Helper\Api
```

```yml
#codeception.yml
namespace: ApiBundle
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```

**Comment by Naktibalda** [comment]
The best workaround would be to setup a route without https scheme.

**Comment by cassianotartari** [comment]
> The best workaround would be to setup a route without https scheme.

Sadly this is not a option.

I'm checking how to do it without using Symfony module, just with PhpBrowser.
```yml
actor: ApiTester
class_name: ApiTester
modules:
    enabled:
        - Symfony:
            app_path: '../../../../../../app'
            var_path: '../../../../../../app'
            environment: 'dev'
        - REST:
            url: 'https://marketplace.ftwo.local/platform/api'
            depends: PhpBrowser
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - \ApiBundle\Helper\Api
```
I've spent some time with this because we use docker here I have changed the nginx container to support this url:
```yml
        networks:
            net:
                aliases:
                    - marketplace.ftwo.local
```
The subdomain ``marketplace`` is a id for switch the database, it's the client reference code. I'm not happy with this solution because the id is hard coded in docker, but I know this offtopic.

I'm learning Codeception, reading the docs more than once. With this REST approach (phpbrowser) I checked the the database records generated in the simple customer creation API were not deleted.

As [documentation](https://codeception.com/docs/modules/Doctrine2) says:
> By default, the module will wrap everything into a transaction for each test and roll it back afterwards (this is controlled by the cleanup setting). By doing this, tests will run much faster and will be isolated from each other.

What I'm missing?
