### ISSUE TITLE
FuncionalTest `Undefined variable`

### ISSUE THREAD

**Issue by Migo2468** [Codeception/Codeception#5835]
Hi when i run my tests, I have error in funcional.suite.yml. What is wrong?

```bash
Codeception PHP Testing Framework v4.0.3
Powered by PHPUnit 8.5.2 by Sebastian Bergmann and contributors.
Running with seed: 
App\Tests.acceptance Tests (0) ------------------------------------------
--------------------------------------------------------------------------------

App\Tests.api Tests (0) -------------------------------------------------
--------------------------------------------------------------------------------

In ErrorHandler.php line 83:
                       
  Undefined variable: file  

```
### Details
* Codeception version: 4.0.3
* PHP Version: 7.4

```yml
actor: FunctionalTester
modules:
    enabled:
        - Symfony:
            app_path: 'src/'
        - Doctrine2:
            depends: Symfony
        - Asserts
        - Sequence
        - \App\Tests\Helper\Functional
```
