### ISSUE TITLE
Support for AngularJS Acceptance Tests

### ISSUE THREAD

**Issue by kushalkh** [Codeception/Codeception#5837]
#### What are you trying to achieve?
Trying to execute Acceptance Tests on an application running on AngularJS 1.7
Documentation here http://docs1.w3cub.com/codeception/modules/angularjs/ and https://codeception.com/03-10-2016/even-more-features-of-codeception.html#algolia:p:nth-of-type(8) suggests we can just enable AngularJS module in acceptance.suite.yml and it should work.

#### What do you get instead?
Running codecept build after enabling the AngularJS module in yml file gives me this:
Building Actor classes for suites: acceptance, api, functional, unit

In ModuleContainer.php line 112:

  Module AngularJS could not be found and loaded

build

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Building Actor classes for suites: acceptance, api, functional, unit

In ModuleContainer.php line 112:

  [Codeception\Exception\ConfigurationException]
  Module AngularJS could not be found and loaded


Exception trace:
  at phar:///usr/local/bin/codecept/vendor/codeception/codeception/src/Codeception/Lib/ModuleContainer.php:112
 Codeception\Lib\ModuleContainer->create() at phar:///usr/local/bin/codecept/vendor/codeception/codeception/src/Codeception/Lib/Generator/Actions.php:65
 Codeception\Lib\Generator\Actions->__construct() at phar:///usr/local/bin/codecept/vendor/codeception/codeception/src/Codeception/Command/Build.php:64
 Codeception\Command\Build->buildActions() at phar:///usr/local/bin/codecept/vendor/codeception/codeception/src/Codeception/Command/Build.php:88
 Codeception\Command\Build->buildSuiteActors() at phar:///usr/local/bin/codecept/vendor/codeception/codeception/src/Codeception/Command/Build.php:102
 Codeception\Command\Build->buildActorsForConfig() at phar:///usr/local/bin/codecept/vendor/codeception/codeception/src/Codeception/Command/Build.php:40
 Codeception\Command\Build->execute() at phar:///usr/local/bin/codecept/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:982
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/codecept/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/codecept/vendor/codeception/codeception/src/Codeception/Application.php:117
 Codeception\Application->run() at phar:///usr/local/bin/codecept/vendor/codeception/codeception/app.php:38
 {closure}() at phar:///usr/local/bin/codecept/vendor/codeception/codeception/app.php:39
 require_once() at /usr/local/bin/codecept:5

build

```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 4.0.1
* PHP Version: 7.0.33
* Operating System: CentOS 7
* Installation type: Phar
* List of installed packages (`composer show`)
* Suite configuration: 

```yml
# 
- AngularJS:
             url: 'http://127.0.0.1/'
             browser: chrome # 'chrome' or 'firefox'
             window_size: 1024x900
             capabilities:
                acceptInsecureCerts: true
                enableVerboseLogging: true
                chromeOptions:
                    args: ["disable-dev-shm-usage", "no-sandbox", "disable-infobars", "headless", "disable-gpu"]
```
