### ISSUE TITLE
retryClick isn't working

### ISSUE THREAD

**Issue by Gadzillion** [Codeception/Codeception#5841]
I am trying to use

```
$I->retryClick('account');
```

I added

```
use \Codeception\Lib\Actor\Shared\Retry;
```

to AcceptanceTester and this 

```
actor: AcceptanceTester
modules:
  enabled:
    - WebDriver
    - \Helper\Acceptance
    - Asserts
    - REST:
        depends: PhpBrowser
        shortDebugResponse: 300
  step_decorators:
    - Codeception/Step/TryTo
    - Codeception/Step/Retry
```
to acceptance.suite.yml

codecept build and nothing.
What did i do wrong?

```
    public function toAccount($testName)
    {
        $I->waitForElementClickable('account', 25);
        $I->retry(4, 200);
        $I->retryClick('account');
    }
```

Codeception 3.1.2
