### ISSUE TITLE
Code Coverage not working with Symfony module's runSymfonyConsoleCommand

### ISSUE THREAD

**Issue by SimonTod** [Codeception/Codeception#5855]
#### What are you trying to achieve?
I am trying to get code coverage while testing my symfony console command.
Code coverage works perfectly in my application when I test my API.
And my runSymfonyConsoleCommand works great like expected.
#### What do you get instead?
I get 0% of code coverage during my Symfony module's runSymfonyConsoleCommand test.
#### My Guess
My guess is that runSymfonyConsoleCommand works just like a runShellCommand and does not work with code coverage at all. Can you confirm ? Is there a workaround ? Are you planning on making it work ?

* Codeception version: 4.1.1
* PHP Version: 7.3.11
* Operating System: Docker - debian stretch
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - \Helper\HttpCodeHelper
        - \Helper\DbHelper
        - \Helper\Building
        - Asserts
        - Cli
        - Symfony
        - REST
        - Db
    config:
        Symfony:
            app_path: 'app'
            var_path: 'var'
            environment: 'dev'
        REST:
            url: 'http://%API_HOST_AND_PORT%/'
            depends: PhpBrowser
            part: Json
        PhpBrowser:
            url: 'http://%API_HOST_AND_PORT%/'
            proxy: ''
            headers:
                Username: USERNAME
                Content-Type: application/json
            curl:
                CURLOPT_TIMEOUT: 90
        Db:
            dsn: 'mysql:host=%BDD_MYSQL_MASTER_HOST%;dbname=%BDD_MYSQL_DATABASE%'
            user: '%BDD_MYSQL_USER%'
            password: '%BDD_MYSQL_PASSWORD%'
            reconnect: true
```

**Comment by Naktibalda** [comment]
It runs command in the same process, so code coverage should be working: https://github.com/Codeception/module-symfony/blob/1.0.0/src/Codeception/Module/Symfony.php#L566-L582

**Comment by SimonTod** [comment]
I don't understand how to make it work. can you help ?

**Comment by Naktibalda** [comment]
> Code coverage works perfectly in my application when I test my API.

Which module do you use for testing API - Symfony or REST?

**Comment by SimonTod** [comment]
I use REST for testing my API

**Comment by SimonTod** [comment]
I am going to try to seperate my tests in different suites. One for the API, and one for the Symfony console commands. I'll let you know how it works

**Comment by SimonTod** [comment]
Everything seems to work with seperated suites.

Here are the new configurations if anyone needs:

#### api.suite.yml
```yml
actor: ApiTester
modules:
    enabled:
        - \Helper\HttpCodeHelper
        - \Helper\DbHelper
        - \Helper\Building
        - Asserts
        - Cli
        - REST
        - Db
    config:
        REST:
            url: 'http://%API_HOST_AND_PORT%/'
            depends: PhpBrowser
            part: Json
        PhpBrowser:
            url: 'http://%API_HOST_AND_PORT%/'
            proxy: ''
            headers:
                Username: USERNAME
                Content-Type: application/json
            curl:
                CURLOPT_TIMEOUT: 90
        Db:
            dsn: 'mysql:host=%BDD_MYSQL_MASTER_HOST%;dbname=%BDD_MYSQL_DATABASE%'
            user: '%BDD_MYSQL_USER%'
            password: '%BDD_MYSQL_PASSWORD%'
            reconnect: true
```
#### command.suite.yml
```yml
actor: ImportTester
modules:
    enabled:
        - \Helper\DbHelper
        - Asserts
        - Symfony
        - Db
    config:
        Symfony:
            app_path: 'app'
            var_path: 'var'
            environment: 'dev'
        Db:
            dsn: 'mysql:host=%BDD_MYSQL_MASTER_HOST%;dbname=%BDD_MYSQL_DATABASE%'
            user: '%BDD_MYSQL_USER%'
            password: '%BDD_MYSQL_PASSWORD%'
            reconnect: true
```
