### ISSUE TITLE
Suggestion: Option `usleep` for `runProcess()`

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#5888]
With this in my `funcional.suite.yml`
```yaml
extensions:
    enabled:
        - Codeception\Extension\RunProcess:
            0: 'bin/console doctrine:fixtures:load --no-interaction --env=test'
```
... I'm having the issue that the first database query in my cest still receives the data from the previous run. Looks like a file system / caching problem with SQLite. This can easily be solved by adding `sleep: 1` to the config.

However, in my case 0.5 seconds would be enough (as I just figured out). But the `sleep` option only takes integers, since it uses (surprise, surprise!) PHP's `sleep()`:
https://github.com/Codeception/Codeception/blob/4.1/ext/RunProcess.php#L90

So what I'm suggesting is to add another option `usleep` which causes an additional `usleep()` (just below the existing `sleep()`).

All this hassle for just saving 0.5 seconds, you might ask. - Well, it's just *one* more line of code, I'll answer ;-) Should I come up with a PR?
