### ISSUE TITLE
Codeception can't see/click a button

### ISSUE THREAD

**Issue by umadgen** [Codeception/Codeception#5889]
Hello everybody !

#### What are you trying to achieve?
I try to click on a button. My test for this button had no problem for weeks until today. But today, he can't see the button, i don't know why.

#### What do you get instead?

```bash
Test tests\TestCommercialCest.php:mainTest
Step Wait for element visible "//ul[contains(@class,"typeahead") and contains(@style,"block")]/li[1]",2
Fail CSS or XPath element with '//input[@class="msgButton"]' was not found.
Scenario Steps:
63. $I->click("//input[@class="msgButton"]") at tests\_support\Page\Acceptance\Pages\Projet\InfosProjet.php:250
62. $I->switchToNextTab() at tests\_support\Page\Acceptance\Pages\Projet\InfosProjet.php:248
61. $I->selectOption("#action_resultat","Rdv Phase 1") at tests\_support\Page\Acceptance\Pages\Projet\InfosProjet.php:247
60. $I->see("Rdv Phase 1","//table[contains(@class,"HACL")]/tbody/tr/td") at tests\_support\Page\Acceptance\Pages\Projet\InfosProjet.php:241
59. $I->waitForText("Rdv Phase 1",5) at tests\_support\Page\Acceptance\Pages\Projet\InfosProjet.php:240
58. $I->click("li[data-name="Infos projet"]") at tests\_support\Page\Acceptance\Pages\Projet\InfosProjet.php:238
```

```php
$this->tester->retrySelectOption("#action_resultat", "Rdv Phase 1");
            $this->tester->retrySwitchToNextTab();
            $this->tester->waitForElementVisible('//input[@class="msgButton"]',20);
            $this->tester->retryClick('//input[@class="msgButton"]');
            
            $this->tester->retryClick('(//button[contains(@class,"ui-multiselect")])[2]');
            $this->tester->retryClick('(//a[@class="ui-multiselect-none"])[2]');
            $this->tester->fillField('(//div[@class="ui-multiselect-filter"]/input[@type="search"])[2]', $commercial);
            $this->tester->retryCheckOption('(//ul[@class="ui-multiselect-checkboxes ui-helper-reset"])[2]/li[@style="display: list-item;"]/label/input');
            $this->tester->retryClick('(//button[contains(@class,"btn_valider_agda")])[2]');
```
### Details

* Codeception version: tried with 3.4 and 4.0
* PHP Version: 7.3
* Operating System: Windows
* Installation type: Phar
* List of installed packages (`composer show`)
* Suite configuration: AcceptanceTest

```yml
# suite config
suites:
    acceptance:
        actor: AcceptanceTester
        path: .
        modules:
            enabled:
                - WebDriver:
                    url: ''
                    port: 9515
                    browser: chrome
                    wait: 5
                - \Helper\Acceptance
                - \Helper\ConfigHelper:
                    login_username: username
                    login_password: password
                        
        # add Codeception\Step\Retry trait to AcceptanceTester to enable retries
        step_decorators:
            - Codeception\Step\ConditionalAssertion
            - Codeception\Step\TryTo
            - Codeception\Step\Retry
                
extensions:
    enabled: [Codeception\Extension\RunFailed]

params: 
    - env

gherkin: []    

# additional paths
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs

settings:
    shuffle: false
    lint: true
    nom_client : ""
    prenom_client : ""
    genre_client : ""
    statut_client : "Particulier"
```
