### ISSUE TITLE
phpstan can't find support/helper classes

### ISSUE THREAD

**Issue by dragoonis** [Codeception/Codeception#5901]
#### What are you trying to achieve?
phpstan to autoload my `tests/_support classes`

#### What do you get instead?
phpstan saying class not found

> Provide console output if related. Use `-vvv` mode for more details.

> Provide test source code if related

```php
backend/tests/_support/ApiTester.php
class ApiTester extends \Codeception\Actor
```

tests/ap/MyFileCest.php
``` php
public function testStore(ApiTester $I) 
{
        $I->sendPOST(route('invoice_line.store')
}

```

### Details

codeception.yml
``` yaml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```

api.suite.yml
``` yaml
actor: ApiTester
modules:
    enabled:
        - Helper\Api
        - Helper\MaintainableEntity
        - Asserts
        - REST:
            url: /api/
            depends: Laravel5
        - Laravel5:
            environment_file: .env.testing
            run_database_migrations: false
            cleanup: false
extensions:
  enabled:
    - Codeception\Extension\RunFailed
    - DbResetter
    - ApiHeaderSetter
```

**Comment by ondrejmirtes** [comment]
Please always also add your `phpstan.neon` configuration. Anyway, this should help you https://phpstan.org/user-guide/autoloading, it has everything you need to know about autoloading.

**Comment by dragoonis** [comment]
@ondrejmirtes I'm using LaraStan, which has its own bootstrap process for Laravel.

As for my project:

```
includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:

    autoload_files:
        - vendor/autoload.php

    # The level 8 is the highest level
    level: 5

    ignoreErrors:
        - '#Unsafe usage of new static#'

    checkMissingIterableValueType: false
```
