### ISSUE TITLE
[Error] Call to a member function getHumanizedActionWithoutArguments() on null

### ISSUE THREAD

**Issue by jg-development** [Codeception/Codeception#5911]
#### What are you trying to achieve?
I want to run the tests with bdd and allure extension.
When I run the "codecept run" command I get the exception:
[Error] Call to a member function getHumanizedActionWithoutArguments() on null
This only happens when I use the bdd homepage.feature.
If I use a HomepageCest.php everything works fine:
```php
<?php

class HomepageCest
{
    public function homepage(AcceptanceTester $I)
    {
        $I->iAmOnPage('/');
    }
}
```
Does anybody have an idea what exactly is going wrong? I was looking around but did not found a solution.

Complete Output:
```bash
Codeception PHP Testing Framework v4.1.4
Powered by PHPUnit 8.5.4 by Sebastian Bergmann and contributors.
Running with seed: 


Acceptance Tests (2) -----------------------------------------------------------
⏺ Recording ⏺ step-by-step screenshots will be saved to /var/www/project/tests/_output/
Directory Format: record_5ead734223f9a_{filename}_{testname} ----
✔ HomepageCest: Homepage (10.56s)
E homepage: show homepage (0.00s)
--------------------------------------------------------------------------------


Time: 11.35 seconds, Memory: 16.00 MB

There was 1 error:

---------
1) homepage: show homepage
 Test  tests/acceptance/homepage.feature:show homepage
                                                                                  
  [Error] Call to a member function getHumanizedActionWithoutArguments() on null  
                                                                                  

Scenario Steps:


#1  /var/www/project/vendor/allure-framework/allure-codeception/src/Yandex/Allure/Codeception/AllureCodeception.php:409
#2  /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:264
#3  /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:239
#4  /var/www/project/vendor/symfony/event-dispatcher/EventDispatcher.php:73
Artifacts:

Png: /var/www/project/tests/_output/homepage.show.homepage.fail.png
Html: /var/www/project/tests/_output/homepage.show.homepage.fail.html

ERRORS!
Tests: 2, Assertions: 0, Errors: 1.
```
### Details

* Codeception version: 4.1.4
* allure-framework/allure-codeception: 1.4.3
* PHP Version: 7.2
* Operating System: ubuntu
* Installation type: Composer
* Suite configuration:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - Codeception\Extension\Recorder:
              delete_successful: false
        - Yandex\Allure\Codeception\AllureCodeception
    config:
        Yandex\Allure\Codeception\AllureCodeception:
            deletePreviousResults: true
            outputDirectory: allure-results
            ignoredAnnotations:
                - env
                - dataprovider
gherkin:
    contexts:
        default:
            - AcceptanceTester
```

acceptance.suite.yml
```yml
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
              url: https://develop.local/
              host: localhost
              browser: chrome
              window_size: false
              port: 9515
              capabilities:
                  chromeOptions:
                      args: ["--headless", "--no-sandbox", "--disable-gpu", "--disable-extensions", "--allow-running-insecure-content", "--ignore-certificate-errors"]
                      binary: "/usr/bin/google-chrome"
        - \Helper\Acceptance
env:
    staging:
        modules:
            config:
                WebDriver:
                    url: https://staging.local/

```

homepage.feature
```yml
@homepage
Feature: homepage

  Scenario: show homepage
      Given I am on page "/"
```
