### ISSUE TITLE
RunFailed extension with sub tests

### ISSUE THREAD

**Issue by roosht3** [Codeception/Codeception#5923]
#### What are you trying to achieve?
Trying to run this
```
 vendor/bin/codecept run --skip api --skip acceptance --no-interaction --no-exit
```
and get a failed file to `tests/_output`  directory

#### What do you get instead?
I don't get the failed test in `tests/_output` instead I get it from the last run module. For example the file is inside `Stock` moduke

Stock/tests/_output/failed with main failed 
```text
/Users/xxx/AdminTest.php:testItCanFindRegisteredAdmin
```

### Details

* Codeception version: 4.1
* PHP Version: 7.4
* Operating System: 
* Installation type: Composer
* Suite configuration: Multiple suite with multi application

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
params:
    - .env.testing
extensions:
    enabled: [Codeception\Extension\RunFailed]
coverage:
    enabled: true
    include: ['Modules/*']
include:
    - 'Modules/*'
bootstrap: _bootstrap.php

```
