### ISSUE TITLE
step_decorators TryTo / Retry are not generated in AcceptanceTesterActions.php if Quickstart is followed

### ISSUE THREAD

**Issue by rene-hermenau** [Codeception/Codeception#5935]
#### What are you trying to achieve?

Trying to initiate step_decorators Retry and TryTo

#### What do you get instead?

The methods are not generated at all in AcceptanceTesterActions.php
I was earlier updating from codeception 2.x to 4.x so I deleted all tests and composer packages to rebuild test suite from scratch by following quick guide instruction and executing:

composer require "codeception/codeception" --dev
php vendor/bin/codecept bootstrap

As a result, TryTo* methods are still undefined

A `codecept build` does not generate the missing methods, either

acceptance.suite.yml

```
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost/myapp
        - \Helper\Acceptance
    step_decorators:
        - \Codeception\Step\TryTo
        - \Codeception\Step\Retry
```

**Comment by rene-hermenau** [comment]
This is caused is a bug in the initial yml default template!

step_decorators: ~ 
must be on the root level in acceptance.suite.yml like this:

```
actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost/myapp1
        - \Helper\Acceptance
step_decorators:
    - \Codeception\Step\TryTo
    - \Codeception\Step\Retry
```
