### ISSUE TITLE
I can't override a single item in a list of values in YML

### ISSUE THREAD

**Issue by Luc45** [Codeception/Codeception#5961]
#### What are you trying to achieve?

I want to override a single item in a list of values in YML.

#### What do you get instead?

When overriding `codeception.dist.yml` with `codeception.yml`, I can only add to the list, not exclude or override the item.

Example, I want to remove **--headless**:

`codeception.dist.yml`:

```yml
modules:
    config:
        WPWebDriver:
            capabilities:
                chromeOptions:
                    args:
                        - "--disable-gpu"
                        - "--ignore-certificate-errors"
                        - "--headless"
```

`codeception.yml`

```yml
modules:
    config:
        WPWebDriver:
            capabilities:
                chromeOptions:
                    args:
                        - "--disable-gpu"
                        - "--ignore-certificate-errors"
```

I expected that the 'codeception.yml` would override `args` with new values. Instead, it just adds to it, something like:

```yml
modules:
    config:
        WPWebDriver:
            capabilities:
                chromeOptions:
                    args:
                        - "--disable-gpu"
                        - "--ignore-certificate-errors"
                        - "--headless"
                        - "--disable-gpu"
                        - "--ignore-certificate-errors"
```

I have tried to use a key/value pair list as well:

`codeception.dist.yml`

```yml
capabilities:
      chromeOptions:
           args:
               - "--disable-gpu"
               - "--ignore-certificate-errors"
              - headless: "--headless"
```

`codeception.yml`

```yml
capabilities:
    chromeOptions:
        args:
            - headless: ""
```

But I get an error: 

```
from invalid argument: cannot parse args
from invalid argument: each argument must be a string
```

Codeception v4.1.6

Any ideas?
Thanks!
