### ISSUE TITLE
Question: How to run the same acceptance tests against multiple start URLs?

### ISSUE THREAD

**Issue by elchenberg** [Codeception/Codeception#6009]
#### What are you trying to achieve?

I want to test if my app works with different PHP versions so I have test servers running for each of them (PHP 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, and 8.0). I am running acceptance tests using the PhpBrowser. My suites configuration looks like this:

```yml
suites:
    PHP 5.6 Acceptance: &acceptance-suites
        actor: AcceptanceTester
        path: .
        modules:
            enabled:
                - PhpBrowser:
                    url: http://php56
                - \Helper\Acceptance
        step_decorators:
            - Codeception\Step\ConditionalAssertion
            - Codeception\Step\TryTo
            - Codeception\Step\Retry
    PHP 7.0 Acceptance:
        <<: *acceptance-suites
        modules:
            enabled:
                - PhpBrowser:
                    url: http://php70
                - \Helper\Acceptance
    # [...]
    PHP 8.0 Acceptance:
        <<: *acceptance-suites
        modules:
            enabled:
                - PhpBrowser:
                    url: http://php80
                - \Helper\Acceptance
```

#### What do you get instead?

On the first glance my approach seems to be working pretty good:

```sh
codecept run
```

```
PHP 5.6 Acceptance Tests (1) ----------------------------------------------------------------------------
✔ SetupCest: Visit setup page (0.02s)
---------------------------------------------------------------------------------------------------------

PHP 7.0 Acceptance Tests (1) ----------------------------------------------------------------------------
✔ SetupCest: Visit setup page (0.01s)
---------------------------------------------------------------------------------------------------------

PHP 7.1 Acceptance Tests (1) ----------------------------------------------------------------------------
✔ SetupCest: Visit setup page (0.01s)
---------------------------------------------------------------------------------------------------------

PHP 7.2 Acceptance Tests (1) ----------------------------------------------------------------------------
✖ SetupCest: Visit setup page (0.01s)
---------------------------------------------------------------------------------------------------------

PHP 7.3 Acceptance Tests (1) ----------------------------------------------------------------------------
✖ SetupCest: Visit setup page (0.01s)
---------------------------------------------------------------------------------------------------------

PHP 7.4 Acceptance Tests (1) ----------------------------------------------------------------------------
✖ SetupCest: Visit setup page (0.01s)
---------------------------------------------------------------------------------------------------------

PHP 8.0 Acceptance Tests (1) ----------------------------------------------------------------------------
✖ SetupCest: Visit setup page (0.00s)
---------------------------------------------------------------------------------------------------------
```

But when I look at the error output I see multiple problems with the approach:

1. I don't know which suite generated this error report so I have to guess the PHP version that produced the error. (Of course I could run the suites individually to find out but running them all at once is very convienient.)
2. All the suites seem to use the same file paths for the artifacts.

```
1) SetupCest: Visit setup page
 Test  tests/SetupCest.php:visitSetupPage
 Step  Don't see in source "will throw an error"
 Fail  Failed asserting that  on page /setup.php
--> [page source snippet]
--> does not contain "will throw an error".

Scenario Steps:

 5. $I->dontSeeInSource("will throw an error") at tests/acceptance/SetupCest.php:10
 4. $I->dontSeeInSource("is deprecated") at tests/acceptance/SetupCest.php:9
 3. $I->dontSeeInSource("stack trace") at tests/acceptance/SetupCest.php:8
 2. $I->dontSeeInSource("fatal error") at tests/acceptance/SetupCest.php:7
 1. $I->amOnPage("/setup.php") at tests/acceptance/SetupCest.php:6

Artifacts:

Html: /var/www/html/tests/_output/SetupCest.visitSetupPage.fail.html
Response: /var/www/html/tests/_output/SetupCest.visitSetupPage.fail.html
```

So I was wondering: Is there a better approach? What is the best way to run the same acceptance tests against multiple start URLs?

### Details

* Codeception version: Codeception 4.1.8
* PHP Version: PHP 7.4.11 (cli)
* Operating System: Alpine Linux v3.12
* Installation type: Phar
* List of installed packages (`composer show`): none
* Suite configuration: see above
