### ISSUE TITLE
DB connection

### ISSUE THREAD

**Issue by vladginosyan12** [Codeception/Codeception#6011]
#### We have a Symfony project where codeception is installed.
We use Webdriver. We have two databases (dev and test)
How can we connect for test only TEST DB??

### Details

* Codeception version: ^4.0
* PHP Version: 7.4
* Operating System: Linux
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

//acceptance.suite.yml
```yml
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
              url: 'http://127.0.0.1:8000'
              window_size: false # disabled in ChromeDriver
              browser: chrome
              port: 9515
        - Symfony:
            app_path: 'src'
            environment: 'test'
            part:
             - ORM
             - services
        - Doctrine2:
            depends: Symfony
            cleanup: true
        - \App\Tests\Helper\Acceptance
        - Filesystem
```

//codeception.yml
```yml
namespace: App\Tests
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    lint: true
    shuffle: true
params:
    - .env.test
coverage:
    enabled: true
    include:
        - src/*
```
