### ISSUE TITLE
Disparity between Phalcon\Mvc\Model::find and UnitTester::seeInDatabase

### ISSUE THREAD

**Issue by Raghu-Kanchiraju** [Codeception/Codeception#6019]
#### What are you trying to achieve?
Call save on a model and assert that it is saved.

#### What do you get instead?
seeInDatabase is not working as expected.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Codeception PHP Testing Framework v4.1.8
Powered by PHPUnit 9.4.2 by Sebastian Bergmann and contributors.
Running with seed:


  [Connecting To Db] {"config":{"populate":true,"cleanup":true,"reconnect":false,"waitlock":0,"dump":"tests/_data/setup.sql","populator":null,"dsn":"mysql:host=es_mysql;dbname=test_db","user":"root","password":"","initial_queries":["create database if not exists test_db;","use test_db;"],"databases":{"test_db":{"dsn":"mysql:host=es_mysql;dbname=test_db","user":"root","password":""}}},"options":[]}
  [Db] Connected to default test_db
  [Connecting To Db] {"config":{"populate":false,"cleanup":false,"reconnect":false,"waitlock":0,"dump":null,"populator":null,"dsn":"mysql:host=es_mysql;dbname=test_db","user":"root","password":""},"options":[]}
  [Db] Connected to test_db test_db

Unit Tests (3) -------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Phalcon, Db, Asserts, \Helper\Unit
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- LocationTest: Connection to test db  [Database] Transaction started
✔ LocationTest: Connection to test db (0.07s)
  [Database] Transaction cancelled; all changes reverted.
- LocationTest: Number cst customer locations  [Database] Transaction started
  [Query] SELECT count(*) FROM `cst_customer_location`
✔ LocationTest: Number cst customer locations (0.04s)
  [Database] Transaction cancelled; all changes reverted.
- LocationTest: Save customer location  [Database] Transaction started
  [Query] SELECT count(*) FROM `cst_customer_location` WHERE `url_code` = ? AND `name` = ? AND `main_email` = ?
  [Parameters] ["urlcode","Location 1","main@email.server.com"]
✖ LocationTest: Save customer location (0.05s)
  [Database] Transaction cancelled; all changes reverted.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 00:49.095, Memory: 21.77 MB

There was 1 failure:

---------
1) LocationTest: Save customer location
 Test  tests/unit/LocationTest.php:testSaveCustomerLocation
No matching records found for criteria {"url_code":"urlcode","name":"Location 1","main_email":"main@email.server.com"} in table cst_customer_location
Failed asserting that 0 is greater than 0.
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:121
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:55
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/Assert.php:2344
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/Assert.php:478
/data/EmployStream/vendor/codeception/lib-asserts/src/Codeception/Util/Shared/InheritedAsserts.php:452
/data/EmployStream/vendor/codeception/module-db/src/Codeception/Module/Db.php:789
/data/EmployStream/vendor/codeception/codeception/src/Codeception/Step.php:268
/data/EmployStream/vendor/codeception/codeception/src/Codeception/Scenario.php:76
/data/EmployStream/tests/_support/_generated/UnitTesterActions.php:173
/data/EmployStream/tests/unit/LocationTest.php:64
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/TestCase.php:1536
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/TestCase.php:1142
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/TestResult.php:730
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/TestCase.php:883
/data/EmployStream/vendor/phpunit/phpunit/src/Framework/TestSuite.php:669
/data/EmployStream/vendor/codeception/phpunit-wrapper/src/Runner.php:117
/data/EmployStream/vendor/codeception/codeception/src/Codeception/SuiteManager.php:161
/data/EmployStream/vendor/codeception/codeception/src/Codeception/Codecept.php:208
/data/EmployStream/vendor/codeception/codeception/src/Codeception/Codecept.php:162
/data/EmployStream/vendor/codeception/codeception/src/Codeception/Command/Run.php:511
/data/EmployStream/vendor/codeception/codeception/src/Codeception/Command/Run.php:405
/data/EmployStream/vendor/symfony/console/Command/Command.php:258
/data/EmployStream/vendor/symfony/console/Application.php:920
/data/EmployStream/vendor/symfony/console/Application.php:266
/data/EmployStream/vendor/symfony/console/Application.php:142
/data/EmployStream/vendor/codeception/codeception/src/Codeception/Application.php:117
/data/EmployStream/vendor/codeception/codeception/app.php:46
/data/EmployStream/vendor/codeception/codeception/app.php:47
/data/EmployStream/vendor/codeception/codeception/codecept:7


FAILURES!
Tests: 3, Assertions: 2, Failures: 1.
  [Db] Disconnected from test_db
```
> Provide test source code if related

```php
        $cst = new \XX\Models\CustLocation();
        $saved = $cst->save($locparams);
        $locations = \XX\Models\CustLocation::find("main_email='".$email."'");
        $this->tester->assertEquals(1, count($locations));

        // this is not working
        $this->tester->seeInDatabase('cst_customer_location', [
            'main_email' => $email
        ]);
```
### Details

* Codeception version: 4.1.8
* PHP Version: 7.3.23
* Operating System: Debian GNU/Linux 10 (buster)
* Installation type: Composer
* Suite configuration:

```yml
actor: UnitTester
modules:
    enabled:
        - Phalcon:
            part: services
            bootstrap: 'api/app/config/bootstrap.php'
            cleanup: true
            savepoints: true
        - Db:
            dsn: 'mysql:host=es_mysql;dbname=test_db'
            user: 'root'
            password: ''
            dump: 'tests/_data/setup.sql'
            populate: true
            cleanup: true
            initial_queries:
              - 'create database if not exists test_db;'
              - 'use test_db;'
            databases:
                test_db:
                    dsn: 'mysql:host=es_mysql;dbname=test_db'
                    user: 'root'
                    password: ''
        - Asserts
        - \Helper\Unit
    step_decorators: ~
```
