### ISSUE TITLE
Argument 1 passed to SebastianBergmann\CodeCoverage\ProcessedCodeCoverageData::merge() must be an instance of SebastianBergmann\CodeCoverage\ProcessedCodeCoverageData

### ISSUE THREAD

**Issue by NeilJ247** [Codeception/Codeception#6042]
#### What are you trying to achieve?

Run code coverage with latest versions of codeception, phpunit and xdebug v3

#### What do you get instead?

An error when merging coverage data:

```
Fatal error: Uncaught TypeError: Argument 1 passed to SebastianBergmann\CodeCoverage\ProcessedCodeCoverageData::merge() must be an instance of SebastianBergmann\CodeCoverage\ProcessedCodeCoverageData, array given, called in /var/www/html/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 319 and defined in /var/www/html/vendor/phpunit/php-code-coverage/src/ProcessedCodeCoverageData.php on line 135




FATAL ERROR. TESTS NOT FINISHED.
Uncaught TypeError: Argument 1 passed to SebastianBergmann\CodeCoverage\ProcessedCodeCoverageData::merge() must be an instance of SebastianBergmann\CodeCoverage\ProcessedCodeCoverageData, array given, called in /var/www/html/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 319 and defined in /var/www/html/vendor/phpunit/php-code-coverage/src/ProcessedCodeCoverageData.php:135
Stack trace:
#0 /var/www/html/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(319): SebastianBergmann\CodeCoverage\ProcessedCodeCoverageData->merge(Array)
#1 /var/www/html/vendor/codeception/codeception/src/Codeception/Coverage/SuiteSubscriber.php(106): SebastianBergmann\CodeCoverage\CodeCoverage->merge(Object(SebastianBergmann\CodeCoverage\CodeCoverage))
#2 /var/www/html/vendor/codeception/codeception/src/Codeception/Coverage/Subscriber/LocalServer.php(126): Codeception\Coverage\SuiteSubscriber->mergeToPrint(Object(SebastianBergmann\CodeCoverage\CodeCoverage))
#3 /var/www/html/vendor/symfony/event-dispatcher/EventDispa 
in /var/www/html/vendor/phpunit/php-code-coverage/src/ProcessedCodeCoverageData.php:135

```
> Provide test source code if related

```php
<?php

//phpcs:ignore PSR1.Classes.ClassDeclaration.MissingNamespace
class ApiGetRequestToAllPhoneCodesCest
{
    public function tryApi(ApiTester $I)
    {
        $I->sendGET('/country-codes/phone');
        $I->seeResponseCodeIs(200);
        $I->canSeeResponseIsJson();
        $I->seeResponseContainsJson([
            'BD' => '880',
            'LA' => '856',
        ]);
    }
}
```

### Details

* Codeception version: 4.1.12
* PHP Version: 7.4
* Operating System: Linux Alpine
* Installation type: Composer
* List of installed packages: 
        "codeception/c3": "^2.6",
        "codeception/codeception": "^4.1",
        "codeception/module-asserts": "^1.3",
        "codeception/module-phpbrowser": "^1.0",
        "codeception/module-rest": "^1.2",
        "php-coveralls/php-coveralls": "^2.0",
        "phpunit/phpunit": "^9.4"
* Suite configuration:

```yml
paths:
    tests: tests
    output: var/_codeception/_output
    data: var/_codeception/_data
    support: var/_codeception/_support
actor_suffix: Tester
params:
    - .env
extensions:
    enabled:
        - Codeception\Extension\RunFailed
coverage:
    enabled: true
    include:
        - src/Application/*
        - src/Domain/*
settings:
    shuffle: false
    lint: true
```
