### ISSUE TITLE
Symfony - Unable to find the controller for path... - vendor route

### ISSUE THREAD

**Issue by thedomeffm** [Codeception/Codeception#6045]
I want to use Codeception with Symfony5.2.* for testing the API.

For authentication I am using https://github.com/lexik/LexikJWTAuthenticationBundle 
The route for authentication is defined in the `config/routes.yml`
```yml
# from here: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#configuration
api_login_check:
    path: /api/login_check
```
In my `tests/api/LoginUserCest.php`:
```php
public function login(ApiTester $I)
    {
        // I set the '/api' as url in api.suite.yml
        $I->sendPost('/login_check', [
            'email' => 'example@user.email',
            'password' => 'examplePassword!',
        ]);
        $I->seeResponseCodeIs(HttpCode::OK);
        // ....
    }
```
I get the following error:
`Unable to find the controller for path '/api/login_check'. The route is wrongly configured. (404 Not Found)`

* PHP Version: 7.4.*
* Operating System: Linux
* Installation type: Composer
* List of installed packages
 ```json
"require-dev": {
        "codeception/codeception": "^4.1",
        "codeception/module-doctrine2": "^1.1",
        "codeception/module-rest": "^1.2",
        "codeception/module-symfony": "^1.5",
        ....
    },
```
* API configuration: 
`tests/api.suite.yml`
```yml
actor: ApiTester
class_name: ApiTester
modules:
    enabled:
        - Symfony:
              app_path: 'src'
              environment: 'test'
        - REST:
              url: /api
              depends: Symfony
        - Doctrine2:
              depends: Symfony
        - \App\Tests\Helper\Api
```

`codeception.yml`
```yml
namespace: App\Tests
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
params:
    - .env

```

What need to be changed in my config that this "vendor" route work?

**Comment by thedomeffm** [comment]
Okey, it seems like "behavior" from lexic-jwt => https://github.com/chalasr/lexik-jwt-authentication-sandbox/issues/16

If I prefix my loginTest with `$I->haveHttpHeader('Content-Type', 'application/json');` than it works.

```php
    public function login(ApiTester $I)
    {
        $I->haveHttpHeader('Content-Type', 'application/json');
        $I->sendPost('/login', [
            'email' => 'example@user.email',
            'password' => 'exampl_password',
        ]);
        $I->seeResponseCodeIs(HttpCode::OK);
    }
```

So my new question is how can I configure Codeception with symfony (like documented here? https://codeception.com/docs/modules/REST#Example )
That the Content-Type is always json?

I can't find something with these settings here: https://codeception.com/docs/modules/Symfony 

This does **not** work:
```yml
# api.suite.yml
actor: ApiTester
class_name: ApiTester
modules:
    enabled:
        - Symfony:
              app_path: 'src'
              environment: 'test'
              headers:
                Content-Type: application/json
        - REST:
              url: /api
              depends: Symfony
              headers:
                  Content-Type: application/json
        - Doctrine2:
              depends: Symfony
        - \App\Tests\Helper\Api
```
