### ISSUE TITLE
Module `_after` methods should run in reverse order

### ISSUE THREAD

**Issue by WillemHoman** [Codeception/Codeception#6061]
#### What are you trying to achieve?
`ModuleA` depends on `ModuleB`.
In `A::_after()`  I want to use `ModuleB` to do some cleanup. 

#### What do you get instead?
`ModuleB::_after()` has already run and so is not in a usable state. 

### Details

* Codeception version:  3.1.2
* PHP Version: 7.4
* Operating System: osx
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - REST:
              depends: PhpBrowser
              part: Json
        - Asserts
        - ModuleB:
            depends:
              - REST
         - ModuleA:
            depends:
              - ModuleB
```
