### ISSUE TITLE
JSON-Type float does not match 0

### ISSUE THREAD

**Issue by amigian74** [Codeception/Codeception#6093]
I'm trying to test an API with JSON results. The datatype of the property to match is float and returns 0 for the current test. So the test fails because 0 ist not matched as float.

In my opinion 0 would be a valid float value.

```bash
1) DataPointsCest: Try get guest data points
 Test  tests\api\DataPointsCest.php:tryGetGuestDataPoints
 Step  See response matches json type {"STAppRun":{"run_st_app_adj_azimuth":"float","run_st_app_adj_elevation":"float","run_st_app_flags":"integer","run_st_app_last_midnight":"integer","run_st_app_mancnt":"integer","run_st_app_state":...}
 Fail  `run_st_app_adj_azimuth: 0` is of type `float`
```

### Details

* Codeception version: 4.1.15
* PHP Version:  7.2.25
* Operating System: Windows
* Installation type: Composer
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - Symfony:
            app_path: 'src'
            environment: 'test'
        - REST:
            url: http://localhost:8444
            depends: Symfony
            part: Json
```
