### ISSUE TITLE
Test file can't be matched

### ISSUE THREAD

**Issue by rwhite27** [Codeception/Codeception#6103]
#### What are you trying to achieve?

Trying to run API tests after released version 4.1.16.

#### What do you get instead?

Test file can't be matched when running API tests.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Codeception PHP Testing Framework v4.1.16
Powered by PHPUnit 9.2.6 by Sebastian Bergmann and contributors.

In Run.php line 545:

  Test file can't be matched

```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 4.1.16
* PHP Version: 7.4
* Operating System: Alpine 9.2.0
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
  enabled:
    - Asserts
    - Helper\Api
    - \Helper\Integration
    - REST:
        depends: Phalcon4

```

**Comment by Naktibalda** [comment]
How do you run tests?
Do you have any interesting path configuration in codeception.yaml file?

**Comment by tormit** [comment]
Same problem here. I haven't changed anything myself.

My codeception.yml:

```yml
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    # name of bootstrap that will be used
    # each bootstrap file should be
    # inside a suite directory.
```
