### ISSUE TITLE
Allow preserveGlobalState and runInSeparateProcess settings in acceptance.suite.yml?

### ISSUE THREAD

**Issue by BobRay** [Codeception/Codeception#6113]
#### What are you trying to achieve?

I'm trying to create a set of acceptance tests that can be run in one pass on different versions of the same platform to be tested. All tests for all platform versions run fine one at a time. The problem is the that there is a constant that has different values in different platform versions. So `codeception run test --env modx 2 --env modx3` runs the first env case fine, but crashes on the second one because the constant hasn't changed. 

I tried using preserveGlobalState and runInSeparateProcess annotations in the test file and using the PhpUnit style settings for those, but in all cases, the value from the first env case is used in all subsequent passes.

I think this may be because the constant is set in a file included by the _bootstrap file.  (I have separate _bootstrap files for each version, which are set in the env: section of acceptance.suite.yml). 

Would it be possible to have a way to set those two settings for PhpUnit in acceptance.suite.yml?

#### What do you get instead?

On the second environment, I get a fatal PHP error due to a failed include because the path set in the constant is wrong for the current version being tested. I also get a warning about trying to redefine the constant.

### Details

* Codeception version: Codeception 4.1.14
* PHP Version: 7.1.14
* Operating System: Windows 10

```yml
# paste suite config here
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.

actor: AcceptanceTester

bootstrap: _bootstrap.php

modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver
        - Asserts

    config:
        WebDriver:
           url: 'http://localhost/test/'
           browser: 'chrome'
           window_size: 'maximize'
           wait: 5

extensions:
    enabled:
        - Codeception\Extension\RunProcess:
            - echo "Launch Selenium in acceptance.suite.php"
            - java -jar c:/Users/BobRay/Downloads/Selenium/selenium-server-standalone-3.141.59.jar
            - echo "Launch Chrome driver in acceptance.suite.php"
            - C:/Users/BobRay/Downloads/selenium-drivers/chromedriver.exe

################################################################
# The code below will be ignored if no Environment is specified
################################################################

env:
    firefox:
        modules:
            config:
                WebDriver:
                    url: 'http://localhost/test/'
                    path: ''
                    browser: 'firefox'
                    window_size: 'maximize'
                    wait: 5
        extensions:
            enabled:
                - Codeception\Extension\RunProcess:
                    - echo "Launching Selenium Server in acceptance.suite.php"
                    - java -jar c:/Users/BobRay/Downloads/Selenium/selenium-server-standalone-3.141.59.jar
                    - echo "Launching geckodriver in acceptance.suite.php"
                    - C:/Users/BobRay/Downloads/selenium-drivers/geckodriver.exe

    chrome:
        modules:
            config:
                WebDriver:
                    url: 'http://localhost/test/'
                    browser: 'chrome'
                    window_size: 'maximize'
                    wait: 5
        extensions:
            enabled:
                - Codeception\Extension\RunProcess:
                    - echo "Launch Selenium server in acceptance.suite.yml"
                    - java -jar c:/Users/BobRay/Downloads/Selenium/selenium-server-standalone-3.141.59.jar
                    - echo "Launch Chrome driver in acceptance.suite.yml"
                    - C:/Users/BobRay/Downloads/selenium-drivers/chromedriver.exe

    modx2:
        bootstrap: _bootstrap2.php

        modules:
            config:
                WebDriver:
                    url: 'http://localhost/test/'

    modx3:
        bootstrap: _bootstrap3.php

        modules:
            config:
                WebDriver:
                    url: 'http://localhost/modx3/'

```
