### ISSUE TITLE
Functional test with ZF1 module failing

### ISSUE THREAD

**Issue by warmwaterkruik** [Codeception/Codeception#614]
I have been trying to get functional testing working for Zend Framework version 1.12 but no luck. In the console I get a message _1) Failed to perform actions and see result in TestWhutCept.php_

The acceptance test did pass though.

The various files have been configured according to the tutorial on codeception.

**log**

```
[2013-10-15 20:48:42] Codeception.ALERT: Undefined index: REQUEST_URI [] []
[2013-10-15 20:48:42] Codeception.INFO: # ERROR # [] []
[2013-10-15 20:48:42] Codeception.INFO: PASSED [] []
```

**TestWhutCept.php**

```
    <?php
    $I = new TestGuy($scenario);
$I->wantTo('perform actions and see result');
$I->amOnPage('/');
$I->seeElement('#login');
```

**functional.suite.yml**

```
        class_name: TestGuy
        modules:
            enabled: [ZF1, Filesystem, TestHelper]
        paths:
            tests: tests
            log: tests/_log
            data: tests/_data
            helpers: tests/_helpers
        settings:
            bootstrap: _bootstrap.php
            suite_class: \PHPUnit_Framework_TestSuite
            colors: false
            memory_limit: 1024M
            log: true
        modules:
            config:
                Db:
                    dsn: 'mysql:host=localhost;dbname=test'
                    user: 'root'
                    password: ''
                    dump: tests/_data/dump.sql
```
