### ISSUE TITLE
How to cover codecoverage in modules.

### ISSUE THREAD

**Issue by terabytesoftw** [Codeception/Codeception#6163]
#### What are you trying to achieve?

I want to cover the tests of the modules with codecoverage. 

Directory structure:
    - app ---> main application
    - vendor/yii-extension/simple-view-bulma --> module to test codeception.

#### What do you get instead?

vendor/bin/codecept run -c vendor/yii-extension/simple-view-bulma --coverage-html -vvv

> Provide console output if related. Use `-vvv` mode for more details.

```bash
$ vendor/bin/codecept run -c vendor/yii-extension/simple-view-bulma --coverage-html -vvv
Codeception PHP Testing Framework v4.1.20
Powered by PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Simple\View\Bulma\Tests.acceptance Tests (1) ---------------------------------------------------------------------------
Modules: PhpBrowser, \Simple\View\Bulma\Tests\Helper\Acceptance
------------------------------------------------------------------------------------------------------------------------
PageHomeCest: See page index.
Signature: Simple\View\Bulma\Tests\Acceptance\PageHomeCest:testHomePage
Test: tests\acceptance\PageHomeCest.php:testHomePage
Scenario --
  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testHomePage%22%2C%22CodeCoverage_Suite%22%3A%22acceptance%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=localhost; path=/; httponly"]
 I am on page "/"
  [Request Headers] []
  [Page] /
  [Response] 200
  [Request Cookies] {"CODECEPTION_CODECOVERAGE":"{"CodeCoverage":"testHomePage","CodeCoverage_Suite":"acceptance","CodeCoverage_Config":null}"}
  [Response Headers] {"Host":["localhost:8080"],"Date":["Fri, 16 Apr 2021 14:03:10 GMT"],"Connection":["close"],"Set-Cookie":["PHPSESSID=pjuurtk99btm3phe099a3dc91dkfmp64tu2fe2t9oud12n81; Domain=localhost; Path=/; HttpOnly; SameSite=Lax"],"Content-Type":["text/html; charset=UTF-8"],"Content-Length":["4145"]}
  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testHomePage%22%2C%22CodeCoverage_Suite%22%3A%22acceptance%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=localhost; path=/; httponly","PHPSESSID=pjuurtk99btm3phe099a3dc91dkfmp64tu2fe2t9oud12n81; domain=localhost; path=/; httponly; samesite=Lax"]
 I see "Hello World"
  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testHomePage%22%2C%22CodeCoverage_Suite%22%3A%22acceptance%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=localhost; path=/; httponly","PHPSESSID=pjuurtk99btm3phe099a3dc91dkfmp64tu2fe2t9oud12n81; domain=localhost; path=/; httponly; samesite=Lax"]
 PASSED

------------------------------------------------------------------------------------------------------------------------


Time: 00:03.230, Memory: 14.00 MB

OK (1 test, 1 assertion)


Code Coverage Report:
  2021-04-16 14:03:12

 Summary:
  Classes:  0.00% (0/4)
  Methods:  0.00% (0/7)
  Lines:    0.00% (0/14)

Remote CodeCoverage reports are not printed to console

HTML report generated in coverage
```
> Provide test source code if related

```php
<?php

declare(strict_types=1);

namespace Simple\View\Bulma\Tests\Acceptance;

use Simple\View\Bulma\Tests\AcceptanceTester;

final class PageHomeCest
{
    public function testHomePage(AcceptanceTester $I): void
    {
        $I->amOnPage('/');
        $I->wantTo('see page index.');
        $I->see('Hello World');
    }
}
```
### Details

* Codeception version: 4.1.20
* PHP Version: 7.4.16
* Operating System: windows-10
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration: Acceptance

```yml
namespace: Simple\View\Bulma\Tests
paths:
    tests: tests
    output: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    suite_class: \PHPUnit_Framework_TestSuite
    memory_limit: 1024M
    colors: true
coverage:
    enabled: true
    remote: true
    include:
        - src/*
```
