### ISSUE TITLE
seeResponseMatchesJsonType issue on multiple arrays of arrays

### ISSUE THREAD

**Issue by MitakaMitaka** [Codeception/Codeception#6245]
#### What are you trying to achieve?
Trying to use seeResponseMatchesJsonType on a response from multiple arrays of arrays

#### What do you get instead?
After several iterations I get an error 

```bash
1) testCest: Test Get the SUSPENDED Venues!
 Test  tests/api/testCest.php:suspendedVenues
 Step  See response matches json type {"businessHourID":"integer","workingDay":"string","specialHourDate":"string|null","fromTime":"string|null","toTime":"string|null","isClosed":"boolean"},"$..businessHours[22]"
 Fail  Key `businessHourID` doesn't exist in []
```
> Provide test source code if related
The code I use is
```php
// businessHours array from the venue payload
    public static $businessHoursArrayResponse = [
        'businessHourID'  => 'integer',
        'workingDay'      => 'string',
        'specialHourDate' => 'string|null',
        'fromTime'        => 'string|null',
        'toTime'          => 'string|null',
        'isClosed'        => 'boolean'
    ];
...
$businessHoursArray = $I->grabDataFromResponseByJsonPath('$..businessHours.*');
        for ($i=0; $i < count($businessHoursArray); $i++){
            if (!empty($businessHoursArray[$i])) {
                $I->seeResponseMatchesJsonType(self::$businessHoursArrayResponse, '$..businessHours['.$i.']');
            }
        }
```
### Details

* Codeception version: v4.1.20
* PHP Version: 7.2.24
* Operating System: Ubuntu
* Installation type: Phar 
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
  enabled:
    - Asserts
    - Helper\Api
    - REST:
        depends: PhpBrowser
        url: '****'
        part: Json
        curl:
          CURLOPT_RETURNTRANSFER: true
```
