### ISSUE TITLE
Env of db for fixtures

### ISSUE THREAD

**Issue by andrew-svirin** [Codeception/Codeception#6255]
I can not use specified env when loading fixtures for tests
Followed instructions here https://codeception.com/docs/12-ParallelExecution

My Cest: (tests/functional/suite2/Author1Cest.php)
```php
class Author1Cest
{
    public function _fixtures()
    {
        return [
            'author' => [
                'class' => tests\fixtures\AuthorFixture::class,
            ],
            'book' => [
                'class' => tests\fixtures\BookFixture::class,
            ],
        ];
    }

    public function testView(FunctionalTester $I, Scenario $scenario, Example $example)
    {
    }
}
```

Suite yml (functional.suite.yml)
```php
class_name: FunctionalTester
modules:
  enabled:
    - Asserts
    - Cli
    - Yii2
    - Db:
        dsn: 'mysql:host=mysql;port=3306;dbname=test_performance_test'
        user: 'test'
        password: 'test'
        populate: false
        cleanup: false
extensions:
  enabled:
    - Codeception\Task\Extension\FailedTestsReporter
env:
  env_1:
    modules:
      config:
        Db:
          dsn: 'mysql:host=mysql;port=3306;dbname=test_performance_test'
  env_2:
    modules:
      config:
        Db:
          dsn: 'mysql:host=mysql-clone-1;port=3306;dbname=test_performance_test'
```

Command running:
```
$ ./vendor/bin/codecept run tests/functional/suite2/Author1Cest.php --env=env_2
```

And in the result fixtures loading into dsn: `mysql:host=mysql;port=3306;dbname=test_performance_test` but expcted to use dsn:  'mysql:host=mysql-clone-1;port=3306;dbname=test_performance_test'

Please help to find the problem? 
May be I need to call reconfigure? But then how will be with parallel testing.

**Comment by andrew-svirin** [comment]
Found the problem:

Here is solution:
```yml
class_name: FunctionalTester
modules:
  enabled:
    - \Helper\YiiHelper
    - Asserts
    - Cli
    - Yii2
extensions:
  enabled:
    - Codeception\Task\Extension\FailedTestsReporter
env:
  env1:
    modules:
      config:
        Yii2:
          configFile: 'src/config/test.php'
  env2:
    modules:
      config:
        Yii2:
          configFile: 'src/config/test_clone_1.php'
```
