### ISSUE TITLE
sttrange behaviour using loadFixtures

### ISSUE THREAD

**Issue by khumme** [Codeception/Codeception#6271]
#### Existing records in the database are not deleted. While executing the doctrine's method

```bash
php bin/console doctrine:fixtures:load
```
is clearing the table as expected.

Output of the test:

```bash
App\Tests.integration Tests (1) -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Asserts, Symfony, Doctrine2, \App\Tests\Helper\Integration
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
- UserTest: Saving a user in database
  [Database] Transaction started
✔ UserTest: Saving a user in database (0.13s)
  [Database] Transaction cancelled; all changes reverted.
```
The very simple code:

```php
public function testSavingAUserInDatabase()
{
    $this->tester->loadFixtures(UserFixtures::class, false);

    $this->assertEquals(1, $this->tester->grabNumRecords(User::class));
}
```

The strange thing, besides the failing record deletion is, that the above posted test will always be green, although I have multiple records in the related table. But if I make another test like 

```php
public function testHavingOnlyOneUserInDatabase()
{
    $this->assertEquals(1, $this->tester->grabNumRecords(User::class));
}
```

this test fails with the message

```bash
1) UserTest: Having only one user in database
 Test  tests/integration/UserTest.php:testHavingOnlyOneUserInDatabase
Failed asserting that 2 matches expected 1.
```

The very simple code:

### Details

* Codeception version: 4.1.22
* PHP Version: 8.0
* Operating System: MacOS
* Installation type: composer

* Suite configuration:

```yml
actor: IntegrationTester
modules:
    enabled:
        - Asserts
        - Symfony:
            app_path: 'src'
            environment: 'test'
            mailer: 'symfony_mailer'
        - Doctrine2:
            depends: Symfony
        - \App\Tests\Helper\Integration
```

I guess that I'm just making a very simple mistake, but I can't figure it out.
