### ISSUE TITLE
Group Filter by file not working

### ISSUE THREAD

**Issue by DanielHansmannAldi** [Codeception/Codeception#6304]
#### What are you trying to achieve?

I want to run only tests from a group file

#### What do you get instead?

Running 
```bash
/data/vendor/bin/codecept run -c /data/codeception.cluster-acceptance.yml --group stage_2_1 --xml /data/tests/_log/result_stage_2_1.xml
```

with 20 files:
 ```bash
╰─$ ls /data/tests/_data/paracept/
stage_2_1   stage_2_11  stage_2_13  stage_2_15  stage_2_17  stage_2_19  stage_2_20  stage_2_4  stage_2_6  stage_2_8
stage_2_10  stage_2_12  stage_2_14  stage_2_16  stage_2_18  stage_2_2   stage_2_3   stage_2_5  stage_2_7  stage_2_9
 ```
with this tests in stage_2_1:
  ```bash
cat /data/tests/_data/paracept/stage_2_1
tests/PyzTest/Acceptance/EndpointValidation/CatalogSearchProductOffers/Scenarios/CatalogSearchProductOffersCest.php:checkResponseStructure
tests/PyzTest/Acceptance/EndpointValidation/CatalogSearchProductOffers/Scenarios/CatalogSearchProductOffersCest.php:checkResponseStructure0
tests/PyzTest/Acceptance/EndpointValidation/CatalogSearchProductOffers/Scenarios/CatalogSearchProductOffersCest.php:checkResponseStructure1
tests/PyzTest/Acceptance/EndpointValidation/CatalogSearchProductOffers/Scenarios/CatalogSearchProductOffersCest.php:checkResponseStructure2
tests/PyzTest/Acceptance/EndpointValidation/CatalogSearchProductOffers/Scenarios/CatalogSearchProductOffersCest.php:checkResponseStructure3
  ```
I would expect to only run this 5 tests. Right?
 
BUT, it is running ALL tests:
   ```bash
✔ CatalogSearchProductOffersCest: Check response structure (8.38s)
✔ CatalogSearchProductOffersCest: Check response structure0 (6.93s)
✔ CatalogSearchProductOffersCest: Check response structure1 (9.72s)
✔ CatalogSearchProductOffersCest: Check response structure2 (7.48s)
✔ CatalogSearchProductOffersCest: Check response structure3 (7.75s)
✔ CatalogSearchProductOffersCest: Check response structure4 (7.11s)
✔ CatalogSearchProductOffersCest: Check response structure5 (5.08s)
...
  ```
### Details

* Codeception version: 4.1.27
* PHP Version: 7.4.20 
* Operating System: linux
* Installation type: Composer 
* Suite configuration:

```yml
namespace: PyzTest
actor: Tester

include:
    - tests/PyzTest/Acceptance/*

groups:
    stage_* tests/_data/paracept/stage_*

paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs

settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true

extensions:
    enabled:
        - \PyzTest\Helper\SprintReviewReporter
        - \SprykerTest\Shared\Testify\Helper\WebDriverHelper
        - Codeception\Extension\Recorder:
              delete_successful: true
    config:
        PhpBrowser:
            curl:
                CURLOPT_TIMEOUT: 300
        \SprykerTest\Shared\Testify\Helper\WebDriverHelper:
            loadImages: true
            diskCache: true
            remote-enable: "%SPRYKER_TESTING_ENABLED%"
            host: "%SPRYKER_TEST_WEB_DRIVER_HOST%"
            browser: "chrome"
            capabilities:
                "goog:chromeOptions":
                    args: [ "--headless", "--no-sandbox", "--disable-dev-shm-usage", "--no-proxy-server", "--proxy-server='direct://'", "--proxy-bypass-list=*" ]
                    binary: "%SPRYKER_TEST_BROWSER_BIN%"

params:
    - tests/default.yml
    - env


```

**Comment by janmaghuyop** [comment]
Hi @DanielHansmannAldi, did you somehow resolve this issue? I'm also running the tests by groups and for some reason only paracept_1 is working, not paracept_2 and so forth.

**Comment by raymon2683** [comment]
Hi,
I'm also facing the same issue, all tests get executed irrespective of the order given.
**Details**
    Codeception version: 4.1.31
    PHP Version: 7.2.5
    Operating System: Linux
    Installation type: Composer 2.2.10
   Framework: Symfony 4.4
    Suite configuration:
```
actor: AcceptanceTester
error_level: "E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_USER_DEPRECATED"
groups: 
  admin: tests/_data/admin.txt
  user_1: tests/_data/user_1.txt
modules: 
  docker_chrome: 
    modules: 
      config: 
        WebDriver: 
          browser: chrome
          capabilities: 
            chromeOptions: 
              args: 
                - "--proxy-server='direct://'"
                - "--proxy-bypass-list=*"
              prefs: 
                browser.set_download_behavior: 
                  behavior: allow
                download.default_directory: /downloads
                download.directory_upgrade: true
                download.prompt_for_download: false
            unexpectedAlertBehaviour: accept
          host: app_chrome
          log_js_errors: true
          port: 4444
          url: "http://app_nginx.local/"
  docker_chrome_headless: 
    modules: 
      config: 
        WebDriver: 
          browser: chrome
          capabilities: 
            chromeOptions: 
              args: 
                - "--headless"
                - "--ignore-certificate-errors"
                - "--allow-running-insecure-content"
                - "--disable-gpu"
                - "--no-sandbox"
                - "--disable-setuid-sandbox"
                - "--disable-web-security"
                - "--proxy-server='direct://'"
                - "--proxy-bypass-list=*"
                - "--whitelisted-ips"
                - "--disable-extensions"
              prefs: 
                browser.set_download_behavior: 
                  behavior: allow
                download.default_directory: /downloads
                download.directory_upgrade: true
                download.prompt_for_download: false
            unexpectedAlertBehaviour: accept
          host: app_chrome
          log_js_errors: true
          port: 4444
          url: "http://app_nginx.local/"
  enabled: 
    - 
      WebDriver: 
        browser: chrome
        clear_cookies: false
        host: app_chrome
        http_proxy: ""
        port: 4444
        url: "http://app_nginx.local/"
        window_size: 1400x900
    - \Helper\Acceptance
    - \Helper\Select2
    - 
      Symfony: 
        app_path: src
        part: SERVICES
    - 
      Doctrine2: 
        depends: Symfony
  extensions: 
    config: 
      Codeception\Extension\Recorder: 
        delete_orphaned: true
        delete_successful: true
  step_decorators: ~
```
