### ISSUE TITLE
webdriver does not reset session (between suits)

### ISSUE THREAD

**Issue by oliwier-insided** [Codeception/Codeception#632]
I have 2 simple acceptance tests:

1) log in
2) password reminder

Unless I implicitly reset the session, eg:
$I->executeInSelenium(function(\WebDriver $webdriver) { $webdriver->manage()->deleteAllCookies(); });

2nd test is not passing because the user is still logged in.

While I am here:
How do I access SUT or the Webguy inside the Cest type test in the methods: _after() and _before() ?

Here is my WebDriver config:

```
WebDriver:
  url: 'http://at-forum.local'
  browser: firefox
  wait: 1
  cleanSession: true                              # I was just desperately trying everything
  ensureCleanSession: true                    # I was just desperately trying everything
  capabilities:      
    unexpectedAlertBehaviour: 'accept'
    cleanSession: true                            # I was just desperately trying everything
    ensureCleanSession: true                 # I was just desperately trying everything
```
