### ISSUE TITLE
Error in run test: Expecting function (T_FUNCTION) or const (T_CONST) incodeception/stub/src/Test/Feature/Stub.php

### ISSUE THREAD

**Issue by sanchezzzhak** [Codeception/Codeception#6326]
#### What are you trying to achieve?
I have tests that used to work, but not now for 7.3

https://github.com/sanchezzzhak/kak-clickhouse/runs/4852645767?check_suite_focus=true

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
./vendor/bin/codecept run
  shell: /usr/bin/bash -e {0}
PHP 7.3.33-1+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Nov 19 2021 06:25:05) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.33-1+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
PHP Parse error:  syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /home/runner/work/kak-clickhouse/kak-clickhouse/vendor/codeception/stub/src/Test/Feature/Stub.php on line 31
Error: Process completed with exit code 255.
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: Installing codeception/codeception (4.1.28): Extracting archive
* PHP Version: PHP 7.3.33-1+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Nov 19 2021 06:25:05) ( NTS )
* Operating System:
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: Tester
paths:
  tests: tests
  log: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
settings:
  bootstrap: _bootstrap.php
  colors: false
  memory_limit: 1024M
extensions:
  enabled:
    - Codeception\Extension\RunFailed
modules:
  config:
    Yii2:
      configFile: 'tests/_config/unit.php'
```

codeception which version should I use to make everything work?
