### ISSUE TITLE
Using "class:" named parameter in $this->make() yields exception and obscure error message

### ISSUE THREAD

**Issue by lcdennison** [Codeception/Codeception#6333]
Create this unit test using the named parameter `class:` before the class name (choice of DateTime is abitrary/irrelevant). 

```php
<?php
declare(strict_types=1);

class TransTest extends \Codeception\TestCase\Test {
    public function testSomeMethod(): void {
           $someObject = $this->make(class: DateTime::class);
    }
}
```
Try to run the test. You'll get an error `Class " " does not exist`. If you remove the `class:` named parameter, the test will execute as expected without error (assuming proper test content).

I had to dig into the Codeception source to find out what was happening because that error doesn't tell me much. The problem seems to be in the loop referenced below. I think Codeception is incorrectly interpreting that `class:` named parameter as a class definition and adding an empty space to the list of classes to be tested, which obviously results in an error.
https://github.com/Codeception/Codeception/blob/8a18c7454cf66414b0f15d4d00267708cd6900ca/src/Codeception/Lib/Parser.php#L155-L170

The problem is easily solved by removing the named parameter (I just have a habit of declaring the names), but I'd recommend that a well-positioned note (I didn't see any) be added to the documentation until this can be fixed. I wasted a lot of time trying to understand what I was doing wrong, which ended up being nothing. Hopefully this issue will help someone else avoid the time sink.

### Details

* Codeception version: 4.1.28
* PHP Version: 8.0.14
* Operating System:  WSL: Ubuntu 20.04
* Installation type: Composer

```yml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests.

actor: UnitTester
modules:
    enabled:
        - Asserts
        - \Helper\Unit
    step_decorators: ~
```
