### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by rackycz** [Codeception/Codeception#6358]
I believe that documentation contains one mistake which does not alow people to run acceptance tests.

Check this URL: https://codeception.com/docs/modules/WebDriver#Headless-Chrome-Browser
... section named "Headless Chrome Browser"

There is an example of YAML configuration which does not work and ends with error:

```
[Codeception\Exception\ConfigurationException]
Error loading Yaml config from `/var/www/public/protected/tests/acceptance.suite.yml`        
A colon cannot be used in an unquoted mapping value at line 42 (near "    chromeOptions:"). 
```

I believe there is incorrect indentation before "capabilities:". Things started to work when I used the same indentation as for "browser:"

Working example:

```
actor: AcceptanceTester
modules:
  enabled:
    - WebDriver:
        url: 'http://localhost/'
        browser: chrome
        capabilities:
          chromeOptions:
            args: ["--headless", "--disable-gpu"]
    - \Helper\Acceptance
```
   
YAML seems to be extremely tricky in these situations.
