### ISSUE TITLE
Module could not be found

### ISSUE THREAD

**Issue by mbolisov** [Codeception/Codeception#6366]
i have a modules in root _support/src-codeception/Module
![image](https://user-images.githubusercontent.com/46170579/154926853-018ac68c-ff6d-4551-b6dc-d52098008000.png)

composer.json : 
```
    "autoload-dev": {
        "psr-4": {
            "Codeception\\": "tests/_support/src-codeception"
        }
    }
```

suite : 
```
actor: ApiTester
modules:
  enabled:
    - Asserts
    - LaravelDataBaseModule:
        dsn: '%dsn'
        user: '%user'
        password: '%password'
    - Auth:
        depends: PhpBrowser
```

then i run php composer.phar build and i have this:

```
In ModuleContainer.php line 117:
                                                              
  Module LaravelDataBaseModule could not be found and loaded  
```

why codeception cant find this module?
