### ISSUE TITLE
[5.0-RC1] Injected Int typed parameter stop test execution

### ISSUE THREAD

**Issue by simonberger** [Codeception/Codeception#6408]
Codeception Version: 5.0-RC1
PHP: 8.1

I tested  the newest version of Codeception 5 and hit a PHP 8.1 deprecation resulting in a test crash.
We inject some parameters into the `codeception.yml` config

```yml
modules:
  config:
    - Redis:
        host: '%redis.host%'
        port: '%redis.port%'
```

The port is an int value and this creates a deprecation here:

https://github.com/Codeception/Codeception/blob/5.0/src/Codeception/Util/Template.php#L80

A cast to string would be an easy change but not sure if this is always correct. Likely the output of Codeception 4 was already converted to a string but I did not check it.
