### ISSUE TITLE
Improve docs for environments in acceptance tests

### ISSUE THREAD

**Issue by ThomasLandauer** [Codeception/Codeception#6444]
I've set up an environment (https://codeception.com/docs/07-AdvancedUsage#Environments) for chrome like this:
```yaml
modules:
    enabled:
        - WebDriver:
            browser: firefox
            path: '' # Required for Firefox to start at all
env:
    chrome:
        modules:
            config:
                WebDriver:
                    browser: chrome
```
Problem: Chrome isn't starting, due to the `path:` key. (I was assuming that the `env` key is overriding the entire `-WebDriver:` key, while in fact it's augmenting it.)
Conclusion: If you want to set up an environment for each browser, you cannot use the config as shown in the docs (one browser as default, the second as `env`), but you need another setup:
* Thin default (probably just `url:`)
* Two `env`s (one for each browser)

Which means that you need to pass the `--env` command line parameter every time you run Codeception.

Right?

If yes, I'd change the docs in that direction.
