### ISSUE TITLE
Group filter by files execution order not working

### ISSUE THREAD

**Issue by raymon2683** [Codeception/Codeception#6445]
#### What are you trying to achieve?
Execute multiple tests according to the group files defined order and group filter. This issue may be similar to #6304   
#### What do you get instead?
Running  
```bash 
codecept run -g admin -g cpc 
```
with the following files in the _data:
```bash
  |-_data
  |  |-admin.txt
  |  |-cpc.txt
```
This is the content of the files:  
```bash
cat ./_data/admin.txt
tests/acceptance/A_AdminCest.php
tests/acceptance/ActivitiesCest.php
tests/acceptance/TrainingCest.php
tests/acceptance/UserInfoCest.php

cat ./_data/cpc.txt
tests/acceptance/A_CpcCest.php
```
Output result:
```php
Codeception PHP Testing Framework v4.1.31 https://helpukrainewin.org
Powered by PHPUnit 8.5.26 #StandWithUkraine
[Groups] admin, cpc

Acceptance Tests (75) --------------------------------------
Testing acceptance
✔ A_AdminCest: Test 1(0.80s)
✔ A_AdminCest: Test 2 (1.53s)
✔ A_AdminCest: Test 3 (2.36s)
✔ A_AdminCest: Test 4 (6.07s)
✔ A_AdminCest: Test 5 (4.29s)
✔ A_CpcCest: Test 1 (0.31s)
✔ A_CpcCest: Test 2 (0.30s)
✔ A_CpcCest: Test 3 (0.30s)
✔ A_CpcCest: Test 4 (0.31s)
# All others tests
✖ ActivitiesCest: ...
✖ TrainingCest: ...
✖ UserInfoCest: ...
```
I was expected the following output and execution order based on the group test definition and not alphabetically -[cf. doc](https://codeception.com/docs/07-AdvancedUsage#group-files):  

```php 
Codeception PHP Testing Framework v4.1.31 https://helpukrainewin.org
Powered by PHPUnit 8.5.26 #StandWithUkraine
[Groups] admin, cpc

Acceptance Tests (75) --------------------------------------
Testing acceptance
✔ A_AdminCest: Test 1(0.80s)
✔ A_AdminCest: Test 2 (1.53s)
✔ A_AdminCest: Test 3 (2.36s)
✔ A_AdminCest: Test 4 (6.07s)
✔ A_AdminCest: Test 5 (4.29s)
✔ ActivitiesCest: ...
✔ TrainingCest: ...
✔ UserInfoCest: ...
✔ A_CpcCest: Test 1 (0.31s)
✔ A_CpcCest: Test 2 (0.30s)
✔ A_CpcCest: Test 3 (0.30s)
✔ A_CpcCest: Test 4 (0.31s)

```

### Details

* Codeception version: 4.1.31
* PHP Version: 7.2.5
* Operating System: Linux
* Installation type: Composer 2.2.10
* List of installed packages (`composer show`): [composer.txt](https://github.com/Codeception/Codeception/files/8561827/composer.txt)
* Suite configuration:
codeception.yml
```yml
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
extensions:
  enabled:
    - Codeception\Extension\RunFailed
bootstrap: /srv/app/tests/bootstrap.php
coverage:
  enabled: true
  low_limit: 50
  high_limit: 80
  show_uncovered: true
  include:
    - src/*.php
  exclude:
    - var/*
    - src/DataFixtures
    - src/Factory
    - src/Purger
  work_dir: /srv/app
  cookie_domain: app_nginx.local
```
Acceptance test suite config:
```yaml 
actor: AcceptanceTester
error_level: "E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_USER_DEPRECATED"
groups: 
  admin: tests/_data/admin.txt
  cpc: tests/_data/cpc.txt
modules: 
  docker_chrome: 
    modules: 
      config: 
        WebDriver: 
          browser: chrome
          capabilities: 
            chromeOptions: 
              args: 
                - "--proxy-server='direct://'"
                - "--proxy-bypass-list=*"
              prefs: 
                browser.set_download_behavior: 
                  behavior: allow
                download.default_directory: /downloads
                download.directory_upgrade: true
                download.prompt_for_download: false
            unexpectedAlertBehaviour: accept
          host: app_chrome
          log_js_errors: true
          port: 4444
          url: "http://app_nginx.local/"
  docker_chrome_headless: 
    modules: 
      config: 
        WebDriver: 
          browser: chrome
          capabilities: 
            chromeOptions: 
              args: 
                - "--headless"
                - "--ignore-certificate-errors"
                - "--allow-running-insecure-content"
                - "--disable-gpu"
                - "--no-sandbox"
                - "--disable-setuid-sandbox"
                - "--disable-web-security"
                - "--proxy-server='direct://'"
                - "--proxy-bypass-list=*"
                - "--whitelisted-ips"
                - "--disable-extensions"
              prefs: 
                browser.set_download_behavior: 
                  behavior: allow
                download.default_directory: /downloads
                download.directory_upgrade: true
                download.prompt_for_download: false
            unexpectedAlertBehaviour: accept
          host: app_chrome
          log_js_errors: true
          port: 4444
          url: "http://app_nginx.local/"
  enabled: 
    - 
      WebDriver: 
        browser: chrome
        clear_cookies: false
        host: app_chrome
        http_proxy: ""
        port: 4444
        url: "http://app_nginx.local/"
        window_size: 1400x900
    - \Helper\Acceptance
    - \Helper\Select2
    - 
      Symfony: 
        app_path: src
        part: SERVICES
    - 
      Doctrine2: 
        depends: Symfony
  extensions: 
    config: 
      Codeception\Extension\Recorder: 
        delete_orphaned: true
        delete_successful: true
  step_decorators: ~
```
