### ISSUE TITLE
Using PhpBrowser and WebDriver in different suites does not work

### ISSUE THREAD

**Issue by JanisE** [Codeception/Codeception#6467]
#### What are you trying to achieve?

I'm trying to use PhpBrowser for some acceptance tests (including checking HTTP response status, which is absent in WebDriver), and use WebDriver for other acceptance tests.

#### What do you get instead?

These two work all right separately:
```bash
./bin/codecept.phar run acceptance_statuses
./bin/codecept.phar run acceptance_user_interaction
```

If I running them together by:
```bash
./bin/codecept.phar run
```

the `acceptance_statuses` suite is executed all right, but the `acceptance_user_interaction` ends with an error:
>  [RuntimeException] Call to undefined method AcceptanceTester::waitForElement

Apparently, Codeception is trying to use PhpBrowser, which does not have `waitForElement` method, also for the `acceptance_user_interaction` suite.

### Details

* Codeception version: 4.1.31
* PHP Version: 7.4.3
* Operating System: Linux Mint 20.1
* Installation type: Phar
* Suite configuration:

```yml
suites:
  # PhpBrowser for checking HTTP statuses.
  acceptance_statuses:
    actor: AcceptanceTester
    path: ./acceptance_statuses
    modules:
      enabled:
        - PhpBrowser:
            url: https://localdev.lv
        - \Helper\Acceptance

    # add Codeception\Step\Retry trait to AcceptanceTester to enable retries
    step_decorators:
      - Codeception\Step\ConditionalAssertion
      - Codeception\Step\TryTo
      - Codeception\Step\Retry

  # Selenium for checking more sophisticated user interaction, but lacking HTTP status checks.
  acceptance_user_interaction:
    actor: AcceptanceTester
    path: ./acceptance_user_interaction
    modules:
      enabled:
        - WebDriver:
            url: https://localdev.lv
            browser: chrome
        - \Helper\Acceptance

    # add Codeception\Step\Retry trait to AcceptanceTester to enable retries
    step_decorators:
      - Codeception\Step\ConditionalAssertion
      - Codeception\Step\TryTo
      - Codeception\Step\Retry

actor_suffix: Tester

extensions:
  enabled: [ Codeception\Extension\RunFailed ]

params:
  - env

gherkin: [ ]

# additional paths
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs

settings:
  shuffle: false
  lint: true
```
