### ISSUE TITLE
Codeception Gitlab Pipeline Error with latest Dockerfile

### ISSUE THREAD

**Issue by nadar** [Codeception/Codeception#6472]
#### What are you trying to achieve?

We have setup codeception in gitlab pipeline:

looks something like this:

```
image:
    name: codeception/codeception
    entrypoint: [""]
  script:
    - ./vendor/bin/codecept run --debug
```

the composer.json looks something like this, its important to note that we use php 8.1

```
{
    "require": {
        "yiisoft/yii2" : "dev-master as 2.0.45",
        "notamedia/yii2-sentry": "^1.7",
        "robthree/twofactorauth": "^1.8",
        "yiisoft/yii2-redis": "^2.0",
        "yiisoft/yii2-debug": "^2.0",
        "yiisoft/yii2-gii": "^2.0",
        "ext-mongodb": "*",
        "ext-intl": "*",
        "ext-pdo": "*"
    },
    "require-dev": {
        "codeception/codeception": "^4.1",
        "codeception/module-phpbrowser": "^1.0",
        "codeception/module-asserts": "^1.0",
        "codeception/module-yii2": "^1.1",
        "codeception/module-rest": "^1.3",
        "codeception/module-db": "^1.1",
        "friendsofphp/php-cs-fixer": "^3.5",
        "phpstan/phpstan": "1.7.4"
    },
    "config": {
        "fxp-asset": {
            "enabled": false
        },
        "platform": {
            "php": "8.1"
        }
    }
}
```

#### What do you get instead?

We get `Parse error: syntax error, unexpected 'static'`

Full pipeline result is:

```
./vendor/bin/codecept run --debug
00:04
Codeception PHP Testing Framework v4.1.31 https://helpukrainewin.org/
Powered by PHPUnit 9.5.20 #StandWithUkraine
  [Connecting To Db] {"config":{"populate":true,"cleanup":true,"reconnect":true,"waitlock":0,"dump":"tests/_data/2021-08-08.sql","populator":null,"skip_cleanup_if_failed":false,"dsn":"mysql:host=.....;dbname=.....","user":"...","password":"..."},"options":[]}
Parse error: syntax error, unexpected 'static' (T_STATIC) in /builds/.............../vendor/symfony/string/UnicodeString.php on line 44
  [Db] Disconnected from default
ERROR: Job failed: exit code 1
```

**Comment by Naktibalda** [comment]
You don't have to use codeception image if you install codeception using composer.

**Comment by nadar** [comment]
Hi @Naktibalda yes you are right, but would be nice to have a codeception image with best performance from the pro's and everything is configured right (modules, etc.)

**Comment by nadar** [comment]
If someone else is looking for a gitlab pipline solution with latest php (8.1) version, this should do the trick:

```yaml
services:
  - name: mariadb
    alias: my_codeceptiondb
variables:
  MYSQL_ROOT_PASSWORD: '...'
  MYSQL_DATABASE: '...'
image: php:8.1-cli
before_script:
  - apt-get update && apt-get -y install git zlib1g-dev libpq-dev libssl-dev libxml2-dev libzip-dev unzip
  - docker-php-ext-install bcmath mysqli pdo pdo_mysql pdo_pgsql soap sockets zip
script:
  - ./vendor/bin/codecept run --debug
```
