### ISSUE TITLE
No arguments expected for "run" command, got "unit"

### ISSUE THREAD

**Issue by duzenko** [Codeception/Codeception#6496]
#### What are you trying to achieve?

No unnecessary exception breaks in debugger

I have some unit tests, such as `tests\unit\LoanPayoutServiceTest.php`
I try to debug them with CLI: `php vendor/bin/codecept run unit --debug`
Immediately I get a break inside symphony
Please add proper definitions for your InputInterface

My dev setup is VSCode + PHP Debug + XDebug + XAMPP

#### What do you get instead?

Exception in vendor\symfony\console\Input\ArgvInput.php, line 193

### Details

* Codeception version: 4.1.18
* PHP Version: 7.4.29 (cli)
* Operating System: w10
* Installation type: Composer

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    colors: true
    memory_limit: 32M
    backup_globals: false
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=e5'
            user: 'ndi'
            password: 'cba'
            populate: false
            cleanup: false
            reconnect: true
            dump: tests/_data/dump.sql

```
