### ISSUE TITLE
Alternative to Hoa/console?

### ISSUE THREAD

**Issue by jim-crawford** [Codeception/Codeception#6524]
#### What are you trying to achieve?
I am trying achieve two things, firstly, I need to find an alternative to `hoa/console` as my work will not allow us to use abandoned projects. 
#### What do you get instead?
Ive looked around for alternatives to hoa but there doesnt seem to be any issues because I suppose hoa/console still works

* Codeception version: 4
* PHP Version: 7.1 local 7.4 remote
* Operating System: Ubuntu 18
* Installation type: Phar
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# suite config
suites:
    acceptance:
        actor: AcceptanceTester
        path: .
        modules:
            enabled:
                - WebDriver:
                    url: <REDACTED>
                    window_size: 1600x1400
                    retry: true
                    browser: chrome
                - \Helper\Acceptance
                
        # add Codeception\Step\Retry trait to AcceptanceTester to enable retries
        step_decorators:
            - Codeception\Step\ConditionalAssertion
            - Codeception\Step\TryTo
            - Codeception\Step\Retry
                
extensions:
    enabled: [Codeception\Extension\RunFailed]

params: 
    - env

gherkin: []    

# additional paths
paths:
    tests: tests/ccTests
    output: tests/ccTests/_output
    data: tests/ccTests/_data
    support: tests/ccTests/_support
    envs: tests/ccTests/_envs

settings:
    shuffle: false
    lint: true
```
