### ISSUE TITLE
InnerBrowser Interfaces are missing

### ISSUE THREAD

**Issue by brutto** [Codeception/Codeception#6540]
#### What are you trying to achieve?

Current project use v4 and api-tests are running well. I try to ugrade from v4 to v5. 
Update core and modules:
```
# composer.json
...
        "codeception/codeception": "^5.0",
        "codeception/module-asserts": "^3.0",
        "codeception/module-cli": "^2.0",
        "codeception/module-rest": "^3.0",
        "codeception/module-phpbrowser": "^3.0",
...
```

#### What do you get instead?

When run tests i get this error:
```bash
Fatal error: Uncaught Error: Interface "Codeception\Lib\Interfaces\Web" not found in /app/www/vendor/codeception/lib-innerbrowser/src/Codeception/Lib/InnerBrowser.php:43
```

In my test code i use self-wrote мodule based on `InnerBrowser` as `$connectionModule` for REST-module
```
# api.suite.php
...
        - \Helper\ApplicationHelper
        - REST:
            depends: \Helper\ApplicationHelper
            part: Json
            shortDebugResponse: 250
...
```

### Details

* Codeception version: 5.0
* PHP Version: 8.1
* Operating System: Alpine Linux
* Installation type: Composer
* Suite configuration:

Searching for this missing interface i found that it was presented in v4.2 (https://github.com/Codeception/Codeception/tree/4.2/src/Codeception/Lib/Interfaces), 
but missing from v5 (https://github.com/Codeception/Codeception/tree/5.0/src/Codeception/Lib/Interfaces).

Also any other InnerBrowser interface are missing too. 
Trying to find information about some kind of migrations into separate module, but found nothing. 

BTW: Thanks for you work!
