### ISSUE TITLE
Codeception 5 does not load new coverage settings from codeception.yml

### ISSUE THREAD

**Issue by Naktibalda** [Codeception/Codeception#6543]
#### What are you trying to achieve?

Enable path coverage in configuration file

```yml
coverage:
    enabled: true
    path_coverage: true
```

#### What do you get instead?

Only configuration override using parameter ` -o 'c
overage: path_coverage: true'` works.
