### ISSUE TITLE
Disable remote coverage not work

### ISSUE THREAD

**Issue by alex-ello** [Codeception/Codeception#655]
codeception.yml:

``` yml
coverage:
    enabled: true
    remote: false
```

output:

```
[ErrorException]
file_get_contents(http://localhost/c3/report/clear): failed to open str
eam: HTTP request failed! HTTP/1.1 404 Not Found
```

**Comment by etki** [comment]
2.1.2, same situation

**Comment by maxgu** [comment]
2.1.2, same situation:
```
$ vendor/bin/codecept run --coverage --coverage-html
Codeception PHP Testing Framework v2.1.2
Powered by PHPUnit 4.8.4 by Sebastian Bergmann and contributors.
Unit Tests (1) ----------------------------------------------------------------------
UnitTest\FixedAssets\Controller\User\ComputersControllerTest::testList         Ok
Functional Tests (0) ------------------------
Acceptance Tests (0) ------------------------                                                                                                                              
  [PHPUnit_Framework_Exception]                                                                                                  
  file_get_contents(http://localhost/myapp/c3/report/clear): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found  
```

**Comment by maxgu** [comment]
you get URL from acceptance suite??
when i set
```
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost:8080
```
all works

## for all: if you want use coverage? you must:
1. download and install c3.php (https://github.com/Codeception/c3), __even you use PHP internal webserver__
2. set url in `acceptance.suite.yml` like this:
```
modules:
    enabled:
        - PhpBrowser:
            url: http://localhost:8080  // url to your app
```
3. run
```
$ vendor/bin/codecept run --coverage --coverage-html
```
when you can see HTML coverage report in `tests/_output/coverage` directory.

Why url readed from `acceptance.suite.yml` ?
What i must run coverage report if in my project __not exists__ acceptance tests  ?
