### ISSUE TITLE
How to config and open Edge browser in headless mode

### ISSUE THREAD

**Issue by Dexter55555** [Codeception/Codeception#6579]
how to set up codeception headless mode for EDGE

config is set like this (just like headless mode for Chrome, where headless mode works), but tests still run in nonHeadless mode in EDGE

```
modules:
   enabled:
        - WebDriver:
      config:
        WebDriver:
          browser: MicrosoftEdge
          window_size: 1920x1080
          capabilities:
                  EdgeOptions:
                    args: [ "--headless", "--disable-gpu", "--no-sandbox" ]
                    binary: ""
```
```
* Codeception version: 5
* PHP Version: 8.1
* Operating System: win
* Installation type: Composer
