### ISSUE TITLE
D:\GitHub\demo\runtime/tests/_output\c3tmp/codecoverage.serialized does not exist.

### ISSUE THREAD

**Issue by terabytesoftw** [Codeception/Codeception#6583]
```
actor: CliTester
modules:
  enabled:
    - Asserts
    - Cli
  step_decorators: ~
```
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Codeception PHP Testing Framework v5.0.3 https://helpukrainewin.org

[1mApp\Tests.Acceptance Tests (16) [22m-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: [32mPhpBrowser, \App\Tests\Helper\Acceptance[39m
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[35;1mBlogPageCest:[39;22m Test blog page
Signature: [32mApp\Tests\Acceptance\BlogPageCest:testBlogPage[39m
Test: [32mtests\Acceptance\BlogPageCest.php:testBlogPage[39m
[33mScenario --[39m
[36m  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testBlogPage%22%2C%22CodeCoverage_Suite%22%3A%22App%5C%5CTests.Acceptance%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=127.0.0.1; path=/; httponly"][39m
[1m I [22mam on page "/blog"
[36m  [Request Headers] [][39m
[36m  [Page] /blog[39m
[36m  [Response] 200[39m
[36m  [Request Cookies] {"CODECEPTION_CODECOVERAGE":"{"CodeCoverage":"testBlogPage","CodeCoverage_Suite":"App\\Tests.Acceptance","CodeCoverage_Config":null}"}[39m
[36m  [Response Headers] {"Host":["127.0.0.1:8080"],"Date":["Fri, 30 Sep 2022 18:28:53 GMT"],"Connection":["close"],"Cache-Control":["public, max-age=3600"],"Last-Modified":["Fri, 30 Sep 2022 18:28:53 GMT"],"X-Debug-Id":["63373565500340.34359430"],"X-Debug-Link":["/debug/api/view/63373565500340.34359430/"],"Set-Cookie":["PHPSESSID=p8688pf5u0hsmpp64chse8bkkombvfecgn8ve32lnkan42ue; Domain=127.0.0.1; Path=/; HttpOnly; SameSite=Lax"],"Content-Type":["text/html; charset=UTF-8"],"Content-Length":["5234"]}[39m
[36m  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testBlogPage%22%2C%22CodeCoverage_Suite%22%3A%22App%5C%5CTests.Acceptance%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=127.0.0.1; path=/; httponly","PHPSESSID=p8688pf5u0hsmpp64chse8bkkombvfecgn8ve32lnkan42ue; domain=127.0.0.1; path=/; httponly; samesite=Lax"][39m
[1m [22mI expect to see blog page.
[36m  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testBlogPage%22%2C%22CodeCoverage_Suite%22%3A%22App%5C%5CTests.Acceptance%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=127.0.0.1; path=/; httponly","PHPSESSID=p8688pf5u0hsmpp64chse8bkkombvfecgn8ve32lnkan42ue; domain=127.0.0.1; path=/; httponly; samesite=Lax"][39m
[1m I [22msee "Blog"
[36m  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testBlogPage%22%2C%22CodeCoverage_Suite%22%3A%22App%5C%5CTests.Acceptance%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=127.0.0.1; path=/; httponly","PHPSESSID=p8688pf5u0hsmpp64chse8bkkombvfecgn8ve32lnkan42ue; domain=127.0.0.1; path=/; httponly; samesite=Lax"][39m
[1m I [22msee "No records"
[36m  [Cookie Jar] ["CODECEPTION_CODECOVERAGE=%7B%22CodeCoverage%22%3A%22testBlogPage%22%2C%22CodeCoverage_Suite%22%3A%22App%5C%5CTests.Acceptance%22%2C%22CodeCoverage_Config%22%3Anull%7D; domain=127.0.0.1; path=/; httponly","PHPSESSID=p8688pf5u0hsmpp64chse8bkkombvfecgn8ve32lnkan42ue; domain=127.0.0.1; path=/; httponly; samesite=Lax"][39m
[32;1m PASSED [39;22m

In LocalServer.php line 163:

  [RuntimeException]
  Code coverage file D:\GitHub\demo\runtime/tests/_output\c3tmp/codecoverage.serialized does not exist


Exception trace:
  at D:\GitHub\demo\vendor\codeception\codeception\src\Codeception\Coverage\Subscriber\LocalServer.php:163
 Codeception\Coverage\Subscriber\LocalServer->afterSuite() at D:\GitHub\demo\vendor\symfony\event-dispatcher\EventDispatcher.php:230
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at D:\GitHub\demo\vendor\symfony\event-dispatcher\EventDispatcher.php:59
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at D:\GitHub\demo\vendor\codeception\codeception\src\Codeception\SuiteManager.php:150
 Codeception\SuiteManager->run() at D:\GitHub\demo\vendor\codeception\codeception\src\Codeception\Codecept.php:260
 Codeception\Codecept->runSuite() at D:\GitHub\demo\vendor\codeception\codeception\src\Codeception\Codecept.php:216
 Codeception\Codecept->run() at D:\GitHub\demo\vendor\codeception\codeception\src\Codeception\Command\Run.php:648
 Codeception\Command\Run->runSuites() at D:\GitHub\demo\vendor\codeception\codeception\src\Codeception\Command\Run.php:469
 Codeception\Command\Run->execute() at D:\GitHub\demo\vendor\symfony\console\Command\Command.php:291
 Symfony\Component\Console\Command\Command->run() at D:\GitHub\demo\vendor\symfony\console\Application.php:1002
 Symfony\Component\Console\Application->doRunCommand() at D:\GitHub\demo\vendor\symfony\console\Application.php:299
 Symfony\Component\Console\Application->doRun() at D:\GitHub\demo\vendor\symfony\console\Application.php:171
 Symfony\Component\Console\Application->run() at D:\GitHub\demo\vendor\codeception\codeception\src\Codeception\Application.php:112
 Codeception\Application->run() at D:\GitHub\demo\vendor\codeception\codeception\app.php:45
 {closure}() at D:\GitHub\demo\vendor\codeception\codeception\app.php:46
 require() at D:\GitHub\demo\vendor\codeception\codeception\codecept:7
 include() at D:\GitHub\demo\vendor\bin\codecept:120

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--phpunit-xml [PHPUNIT-XML]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--shard SHARD] [--filter FILTER] [--grep GREP] [--bootstrap [BOOTSTRAP]] [--no-redirect] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-cobertura [COVERAGE-COBERTURA]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast [FAIL-FAST]] [--no-rebuild] [--seed SEED] [--no-artifacts] [--] [<suite> [<test>]]


```
> Provide test source code if related

### Details

* Codeception version: 5.0.3
* PHP Version: 8.0
* Operating System: ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

codeception.yml
```yml
namespace: App\Tests
paths:
    tests: tests
    output: runtime/tests/_output
    data: runtime/tests/_data
    support: tests/_support
    envs: tests/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
settings:
    suite_class: \PHPUnit_Framework_TestSuite
    memory_limit: 1024M
    colors: true
coverage:
    enabled: true
    whitelist:
        include:
            - src/*
        exclude:
            - src/Asset/*
```

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - PhpBrowser:
            url: http://127.0.0.1:8080
        - \App\Tests\Helper\Acceptance
    step_decorators: ~
```

```yml
actor: CliTester
modules:
  enabled:
    - Asserts
    - Cli
  step_decorators: ~
```

```yml
# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make application process them
# Include one of framework modules (Symfony2, Yii2, Laravel5, Phalcon4) to use it
# Remove this suite if you don't use frameworks

actor: FunctionalTester
modules:
    enabled:
        - PhpBrowser:
            url: http://127.0.0.1:8080
        # add a framework module here
        - \App\Tests\Helper\Functional
    step_decorators: ~
```

```yml
# Codeception Test Suite Configuration
#
# Suite for unit or integration tests.

actor: UnitTester
modules:
    enabled:
        - Asserts
        - \App\Tests\Helper\Unit
    step_decorators: ~     
```

I have searched to solve the problem but it is strange, repository: https://github.com/yiisoft/app
