### ISSUE TITLE
Untyped method arguments in Cest format are deprecated since Codeception 5.0.0

### ISSUE THREAD

**Issue by iBotPeaches** [Codeception/Codeception#6588]
#### What are you trying to achieve?

A warning-less build.

#### What do you get instead?

```bash
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
11x DEPRECATION: Untyped method arguments in Cest format are deprecated since Codeception 5.0.0 and will be removed in 6.0.0 /code/tests/Support/Helper/LoginHelperTrait.php:21
11x DEPRECATION: Untyped method arguments in Cest format are deprecated since Codeception 5.0.0 and will be removed in 6.0.0 /code/tests/Support/Helper/LoginHelperTrait.php:40

Time: 00:17.768, Memory: 66.00 MB

OK (11 tests, 44 assertions)
root@590cd8068040:/code# 

```

```php
    public function _before(AcceptanceTester|FunctionalTester $I): void // line 21
    {
       //
    }
    public function _after(AcceptanceTester|FunctionalTester $I): void // line 40
    {
        $I->cleanFixtures([AuthAssignmentFixture::class, UserFixture::class, ProfileFixture::class, DeploymentFixture::class]);
    }
```

 * Unless I'm misunderstanding these warnings, these method arguments are clearly typed as well as the return.
 
### Details

* Codeception version: 5.0.3
* PHP Version: 8.0.23
* Operating System: linux
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
namespace: Tests
support_namespace: Support
actor_suffix: Tester
bootstrap: _bootstrap.php
paths:
  tests: tests
  output: tests/_output
  data: tests/Support/Data
  support: tests/Support
params:
  - .env
modules:
  config:
    Yii2:
      configFile: 'config/test-web.php'
    Db:
      dsn: '%DB_TEST_DSN%'
      user: '%DB_USERNAME%'
      password: '%DB_PASSWORD%'
coverage:
  enabled: true
  low_limit: 30
  high_limit: 60
  include:
    - controllers/*
    - components/*
    - extensions/*
    - models/*
  exclude:
    - models/base/*

```
