### ISSUE TITLE
Can not override a config option from the command line in a suite

### ISSUE THREAD

**Issue by schmunk42** [Codeception/Codeception#6613]
#### What are you trying to achieve?

I want to override a config option from the command line in a suite.
In my case actually the base-URL for the WebDriver.

#### What do you get instead?

```bash
codecept config:validate -o 'foo: bar'

root@de43a6b7a5fc:/project/tests# codecept config:validate -o 'foo: bar'
Validating global config... foo: bar
Ok
------------------------------

Codeception Config:

Array
(
    foo => bar
    actor => Test
[...]
```
The above works, I can see foo: bar in the output, it's also shown in the first line.

```bash
codecept config:validate -o 'foo: bar' idp

root@de43a6b7a5fc:/project/tests# codecept config:validate -o 'foo: bar' idp
Validating idp config... Ok
------------------------------

idp Suite Config:
[...]
```

No override is applied, I tried several different formats eg. `modules: config: ...`, `env: chrome: modules: ...`

### Details

* Codeception version: tested latest version for v3, v4, v5 (Docker image) - output above is from 5.0.5
* Suite configuration:

```yml
class_name: XyzTester
modules:
    enabled:
        - WebDriver
        - Asserts
        - Helper\Xyz
    config:
        WebDriver:
            host: chrome
            url: https://www-test.mydomain.de
            browser: chrome
            port: 4444
            window_size: 1024x768
            restart: true
env:
    chrome:
        modules:
            config:
                WebDriver:
                    browser: 'chrome'
                    host: chrome
                    window_size: 1440x960

    firefox:
    # nothing changed
```

Related issues:
- https://github.com/Codeception/Codeception/issues/4102
- https://github.com/Codeception/Codeception/issues/5915
- https://github.com/Codeception/Codeception/pull/6536
- https://github.com/Codeception/Codeception/pull/6452
