### ISSUE TITLE
Notice: Undefined index: convert_deprecations_to_exceptions

### ISSUE THREAD

**Issue by siggi-k** [Codeception/Codeception#6653]
Hello, I got an error message: "Notice: Undefined index: convert_deprecations_to_exceptions in /app/modules/objects/_ext/composer/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php on line 62"

#### What are you trying to achieve?
![Undefined index](https://user-images.githubusercontent.com/43443582/224672663-5cf49ef6-d8fd-4a4b-a813-4eb6ee6feaaa.png)

I ran a CodeceptionCest.
Test was successful, but this error message bothers me.

### Details

```yml
...
    "require": {
        "php": "^5.6",
        "ext-json": "*",
        "ext-soap": "*",
        "ext-pdo": "*",
        "ext-curl": "*",
        "ext-intl": "*",

        "smarty/smarty": "~3.1.33",
        "mikehaertl/phpwkhtmltopdf": "~2.2.1",
        "jejik/mt940": "0.3",
        "pear/xml_serializer": "0.21.0",
        "zendframework/zendframework1": "^1.12",

    },
    "require-dev": {
        "roave/security-advisories": "dev-master",

        "codeception/module-asserts": "^1.0",
        "codeception/module-phpbrowser": "^1.0",
        "codeception/module-db": "^1.0",
        "codeception/module-rest": "^1.3",
        "codeception/module-webdriver": "^1.0",
        "testomatio/reporter": "~0.1.6",
        "nategood/httpful": "~0.2.20"
    },
    "autoload-dev": {
        "psr-4": {
            "tests\\": "tests/"
        }
    }
```
