### ISSUE TITLE
Cannot call debugWebDriverLogs() in W3C mode

### ISSUE THREAD

**Issue by mbrodala** [Codeception/Codeception#6677]
#### What are you trying to achieve?

Debug a failing test or manually call `debugWebDriverLogs()`.

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
   I debug web driver logs 
  Unable to retrieve Selenium logs : unknown command: Cannot call non W3C standard command while in W3C mode
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: v5.0.10
* PHP Version: 8.1
* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
```
codeception/codeception       5.0.10 BDD-style testing framework
codeception/lib-asserts       2.1.0  Assertion methods used by Codeception core and Asserts module
codeception/lib-innerbrowser  4.0.0  Parent library for all Codeception framework modules and PhpBrowser
codeception/lib-web           1.0.1  Library containing files used by module-webdriver and lib-innerbrowser or module-phpbrowser
codeception/lib-xml           1.0.1  Files used by module-rest and module-soap
codeception/module-asserts    3.0.0  Codeception module containing various assertions
codeception/module-db         3.1.0  DB module for Codeception
codeception/module-doctrine2  3.0.3  Doctrine2 module for Codeception
codeception/module-filesystem 3.0.0  Codeception module for testing local filesystem
codeception/module-phpbrowser 3.0.0  Codeception module for testing web application over HTTP
codeception/module-rest       3.3.2  REST module for Codeception
codeception/module-sequence   3.0.0  Sequence module for Codeception
codeception/module-symfony    3.1.1  Codeception module for Symfony framework
codeception/module-webdriver  4.0.0  WebDriver module for Codeception
codeception/stub              4.1.0  Flexible Stub wrapper for PHPUnit's Mock Builder
```
* Suite configuration:

```yml
...

modules:
    enabled:
        - ...
        - WebDriver:
            url: '%WEBDRIVER_URL%'
            host: '%WEBDRIVER_HOST%'
            browser: '%WEBDRIVER_BROWSER%'
            window_size: 1024x768
            debug_log_entries: 15
            log_js_errors: true
        - ...
```
* Chrome: using `selenium/standalone-chrome:4.10.0` Docker image
