### ISSUE TITLE
Use shard option during tests with dataProvider

### ISSUE THREAD

**Issue by michalpotasiakdroptica** [Codeception/Codeception#6689]
#### What are you trying to achieve?

I try tu use shard option during tests with dataProvider. I have ony one test with many examples ad I want to split them to several threads.

#### What do you get instead?

All test run in first thread (--shard 1/3). Other threads are empty

### Details

* Codeception version:5.0.11
* PHP Version:8.1
* Operating System:Ubuntu 20.04
* Installation type: Composer
* List of installed packages (`composer show`)
```json
                "codeception/codeception": "^5.0",
		"codeception/module-webdriver": "3.2.1",
		"codeception/module-phpbrowser": "^3.0",
		"codeception/visualception": "v5.0.0"
```
* Suite configuration:

```yml
actor: CompareTester
step_decorators:
  - \Codeception\Step\TryTo
  - \Codeception\Step\Retry
modules:
    enabled:
        - Tests\Support\Helper\Compare
        - Tests\Support\Helper\DrupalHelper
        - Tests\Support\Helper\PageLoad
        - WebDriver:
             host: selenium-hub
             url: http://apache_1
             auth_timeout: 1200
             browser: chrome
             restart: false
             curl:
                 CURLOPT_TIMEOUT: 1200
        - VisualCeption:
            referenceImageDir: "./../../_output/Visualception/"
            maximumDeviation: 0                                 
            saveCurrentImageIfFailure: true  
            report: true
            templateFile: "/app/build/tests/tests/test_template/custom_template.php"
```
