### ISSUE TITLE
How to Allow Self-signed Certificate with PhpBrowser?

### ISSUE THREAD

**Issue by blueblakk** [Codeception/Codeception#6692]
#### What are you trying to achieve?

I'm trying to run acceptance tests with the REST module depending on PhpBrowser through a URL with a self-signed certificate.

#### What do you get instead?

```
Failed to connect to localhost port 443 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://localhost/api/v1/test
```

When I then run to get some more details from cURL:

```
curl --ipv4 -v https://localhost/api/v1/test
```

The output ends with:

```
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html
```

### Details

* Codeception version: 5.0.7
* PHP Version: 8.2.10
* Operating System: MacOS Ventura 13.5.2
* Installation type: Composer
* Suite configuration:

```yml
actor: AcceptanceTester
modules:
  enabled:
    - REST:
        url: https://%PROXY_SERVER_NAME%
        depends: PhpBrowser
        part: Json
  step_decorators: ~
```
