### ISSUE TITLE
SSL CA issue

### ISSUE THREAD

**Issue by sachitsac** [Codeception/Codeception#671]
Hi Guys,

I am having an issue with adding ssl ca cert. When i provide the ca file using the curl options, the handshake fails with the error message: 

```
Provided URL can't be accessed by this driver.[curl] 35: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca
```

This happens when i install codeception using composer. When i use the phar file, i get a different error:

```
copy(phar:///home/ubuntu/apitests_bak/codecept.phar/vendor/guzzle/http/Guzzle/Http/Resources/cacert.pem): failed to open stream: phar error: "vendor/guzzle/http/Guzzle/Http/Resources/cacert.pem" is no  
  t a file in phar "/home/ubuntu/apitests_bak/codecept.phar"
```

Here's my api test configuration that defines the CA and certs:

``` yml
class_name: ApiGuy
modules:
    enabled: [PhpBrowser, REST]
    config:
      PhpBrowser:
       url: https:/localhost/v2/
       curl: 
         CURLOPT_CAPATH: /path_to_ca_certs/
         CURLOPT_SSLCERT: /path_to_certs/client.pem
         CURLOPT_SSLCERTPASSWD: xxxxxxxx
         CURLOPT_SSLKEY: /path_to_certs/client.key
         CURLOPT_SSLKEYPASSWD: xxxxxxxx
         CURLOPT_SSL_VERIFYPEER: true
         CURLOPT_SSL_VERIFYHOST: false
         #CURLOPT_VERBOSE: true
      REST:
       url: https:/localhost/v2/
       curl:
         CURLOPT_CAPATH: /path_to_ca_certs/
         CURLOPT_SSLCERT: /path_to_certs/client.pem
         CURLOPT_SSLCERTPASSWD: xxxxxxxx
         CURLOPT_SSLKEY: /path_to_certs/client.key
         CURLOPT_SSLKEYPASSWD: xxxxxxxx
         CURLOPT_SSL_VERIFYPEER: true
         CURLOPT_SSL_VERIFYHOST: false
         #CURLOPT_VERBOSE: true
```

Now, i was able to resolve the issue by adding the ca to the following path:

``` bash
/vendor/guzzle/http/Guzzle/Http/Resources/cacert.pem
```

But i don't feel this is the right solution. Do we have some way of providing the CA file either using curl options or some other way? As if i am using the phar file, then its not possible unless i compile a phar myself.

Any help is much appreciated.

Cheers.
