### ISSUE TITLE
Call to srand() with non-int fails with PHP < 8.3

### ISSUE THREAD

**Issue by fulstadev** [Codeception/Codeception#6717]
#### What are you trying to achieve?

I'm trying to run Codeception tests within PHP code, using 

```
$codecept = new Codecept();

$codecept->run(
            suite : 'Acceptance',
            test  : 'SampleCest'
);
```

To run a Codeception Acceptance test at a specific moment (in between two integration tests currently written in PHP).

#### What do you get instead?

If your PHP version is below 8.3, the call to `srand($this->options['seed']);` within `Codecept::runSuite()` fails, as `seed` is in this scenario not an `int`. As soon as you upgrade your PHP to 8.3, that error disappears and the Acceptance test completes successfully without any issue (supposingly due to the fact that the signature of `srand()` accepts `null` from upon PHP `8.3`?).

As I'm new to Codeception, please let me know if I'm misunderstanding something / if it's better to dispatch Acceptance tests from Codeception in another way via PHP.

* Codeception version: 5.0.12
* PHP Version: 8.3.0 (now, failed with 8.2.12 in above-mentioned way)
* Operating System: macOS
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WebDriver or PhpBrowser.
# If you need both WebDriver and PHPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
              url: 'https://{uname}:{pword}@mydom.org'
              browser: chrome
# add Codeception\Step\Retry trait to AcceptanceTester to enable retries
step_decorators:
    - Codeception\Step\ConditionalAssertion
    - Codeception\Step\TryTo
    - Codeception\Step\Retry
```
