### ISSUE TITLE
Can't change user agent for firefox/geckodriver

### ISSUE THREAD

**Issue by jcvignoli** [Codeception/Codeception#6732]
I'm trying to set a specific User-Agent in geckodriver for the sake of my tests. But I can't find how to properly set that option in yml settings.

Is there any way to change for firefox the user agent?

* Codeception version: 5.1
* PHP Version: 8.2
* Operating System: Ubuntu
* Installation type: Composer
* Suite configuration:

```yml
   wpfirefox:
       modules:
          enabled:
              config:
                 WPWebDriver:
                     url: '%TEST_LOCAL_WP_URL%'
                     adminUsername: '%TEST_WP_ADMIN_USERNAME%'
                     adminPassword: '%TEST_WP_ADMIN_PASSWORD%'
                     adminPath: '%TEST_WP_ADMIN_PATH%'
                     browser: firefox
                     path: ''
                     window_size: 1024x768
                     capabilities:
                         moz:firefoxOptions:
                             args: ["-user-agent=wp-browser", "-headless"]
                             prefs:
                                intl.accept_languages: "fr-FR"
```
