### ISSUE TITLE
[JsonException] Non-backed enums have no default serialization

### ISSUE THREAD

**Issue by innerfly** [Codeception/Codeception#6753]
#### What are you trying to achieve?
Run test with dataprovider wich contains non-backed enum

#### What do you get instead?

When run unit tests and some test is fail, console output get an extra exception in addition to main error:   
> [JsonException] Non-backed enums have no default serialization  
  
I have explored this and found that exception is thrown for test with dataprovider, contained non-backed enums in example case. When run separately, this test works correctly.
I have debuged PHPUnit and then Codecepton and found place where exception is thow: it is `json_encode()` call in `\Codeception\Test\Descriptor::getTestSignatureUnique()` class. When `json_encode()` try to serialize non-backed enum wich is not serializable, it thows such exception. I assume there should be added checking if example data is serializable.

### Details

* Codeception version: 5.1.2
* PHP Version: 8.2.18
* Operating System: Ubuntu 20.04.6 LTS
* Installation type: Composer
* Suite configuration:

```yml
actor: UnitTester
bootstrap: _bootstrap.php
modules:
    enabled:
        - Mockery
        - \App\Tests\Helper\SymfonyHelper:
              app_path: 'src'
              environment: 'test'
              debug: false
              rebootable_client: false
```
