### ISSUE TITLE
session not created: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by jerome2710** [Codeception/Codeception#6781]
#### What are you trying to achieve?

We would like to run Selenium tests in our Symfony project with Codeception. Selenium, Chrome and the Chrome driver are installed through Puppet on our Debian server.

Selenium is running standalone through a service:

```bash
root@web1:~# service selenium status
● selenium.service - Selenium Server
     Loaded: loaded (/etc/systemd/system/selenium.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2024-08-20 09:58:18 UTC; 1s ago
   Main PID: 212389 (java)
      Tasks: 28 (limit: 9526)
     Memory: 110.4M
        CPU: 2.209s
     CGroup: /system.slice/selenium.service
             └─212389 /bin/java -jar /opt/selenium/selenium-server-standalone.jar standalone

Aug 20 09:58:18 XXXXXX systemd[1]: Started Selenium Server.
Aug 20 09:58:19 XXXXXX java[212389]: 09:58:19.450 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
Aug 20 09:58:19 XXXXXX java[212389]: 09:58:19.458 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
```

Chrome and the Chrome driver have matching versions:

```bash
root@web1:~# google-chrome --version
Google Chrome 127.0.6533.119 

root@web1:~# chromedriver --version
ChromeDriver 127.0.6533.119 (bdef6783a05f0b3f885591e7d2c7b2aec1a89dea-refs/branch-heads/6533@{#1999})
```

And we configured the `tests/acceptance.suite.yml`:

```yaml
modules:
    enabled:
        - WebDriver
    config:
        WebDriver:
            url: 'https://ourdomain.tld'
            browser: chrome
            window_size: 1920x4000
            capabilities:
                goog:chromeOptions:
                    args: ["--disable-gpu", "--disable-dev-shm-usage", "--headless", "--disable-extensions", "--verbose", "--whitelisted-ips=''", "--ignore-certificate-errors" ]
```

#### What do you get instead?

But when running the tests, Codeception fails immediately:

```bash
[Facebook\WebDriver\Exception\SessionNotCreatedException] Could not start a new session. Error while creating session with the driver service. Stopping driver service: Could not start a new session. Response code 500. Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) 
Host info: host: 'XXXXXX', ip: 'XXXXXX'
Build info: version: '4.23.0', revision: '4df0a231af'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-28-cloud-amd64', java.version: '11.0.24'
Driver info: driver.version: unknown
Build info: version: '4.23.0', revision: '4df0a231af'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.0-28-cloud-amd64', java.version: '11.0.24'
Driver info: driver.version: unknown  
```

What are we missing?

### Details

* Codeception version: 4.2.2
* PHP Version: PHP 8.1
* Operating System: Debian Linux 11 Bullseye
* Installation type: Composer
