### ISSUE TITLE
Using Recorder make acceptPopup() fail

### ISSUE THREAD

**Issue by jcvignoli** [Codeception/Codeception#6819]
Using this config:

```
extensions:
    enabled:
      - Codeception\Extension\Recorder
    config:
      Codeception\Extension\Recorder:
          module: lucatume\WPBrowser\Module\WPWebDriver
          delete_successful: false
```

Makes `$I->acceptPopup();` to fail.

If I deactivate the recorder, the method is successfull.
