### ISSUE TITLE
`acceptInsecureCerts: true` not working

### ISSUE THREAD

**Issue by flowl** [Codeception/Codeception#6823]
Using `docker`, `selenium-standalone`, `codeception`, `selenium-chrome`:

```
browser:
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
```

```
actor: AcceptanceTester
modules:
    enabled:
        -   WebDriver:
                host: browser
                baseUrl: 'https://caddy/'
                url: 'https://caddy/'
                window_size: 1920x1024
                browser: chrome
                request_timeout: 10
                capabilities:
                    acceptInsecureCerts: true
                    goog:chromeOptions:
                        args: [ "--headless", "--disable-gpu", "--ignore-certificate-errors", "--test-type", "--allow-insecure-localhost", "--ignore-urlfetcher-cert-requests" ]
```

Using `http` or `https` makes no difference.

    /srv/app # vendor/bin/codecept run Acceptance features/test.feature

```
 Test  tests/Acceptance/features/test.feature:test starts the test
                                                                                                                                          
  [Facebook\WebDriver\Exception\UnknownErrorException] unknown error: net::ERR_SSL_PROTOCOL_ERROR
  (Session info: chrome=132.0.6834.110)  
                                                                                                                                          

Scenario Steps:

 4. $I->amOnPage("/login") at tests/Support/AcceptanceTester.php:34
```

Please advice me how to make chrome accept the invalid certificate for my dev box.
