### ISSUE TITLE
Codeception will not connect to Selenium 2

### ISSUE THREAD

**Issue by azngeek** [Codeception/Codeception#692]
Hello,

it seems like, codeception has some problems on connecting to the Selenium 2 Server. I use Selenium as a Grid.

```
java -jar /opt/selenium/selenium-server-standalone-2.37.0.jar -role hub
```

My Clients are connected as nodes

```
java -jar selenium-server-standalone-2.37.0.jar -role node -hub http://192.168.162.134:4444/grid/register
```

My Config is 

```
class_name: WebGuy
modules:
    enabled: [Selenium2]
    config:
     Selenium2:
             url: 'http://hackathon.vm/'
             browser: firefox
             host: '192.168.162.134'
             port: 4444
             capabilities:
                 unexpectedAlertBehaviour: 'ignore'
```

I know that the node/hub configuration works as i currently test my application via javascript using node.js and webdriverjs. I can also see that Codeception requests a connection at the hub:

```
INFO: Got a request to create a new session: {platform=ANY, browserVersion=9, browserName=firefox, deviceType=tablet, name=Codeception Test, selenium-version=2.31.0, browser=firefox, deviceOrientation=portrait, unexpectedAlertBehaviour=ignore, version=9}
```

Is anybody here using a similar setup? 

Regards
