### ISSUE TITLE
Codeception WebDriver Implementation for clicks different than native Webdriver

### ISSUE THREAD

**Issue by azngeek** [Codeception/Codeception#706]
Hello,

according to the documentation at http://codeception.com/docs/modules/WebDriver#click, seleting an element using this command should work:

```
// XPath
$I->click("//label[@id='519']"); 
```

But it does not work. I have to use the native WebDriver-Implementation instead. Does anyone has an idea? 

```
$I->executeInSelenium(function(\WebDriver $webDriver) {
        $element=$webDriver->findElement(WebDriverBy::xpath("//label[@id='519']"));
        $element->click();
        $this->assertEquals("135 cm", $element->getText());
    });
```

My Config: (Codeception version 1.8.0.1)

```

class_name: WebGuy
modules:
    enabled:
      - WebDriver
    config:
     WebDriver:
             url: 'http://dev.waketoolz.de/'
             browser: firefox
             host: '192.168.162.134'
             port: 4444
             wait: 10
             capabilities:
                 unexpectedAlertBehaviour: 'accept'
```

The HTML-Snippet

```
<label class="label-radio-configurable" id="519" style="width: 36px;">
    <input type="radio" name="super_attribute[145]" id="attribute145" class="validate-custom-configurable" value="98">135 cm
</label>
```
