### ISSUE TITLE
Setting phantomjs/WebDriver useragent

### ISSUE THREAD

**Issue by precariouspanther** [Codeception/Codeception#713]
Hey, haven't been able to set the useragent for phantomjs using the new webdriver via capabilities. 

acceptance.suite.yml is as follows:

```
    config:
        WebDriver:
            url: 'http://build2.domain/'
            browser: 'phantomjs'
            port: 9988
            delay: 200
            wait: 10
            capabilities:
              userAgent: "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1667.0 Safari/537.36"
```

Any suggestions?
