### ISSUE TITLE
WebDriver seeResponseCodeIs missing?

### ISSUE THREAD

**Issue by lordlele** [Codeception/Codeception#739]
In PhpBrowser module there's the method **seeResponseCodeIs** but there isnt in WebDriver module.

I'm missing something?

For now, I have resolved with this configuration in acceptance.suite.xml:

```
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebDriver
        - WebHelper
    config:
        PhpBrowser:
            url: 'http://myurl.localhost'
            curl:
               CURLOPT_RETURNTRANSFER: true
               CURLOPT_TIMEOUT: 10 
        WebDriver:
             url: 'http://myurl.localhost'
             browser: 'firefox'
```

But I'm not sure this is the correct way.
