### ISSUE TITLE
Unit + Acceptance test and code coverage

### ISSUE THREAD

**Issue by lordlele** [Codeception/Codeception#763]
Hi,
I have successfully used the `c3.php` file for code coverage for acceptance tests, however I must use a _strange_ configuration, otherwise it's not working.

With this config, coverage works only for unit test:

**codeception.yml**

```
coverage:
    enabled: true
    whitelist:
        include: 
            - protected/commands/*
            - protected/components/*
            - protected/config/*
            - protected/controllers/*
            - protected/extensions/*
            - protected/messages/*
            - protected/migrations/*
            - protected/models/*
            - protected/modules/*
            - protected/views/*
    blacklist:
        include:
            - protected/data/*
            - protected/node/*
            - protected/gii/*
            - protected/runtime/*
            - vendor/*
            - tests/*
            - bower_components/*
```

With this configuration, coverage works for both unit and acceptance and merge of coverage results will be done successfully:

**codeception.yml**

```
coverage:
    enabled: true
    whitelist:
        include: 
            - protected/commands/*
            - protected/components/*
            - protected/config/*
            - protected/controllers/*
            - protected/extensions/*
            - protected/messages/*
            - protected/migrations/*
            - protected/models/*
            - protected/modules/*
            - protected/views/*
    blacklist:
        include:
            - protected/data/*
            - protected/node/*
            - protected/gii/*
            - protected/runtime/*
            - vendor/*
            - tests/*
            - bower_components/*
```

**unit.suite.yml**

```
coverage:
    enabled: true
    whitelist:
        include: 
            - protected/commands/*
            - protected/components/*
            - protected/config/*
            - protected/controllers/*
            - protected/extensions/*
            - protected/messages/*
            - protected/migrations/*
            - protected/models/*
            - protected/modules/*
            - protected/views/*
    blacklist:
        include:
            - protected/data/*
            - protected/node/*
            - protected/gii/*
            - protected/runtime/*
            - vendor/*
            - tests/*
            - bower_components/*
```

**acceptance.suite.yml**

```
coverage:
    enabled: true
    remote: true
    whitelist:
        include: 
            - protected/commands/*
            - protected/components/*
            - protected/config/*
            - protected/controllers/*
            - protected/extensions/*
            - protected/messages/*
            - protected/migrations/*
            - protected/models/*
            - protected/modules/*
            - protected/views/*
    blacklist:
        include:
            - protected/data/*
            - protected/node/*
            - protected/gii/*
            - protected/runtime/*
            - vendor/*
            - tests/*
            - bower_components/*   
```

Please note that in `acceptance.suite.yml` I must put `remote: enable` otherwise call of `/c3/report/...` dont be executed.

Is this the correct way and the correct configuration? 
Or I'm missing something?
