### ISSUE TITLE
Can't use WebDriver: Failed connect to 127.0.0.1:4444; No error

### ISSUE THREAD

**Issue by MotazG** [Codeception/Codeception#780]
Hello,
It was working a while ago but suddenly I'm having this problem.

Whenever I try to use webdriver (or Selenium2) I get a 

```
Codeception PHP Testing Framework v1.9-dev
Powered by PHPUnit 3.7.28 by Sebastian Bergmann.



  [WebDriverCurlException]
  Curl error thrown for http POST to http://127.0.0.1:4444/wd/hub/session wit
  h params: {"desiredCapabilities":{"browserName":"firefox"}}

  Failed connect to 127.0.0.1:4444; No error



run [-c|--config="..."] [--report] [--html] [--xml] [--tap] [--json] [--colors]
[--no-colors] [--silent] [--steps] [-d|--debug] [--coverage] [--no-exit] [--defe
r-flush] [-g|--group="..."] [-s|--skip="..."] [--skip-group="..."] [--env="..."]
 [suite] [test]
```

This is my acceptance.suite.yml

```
class_name: WebGuy
modules:
    enabled:
        - WebDriver
    config:
        WebDriver:
            url: 'http://localhost/laravel/warehouse/public'
            browser: firefox
```

This is my test

```
<?php
$I = new WebGuy($scenario);
$I->am('an employee');
$I->wantTo('sign in with valid account');
$I->lookForwardTo('get authintcated');
$I->amOnPage('/');
$I->seeLink('Login');
$I->click('Login');
$I->fillField('Email','name@ma.co');
$I->fillField('Password','*****');
$I->click('Sign in');
$I->wait(5000);
$I->click('#submit_approve_access');
$I->click('Back to wherever you where');
$I->seeLink('Log out');
?>
```

As I said, this was working fine before, it just suddenly stopped working.  Any ideas?

I'm running firefox 24.0
