### ISSUE TITLE
Symfony1 Module Fatal Error

### ISSUE THREAD

**Issue by nexik** [Codeception/Codeception#789]
While running acceptance tests:

PHP Fatal error:  Call to undefined method Codeception\Util\Framework::formatResponse() in /home/nexik/projects/foo/vendor/codeception/codeception/src/Codeception/Module/Symfony1.php on line 202

config file

```
class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
        - Symfony1
        - Db
    config:
        PhpBrowser:
            url: 'http://host.dev/frontend_test.php/'
        Symfony1:
            app: frontend
        Db:
            dsn: 'mysql:host=localhost;dbname=test'
            user: 'root'
            password: 'pass'
            dump: tests/_data/dump.sql
            populate: true
            cleanup: false
```
