### ISSUE TITLE
Acceptance test env name concatentation

### ISSUE THREAD

**Issue by alexwhitman** [Codeception/Codeception#794]
With an `acceptance.suite.yml` file containing:

``` yaml
class_name: WebGuy
modules:
    enabled:
        - WebDriver
    config:
        WebDriver:
            host: 'selenium-hub'
            port: 4444
            url: 'https://www.domain.com'
            browser: firefox
            wait: 10
            capabilities:
                unexpectedAlertBehaviour: 'accept'
env:
    chrome:
         modules:
            config:
                WebDriver:
                    browser: 'chrome'

    firefox:

    opera:
         modules:
            config:
                WebDriver:
                    browser: 'opera'

    phantomjs:
         modules:
            config:
                WebDriver:
                    browser: 'phantomjs'

    safari:
         modules:
            config:
                WebDriver:
                    browser: 'safari'
```

If I run the tests for all environments with `codecept run acceptance --env chrome --env firefox --env opera --env phantomjs --env safari` then I get the following output:

```
Acceptance-chrome Tests (1) ---------------------------------------------
Trying to want to check the homepage title (HomepageCept.php)       Ok
-------------------------------------------------------------------------

Acceptance-chrome-firefox Tests (1) -------------------------------------
Trying to want to check the homepage title (HomepageCept.php)       Ok
-------------------------------------------------------------------------

Acceptance-chrome-firefox-opera Tests (1) -------------------------------
Error
-------------------------------------------------------------------------

Acceptance-chrome-firefox-opera-phantomjs Tests (1) ---------------------
Trying to want to check the homepage title (HomepageCept.php)       Ok
-------------------------------------------------------------------------

Acceptance-chrome-firefox-opera-phantomjs-safari Tests (1) --------------
Trying to want to check the homepage title (HomepageCept.php)       Ok
-------------------------------------------------------------------------
```

Note how the name of each test block contains the names of the previous environments ending up with `Acceptance-chrome-firefox-opera-phantomjs-safari`.
