### ISSUE TITLE
Yii 2.0 Advanced App Functional Testing => FATAL ERROR TESTS NOT FINISHED: Class 'Yii' Not Found

### ISSUE THREAD

**Issue by deerawan** [Codeception/Codeception#832]
Hi, 

I use Yii 2.0 Advanced App and try to configure Codeception. Here is my composer.json

```
"require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
                "codeception/codeception": "*",                
    }
```

I execute codecept bootstrap and the folder tests is created. I changed the functional.suite.yml into this

```
class_name: TestGuy
modules:
    enabled: [FileSystem, TestHelper, Yii2]
    config:
        Yii2:
            entryScript: '/romawi/dodo/mabokapp/frontend/web/index.php'
            url: 'http://localhost/romawi/dodo/mabokapp/frontend/web/index.php'
```

I create one functional testing and execute codecept run command and here is the error

```
FATAL ERROR. TESTS IS NOT FINISHED
Class Yii not found
in blablabla / codeception/module/Yii2.php:70
```

I use Codeception 1.8.1

Is it a bug or something wrong with my configuration? 

Thank you :)
