### ISSUE TITLE
Access to Suite config for each suite environment from _bootstrap.php

### ISSUE THREAD

**Issue by jonphipps** [Codeception/Codeception#893]
Sorry to bother you with what is probably a dumb question...

I'm trying to check a full URI returned by an API. I have server environments setup for dev and production. 

``` yaml
env:
  dev:
    modules:
      config:
        PhpBrowser:
          url: http://rdaregistry.dev/
        REST:
          url: http://rdaregistry.dev/

  prod:
    modules:
      config:
        PhpBrowser:
          url: http://rdaregistry.info/
        REST:
          url: http://rdaregistry.info/
```

Ideally I'd be able to set the base URI to check against in the suite _bootstrap.php based on the environment I'm running in.

``` php
$this->server = \Codeception\SuiteManager::$modules['REST']->config['url'];
```

...but 'config' is protected and I'm afraid that I'm uncertain about the best way to retrieve that value. I must be missing something, but I can't see any way to get either the suite config or the `$modules['REST']->client->baseUri` which is also protected with no public access that I can find.

Any advice would be appreicated.
