### ISSUE TITLE
Symfony 2 + Codeception + Code coverage

### ISSUE THREAD

**Issue by sidorovich** [Codeception/Codeception#898]
Hi!

Codeception installed via Composer

```
"codeception/codeception": "*",
```

codeception.yml (placed in root folder in project)

```
paths:
    tests: tests
    log: tests/_log
    data: tests/_data
    helpers: tests/_helpers
settings:
    bootstrap: _bootstrap.php
    suite_class: \PHPUnit_Framework_TestSuite
    colors: true
    memory_limit: 1024M
    log: true
modules:
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=dbtest'
            user: 'dev'
            password: 'dev'
            dump: tests/_data/dbdump.sql

coverage:
    enabled: true
    remote: false
    whitelist:
        include:
            - src/*
        exclude:
            - src/*/*Bundle/Resources
            - src/*/*Bundle/Tests
            - src/*/*Bundle/Model/map
            - src/*/*Bundle/Model/om
            - src/*/*Bundle/Model/*/map
            - src/*/*Bundle/Model/*/om
```

First acceptance test

```
<?php
/** @var \Codeception\Scenario $scenario */
$I = new WebGuy($scenario);
$I->wantTo('see homepage');
$I->amOnPage('/');
$I->canSeeElement('#search-box');
$I->canSeeElement('.go-login');
$I->canSeeElement('.go-register');
```

tests/acceptance.suite.yml

```
# Codeception Test Suite Configuration

# suite for acceptance tests.
# perform tests in browser using the Selenium-like tools.
# powered by Mink (http://mink.behat.org).
# (tip: that's what your customer will see).
# (tip: test your ajax and javascript by one of Mink drivers).

# RUN `build` COMMAND AFTER ADDING/REMOVING MODULES.

class_name: WebGuy
modules:
    enabled:
        - PhpBrowser
        - WebHelper
    config:
        PhpBrowser:
            url: 'http://sitedomain.local/'
```

First run result

```
> bin/codecept run --coverage --xml --html
Codeception PHP Testing Framework v1.8.3
Powered by PHPUnit 3.7.32 by Sebastian Bergmann.

Unit Tests (0) ------------------------------
---------------------------------------------

Acceptance Tests (1) -------------------------------------------
Trying to see homepage (IsHomePageAvailableCept.php)       Ok
----------------------------------------------------------------



  [ErrorException]                                                                                                                   
  file_get_contents(http://sitedomain.local//c3/report/serialized): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found  




run [-c|--config="..."] [--report] [--html] [--xml] [--tap] [--json] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage] [--no-exit] [--defer-flush] [-g|--group="..."] [-s|--skip="..."] [--skip-group="..."] [--env="..."] [suite] [test]



Process finished with exit code 1 at 10:27:15.
Execution time: 6 065 ms.
```

Place c3.php into web directory (near app.php and app_dev.php), added into app_dev.php

```
<?php

require_once(__DIR__ . '/c3.php');

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Debug\Debug;
...
```

Run and result:

```
> bin/codecept run --coverage --xml --html
Codeception PHP Testing Framework v1.8.3
Powered by PHPUnit 3.7.32 by Sebastian Bergmann.

Unit Tests (0) ------------------------------
---------------------------------------------



  [Codeception\Exception\ModuleConfig]                                                                                                                              
  Codeception\Util\Mink module is not configured!                                                                                                                   

  Provided URL can't be accessed by this driver.[curl] 28: Operation timed out after 30027 milliseconds with 0 out of -1 bytes received [url] http://sitedomain.local  



run [-c|--config="..."] [--report] [--html] [--xml] [--tap] [--json] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage] [--no-exit] [--defer-flush] [-g|--group="..."] [-s|--skip="..."] [--skip-group="..."] [--env="..."] [suite] [test]



Process finished with exit code 1 at 10:29:42.
Execution time: 30 516 ms.
```

Any ideas? I want to get code coverage with codeception tests for Jenkins server. Have no problem with codeception when run phpunit.

nginx + php5-fpm
