### ISSUE TITLE
Db module problem

### ISSUE THREAD

**Issue by maxibello** [Codeception/Codeception#901]
Привет!
Решил по мануалу подключить Db модуль. Привожу конфиг:

```
class_name: WebGuy
modules:
    enabled:
        - WebDriver
        - WebHelper 
        - Db
    config:
        Db:
            dsn: 'mysql:host=localhost;dbname=db_name'
            user: 'root'
            password: 'muscle'
            dump: 'tests/_data/dump.sql'
            populate: true
            cleanup: false
        WebDriver:
            url: 'http://mysite.local/'
            browser: firefox
```

После добавления модуля тесты перестали запускаться:

```
Ошибка сегментирования (сделан дамп памяти)
```

Когда я поставил  populate: false, тесты заработали. Далее я попробовал в тесте использовать Db:

``` php
$I->seeInDatabase('users', array('first_name' => 'Иван', 'last_name' => 'Иванов', 'e-mail' => 'ivan@ivanov.ru'));
```

и снова получил ошибку сегментирования.

Что я делаю не так?
Вручную база ресторится без ошибок.

```
mysql -uroot -pmuscle db_name < ~/codeception/tests/_data/dump.sql
```
