### ISSUE TITLE
Codecoverage failed.

### ISSUE THREAD

**Issue by csim-sg** [Codeception/Codeception#974]
Hi,

I'm running Yii2 framework, during normal testing, everything is fine and working good. But when I run codecept with the following code, 

codecept run --coverage --html

it will produce these errors

```
  [UnexpectedValueException]                                                   
  phar error: "C:\Users\Chris Sim\AppData\Local\Temp\C39C07tmp.tar" is a corr  
  upted tar file (checksum mismatch of file "<!DOCTYPE HTML PUBLIC "-//W3C//D  
  TD HTML 3.2 Final//EN">                                                      
  <html>                                                                       
   <head>                                                                      
    <title>Index of /Antpolis C")                                              
```

Should I download anymore module or some config change to prevent this exception??

My config is as follow

```
coverage:
    enabled: true
    remote: true
    include:
          - components/*
          - config/*
          - controllers/*
          - messages/*
          - models/*
          - extensions/*
          - modules/*
          - views/*
    exclude:
        - vendor/*
        - tests/*
        - runtime/*
```
