### ISSUE TITLE
XML and HTML code coverage are not generated

### ISSUE THREAD

**Issue by elimentz** [Codeception/Codeception#986]
I am writing a Laravel 4 app which I am testing with Codeception 2.0.*[dev-master]. Whatever I do, I can't seem to get the code coverage report generated. Code coverage is definitely run though, because I get to see the final report in my console every time without fail. 

![coverage](https://cloud.githubusercontent.com/assets/1410811/2802506/280eeade-cc8f-11e3-8f0d-d9687f6d9fa2.PNG)

However, the actual HTML/XML report is missing in my _log directory:

![files](https://cloud.githubusercontent.com/assets/1410811/2802512/31a2b878-cc8f-11e3-85bf-7f5fe60b6ec8.PNG)

Below is my codeception.yml file

``` yml
actor: Guy
paths:
    tests: app/tests
    log: app/tests/_log
    data: app/tests/_data
    helpers: app/tests/_helpers
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
coverage:
    enabled: true
    whitelist:
        include:
            - app/controllers/*
            - app/models/*
            - app/presenters/*
            - app/repositories/*
            - app/services/*
```

Tried running the following:
vendor/bin/codecept run unit --coverage --xml --html
vendor/bin/codecept run unit --coverage --html
vendor/bin/codecept run unit --report --coverage --xml --html

Nothing seems to work. Not sure if it is a bug or not, but any help is appreciated
