### ISSUE TITLE
Fatal Error On PHP 5.3.* Codeception\Actor not found

### ISSUE THREAD

**Issue by charlesportwoodii** [Codeception/Codeception#987]
Hello. I'm experiencing a fatal error when attempting to run codeception on any version of PHP 5.3 (tested thus far on 5.3.10, 5.3.19, 5.3.27, and 5.3.28) when using `1.8.5` and `1.8.6-dev`. It works fine on 5.4 and 5.5 though.

Let me know if I can assist in any way by providing you with more details

---

yml

```
actor: Dev
paths:
    tests: protected/tests
    log: protected/tests/_log
    data: protected/tests/_data
    helpers: protected/tests/_helpers
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    log: true
modules:
    enabled: [PhpBrowser, WebHelper, TestHelper, Yii1, Db]
    config:
        PhpBrowser:
            url: http://localhost:8234
        Yii1:
            appPath: test.php
            url: http://localhost:8234/test.php
        Db:
            dsn: 'mysql:host=127.0.0.1;dbname=ciims_test'
            user: 'root'
            password: ''
            populate: false
            cleanup: false
```

Stack trace is as follows

```
$ ./vendor/bin/codecept run
Codeception PHP Testing Framework v1.8.6-dev
Powered by PHPUnit 3.7.35-12-ga702318 by Sebastian Bergmann.
PHP Fatal error:  Class 'Codeception\Actor' not found in /home/travis/build/charlesportwoodii/CiiMS/protected/tests/acceptance/WebDev.php on line 27
PHP Stack trace:
PHP   1. {main}() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/codecept:0
PHP   2. Symfony\Component\Console\Application->run() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/codecept:29
PHP   3. Symfony\Component\Console\Application->doRun() /home/travis/build/charlesportwoodii/CiiMS/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/travis/build/charlesportwoodii/CiiMS/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   5. Symfony\Component\Console\Command\Command->run() /home/travis/build/charlesportwoodii/CiiMS/vendor/symfony/console/Symfony/Component/Console/Application.php:894
PHP   6. Codeception\Command\Run->execute() /home/travis/build/charlesportwoodii/CiiMS/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   7. Codeception\Command\Run->runSuites() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/Command/Run.php:93
PHP   8. Codeception\Codecept->run() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/Command/Run.php:125
PHP   9. Codeception\Codecept->runSuite() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/Codecept.php:131
PHP  10. Codeception\SuiteManager->__construct() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/Codecept.php:145
PHP  11. require_once() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/SuiteManager.php:50
Fatal error: Class 'Codeception\Actor' not found in /home/travis/build/charlesportwoodii/CiiMS/protected/tests/acceptance/WebDev.php on line 27
Call Stack:
    0.0002     659688   1. {main}() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/codecept:0
    0.0310    5093928   2. Symfony\Component\Console\Application->run() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/codecept:29
    0.0353    5727536   3. Symfony\Component\Console\Application->doRun() /home/travis/build/charlesportwoodii/CiiMS/vendor/symfony/console/Symfony/Component/Console/Application.php:124
    0.0354    5727704   4. Symfony\Component\Console\Application->doRunCommand() /home/travis/build/charlesportwoodii/CiiMS/vendor/symfony/console/Symfony/Component/Console/Application.php:193
    0.0355    5727872   5. Symfony\Component\Console\Command\Command->run() /home/travis/build/charlesportwoodii/CiiMS/vendor/symfony/console/Symfony/Component/Console/Application.php:894
    0.0360    5728616   6. Codeception\Command\Run->execute() /home/travis/build/charlesportwoodii/CiiMS/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
    0.0803   10015552   7. Codeception\Command\Run->runSuites() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/Command/Run.php:93
    0.0803   10016120   8. Codeception\Codecept->run() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/Command/Run.php:125
    0.0850   10020160   9. Codeception\Codecept->runSuite() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/Codecept.php:131
    0.0860   10223096  10. Codeception\SuiteManager->__construct() /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/Codecept.php:145
    0.0888   10882320  11. require_once('/home/travis/build/charlesportwoodii/CiiMS/protected/tests/acceptance/WebDev.php') /home/travis/build/charlesportwoodii/CiiMS/vendor/codeception/codeception/src/Codeception/SuiteManager.php:50
The command "./vendor/bin/codecept run" exited with 255.
```
